### ISSUE TITLE
Nethereum is using http connection lifespan and idle timeout of 1 hour - too long

### ISSUE THREAD

**Issue by sergey-s-s** [Nethereum/Nethereum#1008]
Nethereum is using http connection leftspan of 1 hour - too high.

Despine the name (NUMBER_OF_SECONDS_TO_RECREATE_HTTP_CLIENT = 60), it is acutally the number of minutes as it is passe as 'minutes' param to TimeSpan:
see https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.RpcClient/RpcClient.cs#L73

Likely meant to pass as the last arg. Recommend to use TimeSpan.FromMinutes() or FromSeconds() rather than new() to make time unit obviously clear.

**Comment by juanfranblanco** [comment]
Changed in the latest to be more clear.  As I remember now this was done to allow very long requests (debug), although yes.. Too long.
