### ISSUE TITLE
Object reference, when contract ABI doesn't contain constructor

### ISSUE THREAD

**Issue by paradise** [Nethereum/Nethereum#101]
It is not necessary to specify default constructor in solidity contract, but `web3.Eth.DeployContract.SendRequestAsync` throws object reference if it is not specified.

**Comment by juanfranblanco** [comment]
Hi, this was done to identify if there is was a constructor input, but good point. If there is no abi it can be assumed as not required.

**Comment by juanfranblanco** [comment]
@paradise will this not solve your issue?  public Task<string> SendRequestAsync(string contractByteCode, string from, HexBigInteger gas), if not having a constructor.
