### ISSUE TITLE
Required property 'message' not found in JSON

### ISSUE THREAD

**Issue by mg1612** [Nethereum/Nethereum#1014]
Hi, 
i am receiving the folllowing error to trying to apply filter on event log

Nethereum.JsonRpc.Client.RpcClientUnknownException: 'Error occurred when trying to send rpc requests(s): eth_getLogs'
with InnerException:
JsonSerializationException: Required property 'message' not found in JSON. Path 'error', line 1, position 84.
-----------
my source code :
```
            var account = new Account(privateKey);
            var web3 = new Web3(account, url);
            var contract = web3.Eth.GetContract(abi, contractAddress);

            var mEventHandler = web3.Eth.GetEvent<CarbonCreditMintedEventDTO>(contractAddress);
            var filterAllTransferEventsForContract = mEventHandler.CreateFilterInput();
            var allTransferEventsForContract = await mEventHandler.GetAllChangesAsync(filterAllTransferEventsForContract); //EXCEPTION THROWN HERE
```
I tried several options to fetch or filter logs and events with the same message error, 
creating transactions, and querying the smart contract is working well, so no issue in the connection to the smart contract
I am using Nethereum.Web3 4.19.0
Newtonsoft.Json 13.0.3
in a .net core 6.0 web app 
my my smart contract hosted on https://rpc-mumbai.maticvigil.com

**Comment by juanfranblanco** [comment]
Hi,

Do you still have this issue? This will be due to their rpc implementation not being correct. Ill close it as it is not in the Nethereum side
