### ISSUE TITLE
Call a contract function on previous block always returns 0

### ISSUE THREAD

**Issue by nvtaveras** [Nethereum/Nethereum#102]
I'm trying to get the balance of an ERC20Token contract on a previous block (similar to the way the eth_getBalance rpc can take a block parameter).

After loading the contract and getting a reference to the function I want to call (balanceOf), I see that the CallAsync method has an overload which takes CallInput(), BlockParameter and params object[] functionInput, however when I try to pass the block number, I always get 0 as a result.

It works fine if I use the overload that only takes params object[] functionInput as arguments, I'm able to get the balance on the latest block.

It also works fine when using the Web3.Eth.GetBalance function for normal ethereum accounts, using the overload that takes the address and the block number.

Has anyone experienced something similar or has anyway to make it work?

**Comment by juanfranblanco** [comment]
@nvtaveras  I have pushed an example on how to achieve this. I will leave this open as I will add more overloads to simplify this.

**Comment by nvtaveras** [comment]
Thanks @juanfranblanco it works now. Looks my error was passing CallInput() with the default empty constructor.

**Comment by juanfranblanco** [comment]
@nvtaveras Thanks for reporting it, great feedback. I have added extra overloads now for BlockParameters and remove the ones using CallInput.

**Comment by knocte** [comment]
@juanfranblanco seems you also removed the faulty overloads? I ask because I was going to say: if the result of the call is zero when it doesn't work, it would be a bug. If it doesn't work it should throw an exception instead of giving a misleading result, right?

**Comment by juanfranblanco** [comment]
@knocte Oh no, I removed them for simplicity. There was not a bug just mainly too complex to use as you have to assign again the Contract address as To and From address. Mainly build again the CallInput. What I have done is just add extra overloads that accept a BlockParameter to simplify usage.

Based on this I am thinking of also removing eventually (maybe deprecate) the "from" parameter of functions transactions as this will use the transaction manager account address.
