### ISSUE TITLE
Nonce not getting reset

### ISSUE THREAD

**Issue by ShubhankarBanerjee87** [Nethereum/Nethereum#1030]
I am using the transaction manager from the Nethereum package to send transactions automatically. However, I am encountering an issue where multiple transactions are getting stuck, specifically up to nonce 100.

The problem is that the nonce is not resetting even after 3 days. However, when I use another wallet like Metamask, it detects the correct nonce.

Why is the nonce not resetting in the Nethereum transaction manager, and how can I resolve this issue?

**Comment by juanfranblanco** [comment]
Nethereum has an in memory nonce service, to keep track of nonces to avoid racing conditions, it does not have an expiry for this, you could change the nonce service with your own implementation, or reset it (it has a method to do so) await web3.TransactionManager.Account.NonceService.ResetNonceAsync();
