### ISSUE TITLE
Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by Skr1pt** [Nethereum/Nethereum#1033]
Hello. I try decode this input
`string data = "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000011800000000000000000000000000000000000000000000000000003bfd07bc778b9000000000000000000000000000000000000000000000000000000006605725f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000af58534093046399bb88776a3b623d640ecfbc840000000000000000000000000000000000000000000000000000000000000000206e03a58f8ddcb910ef80d95ae02e45a1bfe41c889162305151840d791a0e5e0774f930188d6c5a93f8f73bc8483ff54452495fd073409b80ad8b2d2425287e000000000000000000000000000000000000000000000000000000000000001b0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000b99e093b7e8ba2c52fec89f1d027d088000000000000000000000000013026c99250694e2cd6c37793771f2a7b2618a200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000c6848bbf000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000001c000f4f6e6427c8e85a5c6a8ac98f77bab1a517d4f7e9083188e099240ae8270b75a2ea611c5c336e9450a8a6ee5188bff52c21b6a906ba6591f95783794c052e3000000000000000000000000000000000000000000000000000000000000001b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000380000000000000000000000000000000000000000000000000000000000000046000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000000620000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000007e000000000000000000000000000000000000000000000000000000000000008c000000000000000000000000000000000000000000000000000000000000009a00000000000000000000000000000000000000000000000000000000000000a800000000000000000000000000000000000000000000000000000000000000b600000000000000000000000000000000000000000000000000000000000000c400000000000000000000000000000000000000000000000000000000000000d2000000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b9000000000000000000000000000000000000000000000000000000000000028900000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b9000000000000000000000000000000000000000000000000000000000000028900000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007d60000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000011520000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007d80000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000d6e0000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000d370000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007dd00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000f7a00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000ab400000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007ec00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b9000000000000000000000000000000000000000000000000000000000000168e00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000dc900000000000000000000000000000000000000000000000000049e57d6354000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000008370000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000038d7ea4c68000b4aab189d23834f6e5d6d9794a69b572987a8a9d80601423ec9bb68efb3a8e7a000000000000000000000000f849de01b080adc3a814fabe1e2087475cf2e35400000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000001388000000000000000000000000d823c605807cc5e6bd6fc0d7e4eea50d3e2d66cd";
 var runInput = new RunInputFunction().DecodeOutput(data);

[FunctionOutput]
public class RunInputFunction : IFunctionOutputDTO
{
    [Parameter("tuple[]", "orders", 1)]
    public List<Order> Orders { get; set; }

    [Parameter("tuple[]", "details", 2)]
    public List<SettleDetail> Details { get; set; }

    [Parameter("tuple", "shared", 3)]
    public SettleShared Shared { get; set; }

    [Parameter("bytes32", "r", 4)]
    public byte[] R { get; set; }

    [Parameter("bytes32", "s", 5)]
    public byte[] S { get; set; }

    [Parameter("uint8", "v", 6)]
    public byte V { get; set; }
}
[FunctionOutput]
public class Order : IFunctionOutputDTO
{
    [Parameter("uint256", "salt", 1)]
    public BigInteger Salt { get; set; }

    [Parameter("address", "user", 2)]
    public string User { get; set; }

    [Parameter("uint256", "network", 3)]
    public BigInteger Network { get; set; }

    [Parameter("uint256", "intent", 4)]
    public BigInteger Intent { get; set; }

    [Parameter("uint256", "delegateType", 5)]
    public BigInteger DelegateType { get; set; }

    [Parameter("uint256", "deadline", 6)]
    public BigInteger Deadline { get; set; }

    [Parameter("address", "currency", 7)]
    public string Currency { get; set; }

    [Parameter("bytes", "dataMask", 8)]
    public byte[] DataMask { get; set; }

    [Parameter("tuple[]", "items", 9)]
    public List<OrderItem> Items { get; set; }

    [Parameter("bytes32", "r", 10)]
    public byte[] R { get; set; }

    [Parameter("bytes32", "s", 11)]
    public byte[] S { get; set; }

    [Parameter("uint8", "v", 12)]
    public byte V { get; set; }

    [Parameter("uint8", "signVersion", 13)]
    public byte SignVersion { get; set; }
}
[FunctionOutput]
public class OrderItem : IFunctionOutputDTO
{
    [Parameter("uint256", "price", 1)]
    public BigInteger Price { get; set; }

    [Parameter("bytes", "data", 2)]
    public byte[] Data { get; set; }
}
[FunctionOutput]
public class SettleDetail : IFunctionOutputDTO
{
    [Parameter("uint8", "op", 1)]
    public byte Op { get; set; }

    [Parameter("uint256", "orderIdx", 2)]
    public BigInteger OrderIdx { get; set; }

    [Parameter("uint256", "itemIdx", 3)]
    public BigInteger ItemIdx { get; set; }

    [Parameter("uint256", "price", 4)]
    public BigInteger Price { get; set; }

    [Parameter("bytes32", "itemHash", 5)]
    public byte[] ItemHash { get; set; }

    [Parameter("address", "executionDelegate", 6)]
    public string ExecutionDelegate { get; set; }

    [Parameter("bytes", "dataReplacement", 7)]
    public byte[] DataReplacement { get; set; }

    [Parameter("uint256", "bidIncentivePct", 8)]
    public BigInteger BidIncentivePct { get; set; }

    [Parameter("uint256", "aucMinIncrementPct", 9)]
    public BigInteger AucMinIncrementPct { get; set; }

    [Parameter("uint256", "aucIncDurationSecs", 10)]
    public BigInteger AucIncDurationSecs { get; set; }

    [Parameter("tuple[]", "fees", 11)]
    public List<Fee> Fees { get; set; }
}
[FunctionOutput]
public class Fee : IFunctionOutputDTO
{
    [Parameter("uint256", "percentage", 1)]
    public BigInteger Percentage { get; set; }

    [Parameter("address", "to", 2)]
    public string To { get; set; }
}
[FunctionOutput]
public class SettleShared : IFunctionOutputDTO
{
    [Parameter("uint256", "salt", 1)]
    public BigInteger Salt { get; set; }

    [Parameter("uint256", "deadline", 2)]
    public BigInteger Deadline { get; set; }

    [Parameter("uint256", "amountToEth", 3)]
    public BigInteger AmountToEth { get; set; }

    [Parameter("uint256", "amountToWeth", 4)]
    public BigInteger AmountToWeth { get; set; }

    [Parameter("address", "user", 5)]
    public string User { get; set; }

    [Parameter("bool", "canFail", 6)]
    public bool CanFail { get; set; }
}`

on js example code is ```
const orderInput = ethers.utils.defaultAbiCoder.decode(
    [`tuple(tuple(uint256 salt, address user, uint256 network, uint256 intent, uint256 delegateType, uint256 deadline, address currency, bytes dataMask, tuple(uint256 price, bytes data)[] items, bytes32 r, bytes32 s, uint8 v, uint8 signVersion)[] orders, tuple(uint8 op, uint256 orderIdx, uint256 itemIdx, uint256 price, bytes32 itemHash, address executionDelegate, bytes dataReplacement, uint256 bidIncentivePct, uint256 aucMinIncrementPct, uint256 aucIncDurationSecs, tuple(uint256 percentage, address to)[] fees)[] details, tuple(uint256 salt, uint256 deadline, uint256 amountToEth, uint256 amountToWeth, address user, bool canFail) shared, bytes32 r, bytes32 s, uint8 v)`],
    input.input
)[0]
```
but i get Value was either too large or too small for an Int32 exception

**Comment by hasandogu** [comment]
We are getting the same result with all functions that return a tuple / class.

**Comment by Skr1pt** [comment]
> We are getting the same result with all functions that return a tuple / class.

no solution?

**Comment by juanfranblanco** [comment]
The function input / output needs to contain the struct.
```csharp
public static async Task Main()
	{
	
		string data = "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000011800000000000000000000000000000000000000000000000000003bfd07bc778b9000000000000000000000000000000000000000000000000000000006605725f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000af58534093046399bb88776a3b623d640ecfbc840000000000000000000000000000000000000000000000000000000000000000206e03a58f8ddcb910ef80d95ae02e45a1bfe41c889162305151840d791a0e5e0774f930188d6c5a93f8f73bc8483ff54452495fd073409b80ad8b2d2425287e000000000000000000000000000000000000000000000000000000000000001b0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000b99e093b7e8ba2c52fec89f1d027d088000000000000000000000000013026c99250694e2cd6c37793771f2a7b2618a200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000c6848bbf000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000001c000f4f6e6427c8e85a5c6a8ac98f77bab1a517d4f7e9083188e099240ae8270b75a2ea611c5c336e9450a8a6ee5188bff52c21b6a906ba6591f95783794c052e3000000000000000000000000000000000000000000000000000000000000001b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000380000000000000000000000000000000000000000000000000000000000000046000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000000620000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000007e000000000000000000000000000000000000000000000000000000000000008c000000000000000000000000000000000000000000000000000000000000009a00000000000000000000000000000000000000000000000000000000000000a800000000000000000000000000000000000000000000000000000000000000b600000000000000000000000000000000000000000000000000000000000000c400000000000000000000000000000000000000000000000000000000000000d2000000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b9000000000000000000000000000000000000000000000000000000000000028900000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b9000000000000000000000000000000000000000000000000000000000000028900000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007d60000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000011520000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007d80000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000d6e0000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000d370000000000000000000000000000000000000000000000000003e871b540c000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007dd00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000f7a00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000ab400000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000007ec00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b9000000000000000000000000000000000000000000000000000000000000168e00000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b90000000000000000000000000000000000000000000000000000000000000dc900000000000000000000000000000000000000000000000000049e57d6354000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000090085fb517a0b46676b3efc6a56e255cbd0f22b900000000000000000000000000000000000000000000000000000000000008370000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000038d7ea4c68000b4aab189d23834f6e5d6d9794a69b572987a8a9d80601423ec9bb68efb3a8e7a000000000000000000000000f849de01b080adc3a814fabe1e2087475cf2e35400000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000001388000000000000000000000000d823c605807cc5e6bd6fc0d7e4eea50d3e2d66cd";
		var runInput = new Function().DecodeOutput(data);
		Console.WriteLine(runInput.OrderInput.Shared.Salt);
	}

	[FunctionOutput]
	public class Function : IFunctionOutputDTO{
		[Parameter("tuple", "orderInput")]
		public OrderInput OrderInput {get; set;}
	}

	
public class OrderInput 
{
[Parameter("tuple[]", "orders", 1)]
public List<Order> Orders { get; set; }

[Parameter("tuple[]", "details", 2)]
public List<SettleDetail> Details { get; set; }

[Parameter("tuple", "shared", 3)]
public SettleShared Shared { get; set; }

[Parameter("bytes32", "r", 4)]
public byte[] R { get; set; }

[Parameter("bytes32", "s", 5)]
public byte[] S { get; set; }

[Parameter("uint8", "v", 6)]
public byte V { get; set; }
}

public class Order 
{
[Parameter("uint256", "salt", 1)]
public BigInteger Salt { get; set; }

[Parameter("address", "user", 2)]
public string User { get; set; }

[Parameter("uint256", "network", 3)]
public BigInteger Network { get; set; }

[Parameter("uint256", "intent", 4)]
public BigInteger Intent { get; set; }

[Parameter("uint256", "delegateType", 5)]
public BigInteger DelegateType { get; set; }

[Parameter("uint256", "deadline", 6)]
public BigInteger Deadline { get; set; }

[Parameter("address", "currency", 7)]
public string Currency { get; set; }

[Parameter("bytes", "dataMask", 8)]
public byte[] DataMask { get; set; }

[Parameter("tuple[]", "items", 9)]
public List<OrderItem> Items { get; set; }

[Parameter("bytes32", "r", 10)]
public byte[] R { get; set; }

[Parameter("bytes32", "s", 11)]
public byte[] S { get; set; }

[Parameter("uint8", "v", 12)]
public byte V { get; set; }

[Parameter("uint8", "signVersion", 13)]
public byte SignVersion { get; set; }
}

public class OrderItem : IFunctionOutputDTO
{
[Parameter("uint256", "price", 1)]
public BigInteger Price { get; set; }

[Parameter("bytes", "data", 2)]
public byte[] Data { get; set; }
}

public class SettleDetail : IFunctionOutputDTO
{
[Parameter("uint8", "op", 1)]
public byte Op { get; set; }

[Parameter("uint256", "orderIdx", 2)]
public BigInteger OrderIdx { get; set; }

[Parameter("uint256", "itemIdx", 3)]
public BigInteger ItemIdx { get; set; }

[Parameter("uint256", "price", 4)]
public BigInteger Price { get; set; }

[Parameter("bytes32", "itemHash", 5)]
public byte[] ItemHash { get; set; }

[Parameter("address", "executionDelegate", 6)]
public string ExecutionDelegate { get; set; }

[Parameter("bytes", "dataReplacement", 7)]
public byte[] DataReplacement { get; set; }

[Parameter("uint256", "bidIncentivePct", 8)]
public BigInteger BidIncentivePct { get; set; }

[Parameter("uint256", "aucMinIncrementPct", 9)]
public BigInteger AucMinIncrementPct { get; set; }

[Parameter("uint256", "aucIncDurationSecs", 10)]
public BigInteger AucIncDurationSecs { get; set; }

[Parameter("tuple[]", "fees", 11)]
public List<Fee> Fees { get; set; }
}

public class Fee 
{
[Parameter("uint256", "percentage", 1)]
public BigInteger Percentage { get; set; }

[Parameter("address", "to", 2)]
public string To { get; set; }
}

public class SettleShared 
{
[Parameter("uint256", "salt", 1)]
public BigInteger Salt { get; set; }

[Parameter("uint256", "deadline", 2)]
public BigInteger Deadline { get; set; }

[Parameter("uint256", "amountToEth", 3)]
public BigInteger AmountToEth { get; set; }

[Parameter("uint256", "amountToWeth", 4)]
public BigInteger AmountToWeth { get; set; }

[Parameter("address", "user", 5)]
public string User { get; set; }

[Parameter("bool", "canFail", 6)]
public bool CanFail { get; set; }
}
}
```

**Comment by hasandogu** [comment]
That was indeed the case @juanfranblanco. If a function returns a tuple, don't make the FunctionOutput attribute that tuple, just write the tuple as a separate structure that is then wrapped by the class that has the FunctionOutput attribute.

@Skr1pt
