### ISSUE TITLE
transaction failed operation is not supported on this platform webgl unity

### ISSUE THREAD

**Issue by khawarmeta** [Nethereum/Nethereum#1038]
I am interacting with a contract using private key in my unity webgl build and receiving exception message of not supported on this platform
![image (5)](https://github.com/user-attachments/assets/26ebb496-e599-42b5-9b1c-0b52a20a58f8)
here's my code please help

**Comment by juanfranblanco** [comment]
@khawarmeta have you added "using Nethereum.Unity.Rpc;"? Please come and chat in discord if needed.

**Comment by juanfranblanco** [comment]
Closing this.. until further action
