### ISSUE TITLE
Nested contracts.

### ISSUE THREAD

**Issue by akopeliovich** [Nethereum/Nethereum#104]
Hello, I'm trying to create a smart contract Poll, which creates nested contracts in function addQuestion.
And when I call PollQuestion.GetName(), it always returns null.
**----------------------------------------Contracts**
contract Poll {
	string _name;
	string _description;
	address[] _questions;

	function Poll(string name, string description) {
		_name = name;
		_description = description;
	}

	function addQuestion(
		string name,
		uint maxOptions) returns (address) {
		if (_opened) throw;

		address question = new PollQuestion(name, maxOptions);
		_questions.push(question);
		
		return question;
	}
}

contract PollQuestion {
	string _name;
	uint _maxOptions;

	function PollQuestion(
	string name,
	uint maxOptions) {
		_name = name;
		_maxOptions = maxOptions;
	}
	
	function getName() returns (string name) {
		return _name;
	}
}

**-----------------------------------------------C# code**
	public async Task<EthereumPollAddress> CreatePoll(
			string name,
			string description,
			IEnumerable<EthereumPollQuestion> questions) {
			var result = new EthereumPollAddress();
			var addressFrom = "0x12890d2cce102216644c59dae5baed380d84830c";
			var pass = "password";

			var web3 = new Web3();
			var unlockAccountResult = await web3.Personal.UnlockAccount.SendRequestAsync(addressFrom, pass, 10);

			var transactionHash = await web3.Eth.DeployContract.SendRequestAsync(
				pollAbi,
				pollBin,
				addressFrom,
				new HexBigInteger(900000),
				name,
				description);

			var mineResult = web3.Miner.Start.SendRequestAsync(6).Result;
			var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);

			while (receipt == null) {
				Thread.Sleep(1000);
				receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
			}

			var code = await web3.Eth.GetCode.SendRequestAsync(receipt.ContractAddress);
			if (string.IsNullOrEmpty(code) || code.Length < 3) {
				throw new InvalidOperationException("Can't deploy contract. ");
			}

			var contractAddress = receipt.ContractAddress;
			var stopResult = web3.Miner.Stop.SendRequestAsync().Result;

			result.Address = contractAddress;
			var contract = web3.Eth.GetContract(pollAbi, contractAddress);

			var addQuestionFunction = contract.GetFunction("addQuestion");
			foreach (var question in questions) {
				var callResult = await addQuestionFunction.CallAsync<string>(question.Title, question.MaxOptions);
				result.QuestionsAddress.Add(callResult);
			}

			return result;
		}

		public string GetQuestionMane(string questionContractAddress) {
			var web3 = new Web3();
		
			var contract = web3.Eth.GetContract(questionAbi, questionContractAddress);

			var getNameFunction = contract.GetFunction("getName");
			var callResult = getNameFunction.CallAsync<string>().Result; **//Always null**
			return callResult;
		}

**Comment by juanfranblanco** [comment]
```
var callResult = await addQuestionFunction.CallAsync<string>(question.Title, question.MaxOptions);
```
This is a call, you will need a transaction. Also you will need an event to get the contract address created.

**Comment by juanfranblanco** [comment]
Just re-checked your contract, you can could your array to get the addresses too

**Comment by akopeliovich** [comment]
Thank you for the answer! 
I've understood what I have to do. But now, when I've changed my Poll contract, it doesn't deploy anymore. var code = await web3.Eth.GetCode.SendRequestAsync(receipt.ContractAddress); returns 0x. I suggest, that I don't have enough gas anymore, but I don't know why.
Why do you use 900000gas for deployment contract? 
 
contract Poll {
	string _name;
	string _description;
	address[] _questions;

	function Poll(string name, string description) {
		_name = name;
		_description = description;
	}

	event QuestionAdded(address questionAddress);

	function addQuestion(
		string name,
		uint maxOptions) returns (address) {
		if (_opened) throw;

		address question = new PollQuestion(name, maxOptions);
		_questions.push(question);
		
		QuestionAdded(question);

		return question;
	}
}

**Comment by juanfranblanco** [comment]
It is an arbitrary figure, feel free to increase it, depending on the size of your name / description you might have exceeded the transaction gas cost. I cannot see anything wrong with the contract which might prevent deployment. I assume you have declared _opened.
