### ISSUE TITLE
The seed parameter for `EthECKey.GenerateKey()` does not create a fixed value

### ISSUE THREAD

**Issue by joemphilips** [Nethereum/Nethereum#1044]
The `seed` parameter for `EthECKey.GenerateKey()` does not create a fixed value.

when you instantiate SecureRandom in 
https://github.com/Nethereum/Nethereum/blob/1af2efbb884128037eb70b079fd8e05260248056/src/Nethereum.Signer/EthECKey.cs#L110

It will in fact call `CreatePrng` with `autoSeed: true` which feeds some random seeds to a generator.
And SetSeed in the next line just adds the user-specified seed as a source of entropy, so the actual compounded seed is still not fixed.

## Expected Behavior

`EthEcKey.GenerateKey(seed)` will always return the same value for same seed

## Current Behavior

It returns a different value every time

## Steps to Reproduce

1.
1.
1.
1.

## Possible Implementation

To fix this problem, you must set SecureRandom like this in the `EthEcKey.GenerateKey(seed)` method

```cs
var secureRandom = SecureRandom.GetInstance("SHA256PRNG", autoSeed: false);
secureRandom.SetSeed(seed);
```

**Comment by juanfranblanco** [comment]
Wouldn't that make it more deterministic which is the opposite of what we want?

**Comment by joemphilips** [comment]
Yes. I want it to be deterministic.
I want to fix the seed for the sake of reproducability of my test.
the parameter name "seed" is misleading IMO if this is an intended behaviour. At least it should be renamed to something like "additionalEntropy"

**Comment by juanfranblanco** [comment]
Yes it could be called additional entropy seed, but this is exactly what this required to do create a random number. If it is deterministic it would allow an attack. I would not want to add that option. For your tests I would recommend to use an existing private key.

**Comment by juanfranblanco** [comment]
Thank you, but I cannot add this
