### ISSUE TITLE
AdminPeers class is not available

### ISSUE THREAD

**Issue by prashantgithub82** [Nethereum/Nethereum#106]
Hi - I am using latest packages from nuget and when I am writing following code, its showing compile error as its not found.

var adminPeers = new AdminPeers(client);
return await adminPeers.SendRequestAsync();

Actually I am looking to get all nodes into my private blockchain. Please let me know how to do that using Nethereum client library.

Kind Regards

**Comment by juanfranblanco** [comment]
@prashantgithub82  Admin peers is available here:  https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Geth/RPC/Admin/AdminPeers.cs

**Comment by prashantgithub82** [comment]
Hi - Thanks for your response. I have installed nuget from PM > Install-Package Nethereum.Portable -Pre but when I am writing code like "var adminPeers = new AdminPeers(client);", its not recognizing.

Kind Regards,
Prashant Rai

**Comment by juanfranblanco** [comment]
@prashantgithub82  yes it has not been released yet, you can use the source temporarily if wanted.

**Comment by juanfranblanco** [comment]
```csharp

 public class AdminPeers : GenericRpcRequestResponseHandlerNoParam<JArray>
    {
        public AdminPeers(IClient client) : base(client, "admin_peers")
        {
        }
    }
```
