### ISSUE TITLE
DaoService example - https://eth2.augur.net

### ISSUE THREAD

**Issue by riskebiz** [Nethereum/Nethereum#108]
Should this be https://eth3.augur.net as https://eth2.augur.net produces a 502 Bad Gateway error.  Also, is there a current Ethereum address that will return a list of proposals just to see how it responds?

**Comment by riskebiz** [comment]
I'm just using https://infura.io until blockchain is downloaded.

**Comment by juanfranblanco** [comment]
@riskebiz yes use infura, is the best. This was created before Infura was launched, and the truth the sample needs to be upgraded to another working one  (Not the DAO). I will use ENS most probably
