### ISSUE TITLE
receipt is always null

### ISSUE THREAD

**Issue by fenix2222** [Nethereum/Nethereum#109]
I can't get tutorial code to work. I started provided testchain and when I run xunit test with provided test contract, it gets to code to get receipt and it just loops in "while" and receipt is always null. I haven't changed code much and I am starting the miner and getting true back.

```
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 120);

			Assert.True(unlockResult);

			var transactionHash = await web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, senderAddress, multiplier);

            var mineResult = await web3.Miner.Start.SendRequestAsync();

            Assert.True(mineResult);

            var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);

            while (receipt == null)
            {
                Thread.Sleep(5000);
                receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
            }
```

**Comment by juanfranblanco** [comment]
if if this is the first time to are  running Ethereum, your DAG might be building in the background. Check if your block numbers are increasing. Go to the Geth console and just type eth, this will give you all the info. 

You may need to provide some gas too, not just the default.

**Comment by fenix2222** [comment]
Yes, it is the first time. Ok, I will wait a bit for blocks to build. Ok, is default value 90000? Should you update that tutorial code?

I just checked eth.blockNumber few times (with a wait of 10 sec) and it keeps saying 393

**Comment by fenix2222** [comment]
I have tried to use 900000 as per your suggestion, but still no luck. receipt is still null and stuck in the loop. Block number is not increasing

eth.mining returns true while it is in the loop. And eth.getTransactioReceipt("xxxxxx") returns null also.

**Comment by juanfranblanco** [comment]
regarding the gas, this is just a high value setting.. you could use estimate gas for that.
Have you downloaded the latest geth and put it in your folder?

**Comment by fenix2222** [comment]
I didn't use the latest. I just used geth.exe that was provided in the solution. I tried to paste latest geth.exe and I get out of memory exception:

runtime: out of memory: cannot allocate 536870912-byte block (5242880 in use)
fatal error: out of memory

I have 16GB ran on my laptop...

**Comment by juanfranblanco** [comment]
Yes, use the latest geth, that is a modified version of geht for testing. 
I believe you have downloaded the 32 bit version, check that. I remember doing that same mistake myself a while ago.

**Comment by fenix2222** [comment]
Do you have a link by any chance of the geth I should be using, so I get the right one? I really want to get this simple tutorial working...

**Comment by juanfranblanco** [comment]
https://gethstore.blob.core.windows.net/builds/geth-alltools-windows-amd64-1.5.9-a07539fb.zip

**Comment by fenix2222** [comment]
Looks like I have geth running now, but it is still building blocks, it is up to 1414 blocks. How many block should there be in testchain?

**Comment by juanfranblanco** [comment]
if you don't stop mining you will continue to produce blocks, transactions are part of the blocks. If you are not doing anything.. just stop mining.

**Comment by fenix2222** [comment]
Ok, got it all working now. Thanks for all your help

**Comment by juanfranblanco** [comment]
Excellent, getting started is a small learning curve. But it helps to get an understanding of how everything fits together.
