### ISSUE TITLE
Issues compiling the project on VS 2017

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#110]
The following error comes up when compiling on VS 2017

> The type or namespace name 'Debug' does not exist in the namespace 'Nethereum.Geth.RPC' (are you missing an assembly reference?)	Nethereum.Geth(net451), Nethereum.Geth(netstandard1.1), Nethereum.Portable	

using Nethereum.Geth.RPC.Debug;  

is not recognized and objects within DebugApiService class are flagged as issues - object not found.

**Comment by juanfranblanco** [comment]
@ushakrishnan  check the latest, there was an issue with the ignored folders.

**Comment by ushakrishnan** [comment]
Perfect!  Thanks Juan, adding the gethdebug folder / downloading the new checkin worked perfectly.  Cheers!!
