### ISSUE TITLE
Extremely expensive contract deployment

### ISSUE THREAD

**Issue by aquiladev** [Nethereum/Nethereum#111]
I've tried to deploy contract with Nethereum and I was confused a bit when I saw the price. I think something wrong in my code...

Code:
```
var transactionHash = await _web3.Eth.DeployContract
    .SendRequestAsync(_abi,
	_contractByteCode,
	_userAddress,
	new HexBigInteger(158000),
	"cc0f128a4b90a4d18d01cc180d549b508b5110bca282e9e89ad9ccbd6331f8ee",
	"http://127.0.0.1:10000/devstoreaccount1/aaq/636257112543166241_17700055.PDF");
```
It costs me ~1.4 ETH in test-network

BUT, when I deploy this contract trough Mist it costs  ~0.003 ETH in test-network
Any ideas why is that?

**Comment by juanfranblanco** [comment]
Was your contract deployed successfully on both occasions? Did you use eth_getCode to verify it? 
Trying to validate if one of the deployments was not successful or an issue with the code might have lead to running out of gas.

**Comment by aquiladev** [comment]
Both were deployed successfully. I didn't use eth_getCode.

**Comment by juanfranblanco** [comment]
ok so both were working then and functional. Mainly you can set the gas to what you want, obviously deploying a contract will use more gas, and if you dont provide enough gas it wont be deployed succesfully. 
http://ethereum.stackexchange.com/questions/1113/can-i-set-the-gas-price-to-whatever-i-want

**Comment by juanfranblanco** [comment]
Btw Nethereum and Mist both connect to geth or parity or whatever node you have running. So it makes no difference.

**Comment by juanfranblanco** [comment]
@aquiladev on one of the latest commits you can find a simple method to estimate gas for contracts https://github.com/Nethereum/Nethereum/blob/21d1627cdf355b227db2fcbea9d1020c14260a0f/src/Nethereum.Web3.Tests/ContractConstructorDeploymentAndCall.cs#L13-L27

**Comment by aquiladev** [comment]
@juanfranblanco I'll check it. It is clear that I can set as many gases as I want, but in my case when I set less I have message like "not enough gas"

**Comment by juanfranblanco** [comment]
That is a geth message, also estimate is  an estimate, so use it as a basis.
