### ISSUE TITLE
Support for .net core 1.1

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#112]
Created a blank .net core 1.1 console app.  Trying to add both RC and stable versions, but bouncycastle (?) or some incompat.

Is it possible to use nethereum to create core console app?

**Comment by juanfranblanco** [comment]
If you are using the 2.0.0-rc1 add the BouncyCastle Portable 1.8.1.1 first

**Comment by ushakrishnan** [comment]
Thank you, Juan.  Worked like a charm.
