### ISSUE TITLE
EdjCase.JsonRpc.Client GetResult not found

### ISSUE THREAD

**Issue by bitcoinbrisbane** [Nethereum/Nethereum#113]
I know its a 3rd party library, but after NuGet update from 1.1.2 to 1.3.1 the following method doesn't work.

var accounts = web3.Personal.ListAccounts.SendRequestAsync().Result;

**Comment by juanfranblanco** [comment]
Don't upgrade it

**Comment by bitcoinbrisbane** [comment]
Yes, I've rolled back.  I thought the post could be helpful to others.

**Comment by juanfranblanco** [comment]
Thanks for the heads up :), I am upgrading it for 2.0.0 just now. The method is there in 1.3.1.

**Comment by juanfranblanco** [comment]
Everything seems fine, are you running portable? is it Ok if you await?

**Comment by bitcoinbrisbane** [comment]
Its on a Xamarin / Visual Studio for Mac on MacOS, targeting .Net 4.5 / Mono.  Its just a console app at the moment for a demo.  Ill run an async unit test and report the results.

**Comment by juanfranblanco** [comment]
Thanks it should be compatible on your environment they target  net451;netstandard1.1;portable45-net45+win8+wpa81.
