### ISSUE TITLE
Netstandard and Portable future projects

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#114]
As of now the idea is to have Netstandard and net451 only for individual libraries, it seems that with the new csproj file, portable is only supported to be compiled on environments that have MsBuild (windows). So to allow anybody to contribute and compile Nethereum in any environment individual libraries will target those versions.

Nethereum.Portable will continue to be the portable project including everything.

**Comment by cicorias** [comment]
Not sure if you're aware, but msbuild is xplat at least for core https://github.com/Microsoft/msbuild

**Comment by juanfranblanco** [comment]
@cicorias many thanks that might be the solution I did not know that, Oren mentioned the opposite in one of the issues, but I guess he was referring only to "dotnet build"

**Comment by juanfranblanco** [comment]
@cicorias  yes now I remember the issue, mainly MsBuild only builds .net core x-platform.

**Comment by juanfranblanco** [comment]
For reference https://github.com/dotnet/roslyn-project-system/issues/1369
