### ISSUE TITLE
DAPP options for Quorum

### ISSUE THREAD

**Issue by rohitgkr** [Nethereum/Nethereum#115]
Hello, I am trying to post offline transactions to a Quorum chain setup in Azure. I can see that a VM is created with a public IP address which runs the 7 node Geth instances. CAn you please suggest how I can use Nethereum from another server to post offline transactions? Does this require Geth installed on the other node? If Geth is running in my local domain as an observer how do I get this node to post offline transactions to the Quorum network? Many thanks.

**Comment by juanfranblanco** [comment]
@rohitgkr you should be able to communicate with each node via RPC in the same way as you do with a local / remote geth. Quorum is different to Geth it is a fork with different consensus. 

Check how to use privacyFor here
https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.Quorum

or  to view the differences between using privateFor.
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Quorum.Tests/QuorumPrivateContractTests.cs

You will need to open the port of the node/s you want to communicate to.
The ports are 22000 to 22006 (1 to 7)

**Comment by juanfranblanco** [comment]
Keeping it open to add step by step guide on documentation / video.

**Comment by rohitgkr** [comment]
Hi Juan,

Cheers for the quick response. I would like to use the Nethereum Quorum client to interact with Quorum framework which sits on top of the Ethereum private blockchain (on the Linux VM). I intend to use the client from the web tier in Azure (say API Apps service layer) which is a PAAS system. My understanding is that Web3 requires a local version of Geth running on the same server. If so I believe Nethereum.Quorum will require GETH to be installed on each of the PAAS VMs. Instead I think I can have 1 gateway machine  hosting an API service which will also have GETH installed and exposes a service API for the Quorum blockchain. This can use Nethereum to communicate with the Linux VM hosting Quorum nodes. So I should open ports on the linux server for the gateway to call into Quorum.

 

Do you have a better suggestion on how to deploy Nethereum? The alternative is to use the Linux VM to host a service API written in node.js. However then everything is running on one Linux box including the blockchain + service which is a lot of IO. My inclination is for the gateway server. However I’d really like to hear from you on this.

Many thanks.

Rohit

**Comment by juanfranblanco** [comment]
@rohitgkr It all depends on your architecture, (and security) but you can communicate directly to a specific node using RPC (it does not need to be on the same machine). So opening those ports would allow you to send requests from your Azure Website if wanted (or any other app service / microservice).

**Comment by rohitgkr** [comment]
Great. In that case I will try using RPC to post from my DEV laptop to the Azure Quorum VM in the evening - without using GETH. I guess this will require site to site VPN to interact with the Quorum VM from my laptop. Cheers.

**Comment by juanfranblanco** [comment]
If you open the ports directly on the VM you should be able to do the calls, your VM should have a public IP, use that to connect. (Obviously you would not do this on prod ;) )

**Comment by rohitgkr** [comment]
Yes indeed, the workaround is for a DEV setup. I am in a different office now, so will try it out later from home & let you know. Thanks for your help!
