### ISSUE TITLE
Event log vs contract storage mapping

### ISSUE THREAD

**Issue by rohitgkr** [Nethereum/Nethereum#118]
Hi Juan. Thanks for your useful video on Events/Filters/Topics. I am planning to store portfolio transactions on chain and also a corresponding counter cash transaction which is executed after aggregating individual transactions (say intraday). I'm considering events vs mappings.

I believe Ethereum internally imeplements bloom filters for events which allows fast filtering criteria via topics. The dataset can accumulate to a large size over time & bloom filters should be able to handle this. But over time there can be hash collisions. In contract storage as I can only search by mapping key unlike with events which can have multiple indexes. In the context of Quorum I think there's no gas limit for contract storage and memory storage wise there's no limit. I'm not sure if Nethereum has any additional considerations/preference for underlying storage. Based on your experience what do you suggest? Cheers.

**Comment by juanfranblanco** [comment]
@rohitgkr, As usual, it depends, if you are only storing this data as a record of an event (portfolio transaction), I would supplement this with other traditional storage, which would allow you for more complex queries but still correlated to the original transaction (off chain id). The data can be verified by querying the chain. The smart contract can execute some logic and provide also the storage. Use an event with the information you want to capture (and as a proof of successful storage on chain) and push it to your usual database.  In a public chain, you may want to use events to reduce the cost of storage, but these are not designed (even if they currently do) to be stored permanently as a record on the chain.

**Comment by rohitgkr** [comment]
Yes JSON style offchain storage with documentDB or mongoDB could be an option. However with private blockchain is contract storage a better option? Because it is stored permanently on chain, tehre's no theoretical storage limit and also it doesn't cost gas? However I believe you can query only by key in case of mapping. Looks like the transaction hash can be maintained in the off chain table and indexing on other fields can be done offchain with correlation being the transaction hash for onchain. Contract storage can store a subset of immutable data, instead of maintaining that externally in documentDB and then also storing the message digest offchain - seems to beat the point of the blockchain. Nice point about event log, since it is not part of consensus it is not a proof of immutability. Cheers.

**Comment by juanfranblanco** [comment]
Yes, it also depends on your need, do you need several parties to agree on that immutable data? Are you just using this as a tamper proof mechanism to have auditable historical records?

**Comment by rohitgkr** [comment]
For now its mainly for audit trail and also regulatory compliance which in the Quorum world probably maps to an observer role. However I am thinking of making the regulator a party to private transactions with block voting rights between the party and brokerage. That way the observer can also get the same data discretely (cryptographically transmitted) into their private state DB. Would you rather make it an observer role without maker or voter rights - but that wouldn't give it access to all transactions.

**Comment by juanfranblanco** [comment]
Very nice, and good point about the observer without maker or voter rights on the private.
