### ISSUE TITLE
Could not load 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'

### ISSUE THREAD

**Issue by sinhashish** [Nethereum/Nethereum#119]
Hi Juan,

I am getting this when calling a function. Please help.

{"Could not load file or assembly 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The system cannot find the file specified.":"crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942"}

at Nethereum.ABI.Util.Sha3Keccack.CalculateHash(Byte[] value)\r\n   at Nethereum.ABI.Util.Sha3Keccack.CalculateHash(String value)\r\n   at Nethereum.ABI.FunctionEncoding.SignatureEncoder.GenerateSha3Signature(String name, Parameter[] parameters)\r\n   at Nethereum.ABI.FunctionEncoding.SignatureEncoder.GenerateSha3Signature(String name, Parameter[] parameters, Int32 numberOfFirstBytes)\r\n   at Nethereum.ABI.FunctionEncoding.FunctionABI.get_Sha3Signature()\r\n   at Nethereum.Web3.Function.GetData(Object[] functionInput)\r\n   at Nethereum.Web3.Function.SendTransactionAsync(String from, HexBigInteger gas, HexBigInteger value, Object[] functionInput)\r\n

**Comment by juanfranblanco** [comment]
@sinhashish do you have a reference to Portable BouncyCastle ?

**Comment by juanfranblanco** [comment]
Closed, no response. In this situations normally there is a need to add the package of Portable Bouncy Castle 1.8.1.1 first

**Comment by morejump** [comment]
@juanfranblanco I also faced this issue. My project used to build and run ok, but now it throws this message. My project has reference to BouncyCastle :(.

What should I do?

**Comment by tuyen-vuduc** [comment]
BouncyCastle must be 1.8.1.1 on Android.

**Comment by ciarmoli-marco** [comment]
I have the same problem and I have the reference to both BouncyCastle 1.8.1.1 and Portable.BouncyCastle 1.8.1.1 . It doesn't change anything. In the error the version is 1.8.1.0, why is that?

**Comment by juanfranblanco** [comment]
If you look at the project nugets references dependencies (Nethereum.Util) is as follows:
```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.1'">
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.1.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net451' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
   <PackageReference Include="BouncyCastle" Version="1.8.1" />
  </ItemGroup>
```
So depending what are you using (.ie) Android, Core, etc you should have Portable 1.8.1.1. If you are using the full .Net framework the package is 1.8.1.

**Comment by pushist1y** [comment]
I have encountered the same error. Reading issues here i've come to conclusion that it's some kind of dependencies conflict. I've found out that including in the project either MimeKit or MailKit inflicts this error. Without them signature verifying works well now. Hope this helps to locate the problem.

**Comment by tellamon** [comment]
I also have faced the same problem. As @pushist1y  mentioned, it looks like MailKit(2.0.3) is conflicting since it references Portable.BouncyCastle >= 1.8.1.3

I have not found any solution yet. trying to recompile Nethereum with the same version of Portable.Bouncy that MailKit has.

**Comment by dradovic** [comment]
I'm facing the same issue but I don't have a reference to MailKit or BouncyCastle. It's occuring at: Nethereum.Signer.EthECKey.GenerateKey()

Any tips how to tackle this?

**Comment by pushist1y** [comment]
@dradovic most likely you have another reference that in it's order references different version of BouncyCastle. In our project we managed to keep both MailKit and Nethereum by selecting versions which both use the same version of BouncyCastle.

**Comment by dradovic** [comment]
I suspect in my case it's WebPush which is requiring >= Portable.BouncyCastle 1.8.1.3. But there is no WebPush version that requires less. So I'm out of luck. Any other ideas?

**Comment by juanfranblanco** [comment]
I am looking into it to pump the version as we speak, I am doing some validations and compatibility.

**Comment by dradovic** [comment]
Perfect! Thank you very much. In that case I'll wait for the next version and see if it resolves the problem.
