### ISSUE TITLE
Issues while trying to make the money transfer using Nethereum - May 19, 2017

### ISSUE THREAD

**Issue by maksym-devpro** [Nethereum/Nethereum#126]
Dear Support Team, 

We have faced with the problem while trying to make the transfer through the Nethereum client.

We are using AspNetCore1.0  framework, and next libraries:

    "Nethereum.Web3": "2.0.0-rc3",
    "Nethereum.Hex": "2.0.0-rc3",
    "Nethereum.RPC": "2.0.0-rc3",
    "Nethereum.ABI": "2.0.0-rc3",
    "Nethereum.Contracts": "2.0.0-rc3",
    "Nethereum.Geth": "2.0.0-rc3"

http://screenshots.client-demo-site.net/scn-20170519-121856-m7a8w.png

We are running Geth with the next parameters:

geth --rpc --rpcapi "eth,web3,personal,net,miner,admin"

http://screenshots.client-demo-site.net/scn-20170519-122724-k7nqj.png
http://screenshots.client-demo-site.net/scn-20170519-122820-25e0x.png

After Geth has started we've received balances from our Ethereum wallets:

var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5"; 
var receiverAddress = "0xFa124009bBE18ec5F0426c5Fd3275C30E480633b";

http://screenshots.client-demo-site.net/scn-20170519-123801-70dcn.png

After that, we have signed the transaction using the private key from the file in Keystore. During the transaction verification, the value is True.
http://screenshots.client-demo-site.net/scn-20170519-125152-r72ap.png

A. First issue

The main problem is that we could send a transaction and get the transactionId ( "0x3483fdd5409cdd814ffa4751cd3c5297cabc24c8059a98f0a78b69789ac29660"), but the balance is still Null (didn't change).
http://screenshots.client-demo-site.net/scn-20170519-130507-v0kfj.png

Please help us to understand how to transfer the money between wallets properly so that we'll be able to see updated balance after transaction passed successfully.
 
Below you can find the code:

var web3 = new Web3("http://localhost:8545");
var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5";
var receiverAddress = "0xFa124009bBE18ec5F0426c5Fd3275C30E480633b";
                
var balanceSender = await web3.Eth.GetBalance.SendRequestAsync(senderAddress);
var balanceReceive = await web3.Eth.GetBalance.SendRequestAsync(receiverAddress);
                
var path = @"...\keystore\0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5.json";
var file = System.IO.File.OpenText(path);
var json = file.ReadToEnd();
                
var keyStoreService = new KeyStoreService();
var keyByteArray = keyStoreService.DecryptKeyStoreFromJson(senderPass, json);  //decrypt the private key
var senderPrivateKey = keyByteArray.ToHex();
var adressFromKeyStore = keyStoreService.GetAddressFromKeyStore(json);
                
var txCount = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(senderAddress);
                var gasPrice = new BigInteger(21000);
                var gasLimit = new BigInteger(21000); 

var encoded = web3.OfflineTransactionSigner.SignTransaction(senderPrivateKey, receiverAddress,100000,   txCount.Value, gasPrice,gasLimit);

var isVerifyN = web3.OfflineTransactionSigner.VerifyTransaction(encoded);
var hexPrefixN = web3.OfflineTransactionSigner.GetSenderAddress(encoded).EnsureHexPrefix();
                
var txId = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + encoded);

var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txId);

 while (receipt == null)
{
Thread.Sleep(5000);
receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txId);
}

B. Second issue

The second problem is we get the error at the time of the request web3.Personal.UnlockAccount:

var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5"; 
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, senderPass, new HexBigInteger(120));

Error text: invalid argument 2: JSON: cannot unmarshal string into Go value of type uint64.

Please help us to understand why UnlockAccount request produces this error.

Looking forward hearing from you

**Comment by juanfranblanco** [comment]
First of all, thanks for such a descriptive issue.
Starting with B, which is the simplest. To Unlock an account using the new Geth you need to use an integer or uint, instead of HexBigInteger replacing the HexBigInteger(120) with 120.

**Comment by juanfranblanco** [comment]
For the first part of the question, please find the following examples, which can be used with 2.0.0

https://github.com/Nethereum/Nethereum/blob/e59d0c209df44e85aab03fd02c90b614036c36d8/src/Nethereum.Tutorials/Nethereum.Tutorials.Account/AccountTransfer.cs

**Comment by maksym-devpro** [comment]
Thank you so much for the fast reply. I will fix the type and check the flow. Will keep you updated.

**Comment by juanfranblanco** [comment]
Yes, in 2 I have tried to unify / and simplify the way accounts are managed.

**Comment by maksym-devpro** [comment]
Hello juanfranblanco,

A. First issue

I found your examples by this link 
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Tutorials/Nethereum.Tutorials.Account/AccountTransfer.cs

and tried to create a transfer through TransactionReceiptPollingService, but I got an error "Nethereum.JsonRpc.Client.RpcResponseException: unknown account", in this point:

var transactionReceipt = await transactionPolling.SendRequestAsync(() =>  web3.TransactionManager.SendTransactionAsync(account.Address, receiverAddress, new HexBigInteger(20)));

http://screenshots.client-demo-site.net/scn-20170522-133841-f9tkt.png

Please help me to understand why transactionPolling request produces this error.

Please find the code bellow:

var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5";//imToken senderAddress
var receiverAddress = "0xFa124009bBE18ec5F0426c5Fd3275C30E480633b";//imToken receiveAddress

var account = new ManagedAccount(senderAddress, senderPass);

var web3 = new Web3(account);

var transactionPolling = new TransactionReceiptPollingService(web3);

var currentBalance = await web3.Eth.GetBalance.SendRequestAsync(receiverAddress);


var transactionReceipt = await transactionPolling.SendRequestAsync(() =>
                                web3.TransactionManager.SendTransactionAsync(account.Address, receiverAddress, new HexBigInteger(20)));

var newBalance = await web3.Eth.GetBalance.SendRequestAsync(receiverAddress);

B. Second issue

The issue is that we got an error at the time of the request web3.Personal.UnlockAccount.

I used an integer, instead of HexBigInteger and got the next error: Nethereum.JsonRpc.Client.RpcResponseException: no key for given address or file.
http://screenshots.client-demo-site.net/scn-20170522-140026-wiihp.png

var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5"; 
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, senderPass, 120);
 
This variation requests return the same errors:

var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, PassToKeystoreFile, 120);
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, senderPrivateKey, 120);

Please help me understand why UnlockAccount request produces this error.

Thank you,

**Comment by juanfranblanco** [comment]
You are trying to use an account which is not part of the client. (Not in the keystore folder of the client)

**Comment by MartinOpde** [comment]
So what can we do in that case ?

**Comment by juanfranblanco** [comment]
@MartinOpde sign your own transactions.  Check this info, it may help you: http://nethereum.readthedocs.io/en/latest/accounts/

**Comment by MartinOpde** [comment]
@juanfranblanco thx for quick reply.  I had "Invalid account used" but now it's gone, don't know exactly why.

**Comment by juanfranblanco** [comment]
@MartinOpde once you start signing offline the issue will be gone, if you are pointing to a local node, you might be have been using an account not included in the KeyStore which geth / parity will manages
