### ISSUE TITLE
Code for SignAndSendRequestAsync

### ISSUE THREAD

**Issue by simonrhart** [Nethereum/Nethereum#128]
Hi

In the NuGet v1.0.6 package there are multiple overloaded methods: Nethereum.Web3.SignAndSendRequestAsync but these do not exist in the source code. Where can I find this code?

Thanks
Simon

**Comment by juanfranblanco** [comment]
This code has been refactored in version 2.0.0. You will need to use the TransactionManager in Web3.

https://nethereum.readthedocs.io/en/latest/accounts/

This may help.

**Comment by juanfranblanco** [comment]
Closing this
