### ISSUE TITLE
Issues while trying to make the money transfer using Nethereum May  23, 2017

### ISSUE THREAD

**Issue by maksym-devpro** [Nethereum/Nethereum#129]
Hello juanfranblanco,

A. First issue

I found your examples by this link
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Tutorials/Nethereum.Tutorials.Account/AccountTransfer.cs

and tried to create a transfer through TransactionReceiptPollingService, but I got an error "Nethereum.JsonRpc.Client.RpcResponseException: unknown account", in this point:

var transactionReceipt = await transactionPolling.SendRequestAsync(() => web3.TransactionManager.SendTransactionAsync(account.Address, receiverAddress, new HexBigInteger(20)));

http://screenshots.client-demo-site.net/scn-20170522-133841-f9tkt.png

Please help me to understand why transactionPolling request produces this error.

Please find the code bellow:

var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5";//imToken senderAddress
var receiverAddress = "0xFa124009bBE18ec5F0426c5Fd3275C30E480633b";//imToken receiveAddress

var account = new ManagedAccount(senderAddress, senderPass);

var web3 = new Web3(account);

var transactionPolling = new TransactionReceiptPollingService(web3);

var currentBalance = await web3.Eth.GetBalance.SendRequestAsync(receiverAddress);

var transactionReceipt = await transactionPolling.SendRequestAsync(() =>
web3.TransactionManager.SendTransactionAsync(account.Address, receiverAddress, new HexBigInteger(20)));

var newBalance = await web3.Eth.GetBalance.SendRequestAsync(receiverAddress);

B. Second issue

The issue is that we got an error at the time of the request web3.Personal.UnlockAccount.

I used an integer, instead of HexBigInteger and got the next error: Nethereum.JsonRpc.Client.RpcResponseException: no key for given address or file.
http://screenshots.client-demo-site.net/scn-20170522-140026-wiihp.png

var senderAddress = "0x9F8266d2E1Cd48124DeC022BA3eec4919fAAc4C5";
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, senderPass, 120);

This variation requests return the same errors:

var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, PassToKeystoreFile, 120);
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, senderPrivateKey, 120);

Please help me understand why UnlockAccount request produces this error.

Thank you,

**Comment by jcalixv** [comment]
Hello, did you solve your issue???

I've been using the below code on private and dev chain and works as expected.

            public async Task ShouldBeAbleToTransferBetweenAccountsUsingManagedAccount()
           {
            // A managed account is an account which is maintained by the client (Geth / Parity)
            var account = new ManagedAccount(_mainAccount, _password);
            var web3 = new Web3(account, _url);
            var web3Geth = new Web3Geth(web3.Client);

            //The transaction receipt polling service is a simple utility service to poll for receipts until mined
            var transactionPolling = new TransactionReceiptPollingService(web3);

            var currentBalance = await web3.Eth.GetBalance.SendRequestAsync(_adminAccount);
            Console.WriteLine(currentBalance);
            //assumed client is mining already

            var res = await StartMining(web3Geth);
            if (res == false)
            {
                //My Dev Net doesnt return true. 
                //throw new ArgumentException("Could not start mining...");
            }

            //When sending the transaction using the transaction manager for a managed account, personal_sendTransaction is used.
            var transactionReceipt = await transactionPolling.SendRequestAsync(
                () => web3.TransactionManager.SendTransactionAsync(account.Address, _adminAccount, new HexBigInteger(UnitConversion.Convert.ToWei(1)))
            );
            Console.WriteLine(JsonConvert.SerializeObject(transactionReceipt));

            res = await StopMining(web3Geth);
            if(res == false) throw new ArgumentException("Could not stop mining...");

            var newBalance = await web3.Eth.GetBalance.SendRequestAsync(_adminAccount);
            Console.WriteLine(newBalance);
        }

and this one (without the managed account)

             public async Task SendEtherTest()
            {
            var web3Geth = new Web3Geth(_web3.Client);
            
            var ethSendTransation = new EthSendTransaction(_web3.Client);
            var transactionInput = new TransactionInput
            {
                From = _mainAccount,
                To = _adminAccount,
                Value = new HexBigInteger(UnitConversion.Convert.ToWei(10)),
                //Gas = new HexBigInteger(UnitConversion.Convert.ToWei(0)),
                Data = "SomeGuidId1234567890".ToHexUTF8()
            };

            var result = await StartMining(web3Geth);
            if(!result) throw new ArgumentException("Could not start mining.");
            //The Start Mining Always return False, but the miner do Starts.
            

            string txHash = String.Empty;
            var unlockAccount = await _web3.Personal.UnlockAccount.SendRequestAsync(_mainAccount, _password, 600);
            if (unlockAccount)
            {
                txHash = await ethSendTransation.SendRequestAsync(transactionInput);
                Console.WriteLine(txHash);
            }
            if (!string.IsNullOrWhiteSpace(txHash))
            {
                var txReceipt = await TransactionReceipt(_web3, txHash);
                Console.WriteLine(JsonConvert.SerializeObject(txReceipt));
                Console.WriteLine(txReceipt.GasUsed.Value);
            }

            result = await web3Geth.Miner.Stop.SendRequestAsync();
            if (result != true) throw new Exception("Could not stop mining");

            var lockAccount = await _web3.Personal.LockAccount.SendRequestAsync(_adminAccount);
            Console.WriteLine(lockAccount);
        }
hope this helps you.

**Comment by maksym-devpro** [comment]
Thank you so much jcalixv for your attempt to help me.

Sorry, your code isn't work in my project. I solved the problem with next steps

var account = new ManagedAccount(senderAddres, senderPass);
 var web3 = new Web3(account);
var web3Geth = new Web3Geth(web3.Client);  
 

var transactionPolling = new TransactionReceiptPollingService(web3); 

var transactionReceipt = await transactionPolling.SendRequestAsync(
                        () => web3.TransactionManager.SendTransactionAsync(account.Address,
                                                                        receiverAddress, new HexBigInteger(100000) ));
             
var hash = transactionReceipt.BlockHash;

**Comment by jcalixv** [comment]
Hello, glad you solve it.
One thing though, the below line is the only one that is different, yours only works if your node is running/listening in http://localhost:8545 address
                    var web3 = new Web3(account);
mine is:
                    var web3 = new Web3(account, _url);
where _url is the http://someprivateorpublicIP:someport

Have a nice day.

**Comment by maksym-devpro** [comment]
Thank you jcalicu
