### ISSUE TITLE
Non-PCL Nuget packages shouldn't depend on BouncyCastlePCL?

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#130]
There are issues with PCL assemblies in Linux (the long-term fix for these problems is .NET Standard, but it's not there yet...), so then I tried to use the alternative Nethereum Nuget packages that are not PCL, however, those depend on the BouncyCastlePCL nuget package.

Shouldn't the dependency be on the nonPCL BouncyCastle nuget package instead?

**Comment by juanfranblanco** [comment]
@knocte Latest source targets non pcl for net451 https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer/Nethereum.Signer.csproj#L36-L40

**Comment by knocte** [comment]
I see! cool! Do you mind publishing a 2.0.0-rc4 version to nuget so I can test?

**Comment by juanfranblanco** [comment]
Yes, most probably tomorrow.

**Comment by knocte** [comment]
rc4 fixes the problem, thank you!!
