### ISSUE TITLE
startgeth.sh - genesis block error geth 1.6.1

### ISSUE THREAD

**Issue by christophwille** [Nethereum/Nethereum#131]
INFO [06-01|11:07:12] Allocated cache and file handles         database=/Users/christophw/gitworkspace/nethereum/testchain/devChain/geth/chaindata cache=16 handles=16
Fatal: Failed to write genesis block: genesis has no chain configuration
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.1-stable-021c3c28/darwin-amd64/go1.8.1
coinbase: 0x12890d2cce102216644c59dae5baed380d84830c
at block: 0 (Thu, 01 Jan 1970 01:00:00 CET)
 datadir: /Users/christophw/gitworkspace/nethereum/testchain/devChain
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

*****

Using latest from Github (I remember that .bat had some issues back too when I did try workbooks on Windows)

**Comment by prasannapattam** [comment]
Geth made config as mandatory. Hence I added the following to the genesis_dev.json

	"config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
