### ISSUE TITLE
Only one usage of each socket address (protocol/network address/port) is normally permitted 127.0.0.1:8545

### ISSUE THREAD

**Issue by tanderbold** [Nethereum/Nethereum#132]
Hi! A little time ago I began to recive a periodic messages, when calling an async methods of web3.

`05-11:22:12 System.AggregateException: One or more errors occurred. ---> EdjCase
.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rp
c requests(s) ---> System.Net.Http.HttpRequestException: An error occurred while
 sending the request. ---> System.Net.WebException: Unable to connect to the rem
ote server ---> System.Net.Sockets.SocketException: Only one usage of each socke
t address (protocol/network address/port) is normally permitted 127.0.0.1:8545
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Sock
et s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state,
IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, Tr
ansportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar
)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__24`2.MoveNext()
   --- End of inner exception stack trace ---
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__24`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at EdjCase.JsonRpc.Client.RpcClient.<SendRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.<SendRequestAsync>d__
7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ethereum.Worker.StepIn() in C:\BuildAgent\work\6d3c7e70f935673e\CryptoBill
ing.Ethereum\Ethereum\Ethereum\Worker.cs:line 178
---> (Inner Exception #0) EdjCase.JsonRpc.Client.RpcClientUnknownException: Erro
r occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestE
xception: An error occurred while sending the request. ---> System.Net.WebExcept
ion: Unable to connect to the remote server ---> System.Net.Sockets.SocketExcept
ion: Only one usage of each socket address (protocol/network address/port) is no
rmally permitted 127.0.0.1:8545
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Sock
et s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state,
IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, Tr
ansportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar
)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__24`2.MoveNext()
   --- End of inner exception stack trace ---
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__24`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at EdjCase.JsonRpc.Client.RpcClient.<SendRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.<SendRequestAsync>d__
7.MoveNext()<---`

I run netstat and saw thousands of open sockets (see screen). 
Code is simple: 
`Web3 web3 = new Web3(ConfigurationManager.AppSettings.Get("ServerIp"));
var accs = Utils.web3.Personal.ListAccounts.SendRequestAsync().Result;`

Where is reason of my problem?

**Comment by juanfranblanco** [comment]
That is very strange, have you restarted the client?. The clients won't start if they have the same port open already, so it won't be an issue with different clients opened by mistake. Http requests from Nethereum will get closed straight away, the inner client uses "using", and the ipc has a set timeout.

**Comment by tanderbold** [comment]
Yes I've restarted geth and my client many times on two different servers, result is the same.

**Comment by juanfranblanco** [comment]
hmm, what client are you using / version? RPC / IPC? (I assume RPC)

**Comment by tanderbold** [comment]
geth 1.6.5 (screen below)
![2](https://cloud.githubusercontent.com/assets/18721315/26779723/375e3112-49ef-11e7-9de8-de31dfce8ed8.png)

RPC client of Nethereum
Web3 web3 = new Web3(ConfigurationManager.AppSettings.Get("http://localhost:8545"));
<package id="EdjCase.JsonRpc.Client" version="1.1.0" targetFramework="net452" />
  <package id="EdjCase.JsonRpc.Core" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.NETCore.Platforms" version="1.0.1" targetFramework="net452" />
  <package id="Nethereum.ABI" version="1.0.6" targetFramework="net452" />
  <package id="Nethereum.Hex" version="1.0.6" targetFramework="net452" />
  <package id="Nethereum.JsonRpc.Client" version="1.0.6" targetFramework="net452" />
  <package id="Nethereum.JsonRpc.IpcClient" version="1.0.6" targetFramework="net452" />
  <package id="Nethereum.RPC" version="1.0.6" targetFramework="net452" />
  <package id="Nethereum.Web3" version="1.0.6" targetFramework="net452" />
  <package id="NETStandard.Library" version="1.6.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="NLog" version="4.4.0" targetFramework="net452" />
  <package id="NLog.Targets.Syslog" version="3.0.2" targetFramework="net452" />
  <package id="Portable.BouncyCastle" version="1.8.1" targetFramework="net452" />
  <package id="System.Collections" version="4.0.11" targetFramework="net452" />
  <package id="System.Collections.Concurrent" version="4.0.12" targetFramework="net452" />
  <package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="net452" />
  <package id="System.Diagnostics.Tools" version="4.0.1" targetFramework="net452" />
  <package id="System.Diagnostics.Tracing" version="4.1.0" targetFramework="net452" />
  <package id="System.Globalization" version="4.0.11" targetFramework="net452" />
  <package id="System.IO" version="4.1.0" targetFramework="net452" />
  <package id="System.IO.Compression" version="4.1.0" targetFramework="net452" />
  <package id="System.Linq" version="4.1.0" targetFramework="net452" />
  <package id="System.Linq.Expressions" version="4.1.0" targetFramework="net452" />
  <package id="System.Net.Http" version="4.1.0" targetFramework="net452" />
  <package id="System.Net.Primitives" version="4.0.11" targetFramework="net452" />
  <package id="System.ObjectModel" version="4.0.12" targetFramework="net452" />
  <package id="System.Reflection" version="4.1.0" targetFramework="net452" />
  <package id="System.Reflection.Extensions" version="4.0.1" targetFramework="net452" />
  <package id="System.Reflection.Primitives" version="4.0.1" targetFramework="net452" />
  <package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="net452" />
  <package id="System.Runtime" version="4.1.0" targetFramework="net452" />
  <package id="System.Runtime.Extensions" version="4.1.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices" version="4.1.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.0.0" targetFramework="net452" />
  <package id="System.Runtime.Numerics" version="4.0.1" targetFramework="net452" />
  <package id="System.Text.Encoding" version="4.0.11" targetFramework="net452" />
  <package id="System.Text.Encoding.Extensions" version="4.0.11" targetFramework="net452" />
  <package id="System.Text.RegularExpressions" version="4.1.0" targetFramework="net452" />
  <package id="System.Threading" version="4.0.11" targetFramework="net452" />
  <package id="System.Threading.Tasks" version="4.0.11" targetFramework="net452" />
  <package id="System.Threading.Timer" version="4.0.1" targetFramework="net452" />
  <package id="System.Xml.ReaderWriter" version="4.0.11" targetFramework="net452" />
  <package id="System.Xml.XDocument" version="4.0.11" targetFramework="net452" />

**Comment by juanfranblanco** [comment]
Hi did your issue get sorted?

**Comment by BenjaminNitschke** [comment]
Hi, I had the same issue and it turned out some RPC calls were not closed yet (I am querying 20k addresses and checking balances every 30s) and I got randomly the same error in the log. I have increased the time to 90s for each run and no more errors. So basically the issue is if another RPC call is still active, a new one might fail.

**Comment by juanfranblanco** [comment]
This was solved by creating a new RPC implementation and workaround on some issues with .Net core by recreating connections.
