### ISSUE TITLE
Nuget package for Nethereum.KeyStore 2.0.0-rc4

### ISSUE THREAD

**Issue by prasannapattam** [Nethereum/Nethereum#133]
The Nuget Package for Nethereum.KeyStore 2.0.0-rc4 is missing. As a result unable to install Nethereum.Geth 2.0.0-rc4

Error I am getting:
Unable to resolve 'Nethereum.KeyStore (>= 2.0.0-rc4)' for '.NETCoreApp,Version=v1.1'.

**Comment by juanfranblanco** [comment]
In NuGet now
