### ISSUE TITLE
Every function call, get or event log yields no result

### ISSUE THREAD

**Issue by BennyM** [Nethereum/Nethereum#134]
I seem to be able to deploy contracts alright. Yet when I call a function I always get null.

Given the following function:

```
    function hash(State myEnumValue, string secret) returns (bytes32)
    {
        return keccak256(hand, secret);
    }

```
After getting the receipt of the transaction to deploy the contract and storing the address. I later use the address to get a reference and call the function.
```
            var web3 = new Web3("http://myaddress")
            var contract = web3.Eth.GetContract(abi, contractAddress);
            var hashFunc = contract.GetFunction("hash");
            var hashed = await hashFunc.CallAsync<string>(new object[]{1, "salt1"});
```

hashed is always null, am I missing something?

**Comment by juanfranblanco** [comment]
Are you using enough gas to deploy the contract? If you use web3.Eth.GetCode.SendRequestAsync("contractAddress") do you get "0x"?

**Comment by BennyM** [comment]
Well indeed I got 0x so I increased the gas and now it works. Should I not get an exception or something, when using truffle / web3 and you deploy you get an error if you are not providing sufficient gas. I did get an address though so when using web3 I could look at the contract and see that something was deployed but no values where present. Very confusing :)

**Comment by juanfranblanco** [comment]
In this scenario, you have provided enough gas to submit the transaction but not to deploy / store the contract. So your transaction was successful but not the full contract deployment. This is similar when making a transaction, you may not provide enough gas. You could use https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3/TransactionReceipts/TransactionReceiptPollingService.cs#L75 which does your validation on receipt.

**Comment by BennyM** [comment]
Thanks for the tip. Can't use it as is since I'm saving the transactionhash and polling in the background for the receipt but I can adapt the code you showed.

Thanks for the help, great library.

**Comment by juanfranblanco** [comment]
Yes of course, that is a very simple helper class. Tried to be not opinionated on polling
