### ISSUE TITLE
Passing address to constructor of contract

### ISSUE THREAD

**Issue by BennyM** [Nethereum/Nethereum#135]
I'm deploying a contract and eventually receiving a receipt using the code below:
```
await web3.Eth.DeployContract.SendRequestAsync(abi, binary, "0xMyAccount", new HexBigInteger(900000),
               "0xAddress1", "0xAddress2", HexByteConvertorExtensions.HexToByteArray("0xValue1"), HexByteConvertorExtensions.HexToByteArray("0xValue2"));
```
Using the constructor of the contract below:
```
    function Constructor(address addr1, address addr2, bytes32 val1, bytes32 val2){
        address1 = addr1;
        address2 = addr2;
        anArray.push(aStruct({value1: val1, value2: val2}));
    }
```

address1 and address2 are always 0x. Should I be encoding them before calling sendrequest from deploycontract?

**Comment by juanfranblanco** [comment]
No, addresses should be accepted as a string, this should not be an issue.

**Comment by BennyM** [comment]
Yes indeed. I think it was related to my other issue.
