### ISSUE TITLE
Extremely expensive contract deployment Part 2

### ISSUE THREAD

**Issue by aquiladev** [Nethereum/Nethereum#136]
I would like to reopen previous issue #111, but I can't.

So, I figured out what it was and main problem with GasPrice. There is no possibility to set GasPrice for contract deployment. There is default value
```
public static readonly BigInteger DEFAULT_GAS_PRICE = BigInteger.Parse("10000000000000");
```
the price is really big!

For our needs we introduced own Interceptor with code like this:
```
public override async Task<object> InterceptSendRequestAsync<TResponse>(Func<RpcRequest, string, Task<TResponse>> interceptedSendRequestAsync, RpcRequest request, string route = null)
{
	if (request.Method == "eth_sendTransaction")
	{
		TransactionInput transaction = (TransactionInput)request.RawParameters[0];
		transaction.GasPrice = await _web3.Eth.GasPrice.SendRequestAsync().ConfigureAwait(false); //SET GAS PRICE FROM CLIENT
		return await SignAndSendTransaction(transaction).ConfigureAwait(false);
	}
	return await base.InterceptSendRequestAsync(interceptedSendRequestAsync, request, route).ConfigureAwait(false);
}
```
But I think we need to found best way.

**Comment by juanfranblanco** [comment]
Yes, we can add an overload to contract deployment.

**Comment by juanfranblanco** [comment]
@aquiladev  new commits includes gas price as overload on deployment, function and you can set it also in the transaction manager. 

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3.Tests/ContractConstructorDeploymentAndCall.cs#L150

Ill keep it open for your feedback

**Comment by aquiladev** [comment]
@juanfranblanco it looks ok. I would like to build and check it, but it is not so easy to build the solution.

**Comment by juanfranblanco** [comment]
@aquiladev ok I will put it for the rc5 release

**Comment by juanfranblanco** [comment]
"Reduced" to 20 Shannons. An estimator for the latest blocks will be a good idea.

**Comment by juanfranblanco** [comment]
Closing and adding an issue / backlog for the estimation
