### ISSUE TITLE
.NET Core not supported

### ISSUE THREAD

**Issue by djsowa** [Nethereum/Nethereum#138]
Hi,

When I try to install(VS 2017): Install-Package Nethereum.Portable -Pre
I receive an error:
_Install-Package : Package Nethereum.Portable 2.0.0-rc4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Nethereum.Portable 2.0.0-rc4 supports: portable45-net45+win8+wpa81 (.NETPor
table,Version=v4.5,Profile=Profile111)_

Looks like package/lib are not compatibile within .NET Core 1.1 ??

**Comment by juanfranblanco** [comment]
Yes, use Nethereum.Web3.
