### ISSUE TITLE
Question: Use case

### ISSUE THREAD

**Issue by lnaie** [Nethereum/Nethereum#140]
Hi,
First of all an amazing enterprise.

I would like to know, because it's not exactly clear at the first look, if the library can be embedded in a mobile app, let's say built with Xamarin, and run an etherium node right there on the mobile device.

Thanks

**Comment by juanfranblanco** [comment]
Hi,

The library does not implement a full or light node (yet), it will implement eventually the latter. But you can connect (if wanted) to a public node like Infura, or one you host yourself. Check the wallet example for that
