### ISSUE TITLE
NEED HELP WITH FILTERS

### ISSUE THREAD

**Issue by sinhashish** [Nethereum/Nethereum#142]
Hi. Sorry this is not an issue but just a help needed. Couldn't find a better place to ask.

I need to get the details of the latest send ether transaction in my private network. I am trying to use filters.  I understand we have the below available but I just need help on how to use them, and which one is the most appropriate for my purpose? Thanks.

            web3.Eth.Filters.GetFilterChangesForBlockOrTransaction
            web3.Eth.Filters.GetFilterChangesForEthNewFilter
            web3.Eth.Filters.GetFilterLogsForBlockOrTransaction
            web3.Eth.Filters.GetFilterLogsForEthNewFilter
            web3.Eth.Filters.GetLogs
            web3.Eth.Filters.NewBlockFilter
            web3.Eth.Filters.NewFilter
            web3.Eth.Filters.NewPendingTransactionFilter
            web3.Eth.Filters.UninstallFilter

**Comment by juanfranblanco** [comment]
Hi, 

Have a look at this https://nethereum.readthedocs.io/en/latest/contracts/calling-transactions-events/. or this to see if it helps you https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
