### ISSUE TITLE
BouncyCastle Dependency does not support netstandard

### ISSUE THREAD

**Issue by assafY** [Nethereum/Nethereum#143]
When installing the package on a mac using the dotnet-cli, I get the following error

```
Package BouncyCastle 1.8.1 is not compatible with netstandard1.6
```
BouncyCastle only supports .NET 4.5.

**Comment by juanfranblanco** [comment]
Can you add BouncyCastle Portable 1.8.1.1 first

**Comment by assafY** [comment]
That worked, thanks!

**Comment by juanfranblanco** [comment]
Cool, there are 3 different targets at the moment and nuget gets confused.
