### ISSUE TITLE
web3.Miner is missing 

### ISSUE THREAD

**Issue by samuelhmorgan** [Nethereum/Nethereum#144]
Hi,

Im using runtime version v4.0.30319 of the Nethereum.Web3 DLL from Nuget and it appears Web3.Miner is missing. The Web3 class instantiates correctly but there is no property 'Miner' in the class as expected based on the tutorial here 
https://www.youtube.com/watch?v=4t5Z3eX59k4

Did the Property get removed?

**Comment by juanfranblanco** [comment]
Hi v4.0.30319 does not exist, but I guess you are using the newest version.

You need to add the package Nethereum.Geth, this includes the Web3Geth specialised version which includes the miner-specific methods.

**Comment by samuelhmorgan** [comment]
Hi @juanfranblanco ,
Yeah.. I made a mistake with the version number (using V/S assembly version instead) :) 
Thanks - I noticed that Miner was pulled out of the code somewhere around January/Feb 2017.
Cheers
Sam

**Comment by samuelhmorgan** [comment]
Id love to help out btw.. very neat project and exciting what its doing!

**Comment by juanfranblanco** [comment]
Don't worry it happens to all of us :)
