### ISSUE TITLE
Error: No GAS for calling contract method using SendTransactionAsync

### ISSUE THREAD

**Issue by porscheme** [Nethereum/Nethereum#149]
I am using Nethereum library to call a method on a simple contract. it always fail with  below gas price...
Also, I am not able to compile latest Nethereum in VS2015.
Please help.

My c# code snippet
            var transactionHash = multiply.SendTransactionAsync(
                from: senderAddress,
                gas: new HexBigInteger(gas),
                gasPrice: new HexBigInteger(gasprice),
                value: new HexBigInteger(0),
                functionInput: new object[] {7}).Result;

Below is the trace from TX node.

I0704 15:53:18.211015 core/tx_pool.go:534] Promoting queued transaction:
 
	TX(c501e599e7465ea72190893665b389e70fe1f13fdffbc398787d811f90490daa)
	Contract: false
	From:     fdc025c7f4a2308376b5dca7432c49830889d1fd
	To:       fa85abb0d7d364668788f594f1ec599667ff980a
	Nonce:    7
	GasPrice: 0x0
	GasLimit  0x53d9
	Value:    0x
	Data:     0x1df4f1440000000000000000000000000000000000000000000000000000000000000007
	V:        0x1c
	R:        0xca27a383c0cde13b862d9aec1a7044f4a08d8ec54a1c2bdc05eb3ac061eb8b91
	S:        0x33ce03233f1a7e0ac791b0a5bbd6d49e2d10f731b5a107b59bfa481174b1c803
        R:
	Hex:      f88307808253d994fa85abb0d7d364668788f594f1ec599667ff980a80a41df4f14400000000000000000000000000000000000000000000000000000000000000071ca0ca27a383c0cde13b862d9aec1a7044f4a08d8ec54a1c2bdc05eb3ac061eb8b91a033ce03233f1a7e0ac791b0a5bbd6d49e2d10f731b5a107b59bfa481174b1c803
I0704 15:53:18.211437 internal/ethapi/api.go:1197] Tx(c501e599e7465ea72190893665b389e70fe1f13fdffbc398787d811f90490daa) to: &fa85abb0d7d364668788f594f1ec599667ff980a
I0704 15:53:18.211814 miner/worker.go:566] Transaction (c501e599) below gas price (tx=0 Wei ask=18 Shannon). All sequential txs from this address(fdc025c7) will be ignored

**Comment by juanfranblanco** [comment]
Nethereum uses VS2017, hence you won't be able to compile it. You might require to install the latest .net core.

Question do you have any ether? What is the price provided?  It seems that is 0.

**Comment by porscheme** [comment]
Thanks for the reply juanfranblanco.

Nethereum client library.
Private Ethereum blockchain 
AZURESTACK.

-Attached is my simple HelloWorld.sol contract
[HelloWorld.sol.txt](https://github.com/Nethereum/Nethereum/files/1123200/HelloWorld.sol.txt)
-Complied the contract with solc (download from https://github.com/ethereum/solidity/releases)
-Created the contract successfully.
-Calling contract any method fail if SendTransactionAsync used.
-Result of contract method is zero is CallAsync was used.

My account has enough ether. Below is my input to SendTransactionAsync API
    From:0xfdc025c7f4a2308376B5dcA7432c49830889d1FD
    gas:0x53d9
    gasPrice:0xA7359400
    value:0
    functionInput:7


Below is what I read from the transaction receipt.
     Hash: 0xd3b34bd756e7bab8aa6b5cb39af0259e6e5bb436f80c320faad2d19224e6eccc
     Nonce: 0xb
     BlockHash: 0x0000000000000000000000000000000000000000000000000000000000000000
     BlockNumber:
     TransactionIndex: 0x0
     Value: 0x0
     From: 0xfdc025c7f4a2308376b5dca7432c49830889d1fd
     To: 0xa4e0b2abc1e36e57af049ffee6a0799b9dec54e3
     Gas: 0x53d9
     GasPrice: 0x0
     Input: 0x1df4f1440000000000000000000000000000000000000000000000000000000000000007


Below is what is recorded on TX node
I0704 23:59:07.882704 core/tx_pool.go:534] Promoting queued transaction:
 
     TX(d3b34bd756e7bab8aa6b5cb39af0259e6e5bb436f80c320faad2d19224e6eccc)
     Contract: false
     From:     fdc025c7f4a2308376b5dca7432c49830889d1fd
     To:       a4e0b2abc1e36e57af049ffee6a0799b9dec54e3
     Nonce:    11
     GasPrice: 0x0
     GasLimit  0x53d9
     Value:    0x0
     Data:     0x1df4f1440000000000000000000000000000000000000000000000000000000000000007
     V:        0x1b
     R:        0xd22c277adff942ad91e02859309496a9370a71997be0142ce813b361d43a8d0
     S:        0x206aa4f03533d0252e8dcae5ecbfdddd7af3b9d21b2c07d98ead6c7f4c04e32
     Hex:  f8830b808253d994a4e0b2abc1e36e57af049ffee6a0799b9dec54e380a41df4f14400000000000000000000000000000000000000000000000000000000000000071ba00d22c277adff942ad91e02859309496a9370a71997be0142ce813b361d43a8d0a00206aa4f03533d0252e8dcae5ecbfdddd7af3b9d21b2c07d98ead6c7f4c04e32
      I0704 23:59:07.883249 internal/ethapi/api.go:1197] Tx(d3b34bd756e7bab8aa6b5cb39af0259e6e5bb436f80c320faad2d19224e6eccc) to: &a4e0b2abc1e36e57af049ffee6a0799b9dec54e3
      I0704 23:59:07.883679 miner/worker.go:566] Transaction (d3b34bd7) below gas price (tx=0 Wei ask=18 Shannon). All sequential txs from this address(fdc025c7) will be ignored

**Comment by porscheme** [comment]
Found why CallAsync wasn't working, my contract was never mined because of low gas. 
After I increased gas my contract was mined and able make CallAsync calls.

But SendTransactionAsync wasn't working?

**Comment by juanfranblanco** [comment]
Are you ok now?

**Comment by juanfranblanco** [comment]
Closing old issue
