### ISSUE TITLE
How do I set the gasPrice when sending a transaction?

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#15]

**Comment by slothbag** [comment]
It seems as all my tx construction and signing will happen on the browser side I don't really need to do this in Nethereum.

Still, it would be good to know how to do it.

**Comment by juanfranblanco** [comment]
in one of the overloads ie: multiplyFunction.SendTransactionAsync(addressFrom, null, new HexBigInteger(6000), 69); or using the TransactionInput

**Comment by slothbag** [comment]
Thanks, I had a look at TransactionInput and couldn't find any reference to gasPrice though..

[src/Nethereum.RPC/Eth/DTOs/SendTransactionInput.cs](src/Nethereum.RPC/Eth/DTOs/SendTransactionInput.cs)

**Comment by juanfranblanco** [comment]
an inherits from CallTransaction (or something similar)
