### ISSUE TITLE
Self compiled contract issue

### ISSUE THREAD

**Issue by sridharanprasanna** [Nethereum/Nethereum#150]
If I use the tutorial abi and bytecode as is, it works fine. However if I compile the .sol myself using the VS Code Sol compiler, it is huge bytecode compared to one in tutorial for the same Sol file. The deployment using code works fine, if I use the testchain (it gives invalid opcode with rpctest client). The functions can also be found with the hash, however execution of function returns nothing (null for any string return functions and 0 for integer return functions). I have returned hardcoded values in function.

Sol compiler version: 0.0.22
Nethereum.Web3, Version=2.0.0.0

Am I missing something?

**I am new to blockchain and this is almost just the first day of coding.**

**Comment by sridharanprasanna** [comment]
Gas gas gas!! sorry, my issue not setting gas properly and relying on the default gas.

**Comment by juanfranblanco** [comment]
Glad you got sorted. yes gas is the most common issue
