### ISSUE TITLE
OfflineTransactionSigner should be outside Web3 class

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#151]
I'm doing several abstractions with my code that consumes Nethereum APIs and I've reached a point in which I've realised that there's no point in OfflineTransactionSigner being a member of Web3 because Web3 receives a URL in the constructor, however OfflineTransactionSigner, being Offline, means that it doesn't need this dependency at all.

Because of this I have to apply some workarounds in my code, but it would be nice if we could decouple it in Nethereum.

**Comment by knocte** [comment]
Maybe it's enough if we make it static?

**Comment by juanfranblanco** [comment]
Just use the signer libraries ?

**Comment by juanfranblanco** [comment]
That has been kept for compatibility with 1.0, I will mark it as deprecated. Also you do need a nonce to sign transactions.

**Comment by knocte** [comment]
Yes but that nonce can come from a previous run (e.g. pre-generating transaction online -> signing offline).

>  I will mark it as deprecated. 

Sounds good.

**Comment by juanfranblanco** [comment]
I actually I have opted for the static option, even if I am not very keen on statics as they cannot be replaced the implementations. 

But at the end of the day, Web3 core function is to be a simplification wrapper, if you want a different implementation you can inherit/ modify or create a custom TransactionSigner.

**Comment by juanfranblanco** [comment]
Thanks!
