### ISSUE TITLE
the ToWei method product wrong result.

### ISSUE THREAD

**Issue by diykid** [Nethereum/Nethereum#152]
the following unittest can not pass
`        [TestMethod]
        public void TestToWei()
        {
            var web3 = new Nethereum.Web3.Web3();
            var result1 = web3.Convert.ToWei(10m);
            var result2 = web3.Convert.ToWei(100m);

            Assert.AreNotEqual(result1.ToString(),result2.ToString());
        }`

**Comment by diykid** [comment]
if we convert to biginteger it will pass
`      [TestMethod]
        public void TestToWei1()
        {
            var web3 = new Nethereum.Web3.Web3();
            var result1 = web3.Convert.ToWei(new BigInteger(10m));
            var result2 = web3.Convert.ToWei(new BigInteger(100m));

            Assert.AreNotEqual(result1.ToString(), result2.ToString());
        }`

**Comment by juanfranblanco** [comment]
What version are you using?

**Comment by juanfranblanco** [comment]
Don't worry I think I have spotted the issue, thanks.

**Comment by diykid** [comment]
thanks, wish it can be fixed next release:)

**Comment by juanfranblanco** [comment]
Fixed on the latest commit
