### ISSUE TITLE
Add DTOS in Parity for trace modules

### ISSUE THREAD

**Issue by jhorak01** [Nethereum/Nethereum#153]
First off, great library. Further support for the Parity modules would be a great addition if it's not in the road map - particularly, I find the trace module to be most effective for tracing transactions.

**Comment by juanfranblanco** [comment]
Thanks for the feedback, I'll prioritise those.

**Comment by nvtaveras** [comment]
@juanfranblanco Hi Juan, 

I was wondering if there's any work currently being done on this? I ran into a case where I need to use Parity's trace module as well.

I wouldn't mind having a try at implementing this with some guidance, but I'm not very familiar with how modules that are specific to parity/geth are abstracted in the code.

**Comment by juanfranblanco** [comment]
Ill push something this week for the trace modules, I got pushed with other priorities.

**Comment by juanfranblanco** [comment]
Feel free to ask / remind me any time if you dont see something moving.. too many things too little time :D

**Comment by nvtaveras** [comment]
Awesome, thanks a lot for your work! :)

**Comment by milkeg** [comment]
Hello Juan,
Awesome, waiting for it too :)
Thank you

**Comment by milkeg** [comment]
Hi @juanfranblanco 
Any update on this issue?
Thanks a lot

**Comment by juanfranblanco** [comment]
I forgot to mention, trace modules are the latest release.

**Comment by milkeg** [comment]
Thank you very much Juan :)

**Comment by nvtaveras** [comment]
@juanfranblanco Quick question: Is there any particular reason why you didn't add the DTO's for the trace_transaction RPC call? Is it because of the lack of documentation for the response in Parity's Wiki? I noticed the implementation for the method returns a JObject.

I'm working on this and can contribute it to the project, but want to know what is your take on this first.

Thanks!

**Comment by juanfranblanco** [comment]
Documentation it is one of the reason, but also the dynamic nature of the structure of logs. Feel free to make a pull request with a DTO and let's see how it goes. We can always revert if needed (Everyone will understand)

**Comment by nvtaveras** [comment]
By looking at the structure of the response ([0]) I'm not entirely sure of the meaning of the "traceAddress" array and the type of data it can contain (seems to be an array of Integers?).

Would you be agains't of a DTO which excludes that field? 

[0]: https://github.com/paritytech/parity/wiki/JSONRPC-trace-module#trace_transaction

**Comment by juanfranblanco** [comment]
Parity docs get outdated very quickly. What you could do is create an extra method to deserialise the JToken so you get the best of both worlds

**Comment by juanfranblanco** [comment]
So if you miss an attribute it can be added later

**Comment by juanfranblanco** [comment]
Change the Issue now to add DTOs

**Comment by juanfranblanco** [comment]
Parity / OE is getting deprecated.
