### ISSUE TITLE
Best way to view all transactions for a given account.

### ISSUE THREAD

**Issue by simonpbond** [Nethereum/Nethereum#155]
Is it possible using Nethereum (or can you recommend the best method) to retrieve a list of all transactions for a given account number?

**Comment by jerryhorak** [comment]
Etherscan has an API to pull this. Else, you'll have to iterate through the blocks it seems. It might even make sense to migrate the entire chain to a local db.

**Comment by simonpbond** [comment]
Thanks for the recommendations Jerry, that's what I was thinking after doing some research today.

Appreciated.

**Comment by userid2018** [comment]
@simonpbond could you please point out to resources you used to implement this ?

**Comment by simonpbond** [comment]
I couldn't find a simple way of doing this.

As a workaround I looked in to reading every single block on the chain (starting at 0) using Nethereum and then pushing each transaction one by one as a record into a db. Then keeping a service running to constantly read each new block minute by minute, keeping the db up to date. Then just querying my own db transaction list of the blockchain.

No idea if there is a better way to approach this.
I was hoping for the functionality to be built in to Nethereum. 

[](https://github.com/Nethereum/Nethereum/issues/156)
