### ISSUE TITLE
Need help with retrieving all transactions from a block.

### ISSUE THREAD

**Issue by simonpbond** [Nethereum/Nethereum#156]
Hi guys, sorry to be bothering you with my questions on here again, but having an issue I can't seem to figure out.

I'm trying to specify the block number (I guess, the block height) and retrieve all transactions. 
This seems to work when I specify a large block number, however when looking at etherscan's first block 0, it shows 8893 transactions.

When I input '0' into my code for the block number, I receive no transactions.
Any assistance as to where I'm going wrong would be greatly appreciated!

Can't seem to get the code formatted properly on here (apologies).

`static void Main(string[] args)
        {
            var web3 = new Nethereum.Web3.Web3();
             //string account = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
             
            int blockNumber = 450000;

            //var balanceTask = web3.Eth.GetBalance.SendRequestAsync(account);
            //balanceTask.Wait();
            //var balance = balanceTask.Result;

            //Console.WriteLine("account " + account + "; balance in ether: " + web3.Convert.FromWei(balance.Value));
                        
            HexBigInteger myhexBigInt = new HexBigInteger(blockNumber);
            
            var block = web3.Eth.Blocks.GetBlockWithTransactionsByNumber.SendRequestAsync(myhexBigInt);
            block.Wait();

            Console.WriteLine("block: " + blockNumber.ToString() + " transaction count: " + block.Result.Transactions.Count());

            
            var blockTxs = web3.Eth.Blocks.GetBlockNumber.SendRequestAsync();
            blockTxs.Wait();

            Console.WriteLine("last blocks: " + blockTxs.Result.Value.ToString());

            int myCount = 0;
            if (block != null && block.Result.Transactions != null)
            {
                foreach (Nethereum.RPC.Eth.DTOs.Transaction e in block.Result.Transactions)
                {
                    myCount += 1;

                    Console.WriteLine("Transaction Count: " + myCount.ToString());
                    
                        Console.WriteLine("  tx hash          : " + e.TransactionHash + "\n"
                          + "   nonce           : " + e.Nonce.Value + "\n"
                          + "   blockHash       : " + e.BlockHash + "\n"
                          + "   blockNumber     : " + e.BlockNumber.Value + "\n"
                          + "   transactionIndex: " + e.TransactionIndex.Value + "\n"
                          + "   from            : " + e.From + "\n"
                          + "   to              : " + e.To + "\n"
                          + "   value           : " + web3.Convert.FromWei(e.Value.Value) + "\n"
                          + "   time            : " + block.Result.Timestamp.Value + "\n"
                          + "   gasPrice        : " + web3.Convert.FromWei(e.GasPrice.Value) + "\n"
                          + "   gas             : " + e.Gas.Value + "\n"
                          + "   input           : " + e.Input);

                    Console.WriteLine("Press Any Key");
                    Console.ReadLine();
                }
            }

            Console.WriteLine("Press any key to close...");
            Console.ReadLine();
        }`

**Comment by jerryhorak** [comment]
Technically, those aren't transactions because that's the genesis block.  The 8893 number represents the number of accounts pre-allocated with ether. Please see the original genesis json:

[https://github.com/jerryhorak/EthereumGenesis/blob/master/genesis_frontier.json](url)

**Comment by simonpbond** [comment]
and Jerry, how would I go about retrieving or identifying pending transactions?

**Comment by juanfranblanco** [comment]
@simonpbond Use https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/Eth/Blocks/EthGetBlockByNumber.cs

Using the block parameter, pending.

Also check out the Nethereum.BlockchainStorage
