### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by bijeebuss** [Nethereum/Nethereum#160]
version: 2.0.0-rc5
I am receiving this error when trying to send a transaction to a contract function. Here is my code without the actual addresses and abi. I know the account has enough to fund it based on the values I put there. Also I tested the same thing using the javascript API and it worked fine. Is the gas price supposed to be in gwei instead of wei?

```
public class ContractService
    {

        private readonly Web3 _web3;
        private readonly string _accountAddress = "MyAddress";

        private const string ContractAddress = "ContractAddress";
        private const string ContractAbi = @"contract_abi";
        private readonly Contract _contract;


        public ContractService()
        {
            var account = new ManagedAccount(_accountAddress, "password");
            _web3 = new Web3(account, "http://localhost:8545");
            _contract = _web3.Eth.GetContract(ContractAbi, ContractAddress);
        }
        public string MyFunction()
        {
            var myFunction = _contract.GetFunction("myFunction");

            var gasLimit = new HexBigInteger(0xC3500);
            var gasPrice = new HexBigInteger(0x4A817C800);
            var value = new HexBigInteger(0xB1A2BC2EC50000);

            return myFunction.SendTransactionAsync(_accountAddress, gasLimit, gasPrice, value).Result;
        }
    }
```

Also when I tried calling this without specifying the gas price it set the gas price to 10,000 Gwei and I got charged a $100 fee.

**Comment by juanfranblanco** [comment]
Hi,

A quick note, you can use integers / long when creating a new instance of HexBigInteger, these values are converted to Hex internally.

Your gas price is the default 20 shannon / gwei in wei : 20000000000, so that should not be an issue.

You are sending 0.5 Ethers

and your gas limit is 800000

If you are using a client like geth / parity, (as I can see with the Managed Account) it will use the default values of the client.

Now to your problem, if you believe you have enough Ether to fund this transaction, it may be that you have not fully sync your client.

**Comment by bijeebuss** [comment]
Correct me if I'm wrong but isnt 0xB1A2BC2EC50000 in wei equivalent to 0.05 ETH. But either way I should have enough in the account. I tried using a keystore instead of a managed account and now the SendTransactionAsync call is never completing. If my node isnt fully synced why would the javascript w3 library work? The log is spitting out this

`INFO [07-25|07:23:29] Imported new chain segment               blocks=1  txs=30   mgas=0.860  elapsed=122.167ms mgasps=7.039  number=4071965 hash=a1aff9…04d5f5`

which appears to be the latest block so that means it synced right?
Ifi t helps my geth version is  1.6.7-stable-ab5646c5

**Comment by juanfranblanco** [comment]
Yes, it is a typo on the Ether. well spotted.

Being in sync is important so the client can validate you have enough ether to send the transaction. I thought that was your issue. 

If you are using your key store account.  you can connect to a public node which is synced like infura. I am assuming you are targeting the main chain or a public testnet. 

Javascript vs .Net does not make any difference if you use the same parameters.

**Comment by bijeebuss** [comment]
I tried using Infura and the same thing is happening, its just hanging on SendTransactionAsync forever.

**Comment by bijeebuss** [comment]
So it looks like when I try to set gas price like this the transaction object has null for GasPrice
`var transaction = depositFunction.CreateTransactionInput(_accountAddress, gasLimit, gasPrice, value);`

which would explain why it says I dont have enough gas since the default gas price is 10000.
As for why it hangs when I dont use a managed account I still dont know.

For now ill just set the default gas price and use a managed account

**Comment by juanfranblanco** [comment]
Thanks! Now I found the issue, with the gas price null and default values. I am releasing the 20 shannon default today ASAP.

For a more simpler control of GasPrice and Gas, you can use the TransactionManager, default values.

For example:

  var web3 = new Web3(new Account("privateKey"));
//or 
 web3 = new Web3(new ManagedAccount("address", "password"));
  web3.TransactionManager.DefaultGasPrice = new BigInteger("XXX");
  web3.TransactionManager.DefaultGas = new BigInteger("XXX");

**Comment by juanfranblanco** [comment]
Check the new update, it defaults to 20 shannon, and fixes the null issue.

**Comment by bijeebuss** [comment]
Thanks! should I open a new ticket for the transaction not sending error?

**Comment by bijeebuss** [comment]
Ok I found another clue. When I use 
`return myFunction.SendTransactionAsync(_accountAddress, gasLimit, gasPrice, value).Result;`
it never returns but when I use 
`return await myFunction.SendTransactionAsync(_accountAddress, gasLimit, gasPrice, value);`
it works fine

**Comment by juanfranblanco** [comment]
I have checked and all the ConfigureAwaits are set for both Managed and Offline signing. Have you upgraded to 2.0.0.rc6-2? It has the new defaults

**Comment by bijeebuss** [comment]
Environment is Web .NET 4.5.2 I have 2.0.0-rc6 but I dont see 2.0.0-rc6-2 in the package manager

**Comment by juanfranblanco** [comment]
I see, so you are using the portable version. Which is the same as rc6-2, that was a specific release.
On web there are issues when using Result due to threading, hence my comments around the ConfigureAwait.

**Comment by juanfranblanco** [comment]
BTW the issues are general .net issues :) ConfigureAwait solves them.

**Comment by bijeebuss** [comment]
Ok, I think that solves this then. Thanks
