### ISSUE TITLE
call contract function failed

### ISSUE THREAD

**Issue by weitaolee** [Nethereum/Nethereum#163]
`var abi = "[{\"constant\":false,\"inputs\":[{\"name\":\"_token\",\"type\":\"address\"},{\"name\":\"balance\",\"type\":\"uint256\"}],\"name\":\"claimToken\",\"outputs\":[],\"payable\":false,\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"kill\",\"outputs\":[],\"payable\":false,\"type\":\"function\"},{\"inputs\":[],\"payable\":false,\"type\":\"constructor\"},{\"payable\":true,\"type\":\"fallback\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"name\":\"_token\",\"type\":\"address\"},{\"indexed\":false,\"name\":\"balance\",\"type\":\"uint256\"}],\"name\":\"Claim\",\"type\":\"event\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"name\":\"_token\",\"type\":\"address\"},{\"indexed\":false,\"name\":\"balance\",\"type\":\"uint256\"}],\"name\":\"NotClaim\",\"type\":\"event\"}]";
`
`var _token="0xa74476443119a942de498590fe1f2454d7d4ac0d";`
`try
 {     
         //unlock _mainAccount first
        var unlockAccountResult = await _web3.Personal.UnlockAccount.SendRequestAsync(_mainAccount, password, 1200);
         //if unlock success, continue
          var contract = _web3.Eth.GetContract(abi, "0x9023af28273d38b2da8af755bada2e3ea943be27");
          var claimFunction = contract.GetFunction("claimToken");
          var sendValue = UnitConversion.Convert.ToWei(0.001, UnitConversion.EthUnit.Ether);
          var result = await claimFunction.SendTransactionAsync(_mainAccount, new HexBigInteger(300000), new HexBigInteger(0), _token, sendValue );
  }
  catch (Exception ex)
 {

  }`
![image](https://user-images.githubusercontent.com/4479969/28666662-ee09e382-72fa-11e7-8373-59c90d5cc6ea.png)

I see submit it sucess, but never find this txid on etherscan.io, I have test many times(with restart geth)

I am using geth 1.6.7, anything wrong with my code?

When I use parity call "claimToken" function, sucess. so the contact have no problem. this is the sucess tx:
https://etherscan.io/tx/0x9ad535af5a6085a9638eed69a3464b76e30e0e41c267d8f898339d24d089ece4

**Comment by weitaolee** [comment]
@juanfranblanco could you help it?

**Comment by juanfranblanco** [comment]
You may not have enough ether? So the transaction is sent but later on rejected? You could also point to infura, and use the Account object

**Comment by weitaolee** [comment]
Yes,have enough ether.this is the mainaccount (https://etherscan.io/address/0x0089a73a2b8ed59b4caf457898066ff6ffb7b0f7),

**Comment by juanfranblanco** [comment]
Have you upgraded to the latest? Just to validate versions.

**Comment by weitaolee** [comment]
I'm using 2.0-rc6

**Comment by sevenbitsAbhishek** [comment]
I am also facing same issue.
I am using testnet.
Please help me.

**Comment by diykid** [comment]
with same issue
pls help to have a look, tks.

**Comment by diykid** [comment]
it works with testrpc client,but does not work with geth

**Comment by diykid** [comment]
it works now magically, maybe it is not a bug

**Comment by juanfranblanco** [comment]
Make sure you use the latest 2.0.0 rc6.
Also set the default values using the TransactionManager as follows:
 
web3.TransactionManager.DefaultGas = Transaction.DEFAULT_GAS_LIMIT;
web3.TransactionManager.DefaultGasPrice = Transaction.DEFAULT_GAS_PRICE;

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3/Web3.cs#L30-L32

**Comment by sevenbitsAbhishek** [comment]
Upgraded to latest 2.0.0 rc6
Created a contract with Mist. Contract Execution works grate with Mist.
Check below link
https://ropsten.etherscan.io/tx/0x8b400316d2019fed94f4890724fbfd8c707971a43a4a533f3960347abca1ea06 

Now I am trying to execute contract from below code
But it give me "Additional information: intrinsic gas too low" error. 
You can check balance 
https://ropsten.etherscan.io/address/0x3A2E308DbB6c1A2b255b769f34f33E7cCdD3c042

var senderAddress = "0x3A2E308DbB6c1A2b255b769f34f33E7cCdD3c042";            
ManagedAccount account = new ManagedAccount(senderAddress, "xxxxxxxxxx");
string abi = "api";
var contractAddress = "0x95A0285Af48C9bCD78C9831aE17383b26F368C18";
var web3 = new Web3(account);
bool unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, "xxxxxxxxxx", 60);
Contract con = web3.Eth.GetContract(abi, contractAddress);
var x= await con.GetFunction("notarize").CallAsync<string>("test from code");
var y= await con.GetFunction("notarize").SendTransactionAsync(senderAddress,"test with data");

**Comment by diykid** [comment]
it's really magically, it does not work now.....

**Comment by juanfranblanco** [comment]
Put those settings on Web3, I'll push a release later on

**Comment by sevenbitsAbhishek** [comment]
When I pass below code it gives same error "Additional information: intrinsic gas too low"
web3.TransactionManager.DefaultGas = Transaction.DEFAULT_GAS_LIMIT;
web3.TransactionManager.DefaultGasPrice = Transaction.DEFAULT_GAS_PRICE;

But when I pass below code it works 
web3.TransactionManager.DefaultGas = BigInteger.Parse("290000");
web3.TransactionManager.DefaultGasPrice = Transaction.DEFAULT_GAS_PRICE;

Not able to understand why but it works.

**Comment by juanfranblanco** [comment]
The total amount of gas varies depends on your transaction contract's complexity, storage, etc.  So when interacting with a contract you need more gas than the default one.

But your gas price can remain the same.

**Comment by juanfranblanco** [comment]
Default values added in rc7
