### ISSUE TITLE
Invalid Function.EstimateGasAsync

### ISSUE THREAD

**Issue by olekon** [Nethereum/Nethereum#164]
Hello. 
I am trying to calculate gas amount required for transaction and keep getting too high results.
Here is code sample 

```
var contract = web3.Eth.GetContract(abi, contractAddres);
Function markFunction = contract.GetFunction("markAsDelivered");
var res1 = markFunction.EstimateGasAsync(2);
res1.Wait();
```
contract function itself looks like 
```
function markAsDelivered(uint256 purchaseId) {
        VendorInformation vendorInfo = VendorInformation(owner);

        require (msg.sender == vendorInfo.vendor());
        require(purchaseId < purchases.length);
        require(!purchases[purchaseId].delivered); 

        purchases[purchaseId].delivered = true;
    }
```

If I am trying to execute this transaction via Mist (call contract method) the estimated gas amount is about 46000. However res1.Result equals 4712388. I guess that is close to block gas limit.
Am I doing something wrong or is it a bug?

**Comment by juanfranblanco** [comment]
Estimate Gas in geth is not accurate.
