### ISSUE TITLE
Block with no transactions fails to convert

### ISSUE THREAD

**Issue by gordns** [Nethereum/Nethereum#166]
In the Unity release, using the EthGetBlockWithTransactionsHashesByNumberUnityRequest method fails when there is no transactions in the requested block (for example block 4132389). 

Error message:
System.Exception: Unable to convert the result to type Nethereum.RPC.Eth.DTOs.BlockWithTransactionHashes

**Comment by juanfranblanco** [comment]
Thanks I will have a look

**Comment by juanfranblanco** [comment]
This should fix it. BigInteger in 3.5 from mono was not accepting default values https://github.com/Nethereum/Nethereum/commit/9f0eb76da617c8a6866b695fe68c833c099e0db1
