### ISSUE TITLE
Add HexBigInteger Ctor with no param

### ISSUE THREAD

**Issue by Bdussart** [Nethereum/Nethereum#167]
Hi Dude !

Nice works that you've done !

I've a little (I hope) request, 
I would like to Serialize my block into a JsonFile, 
but when i tried to deserialize it, i got an exception from JavaScriptSerializer or DataContractJsonSerializer : 
They can't deserialize it because the HexBigInteger  class didn't have a ctor with no param.

Can you have a look on that please ?

Thank you :).

Brice.

**Comment by juanfranblanco** [comment]
The HexTypes have: https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Hex/HexTypes/HexBigInteger.cs#L7, this way they can be deserialise already when receiving json rpc responses.

**Comment by Bdussart** [comment]
Yeah, it's working for Json Rpc Responses,
but not to deserialize from a file : 
![image](https://user-images.githubusercontent.com/31310297/29665136-0080090e-88d3-11e7-827a-7c9d7277e3c4.png)
(Sorry for the French error message) this message means : There is no Ctor with no parameter for the type : Nethereum.Hex.HexTypes.HexBigInteger.

**Comment by juanfranblanco** [comment]
Use Newtonsoft instead.

**Comment by Bdussart** [comment]
You're right, it's working with Newtonsoft.

Thank you for your help.

Brice.
