### ISSUE TITLE
Question: is the lack of Bytes16 encoder/decoder on purpose?

### ISSUE THREAD

**Issue by kirsis** [Nethereum/Nethereum#169]
I noticed that an event with bytes16 returns 32 bytes padded with 16 zeros. E.g. instead of e8cec183346848debfc6a95824a780d5 I get e8cec183346848debfc6a95824a780d500000000000000000000000000000000.

I looked into the ABIType class, and saw that it only supports bytes and bytes32, but there is no bytes16 support.

This seems like a fundamental type, so I'm wondering - is there's a reason why it's omitted?

**Comment by juanfranblanco** [comment]
Not other reason that all byte types are "transferred" padded to 32 bytes, from 1 to 32. I did not see it as a priority as the user will know what length they want and can just use .Take(16) in your case.

Nevertheless, now that you have raised it, it is back in the TODO list.

**Comment by kirsis** [comment]
I see, thanks for the info. I suspect the lack of a Bytes16Type causes issues when a smart contract function expects a bytes16 value as the first parameter (causes the rest of the values to have their bytes offset).

I submitted a PR for this #170.

**Comment by juanfranblanco** [comment]
No, everything should be padded with 32 bytes, your PR brings now that issue for bytes16. Actually, now we don't have a type to encode/decode the other types. Bytes32 is accepted normally as a string too (historical reasons), but not bytes16.

I'll get it done now then.

**Comment by kirsis** [comment]
Shoot, you're right. I should've read http://solidity.readthedocs.io/en/develop/abi-spec.html#abi first, sorry. 

Thanks for looking at this 👍

**Comment by juanfranblanco** [comment]
@kirsis  I have added all the bytes types now, let me know how it goes. Thanks again :)
