### ISSUE TITLE
Support for Real Types Solidity / ABI for encoding / decoding contracts using Big Integer or another BigNumber implementation

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#17]
Add support for encoding / decoding of Real Types using BigInteger or BigNumber Library (Need to find one).
Create encoding / decoding to match (or similar, will never be the same) web3.js implementation, and unit tests.

**Comment by ByronAP** [comment]
.net now has BigInteger built in since 4.0 https://msdn.microsoft.com/en-us/library/system.numerics.biginteger%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396 using fixed point precision it can be used to work with big fractional types

**Comment by juanfranblanco** [comment]
Thanks :+1: , BigInteger is used everywhere already, was thinking of matching web3.js implementation (BigNumber) or as you said if BigInteger is already providing us this, will use this. Ill edit the OP to clarifiy this.
