### ISSUE TITLE
Inconsistent detection of Events

### ISSUE THREAD

**Issue by Baaleos** [Nethereum/Nethereum#175]
Given the following contract code:
  

```
event WorldCreated(bytes32 indexed worldName, address indexed sender, address result );
   //Only ever going to retrieve the worldCreated result via event - no return value needed
	function createWorld(bytes32 name){
		World w = new World(name);
		worldContracts.push(w);
		NamesIndex[name] =worldContracts.length-1;
		WorldCreated(name,msg.sender,w);
	}
```

When I monitor the events on the contract in mist/Ethereum Wallet - I can see the events 100% of the time.
When I run the following code in .Net:

```

 public class WorldCreatedEvent
        {
            [Parameter("bytes32", "worldName", 1, true)]
            public string worldName { get; set; }

            [Parameter("address", "sender", 2, true)]
            public string Sender { get; set; }

            [Parameter("address", "result", 3, false)]
            public string Result { get; set; }

        }
```
```
public static string CreateWorld(string world)
        {

            var web3 = new Web3(Resources.Server);
             // Contract address
            var contract = web3.Eth.GetContract(Resources.WorldAdmin, address);

            var add = contract.GetFunction("createWorld");                         // Add method
            var worldCreatedEvent = contract.GetEvent("WorldCreated");
            var filterAll = worldCreatedEvent.CreateFilterAsync().Result;
            var totalGas = GenericUtil.GetGasPrice(add, world);
            UnlockAccountForTransaction();
            var callResult = add.SendTransactionAsync("0x13111c7C98dFb371A4dd6cD1B1D9E6285bE68d2e",totalGas,new HexBigInteger(0), world).Result;
            var theResult = GenericUtil.GetReceiptAsync(web3, callResult);
            System.Threading.Thread.Sleep(1000);
            var log = worldCreatedEvent.GetAllChanges<WorldCreatedEvent>(filterAll).Result;
            while (log.Count == 0)
            {
                log = worldCreatedEvent.GetAllChanges<WorldCreatedEvent>(filterAll).Result;
                Thread.Sleep(1000);
            }

            return log[0].Event.Result;

        }

```
Even though this C# code is triggering the event, the GetAllChanges (with and without an indexed filter value) - seems to only pick up the event say 50-60% of the time.
This prevents me from getting new contract addresses created from my contract methods.

I can see the event appearing in the Wallet Application, so I know it isnt a gas issue - as if it were, then the event wouldnt appear in Ethereum Wallet or in .Net.

Any ideas on how to resolve?

Using Nethereum.Portable
1.0.6
.Net 4.5

Ignore this - I am updating to v2 now.
For some reason nuget was not showing any updates when I went to updates tab.

**Comment by Baaleos** [comment]
Note- tested on 
<package id="Nethereum.Portable" version="2.0.0-rc7" targetFramework="net45" />

Just got stuck in an infinite loop - event not being detected by .Net

**Comment by Baaleos** [comment]
Seems that GetAllChanges is less reliable than GetFilterChanges
GetFilterChanges seems to be detecting the events alot more reliably than the GetAllChanges

**Comment by juanfranblanco** [comment]
You may want to supply the block number range

**Comment by Baaleos** [comment]
Closing this now - as using GetFilterChanges seems to be working.
Although GetAllChanges might need some investigation - as you would expect it to be encompassing of GetFilterChanges also.
