### ISSUE TITLE
Encoding of string types - invalid argument 0: hex has invalid length 64 after decoding

### ISSUE THREAD

**Issue by Baaleos** [Nethereum/Nethereum#177]
There might be an encoding issue with string types in 'CreateFilterAsync'

Calling this C# function:
```

public Player RegisterPlayer(string firstname, string lastname)
        {
            
            var register = _theContract.GetFunction("registerPlayer");
            var registerPlayerEvent = _theContract.GetEvent("PlayerRegistered");
            var filterAll = registerPlayerEvent.CreateFilterAsync(firstname, lastname).Result;
            var totalGas = GenericUtil.GetGasPrice(register, firstname, lastname);
            WorldAdmin.UnlockAccountForTransaction();
            var callResult = register.SendTransactionAsync("0x13111c7C98dFb371A4dd6cD1B1D9E6285bE68d2e", totalGas, new HexBigInteger(0), firstname, lastname);

            var theResult = GenericUtil.GetReceiptAsync(callResult.Result);
            var log = registerPlayerEvent.GetFilterChanges<PlayerRegisteredEvent>(filterAll).Result;
            while (log.Count == 0)
            {
                log = registerPlayerEvent.GetFilterChanges<PlayerRegisteredEvent>(filterAll).Result;
                Thread.Sleep(1000);
            }

            return new Player(log[0].Event.player);
        }
```

It is failing on the 

`var filterAll = registerPlayerEvent.CreateFilterAsync(firstname, lastname).Result;`

with an aggregate exception:
invalid argument 0: hex has invalid length 64 after decoding

The event is defined as:
event PlayerRegistered(string indexed firstname, string indexed lastname, address player);

The value for firstname in the function c# is 'Jonny'.

 The ABI shows the event to be defined as:

> {
> 	"anonymous": false,
> 	"inputs": [{
> 		"indexed": true,
> 		"name": "firstname",
> 		"type": "string"
> 	},
> 	{
> 		"indexed": true,
> 		"name": "lastname",
> 		"type": "string"
> 	},
> 	{
> 		"indexed": false,
> 		"name": "player",
> 		"type": "address"
> 	}],
> 	"name": "PlayerRegistered",
> 	"type": "event"
> }

And my C# model for the event is also defined below - although, I don't think that is the problem, since it is failing before it gets as far as using the PlayerRegisteredEvent type.
```
public class PlayerRegisteredEvent
        {
            [Parameter("string", "firstname", 1, true)]
            public string firstname { get; set; }

            [Parameter("string", "lastname", 2, true)]
            public string lastname { get; set; }

            [Parameter("address", "player", 3, false)]
            public string player { get; set; }

        }

```

**Comment by juanfranblanco** [comment]
Strings, when indexed, the value is the keccak hash

**Comment by Baaleos** [comment]
What argument type should I be using then?
Do I need to calculate the keccak hash of the string before passing it into the filter then?

**Comment by juanfranblanco** [comment]
yes that should work
