### ISSUE TITLE
Out of date assemblies for .NET Standard - Newtonsoft

### ISSUE THREAD

**Issue by ryanrlj** [Nethereum/Nethereum#178]
I'm having an issue that I'm having trouble getting around. The nethereum project is referencing Newtonsoft.Json 9.0.1, however, I've got several other dependencies attempting to load Newtonsoft 10.0.3.  This is causing an update loop, and ultimately the run time for one of the projects isn't loading the correct assembly. 

Is it possible to update your nuget references to Newtonsoft?

**Comment by juanfranblanco** [comment]
Projects updated, this will be available in the next release
