### ISSUE TITLE
Instantiating Nethereum from within Azure function

### ISSUE THREAD

**Issue by ttichy** [Nethereum/Nethereum#180]
I am using VS2017 and I added the Nethereum.Web3 package via NuGet.

When instantiating via `var web3 = new Nethereum.Web3.Web3();` I get the following eror:

` System.MissingMethodException : Method not found: 'Void EdjCase.JsonRpc.Client.RpcClient..ctor(System.Uri, System.Net.Http.Headers.AuthenticationHeaderValue, Newtonsoft.Json.JsonSerializerSettings, System.Text.Encoding, System.String)'.\r\n   at Nethereum.JsonRpc.Client.RpcClient..ctor(Uri baseUrl,AuthenticationHeaderValue authHeaderValue,JsonSerializerSettings jsonSerializerSettings)\r\n   at Nethereum.Web3.Web3.IntialiseDefaultRpcClient(String url)\r\n   at Nethereum.Web3.Web3..ctor(String url)\r\n   at async FunctionApp1.Ethereum1.Run(HttpRequestMessage req,TraceWriter log)`

I tried the Nethereum.Portable package with the same result.

For troubleshooting,  I created a console project, added the Nethereum package and tried to instantiate Web3; no issues there.

Any ideas?

**Comment by juanfranblanco** [comment]
It seems you are referencing a newer version of the EdjCase RpcClient

**Comment by ttichy** [comment]
Looks like Azure functions don't support .Net Core yet.  Once I downgraded to 1.0.6. I was able to execute in Azure.
Btw.. I am looking for a doc that outlines the differences 1.0.6 vs 2.0.1.. Could you point me in the right direction?
Thanks!

**Comment by juanfranblanco** [comment]
You don't need to use .net core, 2.0.1 is still net451. Re docs, there is some work at the moment to update the documentation.   But check the change log for previous RC releases.

I do not recommend using 1.0.6.

**Comment by juanfranblanco** [comment]
I have created an Azure Functions project and you are correct same error and it is targetting 4.6.1 same as a console project.  The console project is successful but not the Azure function

**Comment by ttichy** [comment]
Yeah - I had one of my colleagues do that on their computer as well. Same error as mine .. and now yours.

I did check the references. I can't find a difference between the Azure function project and the Console app. 

Strange :(

**Comment by juanfranblanco** [comment]
I think is something todo with AzureFunctions, it is not resolving namespaces.

![image](https://user-images.githubusercontent.com/562371/31395760-6e72b4a4-add9-11e7-9035-c28288e0e10b.png)

**Comment by juanfranblanco** [comment]
Ok that was solved by adding some casting, but did not solve the problem. It might be due to System.Net.Http, using a newer version of the library breaks it due to this.

**Comment by ttichy** [comment]
I don't think it's that - the compilation error you're showing is because the null parameter for AuthorizationHeaderValue. When you replace that with new AuthorizationHeaderValue("Authorization"), it will compile.

However, the function will throw immediately when you try to execute it.
It's like the azure function bungles loading the DLL somehow

**Comment by juanfranblanco** [comment]
Yes true :). Just trying to figure out what.

**Comment by ttichy** [comment]
ouch. Thanks for looking into this Juan!

**Comment by ttichy** [comment]
I did a little more digging. The error happens inside the IntialiseDefaultRpcClient(string url) method, when a new RpcClient is instantiated by

`Client = new RpcClient(new(Uri(url));`

I believe it has to do with compilation and optional parameters. What doesn't make sense is that it works in the Console app.

Anyways, I was able to make it work by brute forcing it. I used `git subtree` to add Nethereum and EdjCase.JsonRpc repos into my project in order to avoid using the NuGet packages.

**Comment by juanfranblanco** [comment]
I dont think that is the issue, as I removed Nethereum and only try to create an instance the Edjcase. That still had the issue, but swapping versions and http libraries caused the issue.

And yes that is the solution I was thinking about. When forking you will use the same http library for all. 
As Azure has a fixed dependency and breaks everything.

I was even considering having an specific Azure function Client (IClient RPC implementation) with that specific library. Yet again not a nice solution and a workaround. But it might be an option if the problems continue.

**Comment by ttichy** [comment]
I have a new theory about this error inside Azure functions:
https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/

**Comment by juanfranblanco** [comment]
Nice find! Actually, that seems to be the solution to the problem :). Ill test it later.

**Comment by barissaydag** [comment]
Did anyone actually solve this problem? I am receiving the exact same error. I really want to be able to use Nethereum in Azure functions, but I am currently blocked..

**Comment by ttichy** [comment]
@barissaydag - I "Solved" it by not using Nuget packages for dependencies, but simply cloning the repos (Nethereum and JSONRpc) and including them with the project manually

**Comment by juanfranblanco** [comment]
The new version of Nethereum removes the edjcase dependency so there is no more issues with the System.Net.HttpClient. Although now there is with the version of Newtonsoft Json, but it is resolve by either using Netstandard or forcing the latest version. 

Sample (rather simple) here https://github.com/Nethereum/AzureFunction.Sample/tree/master/AzureFunction.SampleNet

**Comment by juanfranblanco** [comment]
Keeping it open for feedback

**Comment by bjaq** [comment]
I had this issue that got resolved for me by installing the latest version of Nethereum (v2.2.0).
