### ISSUE TITLE
Return RpcResponse from RpcClient.cs

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#181]
My solution requires customizing contract from template, add parameters, extract abi, extract bytecode - in other words use the RpcResponse back in solution.  The update (I was using a very old version of nethereum, not sure when this change was made) does not return RpcResponse.  So I added a function to return response.

`https://github.com/ushakrishnan/Nethereum/blob/master/src/Nethereum.JsonRpc.RpcClient/RpcClient.cs `

```
        public async Task<RpcResponse> SendRequestAsyncReturnResponse(RpcRequest request, string route = null)
        {
            var response =
                await _innerRpcClient.SendRequestAsync(
                        new EdjCase.JsonRpc.Core.RpcRequest(request.Id, request.Method, (object[])request.RawParameters), route)
                    .ConfigureAwait(false);
            HandleRpcError(response);
            return response;
        }
```

Not sure if there is a better way, or this is not a useful addition.  Just letting you know, to see if there is a better way to do it.

Thanks

**Comment by juanfranblanco** [comment]
Hi @ushakrishnan  

I hope you are well, I am trying to avoid surfacing any objects from Edjcase to avoid any coupling. So IClient implementation does not need to depend on any Edjcase libraries. 

So in this scenario, I will need to create a new RpcResponse object that maps to Edjcase response, which it is mainly the standard RPC JSON response.

Eventually, the RpcRequest and RpcResponse from Edjcase will disappear altogether removing the need from IPC,  and finally from RPC (if wanted / needed)

**Comment by ushakrishnan** [comment]
Hi @juanfranblanco 

Thanks for explaining.  In my case, I do need the full details in the response to use the components of the response's result.

I can see the cleaner implementation of not exposing the object directly.  I would be thrilled, if we can go the way of implementing the latter way by creating a new object that maps to the response.

Thanks for the awesome toolset and look forward to exploring more :-)

**Comment by juanfranblanco** [comment]
I have replaced now the edjcase library to improve performance on the latest release, I have not yet added this extra method, but we are getting there :)

**Comment by juanfranblanco** [comment]
QueryRaw can solve this for smart contract calls
