### ISSUE TITLE
Internal method causes my app to terminate

### ISSUE THREAD

**Issue by Affinity121** [Nethereum/Nethereum#186]
```
protected override async Task<T> SendInnerRequestAync<T>(RpcRequest request, string route = null)
{
	var response =
		await _innerRpcClient.SendRequestAsync(
			new EdjCase.JsonRpc.Core.RpcRequest(request.Id, request.Method, (object[])request.RawParameters), route)
			.ConfigureAwait(false);
	HandleRpcError(response);
	return response.GetResult<T>();
}
```

When I execute any RPC method, my app terminates immediately on the line `_innerRpcClient.SendRequestAsync`. `catch` and `finally` blocks are not executed and 'Break When Thrown' is not triggered. Any ideas?

**Comment by juanfranblanco** [comment]
What environment are you?

**Comment by Affinity121** [comment]
Windows x64 Console app, target framework is .NET Framework 4.5.2.

**Comment by juanfranblanco** [comment]
Strange, how are you handling the async call in the console?

**Comment by juanfranblanco** [comment]
This may help you https://github.com/Nethereum/Nethereum.Console/blob/master/Nethereum.Console/Commands/SendTransactionFromAccountFileCommand.cs
