### ISSUE TITLE
TransactionHash is 0x000000 when filtering

### ISSUE THREAD

**Issue by Rexota** [Nethereum/Nethereum#187]
I'm filtering old logs to get token transfers like etherscan.io, however `TransactionHash` returns `0x0000000000000000000000000000000000000000000000000000000000000000` for all logs.

Is this intended mechanism of ethereum? How can I get correct tx `hash`, `value` and `from`? I am using this with your `StandardTokenService`.

```
var filter = await transfersEvent.CreateFilterAsync(new BlockParameter(4376084));
var logs = await transfersEvent.GetAllChanges<Transfer>(filter);

foreach (var log in logs)
{
    Log("-------");
    Log("TransactionHash: " + log.Log.TransactionHash);
    Log("From: " + log.Event.AddressFrom);
    Log("Value: " + (log.Event.Value));
}
```

Output:

```
TransactionHash: 0x0000000000000000000000000000000000000000000000000000000000000000
From: 0x6fed36ee956a4f72ffba958d6ae62ed057999008
Value: 1239767300
```

**Comment by juanfranblanco** [comment]
Hi,

What chain are you connecting to?

**Comment by Rexota** [comment]
I am on mainnet blockchain in my localhost, its synced.

**Comment by juanfranblanco** [comment]
Then you should not have any issues, is it fast synced?

**Comment by Rexota** [comment]
Yes, --fast synced, I am getting same result with node.js too.

**Comment by juanfranblanco** [comment]
Try full sync, events are not part of the consensus and when you do a fast sync you get the latest state.

**Comment by Rexota** [comment]
Okay, will set up a VPS and try again without --fast.

**Comment by Rexota** [comment]
Solved with full sync.
