### ISSUE TITLE
Deploy smart contract using private and public key (address)

### ISSUE THREAD

**Issue by AlexETF** [Nethereum/Nethereum#189]
Is there a way to create and deploy smart contract with private key and public key (address) not public key (address) and password in order to unlock it first ?

I want to deploy contract from address that is not stored on the node.

I looked at the offical documentation, did not find a way to do it. 

https://nethereum.readthedocs.io/en/latest/contracts/deploying/#create-and-deploy-a-smart-contract-to-ethereum

I am currently using Nethereum.Portable v2.0.1.

**Comment by option-greek** [comment]
You can do something like this:
            var account = new Account(privatekey);
            var network = "https://ropsten.infura.io/";
            var web3 = new Nethereum.Geth.Web3Geth(account, network);

**Comment by juanfranblanco** [comment]
@AlexETF  try this workbook https://github.com/Nethereum/Nethereum.Workbooks/blob/master/nethereum-gettingstard-smartcontrats.workbook

**Comment by AlexETF** [comment]
Thank you for your quick reponses. I managed to deploy it. :)
