### ISSUE TITLE
Web3 requests to latest geth fail due to null properties

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#19]
Nethereum includes gas:null, gasPrice: null etc in RPC request that causes Geth to respond with error.

Web3.js gets around this by not including null properties.

Proposed solution here #18

**Comment by juanfranblanco** [comment]
As mentioned before this is a bug with Dev, latest geth is 3.5 https://github.com/ethereum/go-ethereum/releases. You can use the chat to discuss if you want, it will be async due to timezone but it can prevent lots of issues created.

**Comment by slothbag** [comment]
Sorry, was just trying to keep track of this issue as I have to remember to merge my change each time with your latest.. Plus I thought it was worth keeping around for others who may run into the same problem until its resolved.

I'll leave it to you :)

**Comment by juanfranblanco** [comment]
Don't worry, I was just thinking it could be better to chat in gitter. Makes it more personal :) and might be able to answer or ask what your setup, targets etc
