### ISSUE TITLE
Getting exception {"Response status code does not indicate success: 405 (Method Not Allowed)."}

### ISSUE THREAD

**Issue by option-greek** [Nethereum/Nethereum#190]
Hi all,
     I'm getting below exception when trying to do CreateFilterAsync():

{"Response status code does not indicate success: 405 (Method Not Allowed)."}

I'm using ropsten over https. Following is code I'm using:

var contractAddress = "0xece9e7dbd97f28ebbeef4d8d852ae0209007849d";
var byteCode = "6060604052341561000f57600080fd5b60405160208061011f833981016040528080519150505b60008190555b505b60e38061003c6000396000f300606060405263ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416631df4f1448114603c575b600080fd5b3415604657600080fd5b604f6004356061565b60405190815260200160405180910390f35b600054810273ffffffffffffffffffffffffffffffffffffffff3316827f841774c8b4d8511a3974d7040b5bc3c603d304c926ad25d168dacd04e25c4bed8360405190815260200160405180910390a35b9190505600a165627a7a7230582019a6f0abcdda9bd680b1c626ed26181531065f6b890f5c078a85c73cbd8523560029";

var account = new Account(privatekey);
var network = "https://ropsten.infura.io/";
var web3 = new Nethereum.Geth.Web3Geth(account, network);
var contract = web3.Eth.GetContract(abi, contractAddress);
var multiplyFunction = contract.GetFunction("multiply");

var multiplyEvent = contract.GetEvent("Multiplied");
var filter7 = await multiplyEvent.CreateFilterAsync(7);

at this point I get the above mentioned exception. 

Any help is appreciated.

Regards,
OG

**Comment by juanfranblanco** [comment]
Filters are not supported in infura. You will need to use GetLogs (top of my head)

**Comment by option-greek** [comment]
Thank you. If possible, could you please point to an example with EthGetLogs. Is there any other testnet that supports filters without running a local node.

**Comment by juanfranblanco** [comment]
No, filters are local. EthGetLogs is the same as new filter but you pass the filter input instead.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/f961e478afed8f8d9667856e66c0789b38105752/src/Nethereum.Web3.Tests/AccountTests.cs#L14-L16
