### ISSUE TITLE
Unable to convert the result to type 'Nethereum.RPC.Eth.DTOs.TransactionReceipt

### ISSUE THREAD

**Issue by theHour** [Nethereum/Nethereum#193]
Hi all,

So I'm not sure if I'm doing something wrong here but I'm getting the this error when trying to deploy the contract 

> Unable to convert the result to type 'Nethereum.RPC.Eth.DTOs.TransactionReceipt

I'm trying to deploy the contract from [https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/examples/SampleCrowdsale.sol](url) and I'm stuck with the above error.

I have tried with both Nethereum.Portable versions 2.01 and 2.1, also I've tried using CQS, but no luck so far. 

I've been following the tutorial from Workbooks and from [https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3.Tests/Contract.CQS/ContractHandlers.cs](url).

Do I have to deploy the token contract first and then crowdsale, or I can just deploy the crowdsale alone?

**Comment by juanfranblanco** [comment]
Can you see the transaction submitted?

**Comment by theHour** [comment]
Hi Juan,

Here is the latest transaction:
https://ropsten.etherscan.io/tx/0x0dd4f4a5f83e118a8d5d128a50f2f44df7b0c1505e5fc981b1d86dd38e1f6d8f

Every transaction failed.

**Comment by juanfranblanco** [comment]
Thanks, I can retrieve the receipt ok. It might another issue. Are you deploying to infura? Or local

**Comment by juanfranblanco** [comment]
Nethereum.Portable includes the Status field that is the only difference.

**Comment by juanfranblanco** [comment]
So if you retrieve the TransactionReceipt now from your local node is fine? It is only an issue when deploying. Correct?

**Comment by theHour** [comment]
Weirdest thing is, I managed to deploy contracts yesterday without problems (they were multisig contracts, only had problems with gas ⚡️ ) but today no luck.

I can't confirm that yet, I don't have access currently to the machine and will update you tomorrow.

**Comment by theHour** [comment]
Hi Juan,

I'm going to close this issue.
I've tried with other contracts and I can deploy them without any problems. There seems to be a problem with Crowdsale contract that I'm using as an example.

If I find the problem I will update this for future references if someone encounters the same problem as me.

**Comment by juanfranblanco** [comment]
Thanks, let me know how it goes, as I am concerned about the response itself.
