### ISSUE TITLE
How can I deploy inherited classes?

### ISSUE THREAD

**Issue by waggy55** [Nethereum/Nethereum#194]
Hi,

I followed your tutorial to deploy the Multiply contract using Nethereum (many thanks!). But I haven't been able to find how to deploy a contract that inherits from another contract.

Assuming Multiply inherits from Mortal, and I compile the contracts using Visual Studio Code, I am given two ABIs and two binaries. How do you recommend they are deployed using Nethereum?

Many thanks,
Dan

```
pragma solidity ^0.4.15;

contract Mortal {

    address creator;

    function Mortal() public {
        creator = msg.sender;
    }

    function kill() public {
        if( msg.sender  == creator ) {
            selfdestruct( creator );
        }
    }
}

contract Multiply {

    int _mulitplier;

    function Multiply( int multiplier ) public {
        _mulitplier = multiplier;
    }
    
    function multiply( int val ) public pure returns( int d ) {
        return val * 7;
    }

}
```

**Comment by juanfranblanco** [comment]
you have not inherited, you have 2 contracts.

You need to do something like contract Multiply is Mortal {}

**Comment by waggy55** [comment]
My goodness, that's embarrassing! I do apologise...now, how do I delete this thread? :)

P.S. Thanks for writing Nethereum, great tool!

**Comment by juanfranblanco** [comment]
Don't worry :), it can happen to everyone. Simple issues disappear of view when dealing with new stuff. Well, at least to me.
