### ISSUE TITLE
Compilation of the full solution in Visual Studio Mac

### ISSUE THREAD

**Issue by ericmuyser** [Nethereum/Nethereum#195]
How does one compile the project (in Visual Studio Mac)? It has dependency on Web3, which has dependency on other projs. If I try to build the soluton, it says I need to restore Nuget packages. Attempting to do that says `Project Nethereum.JsonRpc.IpcClient is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win-x86. Project Nethereum.JsonRpc.IpcClient supports: net462 (.NETFramework,Version=v4.6.2)`

Thoughts?

![image](https://user-images.githubusercontent.com/156768/32141808-ef43fea0-bc46-11e7-9317-af82f760a283.png)

![image](https://user-images.githubusercontent.com/156768/32141805-d5f42420-bc46-11e7-80ff-c72c3d35f8c0.png)

**Comment by juanfranblanco** [comment]
I recommend Windows if you want to do a full build of the project, there are many multi targets.

**Comment by ericmuyser** [comment]
Can I compile it on Windows and it'll run on Mac?

**Comment by juanfranblanco** [comment]
Of course, have you tried the nuggets?

**Comment by Jay-Dee** [comment]
I've had a similar issue on Linux(CentOS-7) and dotnetcore2.0
I even tried to downgrade to dotnetcore1.1 which seems to be supported target framework in some of the projects, but still running into compilation issues such as these.

`/opt/dotnet/sdk/1.1.4/Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/jd/SourceCode/csharp/Nethereum/src/Nethereum.HDWallet/Nethereum.HdWallet.csproj]
    43 Warning(s)
    33 Error(s)
`

@juanfranblanco : is there a minimum set of projects that can be used without having to use Windows?

**Comment by juanfranblanco** [comment]
Well I recommend you using the nugets in those scenarios, mainly Nethereum is made cross platform.

**Comment by Jay-Dee** [comment]
Thanks for the reply.. but I am looking at this from the point of contributing to Nethereum rather than using it. :)

**Comment by juanfranblanco** [comment]
Ah then you will need Windows too, a Mac and Linux (the joys of cross platform testing) :D

**Comment by juanfranblanco** [comment]
But nevertheless to play around with the code, if you install mono, theoretically should be ok.

**Comment by Jay-Dee** [comment]
Ok, I might give MONO a try.. although I was hoping "dotnetcore" to be the way forward for developing .net apps on Linux. Thanks though.

**Comment by juanfranblanco** [comment]
Mainly Nethereum has to be fully cross platform and also support where it cans the oldest possible version, in this scenario net451 / netstandard1.1 but even more the custom net351 for Unity3d. So yes the aim is to target everything, which for library development is a pain :). In a similar way to be able to work in iOS you need to make sure that AOT is supported (same for unity3d)

**Comment by juanfranblanco** [comment]
Maybe this helps https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by Jay-Dee** [comment]
[mono_compilelog_centos7.log](https://github.com/Nethereum/Nethereum/files/1439566/mono_compilelog_centos7.log)

I've attached the logs from mono. Also below is the output of my dotnetcore installation. 
The link that you sent does not list the latest stable dotnetcore LTS version.
[dotnetcore LTS release](https://github.com/dotnet/core/releases)

`.NET Command Line Tools (1.1.4)

Product Information:
 Version:            1.1.4
 Commit SHA-1 hash:  d2f3571419

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /opt/dotnet/sdk/1.1.4`

Anyways, I think it might be worth me spending sometime to get the existing solution compiling on Linux just as a learning exercise for me. Do you mind sending me the order of the project dependencies? Thanks again.

**Comment by juanfranblanco** [comment]
No, the link explains the netstandard compatibility chart.

**Comment by juanfranblanco** [comment]
You can see the projects dependencies in each project.

**Comment by Jay-Dee** [comment]
Ok. Thanks.

**Comment by juanfranblanco** [comment]
Maybe this will help you understand the relationships. https://www.hanselman.com/blog/DraftNETGlossaryDiagram.aspx

**Comment by Jay-Dee** [comment]
Yes. Thanks. Also I've been looking into the code a bit more.. and if I understand this correct, even though Nethereum is cross-platform and can be used on a machine with "netstandard1.1", compiling the Nethereum.sln needs a windows platform as some of the test/helper/sample projects rely on windows features.
I will try and get a windows machine setup. :-)

**Comment by juanfranblanco** [comment]
Good luck, you might want a Mac too ;). I am closing this now as it is not an issue.
