### ISSUE TITLE
This looks great, could we create a standard .net class library out of it?

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#2]
Thanks for implementing this, I will try it out shortly.

Any plans to release as a nuget package?

**Comment by slothbag** [comment]
I just went to compile it and realized its not a standard DotNet library.  Its a DNX asp.net library.

I attempted to migrate it to a standard dotnet library without much luck.  RpcClient is a DNX specific package and a few syntax differences that throw compile errors.

Is it possible to convert this to a standard dotnet library and reference it from your DNX project?

**Comment by juanfranblanco** [comment]
Hi it is an standard .net library it outputs .net 4.5, see the Desktop Sample as it uses the build output from the different components.

Nuget beta should be coming this week.

**Comment by slothbag** [comment]
My apologies, i'm not using Visual Studio.  I use Xamarin and SharpDevelop IDEs.. both cant open xproj files, and when I add the projects manually they wont compile (under .net 4.5) due to various syntax errors like..

`public virtual string CanonicalName => Name;`

and

`return enumType?.GenericTypeArguments[0];`

Not sure why my .net4.5 doesn't like it..

**Comment by slothbag** [comment]
Looks like they are c# 6 specific syntax.  I'll have to look into how I can compile c# 6 code :)

**Comment by slothbag** [comment]
Unfortunately the combination of c# 6 code, xproj file formats and DNX based packages means working with this library is very difficult outside of VS :(

The only way I can get any compilation happening is to download the latest Roslyn C# compiler from Nuget and on the command line manually type csc *.cs etc.. for each project.  None of my IDEs can edit or compile.

And the new Dotnet CLI tool has issues getting packages associated with the older DNX packages.

A pre-compiled dll from Nuget would save me the trouble, but I would not be able to build/debug/compile myself to contribute.

Let me know how I can help.

**Comment by juanfranblanco** [comment]
Ill release a nuget package soon (as in tomorrow, saturday). You can use dnx to create your package, compile, vscode. As I have use it in linux

**Comment by juanfranblanco** [comment]
Xamarin has been bought by MS, so I guess the tooling will be unified soon.

**Comment by slothbag** [comment]
I saw that DNX was discontinued so I didn't want to go to the trouble to install it.  Will you be migrating to the new Dotnet CLI soon?

To be honest, after 15 years of the .Net framework i'm pretty shocked to have just found out they are moving down this path of individually packaged apps.

I guess sharpdevelop, xamarin and Mono will need to overhaul their products to reflect this new .Net world.  And that is going to take some serious time/effort.

Thanks, look forward to trying out the dll soon :)

**Comment by juanfranblanco** [comment]
First beta nugets, and then will try to create a netstandard library.. net cli

**Comment by slothbag** [comment]
I was a bit excited so ended up compiling it by hand with csc.. managed to get it talking to geth at least.

Now its throwing RPC error about property "id" not existing.  Think I will go have a break now.

**Comment by juanfranblanco** [comment]
I have used .net cli to compile it.. it will be easier.
1. Install .NET CLI
2. dotnet restore at solution level
3. Go to Web3 or Web3 sample and do a dotnet build

**Comment by juanfranblanco** [comment]
What method are you calling on RPC? This might be a bug..

**Comment by slothbag** [comment]
Re: .Net CLI - dotnet restore gives errors about no compatible assembly for win7-x64

Re: RPC error - I did a GetFunction("myfunctions") and then a myFunction.CallAsync() then after a few seconds it throws the exception.

**Comment by juanfranblanco** [comment]
Re: .Net CLI - dotnet restore gives errors about no compatible assembly for win7-x64

Ignore it the dlls should be fine... I need to update the project.json dependencies to netstandard but also validate with external nuggets, hence I am waiting for the newer release (expected build)

 Re: RPC error - I did a GetFunction("myfunctions") and then a myFunction.CallAsync() then after a few seconds it throws the exception.

Ill check that, thanks!!!

**Comment by juanfranblanco** [comment]
On your error it seems that you were using a function with no parameters so I have extended this example to include that:

solidity 

` //The compiled solidity contract to be deployed
`            /*
`              contract test { 
`             uint _multiplier;
`            function test(uint multiplier){
`               _multiplier = multiplier;
`              }
`               function getMultiplier() constant returns(uint d){
`                   return _multiplier;
`              }
`              function multiply(uint a) returns(uint d) { return a * _multiplier; }
`          }
`          */

.net

`var multiplierFunction = contract.GetFunction("getMultiplier");
`
`  var multiplier = await multiplierFunction.CallAsync<int>();
`

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3.Sample/ContractConstructorDeploymentAndCall.cs

- Are you using enough gas, when you deploy your contract?

`var transactionHash = await web3.Eth.DeployContract.SendRequestAsync(abi, contractByteCode, addressFrom, new HexBigInteger(900000), 7);`

- GetFunction("myfunctions") --> I assume is GetFunction("myfunction") :)

Finally can you validate using one of the web3.samples ?

**Comment by slothbag** [comment]
The function I am calling is an auto generated getter function

e.g. solidity
`string public name = "Some arbitrary name";`

So yes, it takes no parameters.  The contract is already deployed and working well in web3.js

**Comment by juanfranblanco** [comment]
Ok the issue was wtih a generic constraint, when simplifying for web3 (I oversimplified too much ;) and it would not allow for strings, the compiler should not have accepted that. Thanks.

Updated the example.

**Comment by slothbag** [comment]
I'm gonna close this issue and create a few more specific issues if thats ok :)
