### ISSUE TITLE
A few questions about Netheruem

### ISSUE THREAD

**Issue by aprz43** [Nethereum/Nethereum#20]
Hi Juan,

Firstly, I'd like to say that it's great to see .Net support starting to come out for Etheruem, thanks for your contribution to the ecosystem.

I have a couple of questions that I hope you can help me with.

I'm looking at adding ETH support to an existing Bitcoin exchange and there are two functions that I need to perform for this to happen:

1) Generate an ETH address and corresponding private key
2) Sign a raw transaction with a private key

Is Nethereum able to perform these two functions without connecting to any other 3rd party services?

If not, are you able to recommend any other .Net library which can do this?

Thanks,

Adrian

**Comment by juanfranblanco** [comment]
Nethereum is an rpc client for geth, so you can create an account using personal

**Comment by aprz43** [comment]
Thanks, I’ll look at that
