### ISSUE TITLE
Dynamic Event Log

### ISSUE THREAD

**Issue by krispenner** [Nethereum/Nethereum#201]
Would it be possible to retrieve an event's logs with an untyped event class? Currently a typed class is required with the ParameterAttribute applied. The properties are then populated based on their Order that is set and whether they are indexed (topics) or not. The name set on the attribute does not appear to be utilized anywhere. 

What if I don't know the exact typing of an event? Or if I want a generic way to retrieve event data for any event? This could be done with a list of parameters { name, type, value } in the order they are defined within the event. This type info could be pulled/parsed from the ABI of the contract, such as the Multiplied sample event which lists in the ABI it's parameters with their names, type, order and if indexed.

I am new to programming with Ethereum and Nethereum so maybe there is a way to solve this already. Or maybe what I am trying to achieve doesn't make sense. Please let me know.

I tried passing in dynamic and object to the Event.GetFilterChangesAsync<dynamic/object>(filterId) but this throws an IndexOutOfRangeException error. I can see in the code that the indexed parameters must be all set on the typed generic type parameter.

Thanks for your help,
This is an incredible library, really well done!!

Cheers,
Kris

**Comment by juanfranblanco** [comment]
Dynamic is not supported as there is no knowledge of the type. Everything is a set of bytes there is no knowledge of the type already or the way it is stored

**Comment by krispenner** [comment]
Is there no way to get the ABI of a deployed contract? The ABI contains the event signatures. I assumed the ABI would be available as it's required during a contract's deployment. Why is the ABI required when deploying a contract if it isn't somehow stored beside/within the contract?
Thanks!

**Comment by juanfranblanco** [comment]
http://solidity.readthedocs.io/en/develop/metadata.html this might help you

**Comment by diegodayone** [comment]
Facing the same problem... As far as I understood I must create a class that match the response type.
Actually If i perform the same operation from web3JS I get an object like:


address: "0xdde2d979e8d39bb8416eafcfc1758f3cab2c9c72"
​args: Object { _from: "0x0000000000000000000000000000000000000000", _to: "0x3f8c962eb167ad2f80c72b5f933511ccdf0719d4", _tokenId: {…} }
​blockHash: "0xeb8ee01455f01d187528c1fb7f3a9000b44b5d4bf65512f2397b694f694b995f"
​blockNumber: 5383361
​event: "Transfer"
​logIndex: 21
​removed: false
​transactionHash: "0x8e45101ced2ef96ddd796399c5e7862d5af16cbf52abec61022020a0cd553da3"
transactionIndex: 45

That I translated in 2 C# classes

 public class Args
        {
            public string _from { get; set; }
            public string _to { get; set; }
            public string _tokenId { get; set; }
        }

        public class T1
        {
            public string address { get; set; }
            public int blockNumber { get; set; }
            public string transactionHash { get; set; }
            public int transactionIndex { get; set; }
            public string blockHash { get; set; }
            public int logIndex { get; set; }
            public bool removed { get; set; }
            public string @event { get; set; }
            public Args args { get; set; }
        }

var web3 = new Web3("https://mainnet.infura.io");
            var contract = web3.Eth.GetContract(Service.ABI, Service.Address);

            var transferEvent = contract.GetEvent("Transfer");
            var filter = transferEvent.CreateFilterInput(new BlockParameter((ulong)5383361), new BlockParameter((ulong)(100)));
            var x = await transferEvent.GetAllChanges<T1>(filter);
            
but it's still not working.. Any hint?

Thanks

**Comment by krispenner** [comment]
This was a while ago, I never did get it to work as I was originally hoping and I don’t believe it is possible based on the above comments and my own research.
