### ISSUE TITLE
Getting list of all transactions for Ethereum wallet

### ISSUE THREAD

**Issue by AlekseiManuilovDevPro** [Nethereum/Nethereum#202]
Hi Juan!
First of all, I would like to say 'Thank' for your work! Nethereum is awesome library which helps save time during Ethereum integration!

We have our Ethereum wallet and we need to get list of all transactions for this wallet. Is it possible to do that with Nethereum library? Or maybe there is some other approach? 

Thanks

**Comment by juanfranblanco** [comment]
Check the Nethereum blockchain storage repo. Mainly this can index all transactions.

**Comment by AlekseiManuilovDevPro** [comment]
Thanks for quick response! I will check Nethereum blockchain
