### ISSUE TITLE
Event detection seems unreliable

### ISSUE THREAD

**Issue by waggy55** [Nethereum/Nethereum#203]
Good afternoon.

Given the following contract:

```
contract Registration {

    mapping(address => string) nameByAddress;
    mapping(string => address) addressByName;

    event Registered(
        string name,
        address ethereumAccountId,
	uint timestamp
    ); 

    event RegistrationFailed(
        string name,
        address ethereumAccountId,
	uint timestamp
    );

    function register(string name) public payable {

        if (0 == bytes(nameByAddress[msg.sender]).length &&
            0 == addressByName[name]) {

            nameByAddress[msg.sender] = name;
            addressByName[name] = msg.sender;

            Registered(name, msg.sender, now);

        } else {

            RegistrationFailed(name, msg.sender, now);

        }

    }
}
```
And, given the following C# DTO code:
```
public class RegisteredEvt
{
    [Parameter("string", "name")]
    public string Name { get; set; }

    [Parameter("address", "ethereumAccountId")]
    public string EthereumAccountId { get; set; }

    [Parameter("int", "timestamp")]
    public int Timestamp { get; set; }
}
...
public class RegistrationFailedEvt
{
    [Parameter("string", "name")]
    public string Name { get; set; }

    [Parameter("address", "ethereumAccountId")]
    public string EthereumAccountId { get; set; }

    [Parameter("uint", "timestamp")]
    public uint Timestamp { get; set; }
}
```
And, given the following C# code:
```
var contract = web3.Eth.GetContract(abi, Address);

var evtRegisteredOk = contract.GetEvent("Registered");
var filterRegisteredOk = evtRegisteredOk.CreateFilterAsync().Result;

var evtRegisterFailed = contract.GetEvent("RegistrationFailed");
var filterRegisterFailed = evtRegisterFailed.CreateFilterAsync().Result;

<THE FOLLOWING IS POLLED IN A SEPARATE THREAD>
var logRegistered = evtRegisteredOk.GetFilterChanges<RegisteredEvt>(filterRegisteredOk).Result;
var logRegistrationFailed = evtRegisterFailed.GetFilterChanges<RegistrationFailedEvt>(filterRegisterFailed).Result;
```

A test runs which attempts to register three times with the same address. The expected result is that one `evtRegisteredOk` event is received and two `evtRegisterFailed` events are received.

The problem is that:
although `evtRegisteredOk` is always received (at least once), `evtRegisterFailed` is received about 50% of the time, and `evtRegisterFailed` is never received twice.

I've retrieved the events using the NodeJs Web3 object, and they are there as expected.

Many thanks for your help.

Dan

**Comment by juanfranblanco** [comment]
You are using GetFilterChanges, have you made sure the filters are set before hand?  When you check with node, am I correct that you are not expecting to see the same results afterwards in .Net?

**Comment by juanfranblanco** [comment]
Also, have you validated that the events are included on the receipt anyway?

**Comment by waggy55** [comment]
Thank you for your quick reply!

I have just added a delay amade sure that the filters are created before the contract transaction `register(...)` is called and before `GetFilterChanges` is called.

I have just checked the receipts for the contract transaction `register(...)`. The receipts do indeed contain the expected log data.

I checked the results in node after they didn't appear in .Net.

Thanks.

**Comment by waggy55** [comment]
In trying to figure out why it wasn't working, I was using `GetAllChanges` rather than `GetFilterChanges`. Now I'm using `GetFilterChanges` again, it seems to work and it's working consistently.

Can I just make sure, please:
The filter must be created before the transaction is sent, or only before `GetFilterChanges` is called?

**Comment by juanfranblanco** [comment]
"Can I just make sure, please:
The filter must be created before the transaction is sent, or only before GetFilterChanges is called?"

Before the transaction is sent, get changes is related to the block.

"Also, I haven't been able to find an answer to the following, please.
Is it possible to create two filters for the same event?"

Yes, you can have different filters for the same event, they can include different topics too. Just think that there might be many different "clients" creating different filters related to an event.

**Comment by juanfranblanco** [comment]
I would use GetLogs and iterate through various set of blocks, when starting from 0.

**Comment by waggy55** [comment]
> Before the transaction is sent, get changes is related to the block.
Thanks so much for the clarification.

>  would use GetLogs and iterate through various set of blocks, when starting from 0.
And thank you very much for the recommendation!
