### ISSUE TITLE
function.CallAsync returns false.........

### ISSUE THREAD

**Issue by jayantbramhankar** [Nethereum/Nethereum#204]
balance of tokens methods works but transfer of tokens is not working.....

`public async Task Test(int token)
        {

            var web3 = new Web3("http://localhost:8545");
            string addressFrom = "0x77caf50d780e704c092b9ca47d6b1a84cb795a92"; //admined
            string password = "password";
            string addressTo = "0xEe0aa527ffCd1B69D9e6a6412B3328A180Ae2eeb";

            var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(addressFrom, password, 120);

            web3.TransactionManager.DefaultGas = BigInteger.Parse("290000");
            web3.TransactionManager.DefaultGasPrice = BigInteger.Parse("290000");

            string abi = @"[{""constant"":true,""inputs"":[],""name"":""name"",""outputs"":[{""name"":"""",""type"":""string""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""totalSupply"",""outputs"":[{""name"":"""",""type"":""uint256""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""constant"":false,""inputs"":[{""name"":""newAdmin"",""type"":""address""}],""name"":""transferAdminship"",""outputs"":[],""payable"":false,""stateMutability"":""nonpayable"",""type"":""function""},{""constant"":true,""inputs"":[{""name"":"""",""type"":""address""}],""name"":""balanceOf"",""outputs"":[{""name"":"""",""type"":""uint256""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""decimal"",""outputs"":[{""name"":"""",""type"":""uint8""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""constant"":false,""inputs"":[{""name"":""target"",""type"":""address""},{""name"":""mintedAmount"",""type"":""uint256""}],""name"":""mintToken"",""outputs"":[],""payable"":false,""stateMutability"":""nonpayable"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""symbol"",""outputs"":[{""name"":"""",""type"":""string""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""constant"":false,""inputs"":[{""name"":""_to"",""type"":""address""},{""name"":""_value"",""type"":""uint256""}],""name"":""transfer"",""outputs"":[],""payable"":false,""stateMutability"":""nonpayable"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""intialSupply"",""outputs"":[{""name"":"""",""type"":""uint256""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""admin"",""outputs"":[{""name"":"""",""type"":""address""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""payable"":false,""stateMutability"":""nonpayable"",""type"":""constructor""},{""anonymous"":false,""inputs"":[{""indexed"":true,""name"":""from"",""type"":""address""},{""indexed"":true,""name"":""to"",""type"":""address""},{""indexed"":false,""name"":""value"",""type"":""uint256""}],""name"":""Transfer"",""type"":""event""}]";
            Contract contract = web3.Eth.GetContract(abi, "0x068BD35f0f2Aaf9b6e51c903500F8eD72e55Afaa");

            var code = web3.Eth.GetCode.SendRequestAsync("0x068BD35f0f2Aaf9b6e51c903500F8eD72e55Afaa"); 

            Function functionTransfer = contract.GetFunction("transfer");
             
            var sss = functionTransfer.CallAsync<bool>(addressTo, token);
            
        }`

**Comment by juanfranblanco** [comment]
Hi,

I don't know if it may help you to checkout this workbook:
https://github.com/Nethereum/Nethereum.Workbooks/blob/master/nethereum-gettingstard-smartcontrats.workbook

**Comment by jayantbramhankar** [comment]
Thanks, solved....
