### ISSUE TITLE
How To : Multiple addressTo transactions

### ISSUE THREAD

**Issue by Ashish81** [Nethereum/Nethereum#205]
Wondering how i can specify multiple recipient address and corresponding amount in a single transaction.
And the vice-versa multiple from address to fund the one single output address.

web3.TransactionManager.SendTransactionAsync(senderAddress, addressTo,amt)

seems to handle one-one address.

**Comment by juanfranblanco** [comment]
You will need a smart contract for that. 
Smart contract has the funds and splits, sends to different addresses. Many to one could be possible yet again with a "controller" smart contracts calling other smart contracts holding funds which will transfer to a single address, a bit more complex but possible.

In a normal scenario, no is not possible.

**Comment by Ashish81** [comment]
Thnaks
