### ISSUE TITLE
Error while connecting to the Azure ethereum consortium

### ISSUE THREAD

**Issue by sinsonfrancis** [Nethereum/Nethereum#206]
We are trying to connect with ethereum consortium blockchain from the Nethereum with the help of your tutorial, "Nethereum.Tutorials", but it throws error.
I have tried to connect with the below code
var web3 = new Geth.Web3Geth(account, "http://--------.southeastasia.cloudapp.azure.com:8545");

Error Message: 
Could not load file or assembly 'EdjCase.JsonRpc.Client, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by juanfranblanco** [comment]
From gitter:

(1.) The nodes in Azure are already mining, so you don't need to control the mining procedure
(2.) The account you are using is a ManagedAccount, I don't know if the node you are connecting has "personal" permissions, so it is best to use your private key instead to sing the transactions beforehand.
(3.) If you want to create a new account you can simply do the following
   var ecKey = Nethereum.Signer.EthECKey.GenerateKey();
   var address = ecKey.GetPublicAddress();
   var privateKey = ecKey.GetPrivateKey();
(4.) Now using the address you should be able to fund it going to your url
(excluding the 8545 port, just use 80) in the browser
[![image.png](https://files.gitter.im/Nethereum/Nethereum/LKho/thumb/image.png)](https://files.gitter.im/Nethereum/Nethereum/LKho/image.png)
You mainly need Ether to execute transactions

(5.) Now that you have an account funded with some Ether, you can use it with its private key to sign transactions:
```csharp
 var accountPrivateKey = "This is your new private key";
            var accountAddress = "This is your address already funded";

            var account = new Account(accountPrivateKey);
            var rpcAddress = "http://juann45fg.northeurope.cloudapp.azure.com:8545";
            var web3 = new Web3(account, rpcAddress);
            var balance = await web3.Eth.GetBalance.SendRequestAsync(accountAddress);
```

**Comment by sinsonfrancis** [comment]
thank you so much, that really worked for me. I could able to get the ether that I added with the ehtereum wallet as well.
