### ISSUE TITLE
Unity Import Trouble

### ISSUE THREAD

**Issue by lopezmramon** [Nethereum/Nethereum#207]
Using Unity with  .Net 4.6 Mono. We've tried building the solution by itself, but it doesn't work, building Web3, but it doesn't work either. We tried copy pasting DLLs built from a Mac, we get a lot of errors within Unity. Is it possible to build Nethereum 2.1.0 and use it in Unity with .Net 4.6? If not, what would you recommend is used as a workaround?

**Comment by juanfranblanco** [comment]
Nethereum for Unity uses net351, but you can use it together with .net 4.6. Actually if you are just targetting Windows PC, UWP, Hololens you can use Nethereum out of the box

**Comment by juanfranblanco** [comment]
I use a vanilla visual studio, latest on Windows. I have recently installed it on a brand new laptop.

**Comment by lopezmramon** [comment]
Interesting. Which kind of project do I create? Do I install into Nuget to a blank project?

I really appreciate your help Juan!

**Comment by juanfranblanco** [comment]
Oh if you are just interested in Unity3d, just use the dlls from the releases https://github.com/Nethereum/Nethereum/releases/tag/2.0.0.

There are no nugets for Unity3d
