### ISSUE TITLE
calling UnitConversion.Convert.ToWei with decimalPlacesFromUnit = 0 terminates the current executing thread

### ISSUE THREAD

**Issue by chenshak** [Nethereum/Nethereum#208]
For example the following line:
`UnitConversion.Convert.ToWei(0.2999541089999999m, 0);`
will enter an infinite loop (seems that since it doesn't expect 0 it enters an infinite loop in BigDecima.Truncate()) . I understand that calling the method with 0 doesn't make sense (It happened to me because of some bad data).

UPDATE:
apparently many other inputs cause the same behavior, for example:
`UnitConversion.Convert.ToWei(0.00435176m, 2);`
`UnitConversion.Convert.ToWei(0.00000000000331095m, 8);`

**Comment by juanfranblanco** [comment]
Thanks!

**Comment by juanfranblanco** [comment]
Yes, it was using the wrong overload.

**Comment by chenshak** [comment]
Thanks @juanfranblanco!

I think you should also update the BigDecimal.Truncate() because it's public and it allows input that results in an infinite loop.

Semantically, I'd say you should be updated to allow precision of 0 since doing the following
`var value = new BigDecimal(3.00435176m).Truncate(0);`
I'd expect value to be 3.

But should throw an exception if precision is less then 0.

Just to correct my original post the issue just caused an infinite loop (without termination of the executing thread as I've stated) so I'll edited my original post to reflect the issue accurately.

**Comment by juanfranblanco** [comment]
Good point :). Apologies for the delay of the response, as I saw your comment and thought about ways to keep it public. I think it is rather confusing anyway to know about the exponent and mantissa, so I will make it internal as per your thought.
