### ISSUE TITLE
Trouble calling contract function with no inputs and multiple array outputs

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#21]
I'm using the DTO example on the README, but it forces me to pass the same class as both Input and output.

That is causing the encoding to fail because its trying to encode both null output parameters.

`function getAllDataFeeds() constant returns(bytes4[500] feedCode, address[500] addresses) {`

```
		[Nethereum.ABI.FunctionEncoding.Attributes.Function(Name = "getAllDataFeeds")]//, Sha3Signature="78cded60")]
		[Nethereum.ABI.FunctionEncoding.Attributes.FunctionOutput]
		public class getAllDataFeedsFunction
		{
			[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("bytes4[500]", "feedCode", 1)]
			public List<byte[]> feedCode { get; set; }

			[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("address[500]", "addresses", 2)]
			public List<Nethereum.ABI.AddressType> addresses { get; set; }

		}
```

**Comment by slothbag** [comment]
I did a test and manually set the encodedParameters to "" in EncodeRequest() and then the call works.

How do I use the <T> Function class above to work with no input params?

**Comment by juanfranblanco** [comment]
On the example, I used the same class for input / output, but both can be different, and non existing if no input is required.

**Comment by juanfranblanco** [comment]
I have seen the problem, when decoupling abi and attribute encoding I went 3 steps further. ;)

**Comment by juanfranblanco** [comment]
So here you have 2 options... One pass a class with a Function attribute with the Encoded sha3.
Second use the usual getFunction and wait for me to put the fix. Mainly everything will call DecodeOutput<T>.

**Comment by slothbag** [comment]
Thanks for looking into it.  Option 1 sounds like what I am already doing.. passing in a class with Function attribute and sha3. 

I seem to be stuck because this is my CallAsync
`tmpFunction.CallAsync<getAllDataFeedsFunction>(new getAllDataFeedsFunction())`
It forces the return type and the inputParam type to be the same otherwise throws a compile error

**Comment by juanfranblanco** [comment]
just checked in a general fix

**Comment by juanfranblanco** [comment]
Added parameterless for typed Functions now

**Comment by slothbag** [comment]
I just tried it.. `tmpFunction.CallAsync<getAllDataFeedsFunction>()`

It ends up using the FunctionCallDecoder.DecodeSimpleTypeOutput which tries to decode the results aka my custom DTO class into a List<> which results in the error
`Unable to cast object of type 'getAllDataFeedsFunction' to type 'System.Collections.IList'.`

It needs to use the other DecodeFunctionOutput

**Comment by juanfranblanco** [comment]
you need to use CallMultipleOutputAsync<FunctionOutput>

**Comment by slothbag** [comment]
Brilliant, works great. Thanks.

**Comment by juanfranblanco** [comment]
Renamed to CallDeserializingToObjectAsync... still hate the name, but is more meaningful. American spelling too.

**Comment by juanfranblanco** [comment]
If it wasnt for structs and new T() this could have been avoided, also including the return type will confuse the compiler on overloads ;(.
