### ISSUE TITLE
Web3.OfflineTransactionSigner.SignTransaction - How do add Parameters to function ?

### ISSUE THREAD

**Issue by hscanlan** [Nethereum/Nethereum#210]
I think I have this all correct for a raw request, EXCEPT, Im not sure if I'm adding parameters right, because they don't show up in the Tx. Although the transaction goes through, it fails because the Params aren't being detected. I assume I'm not sending them correctly .. I can't find any documentation on how to do so using the SignTransaction feature ..

      // get function
                var moveFromFunction = someContract.GetFunction("move");
                object[] moveParms = { receiveAddress, someHexValue };
                moveFromFunction.CreateTransactionInput(senderAddress, moveParms);

                var encoded = Web3.OfflineTransactionSigner.SignTransaction(privateKey, coreContract, amount, txCount.Value, gasPrice, gasLimit, **transferFromFunction.GetData() ???** );

**Comment by juanfranblanco** [comment]
If you just want to send the transaction just use Web3(new Account(privateKey), it will behave the same.

**Comment by hscanlan** [comment]
Is there an overload to set the URL doing that as well?

var web3 = new Web3(new Account(privateKey), "https://mainnet.infura.io");  ?

**Comment by juanfranblanco** [comment]
Yes it is :)

**Comment by hscanlan** [comment]
Thanks for being so quick on the answers ... Sorry for all the questions - new here. Your work is amazing!

So if i'm replacing this

var encoded = Web3.OfflineTransactionSigner.SignTransaction(privateKey, contractaddress, amount, txCount.Value, gasPrice, gasLimit, moveFromFunction.GetData());

with this

// send the transaction
var transactionHash = await moveFromFunction.SendTransactionAsync(senderAddress, gasLimit, gasPrice, txCount.Value, parms);

I get an error ..

Exception: Invalid value for type 'Nethereum.ABI.Encoders.IntTypeEncoder': System.Object[] (System.Object[])

**Comment by hscanlan** [comment]
Oh crap, I had an extra item at the end that I didn't need ... 

`// send the transaction
var transactionHash = await moveFromFunction.SendTransactionAsync(senderAddress, gasLimit, gasPrice, txCount.Value);`

**Comment by hscanlan** [comment]
I'm getting close, but it seems my param's are making it through still ..

**Comment by juanfranblanco** [comment]
You could try to code generate a service if that helps. http://nethereum.readthedocs.io/en/latest/nethereum-code-generation/
Or another option is to use it in a Message like in CQS
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3.Tests/Contract.CQS/ContractHandlers.cs#L37-L46

**Comment by hscanlan** [comment]
I got it to work!! Thanks for your help.

I set the gas price and limit in the web3, and then just used your more simple function..


var transactionHash = await moveFromFunction.SendTransactionAsync(senderAddress, moveParms);
