### ISSUE TITLE
Events are only logged when a Function is called via SendTransactionAsync ?

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#212]
I've the following contract:
```
pragma solidity ^0.4.18;


contract MultiplyContract {
    address owner;
    int multiplier;

    event MultiplyEvent (
        address indexed from,
        int indexed value
    );

    event AddEvent(
        address indexed from,
        int indexed value1,
        int indexed value2
    );

    function MultiplyContract(int _multiplier) public {
        owner = msg.sender;
        multiplier = _multiplier;
    }

    function multiply(int val) public returns (int result) {
        MultiplyEvent(msg.sender, val);

        return val * multiplier;
    }

    function add(int val1, int val2) public returns (int result) {
        AddEvent(msg.sender, val1, val2);

        return val1 + val2;
    }
}
```

When executing this code:

```c#
var function = _contract.GetFunction("add");
var result = await function.CallAsync<BigInteger>(10, 20);
```

I do not get any logs?

But when executing this code:
```c#
var function = _contract.GetFunction("add");
var transaction = await function.SendTransactionAsync("...address...", 5, 7, new HexBigInteger(90000));
```

I can get the logs with:
```c#
var addEvent = service.GetAddEvent();
var addFilterAll = await addEvent.CreateFilterAsync();
var addLog = await addEvent.GetFilterChanges<AddEvent>(addFilterAll);
foreach (var log in addLog)
{
    Console.WriteLine(JsonConvert.SerializeObject(log));
}
```

And the logging looks like:
```json
{
  "Event": {
    "From": "0x12890d2cce102216644c59dae5baed380d84830c",
    "Value1": 5,
    "Value2": 7
  },
  "Log": {
    "removed": false,
    "type": null,
    "logIndex": "0x0",
    "transactionHash": "0x88ec3f5ad775fc909c407b2441041511d74abf5be7c1fb95fd231f2696a5868e",
    "transactionIndex": "0x0",
    "blockHash": "0xbc6f5376db86f2a2e5e8d1a0863c6bbc52fe58fe5c0c81ae631ab27253e58ac5",
    "blockNumber": "0x502",
    "address": "0x5bd02aabdf6488cf1f116887097acc2a32024dec",
    "data": "0x",
    "topics": [
      "0xc23966d0a2948f73a1c4a577849824fa93acb0b93e06c6b43b5c0187ac04c300",
      "0x00000000000000000000000012890d2cce102216644c59dae5baed380d84830c",
      "0x0000000000000000000000000000000000000000000000000000000000000005",
      "0x0000000000000000000000000000000000000000000000000000000000000007"
    ]
  }
}
```

What is the difference?

**Comment by juanfranblanco** [comment]
The difference is that one does a call, the other is a transaction. First does not change the state or persist anything, it is mainly to query the state or "execute" some code. The other is committed on the chain and will also the creation of log entries, as you will find in the transaction receipt (for example). Logs / events as they are not part of the transactions / consensus may not be retained.

**Comment by StefH** [comment]
Thanks for this explanation.

Please review statements below and comment.

1. In case a function does not store any data or does anything on the blockchain, you can just `call` the function.
2. In case a function needs to store/change the state, you need to create a transaction.
3. In my example ; how can I get the result from that **add** transaction? Or this is not possible / intended to work like that ? Do transaction state functions never return a value?

**Comment by juanfranblanco** [comment]
They don't return values, they are transactions. Similar to a Command Query pattern. The command executes the transaction, you know if it has been submitted, from there you can query the state. Note you don't know when the transaction will be included in the blockchain, or if it will error. You can use events which log information to return values (if wanted).

**Comment by juanfranblanco** [comment]
1. In case a function does not store any data or does anything on the blockchain, you can just call the function.

Yes, these are constant functions, they mainly query the state, or do an operation.


In case a function needs to store/change the state, you need to create a transaction.

Yes, this is the point of the blockchain, you want to create a transaction that is included in the chain, and modify the state.

In my example ; how can I get the result from that add transaction? Or this is not possible / intended to work like that ? Do transaction state functions never return a value?

Answer above.

**Comment by StefH** [comment]
Thanks for info!
