### ISSUE TITLE
System.StackOverflowException in version 2.2.0 when creating ManagedAccount in netcoreapp2.0

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#216]
Project file looks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nethereum.Geth" Version="2.2.0" />
    <PackageReference Include="Nethereum.Web3" Version="2.2.0" />
  </ItemGroup>

</Project>
```

Source code for `Program.cs` is:

```csharp
static void Main(string[] args)
{
    var account = new ManagedAccount("0x12890d2cce102216644c59daE5baed380d84830c", "password"); // <---- System.StackOverflowException

    var web3 = new Web3Geth(account);
}
```

Calling the **ManagedAccount** constructor throws a System.StackOverflowException when used in a dotnet core 2.0 app.

Note that this only happens with version **2.2.0**, the previous version is fine.

**Comment by juanfranblanco** [comment]
Thanks, Ill have a look now.

**Comment by juanfranblanco** [comment]
It should be in nuget soon 2.2.2

**Comment by StefH** [comment]
I've have some errors restoring nuget packages for this example project.

> error NU1605: Detected package downgrade: Nethereum.Hex from 2.2.2 to 2.2.0. Reference the package directly from the project to select a different version. 
> error NU1605:  ConsoleAppTestForNethereum -> Nethereum.Web3 2.2.2 -> Nethereum.Contracts 2.2.2 -> Nethereum.Hex (>= 2.2.2) 
> error NU1605:  ConsoleAppTestForNethereum -> Nethereum.Web3 2.2.2 -> Nethereum.Hex (>= 2.2.0)

I see that the new NuGets reference an older version from **Nethereum.Hex (>= 2.2.0)**  ?

**Comment by juanfranblanco** [comment]
The package building and deployment failed, this never happens as it is automated. 2.2.3 is out.
Thanks again!

**Comment by StefH** [comment]
Solved.

**Comment by StefH** [comment]
BTW : **Nethereum.Portable** is not updated to 2.2.3?

**Comment by juanfranblanco** [comment]
Yes, that did not need an (emergency release) update. Hex is included in there. I will push one later for consistency.
