### ISSUE TITLE
Question : easiest way to convert string to bytes32 and back?

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#219]
Can you please tell me which (extension) code I can use to convert a UTF8 string into a valid bytes32 and back ?

**Comment by juanfranblanco** [comment]
It does it for you, there is in an automapping.

**Comment by juanfranblanco** [comment]
If you have an abi with bytes32, you just deserialise to string when using a Call, or if you have multiple parameters, and event or function input, just mark it in c# as a string.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/4f8d9094604c4b70b694764676602dfb5d480991/src/Nethereum.Web3.Tests/Issues/EventAddressIntString.cs
This could be a sample

**Comment by StefH** [comment]
In your solidity contract example, I don't see any parameter defined as a `bytes32` ?

What I mean is that I've a function like:
```js
function addProduct(bytes32 ean, string name, string description, uint quantity, uint price, string location, uint producedTimestamp) public {
```

**Comment by juanfranblanco** [comment]
Mainly if a bytes32 is used as a string, it will be converted automatically.

Ahh... I got you. When code generating a bytes32, I don´t know what type you want so I just take the simple route and let you decide.

So for your scenario just do:
```csharp
Task<string> AddProductAsync(string addressFrom, string ean, string name, string description, BigInteger quantity, BigInteger price, string location, BigInteger producedTimestamp, HexBigInteger gas = null, HexBigInteger valueAmount = null);
```

**Comment by StefH** [comment]
Yes.

I've now update the helper function **function getTypeMap(typeName)** in the file `cs-service.ejs` and added:

```js
if (typeName === 'bytes32') {
    return 'string';
}
```

**Comment by juanfranblanco** [comment]
Cool, I guess, it could be made a generic user setting. (somehow)
