### ISSUE TITLE
Looking for a new wallet creation sample

### ISSUE THREAD

**Issue by lostmsu** [Nethereum/Nethereum#220]
Seems like I should be able to create one using Nethereum.HdWallet.Wallet, by passing a seed (how many bytes)? But then, how do I export it so Mist could use it?

**Comment by juanfranblanco** [comment]
Apologies for the late response, I have missed this issue. You cannot use an HD wallet with Mist (as such) you can use private keys encrypted using the Web3 storage definition. (KeyStore)
