### ISSUE TITLE
Feature request : add functionality to (de)serialize a Guid to bytes16

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#221]
Would it be possible to add an automatic conversion from:

- bytes16 (_Solidity_) to Guid (_C#_)
- Guid (_C#_) to bytes16 (_Solidity_)

**Comment by fasmat** [comment]
Is it possible to use bytes16 at all? The function i'm calling has the following signature:
`function getInfo(bytes16 arg) public view returns (address, bytes16)`

 I defined my FunctionOutput as follows:
```
[FunctionOutput]
public class Result {

    [Parameter("address", "address", 1)]
    public string Address { get; set; }

    [Parameter("bytes16", "id", 2)]
    public byte[] Id { get; set; }
}
```
calling it the following way always seems to fail with System.NotSupportedException:
```
var function = contract.GetFunction("getInfo");
return await function.CallAsync<Result>("test".ToByteArray());
```

'xxx.Result is not supported'

**Comment by StefH** [comment]
My contract looks like this:
``` js
function getOrderByManufacturerAndId(address _manufacturer, bytes16 orderId) public view returns (
		bytes16 id,
		// more fields
	) {

	require(orderId > 0);

	// more code ...

	return (
		order.id,
		// more fields
	);
}
```

And C# DTO looks like:
```c#
[FunctionOutput]
public class GetOrderByManufacturerAndId
{
	[Parameter("bytes16", "id", 1)]
	public byte[] Id { get; set; }

	// more fields
}
```

And this code can be used like:
``` c#
var order = await service.GetOrderByManufacturerAndIdCallAsync(Manufacturer1.Address, Manufacturer1.Address, order.OrderId);
var uuid = new Guid(order.Id);
```

**Comment by juanfranblanco** [comment]
Added now :) let me know how it goes.

**Comment by StefH** [comment]
When will you create new NuGet?

I noticed that the file `src/Nethereum.ABI/Decoders/BytesElementaryTypeDecoder .cs` has an extra space in the name?

**Comment by juanfranblanco** [comment]
There is now a Continuous Integration myget feed

**Comment by juanfranblanco** [comment]
https://www.myget.org/feed/nethereum/package/nuget/Nethereum.Web3
