### ISSUE TITLE
Error deploying contract : Code not deployed succesfully

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#222]
This C# code deploys contract on local development geth instance.
```cs
var transactionReceipt = await web3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync(ABI, ByteCode, addressFrom, gas, token);
```
Throws an exection:

> Unhandled Exception: System.AggregateException: One or more errors occurred. (Code not deployed succesfully) ---> Nethereum.RPC.Eth.Exceptions.ContractDeploymentException: Code not deployed succesfully
>    at Nethereum.RPC.TransactionReceipts.TransactionReceiptPollingService.<DeployContractAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at ConsoleApp.SupplyChainLogContractService.<DeployContractAsync>d__2.MoveNext()

Is there any way to detect what's wrong?

See abi and bin files:
[contract.abi.txt](https://github.com/Nethereum/Nethereum/files/1571578/contract.abi.txt)
[contract.bin.txt](https://github.com/Nethereum/Nethereum/files/1571579/contract.bin.txt)

**Comment by juanfranblanco** [comment]
You may have ran out of gas, (not supplied enough) you have the receipt as part of the deployment exception. The check validates that the code exists, in the contract address, if it doesn't throws the exception.

**Comment by StefH** [comment]
I'm not sure if gas is the issue.
Is there a way to detect / calculate the gas requirements?

**Comment by juanfranblanco** [comment]
You can estimate your gas mostly correctly using EstimateGasAsync when using Geth for Function transactions, BUT it does not work particularly well on Deployment. The total cost of remix "might" be correct, depending of what you do on your constructor. 

There might be a problem with your constructor hence the error.

**Comment by StefH** [comment]
When I set the logging from `geth.exe` to `--verbosity 4`, I see this:
```bash
INFO [12-20|06:54:30] Submitted contract creation              fullhash=0x090328b5dec637bea85953f8d63b595f761fc4780705e8b72fe69c384275b6bb contract=0x6c498f0f83d0BBEc758ee7F23E13C9Ee522A4c8F
INFO [12-20|06:54:31] Successfully sealed new block            number=74 hash=cb8ab2…32cf3e
DEBUG[12-20|06:54:31] Trie cache stats after commit            misses=6 unloads=0
INFO [12-20|06:54:31] 🔗 block reached canonical chain          number=69 hash=beeac9…d12cda
INFO [12-20|06:54:31] 🔨 mined potential block                  number=74 hash=cb8ab2…32cf3e
DEBUG[12-20|06:54:31] Reinjecting stale transactions           count=0
DEBUG[12-20|06:54:31] VM returned with error                   err="contract creation code storage out of gas"
```

The `genesis_dev.json` defines 
```js
"gasLimit": "0x4c4b40"
```

Which is 5000000, and this seems to be not enough.

**Comment by juanfranblanco** [comment]
This is the gas for the Transaction deployment, not the overall gas limit per block. So you need to put the gas in your transaction call.

Kind of like this workbook http://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstard-smartcontrats/

This can be opened if you want here: 
http://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/

**Comment by StefH** [comment]
OK. It's solved.

```c#
var gasForDeployContract = new HexBigInteger(10000000);
```

**Comment by ognjenkurtic** [comment]
I get the same error message occasionally while deploying using:

`web3.Eth.GetContractDeploymentHandler<TestContractDeploymentMessage>().SendRequestAndWaitForReceiptAsync(message);` 

The fun part is that the contract actually gets  deployed but Nethereum throws the `ContractDeploymentException`.

Transaction receipt logs after the "failed" deployment transaction are empty: 

`catch (ContractDeploymentException ex)`
     ` {`
            `logger.Log(LogLevel.Error, $"Deployment failed: {ex.Message} ");`
            `if(ex.TransactionReceipt.Logs != null) {`                 
            ` logger.Log(LogLevel.Error, $"Errors: {ex.TransactionReceipt.Logs.ToString()} ");`
      `}`

I am using Nethereum 2.5.1.

**Comment by juanfranblanco** [comment]
I recommend you move to 3.0 first. It has many improvements.
Regarding your question, it has surface that Parity sometimes does not store the contract before returning a transaction receipt, so that might be the cause of the issue.
