### ISSUE TITLE
Unity Network error

### ISSUE THREAD

**Issue by Scott4u123** [Nethereum/Nethereum#225]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Networking' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)	Nethereum.Unity(net35)	C:\Projects\...\Nethereum-master\Nethereum-master\src\Nethereum.Unity\UnityRpcClient.cs	8	Active.

I opened the solution in VS2017

**Comment by nguyendangdung** [comment]
I resolved this by installing https://www.nuget.org/packages/UnityEngine5/
