### ISSUE TITLE
Can't open/build Nethereum.sln in Visual Studio for Mac

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#228]
So today I cloned Nethereum and tried to open its solution in Visual Studio for Mac 7.3, and I get a bunch of this kind of errors:

```
Error while trying to load the project '/Users/andres/Documents/Code/Nethereum/src/Nethereum.Hex/Nethereum.Hex.csproj: Project does not support framework '_, Version=v0.0'
```

The nuget package restore also fails.

**Comment by juanfranblanco** [comment]
Yes, I am looking at that this week. There was a pull just to force netstandard but broke other stuff.

**Comment by juanfranblanco** [comment]
Felices Reyes ;)

**Comment by knocte** [comment]
It might be a VS4Mac bug actually. Seems like the import of some .props file is not working in this platform? We should open a bug on Xamarin's bugzilla probably.

**Comment by juanfranblanco** [comment]
Yes true, everything should work out of the box in VS4Mac apart from the Windows-specific projects. I read they are moving the bug tracking to GitHub (I don't know if they have already)

**Comment by knocte** [comment]
VS4Mac 7.4 can open it!
