### ISSUE TITLE
Set client timeout

### ISSUE THREAD

**Issue by raymens** [Nethereum/Nethereum#23]
Sometimes a RPC request takes a lot of time. It would be great to be able to set a timeout (probably in the IClient, or maybe per request).

**Update:**
I guess it's also possible to just cancel the `Task<T>`

**Comment by juanfranblanco** [comment]
Yes to both :).. Ill have a look to expose the timeout on IClient

**Comment by mikhail-mikhaylov** [comment]
So, how's it going?:)
If I got it right, this feature is still missing?

**Comment by juanfranblanco** [comment]
Yes, still missing. The task solution seems to be the simplest one.
Ill move this to Release 2.0.1

**Comment by juanfranblanco** [comment]
Done in 2.4.1
