### ISSUE TITLE
Is Unity documentation available?

### ISSUE THREAD

**Issue by CCludts** [Nethereum/Nethereum#230]
Hi.

I would love to use this library, but it seems API in the Unitypackage is different from the API in the regular version. 
for example, `new Web3("https://morden.infura.io/aEcNY6wGN4KuEpoXQRxZ");` doesnt seems to work.
I would also like to use the HDWallet class, which doesnt seem like it's available either.
I am interested in building for android & ios, so the UWP/HoloLens example didnt help much.
Is there any place with documentation for the Unity? (just a simple example would already be nice)

cheers

**Comment by juanfranblanco** [comment]
You can try as a simple sample this:
https://github.com/Nethereum/Unity3dSimpleSample
or the original blog post
https://medium.com/@juanfranblanco/nethereum-2-0-0-rc5-unity3d-integration-eb7664664813
which links to other source code.

Yes it does not work that way... the HDWallet needs to be downported to work in Unity
