### ISSUE TITLE
Creating account in one transaction node is not replicating in other transaction node

### ISSUE THREAD

**Issue by srinivasvinnakota** [Nethereum/Nethereum#231]
I have a private ethereum consortium in azure with 2 transaction and 4 mining nodes. I created account in one of the transaction node, upon doing SSH. I assumed that account should be synced to all transaction nodes. But when tried to check for accounts in the 2nd transaction node, i am not seeing the new account created.

**Comment by srinivasvinnakota** [comment]
Also i am following sample (http://solidity.readthedocs.io/en/develop/introduction-to-smart-contracts.html) for storing a temporary value and then retrieving. I did deploy the contract and executed below code, but not seeing the returned value same as set.

pragma solidity ^0.4.0;

contract SimpleStorage {
    uint storedData;

    function SimpleStorage() public {
    }
    function set(uint x) public {
        storedData = x;
    }

    function get() public constant returns (uint) {
        return storedData;
    }
}

 var contractAddress = "[contract address]";
            var contract = web3.Eth.GetContract(abi, contractAddress);
            var setFunc = contract.GetFunction("set");
             var setCall=await setFunc.CallAsync<int>(8);            
            var getFunc=contract.GetFunction("get");
            **var result=await getFunc.CallAsync<int>();
            //result is zero, but i am expecting 8.**

Am i missing something here.

**Comment by srinivasvinnakota** [comment]
Hi,

Could i get help here please.

I even tried below smart contract. After deploying the contract, i first called **Multiply** function and it returned result as expected.
 Then i tried calling **SetMultiplier** function, i see the return value is as expected.
Later when i call **Multiply** function, i expected that value passed "**SetMultiplier**" could have persisted and should have returned value accordingly. But instead noticed that the value passed during 
"**SetMultiplier**" is not persisted to **_multiplier**.

Please help here, severely spent time but couldnt able to help myself.
pragma solidity ^0.4.0;

contract Matematics {
    
    uint _multiplier;
    function Matematics(uint multiplier) public {
        _multiplier=multiplier;
    }


function **SetMultiplier**(uint input) public  returns (uint) {
    _multiplier=input;
    return _multiplier * input;
}
    function **Multiply**(uint input) public returns (uint){
        return _multiplier * input;
    }
}

**Comment by Trycoder** [comment]
Hi Srinivas,
Set function doesnot work like a normal call.Instead it is kind of a transaction which consumes some gas for that particular transaction.
Try Something like this:
setfunction.SendTransactionAsync(senderAddress, value);

Hope this helps!!!
