### ISSUE TITLE
Transactions seem to not be propagated into ethereum network

### ISSUE THREAD

**Issue by franceq** [Nethereum/Nethereum#232]
Hi,
i am quite new in Nethereum project. The only thing I need is creating an offline transaction and push it into ethereum network which seems to be bigger problem that I expected. I ll try to describe my code (C#) and after the code also the problem:
```
string privateKey = "myprivkeyblabalbal";
string senderAddress = Nethereum.Web3.Web3.GetAddressFromPrivateKey(privateKey);
string receiveAddress = "0xblablablabla";
var web3 = new Nethereum.Web3.Web3("https://mainnet.infura.io/mytokenblabla");
decimal amount = 0.0012345678911m;
BigInteger gasLimit = 90000;
decimal gasPriceGwei = 81;
BigInteger wei = Nethereum.Web3.Web3.Convert.ToWei(amount, UnitConversion.EthUnit.Ether);
var tx = Nethereum.Web3.Web3.OfflineTransactionSigner.SignTransaction(privateKey, receiveAddress, wei, 10, Nethereum.Web3.Web3.Convert.ToWei(gasPriceGwei, UnitConversion.EthUnit.Gwei), gasLimit);
var send = web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + tx);
```

Everything looks well, but if I check the hash which is returned in the result of task stored in variable "send" in some online ethereum explorer - for example etherscan.io - I can not find any such transaction, even if I wait for few hours it does not help. Any idea why the transaction is not propagated into the network? I am also iterating the nonce (so the nonce probably is not the problem), also the balance (amount of ethereum) on the address is enough for all the operations including fees. I do not know if there is a problem in the library or in infury or in my misunderstanding of the concept.

Best regards FF

**Comment by juanfranblanco** [comment]
Apologies I have missed this, if you don't get an answer ASAP please go to the Nethereum gitter channel.
