### ISSUE TITLE
Event watching on Unity3D

### ISSUE THREAD

**Issue by drlecks** [Nethereum/Nethereum#235]
I've been testing with this awesome library for a while and most of the features work out of the box. Wallet operations, contract calls/transactions...

But I haven't been able to deal with Events and logs. Although I've switched to .Net 4.6, Visual studio can't find `GetFilterChanges()` and it's impossible to find any Event.

Is it planed to add Event compatibility with unity?

**Comment by juanfranblanco** [comment]
In 3.5 use EthGetFilterChangesForEthNewFilterUnityRequest

**Comment by drlecks** [comment]
And where do I get the filterId from?

**Comment by drlecks** [comment]
Is it planned to add full Log/Events support with Unity in future updates?

**Comment by juanfranblanco** [comment]
@drlecks it is supported you just need to create the requests using UnityRequests, same as others.

**Comment by juanfranblanco** [comment]
Help issue, closing
