### ISSUE TITLE
Cannot find web3.Mine

### ISSUE THREAD

**Issue by john199604** [Nethereum/Nethereum#237]
Hello,

I wanted to know if there is any new tutorial soon? Since i guess there are a lot of updates since the last tutorial on Agugust 2016. Also it's getting bigger and bigger this technology, so there is only this library for .Net and it should be updated.

The one I need from that old tutorial is web3.Mine. I couldn't find it anywhere.

Thank you.

**Comment by juanfranblanco** [comment]
This is part now of Nethereum.Geth using Web3Geth. Mainly mining is specific of Geth hence the move.
But in general if you start geth to automine, it works better for unit test, development. As in general you would not control it by the application / service etc.

**Comment by john199604** [comment]
Can you please make any updated tutorial if you have any free time?

**Comment by juanfranblanco** [comment]
You can have a look at this https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.Tutorials
Or you can run some workboos https://github.com/Nethereum/Nethereum.Workbooks

**Comment by juanfranblanco** [comment]
Or also the docs which are also being updated http://nethereum.readthedocs.io/en/latest/
