### ISSUE TITLE
This line takes too long to executes and throws Nethereum.JsonRpc.Client.RpcClientUnknownException

### ISSUE THREAD

**Issue by john199604** [Nethereum/Nethereum#238]
Hello, 

I wanted to ask you why this line here it takes to long to execute, and because of the long processing time, the app just throws a Bad Gateway error.
`var receipt = await web3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync(abi, byteCode, senderAddress, new HexBigInteger(900000), null, multiplier);`

p.s. I changed the last issue to this one, because in the last one the problem was with my code, and thought that would be better than opening a new issue.

![1234](https://user-images.githubusercontent.com/34715761/35300030-8c406cfa-0087-11e8-9f4e-2b4a642cb8e3.jpg)
This is the error i get when i try to access that function on my controller with ajax. And that line 48 is the line i wrote up there.

**Comment by juanfranblanco** [comment]
Yes, you are waiting for a receipt, so you are mainly waiting for the transaction to be mined. Have you started mining in your localhost:8545 client?

**Comment by john199604** [comment]
No i didn't, but now when i also open localhost:8545 it show me this one
![image](https://user-images.githubusercontent.com/34715761/35474069-4a40b6f2-0389-11e8-9509-bcc0effce296.png)
`{"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}`

**Comment by juanfranblanco** [comment]
Has this been solved? @john199604

**Comment by juanfranblanco** [comment]
Closing
