### ISSUE TITLE
Exception in Creating Filters for events in contract deployed to RopstenNetwork

### ISSUE THREAD

**Issue by Trycoder** [Nethereum/Nethereum#239]
Hi,
Im getting a Method Not Allowed (405)exception when CreateFilterAsync() is run.
The contract is deployed  in Ropsten Test Net

var contract = web3.Eth.GetContract(abi, contractAddress);
            var gtEvent = contract.GetEvent("GetTransaction");
            var filterAllGetEvent = await gtEvent.CreateFilterAsync();

Can Somebody Help?

**Comment by juanfranblanco** [comment]
If you are pointing to Infura. Infura does not support filters.

**Comment by jsheely** [comment]
Does that mean it doesn't support events period? Or you just can't filter for specific events. Can we just get all the events

**Comment by juanfranblanco** [comment]
You can create a NewFilterInput using the Event and GetAllChanges. On the NewFilterInput specify the blockrange you are interested

**Comment by jsheely** [comment]
So would using the default null values for the block ranges would I expect it to give me all the events from the beginning of the contract?

**Comment by juanfranblanco** [comment]
No, that wouldn't work as Geth won't return you any values. You need to specify a smaller range.

Closing as this is a known unsupported area in Infura
