### ISSUE TITLE
Trouble using Events / Logs / Filters

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#24]
So I copied the examples in the README, but cant seem to get my Events to come through to Nethereum.

Here is the tx on testnet: https://testnet.etherscan.io/tx/0x0d3fd431855e312c63301e9e97cb4777d6cba3979d465455cad33a8873046f0f#eventlog

Here is my DTO class and test method for accessing the Events..
```
		public class EventBatchUploaded
		{
			[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("string", 1)]
			public string address { get; set; }

			[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("bytes", 2)]
			public byte[] hashBytes { get; set; }
		}

		public static void test(string contractAddress, long fromBlock) {
			var web3 = new Web3(ethereum_address);
			var dataFeedContract = web3.Eth.GetContract(abi, contractAddress);

			var filterAllContract = dataFeedContract.CreateFilterAsync().Result;
			var logs = web3.Eth.Filters.GetFilterChangesForEthNewFilter.SendRequestAsync(filterAllContract).Result;

			Nethereum.Web3.Event e = dataFeedContract.GetEvent("BatchUploaded");
			var filterAll = e.CreateFilterAsync().Result;
			var eventLogsAll = e.GetFilterChanges<EventBatchUploaded>(filterAll).Result;

		}
```

as you can see I tried both the Contract get all approach and also the Event specific approach, both return 0 rows.  Not sure what i'm doing wrong.

**Comment by juanfranblanco** [comment]
Make sure you create the filter before the transaction, you can use "get all" also. Check the maker example.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Netherum.Maker/blob/master/Nethereum.Maker.Sample/MakerTokenRegistryServiceTest.cs

**Comment by slothbag** [comment]
Oh right, I need to get all changes since a specified starting block.. so starting at 0 but then running it again using the last checked block etc

I also tried the **GetAllChanges** method but that didn't work either.

I searched the code for "get all", I couldn't find anything.. can you elaborate?

**Comment by slothbag** [comment]
Hmm, if I run this code Nethereum never returns a result, locking the app.

```
Nethereum.Web3.Event e = dataFeedContract.GetEvent("BatchUploaded");
var filterId = e.CreateFilterAsync(new Nethereum.RPC.Eth.DTOs.BlockParameter(500000)).Result;
var changes = e.GetAllChanges<EventBatchUploaded>(filterId).Result;
```

**Comment by juanfranblanco** [comment]
Hi, 
```
var filterId = e.CreateFilterAsync(500000).Result;
var changes = e.GetAllChanges<EventBatchUploaded>(filterId).Result;
```
Get all changes, that is the method I meant. I was on the phone so I could not be more explicit. As you have seen the CreateFilterAsync is using the block number, so anything from that blocknumber will be retrieved as opposed to GetFilterChanges which will retrieve any changes since creation.

Int32? Interesting you have an address and bytes ?

**Comment by slothbag** [comment]
I think this is the problem here.. https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/EncoderDecoderHelpers.cs#L12

numberOfBytesEncoded is either 32 or 160 bytes.. trying to parse into intDecoder??

**Comment by juanfranblanco** [comment]
Yes I have created a unit test and it returns 64 bytes length after stripping the address
```
   var original = "0x000000000000000000000000223aea5cf8c5a21859171edb2d01d2ceab0336780000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002e516d5074633431505661375945585a7359524448586a6332525753474c47794b396774787a524e6543354b4e5641000000000000000000000000000000000000";
            var bytes = "0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002e516d5074633431505661375945585a7359524448586a6332525753474c47794b396774787a524e6543354b4e5641000000000000000000000000000000000000";
            var bytesType = new BytesType();
            var bytesArray = bytes.HexToByteArray();
            var decoded = (byte[])bytesType.Decode(bytesArray, typeof(byte[]));
```

**Comment by slothbag** [comment]
This is the solidity Event
`event BatchUploaded(address, bytes);`

So it should be an address and the second is a byte array.. should be under 32 bytes but could be more i guess.

I'm not sure if i'm understanding your question though :)

**Comment by juanfranblanco** [comment]
no the byte array is longer, the first 32 bytes is the length.. which returns 64 bytes in this scenario, but there are remaining bytes after the address.

**Comment by slothbag** [comment]
Ok, that could be the case, it might be like 34 bytes or something which causes geth to pad out to 64 bytes..

Shouldn't the decoder be able to support a byte array of in-determinant length?

**Comment by juanfranblanco** [comment]
yes it does geth gives us the length

**Comment by juanfranblanco** [comment]
ill look into it maybe for events in this scenario you just need the data part as it is the last field

**Comment by juanfranblanco** [comment]
but I have never got an overflow decoding on all the tests

**Comment by slothbag** [comment]
Thanks for investigating.

How would you handle an Event like this

`event BatchUploaded(address, bytes, uint256);`

where you have an unknown size byte array as 2nd param, but then also another regular uint param as the 3rd? You wouldn't want to bundle the 2nd and 3rd together into a generic data field.

**Comment by juanfranblanco** [comment]
bytes are not stored in the header... there are in the data of the data

**Comment by juanfranblanco** [comment]
so if you are missing a field everything goes pair shape :)

**Comment by juanfranblanco** [comment]
here is the docs https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI

**Comment by juanfranblanco** [comment]
Also I had a typo I meant 46 instead of 64, 64 is the location of data.

**Comment by juanfranblanco** [comment]
if you are looking for a string.. i got this "QmPtc41PVa7YEXZsYRDHXjc2RWSGLGyK9gtxzRNeC5KNVA"

**Comment by slothbag** [comment]
Yeah I was just looking at the bytes.. a header of 2e, showing 46 bytes, followed by a bunch of 0's for padding.  

So i'm not sure where we are at.. is this a bug in Nethereum or in Ethereum?

**Comment by juanfranblanco** [comment]
well i have 46 bytes.. then.. I don't get any overflow. BUT if we have padding I wonder what is happening with endianism.

**Comment by juanfranblanco** [comment]
what bytes are you expecting?

**Comment by slothbag** [comment]
Yes, I need both the address and the string as provided by the Event   the string is the one you highlighted.. all the data i need is in the 160 bytes..  It just doesn't seem to be decoding it for some reason.

**Comment by juanfranblanco** [comment]
on your event you can do this:

[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("bytes", 2)]
public string hashBytes { get; set; }

**Comment by juanfranblanco** [comment]
you mentioned you had an issue with overflows, is that a red herring?

**Comment by slothbag** [comment]
Could be.. Cause in my main project Nethereum just hangs and never returns.. but in my test project it returns the int overflow error.. maybe i'll put my test project up in gist for you to try

**Comment by juanfranblanco** [comment]
ok that will be great.. It won't be straight away as I am going to work.

**Comment by slothbag** [comment]
No worries.. no rush,

https://gist.github.com/slothbag/fe6b36475cfa2d1c43e54238825c1e32

**Comment by juanfranblanco** [comment]
The issue is in your address, it is not a type of a string.. is a type of address


        public class EventBatchUploaded
        {
            [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("address", 1)]
            public string address { get; set; }

            [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("bytes", 2)]
            public string hashBytes { get; set; }
        }

**Comment by juanfranblanco** [comment]
I was looking for a complex problem... hence the bytes.. also I have changed the return of hashbytes to string, so you can decode directly.

**Comment by slothbag** [comment]
Really.. I had a previous problem with Nethereum where I had to change an array of Addresses to an Array of strings to make it work.. 

```
		[Nethereum.ABI.FunctionEncoding.Attributes.Function(Name = "getAllDataFeeds")]//, Sha3Signature="78cded60")]
		[Nethereum.ABI.FunctionEncoding.Attributes.FunctionOutput]
		private class getAllDataFeedsFunction
		{
			[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("bytes4[500]", "feedCode", 1)]
			public List<byte[]> feedCode { get; set; }

			[Nethereum.ABI.FunctionEncoding.Attributes.Parameter("address[500]", "addresses", 2)]
			public List<string> addresses { get; set; }

		}
```

**Comment by juanfranblanco** [comment]
No it was your type declaration of the abi

**Comment by slothbag** [comment]
Oh, I see.  The Parameter declaration type.. ughh.. sorry.

**Comment by juanfranblanco** [comment]
Typos are evil.. aren't they? we look for the most complex issues..

**Comment by slothbag** [comment]
Ok, I think this should resolve it.  Thanks and my apologies :)

**Comment by slothbag** [comment]
Plus i'm finding it very hard to debug, as the debugger drops straight out after each async call.. so I have to breakpoint and restart for each call.. probably an issue with XS, im sure the debugging in VS is much nicer :)

**Comment by juanfranblanco** [comment]
yes much easier, get visual studio 2015 update 2. I have added a SimpleTest project with your gist, that might help.

**Comment by juanfranblanco** [comment]
also out of topic now XS project is separate for portable, so feel free to push those bits there.
