### ISSUE TITLE
How to use gas from other wallet

### ISSUE THREAD

**Issue by jayantbramhankar** [Nethereum/Nethereum#244]
I've created an HD wallet containing many accounts, where wallet.GetAccount(0) holds ETHERs and other wallets been used receive ERC20 tokens for users.

How can I transfer these tokens from child to main(0) account.

Is there any way to use main account gas. 
I'm using  [https://github.com/Nethereum/Nethereum](https://github.com/Nethereum/Nethereum) library in Asp.net MVC.

Thanks.

**Comment by juanfranblanco** [comment]
No, you cannot, all accounts are unrelated to each other.

**Comment by jayantbramhankar** [comment]
Thanks, what is the best way then.
Shall I transfer ether(for gas) to child and then transfer tokens to parent.
Let me know any best approach to this as per your experience.

**Comment by juanfranblanco** [comment]
yes, that is about it.

**Comment by juanfranblanco** [comment]
```csharp
     currentAmount = await web3.Eth.GetBalance.SendRequestAsync(fromAccount.Address);
                currentAmount = currentAmount - (web3.TransactionManager.DefaultGas * web3.TransactionManager.DefaultGasPrice);
```
Use this to transfer the total amount back to your main account.
