### ISSUE TITLE
When passing a NewFilterInput to an Event, the event should set or verify the contract address and event topic1

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#248]
There is a scenario when a developer might not have created a NewFilterInput using the Event. 
In this scenario, the NewFilterInput is detached from the Event.

So when using GetAllChanges and passing as a parameter a NewFilterInput, we could either through an exception if the contract address / topic1 does not match. 

Or override the contract address and topic1. 

I prefer to throw an exception.

**Comment by v-lukanin** [comment]
Is there a scenario when NewFilterInput public ctor is needed? It sounds like it can be made internal if it is not supposed to be used separately from Event.

**Comment by juanfranblanco** [comment]
No NewFilterInputs can be used for other "filters" that do not relate to an specific event. You can get all the logs from a specific smart contract. https://github.com/ethereum/wiki/wiki/JSON-RPC
