### ISSUE TITLE
Didn't getting any response while fetching Ethereum event logs data (of specific event) using Nethereum in C# console application

### ISSUE THREAD

**Issue by AshishBhalodiya** [Nethereum/Nethereum#249]
I am working in C# console application and need to read Ethereum event logs of specific event from Ethereum API. I have preferred Nethereum to do that task. But, Whenever i try to fetch the Event logs using API call then nothing is getting as output. Didn't get any expected data.

I have a following parameters to get event logs:
1. Ethereum API url
2. Contract ABI address
3. Contract address
4. Event name

following are the lines of code, which i am using to get event logs using Nethereum library in C# console application:

`var web3 = new Nethereum.Web3.Web3(@UrlString);
var contract = web3.Eth.GetContract(@abi, @contractAddress);
var event = contract.GetEvent(@eventName);
var filter = await event.CreateFilterAsync();
var logs = await event.GetAllChanges<MultipliedEvent>(filter);`

Didn't getting in "logs". Is anything missing by me? 
Here help would be more appreciated.

**Comment by juanfranblanco** [comment]
You need to pass a block range (start, from), geth (i pressume) won't retrieve all the data from the blockchain.

**Comment by AshishBhalodiya** [comment]
Can you please provide a sample code or code snippet?

**Comment by juanfranblanco** [comment]
You may find this useful https://github.com/Nethereum/Nethereum.Workbooks/issues/7

**Comment by AshishBhalodiya** [comment]
Thanks for sharing the link.

open the link,

In below line, i don't wont to use class "BidAddedEventDTO".  Is it possible with GetAllChanges() method?

`var logs = await stateChangedEventLog1.GetAllChanges<BidAddedEventDTO>(filterInput);`

**Comment by juanfranblanco** [comment]
You need to create your own class to output the parameters, check the information on events and event dtos here:
http://nethereum.readthedocs.io/en/latest/contracts/calling-transactions-events/
