### ISSUE TITLE
Web sockets support

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#25]
Implement web sockets support starting from geth 1.4 https://github.com/ethereum/go-ethereum/releases/tag/v1.4.0

**Comment by djsowa** [comment]
Working on this ;)

**Comment by djsowa** [comment]
Ah, just thinking of reusing my old impl.

wt., 26.06.2018, 19:26 użytkownik Juan Blanco <notifications@github.com>
napisał:

**Comment by juanfranblanco** [comment]
New version available on master
