### ISSUE TITLE
Newtonsoft Json.NET conflict in Unity (Android+IL2CPP)

### ISSUE THREAD

**Issue by qbit86** [Nethereum/Nethereum#250]
Some libraries like `Nethereum.JsonRpc.Client` reference `Newtonsoft.Json` NuGet-package version 10.0.3. Another libraries like `Nethereum.Unity` and `Nethereum.HdWallet`→`NBitcoin` references version 9.0.0 of provided `Newtonsoft.Json.dll` binary.

This results in error CS0012 when I try to add source code of `Nethereum.Unity` to Unity project:
> The type 'JObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.

Including `Nethereum.Unity.dll` binary instead results in IL2CPP error, when I try to build for Android, although it works for Mono.

**Comment by juanfranblanco** [comment]
The Nethereum HdWallet is not supported in Unity3D

**Comment by juanfranblanco** [comment]
Closing as using a none Unity-specific library.
