### ISSUE TITLE
BigInteger Constructor does not handle a byte array with all 0 values

### ISSUE THREAD

**Issue by doreegekku** [Nethereum/Nethereum#251]
Title. Can repro by trying to do any sort of DTO Decoding function call, and passing in a value of zero.

**Comment by juanfranblanco** [comment]
```csharp

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Numerics;
using Nethereum.Hex.HexConvertors.Extensions;

namespace BigIntegerTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var hex = "0x000000000";
            var byteArray = hex.HexToByteArray();
            var bigInteger = new BigInteger(byteArray);
        }
    }


}

```

**Comment by juanfranblanco** [comment]
There is no issue here, can you put a sample? Environment, ie Unity?

**Comment by doreegekku** [comment]
Yeah, it's in Unity. Version 2017.3.1f1

using System.Numerics;
using Nethereum.Hex.HexConvertors.Extensions;
using UnityEngine;

public class test : MonoBehaviour {
    void Start()
    {
            var hex = "0x000000000";
            var byteArray = hex.HexToByteArray();
            var bigInteger = new BigInteger(byteArray);
        
    }
}


Provides:
IndexOutOfRangeException: Array index is out of range.
System.Numerics.BigInteger..ctor (System.Byte[] value)
test.Start () (at Assets/test.cs:14)

**Comment by juanfranblanco** [comment]
What version of Nethereum.Unity are you using? The current version includes a new BigInteger

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/releases/tag/2.2.1

**Comment by doreegekku** [comment]
That one. Am I not supposed to be using the one from System.Numerics?

**Comment by juanfranblanco** [comment]
The one included has a version of System.Numerics for backwards compatibility. But you should not add yours.
