### ISSUE TITLE
How can i know which parameters i need to write in external [FunctionOutput] class while getting all changes by applying filter

### ISSUE THREAD

**Issue by AshishBhalodiya** [Nethereum/Nethereum#252]
I am using Nethereum to read the Ethereum event logs through C# console application.
I have an following lines of code to get all changes by filter:

```
var event = contract.GetEvent("@EventName");
var filter = event.CreateFilterInput(BlockParameter.CreateEarliest(), BlockParameter.CreateLatest());
var data = event.GetAllChanges<MyClass>(filter);
```
but i am getting confused in last line of code. Because i have created [FunctionOutput] class named "MyClass". I don't know what & which type of parameters will returned by last line. 

So, my question is that, 
how can i know which parameters i need to write inside "MyClass" for data mapping?

**Comment by juanfranblanco** [comment]
You could use the code generator in VisualStudio, Solidity or the code generator provided in Nethereum
https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.Generator.Console

But it is as simple as:
Each Parameter maps to the parameter output of the Event, you need to provide the type name, name, order of the parameter and if it is indexed or not.

**Comment by juanfranblanco** [comment]
Closing as help provided.
