### ISSUE TITLE
How to get Block by Block number in Nethereum?

### ISSUE THREAD

**Issue by AshishBhalodiya** [Nethereum/Nethereum#253]
I am a new user of Nethereum library using C#. I had googling on how to get Block by Block number but didn't get any solution yet.

Please provide me a code snippet or any other reference.

**Comment by juanfranblanco** [comment]
var block = await web3.Eth.Blocks.GetBlockWithTransactionsByNumber.SendRequestAsync(new HexBigInteger(100));

100 is the blocknumber

**Comment by thetinshusasi** [comment]
Hi,
Is there a method using which i can download the entire blockchain  blocks, starting from genesis block

**Comment by KevinSmall** [comment]
@thetinshusasi see https://github.com/Nethereum/Nethereum.BlockchainProcessing

Note this ticket is closed, if you have questions you'll get faster reponse on Gitter https://gitter.im/Nethereum/Nethereum
