### ISSUE TITLE
Infura - Unlock Account throws RPC error

### ISSUE THREAD

**Issue by maxcap888** [Nethereum/Nethereum#254]
I want to deploy a smart contract. My code works fine while running a local instance of Geth (Rinkeby).
However, when I switch to Infura using my assigned URL, I get an error when trying to unlock the account.

> "Error occurred when trying to send rpc requests(s)"

This is the line that throws the error:
 `var resultUnlocking = await _web3.Personal.UnlockAccount.SendRequestAsync(_accountAddress, _password, 60);`

Is there a different way to deploy a contract if using an external provider like Infura?

**Comment by juanfranblanco** [comment]
Infura does not host your accounts, for this, you need to sign the transactions beforehand using your private key. 

The accounts document will help to understand the differences between accounts, in this scenario you need an Account object with its private key.

http://nethereum.readthedocs.io/en/latest/accounts/

**Comment by maxcap888** [comment]
Do I still need to "Unlock" the account before deploying the contract or just creating the account object and then deploy the contract is sufficient?

**Comment by juanfranblanco** [comment]
No you don't need to in any situation, ManagedAccount uses the password to submit transaction and then Parity or Geth will decrypt the private key and sign the transaction.

Account does the signing for you, so there is no need to unlock an account
