### ISSUE TITLE
How to get all token transactions of an address.

### ISSUE THREAD

**Issue by jayantbramhankar** [Nethereum/Nethereum#255]
I'm Using this library(c#), need to get all the token (transfer/receive) transactions list of an wallet address.

Contract Address: | 0xb8c5e80904f84092a7deb23e09e59c9bc3e06326

**Comment by juanfranblanco** [comment]
You can use the Parity Filters for that

**Comment by jayantbramhankar** [comment]
This need parity running, can't I get this using NEthereum library.  I'm using INfura.

**Comment by juanfranblanco** [comment]
Then you need to check each block

**Comment by jdmadriz** [comment]
@izzycoder18 I'm having the same issue. Did you solved it?

**Comment by juanfranblanco** [comment]
@jdmadriz check the events documentation http://docs.nethereum.com/en/latest/Nethereum.Workbooks/docs/nethereum-events-gettingstarted/ you can iterate through a set of blocks to retrieve the transfers 

You can also use the log processing, which simplifies the tracking of block numbers retrieved. You can find samples on http://playground.nethereum.com
