### ISSUE TITLE
Nethereum.JsonRpc.Client.RpcResponseException: 'unknown transaction' from Geth 1.8.1

### ISSUE THREAD

**Issue by smurz** [Nethereum/Nethereum#258]
Hello.
I'm getting Nethereum.JsonRpc.Client.RpcResponseException: 'unknown transaction' while trying to deploy any contract on local test network with the latest Geth 1.8.1
When I switch back to Geth 1.7.3 everything works perfectly.

It throws this exception even on example from the docs:

        private async Task DeployContract()
        {
            var senderAddress = "0x12890d2cce102216644c59daE5baed380d84830c";
            var password = "password";
            var abi = @"[{""constant"":false,""inputs"":[{""name"":""val"",""type"":""int256""}],""name"":""multiply"",""outputs"":[{""name"":""d"",""type"":""int256""}],""type"":""function""},{""inputs"":[{""name"":""multiplier"",""type"":""int256""}],""type"":""constructor""}]";
            var byteCode =
                "0x60606040526040516020806052833950608060405251600081905550602b8060276000396000f3606060405260e060020a60003504631df4f1448114601a575b005b600054600435026060908152602090f3";

            var multiplier = 7;

            var web3 = new Web3();
            var unlockAccountResult =
                await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 120);
            var gas = await web3.Eth.DeployContract.EstimateGasAsync(abi, byteCode, senderAddress, multiplier);

            var receipt =
                await web3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync(abi, byteCode, senderAddress, gas, null,
                    null, multiplier);

        }

`

**Comment by smurz** [comment]
I've managed to work around this exception like this:

```
public static async Task<TransactionReceipt> SendDeployRequestAndWaitForReceiptAsync(this DeployContract deployContract, Web3 web3, string abi, string contractByteCode, string from, HexBigInteger gas, HexBigInteger gasPrice, HexBigInteger value, CancellationTokenSource receiptRequestCancellationToken = null, params object[] values)
        {
            try
            {
                var txHash =
                    await deployContract.SendRequestAsync(abi, contractByteCode, from, gas, gasPrice, value, values);

                TransactionReceipt receipt = null;
                while (receipt == null)
                {
                    if (receiptRequestCancellationToken != null &&
                        receiptRequestCancellationToken.IsCancellationRequested)
                    {
                        return null;
                    }

                    await Task.Delay(TimeSpan.FromMilliseconds(100));
                    try
                    {
                        receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txHash);
                    }
                    catch (Exception ex)
                    {
                        if (ex.Message == "unknown transaction")
                            continue;
                        else
                        {
                            throw ex;
                        }
                    }
                }
                return receipt;
            }
            catch (Exception ex)
            {
                return null;
            }
        }
```
the same thing happens with functions, so I just created another extension method for functions with SendTransactionAsync instead of SendRequestAsync

but this solution is kinda dirty.

**Comment by bradamelton** [comment]
There is now an issue opened on the geth repo, 16092. I would recommend waiting until they decide what to do. I can update here if i see an update. (I also have a change ready as well for a neth update if they choose to keep the new exception. I do t think they will though.)

**Comment by juanfranblanco** [comment]
Thanks, yes it is rather silly.

**Comment by knocte** [comment]
>   if (ex.Message == "unknown transaction")

This is a very fragile and smelly way to do error handling. In theory geth should bubble error codes so that Nethereum could convert them to properly-typed exceptions. If it doesn't, we should open an issue in the geth repo.

**Comment by bradamelton** [comment]
There is a geth issue open for it now, as it shouldn't be an error. Perhaps a better way, if it must be handled would be to detect the error inside of xxClientBase.HandleRPCError and detect the error code in the deserialized RpcResponseMessage.Error and ignore it. (Which is -32000)

**Comment by juanfranblanco** [comment]
Referencing it https://github.com/ethereum/go-ethereum/issues/16092

**Comment by juanfranblanco** [comment]
The error code is not standard, so it will break integrations with Parity or any future clients, so it could get very messy in the future if everyone decided to create their own error codes, handling.

**Comment by karalabe** [comment]
Sorry about this, it was an accidental regression. Opened https://github.com/ethereum/go-ethereum/pull/16217 to fix it.

**Comment by juanfranblanco** [comment]
@karalabe no need to apologise :), we should all be grateful for all your work.

**Comment by bradamelton** [comment]
I have verified that this looks good to me now, for Nethereum.Contracts.SendRequestAndWaitForReceiptAsync.

**Comment by juanfranblanco** [comment]
Yes, me too, Ill close this now.
