### ISSUE TITLE
LoadFromKeyStore gets error 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'

### ISSUE THREAD

**Issue by maxcap888** [Nethereum/Nethereum#263]
when I create an instance of Web3 using the account object, I get the error:

> FileNotFoundException: Could not load file or assembly 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'. The system cannot find the file specified.

However, when I create an instance using my localhost works fine.

This works:
`Nethereum.Web3.Web3 web3 = new Web3("http://localhost:8545");`

This generates the error above:
`var account = Nethereum.Web3.Accounts.Account.LoadFromKeyStore(keyStoreEncryptedJson, password);
 Nethereum.Web3.Web3 web3 = new Nethereum.Web3.Web3(account, "https://rinkeby.infura.io/XXXXXXXXXX");`

`keyStoreEncryptedJson` is the JSON from my keystore file

 I already verified that I have the Portable.BouncyCastle version: 1.8.1.4 NuGet package installed

**Comment by maxcap888** [comment]
I didn't get any reply to this ticket yet. Anyway I was able to make it work by removing the NuGet package Portable.BouncyCastle v 1.8.1.4 reference from my project.
I guess this package is already included in the Nethereum package with a different version??

**Comment by juanfranblanco** [comment]
Yes, there is a reference already in Nethereum to Bouncy castle.  Check the dependencies. https://www.nuget.org/packages/Nethereum.Signer/

**Comment by juanfranblanco** [comment]
https://www.nuget.org/packages/Nethereum.Util/

You can also check expanding the dependencies in the solution explorer.

Obviously there is a breaking change somewhere.
