### ISSUE TITLE
Fix HexType.HexValue error

### ISSUE THREAD

**Issue by jun496** [Nethereum/Nethereum#265]
I love this Nethereum project! 
Thank you for your great effort!

I found a bug and report it.

-------------------------------------------------------------

Fix HexType.HexValue error: hexValue -> value
Add UnitTest for HexBigInteger: HexBigIntegerTests

-------------------------------------------------------------
public string HexValue
        {
            get { return hexValue; }
            - set { InitialiseFromHex(hexValue); } // Bug
            + set { InitialiseFromHex(value); }
        }

-------------------------------------------------------------

using Nethereum.Hex.HexTypes;
using System;
using Xunit;

namespace Nethereum.Hex.Tests
{
    public class HexBigIntergerTests
    {
        [Fact]
        public void HexBigIntergerTest()
        {
            HexBigInteger TestValue = new HexBigInteger("0x100");

            Assert.Equal(TestValue.HexValue, "0x100");
            Assert.Equal(TestValue.Value, 256);

            TestValue.Value = 1024;
            Assert.Equal(TestValue.Value, 1024);        // It works perfectly!   

            TestValue.HexValue = "0x200";            // It doesn't work now!
            Assert.Equal(TestValue.HexValue, "0x200");
        }
    }
}

**Comment by juanfranblanco** [comment]
@jun496 I forgot to mention, many thanks for this. Ill push the fix soon.
