### ISSUE TITLE
Send Call Input of Contract to Another Contract as Bytes

### ISSUE THREAD

**Issue by EmreJoint** [Nethereum/Nethereum#267]
Hello, 

I have a contract that has "bytes" parameter. this parameter is used for contract to call 2nd contract with this parameter. this parameter includes 2nd contract's function signature and parameter values. I can create  call input of 2nd contract via Nethereum. The string call input data is : _**0x4253d5ce0000000000000000000000007d919eeeb9935811fbba476109610d2469d820d5**_

![image](https://user-images.githubusercontent.com/35023250/36777385-5dc11186-1c7a-11e8-850d-b42ad315c130.png)

When i call my contract via Ethereum wallet(mist), i can paste this string value for bytes paramater of my contract function  and finally 2nd contracts function is executed. Here is the transaction details of successful execution;

![image](https://user-images.githubusercontent.com/35023250/36777525-daec4752-1c7a-11e8-8feb-5e818e256bc5.png)

But when i want call my function via nethereum, i wasnt able to send this string value, because it says it needs bytes value for execute parameter(ABI definition is bytes). When i encode this string value into bytes via nethereum and send it to my contract, it was not the same value with the previous transaction.

![image](https://user-images.githubusercontent.com/35023250/36777624-3cbe51dc-1c7b-11e8-8ff7-102bc662e987.png)

![image](https://user-images.githubusercontent.com/35023250/36777733-b236389e-1c7b-11e8-9f8e-6d7768bc0ef1.png)

How can i send this parameter as in the first one via Nethereum, thank you.

**Comment by juanfranblanco** [comment]
@EmreJoint 
The string you are passing is not a "string" it is a hex byte array. What you need to do is using the hex string, use the extension method to convert it to a byte array.  "xxx".HexToByteArray();
You will get this extension if you add the namespace "Nethereum.Hex.HexConvertors.Extensions".

**Comment by EmreJoint** [comment]
@juanfranblanco Thank you, that solved my problem.
