### ISSUE TITLE
Truffle migrate issue: Gas price not 0

### ISSUE THREAD

**Issue by yifon** [Nethereum/Nethereum#270]
I install quorum, and run the geth node successfully. And the balance of every account is 0, two issues I hit.

1. If I run "miner.start()", then the geth will be terminated abnormally.
2.If the eth account's balance is 0, then I want to deploy the smart contract, then when running 'truffle migrate', I will hit the 'Gas price not 0' error.

**Comment by juanfranblanco** [comment]
Hi @yifon, I think is best if you direct your question to the truffle team instead. Happy to help if you need more support on this.

**Comment by yifon** [comment]
Thanks @juanfranblanco I fixed this problem, but I here below issue.
I want to setup my applications on the ECS cloud server, the OS configuration is "CPU: 1 Core(s)    Memory:　 2 GB (I/O Optimized) 1Mbps", after I run 'miner.start()' to mine the block, the CPU will jump to 99%, and the geth will be terminated due to the 'out of memory' error.
Does it means such OS configuration is unable to mine the block?
