### ISSUE TITLE
Does TransactionSigner.SignTransaction() work with ETC?

### ISSUE THREAD

**Issue by Affinity121** [Nethereum/Nethereum#274]
I am trying to offline sign a transaction (without installed geth) and send it to the network through https://etcchain.com/gethProxy/eth_sendRawTransaction?hex=$hex API.

> string txHex =
> 	new TransactionSigner().
> 	SignTransaction(
> 		"0x3665be736157772926e0d5517c19325879a59551008a2a33384cf57a50c5acd7",
> 		"0xd30c15fe82feea29325702f72c0e999d7471587e",
> 		BigInteger.Parse("986394320000000000"),
> 		BigInteger.Parse("0"),
> 		BigInteger.Parse("60000000000"),
> 		BigInteger.Parse("21000"));

etcchain.com API gives 500 HTTP error for my transaction. When I generate a transaction with the same parameters using https://ethereumproject.github.io/etherwallet/#send-transaction — it creates different hex string, and API works okay. Am I missed something?

**Comment by juanfranblanco** [comment]
What Nonce are you using? is that 0?

**Comment by Affinity121** [comment]
Yes, "0". I send from "0x5B2aF9D13615F58D6684f882B4F8C2c960ec2529". You can try yourself to send part of coins or all of them, it is for testing purposes.

**Comment by juanfranblanco** [comment]
The nonce cannot be 0. The nonce is the counter of transactions you have created, so the next nonce will be your transaction count for that particular address.

**Comment by juanfranblanco** [comment]
Example https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer.IntegrationTests/TransactionSigningTests.cs#L19

**Comment by Affinity121** [comment]
I tried 0 and 1. As I understand, first nonce must be 0, because we have zero outgoing transactions. I tried to create raw transaction with the same parameters on https://ethereumproject.github.io/etherwallet/#offline-transaction page.

From Address: "0x5B2aF9D13615F58D6684f882B4F8C2c960ec2529"
To Address: "0xd30c15fe82feea29325702f72c0e999d7471587e"
Value / Amount to Send: 0.98639432
Gas Limit: 21000
Gas Price: 60000000000
Nonce: 0
Paste/Type Your Private Key: 0x3665be736157772926e0d5517c19325879a59551008a2a33384cf57a50c5acd7

Signed transaction field is not the same as after  TransactionSigner.SignTransaction(). I didn't try to click 'Send Transcation' there, but I believe it will go okay.

**Comment by juanfranblanco** [comment]
You have already 2 transactions, the explorer. So the next one will be 1.

**Comment by Affinity121** [comment]
http://gastracker.io/addr/0x5b2af9d13615f58d6684f882b4f8c2c960ec2529
http://etcchain.com/addr/0x5b2af9d13615f58d6684f882b4f8c2c960ec2529
I see only 1 incoming transaction.

**Comment by Affinity121** [comment]
I found what was the reason of the problem. Your library is awesome. I promise I will do a donation once my project start to generate income, just don't forget to leave a donation address somewhere. :)
