### ISSUE TITLE
Get transactions information or transactions count by address

### ISSUE THREAD

**Issue by PainMustDie** [Nethereum/Nethereum#275]
How get  all transactions informations or transactions count by address?

**Comment by wangwwww** [comment]
http://api.etherscan.io/api?module=account&action=txlist&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a&startblock=0&endblock=99999999&sort=asc&apikey=YourApiKeyToken  
你可以使用这个接口

**Comment by juanfranblanco** [comment]
Yes you can use etherscan ^^^ if you don't want to "scan it" manually :)

**Comment by zeshanvirk** [comment]
how we can get list of transactions with transaction information for an address using Nethereum lib?

**Comment by juanfranblanco** [comment]
On the manual side you will need to iterate the chain using something like the BlokchainStorage
