### ISSUE TITLE
Unable to verify message sign with Trezor

### ISSUE THREAD

**Issue by hhs18** [Nethereum/Nethereum#278]
Unable to verify message sign with Trezor, message sign with myetherwallet.com version 3

**Comment by juanfranblanco** [comment]
I need an example of the signature, message, etc.

**Comment by wchuan11** [comment]
Example of the signature message:
{
 "address": "0x0dcfcc9c06f5cf4e3f0e22eaae49b2d93bd5adf5",
 "msg": "this is message sign with Trezor, 11-Mar-2018 08:58",
 "sig": "0x6f7ac0bd83c951eb5730810ed0177e3d1e94fb792ba38c6765c95f53d2e2c8867891b05772b6b1c573c0aca1765d74f7fc9955c1ac449654eb75c57de7d48c121b",
 "version": "3",
 "signer": "trezor"
}

**Comment by juanfranblanco** [comment]
@wchuan11  yes I have that one, but I cannot corroborate it so I would need another one.

**Comment by wchuan11** [comment]
@juanfranblanco Do you mean you need a different signature message to confirm the issue?

**Comment by juanfranblanco** [comment]
Yes, I don't have a device to test it myself. Hence I am asking, just to verify the differences. Last resort will be to ask for a device for testing.

**Comment by wchuan11** [comment]
@juanfranblanco Guess so. Another example:
{
 "address": "0x313d0a2a13627157966c8923d992f0f91fea99dc",
 "msg": "test",
 "sig": "0x21e14d6cfe78f04775a51be12607db47f82f506c9ee487fd744fad09eb1a3d4933748030a6d0ebb557a13a1536367e6b816e4f0784d3206b9bdf6f0c6743f6be1b",
 "version": "3",
 "signer": "trezor"
}

**Comment by juanfranblanco** [comment]
https://github.com/ethereum/go-ethereum/issues/14794

**Comment by juanfranblanco** [comment]
Trezor is fixed now, also supported in hardware wallets.
