### ISSUE TITLE
How to get the list of pending transactions (haven't mined to a block yet)

### ISSUE THREAD

**Issue by protocollapse** [Nethereum/Nethereum#279]
Currently I'm using GetBlockWithTransactionsByNumber by looping into the latest 200 blocks to get the transactions sent to my address. I can actually get my transaction through the block number but what about the pending transaction which has no block number yet (haven't mined to a block). 

![image](https://user-images.githubusercontent.com/32349077/37275750-01c94060-261b-11e8-8cf9-298e4212e5a5.png)

**Comment by juanfranblanco** [comment]
check https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter

**Comment by protocollapse** [comment]
Thank you for the reply. I'm not sure though if this is the correct usage.

`Web3 web3 = new Web3();
            Task<HexBigInteger> pendingFilter = Task.Run<HexBigInteger>(async () => await web3.Eth.Filters.NewPendingTransactionFilter.SendRequestAsync());
            Task<FilterLog[]> filterChanges = Task.Run<FilterLog[]>(async () => await web3.Eth.Filters.GetFilterChangesForEthNewFilter.SendRequestAsync(pendingFilter.Result));`

I'm gettlng Status = WaitingForActivation. 
BTW, do you have sample code on how to use pending transaction filters.

**Comment by juanfranblanco** [comment]
Web3 web3 = new Web3();

var pendingFilter = await web3.Eth.Filters.NewPendingTransactionFilter.SendRequestAsync();

var filterChanges = await web3.Eth.Filters.GetFilterChangesForEthNewFilter.SendRequestAsync(pendingFilter);

This will look better, but also notice that you are going to check for changes.

**Comment by protocollapse** [comment]
Thanks for the reply.

I created a simple function to test the FilterLogs returned by GetFilterChangesForEthNewFilter but it seems NewPendingTransactionFilter is not returning at all. I'm trying to query in the mainnet using infura.

**Comment by XmissterioX** [comment]
this is not working for me too

**Comment by Gh0stR0ck** [comment]
I'm trying this to get the pending transactions this way, but i get a 405 code back (methode not allowed.) Does anyone knows why and how to fix this?

**Comment by juanfranblanco** [comment]
@Gh0stR0ck  That is due to infura not allowing filters.

**Comment by juanfranblanco** [comment]
Here is a sample for Pending Transactions if you need it:

```csharp
public class PendingTransactionsSample
    {
        public static string PrivateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
        public static string Address = "0x12890d2cce102216644c59daE5baed380d84830c";

        public async Task RunAsync()
        {
            var web3 = new Web3Geth(new Account(PrivateKey), "http://localhost:8545");

            await web3.Miner.Stop.SendRequestAsync();

            var pendingFilter = await web3.Eth.Filters.NewPendingTransactionFilter.SendRequestAsync();
            

            var deploymentHandler = web3.Eth.GetContractDeploymentHandler<ArrayUint256DynamicDeployment>();
            var txn1 = await deploymentHandler.SendRequestAsync();
            var txn2 = await deploymentHandler.SendRequestAsync();
            var txn3 = await deploymentHandler.SendRequestAsync();

            var filterChanges = await web3.Eth.Filters.GetFilterChangesForBlockOrTransaction.SendRequestAsync(pendingFilter);
        }
    }
```
https://github.com/Nethereum/Nethereum.Issues/blob/master/Net.Issues.Console/PendingTransactionsSample/PendingTransactionsSample.cs

**Comment by SimonOrdo** [comment]
> ```cs
> deploymentHandler
> ```

What's the deploymentHandler stuff doing there?  And why is there 3 of them?
