### ISSUE TITLE
Is there any document to describe the installation on windows?

### ISSUE THREAD

**Issue by fredzhu** [Nethereum/Nethereum#282]
I'm using VS 2015, after download the source files and load the .sln file, there are lots of unavailable projects in it.
Run this "PM > Install-Package Nethereum.Portable"  in  Nuget Package Manger but still many errors.

Do I need VS 2017 ?  Is there any other SDK I need to install?

Is there any document to describe the installation on windows?

Thanks a lot.

**Comment by juanfranblanco** [comment]
hi @fredzhu, currently all the development is done in VS 2017, but you should not have any issue installing in Vs2015 the portable version like any other package from nuget. 

Mainly create the project you are targetting, ie.. .Net class library targetting .Net451, and add the nuget package by right clicking on the project menu.

If you can paste the issues / errors you are having I might be able to clarify anything.

**Comment by fredzhu** [comment]
Thanks a lot. Yes, create a new project and Install-Package Nethereum.Portable works.
Actually I saw the error message because I Clone and download all files and open the .sln file to build, but mine is VS2015.  I'll install VS2017 for it.

**Comment by juanfranblanco** [comment]
great :).
