### ISSUE TITLE
Need a full example of how to do Offline-signature on a Multisig wallet

### ISSUE THREAD

**Issue by wsq003** [Nethereum/Nethereum#283]
Need a full example of how to do Offline-signature on a Multisig wallet.

I have succeeded to do Offline-signature on normal address, but I did not find any example or document on how to do Offline-signature on a Multisig wallet.

Please help!

**Comment by wsq003** [comment]
As far as I know, ETH do not support Offline-signature on a Multisig wallet. Am I wrong?

Can this be a feature request ?

**Comment by juanfranblanco** [comment]
This is on the roadmap for the "wallet" front-end support. But of course, it will work for the backend too.

**Comment by juanfranblanco** [comment]
Re-reading this there is a confusion on my part on multi signature requirements as this is not based on smart contract multi signature requests.
