### ISSUE TITLE
Problem unlockaccount on Rinkeby via infura

### ISSUE THREAD

**Issue by allenzhang83** [Nethereum/Nethereum#286]
I got "405 Method Not Allowed" error when I tried to unlock an account I created on MetaMask.
Here is the code:

string privateKey = "0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
string senderAddress = "0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

var account = new Account(privateKey);
var web3 = new Web3(account, "https://rinkeby.infura.io/cu9QSOeCCcK1lbKZrPey");

var password = "xxxxxxx";  // where does this come from? the meta mask password???

// error on the line below
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(120));

What have I done wrong? Where does 'password' come from?

**Comment by juanfranblanco** [comment]
This method only works if you connect to your own local client. Infura does not have and should not have your keystore files with the private keys.

If you have your private key already (you have it). You use that to sign the transactions no need to unlock accounts.

Remove:

```
var password = "xxxxxxx"; // where does this come from? the meta mask password???

// error on the line below
var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(120));
```

and you are good to go.

**Comment by allenzhang83** [comment]
Thanks a lot! I just realised that, too.
Now I'm getting "intrinsic gas too low" error, but I guess I just need to increase gas.

**Comment by juanfranblanco** [comment]
Yes, if you are calling a function you can use EstimateAsync to calculate the gas, if deploying a contract most of the times the estimation is not correct yet.
