### ISSUE TITLE
Nethereum.KeyStore.KeyStoreService.DecryptKeyStoreFromJson seems too slow on Unity Editor

### ISSUE THREAD

**Issue by umegaya** [Nethereum/Nethereum#288]
hi, thank you for creating Nethereum, its quite useful for our purpose.
but we have a problem with key recovery from keystore, just because it takes too long time. 

we do key encyption/decryption roughly as following. 
- key creation and encrypting as keystore
  ```
  var key = Nethereum.Signer.EthECKey.GenerateKey();
  var service = new Nethereum.KeyStore.KeyStoreService();
  var keyStore = service.EncryptAndGenerateDefaultKeyStoreAsJson(
				password, key.GetPrivateKeyAsBytes(), key.GetPublicAddress());
  ```
- key recovery from keystore to create EthECKey
  ```
  var service = new Nethereum.KeyStore.KeyStoreService();
  key = new Nethereum.Signer.EthECKey(
			service.DecryptKeyStoreFromJson(password, keyStore), 
			true);
  ```

key encyption also seems to take long time, but I think its ok because typically this is only done 1st time. 

problem is key recovery from keystore (always needed when app launches) takes more than 10 seconds at UnityEditor on my machine (macbook pro late 2015, 16GB ram and 2.6 GHz Intel Core i7, High Sierra), which will harm UX a lot.

if I just store ```key.GetPrivateKey()``` and do ```new Nethereum.Signer.EthECKey(privateKey)```, key recovery finished immediately, so I guess this caused by slow decryption speed. 

so question is:

1. this (>10 seconds) is normal decryption speed for my environment? 
2. if 1. is correct, any suggestion to speed up? (maybe a few seconds is limit)
3. if 1. is not correct, any idea about what I am missing? 

regards,

**Comment by garyng2000** [comment]
yes, the keystore thing is VERY VERY SLOW and I am only looking at decryption. I briefly read the code and can't find a reason for it. I am running this as plain C#(in ASP.NET or just console program)

**Comment by garyng2000** [comment]
ah, it seems that even though it is even though it is decrypt, it still need to call SCrypt.GenerateDerivedKey or something which is probably where the time is spent(some repeated hashing which is designed to be slow).

**Comment by garyng2000** [comment]
some form of caching seems to be needed as it seems since it is indeed by design to make the 'create private key/seed' to be slow as it really is just a hash and have to designed to prevent/delay brute force attack. Is there a way to 'securely cache' a .NET object ?

**Comment by juanfranblanco** [comment]
Yes it is very slow by design, but it should not be very slow on a normal pc. Regarding the storage / caching, depends on your scenario and your architecture. For example in Azure you could use a combination of KeyVault and a Secured service with AAD. On windows uwp the secure storage.

**Comment by garyng2000** [comment]
I am using it in the context of ASP.NET so it becomes slow from usage perspective a few seconds each time and that depends on load(unlike a desktop where it is a single user and can be cached in a safer way). But I have found a way to reasonable cache it with some safety measure as all that is needed are the private/public key for this process, generally speaking.

**Comment by juanfranblanco** [comment]
Well, if you are going to load it per each request it is going to be slow.

**Comment by eladleb** [comment]
Yes, I also saw it's very very slow, I didn't quite understand why should this be a different process than unlocking an account in Geth or Metamask? When I do that on the same machine it takes < 1 sec.

**Comment by juanfranblanco** [comment]
The process is the same as in Geth, and performance wise for golang and .net in this area (in my quick random tests) it is the same. In Javascript is far much slower, if you load a key file in metamask you will notice the difference.

**Comment by juanfranblanco** [comment]
Metamask stores the decrypted private key in its internal encrypted storage, so once you load it is retrieved from there, so it is much faster.

**Comment by juanfranblanco** [comment]
Another thought, if you try to use this in WebGL (like in Unity3d) and I assume wasm (but I have not had time to test this yet) it will be as slow as Javascript.

**Comment by juanfranblanco** [comment]
@umegaya In the UnityEditor on Windows it performs at a par, have you compiled your game / scene?

**Comment by eladleb** [comment]
It's funny, on the UnityEditor it takes me about 18 seconds to run either:
`
				Nethereum.KeyStore.KeyStoreService keystoreservice =  new Nethereum.KeyStore.KeyStoreService();
				Nethereum.Signer.EthECKey key = new Nethereum.Signer.EthECKey(keystoreservice.DecryptKeyStoreFromJson(password, json),true);

				this.userAddress = key.GetPublicAddress();
				this.privateKey = key.GetPrivateKey();
`
Or
`			Nethereum.Signer.EthECKey ecKey = new Nethereum.Signer.EthECKey(importedPriveteKey);

Nethereum.KeyStore.KeyStoreService keystoreservice =  new Nethereum.KeyStore.KeyStoreService();
		string json = keystoreservice.EncryptAndGenerateDefaultKeyStoreAsJson (password, ecKey.GetPrivateKeyAsBytes(), this.userAddress);
`

But when I compile to an app it only takes 5-6 seconds.

**Comment by sweatyc** [comment]
Can I assume the solution should be:
- cache the private key in local as serialized file, after the wallet is created
- only decrypt the keystore for returning players (no cached private but providing a keystore of previous wallet), save and cache the private key after
