### ISSUE TITLE
Validate address

### ISSUE THREAD

**Issue by Alansoft-BR** [Nethereum/Nethereum#293]
Hi,
I am not able to find out if web3.utils.isAddress is implemented in Nethereum.
http://web3js.readthedocs.io/en/1.0/web3-utils.html?highlight=isValidAddress#isaddress

Was it already implemented or are there any plans to implement it?
Thank you so much for all your work.
Best,
Alan

**Comment by Alansoft-BR** [comment]
I guess I spoke too soon. Of course it's here:
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Util/AddressUtil.cs

**Comment by Alansoft-BR** [comment]
The new web3 function validates the checksum if there are uppercase chars in the address:

> "Checks if a given string is a valid Ethereum address. It will also check the checksum, if the address has upper and lowercase letters."

**Comment by juanfranblanco** [comment]
So what is the problem?

**Comment by Alansoft-BR** [comment]
No problem, just a question. I just wanted to know if this will be implemented in Nethereum. At the moment I need to check a regex (for hex), size (0x + 40chars) and checksum (if necessary). This function would do all 3.
Thank you.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Util/AddressUtil.cs#L28-L48
Does this not cover all? So mainly you are asking for a single function call correct?

**Comment by Alansoft-BR** [comment]
Yup. This is my implementation.
Could be adjusted to accept addresses with no prefix very easily.... {0,1}
```
        public static bool IsValidAddress(string address)
        {
            Regex r = new Regex("^(0x){1}[0-9a-fA-F]{40}$");
            // Doesn't match length, prefix and hex
            if (!r.IsMatch(address))
                return false;
            // It's all lowercase, so no checksum needed
            else if (address == address.ToLower())
                return true;
            // Do checksum
            else
                return new AddressUtil().IsChecksumAddress(address);
        }

```
Methods in this class could be static.

**Comment by juanfranblanco** [comment]
Address formatting, format validation is included in Utils
