### ISSUE TITLE
Frequent timeouts getting receipt, balance out of sync etc

### ISSUE THREAD

**Issue by cbp123** [Nethereum/Nethereum#294]
Hi,
I'm not sure if this a Nethereum issue or a problem with Infura, or a problem with my code. Any assistance would be appreciated.

What I'm trying to do is fairly simple: transfer money from wallet to another, confirm the transaction went through, and check the final balance.

My code is something like this:

```
var account = new Account(accountKey);

var web3 = new Web3(account, "https://mainnet.infura.io/myinfuraid")
{
    TransactionManager =
    {
        DefaultGasPrice = Web3.Convert.ToWei(0.0000001M),
        DefaultGas = 21000
     }
};

var weiToWithdraw = Web3.Convert.ToWei(amountInEth) - web3.TransactionManager.DefaultGasPrice * web3.TransactionManager.DefaultGas;

var transactionReceipt = await web3.TransactionManager
    .TransactionReceiptService
    .SendRequestAndWaitForReceiptAsync(() =>
        web3.TransactionManager.SendTransactionAsync(sourceAddress, destinationAddress,
                new HexBigInteger(weiToWithdraw))
    );

Console.WriteLine("Transaction hash: " + transactionReceipt?.TransactionHash);

var balance = await web3.Eth.GetBalance.SendRequestAsync(address);

Console.WriteLine("Eth Balance: " +  Web3.Convert.FromWei(balance));

var transaction = await web3.Eth.Transactions.GetTransactionByHash.SendRequestAsync(id);

Console.WriteLine("Confirm transaction exists: " + transaction?.TransactionHash);
```

About half the time there is no problem and the behaviour is as expected. However the other half of transactions includes problems like:

1) Frequent timeouts calling SendRequestAndWaitForReceiptAsync and retrieving the receipt, even if the transaction did in fact complete successfully.

2) Final balance is not fresh, and GetBalance returns the old balance from prior to the transaction.

3) The transaction fails to be processed and never makes it to the Blockchain.

Any assistance would be appreciated.

**Comment by juanfranblanco** [comment]
Apologies for the late response, this indicated a problem with Infura.
