### ISSUE TITLE
CallAsync wrong sender?

### ISSUE THREAD

**Issue by Che4ter** [Nethereum/Nethereum#297]
I have the following simple solidity contract with the function returnSender that should return the sender address. I have deployed the contract with mist on my test blockchain:
```
pragma solidity ^0.4.4;

contract TestContract{
    function returnSender() public view returns (address) {
        return msg.sender;
    }
}
```
And the following nethereum program:
The account has the address: 0xddac9415b7a8f8f04fe57b4c3dcbd47e5892ba43
```
var account = Nethereum.Web3.Accounts.Account.LoadFromKeyStore(@"{""address"":""ddac9415b7a8f8f04fe57b4c3dcbd47e5892ba43"",""crypto"":{""cipher"":""aes-128-ctr"",""ciphertext"":""345dc987b7a02f0fa9a4aa9e8daad196a200c443e88fbd65d7844656a0beef02"",""cipherparams"":{""iv"":""c2de35abd3630f257ef237156218161a""},""kdf"":""scrypt"",""kdfparams"":{""dklen"":32,""n"":262144,""p"":1,""r"":8,""salt"":""46b7f93a7571c6f5e7e7fc56a6161c58b43053bc1ef5787b2a90694d08a1b5bc""},""mac"":""7bb3c60a4fc3141dfe4597d1d0073da0da6b976cb3679a2437516fab1e2ebc68""},""id"":""c92d7a4d-12da-4330-b776-d75ae5b7636c"",""version"":3}", "1234");

Web3 web3Geth = new Nethereum.Web3.Web3(account, "http://127.0.0.1:8501");

var contract = web3Geth.Eth.GetContract(@"[ { ""constant"": true, ""inputs"": [], ""name"": ""returnSender"", ""outputs"": [ { ""name"": """", ""type"": ""address"", ""value"": ""0x108b08336f8890a3f5d091b1f696c67b13b19c4d"" } ], ""payable"": false, ""stateMutability"": ""view"", ""type"": ""function"" } ]", "0xeB5E437f60EB1f4D33991168A70F49cefB887fE0");


var getFunction = contract.GetFunction("returnSender");
var result = await getFunction.CallAsync<string>();

Console.WriteLine($"Sender Address: {result}");
//Sender Address: 0x108b08336f8890a3f5d091b1f696c67b13b19c4d
```
As result I receive the address of the contract creator.
Why is the result address not the same as the sender?

**Comment by garyng2000** [comment]
only transaction has msg.sender.  you are calling a constant function which should not even refer to any msg related values, it is undefined. though I don't know why the return should give you the contract address, to me this is supposed to be an error.

**Comment by juanfranblanco** [comment]
@Che4ter If you pass the FromAddress you will get as a response the sender address. 
Check this here:

https://github.com/Nethereum/Nethereum/blob/9afb625876e64ded7bc785ed1ea37fd4376aad1a/src/Nethereum.Contracts.IntegrationTests/CQS/SimpleMessage.cs#L25

**Comment by juanfranblanco** [comment]
@Che4ter  Here is another example based on your original code
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Contracts.IntegrationTests/CQS/SimpleMessage.cs#L45

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/issues/305 Adding another issue to set the default address based on the current TransactionManager.

**Comment by juanfranblanco** [comment]
@garyng2000  @Che4ter  Note that Gary's point is partially incorrect, the call is not signed but you can pass the sender Address, this is important as we can use the Msg.Sender to query the state and also important if we are going to Estimate the gas consumption.
