### ISSUE TITLE
Generate more than one address against one account

### ISSUE THREAD

**Issue by nomantariq18** [Nethereum/Nethereum#298]
Can i connect my Ethereum wallet to Hd wallet to generate more than one address against one account without using contract ?

**Comment by nomantariq18** [comment]
.

**Comment by juanfranblanco** [comment]
The HD wallet allows creating a key (which can be based on a seed of words), and use it to generate and recover private keys and addresses (accounts). There is not a direct relationship between children and parent. Hopefully, that answers your question.

**Comment by nomantariq18** [comment]
thanks.
