### ISSUE TITLE
Generate multiple address using  smart contract.

### ISSUE THREAD

**Issue by nomantariq18** [Nethereum/Nethereum#299]
I have found that i can't generate multiple address against one account. After a lot of research i have found that i can create more than one address using smart contract. i have created smart contract. but i have not found any method to generate multiple address against this contract . how can i generate multiple addresses of that contract ?

**Comment by juanfranblanco** [comment]
You cannot generate multiple addresses of a contract

**Comment by nomantariq18** [comment]
i've a problem that i want to use one account and generate multiple addresses against this account . how can a handle this this problem?or is there any other solution ?
