### ISSUE TITLE
No support for eth_compileSolidity - latest geth

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#300]
Hello,

On upgrading to latest geth, I get the following error (reverting to older geth compiles with code as is) - 

> RpcResponseException: The method eth_compileSolidity does not exist/is not available

I understand the support has been deprecated (then) and now removed (??).
https://github.com/ethereum/EIPs/issues/209 

Is there a mismatch in what I am doing?  Or am I hitting a different issue?

Thanks

**Comment by garyng2000** [comment]
do not relies on geth for compilation, I wrote separate things using solc.exe(on server) and solc npm package(on javascript)

**Comment by juanfranblanco** [comment]
Hi, @ushakrishnan how are you? Long time no speak.

Yes, it seems to be now removed from Geth, and as per the comment above the best solution is to use your custom compiler and don't rely on the client.

**Comment by ushakrishnan** [comment]
Hi Juan, Got too busy at work - had no time for tinkering and learning :-(

Yes, I had resorted to doing what @garyng2000 had done.  Too bad, I liked the all in one approach!

Thank you both!
