### ISSUE TITLE
ipc client partly failed

### ISSUE THREAD

**Issue by garyng2000** [Nethereum/Nethereum#301]
Have a very weird situation trying to use the IPC client. I can create an ipc client and use it as the web3 provider. It seems that most of the 'read' function works(say eth.blockNumber equivalent or personal.ListAccounts). But if I tried to submit a transaction or unlock an account(of geth), it always failed with some null reference. But the transaction is indeed submitted to the node and the account is unlocked(I can check with another geth attach console which use the same ipc interface).
Now if I switch the ipc client to http client(so one line change in C#), the same code(nothing else change) works as it should.

This is 2.4.0, I used the same code for the 1.x version before and it was ok. tried to interact against geth 1.7.x and 1.8.x and both still failed as long as I am using the IPC client for certain functions.

**Comment by juanfranblanco** [comment]
Are you using a ManagedAccount or an Account when connecting to Geth?

**Comment by garyng2000** [comment]
this particular code would fail(and similar sendTransaction as well):

web3.Personal.UnlockAccount.SendRequestAsync("0x11cxxxxxxxxxxxxxxxx", "123456", 10);

**Comment by juanfranblanco** [comment]
Have tried using a ManagedAccount instead of unlocking?

**Comment by garyng2000** [comment]
oh, it is not how to manage the account that concerns me(I can find alternative there) but that why some calls work and some don't ? As mentioned, even sendTransaction have this problem. I am wondering if it has anything to do with the time taken(as all these are basically done on the geth node which in this case is running on the same machine which is just a VM), i.e. some form of timeout before data has arrived at the pipe ?

**Comment by ceciliato310** [comment]
based on the code ManagedAccount is just a form of 'signing' on the client side I assume(i.e. sendRawTransaction after signing) ? Yes, that seems to work. But now I have another issue. I tried mimic that but for some odd reason, getTransactionCount always give me one even though when I use the geth console(i.e. javascript) it gives me 3(which is correct). Have I used the call wrong(zz is the ListAccount result array) ?

var nonce = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(zz[0]);

**Comment by juanfranblanco** [comment]
@ceciliato310 are you @garyng2000 ? I am confused. Are you referring to this issue on IPC?

With a ManagedAccount you use personal_sendTransaction instead of sendRawTransaction, please read a bit here on Accounts http://nethereum.readthedocs.io/en/latest/accounts/.

Are you positive that zz[0] is the same account? Have those transactions been mined? Are you including the BlockParameter.Pending for that?

**Comment by garyng2000** [comment]
ah, borrowing machine, sorry.
further testing does seem to show that sending via ipc can be iffy even using the ManagedAcount, sometimes I get the same ipc error.
As for the GetTransactionCount, yes I am positive it is the same account. Again if I use the NonceService path, I get the right value.
