### ISSUE TITLE
Managed Account not Unlocking for Quorum

### ISSUE THREAD

**Issue by BlueCoder77** [Nethereum/Nethereum#303]
I have setup the same Quorum 7 node example network as in the tutorial in the quorum git hub. Here I have a project that uses 2 created accounts to try and deploy a simple contract that only has a kill function. When I try to deploy the contract I get the "authentication needed: password or unlock" exception. If I try to unlock the account through Nethereum then I get "invalid argument 2: json: cannot unmarshal string into Go value of type uint64" as an exception. I have manually gone into the RPC console for the node and unlocked the account inside the RPC console to move past this. Then I run into the error in the other issue I submitted [here](https://github.com/Nethereum/Nethereum/issues/302). 

I have uploaded a test solution similar to the other issue, but with minor differences to produce this issue.
[Quorom-Nethereum-Tests.zip](https://github.com/Nethereum/Nethereum/files/1871471/Quorom-Nethereum-Tests.zip)

**Comment by juanfranblanco** [comment]
You need to use a uint value instead of a hex value to unlock the account. Geth in latest versions only accepts that. Thanks for uploading your solution but it is easier to see the issue if you post the code.

**Comment by BlueCoder77** [comment]
Okay, thank you I will remember that. Sorry for the late reply, but this is my weekend project. I really appreciate all the work you do 👍
