### ISSUE TITLE
Solution do not build

### ISSUE THREAD

**Issue by adamskrodzki** [Nethereum/Nethereum#304]
Hello,

I've performed
git clone https://github.com/Nethereum/Nethereum.git
And then
Rebuild All in visual studio 2017

Buid fails
disabling projects:
Nethereum.Generator.Console
Nethereum.Generator.Console.Test
Nethereum.Unity
Nethereum.Generators.UnitTests

fixes the problem

**Comment by juanfranblanco** [comment]
Yes we are working on the Generators projects, and you need to install Unity3d to build Unity projects.

**Comment by adamskrodzki** [comment]
I've needed debug build to find out what is happening under the surface (message signing) 
The only method I know to debug into Nethereum dll's is to do Debug Build of them and as far as i know it is impossible to do throught nugets, or is?

**Comment by juanfranblanco** [comment]
I can step into compiled dlls no problem, but I use Resharper, so I don't know if it is Out of the box or not.

**Comment by juanfranblanco** [comment]
Another idea will be to get the code from the latest release.
