### ISSUE TITLE
Is it possible to DecodeDTOTypeOutput a multi-dimensional array?

### ISSUE THREAD

**Issue by eladleb** [Nethereum/Nethereum#306]
I'm trying to decode a function that returns:
```
"outputs": [
        {
          "name": "",
          "type": "uint8[25][25]"
        }
      ],

```
I noticed that the code generator skipped it, and when I tried decoding with this manually written class:

```
[FunctionOutput]
public class Output 
{

    [Parameter("uint8[25][25]", "", 1)]
    public int[][] multiArray {get; set;}
}
```

I get "Method not found: 'Default constructor not found...ctor() of System.Int32[][]'."

**Comment by juanfranblanco** [comment]
Reopened to fix the new code generator to not output List<BigInteger> but List<List<BigInteger>

**Comment by eladleb** [comment]
List<List<int>> works great, thanks for the support!
