### ISSUE TITLE
ERC20 base Token

### ISSUE THREAD

**Issue by nomantariq18** [Nethereum/Nethereum#309]
can i send other coins which is ERC20 based, on Ethereum address ?

**Comment by juanfranblanco** [comment]
Yes use this library https://www.nuget.org/packages/Nethereum.StandardTokenEIP20/
or an example of doing it directly from your custom contract https://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstard-smartcontrats/
or check https://github.com/Nethereum/Nethereum.SimpleWindowsWallet
