### ISSUE TITLE
different behaviour when using sign then sendrawtransaction vs managedAccount for contract with constructor parameters

### ISSUE THREAD

**Issue by garyng2000** [Nethereum/Nethereum#310]
something weird which I don't know how to explain. I use the following code where constructorParams is just object[]

 var contractBuilder = new Nethereum.Contracts.DeployContractTransactionBuilder();
 var contractCreationData = contractBuilder.GetData(code,abiJson,constructorParams);

then send this (basically the optional data field of a transaction) via the sign then sendRawTransaction as well as using managed account(i.e. signed by geth). In both case, the contract is created successfully but in the case of using sendRawTransaction, it is as if the contract is shifted some how(i.e. simple function call to retrieve constant value would return null) 

But if I give null as the constructorParams(i.e. it expect 3 parameters but not given any), the contract behave correctly subsequently in either method. 

I am puzzled why. In a sense, if I sign the transaction of a contract creation(with constructor parameters), the code created is not right.

I don't know if this is a geth issue(1.83-stable windows 64 bit running private network) or it is a RPC issue.

**Comment by juanfranblanco** [comment]
Hi again, can you explain what you are trying to achieve?

**Comment by garyng2000** [comment]
Hi,
This is related to the ipc client(or basically security related). In order to make use of the geth managed account, I have to either unlock certain address(forever or before I submit a transaction) but that is not very safe. I tried to use the managedAccount route(which if I am not mistaken is just doing the unlock/sign by geth on each transaction). But I found this to be really iffy(I still think it is related to the namepipe as I faintly remember namepipe sometimes need multiple read to get the full return, unlike the http way which is in a sense atomic and why I never encounter this). But I cannot open up the 'personal' channel for http(rpc). So I end up have to do the signing in the C# layer then sent the raw transaction.
Anywway, I found out why it is not running which is because at the time of signing, I have to get the estimate gas(which becomes the gas limit as part of the signing). But since I am doing multiple transactions repeatedly, all the estimates are the same but in actual execution, the state change thus the gas requirement changed and why some transactions failed(forget to check the status in the receipt). Problem solved. thanks.

**Comment by juanfranblanco** [comment]
Thanks Gary for this, and very good pointer to anyone that "But since I am doing multiple transactions repeatedly, all the estimates are the same but in actual execution, the state change thus the gas requirement changed and why some transactions failed(forget to check the status in the receipt)."
