### ISSUE TITLE
Find a Bug

### ISSUE THREAD

**Issue by hxhHpx** [Nethereum/Nethereum#314]
HexTypeJsonConverter.cs  Line 17
 return HexTypeFactory.CreateFromHex<TValue>(**(string) reader.Value**);
mast by 
 return HexTypeFactory.CreateFromHex<TValue>(**reader.Value.ToString()**);
when I run the demo test.sol in vs 2017 ,and the testchain is TestRPC.

**Comment by juanfranblanco** [comment]
Is that due to the TransactionReceipt?

**Comment by hxhHpx** [comment]
Yes,You are right. I use TranscationReceipt Func .But I can not update the TestRpc to the last version ,becouse my internet is so pool.
