### ISSUE TITLE
Update BouncyCastle to newest version

### ISSUE THREAD

**Issue by Niach** [Nethereum/Nethereum#318]
Hey, can you please update to the newest BouncyCastle version? I'm using the Ipfs.Engine nuget package, which requires the newest one and i can't resolve the different versions. 
I'm using Netstandard 2.0 Xamarin Forms

**Comment by juanfranblanco** [comment]
This will need some regression testing https://github.com/Nethereum/Nethereum/issues/330. I don't know if it might help you https://github.com/TrekDev/net-ipfs-api that library is rather good.
