### ISSUE TITLE
How to get a contract's transaction history?

### ISSUE THREAD

**Issue by BlueCoder77** [Nethereum/Nethereum#323]
I am trying to get the history of a given contract. I have searched online how to do this in ethereum in general and I have found something called filters in web3.eth.filter that can filter the transactions I am guessing? When I call...

`var result = await web3.Eth.Filters.NewFilter.SendRequestAsync(new NewFilterInput() { Address = new string[] { address }, FromBlock = new BlockParameter(1), ToBlock = BlockParameter.CreateLatest() });`

I just get back a BigHexInteger class. What do I do with this? How can I get a set of transactions with the name of the method, the from account, the parameters, and the block time?

**Comment by garyng2000** [comment]
technically, you cannot. You cannot filter transaction, only events. What I have done is to make sure all transaction emit an event then you can get all the events since contract creation and parse them which should give you the transaction information.

**Comment by juanfranblanco** [comment]
@garyng2000  is slightly incorrect, @BlueCoder77  you can create a filter as you have created for a block range with the contract address. That contains all the transaction information required. From the data, if you have the abi you can get the information required. 

Now to @garyng2000 point, the events are better as they give you information about the state you want after the event not before.

**Comment by BlueCoder77** [comment]
@juanfranblanco  how would I do that that then?

**Comment by garyng2000** [comment]
@juanfranblanco 
do you mean you just take from block x to block x + 100 to first get all the transactions info then scan those ?

**Comment by juanfranblanco** [comment]
Yes, I meant that :).
