### ISSUE TITLE
support "0xffff" form string as input for bytes

### ISSUE THREAD

**Issue by garyng2000** [Nethereum/Nethereum#325]
for address type, a hex string representation is supposed which internally converted back to BigNumber via parsing. it would be nice if the same can be done to bytes input type.

**Comment by juanfranblanco** [comment]
bytes32 if  a string is by convention a utf-8 string so the user will need to decide what type of string. You can use the extensions of HexToByteArray for this.

**Comment by juanfranblanco** [comment]
Any other byte array passed as a string could be also a utf8 string, but this is not handled by automated decoding. The end user should know what they are dealing with and avoid magic.

**Comment by garyng2000** [comment]
oh, I am thinking along the line of really byte array but supplied as hex string representation. This again is more from an inter-system perspective. We see this for the 'data' element of a transaction/call say when I am deploying a contract that byte array is presented as hex string. This can be say pasted into MyEtherwallet. yes, the developer can do this at the front end/middle tier that make use of Nethereum but I think this is a case where it can be handled at the call level. Anyway, just a wish list item, I can wrap around the existing calls.

**Comment by juanfranblanco** [comment]
Yeah it will be confusing if some areas like bytes32 does a  Utf8 string and others don't. Etherwallet allows the user to select the type, when we a simple front end like that, that will be the strategy. Similar to etherscan decoding.
