### ISSUE TITLE
Nethereum exception: “Required property 'code' not found in JSON.”

### ISSUE THREAD

**Issue by theonemule** [Nethereum/Nethereum#328]
I'm trying to call a contract with Nethereum. I know the contract works because I am able to call it with Web3.JS. However whenever I try to call it with Nethereum, I pass in the following paramenters.

```
        conn = new Web3(url);
        contract = conn.Eth.GetContract(abi, address);
        Function castVote = contract.GetFunction("castVote");
        var result = await castVote.SendTransactionAsync(account, null, null, account, candidate);
```
I get the following exception without much of an explanation...

`Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> Newtonsoft.Json.JsonSerializationException: Required property 'code' not found in JSON. Path 'error', line 1, position 6776.`

What would cause this? I can't find anything online.

**Comment by juanfranblanco** [comment]
Hi,

Did you solve this? Can you post your ABI? An option will be to try using the code generator in vscode solidity.

**Comment by theonemule** [comment]
I did not solve it, but here's my ABI.

````
[
{
"constant":true,
"inputs":[
{
"name":"",
"type":"address"
}
],
"name":"voted",
"outputs":[
{
"name":"",
"type":"bool"
}
],
"payable":false,
"stateMutability":"view",
"type":"function"
},
{
"anonymous":false,
"inputs":[
{
"indexed":false,
"name":"eventID",
"type":"uint256"
},
{
"indexed":false,
"name":"message",
"type":"string"
}
],
"name":"voteEvent",
"type":"event"
},
{
"constant":false,
"inputs":[
{
"name":"voter",
"type":"address"
},
{
"name":"candidate",
"type":"uint256"
}
],
"name":"castVote",
"outputs":{
},
"payable":false,
"stateMutability":"nonpayable",
"type":"function"
},
{
"constant":true,
"inputs":[
{
"name":"entityAddress",
"type":"address"
}
],
"name":"hasVoted",
"outputs":[
{
"name":"voteRecordExists",
"type":"bool"
}
],
"payable":false,
"stateMutability":"view",
"type":"function"
},
{
"constant":true,
"inputs":[
{
"name":"candidate",
"type":"uint256"
}
],
"name":"voteCount",
"outputs":[
{
"name":"votes",
"type":"uint256"
}
],
"payable":false,
"stateMutability":"view",
"type":"function"
}
]
````

**Comment by juanfranblanco** [comment]
cannot see anything obvious, any chance of the binary.. i don't need the solidity code

**Comment by juanfranblanco** [comment]
yes (doh binary cannot multitask)

**Comment by theonemule** [comment]
Thanks.

**Comment by theonemule** [comment]
I found my problem. 

It wasn't anything wrong with Nethereum per se. Rather, my network was throwing an exception, and the transaction wasn't completed. So the serializer for the response was expecting something that was there, -- the code parameter.

I found it by cloning the repo and inserting some code into the RPCClient to at least give me visibility back into the return from my network. Would it be possible to pass back the error codes from Ethereum to the calling .NET functions so that the feedback is given back to the user? I can add this and issue a pull request if that makes it easier for you...

**Comment by juanfranblanco** [comment]
Ah great thanks, feel free to do both. Issue explaining the requirement and the pull.

**Comment by theonemule** [comment]
Done...see the code changes in the PR.

**Comment by juanfranblanco** [comment]
Fixed by removing the non optional requirement of the code.
