### ISSUE TITLE
ArgumentException: Cost parameter N must be > 1 and < 65536.

### ISSUE THREAD

**Issue by topproto** [Nethereum/Nethereum#330]
Hi i am getting the above error when i do the following

 var ecKey = Nethereum.Signer.EthECKey.GenerateKey();

service.EncryptAndGenerateDefaultKeyStoreAsJson(password, ecKey.GetPrivateKeyAsBytes(), ecKey.GetPublicAddress()); 

Is there any way of working out what is causing this???

**Comment by juanfranblanco** [comment]
What version of Bouncy castle are you using? I have not had any issues in general or with different testing vectors.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/commit/312ca85b05c71fa9964a0994feac8ae34668f34d

**Comment by juanfranblanco** [comment]
@topproto any info on this?

**Comment by raymens** [comment]
So I had this issue today too. It was caused by using 1.8.2 of BouncyCastle. Going back to 1.8.1 made this error disappear.

**Comment by juanfranblanco** [comment]
Thanks @raymens  👍

**Comment by juanfranblanco** [comment]
This is solved in 2.5.1
