### ISSUE TITLE
Personal API enabled but  'The method personal_newAccount does not exist/is not available'

### ISSUE THREAD

**Issue by juliavi** [Nethereum/Nethereum#331]
I've enabled the Personal api, but I'm still getting the follwoing error 
`The method personal_newAccount does not exist/is not available`
`The method personal_unlockAccount does not exist/is not available`

I ran geth this way - 
`geth --rinkeby --rpc  --rpcaddr 0.0.0.0  --rpcport 8545  –-rpcapi="eth,net,web3,admin,personal"`

**Comment by juanfranblanco** [comment]
Hi, did you solve your problem? What version of geth are you using? Did you run "console" to validate you can create the account? Did you try using curl to create the account?

```curl -H "Content-Type: application/json" localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"personal_newAccount","params":["hello"],"id":1}'```

**Comment by scientistnik** [comment]
I work geth with `websocket` and have same problem.

`instance: Geth/v1.8.9-stable-ff9b1461/linux-amd64/go1.10.1`
In console and with `curl` I can create new account, but with `web3` don't!

How to start:
```
$ ./geth  --rinkeby --rpc --rpcapi db,eth,net,web3,personal,debug,miner,txpool --datadir=./rinkeby console --fast --ws --wsport 8546 --wsaddr 0.0.0.0 --wsorigins "*"
```
