### ISSUE TITLE
Token Transfer

### ISSUE THREAD

**Issue by nibirc** [Nethereum/Nethereum#332]
I am trying to transfer ERC20 token using the following code. The TokenService class is defined in the attached file. I am getting erre in RPC, method not supported. I am able to get result from other services in the TokenService class like GetBalanceOfAsync() and GetTotalSypplyAsync() properly, but not able to transfer token. Any help will be appresiated. 
[TokenService.txt](https://github.com/Nethereum/Nethereum/files/1967180/TokenService.txt)

public static Web3 web3 = new Web3("https://rinkeby.infura.io/u0m3xwaBzAXaImwFpigV");
public static string abi = "";//contains actual abi in code
public static string contractAddress = "";//contains actual address in code
public static string Account1 = "";//contains actual address in code
public static  string Account1PK = "";//contains actual PK in code
public static string Account2 = "";//contains actual address in code
static void main()
{
Account ac = new Account(Account1PK);
TokenService.web3= new Web3(ac,"https://rinkeby.infura.io/u0m3xwaBzAXaImwFpigV");
TokenService.abi = abi;
TokenService.contractAddress = contractAddress;
TokenService.Initialize();

TransferFunction tf = new TransferFunction()
{
    FromAddress=Account1,
    To = Account2,
     TokenAmount = 100
};

var res = TokenService.TransferAsync(tf).Result;
}

**Comment by garyng2000** [comment]
any chance infura doesn't expose this so it is a read only ? The difference between this and the other two are those are calls that don't change states, transfer does. in order to do that, you would need to sign the transaction which I don't know how Nethereum implement that in this case. either you have to associate a local keystore service or something. I am pretty sure infura doesn't manage the keystore for you.

**Comment by juanfranblanco** [comment]
@nibirc have you tried using another test network? It might be a problem with Rinkeby, I don't see any issue with this current code. Nobody has reported any issues with Rinkeby and Infura that I am aware of. Ill do a quick test later on and report it.

**Comment by juanfranblanco** [comment]
@nibirc  There is no problems at all with Rinkeby check this https://github.com/Nethereum/Nethereum.CQS.SimpleTokenTransfer
