### ISSUE TITLE
Byte[] NBitcoin.BitcoinSerializableExtensions.ToBytes(NBitcoin.IBitcoinSerializable, NBitcoin.Protocol.ProtocolVersion)

### ISSUE THREAD

**Issue by acgarzon** [Nethereum/Nethereum#333]
Method not found problem with any newer version of NBitcoin, when trying to generate an HD Wallet.

It works perfectly with older versions of NBitcoin though, but it means we have to use outdated library and deprecated methods.

**Comment by juanfranblanco** [comment]
NBitcoin is upgraded now in 2.5.1
