### ISSUE TITLE
array GetDefaultDecodingType

### ISSUE THREAD

**Issue by garyng2000** [Nethereum/Nethereum#334]
public override Type GetDefaultDecodingType() 
         { 
             return typeof(List<object>); 
         } 

should this be typeof(List<typeof(elementType.GetDefaultDecodingType())>) rather than just object ? of course assuming the element is not dynamic

**Comment by juanfranblanco** [comment]
This is implemented on:

```csharp
 public override Type GetDefaultDecodingType()
        {
            return typeof(List<>).MakeGenericType(new[] { ElementType.GetDefaultDecodingType() });
        }

```
