### ISSUE TITLE
Create an online version of the code generator (maybe blazor?)

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#335]
To further simplify entry level, apart from the ui and vscode extension maybe an online version of the code generator might be good.

**Comment by StefH** [comment]
Sounds like a good idea which I also intended to do to make C# code generation more easy.

Currently I've updated your `ejs` files from `abi-code-gen` to include some more methods, renamed some methods, added helper methods and added a separate interface generation.

You can take a look here:
https://github.com/mstack/bootcamp-blockchain-smartcontracts/tree/master/Common/Solidity/templates

A first online version would be written in typescript/javascript and could be easily hosted on github using gh-pages I think?

**Comment by juanfranblanco** [comment]
Hey!, 

Yes there is a complete new code generator, the old one was not extensible enough. The new one it is written in c# and converted to Javascript so it works both in .Net and vscode (well javascript so everywhere). We are experimenting with generating directly on build, but configurable.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.Generators

**Comment by StefH** [comment]
Looks good,  how extensible is this generator code?

**Comment by juanfranblanco** [comment]
Well, it is designed to be extensible, one of the problems was how to target multiple languages, how to reuse "models", namespaces, parameter generators, etc, etc. There is still work to do around the edges, mainly a solution generator, with different configuration settings (that can be saved). You have an UI too cross plaftorm using eto.forms that you can add plugins.

**Comment by juanfranblanco** [comment]
The overall idea you should be able to get started very quickly for anything, from UI to service to Apis etc.

**Comment by StefH** [comment]
This sounds like a complete new project which a lot of features. A lot of work I guess.

One important thing would be that this code-generator can also be executed from a `node.js` command. 

Because currently my development environment for smart contracts is VS Code, in this I do:
- create the contract in VS Code (with your extension installed)
- code linting
- unit testing
- code coverage
- generate c# classes from the contracts

This all is described in this project https://github.com/mstack/bootcamp-blockchain-smartcontracts

**Comment by juanfranblanco** [comment]
It does already, it gets compiled to .net and javascript. The new code generator in vscode for csharp, vb.net and fsharp uses this.

**Comment by juanfranblanco** [comment]
And of course ill have a look at your bootcamp :).

**Comment by StefH** [comment]
Please do !

BTW keeping up with all these new things is difficult sometimes, it changes fast...

**Comment by juanfranblanco** [comment]
On the unit test side check this https://github.com/Nethereum/Nethereum.Contracts.IntegrationTester it is a nuget now, and you may have seen a simple generator for it already.

**Comment by StefH** [comment]
That project is a C# project which can be used to unit-test and check coverage from a solidity smart contract ?

**Comment by juanfranblanco** [comment]
Well it mainly allows you to simply deploy, call, send transactions and validate expectations. I need to add the usual smart contracts Test assertors to unit test.

**Comment by juanfranblanco** [comment]
or might be not, depending on the grammar used.

**Comment by juanfranblanco** [comment]
@StefH After some tests, I have the code coverage concept in c# in a similar way to solc cover. But, this is really unit testing not integration testing. I will package the solc .net compiler soon, and think about a unit test runner.

**Comment by juanfranblanco** [comment]
@StefH Actually, one point to mention, is that the intention of the integration tests, is to provide a simple BDD capability providing a way to test all the different scenarios.  There is not any intention to replace the unit testing of a library method. But we can move this discussion there. Ha ha you got me thinking.

**Comment by StefH** [comment]
At this moment, `truffle` with javascript chai is used for unit-testing. And for integration testing, with code-coverage, the combination from `TestRPC` and `solidity-coverage` is used.

I wonder if it's even possible to do integration testing and code-coverage without a running test blockchain.

BTW other question: do you also have skype or do you use another chat tool ? I really like to ask you some more questions.

**Comment by juanfranblanco** [comment]
Just think behaviour tests can be rather complex, i.e including proxies, data store contracts, multiple contracts, versioning. Complex messages, signatures. And more interesting complex business scenarios, based on multiple states and actions. Also events !!  And errors.

**Comment by juanfranblanco** [comment]
Code coverage, is interesting but sometimes it is a false positive. Just because your test touches a function does not mean is tested.

And sure send me a PM in fitter and we can chat :)

**Comment by juanfranblanco** [comment]
The online code generator can be found at http://codegen.nethereum.com

**Comment by StefH** [comment]
Cool initiative.

Looks good.

This triggers me that I also want to build something like this... However I need to find the time... ;-)

**Comment by juanfranblanco** [comment]
@StefH check the new code generator, it is designed to be more extendable so you can add different templates, also supporting all languages. Do some pull requests if you want for new templates.
