### ISSUE TITLE
Nethereum.JsonRpc.Client.RpcResponseException: known transaction: 

### ISSUE THREAD

**Issue by slqcyy** [Nethereum/Nethereum#336]
Hello.
I'm getting Nethereum.JsonRpc.Client.RpcResponseException: known transaction: 608f9e3b4bb0a4fd63a8162b5cbee34c723093797b462c2a2f953dc251713d54 while trying to transfer on local test network with the latest Geth 1.8.1
`var unitConversion = new UnitConversion();
                var web3 = new Web3(account, GetClient(coinTypeInfo));
                

                var transactionHash = await web3.Eth.TransactionManager.SendTransactionAsync(coinTypeInfo.WithdrawalsAccountAdress, toAddress, new HexBigInteger(unitConversion.ToWei(new BigDecimal(amount))));
                result.Data = transactionHash;`

![image](https://user-images.githubusercontent.com/10707370/39738687-150f996e-52bf-11e8-9d99-61918d7efd1b.png)

**Comment by juanfranblanco** [comment]
Did you solve this? This mainly indicates you are sending the same transaction twice, similar when you get transaction replacement underpriced if you want to replace a transaction

**Comment by slqcyy** [comment]
As you said, there are two nonce transactions with the same node. Thank you for your answer.
