### ISSUE TITLE
Question: how to check if an address is a valid address on a Ethereum blockchain

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#338]
Hello Juan,

I see that this code https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Util/AddressUtil.cs can be used to validate an address using a checksum.

However, is it also possible to check if an address actually exists on a Ethereum Blockchain?

**Comment by juanfranblanco** [comment]
@StefH  Have just seen this. Well you can check the balance of an address but an address might be in a smart contract referenced, which it has never used the blockchain.

**Comment by Gelassen** [comment]
You can do this either by regexp or by checking checksum. 

I am working web3 port on ```java``` and there are two classes responsible for this: ```Keys``` and ```WalletUtils```

**Comment by juanfranblanco** [comment]
yes that is what https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Util/AddressUtil.cs  does.
