### ISSUE TITLE
Nethereum.Web3 v2.4.0 and Ipfs.Api v0.20 incompatibility

### ISSUE THREAD

**Issue by jandroalvarez** [Nethereum/Nethereum#345]
I've tried to install Nethereum.Web3 v2.4.0 in a netstandard 1.4 library called MyApp.Core where I had already installed Ipfs.Api v0.20 which is a netstandard 1.4 library, too.
At first, everything worked fine and I didn't get any error from NuGet Package Manager. However, after trying to build the solution I got the following error:

> Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'. Perhaps it doesn't exist in the Mono for Android profile?
> Nombre de archivo: 'crypto.dll'
>    en Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
>    en Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
>    en Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	MyApp.Droid

MyApp.Droid is a Xamarin.Android app that references MyApp.Core.

As an alternative, I tried to install Nethereum.Web3 on MyApp.Droid but I got exactly the same error.

I could find a workaround installing Nethereum.Portable v2.4.0 on MyApp.Droid. This way, everything worked fine and I get no errors.

At this moment, I can handle this situation. Nevertheless, eventually I'd like to move the nethereum code to the common netstandard library (MyApp.Core)

I open the issue on Nethereum instead of Ipfs.Api because it seems a problem with the netstandard version of Nethereum which doesn't work either on Android project or netstandard library. On the other hand, the Portable version works fine on Android.

**Comment by jandroalvarez** [comment]
Hello!

Yesterday I've seen that a new version of Web3 has been released (v2.5.0).

I've tried to install it in the netstandard library with Ipfs.Api and....it worked!

This issue can be closed now :)

**Comment by juanfranblanco** [comment]
Excellent :) Please use 2.5.1 if using .netcore2.1
