### ISSUE TITLE
Unable to pass BigInteger value to contract as ParamArray

### ISSUE THREAD

**Issue by Enigmatic331** [Nethereum/Nethereum#346]
Given a contract as below:

```
contract testing {
    uint256 storeuint256;
    
    function returnuint256() public view returns (uint256) {
        return storeuint256;
    }
    
    function enteruint256(uint256 _storeuint256) public {
        storeuint256 = _storeuint256;
    }
}
```

Attempted to pass (2^256) - 1 (115792089237316195423570985008687907853269984665640564039457584007913129553535) with the below code:

```
Dim SuperBigUint As BigInteger = BigInteger.Parse("115792089237316195423570985008687907853269984665640564039457584007913129639935")
Dim storeSomeStuff = tokencontract.GetFunction("enteruint256")
Dim transactionHash = Await storeSomeStuff.SendTransactionAndWaitForReceiptAsync(account.Address, gas, value, , SuperBigUint)
```

Error "System.ArgumentOutOfRangeException: 'Number was less than the array's lower bound in the first dimension." is thrown. Did a SuperBigUint.ToByteArray and noticed array length was 33.

Works fine on Remix. Current workaround through Nethereum is to sign and send a raw transaction (e.g. data: 0xa3eafc88ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff).

Maybe I am doing something wrong? Thanks in advance. :)

**Comment by juanfranblanco** [comment]
Great point, actually to put an actual guard in Nethereum for overflows. Values encoded are 32 bytes, so the issue might be due to the signing of the BigInteger which includes the extra byte.

**Comment by Enigmatic331** [comment]
Would this mean we could consider maxIntSizeInBytes to be 33 bytes on function EncodeInt(BigInteger value), but check to ensure the BigInteger value does not exceed 2**256 - 1?

Let me know if I am being dumb, Juan. Thanks always!

**Comment by juanfranblanco** [comment]
The idea is to validate that exceeds 2**256 - 1, and in that scenario throw an exception to avoid overflows.

Then yes that will be 33 bytes so it would not fit in the message, you have 32 bytes per value. The problem here because it is signed (my belief) it has added a new byte, 0x00 which could be removed to become unsigned. 

My plan to avoid this issue is to take a hint from .netcore2.1 and create the same extension compatible with all the frameworks, that includes the sign and the endianism.

**Comment by Enigmatic331** [comment]
Ah ok. What I had in mind was too naive. (yes you are right, it came out to be 00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff).

When it is committed I will have a look at your code to learn how would you implement the fixes.

**Comment by juanfranblanco** [comment]
I like naive btw, as I won't have access to the Bits in the BigInteger I won't be able to use the same approach. But a simple thing might be just to remove the 00 if it is a positive BigInteger.

**Comment by juanfranblanco** [comment]
Yeah.. I see what you did there with the 00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff becoming ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

**Comment by juanfranblanco** [comment]
Well in that scenario, I do need to check it with real values, the limit should be 31 bytes.

**Comment by Enigmatic331** [comment]
Was playing with the intTypeDecoder and intTypeEncoder to get a better idea of how this works.

I guess removing the 00 would work when we are encoding, but during decoding it could be a bit tricky as there needs to be a check to see if the return value should be unsigned, and append 00 to the end.

Still thinking how I would fix this if I were to pick up this issue. 🙏

**Comment by Enigmatic331** [comment]
A slightly patchy route I would take is to check if outputParam.Parameter.ABIType is uint256; If yes I would append a zero byte to the front (so later the IsLittleEndian checks can reverse the array).

To be honest not sure if it is ideal though...

![image](https://user-images.githubusercontent.com/28551011/41193879-745a7d7c-6c45-11e8-925e-b7bc18cc30ea.png)

**Comment by juanfranblanco** [comment]
Ok now with some small time to look at the problem.

"int<M>: enc(X) is the big-endian two’s complement encoding of X, padded on the higher-order (left) side with 0xff for negative X and with zero bytes for positive X such that the length is 32 bytes."

So to get a 32 byte array then maximum length will be 31 bytes to include 0xff for negative and 0x00 for positive (in a simplistic way).

If solidity accepts ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff that is just a negative value, padded. As it has reached the maximum value.

**Comment by Enigmatic331** [comment]
Thanks. Good to know I am generally heading down the right direction - Was putting up a conditional when decoding and encoding to handle uint (33 bytes) and int (31 bytes) cases separately.

Would you like me to try picking this up Juan? I can set up the test cases too.

**Comment by juanfranblanco** [comment]
Sure.

Pseudo code:

if(byteArray > 33) throw exception (Out of Range)
if(value >=  BigInteger.Pow(new BigInteger(2), 256) - 2) throw exception (Out of Range)
if(byteArray == 33 && BigInteger.Positive) remove 0x00 sign. (Before reverse to make it BigEndian)
if(BigInteger.Negative && byteArray > 31 bytes) throw exception (Out of Range)

:)

**Comment by Enigmatic331** [comment]
Just a quick update before I create a pull request this weekend.

Int minimum (-57896044618658097711785492504343953926634992332820282019728792003956564819968) is 0x8000000000000000000000000000000000000000000000000000000000000000. Thrown me off at first since I was expecting a 0xFF, and we have a line `var negative = encoded.First() == 0xFF` when decoding.

It also occupies full 32 bytes so I think we can omit the BigInteger.Negative && byteArray > 31 bytes check.
<br/>

Uint maximum (115792089237316195423570985008687907853269984665640564039457584007913129639935) is 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff. On ParameterDecoder.cs I have added a conditional to check if ABIType.Name.Contains("uint") which will then append a 0 byte array, so `new BigInteger(encoded)` will work out it is unsigned.
<br/>

![image](https://user-images.githubusercontent.com/28551011/41485551-98f642e2-7113-11e8-8b62-0b17b12b4d3c.png)

**Comment by juanfranblanco** [comment]
Yes, the signed values are 255 bits, I was using bytes instead of bits (doh!)
So the limit is 7 / 8 not E. (127, 128)
And value ranges as you mentioned are:
57896044618658097711785492504343953926634992332820282019728792003956564819967
or
7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
for positive
and
negative..
-57896044618658097711785492504343953926634992332820282019728792003956564819968
And yes unsigned allows for FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
which needs the necessary check for uint if not it will be converted to -1.


Very cool! I would just put a MinInt256, MaxInt256, MaxUint256, MinUint256 values as a string and Parse and validate ranges, easier visibility than Hex / Bytes. (Although the values in comments might be cool).

**Comment by juanfranblanco** [comment]
Although solidity is managing the 0x8000000000000000000000000000000000000000000000000000000000000000, I don't understand as per specs an FF should indicate a negative value.

**Comment by juanfranblanco** [comment]
Sure make the pull, or I will end up doing it.
Here are my unit tests on decoding https://github.com/Nethereum/Nethereum/commit/64038ce1d740f3a8307b3e7be112d1b18ce606ee.

**Comment by juanfranblanco** [comment]
Ok i have added now just the decoding stuff to make the tests pass, have a look as you are ready for the pull for any thoughts.

Only left are the range validation.

**Comment by juanfranblanco** [comment]
Right, further thought is to add validation for all the lengths. Although that was not my intention as it was the user responsibility to know the contract they are interacting and their limits.

**Comment by Enigmatic331** [comment]
PR done. My first ever PR... Rip it apart... :)

> Right, further thought is to add validation for all the lengths. Although that was not my intention as it was the user responsibility to know the contract they are interacting and their limits.

Understood - For uint8, uint16, int8, int16, etc. Yes I think we should do that, though I admit Remix allows overflowing. I can see if Web3JS does bound checks or not.

Happy to pick this up though I admit I need to learn a lot more from everyone here, so let's first see if I code decent enough through this PR to help out more... :)

**Comment by juanfranblanco** [comment]
Many thanks! @Enigmatic331  
Let me know what you think about this:

I have ended up putting the Min and Max range here for clarity.
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/IntType.cs#L9-L13
Also, note that the check I have put for signed + unsigned that i used in both encoding and decoding

So what I was referring yesterday was this:
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/Decoders/IntTypeDecoder.cs#L68-L73

So it is part of the IntDecoder and checking the sign there.

Now the Encoding part ends up like this:
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/Encoders/IntTypeEncoder.cs#L51-L78

Which does the different checks and conversions, not touching any hex or bytes for clarity (only removing the 0x00 sign if 33 bytes and unsigned.

And for integration testing I have added the further Overflow tests, these are designed to force an overflow in solidity but at the same time validating the encoding is correct of large values.

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Accounts.IntegrationTests/ABIIntegerTests.cs#L171-L280

**Comment by juanfranblanco** [comment]
This is the solidity part:
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Accounts.IntegrationTests/ABIIntegerTests.cs#L21-L63

**Comment by juanfranblanco** [comment]
Now what I was saying it will be interesting (although I did not want to test each type max / min of int / uint), also I have avoided it on purpouse as the end user should know the range they are working with, similar to this situation (althought he pull request that was introduced was wrong, I should not have accepted it so lightly).

**Comment by Enigmatic331** [comment]
> Now what I was saying it will be interesting (although I did not want to test each type max / min of int / uint), also I have avoided it on purpouse as the end user should know the range they are working with, similar to this situation (althought he pull request that was introduced was wrong, I should not have accepted it so lightly).

Ah! I got you Juan - Just caught the tone. My bad.
Thanks for the commits, really appreciate this.

**Comment by juanfranblanco** [comment]
Oh Just to be clear, I was not referring to yours, I was referring to the old one that introduce the bug. It was my fault not checking it further. Yours was great, just changed it on the way with the research.
