### ISSUE TITLE
Nethereum & UWP App

### ISSUE THREAD

**Issue by relianz** [Nethereum/Nethereum#349]
Hi all,

Nethereum is a great thing, you're doing a great Job Juan!

I would like to use the library with a UWP app built with Visual Studio Community 2017 (Version 15.7.2). When I install Nethereum.Web3 using nuget I get a lot of version mismatches for system packages, the same applies to Nethereum.Portable. 

What is best practice to build the library from source for the UWP target (.NET Core 1.1)? 

Thank you in advance.

**Comment by juanfranblanco** [comment]
Hi, have you checked with the latest 2.5.1? What is the minimum target of UWP you are using?

**Comment by relianz** [comment]
Unhappily, the minimum target is the most current Windows 10, version 1803 (10.0; Build 17234). If I check out the latest 2.5.1, what steps do I have to take to compile a library suitable for the target UWP app? Many thanks in advance - best regards!

**Comment by juanfranblanco** [comment]
You should not need to have the latest (at least from the Nethereum side)

**Comment by juanfranblanco** [comment]
The wallet even if using Xamarin Forms it has a head for UWP https://github.com/Nethereum/Nethereum.UI.Wallet.Sample

**Comment by juanfranblanco** [comment]
@relianz  did you get sorted?

**Comment by relianz** [comment]
Hi Juan,
 
thank you for responding and sorry for my late reaction.
 
No, until now, I didn’t get Nethereum up and running with our UWP app. It would be very helpful to find instructions how to build the library for a certain platform – which files hold the configuration that must be adjusted to our target?
 
Thank you in advance.
 
Warm regards.
 
 
 
    Dr.-Ing. Markus A. Stulle
 
    Schleißheimer Straße 70 - 80797 München
    Phone: +49 172 8 59 70 36
    Skype:  <mailto:markus@stulle.onmicrosoft.com> markus@stulle.onmicrosoft.com  
    GnuPG:  <http://eu.pool.sks-keyservers.net/pks/lookup?op=get&search=0x5D9B9925713B5056> markus@stulle.zone (fingerprint: 68ADB7A23C5D774E89A7C5F75D9B9925713B5056)    
     
    .oooooo..o     .               oooo  oooo                
    d8P'    `Y8   .o8               `888  `888                
    Y88bo.      .o888oo oooo  oooo   888   888   .ooooo.      
     `"Y8888o.    888   `888  `888   888   888  d88' `88b     
         `"Y88b   888    888   888   888   888  888ooo888     
    oo     .d8P   888 .  888   888   888   888  888    .o  
    8""88888P'    "888"  `V88V"V8P' o888o o888o `Y8bod8P'  
                                                                                                                    
     <https://smartcontract.world/> https://smartcontract.world  
     <https://explorer.blockstack.org/name/stulle.id> https://explorer.blockstack.org/name/stulle.id  
 
   „The electric light did not come 
    from the continuous improvement of candles.“ ( <https://en.wikipedia.org/wiki/Oren_Harari> Oren Harari).
    
 
 
Von: Juan Blanco <notifications@github.com> 
Gesendet: Mittwoch, 20. Juni 2018 15:39
An: Nethereum/Nethereum <Nethereum@noreply.github.com>
Cc: relianz <markus@stulle.zone>; Mention <mention@noreply.github.com>
Betreff: Re: [Nethereum/Nethereum] Nethereum & UWP App (#349)
 
@relianz <https://github.com/relianz>  did you get sorted?

**Comment by juanfranblanco** [comment]
If you post an empty project I can test it. It is netstandard 1.1 or net451 so it has to work. Failing that the portable.

To build download and you are done, targets are the lowest.. cannot be lower than that.
