### ISSUE TITLE
A conversion error occurs getting FilterLog for pending transactions

### ISSUE THREAD

**Issue by vladkravchuk** [Nethereum/Nethereum#350]
I'm getting the following json deserialization exception when I try to get a FilterLog list:

"...Unable to convert the result to type Nethereum.RPC.Eth.DTOs.FilterLog[] ---> Newtonsoft.Json.JsonSerializationException: Error converting value "0xeedb691...ca83" to type 'Nethereum.RPC.Eth.DTOs.FilterLog'..."

The value there is a real transaction hash that is in pending state. So it looks like geth returns a tx hash instead of an expected object.

Is it a known issue?

The code is as simple as:
var pendingFilterTask = _web3.Eth.Filters.NewPendingTransactionFilter.SendRequestAsync();
var filterId = pendingFilterTask.Result;
var filterChangesTask = _web3.Eth.Filters.GetFilterChangesForEthNewFilter.SendRequestAsync(filterId);
var filterChangesResult = filterChangesTask.Result;
...

The same error is for GetFilterLogsForEthNewFilter.

nethereum version 2.4.0
geth version 1.8.2 (windows)

**Comment by juanfranblanco** [comment]
@vladkravchuk for pending transactions you need to use the following:

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/Eth/Filters/EthGetFilterChangesForBlockOrTransaction.cs

**Comment by vladkravchuk** [comment]
Thanks, this works. 
But how can I filter the list of pending transactions by "From" or "To" address in this case?

**Comment by juanfranblanco** [comment]
Apologies forgot to respond, you cannot.
