### ISSUE TITLE
New Error : An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by realmind90** [Nethereum/Nethereum#351]
here is my code : 

var contract = TokenCommonConstants.Contract;
var web3 = TokenCommonConstants.Web3;

var function = contract.GetFunction("tokensOfOwner");
var callInput = function.CreateCallInput(walletAddress);

var encoded = await web3.Eth.Transactions.Call.SendRequestAsync(callInput);
var decoded = function.DecodeDTOTypeOutput<TokenList>(encoded);

return decoded.TokenIndexList;

It worked fine for over two months, but suddenly error occured yesterday.

When I call SendRequestAsync(), below error occurs : 

**System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host** 

How can I solve this problem? I have no idea.

**Comment by Enigmatic331** [comment]
Are you calling from Infura? Was wondering if this could be the same issue which appeared as Infura recently upgraded to TLS2.

**Comment by realmind90** [comment]
@Enigmatic331 
Yes, I'm calling from Infura. How to fix this problem? Should I modify the code?

**Comment by juanfranblanco** [comment]
If you are using .net451 you will need to add this code
https://github.com/Nethereum/Nethereum.CQS.SimpleTokenTransfer/blob/master/Nethereum.CQS.SimpleTokenTransfer.Net451/Program.cs#L22

**Comment by realmind90** [comment]
@juanfranblanco Thanks for your support! I'll check the link.
