### ISSUE TITLE
FromDER(signature.ToDER()) ->  does not produce same signature

### ISSUE THREAD

**Issue by qisbic** [Nethereum/Nethereum#352]
var privKey = new EthECKey("7e973bff0733ac2aa6c8bd6edc1dcd4b2113e23a2b2435c9d94cff5b69e0a213");
            string msg = "hi";
            byte[] msgBytes = Encoding.UTF8.GetBytes(msg);
            byte[] msgHash = new Sha3Keccack().CalculateHash(msgBytes);
            var signature = privKey.SignAndCalculateV(msgHash);
            EthECDSASignature signatureNew = EthECDSASignature.FromDER(signature.ToDER());
            if (signature== signatureNew )
            {
                Console.WriteLine("Same");
            }
            // results is not the same, V is NULL in signatureNew 

In the above, using ToDER and FromDER does not produce the same signature.  V is null for signatureNEW , R and S are fine (version 2.5.1).

Am I doing anything wrong?

**Comment by juanfranblanco** [comment]
You are not doing anything wrong, the V is calculated on signing.

**Comment by juanfranblanco** [comment]
Yes true, you cannot recover without a signature containing V. Here you will pass your full signature.

**Comment by juanfranblanco** [comment]
Keeping it open to validate force recovery.

**Comment by juanfranblanco** [comment]
The idea of force recovery is not great.

Better explanation to close the issue:

From message signer.
```csharp
 public virtual string EcRecover(byte[] hashMessage, string signature)
        {
            var ecdaSignature = ExtractEcdsaSignature(signature);
            return EthECKey.RecoverFromSignature(ecdaSignature, hashMessage).GetPublicAddress();
        }

```
Whilts  force recovery is not a good idea, it can be done as:

```csharp
      var recId = EthECKey.CalculateRecId(signature, rawBytes, publicKey);
            signature.V = new[] {(byte) (recId + 27)};
```

But we need the public key not address or make up the Vs :)
