### ISSUE TITLE
Is it possible to detect an out of gas exception?

### ISSUE THREAD

**Issue by carlcook** [Nethereum/Nethereum#353]
Hi,

Transaction receipts now carry a status to tell you if a transaction succeeded or failed.

However, from what I can tell, there is no way to programmatically determine if the transaction failed due to being out of gas. 

It used to be possible to detect this via the heuristic of gasUsed == gasLimit. But now that the REVERT opcode has been introduced, this heuristic no longer works reliably.

Any pointers on how this might be achieved (programmatically)? Maybe I am just missing something, but etherscan seems to be able to determine this (and they use parity from what I can gather).

**Comment by juanfranblanco** [comment]
Etherscan checks the debug logs, hence it can get all the information.

**Comment by carlcook** [comment]
Ah, right, node logs... I forgot about those. So I'd need to run a node in debug mode, and scan the logs.

**Comment by juanfranblanco** [comment]
Check the BlockchainStorage that might help, also it is at the moment only for geth for debug
