### ISSUE TITLE
Support for ABIEncoderV2

### ISSUE THREAD

**Issue by naddison36** [Nethereum/Nethereum#355]
Add support for Solidity's ABIEncoderV2 format which allow structs and arbitrarily nested arrays in function arguments and return values
https://medium.com/@chriseth/the-new-solidity-abi-encoder-decoder-and-optimizer-aee8f91e2455

Version 2 of the 0x Protocol uses ABIEncoderV2 so a lot of people will want support for this. eg https://github.com/0xProject/0x-monorepo/blob/v2-prototype/packages/contracts/src/contracts/current/protocol/Exchange/MixinExchangeCore.sol

**Comment by juanfranblanco** [comment]
@naddison36  Check https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Accounts.IntegrationTests/ABIStructsTests.cs

**Comment by naddison36** [comment]
you are one step ahead. Thanks

**Comment by juanfranblanco** [comment]
Well the code generators do not output this yet.. and I have not tested Arrays of structs.. so it is not complete. Ill reopen ;)

**Comment by juanfranblanco** [comment]
And Thanks for always keeping me right :D

**Comment by naddison36** [comment]
Haha, I feel like I've been pestering you for a few years now on various feature requests

Although I'm not currently using Nethereum, I'm building contracts that use ABIEncoderV2 so I want to get the main Ethereum clients to have support.

I've also spoken to Conor Svensson about support in web3j

Ethers.js already has support

**Comment by juanfranblanco** [comment]
Yes, Conor or Yvalo are working on it, also this is going to get more interesting with the EIP 712.  That was one of the main goals of all the Function messages, DTOs etc. Let the user know what they are signing. https://github.com/ethereum/EIPs/blob/master/assets/eip-712/Example.js

**Comment by juanfranblanco** [comment]
This is supported now. Although we need code generators
