### ISSUE TITLE
HexBigInteger.Equals() support?

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#359]
This code:

```
    let bi1 = System.Numerics.BigInteger(0)
    let hbi1 = Nethereum.Hex.HexTypes.HexBigInteger(bi1)
    let bi2 = System.Numerics.BigInteger(0)
    let hbi2 = Nethereum.Hex.HexTypes.HexBigInteger(bi2)
    let eqb = bi1.Equals(bi2)
    Console.Write(eqb.ToString())
    let eqhb = hbi1.Equals(hbi2)
    Console.WriteLine(eqhb.ToString())
```

Currently prints "TrueFalse".

Shouldn't it print "TrueTrue" instead?

**Comment by juanfranblanco** [comment]
@knocte check latest, also there is a CI in MyGet.. (look the readme)

**Comment by knocte** [comment]
awesome, but, what's the point of using MyGet instead of "prereleases" in Nuget?

**Comment by knocte** [comment]
but not sure I can use MyGet from the ancient version of nuget that my (linux)CI has 😬

**Comment by juanfranblanco** [comment]
Are you running dotnet restore?
If you add a nuget.config at root of the solution, that should work:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="MyGet Nethereum CI" value="https://www.myget.org/F/nethereum/api/v3/index.json" />
  </packageSources>
</configuration>
