### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by zeshanvirk** [Nethereum/Nethereum#360]
Unable to send to tokens when using contract function, Here is my code to calculate gas and to send transaction

` var gas = await transferFunction.EstimateGasAsync(senderAddress, null, null, toAddress, 2);
 var receipt = await transferFunction.SendTransactionAndWaitForReceiptAsync(senderAddress, gas, null, null, toAddress, 2);`

EstimateGasAsync returning **22872** as value & **0x5958**  as hexValue

whereas my senderAddress have total balance of 200 tokens, and 0 ether.

i checked gasPrice using `var gasPrice = await _web3.Eth.GasPrice.SendRequestAsync();` and it returns **18000000000** as value & **0x430e23400** as hexValue
i'm following this docs:  https://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstard-smartcontrats/

**Comment by juanfranblanco** [comment]
If you have no Ether (0 ether) you cannot send a transaction
