### ISSUE TITLE
Events not being detected

### ISSUE THREAD

**Issue by UnimaginaryUnit** [Nethereum/Nethereum#364]
Good evening. I'm trying to work with Truffle, Ganache and Nethereum, and for some reason Nethereum doesn't seem to track the events, though I can see events being emitted and `eth_getFilterChanges` in Ganache console.

Here are the code snippets:

Event in Solidity:
```solidity
event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);
```

Nethereum Code:
```csharp
        public class TransferEvent {
            [Parameter("address", "from", 1, true)]
            public string From {get; set;}

            [Parameter("address", "to", 2, true)]
            public string To {get; set;}

            [Parameter("uint256", "tokenId", 3, true)]
            public BigInteger TokenId {get; set;}
        }

        // Contract is stored in 'artifacts' variable

        static async Task updateInventories(){
            // Get event from the contract
            var transferEvent = artifacts.GetEvent("Transfer");
            // Create event filter
            var filter = await transferEvent.CreateFilterAsync();

            // Wait for events
            while(true){
                var log = await transferEvent.GetFilterChanges<TransferEvent>(filter);
                if(log.Count != 0){
                    Console.WriteLine("Gotcha!");
                }
                Thread.Sleep(3000);
            }
        }
```

I'm running `updateInventories()` and then triggering transfer event, but nothing happens. Could you help me?

UPD: Doesn't work with Truffle development console as well.

**Comment by UnimaginaryUnit** [comment]
Might be referenced to #317 but I'm sure the contract is deployed and I can work with it (as I do some calls before calling `updateInventroies()`)

**Comment by kdelwat** [comment]
I'm getting the same issue, although the events do show up in the Truffle console. I've tested triggering the events from transactions created in both Truffle and Nethereum, and they show up with the Truffle web3 watcher, but not the Nethereum filter.

I've also tested with both automining and a slower 5 second mine speed and the issue remains. Any help would be very appreciated :)

My C# code:

```
var getRequestEvent = contract.GetEvent("GetRequest");
var filterAll = await getRequestEvent.CreateFilterAsync();

while (true) 
{
    var requests = await getRequestEvent.GetFilterChanges<GetRequestEvent>(filterAll);
    ...
}
```

```
    public class GetRequestEvent
    {
        [Parameter("uint256", "requestId", 1, true)]
        public int RequestId { get; set; }

        [Parameter("string", "dataURI", 2, false)]
        public int DataUri { get; set; }
    }
```

And solidity:
```
    event GetRequest (
        uint256 indexed requestId,
        string dataURI
    );
```

Version info:
Truffle v4.1.8 (core: 4.1.8)
Solidity v0.4.23 (solc-js)

**Comment by UnimaginaryUnit** [comment]
@juanfranblanco I would be grateful if you could help with the issue, as after a 2-day research on the issue I still have no idea on how to fix it.

**Comment by juanfranblanco** [comment]
Are you creating the filters before you send any transaction?
FilterChanges will only retrieve the changes that have occurred after you create the filter.

**Comment by UnimaginaryUnit** [comment]
Yes, I firstly create the filter, and then send the transaction, while checking for filter changes in loop

**Comment by UnimaginaryUnit** [comment]
My Ganache console log:
```
[11:59:05 AM] eth_newFilter
[11:59:05 AM] eth_getFilterChanges
[11:59:08 AM] eth_getFilterChanges
[11:59:11 AM] eth_getFilterChanges
[11:59:12 AM] eth_sendTransaction
[11:59:12 AM]   Transaction: 0x554bf996247c25946b816c71b2c507c35f71ae21d03dff5a9663451d510435f4
[11:59:12 AM]   Gas usage: 43905
[11:59:12 AM]   Block Number: 36
[11:59:12 AM]   Block Time: Tue Jun 26 2018 11:59:12 GMT+0300 (MSK)
[11:59:12 AM] eth_getTransactionReceipt
[11:59:13 AM] eth_sendTransaction
[11:59:13 AM]   Transaction: 0x3a6812c1dd921ddefa3ec7a024d0f5727478ceab00ced39b7524d9f94bb3245c
[11:59:13 AM]   Gas usage: 54091
[11:59:13 AM]   Block Number: 37
[11:59:13 AM]   Block Time: Tue Jun 26 2018 11:59:13 GMT+0300 (MSK)
[11:59:13 AM] eth_getTransactionReceipt
[11:59:14 AM] eth_getFilterChanges
[11:59:17 AM] eth_getFilterChanges
```
I'm sure the event is being emitted, as I can see it in Truffle log:
```
...
event: 'Transfer',
...
```

**Comment by juanfranblanco** [comment]
Have you tried Geth instead? https://github.com/Nethereum/TestChains (Just to validate is not an issue with Ganache)

Or have you tried to do it inline create filter, send transaction, get changes, just to validate it is fine your threading? (it should be fine based on your console log).

**Comment by UnimaginaryUnit** [comment]
Yeah, I tried it inline, didn't work as well. I think it might be Ganache issue, I'll try it with Geth now.

**Comment by UnimaginaryUnit** [comment]
Yes, it works fine with Geth. Definitely seems like a Ganache issue.

**Comment by juanfranblanco** [comment]
Thanks @UnimaginaryUnit  Ill report it.

**Comment by detachmode** [comment]
Ganache v2.0.0-beta.1  fixed it for me.

**Comment by StefH** [comment]
I can confirm that Ganache `v1.3.0` also works for me.
