### ISSUE TITLE
How to cast event data from FilterLog into event struct from the ABI

### ISSUE THREAD

**Issue by TriplejumpGames** [Nethereum/Nethereum#369]
I'm getting a FilterLog[] back from using EthGetLogsUnityRequest. I can see that the .Data inside the results is correct, but how do I cast the data string into a struct to get the members?

**Comment by juanfranblanco** [comment]
"but how do I cast the data string into a struct to get the members?"

You mean to convert it to an EventDTO?

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Contracts/Event.cs#L134-L137

**Comment by TriplejumpGames** [comment]
Thanks, that worked! I had to figure out that the class for representing the EventDTO needed to be decorated with Parameters that have the correct boolean setting for the indexed properties, otherwise it throws an error when decoding Topics.

I'll post the code that worked here, so ppl in the future can search it.
The event in solidity was:
`event CardCreated(uint indexed _cardInstanceId, uint indexed _cardTypeId, uint _createdTime, address _discoverer);`

The class in Unity was:
`
public class CardCreated
{
	[Parameter("int", "_cardInstanceId", 1, true)]
	public int _cardInstanceId { get; set; }

	[Parameter("int", "_cardTypeId", 2, true)]
	public int _cardTypeId { get; set; }

	[Parameter("int", "_createdTime", 3, false)]
	public int _createdTime { get; set; }

	[Parameter("address", "_discoverer", 4, false)]
	public string _discoverer { get; set; }
}
`

And the code for actually decoding the result and accessing the members:
`
List<EventLog<CardCreated>> list_events = event_cardCreated.DecodeAllEventsForEvent<CardCreated>(request.Result);

for(int i = 0; i < list_events.Count; i++) {

	EventLog<CardCreated> eventLog_cardCreated = list_events[i];

	Debug.Log("EVENT LOG RESULT: " +
		"CardInstance " + eventLog_cardCreated.Event._cardInstanceId +
		"CardType " + eventLog_cardCreated.Event._cardTypeId + 
		"CreatedTime " + eventLog_cardCreated.Event._createdTime + 
		"Discoverer " + eventLog_cardCreated.Event._discoverer +
		" " + Time.time);
}
`
