### ISSUE TITLE
How to pass parameters to constructor ?

### ISSUE THREAD

**Issue by Neustart** [Nethereum/Nethereum#370]
Hi there,
I need to deploy smart contract with next constructor:
```
constructor (uint256 a,
               uint256 p1, uint256 p2, uint256 p3,
               uint8 r1, uint8 r2, uint8 r3, uint8 r4,
               uint256 f) 
```

I've found this method in Netherium, seems like `values `parameters is exactly what I need :
`public Task<TransactionReceipt> SendRequestAndWaitForReceiptAsync(string abi, string contractByteCode, string from, HexBigInteger gas, CancellationTokenSource receiptRequestCancellationToken = null, params object[] values);`

How can I pass parameters to it ?  This not works: `new[] {1, 1, 1, 1, 1, 1, 1, 1, 1}`

Thanks

**Comment by Neustart** [comment]
@juanfranblanco wow, thanks for your amazing answer !
Which VSCode extension should I use ?

**Comment by juanfranblanco** [comment]
This one https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity
And thanks :)

**Comment by RVaniuta** [comment]
@juanfranblanco I have an issue with your solutions.
`BigInteger period1 = (BigInteger)(ConvertToUnixTimestamp(checkin.AddDays(-3)));
            BigInteger period2 = (BigInteger)(ConvertToUnixTimestamp(checkin.AddDays(-2)));
            BigInteger period3 = (BigInteger)(ConvertToUnixTimestamp(checkin.AddDays(-1)));

            byte outsidePeriod1RefundPct = Convert.ToByte(100);
            byte outsidePeriod2RefundPct = Convert.ToByte(50);
            byte outsidePeriod3RefundPct = Convert.ToByte(25);
            byte insidePeriod3RefundPct = Convert.ToByte(5);

            BigInteger expiresAt = (BigInteger)(ConvertToUnixTimestamp(checkout));

            BigInteger amount = (BigInteger)(1.6 * 1000000000000000000);

            var contract = new Tripki.Contracts.Escrow.CQS.EscrowDeployment()
            {
                A = amount,
                P1 = period1,
                P2 = period2,
                P3 = period3,
                R1 = outsidePeriod1RefundPct,
                R2 = outsidePeriod2RefundPct,
                R3 = outsidePeriod3RefundPct,
                R4 = insidePeriod3RefundPct,
                F = expiresAt
            };`

but after deploy all these values are 0

**Comment by garyng2000** [comment]
if I don't use the Generic form, can I use something like new object[]{new BigInteger(1), new BigInteger(1), ...}
and call the params object[] form instead ?

**Comment by juanfranblanco** [comment]
As long as they are in the right order yes

**Comment by juanfranblanco** [comment]
https://docs.nethereum.com/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstarted-smartcontracts-untyped/

**Comment by juanfranblanco** [comment]
But you won't be able to use structs
