### ISSUE TITLE
Issue with passing signature to ERC865 contract

### ISSUE THREAD

**Issue by HadarKeidar** [Nethereum/Nethereum#371]
I deployed a contract implementing ERC865 token.

The Solidity recover function is:

    function recover(bytes32 hash, bytes sig) public pure returns (address) {
      bytes32 r;
      bytes32 s;
      uint8 v;

      //Check the signature length
      if (sig.length != 65) {
        return (address(0));
      }

      // Divide the signature in r, s and v variables
      assembly {
        r := mload(add(sig, 32))
        s := mload(add(sig, 64))
        v := byte(0, mload(add(sig, 96)))
      }

      // Version of signature should be 27 or 28, but 0 and 1 are also possible versions
      if (v < 27) {
        v += 27;
      }

      // If the version is correct return the signer address
      if (v != 27 && v != 28) {
        return (address(0));
      } else {
        return ecrecover(hash, v, r, s);
      }
    }

and the function calling recover function is:

       function transferPreSigned(
               bytes _signature,
               address _to,
               uint256 _value,
               uint256 _fee,
               uint256 _nonce
           )
               public
              returns (bool)
        {
        require(_to != address(0));
        require(signatures[_signature] == false);

        bytes32 hashedTx = transferPreSignedHashing(address(this), _to, _value, _fee, _nonce);

        address from = recover(hashedTx, _signature);
       
        require(from != address(0));
        ........
        ........
       }

when i use Nethereum.Web3.OfflineTransactionSigner.SignTransaction() i get sig.length = 208 
and when i use Nethereum.signer.HashAndSign() i get sig.length = 132.

I think I'm missing out something but can not figure what it is.
Do you know how should pass the signature to the function?
Thanks.

**Comment by juanfranblanco** [comment]
Hi, first apologies for the late response. The ERC865 needs a library in Nethereum altogether :). The transaction signer includes other elements like Data and it is also RLP enconded not something you will use in that implementation. On that scenario you need to use the normal signer, but you are just implementing the relay of a transfer and this should be also used as a smart contract proxy (IMHO)

**Comment by juanfranblanco** [comment]
Closing, just use the message signer for this as per comment
