### ISSUE TITLE
System.ArgumentNullException: transactionHash

### ISSUE THREAD

**Issue by Cryt1c** [Nethereum/Nethereum#382]
I get the mentioned error at Nethereum.RPC.Eth.Transactions.EthGetTransactionReceipt.SendRequestAsync(String transactionHash, Object id)
when I try to deploy autogenerated code.

In my code i do the following and it occurs on the last line:
```               
web3 = new Nethereum.Web3.Web3();
deployment = new ChangeManagerDeployment();
ChangeManagerService changeManagerService = await ChangeManagerService.DeployContractAndGetServiceAsync(web3, deployment);
```

I am using Ganache as a testchain and I don't see any transactions happening there.
Any ideas what I might be doing wrong there?

**Comment by juanfranblanco** [comment]
@Cryt1c you may need to pass your account to Web3.

var web3 = new Web3(new Account("one of the private keys when you start ganache"));

**Comment by Cryt1c** [comment]
Thanks a lot for your quick and always on point responses! It totally worked.

**Comment by juanfranblanco** [comment]
Ha ha thanks
