### ISSUE TITLE
Smart Contract returning random values in logs when a transaction is initiated using nethereum

### ISSUE THREAD

**Issue by CHAIBHANGALE** [Nethereum/Nethereum#389]
My smart contract is as follows

pragma solidity ^0.4.6;

   contract update {

    uint startTime;
    int public counter = 1;

    event Counter(address indexed sender, int result);

    function counterincrement() public 
    {
            counter++;
            emit Counter(msg.sender, counter);
            return counter;
    }

    }

**And my C# code is as follows:**

    public async System.Threading.Tasks.Task<Boolean> callContractIncrement()
    {
        try
        {
            var senderAddress = "0xd2bb2ce7094c160d5f2a6c5004416fb40c1a62f0";
            var password = "newsamp";
            //var abi = @"[{""constant"":false,""inputs"":[],""name"":""counterincrement"",""outputs"":[{""name"":""counter"",""type"":""int256""}],""payable"":false,""stateMutability"":""nonpayable"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""counter"",""outputs"":[{""name"":"""",""type"":""int256""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""anonymous"":false,""inputs"":[{""indexed"":true,""name"":""sender"",""type"":""address""},{""indexed"":false,""name"":""result"",""type"":""int256""}],""name"":""Counter"",""type"":""event""}]";
            var abi = @"[{""constant"":false,""inputs"":[],""name"":""counterincrement"",""outputs"":[],""payable"":false,""stateMutability"":""nonpayable"",""type"":""function""},{""constant"":true,""inputs"":[],""name"":""counter"",""outputs"":[{""name"":"""",""type"":""int256""}],""payable"":false,""stateMutability"":""view"",""type"":""function""},{""anonymous"":false,""inputs"":[{""indexed"":true,""name"":""sender"",""type"":""address""},{""indexed"":false,""name"":""result"",""type"":""int256""}],""name"":""Counter"",""type"":""event""}]";
            //var abi = @"[{""constant"":false,""inputs"":[{""name"":""a"",""type"":""int256""}],""name"":""multiply"",""outputs"":[{""name"":""r"",""type"":""int256""}],""type"":""function""},{""inputs"":[{""name"":""multiplier"",""type"":""int256""}],""type"":""constructor""},{""anonymous"":false,""inputs"":[{""indexed"":true,""name"":""a"",""type"":""int256""},{""indexed"":true,""name"":""sender"",""type"":""address""},{""indexed"":false,""name"":""result"",""type"":""int256""}],""name"":""Multiplied"",""type"":""event""}]";
            var byteCode = "0x608060405234801561001057600080fd5b5042600155610106806100246000396000f30060806040526004361060485763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416634a8922138114604d578063ed4dd52a146071575b600080fd5b348015605857600080fd5b50605f6083565b60408051918252519081900360200190f35b348015607c57600080fd5b50605f60cc565b6000608b60cc565b6000819055604080519182525133917f66051a4cef05b58d22487a536671033aaa093f25b1e6f8c1c735c472090f8c35919081900360200190a25060005490565b6001546005429190910305905600a165627a7a72305820d4f4746fe0c1f5b00c448bfa3a97e6e6133053946928f5631cc6dbded60356900029";
            var multiplier = 7;

            var web3 = new Nethereum.Web3.Web3("http://localhost:8545");

            var unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 120);
            // Assert.True(unlockResult);

            var transactionHash = await web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, senderAddress, new HexBigInteger(900000));

            var receipt = await MineAndGetReceiptAsync(web3, transactionHash);

            var contractAddress = receipt.ContractAddress;

            var contract = web3.Eth.GetContract(abi, contractAddress);

            var multiplyFunction = contract.GetFunction("counterincrement");

            var multiplyEvent = contract.GetEvent("Counter");
            var filterAll = await multiplyEvent.CreateFilterAsync();
            //var filter7 = await multiplyEvent.CreateFilterAsync(7);

            int i = 0;
            do
            {
                //var unlockResultTransaction = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 30);
                transactionHash = await multiplyFunction.SendTransactionAsync(senderAddress, new HexBigInteger(900000), null);
                //transactionHash = await multiplyFunction.SendTransactionAsync(senderAddress, new HexBigInteger(900000), null);

                receipt = await MineAndGetReceiptAsync(web3, transactionHash);

                var log = await multiplyEvent.GetFilterChanges<CounterEvent>(filterAll);
                //System.Diagnostics.Debug.WriteLine(log);
                //var LockResult = await web3.Personal.LockAccount.SendRequestAsync(senderAddress); //UnlockAccount.SendRequestAsync(senderAddress, password, 30);
                System.Threading.Thread.Sleep(1000);
            } while (i < 10);

            //var log7 = await multiplyEvent.GetFilterChanges<MultipliedEvent>(filter7);

            //Assert.Equal(2, log.Count);
            //Assert.Equal(1, log7.Count);
            //Assert.Equal(7, log7[0].Event.MultiplicationInput);
            //Assert.Equal(49, log7[0].Event.Result);
            return true;
        }
        catch (Exception e)
        {
            Console.WriteLine("Exception" + e.Message);
            return false;
        }
    }

    public async System.Threading.Tasks.Task<Nethereum.RPC.Eth.DTOs.TransactionReceipt> MineAndGetReceiptAsync(Nethereum.Web3.Web3 web3, string transactionHash)
    {

        //var miningResult = await web3.Miner.Start.SendRequestAsync(6);
        //Assert.True(miningResult);

        var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);

        while (receipt == null)
        {
            System.Threading.Thread.Sleep(1000);
            receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
        }

        //miningResult = await web3.Miner.Stop.SendRequestAsync();
        //Assert.True(miningResult);
        return receipt;
    }

}

class CounterEvent
{
    //  [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("int", "a", 1, true)]
    //  public int MultiplicationInput { get; set; }

    [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("address", "sender", 1, true)]
    public string Sender { get; set; }

    [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("int", "result", 2, false)]
    public int Result { get; set; }

}
The value returned in the event is random integer value. I am not able to understand why the contract is returning random integer values. Can you please help me with this??

Also when I check the contract if it is deployed in Nethereum using the contract address returned it shows as deployed but when I check the functions they return random values. And If i deploy the same contract using remix and not using Nethereum then everything works fine

**Comment by juanfranblanco** [comment]
Apologies for the late late response, mainly there was a problem when deploying the smart contract (most probably out of gas), so even if you got a receipt, it was not succesful.
