### ISSUE TITLE
Cannot Run workbook samples

### ISSUE THREAD

**Issue by userid2018** [Nethereum/Nethereum#392]
Cannot Run workbook samples. Getting following error. 
(1,1): error CS0006: Metadata file 'Nethereum.Web3' could not be found
error: The application terminated during evaluation of this cell. Run this cell manually to try again.

Tried adding Nethereum.Web3 package manually as well but still gives error.

Update : After changing to .net core, I get following error
(1,1): error CS0006: Metadata file 'Nethereum.Web3' could not be found

**Comment by juanfranblanco** [comment]
@userid2018  what version of Workbooks are you using? Operating System?

**Comment by juanfranblanco** [comment]
Paging @anegg0, any current issues like this?

**Comment by userid2018** [comment]
Xamarin Workbooks version 1.4.3
OS Windows 10
Nethereum Workboom version  : latest from git rebo https://github.com/Nethereum/Nethereum.Workbooks.git

**Comment by anegg0** [comment]
@userid2018 do all of your workbooks fail? In the case some of them only fail, could you please share their reference?

**Comment by userid2018** [comment]
All of them are failing.

**Comment by anegg0** [comment]
Ok, thank you for the prompt feedback, will try them on my (new and freshly reinstalled) environment

**Comment by anegg0** [comment]
@userid2018 I tried running the worbooks from the same repo on a similar environment, but didn't encounter issues. Are you running the latest .NET core version?

**Comment by userid2018** [comment]
Yes .

C:\Users\AppAdmin>dotnet --version
2.1.302

**Comment by userid2018** [comment]
Tested on a different machine. same error.
OS : Windows 10 Pro x64.
dot net version : latest
C:\Users\user>dotnet --version
2.1.301

Netehereum Workbook : latest
Workbook software : latest

Error msg snapshot attached.

![errormsg](https://user-images.githubusercontent.com/39634445/43779526-99a2aae6-9a26-11e8-866f-c140358c05fa.PNG)

**Comment by juanfranblanco** [comment]
@anegg0  the first quick get started should not use portable, better Nethereum.Web3

**Comment by juanfranblanco** [comment]
Closing this now, if there are still any problems please reopen.
