### ISSUE TITLE
How to run js library with Nethereum

### ISSUE THREAD

**Issue by senzacionale** [Nethereum/Nethereum#393]
I would like to use 0x.js and other erc20 js libraries with Nethereum. Is it possible to integrate this libraries or some wrapper exist to use js libraries in Nethereum. 

Thank you

**Comment by juanfranblanco** [comment]
What exactly you need? Nethereum does not create a javascript interop, as it is not portable.
What libraries you need "other erc20 js"

**Comment by senzacionale** [comment]
Hi, I would like to use 0x.js library with NEThereum

**Comment by juanfranblanco** [comment]
Right, the options are:
1. To create an 0x .net implementation ie Nethereum.0x (this would be the best option if you are going to use it in a crossplatform setting, optimised etc). The contract libraries are pretty simple, and most of the other code, can leverage most of Netherum internals. This is not in the road map at the moment but I will raise an issue to chat about this with them.

2. Workaround using something like https://github.com/tjanczuk/edge, this limits your scope. If you are just going to use this in a server environment, you might be ok. I have tried to do plenty of interop to avoid duplicating work, but the best way is to work first in .Net and from there transpile to Javascript (and only in simple libraries).

3. You are using something like Blazor to create a WASM SPA then you can do some interop of wasm in browser, or you are creating a webgl app.
