### ISSUE TITLE
Issue for SendRequestAndWaitForReceiptAsync

### ISSUE THREAD

**Issue by Jimmy987** [Nethereum/Nethereum#396]
Run the following code, I got error: **Error occurred when trying to send rpc requests(s).**
I trace that found SendTransactionAsync is sucessed, but SendRequestAndWaitForReceiptAsync throw a exception. 
`
txnHash = await transactionService.SendRequestAndWaitForReceiptAsync(() => functionSet.SendTransactionAsync(account, 42));`

so How can I got the same result between SendTransactionAsync and SendRequestAndWaitForReceiptAsync? 
the result of SendRequestAndWaitForReceiptAsync must be consistent with SendTransactionAsync.

Can anyone help?
Thanks a lot.

**Comment by knocte** [comment]
Please paste the whole ex.ToString() (including stacktrace).

**Comment by juanfranblanco** [comment]
Closing this now.
