### ISSUE TITLE
I cant compile c# 6 code easily without latest visual studio

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#4]
Would be nice to take out the c# 6 syntax so Xamarin and Sharpdevelop and older VS can compile this library.  At least until c# 6 is better supported.

**Comment by juanfranblanco** [comment]
When moving to netstandard both universal and xamarin will be supported but first Linux windows and osx using core.

**Comment by slothbag** [comment]
This is more a discussion on my own grasp of the new .Net world than a bug or request.. 

I have had no luck getting anything to run using the new dotnet coreclr / dnx / netstandard etc, as mentioned I was able to compile but then it didn't work with my old school .Net framework 4.5.2.  Which is fine, the whole thing is in flux right now.

I have written a build script which takes the sources of JsonRpc.Client & Nethereum and builds one Nethereum.dll with it all included internally.  This also resolves another problem I had where JsonRpc.Client references an older Json.Net and my project uses the newer version.

I guess is it worth me maintaining this setup as a forked repo with the changes following Nethereum and JsonRpc or should I just release Nethereum.dll as my own .Net Framework ready nuget package or have I wasted my time because I missed an obvious solution already :)

**Comment by juanfranblanco** [comment]
Don't worry, the .net world is changing, and you are not the only one.. RC2 is supposed to be when everything will settle down. VS still uses dnx to compile hence the issues with .net cli as Json.net has not been ported to dotnet5x which will later be netstandardx.

 For the time being if that works for you, specially with your setup go ahead. If you build your own, you will get fixes faster than via nugets ;)

Next nugets will target dotnet52, net451 and dnxcore50, so you should be able to use them.

**Comment by slothbag** [comment]
For anyone without the latest VS, this nuget package **Microsoft.Net.Compilers** contains a recent build of the Roslyn compiler which supports c# 6 code.

I have been using it to compile this library.

**Comment by juanfranblanco** [comment]
Thanks im putting an special XS Solution with autogenerated project

**Comment by juanfranblanco** [comment]
Here is the solution for XS together with a quick utility to rebuild the project file
https://github.com/Nethereum/Nethereum/tree/master/Nethereum-XS
