### ISSUE TITLE
Support for EIP55  Checksum address

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#40]
https://github.com/ethereum/EIPs/issues/55

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/Util/AddressUtil.cs

**Comment by knocte** [comment]
New location: https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Util/AddressUtil.cs
