### ISSUE TITLE
Support for custom ERC20 Tokens?

### ISSUE THREAD

**Issue by DynConcepts** [Nethereum/Nethereum#400]
I do not see this, and before I spend time I would like to confirm. The use case is custom tokens being tracked using Ethereum block chain and complex contracts. Aside from GAS charges, there will not actually be any movement of ETH as part of this process.

**Comment by juanfranblanco** [comment]
I don't understand the question.. you are going to create a custom contract which supports the ERC20 interface?

**Comment by DynConcepts** [comment]
Juan, Thanks for the response. I will admit that right now [after over a week of attempting to dig in and find something like what I want/need] I am almost completely baffled [something that has been rare over my 40+ years as a software developer].

The end goal is to track a number of assets. Who has the asset along with structured meta-data about the asset is key. The assets do not have a direct value [ETH or $$$] but I do realize there will be GAS charges for the various transactions. This gives rise to questions such as can Asset #1243 be transferred from A to B with the charged borne by C?

Finding some sample code that I could get to work would be a great starting point. There are [IMHO] so many hurdles. For example, I was doing some experiments with EthConsole. Using Google with "+EthConsole -Geth" still returned a majority of results that in fact referenced geth!!!!

Any help or pointers would be greatly appreciated.

**Comment by juanfranblanco** [comment]
Hi let me know if you still have issues, just go to gitter to ask any questions.
