### ISSUE TITLE
How can I get rid of the SendRequest() debug? 

### ISSUE THREAD

**Issue by OmerAlgur19** [Nethereum/Nethereum#402]
The one starts with "jsonrpc". I think it is in the .dll and I don't know how to get rid of it.

**Comment by juanfranblanco** [comment]
If you are using the latest DLLs on the release (which are built on release mode) and you build also on release, you should be fine.

**Comment by juanfranblanco** [comment]
Cool let me know.. I can release with another pragma flag, or remove it.

**Comment by juanfranblanco** [comment]
Dlls are released in release mode now for Unity3d
