### ISSUE TITLE
Why i got Error 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by WillIDC** [Nethereum/Nethereum#405]
Hi , i wrote some code like this:

here is Solidity:

pragma solidity ^0.4.4;
contract Voting {
　uint a = 22;
　function geta() public view returns (uint){
　　return a;
　}
　function changea(uint bb) public {
　　a = bb;
　}
}

here is my vb:

Dim senderAddress As String = "0xc4482c99aadcb0f8f210dcf3c2d18e17769fa102"
Dim abi As String = "[{'constant':false,'inputs':[{'name':'bb','type':'uint256'}],'name':'changea','outputs':[],'payable':false,'stateMutability':'nonpayable','type':'function'},{'constant':true,'inputs':[],'name':'geta','outputs':[{'name':'','type':'uint256'}],'payable':false,'stateMutability':'view','type':'function'}]"
          
Dim web3 = New Web3("https://ropsten.infura.io/")  
Dim contract = web3.Eth.GetContract(abi, "0xfa43ef6c1dca10f9aebe8933c222b75918a1798d")

Dim gas As HexBigInteger = New HexBigInteger(System.Numerics.BigInteger.Parse("900000"))
Dim value As HexBigInteger = New HexBigInteger(System.Numerics.BigInteger.Parse("0"))

Dim changeFunction As Task(Of String) = contract.GetFunction("changea").SendTransactionAsync(senderAddress, gas, value, 1)
changeFunction.Wait()  ---  error line
　
　
here is error message:
 　
[HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed)。]    System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() +92828    
Nethereum.JsonRpc.Client.<SendAsync>d__17.MoveNext() +696

but i got Error405 , can someone help me? thans a lot.

**Comment by WillIDC** [comment]
if i use this , it can work ,  but i dont know what different they are.

Dim gas As HexBigInteger = New HexBigInteger(System.Numerics.BigInteger.Parse("900000"))
Dim value As HexBigInteger = New HexBigInteger(System.Numerics.BigInteger.Parse("0"))

Dim c = contract.GetFunction("changea")
Dim transactionHash = Await c.SendTransactionAsync(senderAddress, gas, value, 336777)

**Comment by Enigmatic331** [comment]
You will need to create your account object with a private key, since Infura is a public node and they cannot store your private keys for you (vs a locally hosted node like Geth), hence method not allowed.

Something like this to initialise your SenderAddress:

```
Dim privateKey As New Nethereum.Signer.EthECKey("0000000000000000000000000000000000000000000000000000000000000000") 'enter your private key here
Dim account = New Nethereum.Web3.Accounts.Account(privateKey)
Dim senderAddress = account.Address
```

More info: https://nethereum.readthedocs.io/en/latest/accounts/
