### ISSUE TITLE
Hanging - personal.unlockAccount

### ISSUE THREAD

**Issue by Dave-Whiffin** [Nethereum/Nethereum#409]
From gitter - @alphasignal.   

If you connect to a node that for instance does not have "personal" json RCP calls authorized, and you send personal_unlockAccount, it will just hang...and furthermore even if it is implemented, if you get an error message of any kind it will just hand...example, send personal_unlockAccount with a valid hexadecimal integer will give the following error:
{"jsonrpc":"2.0","error":{"code":-32000,"message":"Time-unlocking is only supported in --geth compatibility mode.","data":"Restart your client with --geth flag or use personal_sendTransaction instead."},"id":1}
The method that calls this has await, and will just sit there blocked.

One for investigation and possible error handling improvement.

**Comment by juanfranblanco** [comment]
This is a Parity behaviour, personal unlockAccount needs to use a HexBigInteger to unlock the values. There are different implementations for both Geth and Parity. This is already in the comments.

The hanging this is nothing we can do, as other clients (Geth) will throw an exception. Nethereum has a timeout to handle this situations, but in reality a client should be configured (carefully) to not enable not needed features (for example personal unlock is consider dangerous). 
@alphasignal
