### ISSUE TITLE
v, r, s salt calculation

### ISSUE THREAD

**Issue by cybergogic** [Nethereum/Nethereum#410]
`const { soliditySha3 } = require('web3-utils');
const {
  hashPersonalMessage,
  bufferToHex,
  toBuffer,
  ecsign
} = require('ethereumjs-util')
const { mapValues } = require('lodash');
const raw = soliditySha3({
  t: 'address',
  v: contractAddress
}, {
  t: 'address',
  v: tokenBuy
}, {
  t: 'uint256',
  v: amountBuy
}, {
  t: 'address',
  v: tokenSell
}, {
  t: 'uint256',
  v: amountSell
}, {
  t: 'uint256',
  v: expires
}, {
  t: 'uint256',
  v: nonce
}, {
  t: 'address',
  v: address
});
const salted = hashPersonalMessage(toBuffer(raw))
const {
  v,
  r,
  s
} = mapValues(ecsign(salted, privateKeyBuffer), (value, key) => key === 'v' ? value : bufferToHex(value));
// send v, r, s values in payload`

i did not find the function mapValues, hashPersonalMessage, etc
do I really write this code for a netherium?

**Comment by cybergogic** [comment]
Hi! i try to calculate hash for sign the contract function by idex.api https://github.com/AuroraDAO/idex-api-docs/blob/master/README.md using .NET
Web3.js contain functions hashPersonalMessage and soliditySha3.
Do you plan to do similar functions in the Netherium?
Could you help me?

**Comment by vindberg** [comment]
Hi @cybergogic did you resolve this issue with soliditysha3? Im looking for the same solution.

**Comment by juanfranblanco** [comment]
You can use https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/ABIEncode.cs for this now.
