### ISSUE TITLE
StandardTokenEIP20 TransferAsync no way to set msg.data?

### ISSUE THREAD

**Issue by CKKwan** [Nethereum/Nethereum#411]
I am not sure, but I was trying to search for this feature for one whole day, but couldn't find one.

**Comment by juanfranblanco** [comment]
The data element of the TransactionInput is how Ethereum interacts with smart contracts. You may be able to add extra data, but you will need first to create your own transaction input using the TransferFunction message, then append the extra data and finally send the transaction using the TransactionManager.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/issues/421
