### ISSUE TITLE
HTTPS connection

### ISSUE THREAD

**Issue by alphasignal** [Nethereum/Nethereum#412]
At the moment if you connect to a service such as Infura that only accept HTTPS connections, it will just fail each time. A client that connects with both clear-text (what exists now) and SSL is needed.

This should be a simple implementation that is very much needed.

**Comment by juanfranblanco** [comment]
@alphasignal this is supported, I assume you are using net451.
To connect to infura using .net451 and TLS2 you need to set it in advance

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

https://github.com/Nethereum/Nethereum.CQS.SimpleTokenTransfer/blob/master/Nethereum.CQS.SimpleTokenTransfer.Net451/Program.cs#L22-L24
