### ISSUE TITLE
How to decode transaction input Data

### ISSUE THREAD

**Issue by jzarifis** [Nethereum/Nethereum#414]
Hi,
Is it possible to decode a transaction input data, knowing the abi?
Just like this js implementation:
https://lab.miguelmota.com/ethereum-input-data-decoder/example/

Great work guys, 
Thanks

**Comment by juanfranblanco** [comment]
This is an example https://github.com/Nethereum/Nethereum/blob/2f68f6194a3baf1e4aa9de426209bbcfbcec4581/src/Nethereum.Contracts.UnitTests/Web3FunctionEncodingDecoding.cs#L46

or if you have a typed message, you can use something like this https://github.com/Nethereum/Nethereum/blob/7714186a6fa8d0a085e340ebde29afe84eeef0ea/src/Nethereum.Contracts/Extensions/FunctionMessageExtensions.cs#L25-L29

**Comment by SimonOrdo** [comment]
@juanfranblanco Is it possible to decode the input from a Transaction object without knowing the function in advance?  I have a generic transaction returned from w3.Eth.Transactions.GetTransactionByHash and it has an "input" field.  I know which smart contract was targeted, but not sure how I can derive the called method name using the "input" field data from the Transaction object.

**Comment by juanfranblanco** [comment]
@SimonOrdo if you know the smart contract and is not a proxy, and you have the abi, you should be able to decode it.

**Comment by SimonOrdo** [comment]
> @SimonOrdo if you know the smart contract and is not a proxy, and you have the abi, you should be able to decode it. Just iterate throw the functionmessages and validate it.

Would you please show me how?

**Comment by juanfranblanco** [comment]
Join discord I have answered that before. https://discord.com/channels/765580668327034880/770613045827207168/841973154212872193

**Comment by shunqiziran888** [comment]
> ```cs
>  var transfer = new TransferFunction().DecodeInput(txn.Input);
> ```
幸好有你在，我找了半年...总算解决了！ 文档都没有 日了狗了！~

**Comment by juanfranblanco** [comment]
@shunqiziran888 check the playground there is a similar example using the whole transaction http://playground.nethereum.com/csharp/id/1063
FunctionMessages have many extensions.

**Comment by shunqiziran888** [comment]
> @shunqiziran888检查游乐场时，有一个类似的示例使用整个事务 http://playground.nethereum.com/csharp/id/1063 FunctionMessages有许多扩展。

这个地址无法打开，可能是中国网络限制，等好久没反应，另外logs的data如何解析？

**Comment by juanfranblanco** [comment]
@shunqiziran888 Is it working now? It will take a while to load due to being all Blazor + downloading the dlls. BTW I am using google translate for your tweets.

The samples are here https://github.com/Nethereum/Nethereum.Playground/tree/master/Nethereum.Playground/wwwroot/samples/csharp
And the index of them is here https://github.com/Nethereum/Nethereum.Playground/blob/master/Nethereum.Playground/Repositories/CSharpSamples.cs

**Comment by juanfranblanco** [comment]
@shunqiziran888 Is access to ipfs restricted in China?

**Comment by shunqiziran888** [comment]
> @shunqiziran888 Is access to ipfs restricted in China?

非常感谢，目前已经解决了, 很多国外站点中国是无法访问的，需要翻墙，有机会欢迎来中国旅游!

**Comment by juanfranblanco** [comment]
我很高兴听到这个消息，我敢打赌很难知道哪个网站被禁止，哪个网站没有。我猜 Blazor wasm 和 VPN 的加载速度会慢得多。我需要想办法让这变得更好。我去过上海一次，在以太坊会议上，虽然我没有太多时间好好参观，但我很想和我的家人再次回去。如此美丽的国家。如果我能学中文而不用谷歌翻译就好了

**Comment by shunqiziran888** [comment]
> 我很高兴听到这个消息，我敢打赌很难知道哪个网站被禁止，哪个网站没有。我猜 Blazor wasm 和 VPN 的加载速度会慢得多。我需要想办法让这变得更好。我去过上海一次，在以太坊会议上，虽然我没有太多时间好好参观，但我很想和我的家人再次回去。如此美丽的国家。如果我能学中文而不用谷歌翻译就好了

麻烦了，主要是我的英语也不好。我也用百度翻译。谷歌在中国无法访问，因为它涉及许多非法内容。翻译工具有些内容也不标准， 祝你的家人身体健康，万事如意

**Comment by shunqiziran888** [comment]
web3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync 提示
transaction type not supported: eth_sendRawTransaction

**Comment by shunqiziran888** [comment]
web3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync
Error= transaction type not supported: eth_sendRawTransaction

**Comment by shunqiziran888** [comment]
> 网络3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync Error= 事务类型不受支持：eth_sendRawTransaction
我设置了UseLegacyAsDefault =true 可以正常工作了！ 这东西是干嘛的？

**Comment by Troom** [comment]
When i use 

>  var decode = testFunction.DecodeInput(data); 

 I get right results
 
![image](https://user-images.githubusercontent.com/10126507/199494529-bf2191df-dcc6-4764-b34a-f15b894d4eb3.png)

 
 But when i use

>  var decode= FunctionMessageExtensions.DecodeInput(myTransferFunctionInstance, x.Input);

I get huge BigInteger values

![image](https://user-images.githubusercontent.com/10126507/199495084-975c2c08-b3ff-47fb-813d-8c72e74e95e3.png)

 
 Here is my transferFunction

>      [Function("transfer", "string")]
>     public class TransferFunction : FunctionMessage
>     {
>         [Parameter("uint256", "_plotId", 0)]
>         public  BigInteger _plotId { get; set; }
>         [Parameter("uint8", "_digsToOpen", 1)]
>         public virtual BigInteger _digsToOpen { get; set; }
>         [Parameter("uint256", "_currentRent", 2)]
>         public virtual BigInteger _currentRent { get; set; }
>         [Parameter("uint8", "_r", 3)]
>         public virtual BigInteger _r { get; set; }
>         [Parameter("bytes32", "_v", 4)]
>         public virtual BigInteger _v { get; set; }
>         [Parameter("bytes32", "_s", 5)]
>         public virtual BigInteger _s { get; set; }
>     }




So, How should I decode the data to get the correct result for the typed object?

**Comment by juanfranblanco** [comment]
@Troom what is the data?

**Comment by Troom** [comment]
txn.Input

I get txn by 
            

> var txn = await web3.Eth.Transactions.GetTransactionByHash.SendRequestAsync("0x83e3f1cdf602979f0d0ff4d7f0941b89b8d3e43614fe85807d26eb09fb6239be");

**Comment by juanfranblanco** [comment]
what chain?

**Comment by Troom** [comment]
BSC

**Comment by juanfranblanco** [comment]
The function is openRentPlot not transfer

**Comment by Troom** [comment]
I don't really know what you mean.My point is that I assign other incorrect values ​​to the typed object.
My code:

>             var ABI = @"[{""inputs"":[{""internalType"":""contract IPlanetPlot"",""name"":""_planetPlot"",""type"":""address""},{""internalType"":""contract IPlotState"",""name"":""_plotState"",""type"":""address""},{""internalType"":""contract IMoDApproveProxy"",""name"":""_ModApproveProxy"",""type"":""address""},{""internalType"":""contract IPlanetPassHandler"",""name"":""_planetPassHandler"",""type"":""address""},{""internalType"":""contract IResources"",""name"":""_resources"",""type"":""address""},{""internalType"":""address"",""name"":""_MoDTaxAccount"",""type"":""address""},{""internalType"":""address"",""name"":""_admin_address"",""type"":""address""}],""stateMutability"":""nonpayable"",""type"":""constructor""},{""anonymous"":false,""inputs"":[{""indexed"":false,""internalType"":""address"",""name"":""renter"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""digsClosed"",""type"":""uint256""}],""name"":""CloseRentAndMint"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":false,""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""Paused"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":false,""internalType"":""uint256"",""name"":""recipeId"",""type"":""uint256""}],""name"":""PlotRURecipeCreated"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":false,""internalType"":""uint256"",""name"":""recipeId"",""type"":""uint256""}],""name"":""PlotRURecipeDeleted"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""address"",""name"":""renter"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""plotId"",""type"":""uint256""},{""indexed"":false,""internalType"":""uint256"",""name"":""nrOfDigs"",""type"":""uint256""}],""name"":""Rent"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":false,""internalType"":""uint256"",""name"":""plotId"",""type"":""uint256""},{""indexed"":false,""internalType"":""uint256"",""name"":""recipeId"",""type"":""uint256""}],""name"":""ReplenishUpgradeEvent"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""indexed"":true,""internalType"":""bytes32"",""name"":""previousAdminRole"",""type"":""bytes32""},{""indexed"":true,""internalType"":""bytes32"",""name"":""newAdminRole"",""type"":""bytes32""}],""name"":""RoleAdminChanged"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""indexed"":true,""internalType"":""address"",""name"":""account"",""type"":""address""},{""indexed"":true,""internalType"":""address"",""name"":""sender"",""type"":""address""}],""name"":""RoleGranted"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""indexed"":true,""internalType"":""address"",""name"":""account"",""type"":""address""},{""indexed"":true,""internalType"":""address"",""name"":""sender"",""type"":""address""}],""name"":""RoleRevoked"",""type"":""event""},{""anonymous"":false,""inputs"":[{""indexed"":false,""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""Unpaused"",""type"":""event""},{""inputs"":[],""name"":""DEFAULT_ADMIN_ROLE"",""outputs"":[{""internalType"":""bytes32"",""name"":"""",""type"":""bytes32""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""GAME_CONTROL"",""outputs"":[{""internalType"":""bytes32"",""name"":"""",""type"":""bytes32""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""MoDApproveProxy"",""outputs"":[{""internalType"":""contract IMoDApproveProxy"",""name"":"""",""type"":""address""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""PLANET_PLOT_CREATOR"",""outputs"":[{""internalType"":""bytes32"",""name"":"""",""type"":""bytes32""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_recipeId"",""type"":""uint256""},{""internalType"":""uint256[]"",""name"":""_RIIds"",""type"":""uint256[]""},{""internalType"":""uint256[]"",""name"":""_RIAmounts"",""type"":""uint256[]""},{""internalType"":""uint256"",""name"":""_DIAmount"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_max"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_add"",""type"":""uint256""}],""name"":""addPlotRURecipe"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[],""name"":""breakRent"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""uint256[]"",""name"":""_resources"",""type"":""uint256[]""},{""internalType"":""uint256[]"",""name"":""_amounts"",""type"":""uint256[]""},{""internalType"":""uint256"",""name"":""_digsToClose"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_plotId"",""type"":""uint256""},{""internalType"":""bytes"",""name"":""_prefix"",""type"":""bytes""},{""internalType"":""uint8"",""name"":""_v"",""type"":""uint8""},{""internalType"":""bytes32"",""name"":""_r"",""type"":""bytes32""},{""internalType"":""bytes32"",""name"":""_s"",""type"":""bytes32""}],""name"":""closeRentAndMint"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_sideLength"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_planetId"",""type"":""uint256""}],""name"":""createPlanet"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[],""name"":""fixedRent"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""}],""name"":""getRoleAdmin"",""outputs"":[{""internalType"":""bytes32"",""name"":"""",""type"":""bytes32""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""grantRole"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""hasRole"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""internalNonce"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""maxOpenDigs"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""miningSafetyCap"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""_to"",""type"":""address""},{""internalType"":""uint256"",""name"":""_planetId"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_region"",""type"":""uint256""}],""name"":""mintPlotRegion"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_plotId"",""type"":""uint256""},{""internalType"":""uint8"",""name"":""_digsToOpen"",""type"":""uint8""},{""internalType"":""uint256"",""name"":""_currentRent"",""type"":""uint256""},{""internalType"":""uint8"",""name"":""_v"",""type"":""uint8""},{""internalType"":""bytes32"",""name"":""_r"",""type"":""bytes32""},{""internalType"":""bytes32"",""name"":""_s"",""type"":""bytes32""}],""name"":""openRentPlot"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[],""name"":""pauseHandler"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[],""name"":""paused"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""planetPassHandler"",""outputs"":[{""internalType"":""contract IPlanetPassHandler"",""name"":"""",""type"":""address""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""planetPlot"",""outputs"":[{""internalType"":""contract IPlanetPlot"",""name"":"""",""type"":""address""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""playerMinRent"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""name"":""plotCooldown"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_recipeId"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_plotId"",""type"":""uint256""}],""name"":""plotRU"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""name"":""plotRURecipes"",""outputs"":[{""internalType"":""uint256"",""name"":""darInputAmount"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""max"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""add"",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""plotState"",""outputs"":[{""internalType"":""contract IPlotState"",""name"":"""",""type"":""address""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_recipeId"",""type"":""uint256""}],""name"":""recipeExists"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_recipeId"",""type"":""uint256""}],""name"":""removePlotRURecipe"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""renounceRole"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[],""name"":""replenishCooldown"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""resources"",""outputs"":[{""internalType"":""contract IResources"",""name"":"""",""type"":""address""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""bytes32"",""name"":""role"",""type"":""bytes32""},{""internalType"":""address"",""name"":""account"",""type"":""address""}],""name"":""revokeRole"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_plotId"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_rent"",""type"":""uint256""}],""name"":""setPlotRent"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[],""name"":""staticTax"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[{""internalType"":""bytes4"",""name"":""interfaceId"",""type"":""bytes4""}],""name"":""supportsInterface"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""taxRate"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},{""inputs"":[],""name"":""unpauseHandler"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint8"",""name"":""_maxOpenDigs"",""type"":""uint8""}],""name"":""updateDigLimit"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_fixedRent"",""type"":""uint256""}],""name"":""updateFixedRent"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_miningSafetyCap"",""type"":""uint256""}],""name"":""updateMiningSafetyCap"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_playerMinRent"",""type"":""uint256""}],""name"":""updatePlayerMinRent"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_replenishCooldown"",""type"":""uint256""}],""name"":""updateReplenishCooldown"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""_serverPubKey"",""type"":""address""}],""name"":""updateServer"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""uint256"",""name"":""_staticTax"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""_taxRate"",""type"":""uint256""}],""name"":""updateTax"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},{""inputs"":[{""internalType"":""address"",""name"":""_MoDTaxAccount"",""type"":""address""}],""name"":""updateTaxAccount"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""}]";
>             var web3 = new Web3("MyEndpoint");
>             var txn = await web3.Eth.Transactions.GetTransactionByHash.SendRequestAsync("0x83e3f1cdf602979f0d0ff4d7f0941b89b8d3e43614fe85807d26eb09fb6239be");
> 
>             var contract = web3.Eth.GetContract(ABI, "0xb4d954aB111bdA2c3E5E92a65deeD47e6175B77B");
>             var testFunction = contract.GetFunction("openRentPlot");
> 
>             var DecodedInput = testFunction.DecodeInput(txn.Input); //right result but not typed.
> 
>             var myTransferFunction = new TransferFunction();
>             var NotTypedResult = myTransferFunction.DecodeInput(txn.Input); //Huge unreadable bigInteger
>             var TypedResult = myTransferFunction.DecodeInput<TransferFunction>(txn.Input); //Huge unreadable bigInteger the same as NotTypedResult



Where can I go wrong?

**Comment by Troom** [comment]
Yea, you're right, Thanks a lot for help.
Sorry for replying so late.

I had another problem that you answered four years ago. Now everything work as expected ;)
![image](https://user-images.githubusercontent.com/10126507/200645236-76958990-07da-4db7-97a6-4cf05cf35a1a.png)
