### ISSUE TITLE
web3.Personal.UnlockAccount.SendRequestAsync throws exception when using a long value as durationInSeconds

### ISSUE THREAD

**Issue by StefH** [Nethereum/Nethereum#416]
When using this code:

``` c#
await web3.Personal.UnlockAccount.SendRequestAsync("0x...", "...", 120);
```
I get an exception like:

> System.AggregateException: One or more errors occurred. (Invalid params: invalid type: integer `120`, expected a 0x-prefixed, hex-encoded number of length 32.) ---> Nethereum.JsonRpc.Client.RpcResponseException: Invalid params: invalid type: integer `120`, expected a 0x-prefixed, hex-encoded number of length 32.
>    at Nethereum.JsonRpc.Client.RpcClient.HandleRpcError(RpcResponseMessage response)
>    at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__12`1.MoveNext()

Note that I'm using version **2.5.1**.

And the method with `new HexBigInteger(120)` has been deprecated?

**Comment by juanfranblanco** [comment]
@StefH there are two ways to unlock for parity or geth, parity still uses hex whilst geth uses a number. In the new version is not deprecated but commented as such.

**Comment by StefH** [comment]
What is the version where this is fixed?
