### ISSUE TITLE
SendTransactionAsync  returns  Problem

### ISSUE THREAD

**Issue by BoyYue** [Nethereum/Nethereum#418]
When I using SendTransactionAsync ,how can I  dealwith  the returns ？  can you give me a detail example  or some  advise?    Thanks !
My Code : 
	BigInteger pss = BigInteger.Parse((price * 1000000000000000000).ToString("0"));
        HexBigInteger ps = new HexBigInteger(pss);	
        var  TxHash = await web3.Eth.TransactionManager.SendTransactionAsync(address,
                                                                                                          PCH.CompanyAddress, 
                                                                                                                                             ps);

 
The TxHash  sometimes is null or  Json rpc error  , I can't get the  correct TxHash what  likes TxHash.IndexOf("0x")        I need the correct TxHash  to send to The Server .  What Can I do? Can you help me?

**Comment by juanfranblanco** [comment]
Apologies for the late response, Transactions do not return any values (you may have figure out this by now). If you have any questions, please go to our gitter channel
