### ISSUE TITLE
No miner, admin, debug methods implementation ?

### ISSUE THREAD

**Issue by Pr0xY** [Nethereum/Nethereum#42]
Hi,

I was just wondering if you're planning to implement methods from the miner, admin and debug modules ?
I need to start miners from my project with RPC.
I guess, for the debug module to work, you're waiting for go-ethereum to implement them as well ?

Thanks for your answer.

Best regards,

Proxy

**Comment by juanfranblanco** [comment]
Yes miner, admin are coming soon, they are part of RC2 (Nethereum), I am moving to netstandard, RC2 (.net) and do a general project structure refactor first.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/issues/35

**Comment by juanfranblanco** [comment]
Debug, yes that will when available
