### ISSUE TITLE
SoliditySha3 of multiple parameters with comparable uint, uint40 etc.

### ISSUE THREAD

**Issue by vindberg** [Nethereum/Nethereum#420]
Hi, first of all great work on the library. Love doing work in csharp again 👍 

Im trying to replicate some web3 javascript logic (that replicates solidity sha3). In javascript I am hashing the following:

`var secretHashMessage = web3.utils.soliditySha3({type: 'uint40', value: currentBlock},{type: 'uint', value: randomNumber});`

In solidity it makes a recover of the hash (using r, and s) and approves the signer. The hash message is generated like this (signed message prefix not shown):

`keccak256(abi.encodePacked(uint40(commitLastBlock), commit)))`

Any ideas on how to do a soliditySha3(obj, obj) with different objects in csharp?

Thanks in advance.

**Comment by juanfranblanco** [comment]
For sha3 examples you can see these here: https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Util/Sha3Keccack.cs

And what you have there is a byte array for solidity encoded types, and then keccak256 them.

So you you could do a Array.Concat(new IntType.Encode(value),new IntType.Encode(value2));

**Comment by vindberg** [comment]
Thanks for the feedback. The first part is working now. However, the signing is showing different behaviour related to the message that is signed if its already hashed.

Eg. this returns the same signature:
javascript: await web3.eth.sign("x999fb", secretSigner);
nethereum: signerTest.EncodeUTF8AndSign("x999fb", new EthECKey(secretSignerPrivateKey));

while this returns different signatures:
javascript: await web3.eth.sign("0x999fb", secretSigner); 
nethereum: signerTest.EncodeUTF8AndSign("0x999fb", new EthECKey(secretSignerPrivateKey));

web3 1.0 beta 36

**Comment by juanfranblanco** [comment]
Yes those are different values.
First one is a string, second one is a hex value (according to Javascript), so you should not encode it as utf8

**Comment by vindberg** [comment]
Thanks again, HexToByteArray worked 👍 on the Sign function. I will close this.
