### ISSUE TITLE
NEthereum does not work in web api and web mvc?

### ISSUE THREAD

**Issue by KlynkC** [Nethereum/Nethereum#422]
I have used NEthereum to call specific function of a smartcontract.
It worked finely in Console Application, but in Web API or Web Application, it dit not response any thing, no error, no warning.
Here is my sample code:
`SmartContractService smartContractService =
                new SmartContractService(BASE_URL, CONTRACT_ADDRESS, ABI, PRIVATE_KEY);

            var contractFunction = smartContractService.GetFunction("updateETHPrice");

            double ethPrice = getRate("eth");
            if (ethPrice > 0)
            {
                BigInteger ethPriceBigInteger = new BigInteger(ethPrice * 1e18);
                //var gas = contractFunction.EstimateGasAsync(ethPriceBigInteger).Result;

                TransactionInput transactionInput = new TransactionInput()
                {
                    From = OWNER_ADDRESS,
                    Gas = new HexBigInteger(4503531),
                    Value = new HexBigInteger(0)
                };

                object[] functionInputs = { ethPriceBigInteger };

                var transactionHash = contractFunction.SendTransactionAsync(
                    input: transactionInput, functionInput: functionInputs).Result;`
The `SendTransactionAsync`  does not response any thing, but, I use
`contractFunction.CallAsync<bool>(someInputValue).Result`, it worked for response.
Can you help me?
Thank you.

**Comment by juanfranblanco** [comment]
Have you tried mark your methods as async?

**Comment by juanfranblanco** [comment]
Closing this, for reference you can see the Faucet as a web application https://github.com/Nethereum/Nethereum.Faucet
