### ISSUE TITLE
Keccak of BigInteger gives different result in Nethereum & Web3js (occationally)

### ISSUE THREAD

**Issue by vindberg** [Nethereum/Nethereum#427]
Hi again @juanfranblanco, hope you can help with this last one.

Occationally im getting a wrong hash using Nethereum. About 5% of the values fail. Here is one that works in Web3.js testing but fails in Nethereum:

Reveal Number: "85642239583440150649809314371044393650949676712536280665332876398878573920820"

Keccak this in web3.js:
`newWeb3.utils.soliditySha3({type: 'uint', value: revealNumber});`
Result: 0x480cf5d7dd311db47fc15ed94f8566296294ad8550820663486c871b4d7aed85

Keccak this in Nethereum:
```
var revealBigInt = BigInteger.Parse(revealNumber);
new Sha3Keccack().CalculateHashFromHex(revealBigInt.ToHex(false, false))
```
Result: 93b39de75346b95dcdddc75cbb7f36b2d3b490a9fb14dbfd9dbc2ce0aca9dc84

Been puzzled with this for several days now. Does it have something to do with the left padding logic? Any ideas are most welcome. Thanks.

**Comment by juanfranblanco** [comment]
@vindberg  I believe this was solved in gitter? I forgot to closed it down.

**Comment by vindberg** [comment]
Hi, I haven't been following gitter closely and can't find a place to search in the group. How was this resolved?

Tx.

**Comment by juanfranblanco** [comment]
and using your values

```javascript
var web3 = require("web3");
var hash = web3.utils.soliditySha3('85642239583440150649809314371044393650949676712536280665332876398878573920820');
```
0x002eb8a4b8507d1c54fc8dcaad4fca90f5fc3e12f9f05716946883218cc294a3

and c#

```csharp

            var solidity = new IntTypeEncoder()
                .Encode(BigInteger.Parse(
                    "85642239583440150649809314371044393650949676712536280665332876398878573920820"));
            var kecckak = new Nethereum.Util.Sha3Keccack();
            var hash = kecckak.CalculateHash(solidity);
            Console.WriteLine(hash.ToHex());
```

002eb8a4b8507d1c54fc8dcaad4fca90f5fc3e12f9f05716946883218cc294a3
