### ISSUE TITLE
Contract Transfer Event From Parity Null Issue

### ISSUE THREAD

**Issue by EmreJoint** [Nethereum/Nethereum#429]
Hi,

I want to filter transfer events from an ERC20 contract using nethereum. My goal is to filter to transfer events that sent to my address from any address. I use for fromaddress parameter null, and toaddress parameter as my address. Here is the code;

`var transferEvent = new StandardTokenService(web3, cur.ContractAddress).GetTransferEvent();
var filter = await transferEvent.CreateFilterAsync<string, string>(null, "0x18c61c016b8b04b651819044f3b7ec42c1fc7322", fromBlock: new BlockParameter(startBlock), toBlock: new BlockParameter(latestBlock));
filterresult = await transferEvent.GetAllChanges<Transfer>(filter);`

That works for geth, but when I use Parity as node provider it gives me error;

> Invalid params: Invalid variadic value type: invalid type: null, expected a 0x-prefixed, padded, hex-encoded hash with length 64.

What is wrong with that?

**Comment by EmreJoint** [comment]
Hi, can you help me with this situation? I have to resolve this for our application.

**Comment by EmreJoint** [comment]
This code resolved my problem.

`var filter = await transferEvent.CreateFilterAsync(filterTopic1: null, filterTopic2: new string[] { systemwallet }, fromBlock: new BlockParameter(startBlock), toBlock: new BlockParameter(latestBlock));`

**Comment by juanfranblanco** [comment]
fantastic, apologies I did not see this issue :)
