### ISSUE TITLE
Indexed Variables On Event Not Being Decoded

### ISSUE THREAD

**Issue by p0onage** [Nethereum/Nethereum#433]
Hi, I'm currently returning back all events with no filter and all the indexed variables are being returned but they are encoded. The other none indexed variables are visible and being retrieved fine and are not encoded.

` fevent.GetAllChanges<TEvent>(filterAll).Result;`

Is this normal practice for indexed variables in events to be encoded? how do I decode this fields?

![image](https://user-images.githubusercontent.com/6472111/46820958-698a1d80-cd7f-11e8-9072-49ddaddba36d.png)

 CampaignId above should be an indexed integer.

**Comment by p0onage** [comment]
There isn't an issue here I simply can't do this.

Indexed topics don't contain the unhashed values. searching for the CampaignId you're interested in and filter for that works but I now realise you can't convert from a topic back to the original input.

**Comment by p0onage** [comment]
Looking back into this, it should work as there is an example of doing this call on the NEtherium examples when asserting the MultiplicationInput equals 1? https://nethereum.readthedocs.io/en/latest/contracts/calling-transactions-events/

**Comment by juanfranblanco** [comment]
Check this workbook might help you https://github.com/Nethereum/Nethereum.Workbooks/blob/master/docs/nethereum-events-gettingstarted.workbook

**Comment by juanfranblanco** [comment]
I think your issue is that you are trying to index an string, that will be indexed using a hash. You will need to use a bytes32, or include it in the data.

**Comment by p0onage** [comment]
@juanfranblanco you're right thank you. The string was being indexed as a Hash. changing this variable to an integer returned back an unhashed result
