### ISSUE TITLE
Import HD addresses in watch-only mode

### ISSUE THREAD

**Issue by izzycoder18** [Nethereum/Nethereum#434]
I see that NEthereum is BIP32 compatible.

How to generate (derive) addresses from the public key?

Also, once the addresses have been derived, is it possible to monitor transactions incoming on these addresses in Watch-Only mode?

**Comment by juanfranblanco** [comment]
@izzycoder18 you cannot at the moment derive using the public key, you could using NBitcoin directly but I need to add this capability yet.

If you look at the Blockchain Storage there is currently some work around this

**Comment by izzycoder18** [comment]
Thanks for your reply. 
Any estimate about when are you going to add this functionality in NBitcoin?

Also, you referred to "blockchain storage", can you please be more specific? 

Thanks in advance.

**Comment by izzycoder18** [comment]
@juanfrancoblanco , thanks for your reply. Any idea when the next released will be published?

**Comment by izzycoder18** [comment]
Any update on this matter?
If I have an xpub key , is there a way to derive addresses from that key using NEthereum?

I know NBitcoin can derive addresses across multiple coins, any idea how to do this in NEthereum for different tokens?

**Comment by pingec** [comment]
Hey!

Any news about this feature? (deriving hd addresses and watching the balances)?

If the moving pieces are already there and it is just a matter of using them correctly, could anyone kindly provide the links?

**Comment by juanfranblanco** [comment]
@pingec you can do this already, the issue was how to do this using a public key as opposed to the seed or mnemonic. Still at the moment if asking for the former is to use Nbitcoin directly and then use EthEcKey with the public key to get the address.

**Comment by pingec** [comment]
Alright, thanks for the info, indeed I was asking for the former.
