### ISSUE TITLE
Extract contract abi example

### ISSUE THREAD

**Issue by skostic9242** [Nethereum/Nethereum#436]
Hi, 

could you please provide me with some example of how to get contract without compiling it first, i noticed there is method:

public Contract GetContract<TContractMessage>(string contractAddress)
        {
           return new Contract(this, typeof(TContractMessage), contractAddress);
        }

How to model ABI with TContractMessage? 

Cheers

**Comment by juanfranblanco** [comment]
@skostic9242  If you know what your abi is going to look like, well mainly you have agreed to some interface, you can create a FunctionMessage per Function.

Similar to this: https://github.com/Nethereum/Nethereum.CQS.SimpleTokenTransfer/blob/master/Nethereum.CQS.SimpleTokenTransfer/Program.cs#L151-L159

**Comment by juanfranblanco** [comment]
Per message you have a class, this can be code generated for you from the abi in Solidity, we also generate a Service for this to have a simple wrapper for each message. Each message is a partial class so you can add validation, custom functionality.

If you work up front (ie don't know about the solidity side yet, but you have an agreement on the inferface) yes you will create a message per function, similar as to designing protobufs or a CQS message. Although if you have 10 functions, probably easier to type an interface solidity and generate it from there, as you will end up typing less. 

Having a service wrapper, it is a matter of taste and separation of concerns, as you introduce multiple signatures / proxies etc you will work more with the function message than the service side (well that is my take on it :) )

**Comment by skostic9242** [comment]
Yes, i see now how i can generate this messages from ABI :)

But to invoke GetContract<TContractMessage> i need to specify this generic type, what would that be if my abi consists of 10 functions? Sorry if I misunderstood something...

**Comment by juanfranblanco** [comment]
It will look something like this https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.StandardTokenEIP20/ContractDefinition/StandardTokenDefinition.cs

and you can have a service like this
https://github.com/Nethereum/Nethereum/blob/7714186a6fa8d0a085e340ebde29afe84eeef0ea/src/Nethereum.StandardTokenEIP20/StandardTokenService.cs

All this can be generated, although you can do as simple as function itself.

**Comment by skostic9242** [comment]
Thanks again :)
