### ISSUE TITLE
Nethereum && infura

### ISSUE THREAD

**Issue by keepbreath** [Nethereum/Nethereum#438]
hello,juan
new web3("https://ropsten.infura.io/my-api-key");
An exception occurs when I execute the following sentence
> var sendTxHash = await web3.Eth.TransactionManager.SendTransactionAsync(fromAddr, toAddr, token);
Exception :
> Nethereum.JsonRpc.Client.RpcClientUnknownException:“Error occurred when trying to send rpc requests(s)”
> HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).

thanks and respect(QAQ)

**Comment by juanfranblanco** [comment]
@keepbreath  To interact with a public node like Infura you need your Account with a privateKey, this will sign the transactions "offline" before they are sent to Infura.

Check https://nethereum.readthedocs.io/en/latest/accounts/

**Comment by keepbreath** [comment]
Hello,juan:
Excuse me,I want to ask some questions about mnemonic words,How to generate mnemonic words with Nethereum and BIP39?When I introduced the BIP39 NuGet package, "Nethereum. Signer. EthECKey" will throw exceptions like "failed to initialize".
I wish to express my gratitude once again(^_^)！

**Comment by juanfranblanco** [comment]
Use Nethereum.HdWallet, it uses NBitcoin for it  :) There is a workbook for this here https://github.com/Nethereum/Nethereum.Workbooks/blob/master/docs/nethereum-hdwallet-infura-transfer.workbook
