### ISSUE TITLE
Multiple deployments of smart contracts at the same time

### ISSUE THREAD

**Issue by skostic9242** [Nethereum/Nethereum#439]
Hi,

We are trying to deploy multiple contract at the same time, using one account, and we are getting error because while one deployment is pending, next deployment transaction will get same transaction nonce and deployment would be rejected. Is there some built in way in Nethereum to prevent this? I saw InMemoryNonceService which we can associate with account to solve this problem, is this only solution?

Cheers, and thanks in advance,
Stefan

**Comment by juanfranblanco** [comment]
If you use the same instance of Web3 that maintains an in memory counter of nonces, so that will solve your problem.

**Comment by skostic9242** [comment]
Do we maintain memory counter using InMemoryNonceService, or we do it ourselves? Does Web3 have its own memory counter?

**Comment by skostic9242** [comment]
Cool, will try it out, thank you very much.

**Comment by skostic9242** [comment]
Out of curiosity, because I read a bit of source code, could you please give me short guidance where this maintaining of nonce is happening in Web3?

**Comment by juanfranblanco** [comment]
When you create an Account the InMemoryNonceService is created.
