### ISSUE TITLE
Enable Build Service

### ISSUE THREAD

**Issue by raymens** [Nethereum/Nethereum#44]
There are many free build services around (like AppVeyor & Travis-ci). Enabling one also gets the project closer to implementing CI.

**Comment by juanfranblanco** [comment]
Good idea, I am porting to RC2, then I will do automating building. Sadly most of the stuff relies on integration testing which I want to refactor.

**Comment by juanfranblanco** [comment]
So automated testing won't be possible (finishing the sentence)

**Comment by raymens** [comment]
Automated building is a start, right. Integration tests can be something for the future.

**Comment by juanfranblanco** [comment]
yes of course, but most of the real tests, depends on a geth instance... hence not simple. But possible if having a server which can be reset with a custom chain.

**Comment by bobsummerwill** [comment]
Hey @juanfranblanco,

See https://gitter.im/ethereum/solidity?at=5793d149b92e27447fa6a01c

We've recently switched the Solidity tests to run with an IPC connection to an `eth` instance, where we have added a `test` mode recently.

Maybe you could run your tests against `eth` instead?

We have this running in TravisCI already, and the only think stopping this working on Appveyor for Windows build is that we don't have the IPC sockets bit implemented on the Solidity tests side yet.    You would have all this already, of course:

See

- https://travis-ci.org/bobsummerwill/solidity/builds/145735343
- https://ci.appveyor.com/project/bobsummerwill/solidity/build/0.3.6.144

And:

- https://github.com/bobsummerwill/solidity/blob/standalone_prior_to_splat/scripts/install_deps.sh#L300
- https://github.com/bobsummerwill/solidity/blob/standalone_prior_to_splat/scripts/install_deps.sh#L89

**Comment by juanfranblanco** [comment]
Many thanks @bobsummerwill  Ill have a look

**Comment by juanfranblanco** [comment]
There is a CI service now
