### ISSUE TITLE
Set up {projectDir}/buildConf/Frameworks.props file properly to support different work environments

### ISSUE THREAD

**Issue by paveldz** [Nethereum/Nethereum#441]
Set up _{projectDir}/buildConf/Frameworks.props_ file properly to support different work environments.

**Issue:**     
My work environment is Ubuntu 18.04 + JetBrains Rider 2018.2.3. I would like to work with Nethereum repository but I can't because of `<TargetFrameworks>` values in `csproj` files of each repository.    
    
Currently most not-test projects have value of `<TargetFrameworks>` equal to variable `$(DefaultFrameworksUnitySupport)` from _{projectDir}/buildConf/Frameworks.props_. This value includes `net451` that means .NET Fraemwork that is supported only by Windows.

Also most of projects with tests have hardcoded values of `<TargetFrameworks>` (there are no references to some variables from config file). Looks like all of them include dependency to .NET Framework.

**Therefore, to start work in Nethereum repository using not Windows I need:**
1) Figure out what's going on and why I can't build the solution :)
2) Change a lot of `csproj` files and `{projectDir}/buildConf/Frameworks.props` file

**Solution:**    
Set up _{projectDir}/buildConf/Frameworks.props_ file properly and change 'csproj' files once in each repository. Values `<TargetFrameworks>` of each `csproj` file should depend on variables from _{projectDir}/buildConf/Frameworks.props_.

Please correct me if my understanding is wrong.

**Comment by paveldz** [comment]
Looks like a lot of work has been done in this direction as there are different variables in _{projectDir}/buildConf/Frameworks.props_ file, but this work hasn't been completed properly. 
Could you also explain why `$(DefaultFrameworksUnitySupport)` is default value of most of `csproj` files. It seems to me that `<DefaultFrameworks>` variable should be in these places.

**Comment by juanfranblanco** [comment]
To build Nethereum, you have to build the UnityLibraries, and build .net451 etc. So the ideal working enviroment is Windows. So the overall idea is to continuely support all the frameworks including 3.0 for Unity3d even if is moving towards netstandard, net461. Same for Nethereum.Portable.

**Comment by juanfranblanco** [comment]
I fully understand that is frustrating if you want to build from scratch in Ubuntu, Mac etc and using other editors, but the idea is that all contributions should build in all environments.

**Comment by juanfranblanco** [comment]
@paveldz  if you check the latest, you could work setting the netstandard flag, for most of the projects.

**Comment by mrwillis** [comment]
Is there no way to completely build this project on non-Windows?
