### ISSUE TITLE
Nethereum.JsonRpc.Client.RpcClientUnknownException

### ISSUE THREAD

**Issue by Hanwang107** [Nethereum/Nethereum#444]
Weired problem happened **sometimes** after first line of code

```
var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(functionHashes);
// Monitor the progress of the transaction
while (receipt == null)
{
      Thread.Sleep(100);
      receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(functionHashes);
 }
```
Error:

> WebApplicationTest.Controllers.SolidityController.CallFunction (WebApplicationTest) in 6213.4256ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response

**Comment by juanfranblanco** [comment]
@Hanwang107  this will be due to a failing connection to the rpc client

**Comment by Hanwang107** [comment]
Thank you for your reply!

It is a little hard to detect the issue. The frequency is like half of the times. 
The app is connecting a Kaleido node.

**Comment by juanfranblanco** [comment]
@Hanwang107 the best way to support Kaleido is to contact them directly, let me know if you need any a way to contact them.

**Comment by dbryan0516** [comment]
Hey @Hanwang107! If this is still an issue, would you mind making a ticket by sending an email to support@kaleido.io ?
