### ISSUE TITLE
Nethereum.StandardTokenEIP20 - GetBalanceOfAsync

### ISSUE THREAD

**Issue by ladinek82** [Nethereum/Nethereum#445]
Hi, 

I have tried to read balance of token. I use .NET 4.6.1. I created very simple code. This is part of console application. 
```
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;
var service = new Nethereum.StandardTokenEIP20.StandardTokenService(new Web3("https://ropsten.infura.io:8545/"), "0x037e66b59c884753cf701372c8e243cc213ba052");
var balance = service.GetBalanceOfAsync<System.Numerics.BigInteger>("0xa039C49dDaF1c8362218F54BDE4948e4859FC578").Result;
var value = Web3.Convert.FromWei(balance, 18).ToString();
lAccountBalance.Text = value.ToString();
```
If I run the program, I will never get response.  The line "service.GetBalanceOfAsync(...)" is never ended. 
Here is my account and token: [https://ropsten.etherscan.io/token/0x037e66b59c884753cf701372c8e243cc213ba052?a=0xa039C49dDaF1c8362218F54BDE4948e4859FC578](url)

Thank you for help.

**Comment by juanfranblanco** [comment]
Can you post your whole project? That should not happen as you are calling Result.

**Comment by ladinek82** [comment]
It is very strange, I created two applications one console and one WinFroms and the console app works and winforms app doen't work. The code is same.

All values are hardcoding in the C# code. Please, ignore UI and values within. If you click on button Load Tokens, you run the problematic code.
Here is:
[ConsoleApplication1.zip](https://github.com/Nethereum/Nethereum/files/2510450/ConsoleApplication1.zip)
[WFA_Nethereum01.zip](https://github.com/Nethereum/Nethereum/files/2510451/WFA_Nethereum01.zip)

**Comment by juanfranblanco** [comment]
Thanks I will test it next week, it might be an issue on threading.

**Comment by ladinek82** [comment]
Hi, did you have time to check the codes?

**Comment by juanfranblanco** [comment]
Hi apologies I was in Devcon4 so no time for anything, ill check it now / today.

**Comment by juanfranblanco** [comment]
I have upgraded it to 3.0.0-rc3 and ran it like this.. and no issues 

```csharp
public partial class Form1 : Form
	{
		public Form1()
		{
			System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;

			InitializeComponent();


			tbAccountNumber.Text = "0xa039C49dDaF1c8362218F54BDE4948e4859FC578";
			tbAccountKey.Text = "a578b83a08eb0155f5130843621d5883ab5ed1ae9eba7d64dd9a3c89ee50e8ae";

			tbRFCUrl.Text = "https://ropsten.infura.io";
		}

		private async void bRefreshBalance_Click(object sender, EventArgs e)
		{
			var account = new Account(tbAccountKey.Text);
			var web3 = new Web3(account, tbRFCUrl.Text);
			var balance = web3.Eth.GetBalance.SendRequestAsync(tbAccountNumber.Text).Result;
			var value = Web3.Convert.FromWeiToBigDecimal(balance);
			lAccountBalance.Text = value.ToString();
		}

		private void bLoadTokens_Click(object sender, EventArgs e)
		{
			System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;
			var service = new Nethereum.StandardTokenEIP20.StandardTokenService(new Web3("https://ropsten.infura.io"), "0x037e66b59c884753cf701372c8e243cc213ba052");
			var balance = service.BalanceOfQueryAsync("0xa039C49dDaF1c8362218F54BDE4948e4859FC578").Result;
			var value = Web3.Convert.FromWei(balance, 18).ToString();
			var strValue = value.ToString();
			lTokenBalance.Text = strValue;

		}
	}

```

**Comment by juanfranblanco** [comment]
Let me know how it goes, closing it for now. And apologies again hectic weeks.

**Comment by ladinek82** [comment]
I understand, but it works now. 
Thank you very much.

**Comment by luckymancvp** [comment]
Dear  ladinek82 I've faced same problem as  you. 

I run sample code in winform .net4.6.1 and code never done in async, nothing showed up

But when I create new console project. It worked .

I dont understand why. But I need run in winform. Can you tell me
