### ISSUE TITLE
Feature request: Event query return block number

### ISSUE THREAD

**Issue by codyborn** [Nethereum/Nethereum#446]
By having the block number returned in the metadata of an event object, we can better track the events that we've already seen in our stateless service.

**Comment by juanfranblanco** [comment]
Included and refactored here: https://github.com/Nethereum/Nethereum/commit/a82654252a29ded03adbce206aad224899ed9df1

Now each List<ParameterOuput> is part of the EventLog. The Log includes all the information needed.
