### ISSUE TITLE
Nethereum && BIP39

### ISSUE THREAD

**Issue by keepbreath** [Nethereum/Nethereum#447]
hello,juan:
  Your framework is great, but I've had some problems using it.I wanted to use BIP39 to generate the mnemonic word of ethereum, but it would throw an exception of "failed to load a file or assembly" bouncycastle.crypto, Version=1.7.4771.41295, Culture=neutral, PublicKeyToken=null "or one of its dependencies.The assembly manifest definition found does not match the assembly reference".
  Can you tell me how to solve it or what better way to do it?Thank you very much!

**Comment by juanfranblanco** [comment]
You can use the Nethereum.HdWallet for that..it uses NBitcoin internally
