### ISSUE TITLE
[Question] Is there anything equivalance to "getPastEvents"(web3) in Nethereum?

### ISSUE THREAD

**Issue by futouyiba** [Nethereum/Nethereum#449]
Fu Song, [2018年10月26日 下午4:52:49]:
...When I try to get a list of history events of a contract, in web3 I can do "getPastEvents". 
What about in Nethereum?

example: 
```
cryptoZombies.getPastEvents("NewZombie", { fromBlock: 0, toBlock: "latest" })
.then(function(events) {
  // events is an array of event objects that we can iterate, like we did above
  // This code will get us a list of every zombie that was ever created
});
```

**Comment by juanfranblanco** [comment]
Check this document https://nethereum.readthedocs.io/en/latest/nethereum-events-gettingstarted/

**Comment by futouyiba** [comment]
> Check this document https://nethereum.readthedocs.io/en/latest/nethereum-events-gettingstarted/

Thank you. I checked this doc before I asked,  nothing related was found. Maybe there is a chance I missed it.

**Comment by juanfranblanco** [comment]
From the doc
```csharp
[Event("Transfer")]
public class TransferEventDTO : IEventDTO
{
    [Parameter("address", "_from", 1, true)]
    public string From { get; set; }

    [Parameter("address", "_to", 2, true)]
    public string To { get; set; }

    [Parameter("uint256", "_value", 3, false)]
    public BigInteger Value { get; set; }
}

var transferEventHandler = web3.Eth.GetEvent<TransferEventDTO>(contractAddress);
var filterAllTransferEventsForContract = transferEventHandler.CreateFilterInput();
var transferEventsForContractAllReceiverAddresses = await transferEventHandler.GetAllChanges(filterAllTransferEventsForContract)
```

When you call CreateFilterInput you can pass as a parameters "fromBlock" and "toBlock"

**Comment by futouyiba** [comment]
> From the doc
> 
> ```cs
> [Event("Transfer")]
> public class TransferEventDTO : IEventDTO
> {
>     [Parameter("address", "_from", 1, true)]
>     public string From { get; set; }
> 
>     [Parameter("address", "_to", 2, true)]
>     public string To { get; set; }
> 
>     [Parameter("uint256", "_value", 3, false)]
>     public BigInteger Value { get; set; }
> }
> 
> var transferEventHandler = web3.Eth.GetEvent<TransferEventDTO>(contractAddress);
> var filterAllTransferEventsForContract = transferEventHandler.CreateFilterInput();
> var transferEventsForContractAllReceiverAddresses = await transferEventHandler.GetAllChanges(filterAllTransferEventsForContract)
> ```
> 
> When you call CreateFilterInput you can pass as a parameters "fromBlock" and "toBlock"

Thank you Juan, that's the perfect answer!
