### ISSUE TITLE
IPC broken using geth 1.4+

### ISSUE THREAD

**Issue by raymens** [Nethereum/Nethereum#45]
RPC over IPC doesn't work using geth 1.4+ and the latest Nethereum. The version releases do have a mention of a reworked RPC system that might be the issue. It seems the IPC calls don't receive any response and is `await`ing endlessly.

RPC over HTTP still works fine.

**Comment by juanfranblanco** [comment]
Yes there are lots of issues with 1.4.4.

**Comment by juanfranblanco** [comment]
It should be fixed now
