### ISSUE TITLE
Sending Ether using default gas amount: GetEtherTransferService

### ISSUE THREAD

**Issue by bogos** [Nethereum/Nethereum#450]
When I follow the example of https://nethereum.readthedocs.io/en/latest/nethereum-transferring-ether/#sending-ether-with-nethereum 
### Sending Ether using default gas amount:
I get the following error. I have already installed the Web3 Nugget. There is no GetEtherTransferService method in Web3.Eth

![image](https://user-images.githubusercontent.com/2405388/47593419-ec44d800-d93c-11e8-9922-b85d16163dbc.png)

Error	CS1061:	'EthApiContractService' does not contain a definition for 'GetEtherTransferService' and no accessible extension method 'GetEtherTransferService' accepting a first argument of type 'EthApiContractService' could be found (are you missing a using directive or an assembly reference?)	NethereumCore

**Comment by juanfranblanco** [comment]
@bogos you need Nethereum 3.0.0 rc3 for this. If you are using visual studio make sure you check the tick box when downloading the nugets to include pre releases

**Comment by bogos** [comment]
@juanfranblanco you're right! :) my bad! thank you a lot!
