### ISSUE TITLE
Cannot communicate with the testchain Geth

### ISSUE THREAD

**Issue by jkourakos** [Nethereum/Nethereum#452]
I have downloaded the "Nethereum-master" and from testchain i run the  startgeth.bat . The command promt opens and i can see that the test chain has been started. Also if i type eth.accounts i can see the acounts that are running. Now i open visual studio 2017 and create a new web forms project. I have add all the libraries you provide in the video https://www.youtube.com/watch?v=4t5Z3eX59k4&list=PL4KrqfhCMJhRVz-hJ83SqFkxJQF7Iac8v 
Then i am creating inside the project a folder named "contracts". Then i open this folder with the visual studio code and type the bellow smart contract:
       `contract MasterContract{
    
    struct Patient
    {

        uint Id;
        uint Numberoforigin;
        string FirstName;
        
      
          
    }
    
    //mapping(uint => Patient) public patientslist;

    uint public patientsCount;
    Patient[] public itemArray;

    

    
    function addUser(uint _Id, uint _Numberoforigin, string _FirstName) public returns(uint) {
        itemArray.length++;
        itemArray[itemArray.length-1].Id = _Id;
        itemArray[itemArray.length-1].Numberoforigin = _Numberoforigin;
        itemArray[itemArray.length-1].FirstName = _FirstName;
        
        return itemArray.length;
    }

    function getUsersCount() public constant returns(uint) {
        return itemArray.length;
    }

    function getUser(uint index) public constant returns(uint, uint, string) {
        return (itemArray[index].Id, itemArray[index].Numberoforigin, itemArray[index].FirstName);
    }
    

    }`
 I compile with f5 without error and i am getting the abi and the bytecode. I am normalize the abi ("=>"") and i am creating the bellow c# function that compiles without errors:

       ` private async Task<int> MethodName(int thenum)
        {
            var senderAddress = "0x12890d2cce102216644c59daE5baed380d84830c";
            var password = "password";
            var abi = ...;
            var byteCode =...;
           var web3 = new Web3Geth();
            var unlockAccountResult = await 
            web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 120);
            Assert.True(unlockAccountResult);
            web3.TransactionManager.DefaultGas = BigInteger.Parse("290000");
            web3.TransactionManager.DefaultGasPrice = Transaction.DEFAULT_GAS_PRICE;
            var transactionHash = await web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, 
               senderAddress);
                var mineResult = await web3.Miner.Start.SendRequestAsync(6);
               var receipt = await 
              web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
            while (receipt == null)
            {
                System.Threading.Tasks.Task.Delay(5000).Wait();
                receipt = await 
       web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);

            }
            var contractAddress = receipt.ContractAddress;
            var contract = web3.Eth.GetContract(abi, contractAddress);
            var addPatientFunction = contract.GetFunction("addUser");
            var getPatientCountFunction = contract.GetFunction("getUsersCount");
            var gettheUserFunction = contract.GetFunction("getUser");
            // var result = await multiplyFunction.CallAsync<int>(thenum);
            var result_user = await gettheUserFunction.CallAsync <(int, int, string)>(1);
            var result_count = await getPatientCountFunction.CallAsync<int>();
            int myres = Convert.ToInt32(result_count);
            var result = await addPatientFunction.CallAsync<int>(myres,36, "giannis");
            return Convert.ToInt32(result);//Note we return int not Task<int> and that compiles
        }`

The issue is that never stores anything to the blockchain and always i get 0 itemArray.length  and 0 getUser. I have test the smart contract on remix(without connecting it with my local nethereum project and is working normally.

**Comment by juanfranblanco** [comment]
Hi the contract may have not been deployed correctly, if you tried web3.Eth.GetCode.SendRequestAsync and pass your contract address, this will return you the bytecode deployed. If it returns null or 0x mainly there was a deployment failure. Which may have been lack of gas, passed on the transaction.

**Comment by juanfranblanco** [comment]
To get around that, you can estimate your gas before you make the deployment or any transaction call, another option will be to provide your own gas amount as you have already. (Assuming that is that the issue).

**Comment by juanfranblanco** [comment]
Also if you are going to run a testchain, use the one in the clique folder, or one of these https://github.com/Nethereum/TestChains. These ones don't need to control the mining process as they start mining. Also using a PoA consensus they are far much faster.

**Comment by jkourakos** [comment]
Holla, gracias por la ayuda.
I have added bellow the line:
var contract = web3.Eth.GetContract(abi, contractAddress);
the line:
var testme = web3.Eth.GetCode.SendRequestAsync(abi, contractAddress);
so if i quick watch the testme i am getting the below values:
testme	Id = 285, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"	System.Threading.Tasks.Task<string>
Thank you,
muchos saludos por de Grecia

**Comment by juanfranblanco** [comment]
hi,
You did not get any result for this, as you need to await it.

```
var testme = await web3.Eth.GetCode.SendRequestAsync(contractAddress);
```

you will get a user count of 0, as I believe you have not added any user.

Also I don't know if it will help to follow this guide.

https://nethereum.readthedocs.io/en/latest/nethereum-smartcontrats-gettingstarted/
and this
https://nethereum.readthedocs.io/en/latest/nethereum-code-generation/
