### ISSUE TITLE
Is there any way to use nethereum on c++?

### ISSUE THREAD

**Issue by hapsody** [Nethereum/Nethereum#453]
Hi, I'm just ethereum blockchain dapp developer wanting to use Nethereum in Korea.
I have a team and we're developing PC App on MFC.
It's gotta communicate with local geth client offered to user's local PC, and Thankfully I think 'Nethereum' may be an answer.

but as I mentioned, we're developing with c++ and we can't use this module directly for our project.
I was trying to find the way to use .net framework dll. I made some C# code and made dll to use on c++
but C# dll used on c++ couldn't async methods. I've checked many way, but it couldn't. we can't end up keep going with C++, if there's no way to use nethereum.

Is there any way to use Nethereum module on c++? or is there any other non-async available methods instead of async methods?

**Comment by juanfranblanco** [comment]
You should be able to use the encoders / decoders and craft your own rpc methods which are the ones that use async, Ill have a look for interoperabity of async and c++.

**Comment by juanfranblanco** [comment]
Although have you thought about creating something like a service layer wrapping your contract interaction (or whatever functionality, using something like Result) and from there creating Exports to consume it directly?

**Comment by hapsody** [comment]
No I haven't. But If I should, I will.
I'm thinking of using jsonRPC communication method like curl. 
it would be easier i thought.

**Comment by juanfranblanco** [comment]
@hapsody I am closing this now, but let me know how it goes and feel free to post a sample !
