### ISSUE TITLE
Find information about ERC20 tokens

### ISSUE THREAD

**Issue by keepbreath** [Nethereum/Nethereum#454]
Hello Juan
  Are you ok recently? I am Yuan,I need your help to solve some problems.
  Which module of Nethereum can obtain complete information of ERC20 tokens according to the symbol name of the token or the contract address?
  Such as "http:/api.ethplorer.io/getTokenInfo/YourContractAddress?apiKey=freekey",But this API only implements the search by contract address.  
  Thank you for your help~！QAQ

**Comment by juanfranblanco** [comment]
Hi @keepbreath  you can connect directly to infura or any node using this module.
https://www.nuget.org/packages/Nethereum.StandardTokenEIP20/3.0.0-rc3
Some usage can be found here https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.StandardTokenEIP20.IntegrationTests/Erc20TokenTester.cs#L72

You should not be able to find it by "name" as there is not index on the chain for that.

**Comment by keepbreath** [comment]
@juanfranblanco ,hah...，Oh,Thank you,Do you know if there is a special library to store Ethereum tokens?Such as the "https://etherscan.io/" search function ,
![1](https://user-images.githubusercontent.com/30484691/47763548-24149c80-dcfc-11e8-89ce-f15087832dcd.png)
Thank you again!

**Comment by juanfranblanco** [comment]
@keepbreath Apologies for the late response, no there is not any, we could in Nethereum list tokens with addresses like EOS as part of the library. But that may bring other issues, like corroborating right addresses etc.

**Comment by juanfranblanco** [comment]
I am keeping this open for further thought.

**Comment by keepbreath** [comment]
oh,It doesn't matter,thank you for your reply,I will always keep an eye on the Nethereum, thank you!

**Comment by juanfranblanco** [comment]
After further thought I don't think Nethereum should list ERC20 tokens, but ideally there should be a generic registry + ENS.
