### ISSUE TITLE
Custom data string in send Ether transaction

### ISSUE THREAD

**Issue by MANOJKUMARCH** [Nethereum/Nethereum#455]
As part of the web3.eth.sendRawTransaction we have a "data" field in the transaction where we can give our  inputs. 

Do we have anything of such field in Nethereum where we can send some data in a transaction of sending Ether. I need it to check the data for the reconciliation of the transactions. 

Below is the tx data as per web3.js documentation
var rawTx = {
 nonce: '0x00',
 gasPrice: '0x09184e72a000', 
 gasLimit: '0x2710',
 to: '0x0000000000000000000000000000000000000000', 
 value: '0x00', 
 **_data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'_**
}

**Comment by juanfranblanco** [comment]
@MANOJKUMARCH  apologies for the late response.

If you use the web3.Eth.TransactionMananager.SendTransaction this accepts the TransactionInput that contains the data field, or as you have described web3.Eth.SendRawTransaction.SendRequestAsync ..
