### ISSUE TITLE
EtherDelta: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by GoldRat** [Nethereum/Nethereum#457]
I have 0.0011 ETH on Wallet and 0.008 ETH on EtherDelta address. I try to buy 0.06 PPT for 0.001610000000000002 ETH, but receiving this error. I use [this](https://github.com/etherdelta/bots/tree/master/dotnet) example and didn't change the default values: GasPrice = 1000000000, GasLimit = 250000 and etherdelta.json and token.json are the same. I tried from v 2.5.1 to v.3.0.0-rc3. Please help.

**Comment by juanfranblanco** [comment]
@GoldRat  apologies I did not see this issue. This is the first time I have seen the bot for EtherDelta, which looks rather good btw :).  The truth the best person to contact is the bots creators, as it might be that the Ether used is the one in your Wallet as you are trying to send 0.001610000000000002. But this is a random guess.

**Comment by GoldRat** [comment]
Thank you for the answer. You are the only person who answered (among those I asked, including the creator of the bot). Could the error be due to the wrong GasPrice and GasLimit? What should they be in my case and how to calculate them correctly later?

**Comment by GoldRat** [comment]
Sorry,  what chain do you mean and which one should be right for this case? 

I wrote also there:
[https://github.com/etherdelta/etherdelta.github.io/issues/563](https://github.com/etherdelta/etherdelta.github.io/issues/563)
[https://github.com/etherdelta/bots/issues/28](https://github.com/etherdelta/bots/issues/28)


Here is the debug screenshot before order opening:
![image](https://user-images.githubusercontent.com/40100507/48965016-c9522600-efc5-11e8-9ed3-fc24053810bf.png)

..and the next step is:
![image](https://user-images.githubusercontent.com/40100507/48965021-de2eb980-efc5-11e8-9a85-d830ddcbb9ed.png)

**Comment by juanfranblanco** [comment]
Apologies I have not had time to look at the bot code, the rpc error indicates you don't have enough funds, so it has to be due to the configuration. 

Nevertheless closing this now, if there are still any problems and furhter thoughts, please reopen.
