### ISSUE TITLE
Stranger Things Happen

### ISSUE THREAD

**Issue by keepbreath** [Nethereum/Nethereum#458]
Hello Juan:
  I think I have another problem and need your help,For the same code that was executed successfully in the winform program, I was told in the WebAPI that the RPC request had failed!
  Here's a screenshot of the problem:
![1](https://user-images.githubusercontent.com/30484691/48538573-ca14f900-e8ef-11e8-8882-2cefb3a5e4b9.png)
![2](https://user-images.githubusercontent.com/30484691/48538575-cb462600-e8ef-11e8-8a82-aa18e6111f87.png)
  This is my example of web3(Web3 web3=new Web3("https://ropsten.infura.io/v3/2475024b5.......c4cc326c"))!Thanks in advance.

**Comment by juanfranblanco** [comment]
@keepbreath  so your issue is now in a webapi, what are you using .Net core? Can you post the sample again? That worked well last time ;)
