### ISSUE TITLE
DecodeAllEventsForEvent Can't decode uint256 with large number

### ISSUE THREAD

**Issue by mozheanquan-qiuhuadong** [Nethereum/Nethereum#460]
event TestEvent(address from, address to, uint256 id);
Just like this event, with a large id, for example 0x8000000000000000000000000000000100000000000000000000000000000001
The function(Nethereum.Contracts.Event.DecodeAllEventsForEvent) throw exception: Value was either too large or too small for an Int32.

**Comment by juanfranblanco** [comment]
@mozheanquan-qiuhuadong does your event in .Net have an Int32 instead of a BigInteger?

**Comment by mozheanquan-qiuhuadong** [comment]
@juanfranblanco Int32 is too small, so i must use BigInteger.
The strange thing is, when i use Nethereum.Contracts.Event.DecodeAllEventsForEvent to decode another event, all is OK.

The event throw exception:
event LogAddFile(
        address indexed from,
        address indexed to,
        bytes32 fileHash,
        uint256 id
    );

The event OK:
event Transfer(
    address _spender, 
    address indexed _from, 
    address indexed _to, 
    uint256 indexed _id, 
    uint256 _value);

All events has uint256 type.

**Comment by juanfranblanco** [comment]
I believe this was covered in gitter, if not apologies for the late response. The problem seems to be due to your index definition in your contract definition.

Closing this now, if there are still any problems please reopen, or better please ask in gitter.
