### ISSUE TITLE
Lack of signature response verification

### ISSUE THREAD

**Issue by edeharo** [Nethereum/Nethereum#461]
At leas for a Ledger wallet, when the signature request fails, for example, when you reject the transaction (left button on a Nano S) instead of confirm it, the response is not succeeded causing a NullReferenceException when LedgerExternalSigner.cs tries to build the Signature representation.

```
var response = await LedgerManager.SendRequestAsync<EthereumAppSignatureResponse, EthereumAppSignatureRequest>(firstRequest);
            
var signature = ECDSASignatureFactory.FromComponents(response.SignatureR, response.SignatureS);
signature.V = new BigInteger(response.SignatureV).ToBytesForRLPEncoding();
```

**Comment by juanfranblanco** [comment]
Thanks @edeharo, great point. I will throw an specific exception there.
