### ISSUE TITLE
Connecting Nethereum to own node

### ISSUE THREAD

**Issue by jnaneshkumar09** [Nethereum/Nethereum#463]
Hi Friends,

I am new to Blockchain, I did some workaround in nethereum library it was helpful . But i am unable to find the way to connect to our own node and generate a new address from our own node.I can find some examples how to get the balance of address but not to generate new address from own node.  
These are the below  thing i am looking for

1.How to connect to own node with Nethereum library ?
2.How to Generate a new address from that node ? 
  
Thanks..

**Comment by Enigmatic331** [comment]
Hi @jnaneshkumar09 - You can refer to the link: https://nethereum.readthedocs.io/en/latest/accounts/

When you have a local Geth node, by default it runs on port 8545, so you could connect to it with something like `Dim iweb3 = new Web3("http://localhost:8545")`. Likewise for Infura, just replacing the URL with Infura's provided URL and API token.

More examples: https://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstarted-testchain/

Come join us on our Gitter channel - https://gitter.im/Nethereum/Nethereum - I think questions get noticed faster there.
