### ISSUE TITLE
Need help to connect with MetaMask using NEthereum in asp.net

### ISSUE THREAD

**Issue by pravinchalke** [Nethereum/Nethereum#464]
Hello All,

I am trying to connect/inject MetaMask using NEthereum and ASP.Net but unfortunately still I haven't received any success.

Using Below Tools:
Visual Studio 2015(ASP.Net & VB.Net)-C# Code also fine for me
Nugets Packages
BouncyCastle 1.8.2
Nethereum 2.5.1

It will be good if you will help with this.

Thanks in advance.

**Comment by knocte** [comment]
> unfortunately still I haven't received any success.

This is not very specific. Please explain more details about your problem. Thanks

**Comment by juanfranblanco** [comment]
Closing now.
