### ISSUE TITLE
Decode input data from Transaction Information 

### ISSUE THREAD

**Issue by dongnhdongnh** [Nethereum/Nethereum#465]
Can i decode Input Data from Transaction Information ?
For example
`https://rinkeby.etherscan.io/tx/0x82a441c25607a00e21f9d3873aea28227aef3e9e2ca6a964264b19c13cc1e141`
i want to decode from 
`0xa9059cbb000000000000000000000000e00a1fa70bc8489ab13f2d7c8c5c9c3335c088af0000000000000000000000000000000000000000000000008ac7230489e80000`
to
`From 0x28ab550f84c21ba6c1a4814d750fba0e7336d807To 0xe00a1fa70bc8489ab13f2d7c8c5c9c3335c088affor  10 ERC-20 (LDN)`

**Comment by Enigmatic331** [comment]
Hi @dongnhdongnh - I need to test this myself, but I've seen an example which allows decoding of input given the hex data: https://github.com/Nethereum/Nethereum/blob/2f68f6194a3baf1e4aa9de426209bbcfbcec4581/src/Nethereum.Contracts.UnitTests/Web3FunctionEncodingDecoding.cs#L46

I'll test this later, but give it a shot in the interim to see if it helps? Also, come join us at Nethereum's Gitter channel too - https://gitter.im/Nethereum/Nethereum
