### ISSUE TITLE
Nethereum and Infura, rpc error

### ISSUE THREAD

**Issue by RonLino** [Nethereum/Nethereum#466]
I am trying to use Infura with Nethereum. My code works fine while running a local instance of Geth (mainnet). However, if I try to use infura, the simplest call to Ethereum get the error:
“Error occurred when trying to send rpc request(s)”

I have googled, and there are several posts with this error. For example in Github #https://github.com/Nethereum/Nethereum/issues/254. Followig the sugestions f this posts I have used the account object sending the file path and also sending the Json content, I have also tested  use of the managedAccount object, but always I get the same error.

This is the code using the account object sending the Json content:

```
string password = “….”;
var keyStoreEncryptedJson = @"{""crypto"":{""cipher"":""aes-128-ctr"",""ciphertext"":"" …… ,""version"":3}";
var account = Nethereum.Web3.Accounts.Account.LoadFromKeyStore(keyStoreEncryptedJson, password);

objWeb3 = new Nethereum.Web3.Web3(account, "https://mainnet.infura.io/v3/my-infura-token");

var maxBlockNumber = await objWeb3.Eth.Blocks.GetBlockNumber.SendRequestAsync();
```

I think the password and Json content are corrects, because the account object is created correctly (If I give an incorrect password .Net returns an error and don`t creates the account object).

What is it wrong?

Thank you.

**Comment by Enigmatic331** [comment]
Hey RonLino. If it works fine on local Geth but not on Infura - Could you check to see if your code is running on .NET451? If yes, then you'll need to set ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12. Infura upgraded to start using TLS2 a few months back.

Keystores and private keys will work with Infura, but not ManagedAccount as you've already discovered on issue #254.

See if this helps, and if not, we can crack on it further.

**Comment by RonLino** [comment]
Thank you Enigmatic331. Your suggestion solves my problem.
