### ISSUE TITLE
GetBalance.SendRequestAsync  does not work always well, it fails to get balance in some block height.

### ISSUE THREAD

**Issue by shareworlds** [Nethereum/Nethereum#467]
When i try to get balance with block height, it show error message, but when i change the block height, it works ok,  it seems something wrong happened. does someone know what is wrong?

Code:
BlockParameter blockParameter = new BlockParameter(new HexBigInteger(4515820)); 
var balance = await web3.Eth.GetBalance.SendRequestAsync("0x0607897F3d07BCbFa3A10e7512563a598FbDB7C7", blockParameter);

Error message:
RpcResponseException: This request is not supported because your node is running with state pruning. Run with --pruning=archive.
at Nethereum.JsonRpc.Client.RpcClient.HandleRpcError(RpcResponseMessage response)

Note: in test chain Ropsten

**Comment by Enigmatic331** [comment]
@shareworlds - Replied to you on the Gitter chat; If you'd like to retrieve balance from a point of time too far into the past, an archive node would be needed. Newer versions of geth and parity prune state data (keeping only a number of states in-memory, I think Geth keeps 128 blocks) by default to save space.

I am wondering if there's a way to get a historical balance easily though, e.g. through a block explorer or similar.
