### ISSUE TITLE
Help needed with CreateFilterInput

### ISSUE THREAD

**Issue by miekassu** [Nethereum/Nethereum#475]
Hi, Im having problems with event filter inputs. 

Result 0 events
`var eventTest = web3.Eth.GetEvent<UpdateTradeItemTest>(contractAddress);`
`var filterUpdatedItemsByGUID = eventTest.CreateFilterInput<string, string>("1001", null);`
`var updateItemLogFiltered = await eventTest.GetAllChanges(filterUpdatedItemsByGUID);`

Following is working and I get all "UpdateTradeItemTest" events, including event on GUID "1001"
`var updateItemEvent = web3.Eth.GetEvent<UpdateTradeItemTest>(contractAddress);`
`var filterAllUpdateItem = updateItemEvent.CreateFilterInput();`
`var updateItemLogALl = await updateItemEvent.GetAllChanges(filterAllUpdateItem);`

`        [Event("UpdateTradeItemTest")]`
    `    public class UpdateTradeItemTest : IEventDTO`
   `     {`
   `         [Parameter("string", "GUID", 1, false)]`
   `         public string GUID { get; set; }`
   `         [Parameter("string", "dataHash", 2, false)]`
   `         public string dataHash { get; set; }`
   `     }`

Event on smart contract:
`event UpdateTradeItemTest(string GUID, string dataHash);`

I assume my mistake is some silly, but I just can't understand what.

Thanks!

**Comment by juanfranblanco** [comment]
First thing, your parameters should be marked as indexed to be able to filtered. If not they will come only as part of the filter data.

Now the other tricky element, if you mark both of the parameters as indexed, because they are strings they will be hashed so you will need to filter using their sha3 hash value.

If you use Bytes32 instead of a string that will solve the sha3 hash issue, but you will be limited in the size of your string.

**Comment by miekassu** [comment]
Hi,

using bytes32 is ok for my project.
What is the right approach to convert string to bytes32 and store it?
And when reading event, converting bytes32 back to string?

For storing I tried

`byte[] bytes = Encoding.ASCII.GetBytes("randomStringHere");`
`var storeNewItem = await newItemFunction.SendTransactionAsync(senderAddress, new HexBigInteger(900000), null, bytes, datahash);
`

and

`string random = "randomStringHere";`
`var storeNewItem = await newItemFunction.SendTransactionAsync(senderAddress, new HexBigInteger(900000), null, random.HexToByteArray(), datahash);
`

With both solutions, something is stored, but my event's are not fired anymore and I can't find my item anymore.

**Comment by juanfranblanco** [comment]
Nethereum does it automatically for you in the background, just set your type as a string in your FunctionMessages, EventDtos, ContractDeployments, but you will need to change your solidity type in both Nethereum and solidity (needless to say :) )

**Comment by juanfranblanco** [comment]
Also you can code generate your contract definition using vscode, have a go, it might help you. Estimation is done automatically for you if using FuncionMessages, etc.

https://nethereum.readthedocs.io/en/latest/nethereum-smartcontrats-gettingstarted/
https://nethereum.readthedocs.io/en/latest/nethereum-code-generation/

```csharp
[Event("UpdateTradeItemTest")]
public class UpdateTradeItemTest : IEventDTO
{
[Parameter("bytes32", "GUID", 1, false)]
public string GUID { get; set; }
[Parameter("bytes32", "dataHash", 2, false)]
public string dataHash { get; set; }
}

```

**Comment by miekassu** [comment]
I got it working now! Solution for the latest one was that I was trying too difficult approach, even though Nethereum does the magic for me. 

Thanks for the great library and help!
