### ISSUE TITLE
CallAsync does not accept CancellationToken

### ISSUE THREAD

**Issue by jandroalvarez** [Nethereum/Nethereum#476]
Method `CallAsync` from `Function` class is not overloaded to accept a CancellationToken as .NET suggests on their [Async patterns](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap#cancellation-optional)?
Besides, why do you accept a `CancellationTokenSource` instead of a `CancellationToken` in`SendTransactionAndWaitForReceiptAsync`?

I'm using Nethereum v2.5.1.

**Comment by juanfranblanco** [comment]
Obviously it will be a breaking change to alter this, so if is not necessary, might not consider change it. 
I do recommend you moving to 3.0 btw

**Comment by jandroalvarez** [comment]
Thanks for the quick answer Juan!
