### ISSUE TITLE
Support Newtonsoft.Json 12.0.1

### ISSUE THREAD

**Issue by RoanBrand** [Nethereum/Nethereum#478]

**Comment by knocte** [comment]
motivation?

**Comment by RoanBrand** [comment]
Sorry

I have an app here that uses it alongside a Bittrex .NET lib which uses it. Seems Nuget cannot have multiple versions of the same dependency on the same project.

**Comment by knocte** [comment]
Any motivation to use v12 instead of v11?

**Comment by treenew** [comment]
The .net core 2.2 use Newtonsoft.Json **12.0.1**,
But this project just max version to Newtonsoft.Json **12.0.0**
SO.........

**Comment by keesdewit82** [comment]
The dependency on Newtonsoft.Json < 12.0.0 is holding is from upgrading several depended packages. Packages that hold security related updates. Could you please look if it is possible to allow newer versions for Newtonsoft.Json?

Thanks for the great work!

**Comment by juanfranblanco** [comment]
Hi, you can use the CI version for the time being if wanted

**Comment by keesdewit82** [comment]
@juanfranblanco Good advice. Thank you sir!
