### ISSUE TITLE
how can I sign transaction in Azure KeyVault

### ISSUE THREAD

**Issue by avatar-92** [Nethereum/Nethereum#484]
Nethereum can sign transaction in Azure KeyVault by AzureKeyVaultExternalSigner. But how can I put the private key into key vault and then sign transaction? Help me please.. Give me some code witch put the key into Key Vault and then sign transaction with it. Thanks!

**Comment by avatar-92** [comment]
I found [signing transaction code](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer.AzureKeyVault.Console/Program.cs). How can I put ethereum private key into KeyVault?

**Comment by ConnorChristie** [comment]
Are you looking to import a private ethereum key into keyvalut? If so, I am not sure you can do that. I have just been generating the keys straight from inside the keyvault and using them to sign txns:

Example to generate key inside the key vault:
(You will also need to enable hardware security module support if you haven't done so already when creating the KV)
```
var keyId = Guid.NewGuid().ToString();
var keyBundle = await _keyVault.CreateKeyAsync(KeyVaultUrl, keyId, new NewKeyParameters
{
    Kty = "EC-HSM",
    CurveName = "SECP256K1",
    KeyOps = new [] { "sign", "verify" }
});
```

**Comment by avatar-92** [comment]
Thank you for your code! It helped me write next code
```
var kvc = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(GetToken));

//var ecKey = EthECKey.GenerateKey();

//var ecParameters = new ECParameters
//{
//    Curve = "SECP256K1",
//    D = ecKey.GetPrivateKeyAsBytes(),
//    X = ecKey.GetPubKey().Slice(1, 33),
//    Y = ecKey.GetPubKey().Slice(33, 65)
//};

//var keyId = ecKey.GetPublicAddress();
//var keyBundle = kvc.ImportKeyAsync(URI, keyId, new JsonWebKey(ecParameters)
//{
//    KeyOps = new[] { "sign", "verify" }
//}).Result;

//var vaultUri = keyBundle.Key.Kid;
var vaultUri = "https://btc-keys-test.vault.azure.net/keys/0xCe0D170ffdBF19803eD20C7dD38342Ed1142c58F/8fef3ce47c3745bfaaed5f30803cd3be";

var externalSigner = new AzureKeyVaultExternalSigner(kvc, vaultUri);

//var privateKey = ecKey.GetPrivateKey();
var privateKey = "0x25eb79a6700059a0676fbfd674fa445ad3a8524046cc50fe56a53b9446366045";

var to = "0xd939bec3b695ef4e1811a02a7c276d2ab3b207d7";
var amount = new BigInteger(100);
var gasLimit = new BigInteger(21000);
var gasPrice = new BigInteger(1000000000);
var nonce = new BigInteger(1);
var data = string.Empty;

var tsigner = new TransactionSigner();

var signedTx1 = tsigner.SignTransaction(privateKey, to, amount, nonce, gasPrice, gasLimit, data);
var signedTx2 = tsigner.SignTransactionAsync(externalSigner, to, amount, nonce, gasPrice, gasLimit, data).Result;

var isEquals = string.Equals(signedTx1, signedTx2);
System.Console.WriteLine(isEquals);
```
I got new private key and imported it to KeyVault, but unfortunally signed transaction KV not equals signed transaction NEthereum. What is wrong?

**Comment by juanfranblanco** [comment]
Closing this now, mainly your private key will be different from the key vault one. You can validate using the recovery function that the address is the same.
