### ISSUE TITLE
One or more errors occurred. (Error occurred when trying to send rpc requests(s))

### ISSUE THREAD

**Issue by senzacionale** [Nethereum/Nethereum#487]
This is my code for using simple web3 client.

```
if (_web3 == null)
                {
                    switch (BlockSource)
                    {
                        case BlockSource.Localhost:
                            _web3 = new Web3(Account, "http://localhost:8545");
                            break;
                        case BlockSource.Infura:
                            _web3 = new Web3(Account, "https://mainnet.infura.io/xxx");
                            break;
                        default:
                            break;
                    }
                }
```

And after a while (cca 1 day) I am getting this error. Looks like NEthereum throw this error.

[11:08:39 ERR] One or more errors occurred. (Error occurred when trying to send rpc requests(s))
[11:08:39 ERR] Error occurred when trying to send rpc requests(s)

Any idea why?

**Comment by juanfranblanco** [comment]
We covered this in gitter, you should not get any issues with Nethereum. We keep in memory the HttpClient for performance but it is recycled every hour. This mainly indicates an issue with the client. (If not apologies for the late response!)
Closing this now, if there are still any problems please reopen or check in gitter.
