### ISSUE TITLE
constantinople hardfork compability

### ISSUE THREAD

**Issue by SergeyAnkarenko** [Nethereum/Nethereum#489]
Hello, 

would the upcoming constantinople hardfork affect the implementation of Nethereum? The way transaction if formed and signed.

From what I've read only eip1234 has compatibility problems. So it won't affect the library

But I must be certain about that.

Thank you

**Comment by juanfranblanco** [comment]
Hi Sergey, correct there should not be any compatibility problems as the changes affect the evm and difficulty calculation.

**Comment by SergeyAnkarenko** [comment]
Thank you!
