### ISSUE TITLE
When doing CallAsync with Require(..) that fails, return value is 3963877391197344453575983046348115674221700746820753546331534351508065746944

### ISSUE THREAD

**Issue by devedse** [Nethereum/Nethereum#491]
### Issue

I just wrote a very small contract:

```
pragma solidity ^0.5.2;

contract Ctr {
    address public owner;
    uint public val;

    modifier onlyOwner() {
        require(msg.sender == owner, "Only the owner contract can call functions on this contract");
        _;
    }

    constructor() public {
        owner = msg.sender;
    }
    
    function setVal(uint _val) public onlyOwner {
        val = _val;
    }
    
    function getVal() public view returns (uint _val) {
        require(val > 5, "Val should be larger then 5 to obtain it");
        _val = val;
    }   
}
```

If I upload this contract using Nethereum or Remix and then call the getVal() function when val is actually lower then 5 (the require fails), it returns the following value:
`3963877391197344453575983046348115674221700746820753546331534351508065746944` 

Or converted to hex:
8C379A000000000000000000000000000000000000000000000000000000000

Apparently this issue also happens with Web3.JS and also with Remix:
https://github.com/ethereum/solidity/issues/3971
https://github.com/ethereum/web3.js/issues/1903

I have no idea what's happening here. The community of both Web3.JS and Solidity don't seem to be very active on this topic so I wanted to ask here as well to see if someone with more knowledge from the internal working behind this can figure out why this strange number is returned.

It seems that EtherScan is actually picking up the value correctly:
https://ropsten.etherscan.io/address/0xc66ae60ac63c81b29041a4bb97d541d5b7223671#readContract

However if you then put the contract address in Remix again and try to read the value, the same strange number pops up:
![image](https://user-images.githubusercontent.com/2350015/50911106-74605700-142f-11e9-8e66-ee20242e31ef.png)

If I set the value to 6, then it works again:
![image](https://user-images.githubusercontent.com/2350015/50911296-da4cde80-142f-11e9-9203-b44e25afbd65.png)

### Expected result:

I would expect that somehow Nethereum or Web3JS or Geth catches this error and correctly throws an Exception. (Or maybe even something like a generic type with a status field).

**Comment by juanfranblanco** [comment]
Update on this: It seems that Geth is working on this. Nothing it can be done on Nethereum really.
