### ISSUE TITLE
Getting started with Nethereum

### ISSUE THREAD

**Issue by geniusKoder** [Nethereum/Nethereum#494]
Hi, I am new to Nethereum and blockchain so I am not too sure where to start. Is this video provided (https://www.youtube.com/watch?v=4t5Z3eX59k4), the most basic of Nethereum?

May I also know would the information on the blockchain be private? I read that you can have private chain, but I don't fully understand where the chain will be. Thank you for your help and guidance! :)

**Comment by juanfranblanco** [comment]
Hi @geniusKoder, whilst the video is rather old (and areas upgraded) it covers most of the ares you need to know about getting started. You can refer later on to our documentation and workbooks.

https://nethereum.readthedocs.io/en/latest/nethereum-smartcontrats-gettingstarted/

https://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/

Regarding private chains, they can be hosted in cloud(s) consortium (ie all the nodes in a single cloud or many), hosted in premise by a single party (enterprise) or many, depending on the use case and agreements. 

The very simplest way to get started launching a chain is to just run a single node using our TestChains and then advance to a cloud based one. All our docs and workbooks used those preconfigured ones.

https://github.com/Nethereum/Testchains

@anegg0 cc you for thoughts on improving docs quick intro

**Comment by KevinSmall** [comment]
@geniusKoder if you're new to blockchain, you might also find these courses helpful. They are not about Nethereum, these are general Ethereum:
 * free: https://academy.b9lab.com/courses/B9lab/X16-0/2016/about
 * paid: https://consensys.net/academy/foundations/ and https://consensys.net/academy/bootcamp/

**Comment by geniusKoder** [comment]
@KevinSmall Thanks for sharing. I will take a look
