### ISSUE TITLE
SendTransaction on Azure BaaS results in "Unknown account"

### ISSUE THREAD

**Issue by malichishti** [Nethereum/Nethereum#495]
Hi,
I have followed the instructions [here ](https://nethereum.readthedocs.io/en/latest/azure/set-up-blockchain-on-azure/)to setup a Ethereum Proof-of-Work Consortiam in Azure. As per the last section of the same link i created a new account and transfered 1000 Ether to it.

If i check its balance as below i get 1000 back which is correct.
```
var address = "0x83a672070E78B778789133d2fC5f9686c4Ada920";
var web3 = new Web3("http://ethcdi-dns-reg1.australiaeast.cloudapp.azure.com:8545");
var balance = await web3.Eth.GetBalance.SendRequestAsync(address);
Console.WriteLine(Web3.Convert.FromWei(balance.Value, 18));
```
Next if i try to send a transaction using following code i get **"Unknown Account"** exception

```
var account = new Account(privateKey);
var web3 = new Web3(account, url:"http://ethcdi-dns-reg1.australiaeast.cloudapp.azure.com:8545");
var transactionId = await web3.Eth.Transactions.SendTransaction.SendRequestAsync(new TransactionInput("0x74686973206973206d792064617461", address));
```

I have checked **web3.Eth.Accounts.SendRequestAsync()** and i dont see the new account there. Did i miss something in the documentation?

**Comment by malichishti** [comment]
Thanks I understand the accounts part now.

Yes the address and private key are correct. I even validated them by Sing a message option at Myetherwallet.

Sent from my iPhone

On 14 Jan 2019, at 5:29 pm, Juan Blanco <notifications@github.com<mailto:notifications@github.com>> wrote:


@malichishti<https://github.com/malichishti> you will not be able to retrieve the Account using web3.Eth.Accounts.SendRequestAsync(), those are only the accounts in that Node (also for security you would not want that either).

Is your from address in the TransactionInput the corresponding to the private key? Something to check.

**Comment by juanfranblanco** [comment]
var privateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
var account = new Account(privateKey);
var wei = Web3.Convert.ToWei(1);
var toAddress = "0x12890D2cce102216644c59daE5baed380d84830c";
var transaction = await web3.TransactionManager.SendTransactionAsync(account.Address, toAddress,  new Nethereum.Hex.HexTypes.HexBigInteger(wei));

Ok try this as a sample, (note this is transferring from and to the same address, which I have just funded) note I just validated your "to" address is not valid.

**Comment by juanfranblanco** [comment]
You can change the toaddress to: "0x83a672070E78B778789133d2fC5f9686c4Ada920" to see the changes in balance

**Comment by malichishti** [comment]
@juanfranblanco thank you.
The hex string in my code was not **To Address** but it was **Data** which i wanted to store with the transaction.

I can confirm if i use `web3.TransactionManager.SendTransactionAsync` it works fine; however, i still get "Unknow account" if i use `web3.Eth.Transactions.SendTransaction.SendRequestAsync` even though paramaeters are exactly the same.

**Comment by juanfranblanco** [comment]
Ah, I just realised what you are doing, I should have spotted that earlier, if you don't use the TransactionManager it will default to interact directly with the nodes accounts (which need to be unlocked), hence you are having the issue.

**Comment by malichishti** [comment]
@juanfranblanco thank you.
