### ISSUE TITLE
Running dotnet cli tools unstable

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#5]
This could simply be a matter of me not understanding the new toolchain fully, but when I do a `dotnet restore` it fails with lots of errors.  When I do a `dotnet build` it fails. When I do a `dotnet run` it appears to build all the projects successfully, however when I copy those dlls into my xamarin app I get all sorts of System.Object not referenced errors.

Would be nice to have this library as a more traditional csproj style library until dotnet cli is more stable.

**Comment by juanfranblanco** [comment]
The library is not targeting xamarin yet, check the project.json. Once we target netstandard the restore errors will dissappear too. Let's move forward not backwards it will be harder to maintain later on. Let's wait for build to see the future of Sharp develop, vs and vs code :)

**Comment by juanfranblanco** [comment]
The restore errors relate to the dependencies not the library itself.

**Comment by juanfranblanco** [comment]
Request submitted for Json.Rpc.Client https://github.com/Gekctek/JsonRpc.Router/issues/12 to target netstandard 1.1

**Comment by slothbag** [comment]
Anyone who stumbles across this issue with a similar problem can get in contact with me.  I have a build script to help compile this project for .Net framework.  I may get around to cleaning it up and publishing in a separate repo.

**Comment by juanfranblanco** [comment]
Just post it here in a different folder if you want.

**Comment by juanfranblanco** [comment]
Also im working on the .net cli support, which I might put in another branch. Try this for ABI

[project.json.txt](https://github.com/Nethereum/Nethereum/files/163789/project.json.txt)
