### ISSUE TITLE
EthECKey method GetPrivateKey

### ISSUE THREAD

**Issue by lutk** [Nethereum/Nethereum#506]
```
var privateKey = new EthECKey("0xc7a7810b4b74b602962cbd07c99705f0cc1a0a2f60cca33b96b0eae64ed25e32").GetPrivateKey();
Assert.AreEqual("0xc7a7810b4b74b602962cbd07c99705f0cc1a0a2f60cca33b96b0eae64ed25e32", privateKey);
```
The test with the specified private key does not work, because the method returns "0x00c7a7810b4b74b602962cbd07c99705f0cc1a0a2f60cca33b96b0eae64ed25e32" (extra 2 zeros after the prefix 0x).

**Comment by juanfranblanco** [comment]
This is due to the signature
