### ISSUE TITLE
uPort integration

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#51]

**Comment by pvanroos** [comment]
hi @juanfranblanco 
Have you looked into any other DID providers like SelfKey?

**Comment by juanfranblanco** [comment]
Hi, I have just joined the DIF to start implementing (and migrating some bits) to create a DID library, although I have not seen SelfKey. Uport does not seem to be a thing anymore.

**Comment by pvanroos** [comment]
Yea.  I agree.  It looked promising but there's broken links and other things that have eroded my confidence in the project.  I really liked the offchain stuff though.  

Please share your alpha stuff when you're ready.  I'd love to test it.

**Comment by juanfranblanco** [comment]
@pvanroos it is going to be part of DIF, mainly porting (ish) their java implementation. You can join DIF and collaborate if you want.

**Comment by juanfranblanco** [comment]
Closing this as Uport is not going to happen
