### ISSUE TITLE
RLP Behaviour Confusing

### ISSUE THREAD

**Issue by codingupastorm** [Nethereum/Nethereum#510]
The RLP behaviour is strange in that it always returns the encoded item as the first item inside of a list.

In this case I encode and immediately decode. Given that I receive an RLPCollection back I naturally assume that it will be a list of my encoded items, but instead I actually have to go to decoded[0].

```        
        [Fact]
        public void Test()
        {
            var item1 = new byte[] {0x01};
            var item2 = new byte[] {0x01, 0x02};

            byte[] encoded = RLP.EncodeList(RLP.EncodeElement(item1), RLP.EncodeElement(item2));
            RLPCollection decoded = RLP.Decode(encoded);

            // The actual list is at decoded[0]. These asserts will fail.

            Assert.Equal(item1, decoded[0].RLPData);
            Assert.Equal(item2, decoded[1].RLPData);
        }
```

Is this functionality expected? Maybe there is something about the RLP spec I don't understand.

I notice there is also DecodeFirstElement that seems it might do away with this issue but why do I have to enter a startPos?

Happy to contribute PRs if you agree this could be changed.

**Comment by juanfranblanco** [comment]
Hey @codingupastorm , yes it is correct, as an example, if you look at the signer that uses the list it is expecting it in that format.

**Comment by codingupastorm** [comment]
Hey thanks Juan,

Right I can see that in the decoder that it's expecting that format, but why does it expect the list to be wrapped in another list?

**Comment by juanfranblanco** [comment]
@codingupastorm  I have been on holidays apologies for the delay response, yeah it is confusing, and corrected on the latest commit. Mainly I kept the Collection visitor instead of returning the Element (this was done a long time ago...)
