### ISSUE TITLE
How to catch Ether Send/Transfer Errors ?

### ISSUE THREAD

**Issue by echapeta** [Nethereum/Nethereum#517]
Hello,

I;m using Nethereum to send ETH between addresses (and to call contract transfer function).

When any parameter is wrong, like  wrong signature or address, or not enough sender's ETH balance, the 

Dim T As Nethereum.RPC.Eth.DTOs.TransactionReceipt = Await web3.Eth.GetEtherTransferService().TransferEtherAndWaitForReceiptAsync(ToAddress, Amount)

Statement seems to wait forever.

How can I get an indication of failure ?

Thank You !!!

**Comment by KevinSmall** [comment]
Hi Eduardo,
Could you post up some example code so I can try to replicate?
Thanks,
Kevin.

**Comment by echapeta** [comment]
Hello Kevin,

Dim Account = New Account(privateKey)
        Dim web3 = New Web3(Account, ETHNode)

        Dim transactionMessage = New TransferFunction With {
            .FromAddress = Account.Address,
            .[To] = receiverAddress,
            .TokenAmount = tokens * (10 ^ Decimals)
            }

        Dim transferHandler = web3.Eth.GetContractTransactionHandler(Of TransferFunction)()
        Dim transferReceipt = Await transferHandler.SendRequestAndWaitForReceiptAsync(contractAddress, transactionMessage)

When the Private account, destination address are wrong the SendRequestAndWaitForReceiptAsync lasts for ever.....

Thabnk You

**Comment by KevinSmall** [comment]
Can you replicate issue on rinkeby or mainnet? Or is it a local chain only?

**Comment by echapeta** [comment]
Is happening in Mainnet.........

**Comment by KevinSmall** [comment]
Ok great, and do you have some sample addresses?
I'd like to try to replicate what you're seeing.

**Comment by echapeta** [comment]
I can't bring you control over our addresses

**Comment by KevinSmall** [comment]
Yes sure, I wasn't meaning access to keys, I'd just like to be able to easily replicate the issue with the same/similar data to what you're using.

**Comment by KevinSmall** [comment]
Maybe you could replicate it on e.g. rinkeby and then I can use exact same data as you're using?

**Comment by echapeta** [comment]
Thank You !!

**Comment by KevinSmall** [comment]
Hi Eduardo, did the error replicate ok on rinkeby?

**Comment by echapeta** [comment]
Hello,

We didn't try.
So far we just surrounded the code by Try... Catch

Thank You!
