### ISSUE TITLE
Delete/Update UnixIpcClient project?

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#521]
UnixIpcClient project depends on nuget package https://www.nuget.org/packages/EdjCase.JsonRpc.Client, which depends on nuget package https://www.nuget.org/packages/EdjCase.JsonRpc.Core, which is unlisted in nuget.org.

Ultimately this means that this project cannot really be used. Should we fix it or remove it?

**Comment by juanfranblanco** [comment]
That is an old contribution, and can be deleted.

**Comment by knocte** [comment]
Thanks!
