### ISSUE TITLE
Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.'

### ISSUE THREAD

**Issue by VolodymyrSvystunDevPro** [Nethereum/Nethereum#526]
I am getting the following error:
 "Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce."
from time to time when sending a contract transaction.

I found here: https://github.com/paritytech/parity-ethereum/issues/2908
that if I do not set a nonce then this error will never happen.

But in Nethereum library I found that nonce is required and if it is not set by the user it is calculated by the library.

Is it possible to send a contract transaction without nonce to avoid the error?

Thank you in advance.

**Comment by juanfranblanco** [comment]
If you are signing the transactions you require the nonce, if you use a Managed account you may get away not populating it.

**Comment by VolodymyrSvystunDevPro** [comment]
@juanfranblanco thank you for so quick reaction.
Could you  please explain me what a dofference between ManagedAccount and Account?

**Comment by juanfranblanco** [comment]
Check this doc 
https://nethereum.readthedocs.io/en/latest/accounts/

**Comment by juanfranblanco** [comment]
Btw I am closing this as I am attempting to only have bugs as issues, please come to gitter to ask any other questions if wanted.
