### ISSUE TITLE
Contract Decoding Issue: Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by ekulaleba** [Nethereum/Nethereum#530]
Trying to obtain the token name from an ERC20 Contract Address for the MAKER Token, as seen on Etherscan. The raw name is represented by ta 66 character hex which I'm assuming is the reason behind this issue.
https://etherscan.io/token/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2#readContract

I am able to obtain the decimal and other data but the token name returns the mentioned error.

Code: 
```
var contractAddress = "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2"

var contract = web3.Eth.GetContract(erc20abi, contractAddress);
var decimalValue = await contract.GetFunction("decimals")>CallAsync<int>();
var tokenName = await tokenContract.GetFunction("name").CallAsync<string>();
```

I am using the Standard ERC20 Abi, it works fine for other tokens where the name is a simple string such as: https://etherscan.io/token/0xd7737fcf3e1e6352ab9c7b8f5a9892846da7db8d#readContract

Tried changing the type to different types, both from the code side and from the Abi to no avail

**Comment by juanfranblanco** [comment]
@ekulaleba the Maker contract uses a bytes32 for the name and the token symbol. Maker was created before the string type existed :). If you look at the StandardToken contract library it is solved using the following: 
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.StandardTokenEIP20/StandardTokenService.cs#L54

Also the ERC20 as a standard does not include decimails, name and symbol those were extra additions later on.

**Comment by ekulaleba** [comment]
Thank you for the quick reply, managed to solve the issue by using the QueryRawAsync to decode the bytes32 value.
