### ISSUE TITLE
NullReferenceException : AddressUtil.AreAddressesTheSame

### ISSUE THREAD

**Issue by srothwellbjss** [Nethereum/Nethereum#536]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

The TransactionReceipt object's Equals uses AddressUtil.AreAddressesTheSame to compare the ContractAddress property, however it does not account for the ContractAddress being null, which is the case when the transaction is not deploying a new contract. 

## Expected Behavior
Handle nulls and do a string comparison on the potentially nullable value

## Current Behavior
NullReferenceException is thrown presumably as ToLowerInvariant doesn't support being called on a nullable value, as part of the AreAddressesTheSameFunction

## Possible Solution
Replace line 25/26
`return string.Equals(address1.EnsureHexPrefix().ToLowerInvariant(), address2.EnsureHexPrefix().ToLowerInvariant(),
                StringComparison.OrdinalIgnoreCase);`
with:
`return string.Equals(address1.EnsureHexPrefix()?.ToLowerInvariant(), address2.EnsureHexPrefix()?.ToLowerInvariant(),
                StringComparison.OrdinalIgnoreCase);`

## Steps to Reproduce
1. Take any TransactionReceipt where the ContractAddress is null and attempt to compare it against another TransactionReceipt

## Context (Environment)
This hasn't caused an issue in production code, but in automated testing. This can be worked around, but wanted to make you aware as the most common type of TransactionReceipts will hit this issue if compared.

**Comment by juanfranblanco** [comment]
Closing this now, also the assumption is now made that 0x, "" and null are the same address.
