### ISSUE TITLE
Decoding Struct from View Function: Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by Astrovicis** [Nethereum/Nethereum#538]
Hello! I'm working in C# with Unity and there's this struct that I expect to get back:

```
[FunctionOutput]
public class SubmissionDataDTO : IFunctionOutputDTO
        {
            [Parameter("address", "tournament", 1)]
            public string TournamentAddress { get; set; }
            [Parameter("uint256", "roundIndex", 2)]
            public BigInteger RoundIndex { get; set; }
            [Parameter("bytes32", "commitHash", 3)]
            public string CommitHash { get; set; }
            [Parameter("string", "content", 4)]
            public string ContentHash { get; set; }
            [Parameter("uint256", "reward", 5)]
            public BigInteger Reward { get; set; }
            [Parameter("uint256", "timestamp", 6)]
            public BigInteger Timestamp { get; set; }
        }

```
But Nethereum is telling me after making a call to:
```
public static IEnumerator getSubmission(string submissionHash)
        {
            var queryRequest = new QueryUnityRequest<GetSubmissionFunction, MatryxSubmission.SubmissionDataDTO>(NetworkSettings.infuraProvider, NetworkSettings.activeAccount);
            yield return queryRequest.Query(new GetSubmissionFunction() { SubmissionHash = Utils.HexStringToByteArray(submissionHash) }, address);
            yield return queryRequest.Result;
        }
```

that:

> OverflowException: Value was either too large or too small for an Int32.
> System.Numerics.BigInteger.op_Explicit (System.Numerics.BigInteger value) (at <54fb6b36b4f84da49924d0eaf4d45806>:0)
> Nethereum.ABI.Decoders.IntTypeDecoder.DecodeInt (System.Byte[] encoded) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.EncoderDecoderHelpers.GetNumberOfBytes (System.Byte[] encoded) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeOutput (System.Byte[] outputBytes, Nethereum.ABI.FunctionEncoding.ParameterOutput[] outputParameters) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes (System.Byte[] output, System.Object result, System.Reflection.PropertyInfo[] properties) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes (System.String output, System.Object result, System.Reflection.PropertyInfo[] properties) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes[T] (System.String output, T result, System.Reflection.PropertyInfo[] properties) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.FunctionCallDecoder.DecodeFunctionOutput[T] (T functionOutputResult, System.String output) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.Contracts.FunctionOuputDTOExtensions.DecodeOutput[TFunctionOutputDTO] (TFunctionOutputDTO functionOuputDTO, System.String output) (at <674e307a3d034490917846d11c4e497c>:0)
> Nethereum.JsonRpc.UnityClient.QueryUnityRequest`2+<Query>d__7[TFunctionMessage,TResponse].MoveNext () (at <5188d924381348829350a9b1de03c968>:0)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

And that confuses me because I'm using BigIntegers. Additionally, if I change the first BigInteger field of SubmissionDataDTO ("roundIndex") to type long in the struct, I get a _different_ error:

> OverflowException: Value was either too large or too small for an Int64.
> System.Numerics.BigInteger.op_Explicit (System.Numerics.BigInteger value) (at <54fb6b36b4f84da49924d0eaf4d45806>:0)
> Nethereum.ABI.Decoders.IntTypeDecoder.DecodeLong (System.Byte[] encoded) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.Decoders.IntTypeDecoder.Decode (System.Byte[] encoded, System.Type type) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.ABIType.Decode (System.Byte[] encoded, System.Type type) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeOutput (System.Byte[] outputBytes, Nethereum.ABI.FunctionEncoding.ParameterOutput[] outputParameters) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes (System.Byte[] output, System.Object result, System.Reflection.PropertyInfo[] properties) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes (System.String output, System.Object result, System.Reflection.PropertyInfo[] properties) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes[T] (System.String output, T result, System.Reflection.PropertyInfo[] properties) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.ABI.FunctionEncoding.FunctionCallDecoder.DecodeFunctionOutput[T] (T functionOutputResult, System.String output) (at <8f2bfa5f1f89424d8aca5929566474f6>:0)
> Nethereum.Contracts.FunctionOuputDTOExtensions.DecodeOutput[TFunctionOutputDTO] (TFunctionOutputDTO functionOuputDTO, System.String output) (at <674e307a3d034490917846d11c4e497c>:0)
> Nethereum.JsonRpc.UnityClient.QueryUnityRequest`2+<Query>d__7[TFunctionMessage,TResponse].MoveNext () (at <5188d924381348829350a9b1de03c968>:0)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

A ping to our [server](https://cortex-staging.matryx.ai/submissions/0xe627ceaf65decb29bc6a5f4be54b8d909f28b5ce770fd863c701ff19db28c44d) reveals that the timestamp of the Submission is 1553628157, which BigInteger.Parse() seems to have no problem with...
Halp!

To reproduce:
1) Clone/download the [Calcflow](https://github.com/matryx/calcflow/tree/Matryx_Amendment) repo from the Matryx_Amendment branch
2) Run Calcflow/Assets/_Scenes/FreeParameterization.unity from Unity 2018.2. The error should pop up in the console after grabbing ABIs and things from our server.

Environment:
Windows 10 Home
Nethereum 3.2.0 (net461dllsAOT.zip)
Unity 2018.2

I would suggest a solution but I don't know what's happening! :(

**Comment by juanfranblanco** [comment]
Is your "commitHash" really a BigInteger? And btw great project :)

**Comment by Astrovicis** [comment]
Whoops! Yeah I think an earlier commit had it as a BigInteger, but it should be a string in the most recent commit.
Thank you! :)

**Comment by Astrovicis** [comment]
Any idea what's happening here?

**Comment by Astrovicis** [comment]
After a little more investigation, I think I'm finding that Nethereum isn't decoding structs properly...? Maybe? Commenting out everything but Owner and Timestamp in the struct, Owner is being decoded as 0x0000000000000000000000000000000000000020, and Timestamp as 1351712155614730959841780284864888332772794893279 (0xECC4DE8F2846F3038C11A9E457634AD1A3C703DF aka owner)

**Comment by Dave-Whiffin** [comment]
I can have a look at this for you.  So that I can investigate the decoding issue in isolation - can you please provide the following.

1 - a copy of the abi 
2 - ideally a copy of the solidity contract (sol file) that is returning the structs?
3 - a copy of the latest SubmissionDataDTO 

Many thanks,

Dave 
(I work on the Nethereum team with Juan)

**Comment by Astrovicis** [comment]
I actually noticed the same issue with Commits, which are more important at the moment. Here is the corresponding for them:

1) https://pastebin.com/TtEfXGAJ
2) https://pastebin.com/rbSZe2yJ
3) 
[FunctionOutput]
        public class Commit : IFunctionOutputDTO
        {
            [Parameter("address")]
            public string Owner { get; set; }
            [Parameter("uint256")]
            public BigInteger Timestamp { get; set; }
            [Parameter("bytes32")]
            public string GroupHash { get; set; }
            [Parameter("bytes32")]
            public string CommitHash { get; set; }
            [Parameter("string")]
            public string ContentHash { get; set; }
            [Parameter("uint256")]
            public BigInteger Value { get; set; }
            [Parameter("uint256")]
            public BigInteger OwnerTotalValue { get; set; }
            [Parameter("uint256")]
            public BigInteger TotalValue { get; set; }
            [Parameter("uint256")]
            public BigInteger Height { get; set; }
            [Parameter("bytes32")]
            public string ParentHash { get; set; }
            [Parameter("bytes32[]")]
            public List<string> Children { get; set; }
        }

**Comment by Astrovicis** [comment]
I actually noticed the same issue with Commits, which are more important at the moment. Here is the corresponding for them:
1. https://pastebin.com/TtEfXGAJ
2. https://pastebin.com/rbSZe2yJ
3. 
[FunctionOutput]
        public class Commit : IFunctionOutputDTO
        {
            [Parameter("address")]
            public string Owner { get; set; }
            [Parameter("uint256")]
            public BigInteger Timestamp { get; set; }
            [Parameter("bytes32")]
            public string GroupHash { get; set; }
            [Parameter("bytes32")]
            public string CommitHash { get; set; }
            [Parameter("string")]
            public string ContentHash { get; set; }
            [Parameter("uint256")]
            public BigInteger Value { get; set; }
            [Parameter("uint256")]
            public BigInteger OwnerTotalValue { get; set; }
            [Parameter("uint256")]
            public BigInteger TotalValue { get; set; }
            [Parameter("uint256")]
            public BigInteger Height { get; set; }
            [Parameter("bytes32")]
            public string ParentHash { get; set; }
            [Parameter("bytes32[]")]
            public List<string> Children { get; set; }
        }

**Comment by Astrovicis** [comment]
Thank you guys!!! Really appreciate this :)

**Comment by Astrovicis** [comment]
Thinking about this a little more, it definitely feels like a dynamic-length field issue. Probably need to check the types within the struct and if there is one or more of bytes/(basictype)[]/string, utilize the offsets embedded within the output of the rpc result.

**Comment by Dave-Whiffin** [comment]
Hi - there were a few issues here - mainly due to the struct using bytes32.  There's nothing wrong with using bytes32 but Nethereum can't really know whether the content of a bytes32 is a string or not - especially when decoding a struct.  Also the parameter orders should be specified and the "List" you have for Children - I presume that is a typo.

Below is a DTO that works with this struct - it was code generated - feel free to change the name of the class.   I have a test app which calls a test contract which returns an instance of this struct successfully. You'll also need a little bit of code to decode the byte arrays in to strings which is also below:

Please let us know how you get on?

```
            var bytes32Decoder = new StringBytes32Decoder(); //Nethereum.ABI.Decoders
            var commitHash = bytes32Decoder.Decode(commit.CommitHash);
``

```
    [FunctionOutput]
    public class CommitInstanceOutputDTO : IFunctionOutputDTO 
    {
        [Parameter("address", "owner", 1)]
        public virtual string Owner { get; set; }
        [Parameter("uint256", "timestamp", 2)]
        public virtual BigInteger Timestamp { get; set; }
        [Parameter("bytes32", "groupHash", 3)]
        public virtual byte[] GroupHash { get; set; }
        [Parameter("bytes32", "commitHash", 4)]
        public virtual byte[] CommitHash { get; set; }
        [Parameter("string", "content", 5)]
        public virtual string Content { get; set; }
        [Parameter("uint256", "value", 6)]
        public virtual BigInteger Value { get; set; }
        [Parameter("uint256", "ownerTotalValue", 7)]
        public virtual BigInteger OwnerTotalValue { get; set; }
        [Parameter("uint256", "totalValue", 8)]
        public virtual BigInteger TotalValue { get; set; }
        [Parameter("uint256", "height", 9)]
        public virtual BigInteger Height { get; set; }
        [Parameter("bytes32", "parentHash", 10)]
        public virtual byte[] ParentHash { get; set; }
    }
```

**Comment by Dave-Whiffin** [comment]
Solidity Test Contract
```
pragma solidity ^0.5.0;

contract MatryxCommit {

    event CommitClaimed();

    struct Commit {
        address owner;
        uint256 timestamp;
        bytes32 groupHash;
        bytes32 commitHash;
        string content;
        uint256 value;
        uint256 ownerTotalValue;
        uint256 totalValue;
        uint256 height;
        bytes32 parentHash;
        bytes32[] children;
    }

    Commit public commitInstance;

    constructor () public {
        commitInstance = Commit(
            { 
                owner: 0xEeA159afba3969986f8Dae95ab1F8EaBE6b3aE93, 
                timestamp : 1,
                groupHash : "groupHash",
                commitHash : "commitHash",
                content : "content",
                value : 1,
                ownerTotalValue: 9,
                totalValue: 100,
                height: 80,
                parentHash : "parentHash",
                children: new bytes32[](2)
                 });
            
        commitInstance.children[0] = "child1";
        commitInstance.children[1] = "child2";
    }
}
```

**Comment by Astrovicis** [comment]
Hm. I'm unfortunately still getting "OverflowException: Value was either too large or too small for an Int32." with the struct you've provided. The following struct doesn't give any errors...but it is also awful haha

[FunctionOutput]
        public class Commit : IFunctionOutputDTO
        {
            [Parameter("uint256", "structOffset")]
            public BigInteger StructOffset { get; set; }
            [Parameter("address")]
            public string Owner { get; set; }
            [Parameter("uint256")]
            public BigInteger Timestamp { get; set; }
            [Parameter("bytes32")]
            public byte[] GroupHash { get; set; }
            [Parameter("bytes32")]
            public byte[] CommitHash { get; set; }
            [Parameter("uint256")]
            public BigInteger ContentHashOffset { get; set; }
            [Parameter("uint256")]
            public BigInteger Value { get; set; }
            [Parameter("uint256")]
            public BigInteger OwnerTotalValue { get; set; }
            [Parameter("uint256")]
            public BigInteger TotalValue { get; set; }
            [Parameter("uint256")]
            public BigInteger Height { get; set; }
            [Parameter("bytes32")]
            public string ParentHash { get; set; }
            [Parameter("uint256")]
            public BigInteger ChildrenOffset { get; set; }
            [Parameter("bytes32[10]")]
            public List<BigInteger> DynamicParams { get; set; }
        }

I feel like the above is something I shouldn't have to do though. It's interesting to me that its working on your environment

**Comment by Dave-Whiffin** [comment]
This feels like a moving target I am afraid. Your latest DTO includes dynamic params which the previous did not.  Also, you haven’t added the order to the parameter attributes which should be consistent with the order of the members of the struct. 

The DTO I posted was created based on the solidity struct you sent and the sample contract I wrote above includes it.  It worked end to end using Geth as a local node. 

Double check your solidity struct against your DTO and then compare and contrast my sample.   Also ensure that your abi is definitely consistent with the solidity contract and is not out of date. 

I can assure you that the decoding does work properly given the right DTO so you should be able to find the issue even if it involves creating a test app (which is what I did).  But Juan and I will be back online tomorrow should you need further assistance. 

Best of luck!

**Comment by Astrovicis** [comment]
Hm. Okay so I think I may have found something. Do you guys support ABIEncoderV2?

**Comment by Astrovicis** [comment]
Additionally, the list I have for Children is not a typo and I am unable to find a C# type able to be used to decode them. Also I agree on your point about the dynamic params:  they should not be there. However, those did not end up there as a result of changing the solidity Commit struct (what imo would aptly be called a moving target), but rather as a workaround because I couldn't find a better way to decode structs encoded with AbiEncoderV2 with my current understanding of Nethereum. Maybe Nethereum does support AbiEncoderV2 and I'm missing something. If so, I would be more than grateful to see an example haha
If not however, I would like to request it as a feature because it is very very useful!! :)

**Comment by juanfranblanco** [comment]
Yes Nethereum does support structs and V2 sadly we are not code generating any until the abi changes that are coming in Solidity 0.5.8

**Comment by juanfranblanco** [comment]
If you use structs you can use this as a guidance https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Accounts.IntegrationTests/ABIStructsTests.cs Once I am able to do a generator for this hopefully after 0.5.8 better documentation will also follow :)

**Comment by juanfranblanco** [comment]
If your function output is returning a struct it will be as follows : https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Accounts.IntegrationTests/ABIStructsTests.cs#L164

**Comment by Astrovicis** [comment]
I'm so sorry, I should have checked the integration tests first. That one file solved my problem; I just needed to put the commit and submission DTOs inside one higher level DTO with the sole member being of type tuple.

```
[FunctionOutput]
        public class CommitOutputDTO : IFunctionOutputDTO
        {
            [Parameter("tuple", 1)]
            public virtual Commit outCommit { get; set; }
        }

        [FunctionOutput]
        public class Commit : IFunctionOutputDTO
        {
            [Parameter("address", "owner", 1)]
            public virtual string Owner { get; set; }
            [Parameter("uint256", "timestamp", 2)]
            public virtual BigInteger Timestamp { get; set; }
            [Parameter("bytes32", "groupHash", 3)]
            public virtual byte[] GroupHash { get; set; }
            [Parameter("bytes32", "commitHash", 4)]
            public virtual byte[] CommitHash { get; set; }
            [Parameter("string", "content", 5)]
            public virtual string ContentHash { get; set; }
            [Parameter("uint256", "value", 6)]
            public virtual BigInteger Value { get; set; }
            [Parameter("uint256", "ownerTotalValue", 7)]
            public virtual BigInteger OwnerTotalValue { get; set; }
            [Parameter("uint256", "totalValue", 8)]
            public virtual BigInteger TotalValue { get; set; }
            [Parameter("uint256", "height", 9)]
            public virtual BigInteger Height { get; set; }
            [Parameter("bytes32", "parentHash", 10)]
            public virtual byte[] ParentHash { get; set; }
            //[Parameter("bytes32[]", "children", 11)]
            //public virtual string[] Children { get; set; }
        }
```

Completely failed to realize this was how it was done. Thank you again for your support despite it being my problem!

**Comment by metrocoding** [comment]
Hello Guys Does anyone know how to refer to enum in our return class type?
Here is my code:
Solidity
```
    enum AuctionStatus {
        PENDING,
        CLAIMED,
        CANCELLED
    }

    struct AuctionView {
        uint256 auctionId;
        uint256 tokenId;
        AuctionStatus status;
    }
```
.Net
```
[FunctionOutput]
public class Ret
{
    [Parameter("uint256")]
    public int AuctionId { get; set; }

    [Parameter("uint256")]
    public int TokenId { get; set; }

    [Parameter("uint256")]
    public int Status { get; set; }
}
```
how should I configure Status in Res model?
I'm getting `Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32.` error

**Comment by juanfranblanco** [comment]
@metrocoding code generate, is the simplest thing. Your enum should be ok with an int as it is very small, so the cast from BigInteger will be ok. The issue might be due to the other parameters or the output structure. Best code generate it.

**Comment by metrocoding** [comment]
> 

such a nice feature I didn't know it existed thanks.

**Comment by mustafazencode** [comment]
I have a similar problem with .NET Core 5 using Code Generation.
solidity compiler version is 0.8.20
I have no enum, Just the following simple contract:
```
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0 <0.9.0;

contract SimpleStorage {
    struct Person {
        uint256 age;
        string name;
    }
    Person[] public people; //dynamic array (size)

    function addPerson(string memory _name, uint256 _age) public {
        people.push(Person(_age, _name));
        getAgeByName[_name] = _age;
    }

    mapping(string => uint256) public getAgeByName;

    function getAge(string memory _name) public view returns (uint256) {
        return getAgeByName[_name];
    }
}

```

Error:
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result)
   at System.Convert.ToDecimal(Double value)
   at Nethereum.Util.BigDecimal.op_Implicit(Double value)
   at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestBaseFee(BigInteger[] baseFee, Int32[] order, Int32 timeFactor)
   at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFees(FeeHistoryResult feeHistory, BigInteger tip)
   at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFeesAsync()
   at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFeeAsync(Nullable`1 maxPriorityFeePerGas)
   at Nethereum.RPC.TransactionManagers.TransactionManagerBase.SetTransactionFeesOrPricingAsync(TransactionInput transaction)
   at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignTransactionRetrievingNextNonceAsync(TransactionInput transaction)
   at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignAndSendTransactionAsync(TransactionInput transaction)
   at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SendTransactionAsync(TransactionInput transactionInput)
   at Nethereum.Contracts.DeploymentHandlers.DeploymentTransactionSenderHandler`1.SendTransactionAsync(TContractDeploymentMessage deploymentMessage)
   at Nethereum.Contracts.DeploymentHandlers.DeploymentTransactionReceiptPollHandler`1.SendTransactionAsync(TContractDeploymentMessage deploymentMessage, CancellationToken cancellationToken)
   at Solidity.Controllers.SolidityController.DeployContract(Web3 web, SimpleStorageDeployment deployment) in E:\Projects\Solidity\Solidity\Solidity\Controllers\SolidityController.cs:line 43
   at Solidity.Controllers.SolidityController.Deploy() in E:\Projects\Solidity\Solidity\Solidity\Controllers\SolidityController.cs:line 26

Any tip on how to fix this ?

**Comment by juanfranblanco** [comment]
@mustafazencode that is not related to the decoding that is gas price calculation, what chain are you using?

**Comment by mustafazencode** [comment]
> @mustafazencode that is not related to the decoding that is gas price calculation, what chain are you using?

I am using Ganache locally.
<img width="755" alt="image" src="https://github.com/Nethereum/Nethereum/assets/125034284/529e11b1-b287-439a-b44f-50eda3168a69">

**Comment by mustafazencode** [comment]
```
var url = "HTTP://127.0.0.1:8545";
var privateKey = "0x4b423f9119648340cc6fdb22f35337aa65b2bf8268574a0c80bfe332ef17f90f";
var account = new Account(privateKey);
var web3 = new Web3(account, url);
var deployment = new SimpleStorageDeployment();
var receipt = await SimpleStorageService.DeployContractAndWaitForReceiptAsync(web, deployment);
```

**Comment by AsiaMartini** [comment]
> I have a similar problem with .NET Core 5 using Code Generation. Nethereum.Autogen.ContractApi Version 4.11.0 Nethereum.Web3 Version 4.14.0 solidity compiler version is 0.8.20 I have no enum, Just the following simple contract:
> 
> ```
> // SPDX-License-Identifier: MIT
> pragma solidity >=0.6.0 <0.9.0;
> 
> contract SimpleStorage {
>     struct Person {
>         uint256 age;
>         string name;
>     }
>     Person[] public people; //dynamic array (size)
> 
>     function addPerson(string memory _name, uint256 _age) public {
>         people.push(Person(_age, _name));
>         getAgeByName[_name] = _age;
>     }
> 
>     mapping(string => uint256) public getAgeByName;
> 
>     function getAge(string memory _name) public view returns (uint256) {
>         return getAgeByName[_name];
>     }
> }
> ```
> 
> Error: System.OverflowException: Value was either too large or too small for a Decimal. at System.Number.ThrowOverflowException(TypeCode type) at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result) at System.Convert.ToDecimal(Double value) at Nethereum.Util.BigDecimal.op_Implicit(Double value) at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestBaseFee(BigInteger[] baseFee, Int32[] order, Int32 timeFactor) at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFees(FeeHistoryResult feeHistory, BigInteger tip) at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFeesAsync() at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFeeAsync(Nullable`1 maxPriorityFeePerGas) at Nethereum.RPC.TransactionManagers.TransactionManagerBase.SetTransactionFeesOrPricingAsync(TransactionInput transaction) at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignTransactionRetrievingNextNonceAsync(TransactionInput transaction) at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignAndSendTransactionAsync(TransactionInput transaction) at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SendTransactionAsync(TransactionInput transactionInput) at Nethereum.Contracts.DeploymentHandlers.DeploymentTransactionSenderHandler`1.SendTransactionAsync(TContractDeploymentMessage deploymentMessage) at Nethereum.Contracts.DeploymentHandlers.DeploymentTransactionReceiptPollHandler`1.SendTransactionAsync(TContractDeploymentMessage deploymentMessage, CancellationToken cancellationToken) at Solidity.Controllers.SolidityController.DeployContract(Web3 web, SimpleStorageDeployment deployment) in E:\Projects\Solidity\Solidity\Solidity\Controllers\SolidityController.cs:line 43 at Solidity.Controllers.SolidityController.Deploy() in E:\Projects\Solidity\Solidity\Solidity\Controllers\SolidityController.cs:line 26
> 
> Any tip on how to fix this ?

Same for me. Any help?

**Comment by mustafazencode** [comment]
> 

Where do you deploy it ?
I deploy it on Ganache locally.
