### ISSUE TITLE
BigInteger double declaration

### ISSUE THREAD

**Issue by Edwardeth** [Nethereum/Nethereum#540]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

After Importing unitynet35dlls.zip into assets and successfully retrieving an Rinkeby address balance, I tried to do a function call. using a ```BitInteger``` as function parameter did not work with the error:

>The type 'BigInteger' exists in both 'Nethereum.Hex, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

## Expected Behavior

Should be able to use BigInteger 

## Current Behavior

Gives error

## Possible Solution

Remove Nethereum.Hex BigInteger maybe

## Steps to Reproduce

```
public TransactionInput CreatePingTransactionInput(
        string addressFrom,
        string privateKey,
        BigInteger pingValue,
        HexBigInteger gas = null,
        HexBigInteger gasPrice = null,
        HexBigInteger valueAmount = null)
    {
        var function = GetPingFunction();
        return function.CreateTransactionInput(addressFrom, gas, gasPrice, valueAmount, pingValue);
    }
```

**Comment by juanfranblanco** [comment]
@Edwardeth .Net35 does not include big integer so a custom implementation is included. Maybe: 1. you are not targeting .net35 or 2. you are including System.Numerics. 
Or maybe another that I cannot think of at the moment :)

Check https://github.com/Nethereum/Unity3dSimpleSample/tree/master/Assets/Plugins for an example of set up.

**Comment by juanfranblanco** [comment]
You can also use the net461 library if wanted.

**Comment by juanfranblanco** [comment]
Closing this now
