### ISSUE TITLE
Can't install Nethereum.Generator.Console

### ISSUE THREAD

**Issue by tmm360** [Nethereum/Nethereum#542]
Trying to install the Nethereum.Generator.Console tool with command
`dotnet tool install -g Nethereum.Generator.Console --add-source https://www.myget.org/F/nethereum/api/v3/index.json`

but receive an error NU3004 for invalid sign.

## Expected Behavior
I expect to install the tool

## Current Behavior
This error appears (sorry for italian language):

> error NU3004: Pacchetto 'Nethereum.Generator.Console 3.3.0' dell'origine 'https://api.nuget.org/v3/index.json': Questo repository ha indicato che tutti i relativi pacchetti sono firmati dal repository, ma questo pacchetto non è firmato.
error NU3004: Pacchetto 'Nethereum.Generator.Console 3.3.0' dell'origine 'https://api.nuget.org/v3/index.json': Questo repository ha indicato che tutti i relativi pacchetti sono firmati dal repository, ma questo pacchetto non è firmato.
Non è stato possibile ripristinare il pacchetto dello strumento.
Non è stato possibile installare lo strumento 'nethereum.generator.console'. Le cause di questo errore sono le seguenti:
>
> * Si sta provando a installare una versione precedente e non è stata usata l'opzione --version per specificare la versione.
> * È stato trovato un pacchetto con questo nome, ma non corrisponde a uno strumento .NET Core.
> * Non è possibile accedere al feed NuGet richiesto, probabilmente a causa di un problema di connessione Internet.
> * Il nome dello strumento non è stato digitato correttamente.

**Comment by juanfranblanco** [comment]
Are you installing from CI? what about installing from normal nuget?

**Comment by juanfranblanco** [comment]
To install from the normal nuget you can just do the following 
'dotnet tool install -g Nethereum.Generator.Console'

We have updated the docs now https://nethereum.readthedocs.io/en/latest/nethereum-codegen-console/

**Comment by tmm360** [comment]
Perfect, it works! Thank you
