### ISSUE TITLE
State Mutability in FunctionABI

### ISSUE THREAD

**Issue by fiercef3l1n3** [Nethereum/Nethereum#547]
While deserializing a contract abi, I noticed that the FunctionABI model does not include information on whether the function is payable, pure, nonpayable or view. All of this information could be included by accessing the "stateMutability" property from the element and adding it to FunctionABI model. 

Would it be possible to enhance the FunctionABI model, please?

**Comment by juanfranblanco** [comment]
Yes, we have this as an issue already. But good to ask to prioritise. httpss://github.com/Nethereum/Nethereum/issues/379
