### ISSUE TITLE
Install-Package doesn't find Nethereum.Web3

### ISSUE THREAD

**Issue by fedecaccia** [Nethereum/Nethereum#549]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

## Expected Behavior
Install package

## Current Behavior
Error reported:
```
Install-Package : No se encontró ninguna coincidencia para el criterio de búsqueda especificado y el nombre de paquete
'Nethereum.Web3'. Prueba Get-PackageSource para ver todos los orígenes de paquete registrados disponibles.
En línea: 1 Carácter: 1
+ Install-Package Nethereum.Web3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

## Detailed Description
After creating a project following steps in https://nethereum.readthedocs.io/en/latest/getting-started/ I can't install package using Install-Package.
Using dotnet add package Nethereum.Web3 works, but when I compile, the compiler doesn't recognize the package:

`sample.cs(3,7): error CS0246: No se puede encontrar el tipo o el nombre de espacio de nombres 'Nethereum' (¿falta una           directiva using o una referencia de ensamblado?) `

**Comment by fedecaccia** [comment]
Hi @Dave-Whiffin !
VS: 1.33.1
dotnet sdk 2.2.203 (is dotnet what you are asking or how can I get the .NET version?)
Thanks!

**Comment by juanfranblanco** [comment]
@fedecaccia have you done a

``` dotnet restore ```

then a 

```dotnet build```

**Comment by fedecaccia** [comment]
Nope. Using vscode, from terminal that works without any warning nor error.
Anyway, how can execute the code from vscode? Should I try to compile with csc?

**Comment by juanfranblanco** [comment]
@fedecaccia to use it in vs code you will need to have the csharp extension, and it should compile when pressing F5 and have a csharp file selected.

What I normally do, when using vscode is have installed dot net and use the cli.
So I would use:
```dotnet restore``` to restore and download all the packages
```dotnet build``` to perform the build
```dotnet run``` to run your program, ie the console
```dotnet test``` to test it:)

**Comment by fedecaccia** [comment]
Genius, that worked propertly. Sorry about my ignorance. I came from unity and I don't know too much about NET frameworks. I was just testing to start developing on unity.

It's away from my initial issue, but I would like to know how to start integrating Nethereum on my unity scripts. I am helping using https://nethereum.readthedocs.io/en/latest/unity3d-sending-ether/ and https://github.com/Nethereum/Unity3dSimpleSample/blob/master/Assets/EtherTransfer.cs. Should I copy some .dll on my Unity project? In order to allow `using Nethereum`?

**Comment by juanfranblanco** [comment]
Yes to use Nethereum with Unity3d as it does not support nuget packages you need to copy the dlls into your asset folder. The latest dlls are here: https://github.com/Nethereum/Nethereum/releases
and the project structure should look like this https://github.com/Nethereum/Unity3dSimpleSample

**Comment by fedecaccia** [comment]
Great! Thanks for all your help!!
