### ISSUE TITLE
Investigation on general .net core / netstandard IPC implementation

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#55]
.Net does not support IPC in linux out of the box, this task is to investigate support of other frameworks like https://github.com/hhblaze/SharmIPC to create a port of the IPC implementation for Windows.

**Comment by juanfranblanco** [comment]
Try also https://github.com/AdaptiveConsulting/Aeron.NET

**Comment by juanfranblanco** [comment]
New json.net (^10) supports deserialization of large files / streaming objects

**Comment by djsowa** [comment]
I used mono implementation of UnixEndPoint and I implemented IPC client for Unix Domain Sockets to be used within Nethereum.
[Here is my implementation](https://github.com/djsowa/Nethereum/commit/bc2b61984e0975d665eb18fd93ac9b69875cfa51)

**Comment by juanfranblanco** [comment]
Many thanks to @djsowa  for all his help on this!!! Closed now.
