### ISSUE TITLE
AddressUtil.IsValidEthereumAddressHexFormat should not accept not hex characters

### ISSUE THREAD

**Issue by tmm360** [Nethereum/Nethereum#553]
## Expected Behavior
When I check an address with `AddressUtil.Current.IsValidEthereumAddressHexFormat(myAddress)` only valid addresses should pass the test.

## Current Behavior
Actually also addresses composed by characters that aren't hexadecimal values, but are letter, are accepted. For example, this address is considered valid: `0x0123456789ABCDEFGHIJKLMNOPQRSTUVXYWZabcd`

## Possible Solution
Fix the check replacing the filter function `char.IsLetterOrDigit` with another that exclude invalid letters.

## Steps to Reproduce
    if ("0x0123456789ABCDEFGHIJKLMNOPQRSTUVXYWZabcd".IsValidEthereumAddressHexFormat())
        Console.Write("I should not be printed");

**Comment by juanfranblanco** [comment]
Added now, thanks!
