### ISSUE TITLE
Question / Feature Request: How to Use IHttpClientFactory with Nethereum?

### ISSUE THREAD

**Issue by ryanelian** [Nethereum/Nethereum#559]
ASP.NET Core allows managed / pooled `HttpClient` using `HttpClientFactory` https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests which solves issues like socket exhaustion and stale DNS related to the original `HttpClient`.

I noticed that `Nethereum.JsonRpc.Client.RpcClient` constructor does not accept `HttpClient` unlike some other libraries (for example: https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs#L88) 

It'd be nice if I can pass `HttpClient` created by `IHttpClientFactory.CreateClient()` into Nethereum constructor to be used. Did I miss any API related to this feature?

**Comment by juanfranblanco** [comment]
Hi, you can use this in that scenario: https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.RpcClient/SimpleRpcClient.cs

The other RPC client handles socket exhaustion and stake DNS in a custom way to support earlier versions when this was an issue. Eventually they could be merged and make obsolete the custom implementation.

**Comment by ryanelian** [comment]
Thank you.

I have implemented the solution:

```cs
public class EthereumClientFactory
{
    private readonly AppSettings Settings;
    private readonly IHttpClientFactory HttpClientFac;

    public EthereumClientFactory(AppSettings appSettings, IHttpClientFactory httpClientFactory)
    {
        this.Settings = appSettings;
        this.HttpClientFac = httpClientFactory; 
    }

    public Nethereum.Web3.Web3 GetDefaultClient()
    {
        var uri = new Uri(Settings.EthereumRpcServer);
        var httpc = HttpClientFac.CreateClient();
        var rpc = new SimpleRpcClient(uri, httpc);
        var client = new Nethereum.Web3.Web3(rpc);
        return client;
    }
}
```

Then

```cs
services.AddHttpClient();
services.AddScoped<EthereumClientFactory>();
```

And I got a bad news for you, your implementation is slower than Microsoft's for some reason. Using your RPC implementation, I get 200-2000ms when checking balance, but with the official `HttpClientFactory` implementation, it's around 7ms.

Thanks, closing this issue.

**Comment by juanfranblanco** [comment]
Keeping it open :) When do you start your performance counters? How do you get a 2 seconds response?. 

Can you post a sample of your measuring so it can be justified the merge or just simple use the http factory for .net core and above in default class?

**Comment by juanfranblanco** [comment]
Here are some old performance tests https://github.com/Nethereum/TestPerformance so it will be great to add those for comparison

**Comment by ryanelian** [comment]
I put a stopwatch before creating the web3 client and benchmarked after all async calls using the client.

**Comment by juanfranblanco** [comment]
Ah.. I am trying to figure out if is due to creating the http client the first time, by putting before this
```csharp
 var uri = new Uri(Settings.EthereumRpcServer);
        var httpc = HttpClientFac.CreateClient();
        var rpc = new SimpleRpcClient(uri, httpc);
        var client = new Nethereum.Web3.Web3(rpc);
        return client;
```
or is the HttpClientFactory that takes the load befor injecting it.

**Comment by juanfranblanco** [comment]
Closing this, as there are not any major performance improvements for using the HttpClientFactory as default  https://github.com/Nethereum/TestPerformance and will mean an issue for backwards compatibility for other implementations. Now using .net core 2.1 surely improves performance as seen in Geth.
