### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by skarred14** [Nethereum/Nethereum#56]
It looks like the nuget packages v1.0.0-rc1 are not updates with methods for admin api. When can this be expected to be updated?

**Comment by juanfranblanco** [comment]
I have been testing the netstandard versions before release those. You can use portable for the time being if you are not constrained to core.

**Comment by juanfranblanco** [comment]
RC4 is out now for all the packages, netstandard 1.1, portable 111 and net451
