### ISSUE TITLE
 abnormal behavior of the nethereum package

### ISSUE THREAD

**Issue by MaxRos1234** [Nethereum/Nethereum#560]
I downloaded the Nethreum package via nuget and referenced it to a "console" .NET framework 4.6 application.
When I invoke any function (for example "unlock account"), the application closes unexplained without raising an exception (run / debug time).

First of all I started GETH by enabling the RPC:
.\geth.exe --datadir C:\gethdatadir\datadir1 account new 
.\geth --datadir C:\gethdatadir\datadir1\ init C:\gethdatadir\genesi.json 
.\geth --datadir C:\gethdatadir\datadir1\ --rpc --rpccorsdomain "*" --nodiscover --rpcapi db,eth,web3,miner,admin,personal,net --networkid 15 2>> C:\gethdatadlog\00.log

Launch the console application (code example) in debug mode :

   /// <summary>
        /// 
        /// </summary>
        /// <param name="abiRemix"></param>
        /// <param name="bytecodeRemix"></param>
        /// <param name="senderAddress"></param>
        /// <returns></returns>
        public async Task DeployContract(string senderAddress, string password)
        {
            var web3Client = new Web3();
         

            try
            {              

                var unlockResult = await web3Client.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(120));

                // here does not stop the cursor
            }
            catch (Exception ex)
            {                
				// here does not stop the cursor
                throw;
            }         

        }

I specify that on my machine there are no .Net framework prior to version 4.

thank you.

**Comment by Dave-Whiffin** [comment]
Hi - what version of the Nethereum nuget are you using?

**Comment by Dave-Whiffin** [comment]
Do you also have a reference to the "Nethereum" package owned by "knocte"?

**Comment by MaxRos1234** [comment]
No.

**Comment by Dave-Whiffin** [comment]
Have you tried the running the pre configured Nethereum test chain (geth)?

https://github.com/Nethereum/Testchains

Also - in your console app - how are you invoking the DeployContract function - can you share more of the code?

As you are using 4.6.1. you may need to set your TLS settings prior to calling the function.

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;

**Comment by MaxRos1234** [comment]
No,
I'm using GETH:

Version: 1.8.27-stable
Git Commit: 4bcc0a37ab70cb79b16893556cffdaad6974e7d8
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: windows
GOPATH=
GOROOT=C:\go


Snippet :

file1.cs 

using Nethereum.Hex.HexTypes;
using Nethereum.Web3;
using System;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    public class Runner
    {
       
              
        /// <summary>
        /// 
        /// </summary>
        /// <param name="senderAddress"></param>
        /// <param name="password"></param>
        /// <returns></returns>
        public async Task TryUnlockAccount (string senderAddress, string password)
        {
            var web3Client = new Web3();         

            try
            {            

                var unlockResult = await web3Client.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(120));
             
            }
            catch (Exception ex)
            {
                string message = ex.Message;
                throw;
            }        

        }
    }
}
 
MAIN:

using System;

namespace ConsoleApp3
{
    class Program
    {
        public void Run()
        {
            try
            {
                string senderAddress = "0x0d98fdba021bbae9e93a3402f261babbbf1bf1ac";
                string password = "pippo";
                Runner runner = new Runner();

             

                 runner.TryUnlockAccount(senderAddress, password).Wait();

            }
            catch (Exception ex)
            {
                string errore = ex.Message;
            }
        }

        static void Main(string[] args)
        {
            Program obj = new Program();

            obj.Run();
        }
    }
}

**Comment by Dave-Whiffin** [comment]
strange - can you try this?  (it uses a ulong instead of a HexBigInteger for the duration parameter)

```
        static void Main(string[] args)
        {
            var web3Client = new Web3();
            var unlockResult = web3Client.Personal.UnlockAccount.SendRequestAsync("<address>", "<password>", (ulong)60).Result;
        }
```

**Comment by MaxRos1234** [comment]
It goes!

I have the feeling that it is the incorrect use of the asynchronous pattern ...

Thank you

**Comment by Dave-Whiffin** [comment]
No problem - it's easily done!
