### ISSUE TITLE
CalculateTotalAmountToTransferWholeBalanceInEther Errors Upon Insufficient Balance

### ISSUE THREAD

**Issue by Enigmatic331** [Nethereum/Nethereum#562]
## Current Behavior
When we call CalculateTotalAmountToTransferWholeBalanceInEther on an empty/drained out account, a vague error is thrown:

![image](https://user-images.githubusercontent.com/28551011/59965511-cad6d300-9541-11e9-9251-9e91cee621e3.png)

This is as a negative balance after gas cost deduction is calculated, resulting in an error during UnitConversion.Convert.FromWei:

![image](https://user-images.githubusercontent.com/28551011/59965694-2bffa600-9544-11e9-8b62-f1858ab65f39.png)

![image](https://user-images.githubusercontent.com/28551011/59965680-0a9eba00-9544-11e9-963c-e55af825cf23.png)

## Expected Behavior and Possible Solution
While this could be fixed by having the developer checking for balance beforehand, or placing the process in a try-catch block, it might be worthwhile catching the error within CalculateTotalAmountToTransferWholeBalanceInEther for better clarity on error handling at least, e.g. "insufficient balance for transfer".

## Steps to Reproduce
Perform CalculateTotalAmountToTransferWholeBalanceInEther on an address without any ethers.
`            Dim Amount = Await iweb3.Eth.GetEtherTransferService().CalculateTotalAmountToTransferWholeBalanceInEther(addressFrom, 1)`

**Comment by juanfranblanco** [comment]
Yes great point :)
