### ISSUE TITLE
Get transaction list with detail

### ISSUE THREAD

**Issue by maysun-mayer** [Nethereum/Nethereum#564]
Hi
How can I get transaction list with their details?

**Comment by juanfranblanco** [comment]
web3.Eth.Blocks.GetBlockWithTransactions is one of them, just explore web3.Eth.Blocks or web3.Eth.Transactions for further rpc calls

**Comment by maysun-mayer** [comment]
Hi juan
How can I get just my transactions list?
every transaction where done in my account.
tnx

**Comment by Dave-Whiffin** [comment]
@maysun-mayer - Below is an example.  You need to crawl the blocks and retrieve the transactions for each block and then select the ones you want.

I'll close this issue as questions like these are better suited to our gitter channel - please feel free to contact us through that if you have any more queries: https://gitter.im/Nethereum/Nethereum

Example
https://github.com/Nethereum/Nethereum.Issues/blob/master/Net.Issues.Console/FindTransactionsForAddress/FindTransacactionsForAddress.cs

**Comment by maysun-mayer** [comment]
@Dave-Whiffin Thanks.
