### ISSUE TITLE
Too many CLOSE_WAIT in TCP stack

### ISSUE THREAD

**Issue by avtokey** [Nethereum/Nethereum#565]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

## Expected Behavior
There are many CLOSE_WAIT in TCP stack.
Screen: https://ibb.co/fXcn0fs

## Current Behavior
Need to dispose webSocket to close connection

## Possible Solution
use 'using' block to dispose websocket

## Steps to Reproduce
Screen which my net admin sent: https://ibb.co/fXcn0fs

## Detailed Description
In Nethereum.JsonRpc.WebSocketClient/WebSocketClient.cs Line 121 webScoket open but not disposed properly, which in my opinion causes CLOSE_WAIT in TCP stack. 

## Possible Implementation
```
 using (var webSocket = await GetClientWebSocketAsync().ConfigureAwait(false))
{
}
```

I change this block of code in my fork repository
here is link: https://github.com/avtokey/Nethereum/blob/master/src/Nethereum.JsonRpc.WebSocketClient/WebSocketClient.cs

**Comment by avtokey** [comment]
Only I have CLOSE_WAIT when use Netherium library>

**Comment by juanfranblanco** [comment]
@avtokey hi, apologies about the late response. The websocket client is designed to keep only one in memory and dispose it. So your implementation will mean that we will create a connection each time.

Is your websocket client getting disposed?

J

**Comment by avtokey** [comment]
> @avtokey hi, apologies about the late response. The websocket client is designed to keep only one in memory and dispose it. So your implementation will mean that we will create a connection each time.
> 
> Is your websocket client getting disposed?
> 
> J

May be this isn't best solution, but this way avoid many socket CLOSE_WAITs. Someone can pay attention about this important issue ? or only I have same problem ?

**Comment by avtokey** [comment]
Everybody can fix my Issue ? or Nethereum is Orphan ?

**Comment by juanfranblanco** [comment]
Hi @avtokey your implementation is not valid, like I said you need to dispose the websocket client yourself and keep a single instance of it.

**Comment by juanfranblanco** [comment]
Also you closed the issue.

**Comment by juanfranblanco** [comment]
To make it more clear, https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.WebSocketClient/WebSocketClient.cs#L14 as you can see the websocket client is disposable and is designed to keep using the same instance and reusing the connection in many calls in Web3. So implementing like I said closing the connection per each call will reduce the performance.
