### ISSUE TITLE
Indexed string in event cannot be parsed

### ISSUE THREAD

**Issue by greenkiller** [Nethereum/Nethereum#57]
Hi,

I deployed a straight forward smart contract as below and used GetAllChanges to get all events from block 0. GetAllChanges functions throws overflow exception when I tried to get the MultipliedLog event : 
Value was either too large or too small for an Int32

My testing shows that it happens when I put a "indexed" keyword after a string. Is it expected?
`event Multiplied(uint indexed a, uint indexed result, string hello); `
`event MultipliedLog(uint indexed a, address indexed sender, string indexed hello); `

**Comment by juanfranblanco** [comment]
Is SenderLog2 the same?

**Comment by juanfranblanco** [comment]
Also please raise another issue if it is changed :) (obviously not now)

**Comment by greenkiller** [comment]
Hi Juan,

Here is the DTO for MultipliedLog. Event Multiplied works well.

    public class EventMultipliedSenderLog
    {
        [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("uint", "a", 1, true)]
        public int A { get; set; }

        [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("address", "sender", 2, true)]
        public string Sender { get; set; }

        [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("string", "hello", 3, true)]
        public string Hello { get; set; }
    }

**Comment by greenkiller** [comment]
The C# code to get the events:
            var multipliedEvent = contract.GetEvent("MultipliedLog");
            var filterAll = await multipliedEvent.CreateFilterAsync(new Nethereum.RPC.Eth.DTOs.BlockParameter(0));
            var eventLogsAll = await multipliedEvent.GetAllChanges<EventMultiplied2>(filterAll);

Event Multiplied (with DTO EventMultiplied) works well. The only difference I can find is the "indexed" string.

**Comment by juanfranblanco** [comment]
Short story, retrieving the indexed values for dynamic types (strings, arrays) is not supported.
Long story:
The topics for indexed types if dynamics are stored as the SHA3 Keccak value (so they can be indexed and searched by matching the value).
Work around:
Use a bytes32, or don't index strings if you just want the data

**Comment by juanfranblanco** [comment]
So for example if you look at the index topic for "Hello world" it retrieves ed6c11b0b5b808960df26f5bfc471d04c1995b0ffd2055925ad1be28d6baadfd

**Comment by juanfranblanco** [comment]
Keeping it open as I need to validate the data part

**Comment by greenkiller** [comment]
I see. Thanks.

**Comment by juanfranblanco** [comment]
I have just pushed a fix which will allow to have indexed dynamic types as part of the Event DTO, mainly they will store the sha3 keccak string. This will no error will be thrown.

A further solution for your problem if you want to index and have the value of the string will be to 2 event parameters, 1 for the index and the other for the value.

**Comment by greenkiller** [comment]
Thanks for the prompt solution Juan!
