### ISSUE TITLE
StackOverflowException in ABIEncode

### ISSUE THREAD

**Issue by PaterSantyago** [Nethereum/Nethereum#572]
`ABIEncode.GetABIEncoded("1", "2", "3")`

## Expected Behavior
Returns abi-encoded array of bytes

## Current Behavior
StackOverflowException due to endless recursive call

## Possible solution
ConvertValuesToDefaultABIValues method of ABIEncode should return ABIValue[], GetABIEncoded(params object[] values) method should not convert result of ConvertValuesToDefaultABIValues call to object type.

**Comment by juanfranblanco** [comment]
Thanks fixed now
