### ISSUE TITLE
Error on parsing rpc response to BlockWithTransactions from geth 1.9.0

### ISSUE THREAD

**Issue by vlebedev7** [Nethereum/Nethereum#573]
Recently geth 1.9.0 was released and nethereum stopped returning blocks. 
An error happens on calling any block, here is an example: 
var block = _nethereumClient.Eth.Blocks.GetBlockWithTransactionsByNumber
                .SendRequestAsync(new BlockParameter(Convert.ToUInt64(8244765))).Result;

The error:
System.AggregateException: One or more errors occurred. (Unable to convert the result to type Nethereum.RPC.Eth.DTOs.BlockWithTransactions) ---> System.Exception: Unable to convert the result to type Nethereum.RPC.Eth.DTOs.BlockWithTransactions ---> System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.String'.

I compared json that new geth returns with json from Infura (Infura works fine with our code), the "size" is what I think the cause of the error:
![image](https://user-images.githubusercontent.com/5006907/62160646-4c3a3600-b336-11e9-97ae-f109cd32e09b.png)
Left: geth  |  Right: Infura

**Comment by juanfranblanco** [comment]
There is an issue with Geth, it will be solved on release 1.9.2. Mainly the output is not in the correct format.
