### ISSUE TITLE
No executable found ....

### ISSUE THREAD

**Issue by DWAK-ATTK** [Nethereum/Nethereum#574]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

Ubuntu 18.04 LTS, VS Code  

Created a new dotnet mvc app `dotnet new mvc`  
Added the Nethereum packages:
* `dotnet add package Nethereum.Web3`  
* `dotnet add package Nethereum.Autogen.ContractApi`  

Make a simple solidity file in the root of the project `simple.sol`.  
Pressed ctl-shift-p in VS Code and compiled the selected sol file. The appropriate abi and bin files appeared in the /bin directory.  

In Terminal window typed  `dotnet build`.  Got output: 
> Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
>
>  Restore completed in 612.26 ms for /home/dwak/jitc/Fall_Demo/Fall_Demo.csproj.
  Nethereum: Code generating dotnet files based on abi files in project and/or Nethereum.Generator.json
  No executable found matching command "dotnet-/home/dwak/.nuget/packages/Nethereum.Autogen.ContractApi/3.3.0/tools/Nethereum.Generator.Console.dll"
/home/dwak/.nuget/packages/nethereum.autogen.contractapi/3.3.0/build/Nethereum.Autogen.ContractApi.targets(14,5): error MSB3073: The command "dotnet ~/.nuget/packages/Nethereum.Autogen.ContractApi/3.3.0/tools/Nethereum.Generator.Console.dll generate from-project -p /home/dwak/jitc/Fall_Demo/Fall_Demo.csproj -a Fall_Demo.dll" exited with code 1. [/home/dwak/jitc/Fall_Demo/Fall_Demo.csproj]
>
>Build FAILED.
>
>/home/dwak/.nuget/packages/nethereum.autogen.contractapi/3.3.0/build/Nethereum.Autogen.ContractApi.targets(14,5): error MSB3073: The command "dotnet ~/.nuget/packages/Nethereum.Autogen.ContractApi/3.3.0/tools/Nethereum.Generator.Console.dll generate from-project -p /home/dwak/jitc/Fall_Demo/Fall_Demo.csproj -a Fall_Demo.dll" exited with code 1. [/home/dwak/jitc/Fall_Demo/Fall_Demo.csproj]
    0 Warning(s)
    1 Error(s)

## Expected Behavior

Should have generated some code I can work with.

## Current Behavior

Produces the error above.

## Context (Environment)
Ubuntu 18.04 LTS, VS Code

**Comment by juanfranblanco** [comment]
Hi,

The issue is that the nuget packages are put in a case sensitive folder.

The solution is to edit this file (for the time being until we release a new version)
/home/dwak/.nuget/packages/nethereum.autogen.contractapi/3.3.0/build/Nethereum.Autogen.ContractApi.targets

and 

replace it with this:

<Project>

  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
  </PropertyGroup>

   <PropertyGroup>
    <NugetVersion>3.3.0</NugetVersion>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Message Condition = "$(NethereumGenerateCode) != 'false'" Importance="high" Text="Nethereum: Code generating dotnet files based on abi files in project and/or Nethereum.Generator.json" />
    <Exec Condition = "$(IsWindows) == 'true' and $(NethereumGenerateCode) != 'false'" Command="dotnet &quot;%USERPROFILE%\.nuget\packages\nethereum.autogen.contractapi\$(NugetVersion)\tools\Nethereum.Generator.Console.dll&quot; generat$    <Exec Condition = "$(IsWindows) == ''  and $(NethereumGenerateCode) != 'false'" Command="dotnet ~/.nuget/packages/nethereum.autogen.contractapi/$(NugetVersion)/tools/Nethereum.Generator.Console.dll generate from-project -p $(Project$    <Message Condition = "$(NethereumGenerateCode) != 'false'" Importance="high" Text="Nethereum: Code generation finished." />
  </Target>

</Project>

**Comment by DWAK-ATTK** [comment]
Thank you @juanfranblanco
