### ISSUE TITLE
Contract address - stuck in infinite loop

### ISSUE THREAD

**Issue by manojpramesh** [Nethereum/Nethereum#58]
I am using the following code to get the contract address from transaction hash.

```
TransactionReceipt receipt = null;
while (receipt == null)
    {
         await Task.Delay(500);
         receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txHash);
    }
```

But it is stuck in the while loop like forever. It never retrieves the receipt. Hope you can help me in this.

**Comment by greenkiller** [comment]
On the Ethereum node you connected, run eth.getTransactionReceipt(txHash) and check if you can get it any result. If the transaction is not mined or the related block is not synced to your Ethereum node, it's expected it goes infinite loop.

**Comment by juanfranblanco** [comment]
If you are connected to your own private chain, make sure that you are mining. 
 You can start the mining process in geth or by using web3.Miner.Start.SendRequestAsync().

If your private chain difficulty is rather high, you might want to increase the waiting time. (or reset the chain if doing it for testing purposes)

**Comment by manojpramesh** [comment]
Thank you Juan/greenkiller. It worked for me after starting the miner.
