### ISSUE TITLE
DTO can't work with uint8[]

### ISSUE THREAD

**Issue by CKKwan** [Nethereum/Nethereum#584]
```
[FunctionOutput]
public class SomeDTO
{
    [Parameter("uint8[]", "value", 1)]
    public byte[] Value { get; set; }
}
```

The above code throw **"No parameterless constructor defined for this object"** exception, when I am trying to retrieve using **CallDeserializingToObjectAsync**

I do not have any problem with other variable types.

**Comment by juanfranblanco** [comment]
@CKKwan  apologies, I have just seen this I was off at the time. You need a List<int> instead of a byte[], you can use any of the code generators to help you. http://docs.nethereum.com/en/latest/nethereum-code-generation/

or try the playground.nethereum.com abi code generator too, if you want to test it directly in the browser.

**Comment by CKKwan** [comment]
Thanks juanfranblanco, However when I change to:

`public List<byte> Value { get; set; }`

The error message that I received is:

`Value was either too large or too small for an Int32.`

**Comment by juanfranblanco** [comment]
Thanks @CKKwan ill have a look, it should not be any differences. Can you post your abi / function snippet?

**Comment by CKKwan** [comment]
@juanfranblanco sorry for coming back late.

Code snippet as below:

    contract MyContract {
        struct MyStruct {
            uint8[] MyUint8;
        }
        mapping(uint32 =>MyStruct) public MyStructs;
    }

    [FunctionOutput]
    public class MyStructDTO : IFunctionOutputDTO
    {
        [Parameter("uint8[]", "MyUint8", 1)]
        public byte[] MyUint8 { get; set; }
    }

**Comment by juanfranblanco** [comment]
Have you tried with:

[FunctionOutput]
public class MyStructDTO : IFunctionOutputDTO
{
    [Parameter("uint8[]", "MyUint8", 1)]
    public List<int> MyUint8 { get; set; }
}

and check the code generator, it will help you to do the type mappings

**Comment by CKKwan** [comment]
If I use List<int> I always get back 4 zeros.

If I use BigInteger, I always get back garbage. (the content is there, but somehow it interpreted wrongly)

**Comment by juanfranblanco** [comment]
I'll do a sample for you... are you acceding the struct using the public mapping or another function?

**Comment by CKKwan** [comment]
I directly accessing the structure using the public mapping. There is no other function.

    var w = new Web3(NodeUrl);
    var c = w.Eth.GetContract(ABI, ContractAddress);
    var f = c.GetFunction("MyStructs");
    var r = f.CallDeserializingToObjectAsync<MyStructDTO>(MyUint32).Result;

**Comment by shargon** [comment]
Any update ?

**Comment by juanfranblanco** [comment]
Variable access through properties sometimes require to be accessed directly as the output not as a function.
