### ISSUE TITLE
How to get Eth.pendingTransactions

### ISSUE THREAD

**Issue by supersbbb** [Nethereum/Nethereum#59]
Since i found no API is available in web3.eth.pendingTransactions, I am wondering how can i get web3.eth.pendingTransactions part in my C# program. Thank you.

**Comment by juanfranblanco** [comment]
This might help you: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter

**Comment by tanderbold** [comment]
This filter return an information about new pending transactions only. We can not recieve information about all pending transactions in wallet.
