### ISSUE TITLE
SendTransactionAndWaitForReceiptAsync always  throwing error

### ISSUE THREAD

**Issue by AkhilKRTH** [Nethereum/Nethereum#591]
Always getting this error 

Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).

when calling SendTransactionAndWaitForReceiptAsync

**Comment by Dave-Whiffin** [comment]
Hi there,  we deal with support requests via gitter, would you mind raising this over there please?    It's unlikely this is a bug so I am closing it here for now as gitter is a better place to discuss. 

https://gitter.im/Nethereum/Nethereum
