### ISSUE TITLE
How to get TransactionReceipt by hash directly in  Nethereum?

### ISSUE THREAD

**Issue by johnny0618** [Nethereum/Nethereum#592]
In web3 ,we could query a transaction status by directly hash.
like this

eth.getTransactionReceipt(transactionHash),it will return

{ blockHash: '0xb1fcff633029ee18ab6482b58ff8b6e95dd7c82a954c852157152a7a6d32785e',
  blockNumber: 4370000,
  contractAddress: null,
  cumulativeGasUsed: 21000,
  gasUsed: 21000,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  root: null,
  status: 1, // **** HERE IS THE STATUS FIELD *****
  transactionHash: '0x1421a887a02301ae127bf2cd4c006116053c9dc4a255e69ea403a2d77c346cf5',
  transactionIndex: 0 }

But in Nethereum, After searched all the docs, I found noway to get status directly by a hash. All the docs offer the way is send a transaction by Nethereum then get the Receipt in the return. But I want to query it by a hash ,Is there anyway to do this?

**Comment by Dave-Whiffin** [comment]
Hi there, thanks for the question.   We use GitHub issues for bugs and feature requests. We handle support queries like this via gitter.  Would you mind raising it there?  I promise you'll get a quick response.

https://gitter.im/Nethereum/Nethereum

**Comment by johnny0618** [comment]
Thank you
