### ISSUE TITLE
 UnlockAccount via Infura

### ISSUE THREAD

**Issue by haimHadad** [Nethereum/Nethereum#594]
I am trying to connect my wallet (Metamask) via Infura, but I receiving an error.
My code: 

    `[HttpPost]
            public async Task<IActionResult> LoginAsync([ModelBinder(typeof(AccountBinder))] Account acc)
            {
                try
                {
                    Account.ValidateAddress(acc.AccountAddress);
                    var web3 = new Web3(acc.AccountNetwork + "" + acc.InfuraApiKey); //infura Ropsten+ProjectID
                    var balance = await web3.Eth.GetBalance.SendRequestAsync(acc.AccountAddress);  //works fine
                    var etherAmount = Web3.Convert.FromWei(balance.Value); //works fine
                    acc.AccountBalance = (double)etherAmount;        
                    var unlockAccountResult = await web3.Personal.UnlockAccount.SendRequestAsync(acc.AccountAddress, acc.AccountPassword, 60);   //not working!!!!!!!! <- <- <-
                    if (unlockAccountResult)
                    {
                        acc.IsValidated = true;
                        return View("Login", acc);
                    }
                    else
                        throw new WrongAccountDetails("Incorrect account or password");
                }
                catch (WrongAccountDetails ex)
                {
                    ...
                }
            }`

The error: 

An unhandled exception occurred while processing the request.
RpcResponseException: The method personal_unlockAccount does not exist/is not available
Nethereum.JsonRpc.Client.ClientBase.HandleRpcError(RpcResponseMessage response)
Nethereum.JsonRpc.Client.ClientBase.HandleRpcError(RpcResponseMessage response)
Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync<T>(RpcRequestMessage reqMsg, string route)
Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync<T>(RpcRequest request, string route)
Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync<T>(RpcRequest request, string route)
RealEstate_Web_app.Controllers.AccountController.LoginAsync(Account acc) in AccountController.cs
+
                var unlockAccountResult = await web3.Personal.UnlockAccount.SendRequestAsync(acc.AccountAddress, acc.AccountPassword, 60);
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by juanfranblanco** [comment]
Hi, you cannot use a managed account by Geth / Parity with Infura. This will mean they will hold your keystore with private keys. 

Please check for info http://docs.nethereum.com/en/latest/accounts/

But simply if you want to use a Metamask seed phrase check this 
http://docs.nethereum.com/en/latest/Nethereum.Workbooks/docs/nethereum-managing-hdwallets/

also you can run online this sample 
http://playground.nethereum.com/csharp/id/1043
