### ISSUE TITLE
Deploy a smart contract using Infura

### ISSUE THREAD

**Issue by haimHadad** [Nethereum/Nethereum#597]
Is it possible to deploy a smart contract in Nethereum using Infura?
I know we cannot use web3.Personal.UnlockAccount.SendRequestAsync because Infura doesn`t hold private keys, but Nethereum allow us to use their Account object =>

( var account = new Account(privateKey) ).

In addition, the command await web3.Miner.Start.SendRequestAsync(6) doesn`t compiled because Miner doesnt exist...

Haim

**Comment by juanfranblanco** [comment]
Hi, 

Yes you can deploy an smart contract using Infura, like you said use instead the Account with your private key so it will sign "offline" your transaction.

web3.Miner has been moved to the Geth  library as it is client specific feature. If you try any of the preconfigured https://github.com/Nethereum/TestChains those simplify development as they use Poa which is a faster consensus and they are setup to start mining automatically.

**Comment by haimHadad** [comment]
Smart contract deployment - will this code work? Asking this because of the miner problem, to see I didn't miss anything:  
                    
         `
        public void DeployContract() //for example
        {
            var senderAddress = "0x...";
            var privateKey= "...";
            var abi = @"...";
            var byteCode = "...";
            var multiplier = 7;

            var web3 = new Web3.Web3(/* Nethereum Account object*/ , /* Infura URL*/);

            var transactionHash = await web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, senderAddress, new HexBigInteger(900000), multiplier);
            var receipt = await MineAndGetReceiptAsync( web3   ); 

            /*and then receipt.ContractAddress........... and so on */
        }

        public async Task<TransactionReceipt> MineAndGetReceiptAsync(Web3 web3, string transactionHash)
        {
           //=>I took this code from your web and from elsewhere
           //=> Importan: Web3 web3 paramater here replaced the other one  Web3.Web3 web3 because it did`nt compiled 
            var web3Geth = new Web3Geth(web3.Client);
            var miningResult = await web3Geth.Miner.Start.SendRequestAsync(6); ;
            if (miningResult != true) throw new Exception("Could not start mining");

            var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);

            while (receipt == null)
            {
                Thread.Sleep(1000);
                receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
            }

            miningResult = await web3Geth.Miner.Stop.SendRequestAsync();
            return receipt;
        }
              `

**Comment by juanfranblanco** [comment]
@haimHadad Yes that should work, but if you are connecting to infura (remote node) you don't need to control the mining process. Please check the different samples in http://playground.nethereum.com or http://docs.nethereum.com.

We have some examples on how to get started http://docs.nethereum.com/en/latest/nethereum-smartcontrats-gettingstarted/ also check:

Interactive sample:
Typed version when the contract definition is all described using classes
http://playground.nethereum.com/csharp/id/1007

or 
Untyped when the contract definition is extracted from the abi
http://playground.nethereum.com/csharp/id/1045

**Comment by haimHadad** [comment]
I deleted the mining line and simply deployed the contract as we discussed in [here](https://github.com/Nethereum/Nethereum/issues/600). 
Here is the code: 

        `                   
        var receiptContract = await web3Test.Eth.DeployContract.SendRequestAsync(contractABI, contractByteCode, senderAddressTest, new HexBigInteger(900000));
         `
But I wonder, in many samples, I saw this line too later: 

        `receiptContract.ContractAddress //.... and so on`

But in my case receiptContract doesn`t see ContractAddress. Instead, I recieved a simple string which probably represents an contract address =>Here it is:

 "0xdd58facf20a6169c01ad0f34f89a12c3a914ba9b0a7ae7be4676fe509d1f24a1". 

I checked in Etherscan : [Here is the link](https://ropsten.etherscan.io/tx/0xdd58facf20a6169c01ad0f34f89a12c3a914ba9b0a7ae7be4676fe509d1f24a1) And its seems that the contract successfully deployed (also: my account address appears there).
### **Now I`m asking you, is this the right way to deploy after all?**

**Comment by haimHadad** [comment]
Well, I see now that its deploy a transaction, and not the contract.
Also, the address I received is longer than the address of the  smart contract I deployed in RemixIDE.

**Comment by haimHadad** [comment]
Here is the correction (sorry, I am beginner):

      `
        var receiptContract = await web3Test.Eth.DeployContract.SendRequestAndWaitForReceiptAsync(contractABI, contractByteCode, senderAddressTest, new HexBigInteger(900000), null);
        contractAddress = receiptContract.ContractAddress;
      `

Reminder: No constructor here, so in web3Test.Eth.DeployContract.SendRequestAndWaitForReceiptAsync there are 5 params instead of 6.

**Comment by juanfranblanco** [comment]
@haimHadad we solved this in gitter ❤so I am closing now.
