### ISSUE TITLE
Nethereum returns addresses in lower case letters only

### ISSUE THREAD

**Issue by haimHadad** [Nethereum/Nethereum#608]
I've got a solidity method that returns address: 

       `      
       function getAssetBuyer() public view returns(address) 
       {
            return buyerAddress;
       }
     `

The call from c# (Nethereum) is :

    `
        public async Task<string> getBuyerAddress() //get the address of the buyer which included in the deal
        {
            var getAssetBuyerFunction = deployedContractIsntance.GetFunction("getAssetBuyer");
            var assetBuyerAddress = await getAssetBuyerFunction.CallAsync<string>();
            return assetBuyerAddress;
        }

But the output is incorrect, Nethereum return string in lower case letters:
Instead of:   0x9Bd6dc66e611Ae28344D52C4CF6167C98A1Aac43
I get: 0x9bd6dc66e611ae28344d52c4cf6167c98a1aac43

Remix at testnet returns 0x9Bd6dc66e611Ae28344D52C4CF6167C98A1Aac43 (correct)
    `

**Comment by haimHadad** [comment]
I also tried : 

    `
        var assetBuyerAddress = await getAssetBuyerFunction.CallAsync<String>();
    `

But it didn`t work.

**Comment by dothanhbinh41** [comment]
try it out :D
```
AddressUtil.ConvertToChecksumAddress(string address)
```

**Comment by juanfranblanco** [comment]
The checksum address is used for visual purposes, applying formatting when interacting with smartcontracts or the just the chain, will add a performance overhead that is not necessary. The value is always the same, regardless of the casing.
