### ISSUE TITLE
Goerli Network - Difference in RPC response between Parity and Geth

### ISSUE THREAD

**Issue by Enigmatic331** [Nethereum/Nethereum#610]
Parity and Geth maintains a slightly different RPC response when we call eth.getBlock, namely Parity uses **sealFields** to hold nonce and mixhash values, whereas Geth has dedicated two similarly named fields for these two values.

Parity:
![image](https://user-images.githubusercontent.com/28551011/71610392-8781af00-2bcb-11ea-9478-51e3f9aed95c.png)

Geth:
![image](https://user-images.githubusercontent.com/28551011/71610464-3625ef80-2bcc-11ea-8fa8-e4d48527d258.png)

This results in issues when attempting to call RecoverCliqueSigner (basically the wrong signer is returned), as the BlockHeader construction expects a corresponding mixhash and nonce field from the RPC returns.

![image](https://user-images.githubusercontent.com/28551011/71610417-d596b280-2bcb-11ea-9cc9-79bde1df0010.png)

Suggestion: Could we look into retrieving the sealFields data into mixhash and nonce correspondingly, if the client is Parity (or we look for sealFields if nonce && mixhash == Nothing)?

Much <3 Juan.

**Comment by juanfranblanco** [comment]
Yes, we could do that and wait and see what other clients do.  The nonces and mixhash do not match, is there any other step we need to do here?

**Comment by Enigmatic331** [comment]
I think Parity uses RLP encoding for their sealFields (i.e. https://github.com/paritytech/parity-ethereum/issues/1090). So we might want to account for that.

Just sharing - Seems like someone's looking into this recently as well: https://github.com/paritytech/parity-ethereum/issues/11318

**Comment by Enigmatic331** [comment]
Hmmm. I am not sure if the beta version has the a0 and 88 prepend removed - I should probably try it out (am currently running the latest stable release 2.5.13). Thought parity-ethereum#1090 should have sorted that bit out.

**Comment by juanfranblanco** [comment]
Yes reading the comments, they had the same issue, both a0 and 88, and later a patched followed.

**Comment by juanfranblanco** [comment]
https://github.com/paritytech/parity-ethereum/blob/2a9d3b09f9b25ff7875948bc2b6f52693b77e1b4/ethcore/src/header.rs#L350-L351

Well that is what they want to achieve :)

**Comment by juanfranblanco** [comment]
I have added an extra parameter to the factory.

```BlockHeaderRPCFactory.FromRPC(block, true);```

So you can do something like this:

```csharp
var block = await web3.Eth.Blocks.GetBlockWithTransactionsByNumber.SendRequestAsync(new HexBigInteger(1));
var blockHeader = BlockHeaderRPCFactory.FromRPC(block, true);
var account = new CliqueBlockHeaderRecovery().RecoverCliqueSigner(blockHeader); Assert.True(AccountFactory.Address.IsTheSameAddress(account));
```

And the check is the following: 
```csharp
  if (mixHasAndhNonceInSealFields && rpcBlock.SealFields != null && rpcBlock.SealFields.Length >= 2)
            {
                blockHeader.MixHash = rpcBlock.SealFields[0].HexToByteArray();
                blockHeader.Nonce = rpcBlock.SealFields[1].HexToByteArray();
            }
            else
            {
                blockHeader.MixHash = rpcBlock.MixHash.HexToByteArray();
                blockHeader.Nonce = rpcBlock.Nonce.HexToByteArray();
            }
```
Let's see how this goes before adding the extra checks for the bugs.

**Comment by juanfranblanco** [comment]
Ok after some calculations..

A0 is the RLP of the length, so that is A0 - 80 (OFFSET_SHORT_ITEM = 80).. which is 32 bytes or 256 bits, the length of the mixhash. So in very simple terms if it is starts with A0 and the length is  33 bytes. It can be removed.

Similar to 88.

88 - 80 = 8 bytes is the length of the nonce, which is 64 bits. Similarly if we have 9 bytes and the first one is 88 that can be removed.

**Comment by Enigmatic331** [comment]
Juan is the best. <3 Closing this issue.
