### ISSUE TITLE
Nethereum need install ethereum core?

### ISSUE THREAD

**Issue by ex247365** [Nethereum/Nethereum#614]
Hi.
I'm a beginner coin developer.
for use Nethereum need to install ethereum core?
Best Regards.

**Comment by juanfranblanco** [comment]
Hi, 
Questions are better handled in our chat channel in gitter https://gitter.im/Nethereum/Nethereum. 
You will need to run a test client to develop, or just point to a public testnet. For more information check this http://docs.nethereum.com/en/latest/ethereum-and-clients/.

We have preconfigured testchains https://github.com/Nethereum/Testchains 
The best thing to get started is to run of those clients for development.

If you just want something to learn straight away about creating your own token and interacting with smart contracts. Check this document http://docs.nethereum.com/en/latest/nethereum-smartcontrats-gettingstarted/
and you can start coding and experimenting with the Nethereum playground here which points to our simple testing chain.  http://playground.nethereum.com/csharp/id/1007

**Comment by juanfranblanco** [comment]
Closing this now
