### ISSUE TITLE
Deprecated Solidity 0.6.0 ABI keyword constant

### ISSUE THREAD

**Issue by Enigmatic331** [Nethereum/Nethereum#615]
Currently our Nethereum library detects a functionABI using the keyword "constant":

![image](https://user-images.githubusercontent.com/28551011/72411213-6614eb80-37a5-11ea-97f9-dfdb20fbc32a.png)

With Solidity 0.6.0, ABIs generated will no longer have the "constant" keyword, but is replaced with stateMutability = "view":

> [{"inputs":[{"internalType":"string","name":"_a","type":"string"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"uint256","name":"_number","type":"uint256"}],"name":"giveMeNumber","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],**"stateMutability":"view"**,"type":"function"},{"inputs":[{"internalType":"uint256","name":"_number","type":"uint256"}],"name":"giveMeString","outputs":[{"internalType":"string","name":"someString","type":"string"}],**"stateMutability":"view"**,"type":"function"},{"inputs":[],"name":"myNumber","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],**"stateMutability":"view"**,"type":"function"},{"inputs":[{"internalType":"uint256","name":"test","type":"uint256"}],"name":"sendMeMoney","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"someString","outputs":[{"internalType":"string","name":"","type":"string"}],**"stateMutability"**:"view","type":"function"}]

## Current Behavior
Attempting to deploy (also to interact with) a contract >=0.6.0 will return an error:
![image](https://user-images.githubusercontent.com/28551011/72412208-c4db6480-37a7-11ea-9653-6fe538a9f4dd.png)

## Possible Solution
We might want to look into supporting both constant (for backwards compatibility) and stateMutability when looking up FunctionABI. I believe also the payable flag changed on the ABI too, where for example `"payable":false` is deprecated in favour of `"stateMutability":"nonpayable"`

**Comment by juanfranblanco** [comment]
Thanks @Enigmatic331 your pull solved this issue and is live now. I have added these to the code generators, and support for internal types, structs types / names too.
