### ISSUE TITLE
Unterminated string. Expected delimiter

### ISSUE THREAD

**Issue by Alan-Lun** [Nethereum/Nethereum#617]
```
using (var client = new WebSocketClient("wss://main-net"))
{
    _Web3 = new Web3(client);
    var buildRequest = _Web3.Eth.Transactions.GetTransactionReceipt.BuildRequest(transactionHash);
    var transactionReceipt = await client.SendRequestAsync<TransactionReceipt>(buildRequest);
 }
```

throw exception :
Unterminated string. Expected delimiter: \". Path 'result.logs[3].data', line 1, position 4082.

Call Http is work , Socket is exception , But I need Socket. Help~

**Comment by juanfranblanco** [comment]
Closing as resolved the usage of Web3 in gitter using web3.Transactions.GetTransactionReceipt.SendRequestAsync
although @Alan-Lun  has issues connecting to his server. Will reopen if needed

**Comment by Alan-Lun** [comment]
@juanfranblanco 
Does this question have an answer?

**Comment by juanfranblanco** [comment]
@Alan-Lun Good point i will reopen as your case is strange but worth to mention for

**Comment by Alan-Lun** [comment]
Very Very Thank you.

**Comment by Alan-Lun** [comment]
After updating to 3.7.1, the issue is resolved
