### ISSUE TITLE
Code Gen: Throwing null ref exception when no constructor in ABI

### ISSUE THREAD

**Issue by Dave-Whiffin** [Nethereum/Nethereum#618]
I compiled a Solidity contract using 0.6.1 which did not contain a constructor (in the Solidity code).  Therefore there was no constructor in the ABI.  When I code generated a null ref exception was thrown.

The code templates in the generator reference the ConstructorABI property of the Contract ABI but the ConstructorABI is null.  

## Expected Behavior
The code should have been generated without an error.

## Current Behavior
A null ref exception is thrown in ContractDeploymentCQSMessageCSharpTemplate.GenerateClass.  

``` csharp
{_parameterAbiFunctionDtocSharpTemplate.GenerateAllProperties(Model.ConstructorABI.InputParameters)}
```

## Possible Solution
Change implementation to check for null:

``` charp
{_parameterAbiFunctionDtocSharpTemplate.GenerateAllProperties(Model.ConstructorABI?.InputParameters ?? Array.Empty<ParameterABI>())}
```

Or consider creating a default constructor with any empty parameter array during ABI deserialisation.

## Steps to Reproduce
Create Solidity contract without a constructor.  
Compile (I was using 0.6.1). 
Auto gen using ABI - I used Nethereum.Autogen.ContractApi 3.6.0

**Comment by juanfranblanco** [comment]
Do you have the same issue with vscode?

**Comment by Dave-Whiffin** [comment]
vscode seems to be ok.

**Comment by juanfranblanco** [comment]
Thanks, that won't work.. remember javascript.
```{_parameterAbiFunctionDtocSharpTemplate.GenerateAllProperties(Model.ConstructorABI?.InputParameters ?? Array.Empty<ParameterABI>())```

That can be solved at the .net level to ensure an empty array on the Generators.Net

**Comment by Dave-Whiffin** [comment]
I understand the JS thing, but I am a bit confused, it's not the input parameter array that is null, it's the constructor.   

Is it the null coalescing operator that is the JS issue - or is it Array.Empty<> as well?  I am guessing it's both.

Do we add a null check in GeneratorModelABIDeserialiser DeserialiseABI instead and assign a default constructor with an empty input parameter array which will keep the class templates happy?

**Comment by juanfranblanco** [comment]
The deserialiser creates an empty list anyway of Parameters, so needs more investigation.
