### ISSUE TITLE
extended pubkey

### ISSUE THREAD

**Issue by FIVIL** [Nethereum/Nethereum#629]
I was wondering if Nethereum supports extended pubkeys (I went through the documentation and also did some googling, but I couldn't find anything in this regard). 
Also if you aren't currently supporting this feature is there any plan to add it in the near future??

PS: extended pubkeys let users to store a master public key of the account and then drive other accounts addressed only using that public key without requiring the private key which lets users separate their cold and hot wallets.

**Comment by juanfranblanco** [comment]
Hi check the latest. See the usage here for your needs, just use the hex string of your ExtendedPublicKey. https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.HdWallet.UnitTests/WalletTests.cs#L124-L134

**Comment by FIVIL** [comment]
@juanfranblanco 
Thank you for your answer. I am using Nethereum in a .net core project and I am having `Nethereum` and `Nethereum.HdWallet` (V 3.7.1, which is the latest version according to Nuget) packages installed. However, I can't see the function `GetMasterExtPubKey`  or any function related to extended pubkeys in `HdWallet` Object. 
Should I install another package? or build the latest package from the source code instead of installing it from Nuget??

**Comment by juanfranblanco** [comment]
This is all new, so it will be in the next release, or you can get latest and compile. The CI build is not ready yet.

**Comment by FIVIL** [comment]
@juanfranblanco
I see. 
Tnx
