### ISSUE TITLE
Nethereum.ABI nuget package fails to install

### ISSUE THREAD

**Issue by rgravesdg** [Nethereum/Nethereum#63]
The project's target framework is .NET Framework 4.6.1

Install-Package : Failed to add reference. The package 'Nethereum.ABI' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is 
possibly a bug in the package. Please contact the package owners for assistance.
At line:1 char:1
+ Install-Package Nethereum.ABI -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by juanfranblanco** [comment]
you need to add System.Runtime.. I will be releasing a new update today for RC4.

**Comment by rgravesdg** [comment]
Yes the System.Runtime package is installed.  I'll give it a try with the RC4.

PM> Get-Package

Id                                  Versions                                 ProjectName                                                                               
--                                  --------                                 -----------                                                                               
Nethereum.Hex                       {1.0.0-rc1}                              NethereumTest                                                                            
Newtonsoft.Json                     {9.0.1}                                  NethereumTest                                                                            
Portable.BouncyCastle               {1.8.1.1}                                NethereumTest                                                                            
System.Collections                  {4.0.11}                                 NethereumTest                                                                            
System.Diagnostics.Debug            {4.0.11}                                 NethereumTest                                                                            
System.Globalization                {4.0.11}                                 NethereumTest                                                                            
System.IO                           {4.1.0}                                  NethereumTest                                                                            
System.IO.FileSystem                {4.0.1}                                  NethereumTest                                                                            
System.IO.FileSystem.Primitives     {4.0.1}                                  NethereumTest                                                                            
System.Linq                         {4.1.0}                                  NethereumTest                                                                            
System.Reflection                   {4.1.0}                                  NethereumTest                                                                            
System.Reflection.Extensions        {4.0.1}                                  NethereumTest                                                                            
**System.Runtime                      {4.1.0}                                  NethereumTest**                                                                            
System.Runtime.Extensions           {4.1.0}                                  NethereumTest                                                                            
System.Text.Encoding                {4.0.11}                                 NethereumTest                                                                            
System.Threading                    {4.0.11}                                 NethereumTest                                                                            
System.Threading.Tasks              {4.0.11}                                 NethereumTest

**Comment by juanfranblanco** [comment]
It is out now :) Let me know how it goes

**Comment by juanfranblanco** [comment]
It is netstandard 1.1, 4.51, and portable 111

**Comment by rgravesdg** [comment]
Thanks, the new version installed correctly.

**Comment by juanfranblanco** [comment]
Great!!
