### ISSUE TITLE
Package collision

### ISSUE THREAD

**Issue by FIVIL** [Nethereum/Nethereum#630]
Hi
I have to use `Nethereum` and `Nbitcoin` at the same time. However, after installing Nbitcoin some functionalities of Nethereum stops working.
for example, while creating new HDWallert from a seed phrase I get this exception:
```System.TypeLoadException: 'Method 'GetBytes' in type 'Nethereum.HdWallet.SecureRandom' from assembly 'Nethereum.HdWallet, Version=3.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'```
I believe this is due to Nethereum using an older version (4.x.x) of Nbitcoin than the latest major release (5.x.x). Nonetheless, I need some functionalities of the latest Nbitcoin release. So I was wondering if it is not much trouble for you to update Nethereum so it can work with the latest Nbitcoin.

PS: My project targets `.net core 3.1`
TNX

**Comment by juanfranblanco** [comment]
The latest version of the HD Wallet has the latest of NBitcoin. Although not released yet, this is also the same package that you need for your "PublicWallet"

**Comment by FIVIL** [comment]
Ahhh, I see. That's great. However, I actually couldn't get my supervisors' permission to use `Nethereum` out of Nuget official releases. So I was wondering when this new version will be available on Nuget?
Tnx for all the help.

**Comment by juanfranblanco** [comment]
This is released now.
