### ISSUE TITLE
Can't deploy contract and proxy at the same time.

### ISSUE THREAD

**Issue by commentors-net** [Nethereum/Nethereum#633]
Hi,
This isn't a bug or issue but more of a question, since I couldn't find where to ask the question in relation to Nethereum.

I can deploy contract using the following code from Nethereum
`TranHash = await web3.Eth.DeployContract.SendRequestAsync
                (abiContract, byteCodeContract, ConnectNethereum.MainAddress, new Nethereum.Hex.HexTypes.HexBigInteger("470000"));`

at the same I have Proxy abi which I like to deploy.
It can be achieved using truffle's javascript file (1_deploy_contracts.js) like below 

`const CTRRT = artifacts.require('CTRRTImplementation');
const Proxy = artifacts.require('AdminUpgradeabilityProxy');

module.exports = async function(deployer) {
  await deployer;

  await deployer.deploy(CTRRT);
  const proxy = await deployer.deploy(Proxy, CTRRT.address);
  const proxiedCTRRT = await CTRRT.at(proxy.address);
  await proxy.changeAdmin("0x0000000000000000000000000000000000000000");
  await proxiedCTRRT.initialize();
};`

I have tried few options but I can't seem to achieve this in Nethereum.
Am I missing something?

**Comment by juanfranblanco** [comment]
hi, just pop over for a chat at Gitter: https://gitter.im/Nethereum/Nethereum

The best thing is to code generate your smart contract interface, far much easier, check this https://docs.nethereum.com/en/latest/nethereum-codegen-vscodesolidity/, or simply just right click in vscode in your solidity contract and click compile and code generate to C#.

This creates your contract definition and deployment. 

You can do it for both your proxy and implementation.

Then you can follow this example for deployment for both http://playground.nethereum.com/csharp/id/1006
