### ISSUE TITLE
Nethereum.Generators generating parameters with reserved words in C#

### ISSUE THREAD

**Issue by buddhamangler** [Nethereum/Nethereum#636]
I noticed this issue when generating C# code from the contract for ecr-1155 https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155.sol

As an example, one of the functions generated from this contract is

```
        public Task<string> SetApprovalForAllRequestAsync(string operator, bool approved)
```

This does not compile, operator is a reserved word.

## Expected Behavior
The generator should properly prevent the use of reserved words in C#

## Current Behavior
The generator generates code that does not compile

## Possible Solution
If a reserved word would be used, instead use a name that does not collide with a reserved word

## Steps to Reproduce
Generate code for contract https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155.sol

## Context (Environment)
vscode

**Comment by juanfranblanco** [comment]
Thank you for reporting this, yes operator is a keyword in C#

For reference on C# https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
 
And a specific language extension is needed as per Types.. although for future extensibily (ie UI, xaml, razor etc) should not be coupled to the ABI, but in Core. It should be consumed here.
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Generators/ABI/GeneratorModel/ParameterABIModel.cs

**Comment by buddhamangler** [comment]
> Thank you for reporting this, yes operator is a keyword in C#
> 
> For reference on C# https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
> 
> And a specific language extension is needed as per Types.. although for future extensibily (ie UI, xaml, razor etc) should not be coupled to the ABI, but in Core. It should be consumed here.
> https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Generators/ABI/GeneratorModel/ParameterABIModel.cs

Correct, I was able to find the exact same spot.  Odds on this getting addressed?  I have the code locally, and I am new to Eth so poking around.  I could change the contract to skirt the generation issue, but I am concerned that would invalidate certain assumptions of other code whether that be contract code or not, that assumes a particular signature for this type of token contract standard.  I am not really sure if changing the parameter names would have this ill intended effect or not.

What are the odds this could be addressed?  I could take a stab at a pr, but there is a lot going on here.

**Comment by juanfranblanco** [comment]
Yes, simple thing for the time being is just to rename the parameter, this won't affect anything as parameters signatures are not driven by the parameter names. You could just rename it on the generated code, being the standard it will be one off anyway. I will look into it as a priority anyway as this is key for all users that are consuming external contracts.

**Comment by buddhamangler** [comment]
Great, thanks for the info!

**Comment by vt-btf** [comment]
I have same issue. Just added "@" to objectName

**Comment by juanfranblanco** [comment]
Thanks @vt-btf  ill added to the list, of invalid prefixes!

**Comment by buddhamangler** [comment]
@juanfranblanco Were you planning on a release at any point to fix above?

**Comment by juanfranblanco** [comment]
Yes of course, sadly other priorities have been in place, as funding have stopped, but it will happen shortly.

**Comment by buddhamangler** [comment]
@juanfranblanco completely understandable, thank you.

**Comment by juanfranblanco** [comment]
Fixed on the latest commit
