### ISSUE TITLE
personal_newAccount is not available anymore?

### ISSUE THREAD

**Issue by greenkiller** [Nethereum/Nethereum#64]
Just want to double confirm, i don't see 'personal_newAccount' in the wiki page:
https://github.com/ethereum/wiki/wiki/JSON-RPC

And when I use 
`string newAccount = await web3.Personal.NewAccount.SendRequestAsync("Password01!");`
an exception was threw out with "The method personal_newAccount does not exist/is not available" message

**Comment by juanfranblanco** [comment]
It is in Geth https://github.com/ethereum/go-ethereum/wiki/Management-APIs

**Comment by greenkiller** [comment]
so i guess I cannot use NEthereum to create an account? as there is no json API available?

**Comment by juanfranblanco** [comment]
Of course you can, all the geth API methods are in here. ( Well if I have not missed one). Have you added personal to geth?

**Comment by juanfranblanco** [comment]
Added personal to the geth RPC params

**Comment by greenkiller** [comment]
I see. Thank you!

Date: Fri, 29 Jul 2016 13:06:11 -0700

**Comment by juanfranblanco** [comment]
Glad to help :)
