### ISSUE TITLE
sending tether

### ISSUE THREAD

**Issue by mojtaban12** [Nethereum/Nethereum#640]
Hi guys
I use this sample to send tether to another wallet with infura url.
https://docs.nethereum.com/en/latest/nethereum-events-gettingstarted/
when run the project to send tether with default TokenAmount(100) show me this error: "insufficient funds for gas price + value"
I changed TokenAmount to '100000000000' and show this error : "gas required exceeds allowance (12384409) or always failing transaction"
when added Gas to TransferFunction(), again show me "insufficient funds for gas price + value"

```
var wallet1 = new Wallet(words, password);
var account = wallet1.GetAccount(0);
var contractAddress = "0xdAC17F958D2ee523a2206206994597C13D831ec7"; //Tether contract
var web3 = new Web3(account,"https://mainnet.infura.io/v3/mytoken");
var transferHandler = web3.Eth.GetContractTransactionHandler<TransferFunction>();
var transfer = new TransferFunction()
{
To = ToAddress,
TokenAmount = 100
};
var transactionReceipt = await transferHandler.SendRequestAndWaitForReceiptAsync(contractAddress , transfer);
```

**Comment by mojtaban12** [comment]
and another question, how can create byteCode ? 
i'm beginner :/

**Comment by vision2003** [comment]
Tether (USDT) is ERC20 token, so you will first need to approve the wallet (spender) for the actual amount you want to send before sending. Also note that USDT is a special case where you will (in my experience) first need to approve 0 and then approve the actual amount.
