### ISSUE TITLE
EthECKey.SignAndCalculateV extremely slow

### ISSUE THREAD

**Issue by Favorlock** [Nethereum/Nethereum#644]
I've been writing some benchmarks for signing messages in various languages and I was extremely surprised to learn that Nethereum's performance at message signing ended up being the slowest yet. I'll provide my benchmarks for comparison:

NodeJS/ethers.js: 1k transactions signed in 2463ms
Java/web3j: 1k transactions signed in 1291ms
GoLang/go-ethereum-hdwallet: 1k transactions signed in 427ms
GoLang/go-ethereum: 1k transactions signed in 115ms
C#/Nethereum: 1k transactions signed in 12607ms

I was expecting C#/Nethereum to be faster than Java at the least, but it was quite the shock to see Nethereum nearly five times slower than NodeJS. All benchmarks are accurate in that they effectively can sign the same message and return the expected hash (e.g. "Hello" returns "0x7f7430e57f89fcd4d2bb8ee76ccd4ddbb9449e6d8f011a3aca514ea3404747045eb4f3b8b4e068cc2925fc7d1f69ddb5351d114e9554d9b554ebab0534a5bec91b" and as far as I'm aware I'm only signing the message, not sending it in Nethereum.

Based on what I'm seeing with a quick profile this isn't necessarily Nethereum at fault however, but rather your choice of math library. BouncyCastle seems to be performing pretty poorly. It would be great to see optimizations made to significantly reduce the time it takes to sign and calculate v.

You can see some of the profiling results I got in the following gist. For the sake of brevity I've omitted any calls that weren't significantly impacting the overall time: https://gist.github.com/Favorlock/1da6441a89cb02ba601c047464eedf97

**Comment by juanfranblanco** [comment]
@Favorlock Hi.. I have been away so I could not properly look at this. The main areas of cost are the Bouncy castle operations with Points (addition, multiplication) and BigIntegers (Surely you know this, so this is just for info on the issue). I am caching generation and access of public keys and addresses, also i have avoided most steps in calculations that can be reused, but do not make much of a different, but in some areas the recalculation of public key points as this is done already it has improved the performance a bit (4ms per signature on my pc). Still not great as the bottleneck is bouncy castle at the moment. Anyway I am continuing with this...

**Comment by juanfranblanco** [comment]
The overall performance improvements did not really add much when shuffling the code, so i have just left it for simplicity (readability). Now yes, just avoiding the public key re-generation helps with 1 millisecond on my pc. This carries a Multiply operation.. I have started integrating the NBitcoin implementation for signing, so far so good, and much better than bouncy, but only supported in .Net core as it uses Spans.

**Comment by juanfranblanco** [comment]
This is implemented now in 4.01. use this flag to use NBitcoin implementation.
https://github.com/Nethereum/Nethereum/blob/5fc9edd176db1300383255478eb438efb4cefebf/utils/Nethereum.Signer.Performance/Program.cs#L46
