### ISSUE TITLE
Sending transaction as per documentation gives "invalid sender"

### ISSUE THREAD

**Issue by BadgerTheAdger** [Nethereum/Nethereum#647]
Hello everyone, 

I went through the docs and I created account just the same way described in [this doc:](http://docs.nethereum.com/en/latest/accounts/)
)

```csharp
var ecKey = Nethereum.Signer.EthECKey.GenerateKey();
var privateKey = ecKey.GetPrivateKeyAsBytes().ToHex();
var account = new Nethereum.Accounts.Account(privateKey);
```

now I am using this account to send transaction ([the code is again just a copy-paste from this doc](https://docs.nethereum.com/en/latest/nethereum-transferring-ether/)):

```csharp
var web3 = new Web3(account, "https://mainnet.infura.io/v3/27fef559e3f44f519657fe8d422e1aa4");
var balance = await web3.Eth.GetBalance.SendRequestAsync(account.Address);
var etherAmount = Web3.Convert.FromWei(balance.Value);

var receiverAddress = "some address";
var transactionId = await web3.Eth.GetEtherTransferService().TransferEtherAndWaitForReceiptAsync(receiverAddress, etherAmount / 2);
```

And I get this RPC error: 

> invalid sender

_(I have enough funds as I sent them to this account and verified via GetBalance method that I have them)_

**Comment by BadgerTheAdger** [comment]
Same thing on ropsten

**Comment by BadgerTheAdger** [comment]
Got the following code working:

```
var privateKey = "privateKey";
var senderAddress = "senderAddress";
var receiver = "receiver";

var web3 = new Nethereum.Web3.Web3("https://ropsten.infura.io/v3/apiKey")
var txCount = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(senderAddress);

var encoded = Web3.OfflineTransactionSigner.SignTransaction(privateKey, receiver, 10, txCount.Value);
var isGood = Web3.OfflineTransactionSigner.VerifyTransaction(encoded);
var txId = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + encoded);

Console.WriteLine("isGood" + isGood);
Console.WriteLine("transaction id: " + txId);
```

**Comment by BadgerTheAdger** [comment]
Still doesn't mean the issue doesn't need to be fixed even if I managed to get it working another way. So I'm leaving it open maybe I'll kick in soon and help you guys make the library better

**Comment by juanfranblanco** [comment]
I don't understand your issue.. have you checked this example
http://playground.nethereum.com/csharp/id/1003

**Comment by BadgerTheAdger** [comment]
Yes I did check it, I created address (did it the same way doc described) then copy-pasted code to send transaction (you can check the links in the issue - the links are pointing to the docs), and it was giving me this error

**Comment by BadgerTheAdger** [comment]
The playground works the code I copy-pasted from doc and used on the infura didn't work

**Comment by juanfranblanco** [comment]
If you create a new account, that account is not have any balance on it, until you send it some Ether. Are you telling me that you generated a new account and match an address with some Ether on it?

**Comment by BadgerTheAdger** [comment]
@juanfranblanco Ok before the first and second stages in the code I sent, I did send 0.02 ether to this address and I checked the balance via address.GetBalance stuff, and it was 0.02 yes

**Comment by juanfranblanco** [comment]
Just in case I have just done a test in Ropsten and mainnet and no issues.. 

https://ropsten.etherscan.io/tx/0x4512768524a3390ae7b22834fa7131eb012c1d7f8649702f593a0995ea10d7d6

```csharp
using System;
using System.Text;
using Nethereum.Hex.HexConvertors.Extensions;
using System.Threading.Tasks;
using Nethereum.Web3;
using Nethereum.Web3.Accounts;

public class Program
{
    private static async Task Main(string[] args)
    {
        //First let's create an account with our private key for the account address 
        var privateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
        var account = new Account(privateKey);
        Console.WriteLine("Our account: " + account.Address);
        //Now let's create an instance of Web3 using our account pointing to our nethereum testchain
        var web3 = new Web3(account, "https://ropsten.infura.io/v3/<otherId>");

        var transaction = await web3.Eth.GetEtherTransferService()
            .TransferEtherAndWaitForReceiptAsync(account.Address, 0.1m);
    }
}
```

**Comment by BadgerTheAdger** [comment]
This is kind of crazy that the same code can work and not work, depending on a user of that code/environment, etc. I will check your code later today. Because it looks to be the same as mine.

**Comment by juanfranblanco** [comment]
The truth is you are the only person that has this issue, so i am keen to know how this has happened.

**Comment by juanfranblanco** [comment]
@BadgerTheAdger So any further info on this? Were you targeting Infura and mainnet? Or using a testnet. Did you by any chance specify a ChainId and target the wrong network as this will trigger a similar error.

**Comment by BadgerTheAdger** [comment]
I just tested on ropsten, looks to be working... I don't know what the issue was, probably something with infura as it gave RPC specific error. We can close it until some other new to ethereum chap comes in here and gets the same error that only newbies get😄  (I just tried the same code and it worked)

**Comment by juanfranblanco** [comment]
Yes, it might have been an infura error. Nothing worst that getting started and find the most strange error.
