### ISSUE TITLE
OfflineTransactionHelper docs are outdated

### ISSUE THREAD

**Issue by BadgerTheAdger** [Nethereum/Nethereum#648]
Check this issue dated 2017, still not fixed, please fix, it took me 20-30 minutes figuring out where it is https://github.com/Nethereum/Nethereum/issues/209

**Comment by juanfranblanco** [comment]
Yes that was going to be made obsolete as the best way to sign transactions is to use the transaction manager with your account and private key. But people are still happy to use it, so it has been left out and documentation still outdated.
What is your need for this, why won't you use the transaction manager instead?

**Comment by BadgerTheAdger** [comment]
Because it didn't work for me as per https://github.com/Nethereum/Nethereum/issues/647
