### ISSUE TITLE
Application terminates unexpectedly

### ISSUE THREAD

**Issue by DarthChucks** [Nethereum/Nethereum#65]
I created a new windows console application targeting .Net Framework 4.5.2 (default) and added Nethereum.Web3 1.0.0 rc4 via nuget.  Then I tried the following code:

    using Nethereum.Web3;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    namespace NethereumTest
    {
        class Program
        {
            static void Main(string[] args)
            {
                var t = Task.Run(() => Test());
                t.Wait();
            }

            private async static void Test()
            {
                var web3 = new Web3("http://localhost:8545/");
                var result = await web3.Net.Version.SendRequestAsync();
                Console.Out.WriteLine(result);
            }
        }
    }

Running in the debugger, the call to web3.Net.Version.SendRequestAsync causes the application to terminate unexpectedly.  Using the IpcClient, the application also terminated unexpectedly.

I did verify that the geth http interface was running by connecting to http://localhost:8545/ in a browser.  geth responded to the browser request as expected with:

    {"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}

**Comment by juanfranblanco** [comment]
That is an error with geth itself. Are other methods working as expected?

**Comment by DarthChucks** [comment]
I agree.  As I said, geth responded as expected with an error to an empty request.  I was trying to show that geth was running with http enabled.

I have confirmed the same behavior with the following requests:

    var result = await web3.Net.PeerCount.SendRequestAsync();
    var result = await web3.Eth.Mining.IsMining.SendRequestAsync();
    var result = await web3.Eth.Accounts.SendRequestAsync();

Every time, the application terminates unexpectedly on the SendRequestAsync.

**Comment by juanfranblanco** [comment]
quick catch up.. are you still having the same problem with rc5?

**Comment by DarthChucks** [comment]
Thanks for following up.  Yes same behavior for both a desktop console app and core console app.

**Comment by DarthChucks** [comment]
I pulled the latest from git and I'm trying to run the samples.  A couple of things I've noticed:

### Nethereum.RPC.Sample
It looks like there are some remnants of an old name for the project.  There are several places where "Ethereum.RPC.Sample" are referenced, and I think they should be updated to "Nethereum.RPC.Sample."

### Nethereum.Desktop.Sample
The references to the Nethereum samples are missing:


    Warning		The referenced component 'Nethereum.Hex' could not be found.	Netherum.Desktop.Sample			
    Warning		Could not resolve this reference. Could not locate the assembly "Nethereum.RPC". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Netherum.Desktop.Sample			
    Warning		The referenced component 'Nethereum.RPC' could not be found.	Netherum.Desktop.Sample			
    Warning		Could not resolve this reference. Could not locate the assembly "Nethereum.Hex". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Netherum.Desktop.Sample			
    Warning		The referenced component 'Nethereum.JsonRpc.Client' could not be found.	Netherum.Desktop.Sample			
    Warning		The referenced component 'Nethereum.Web3' could not be found.	Netherum.Desktop.Sample			
    Warning		Could not resolve this reference. Could not locate the assembly "Nethereum.JsonRpc.Client". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Netherum.Desktop.Sample			
    Warning		Could not resolve this reference. Could not locate the assembly "Nethereum.Web3". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Netherum.Desktop.Sample			
    Warning		The referenced component 'Nethereum.ABI' could not be found.	Netherum.Desktop.Sample			
    Warning		Could not resolve this reference. Could not locate the assembly "Nethereum.ABI". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Netherum.Desktop.Sample			
    Error	CS0246	The type or namespace name 'Nethereum' could not be found (are you missing a using directive or an assembly reference?)	Netherum.Desktop.Sample	C:\Projects\Visual Studio 2015\Nethereum\src\Netherum.Desktop.Sample\MainWindow.xaml.cs	15	Active
    Error	CS0246	The type or namespace name 'Web3' could not be found (are you missing a using directive or an assembly reference?)	Netherum.Desktop.Sample	C:\Projects\Visual Studio 2015\Nethereum\src\Netherum.Desktop.Sample\MainWindow.xaml.cs	31	Active

The references are pointing to an artifact directory which doesn't get created during the build.  For example:

    ..\..\artifacts\bin\Nethereum.ABI\Debug\net451\Nethereum.ABI.dll

I updated the references to the projects instead of the files in the artifacts directory and everything compiles.  However, I get an exception when I click the "Get Accounts" button:

    Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Here's the app.config:

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
		<startup> 
			<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1" />
		</startup>
	  <runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
		  <dependentAssembly>
			<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
			<bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
		  </dependentAssembly>
		</assemblyBinding>
	  </runtime>
	</configuration>

I updated Newtonsoft.Json from nuget which fixed the binding redirect:

    <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />

Now GetAccounts works as expected

**Comment by DarthChucks** [comment]
Correction.  The artifacts directory is created and it has an obj sub directory.  There is no bin sub directory.

**Comment by DarthChucks** [comment]
After getting the sample running, I tried creating a WPF app and duplicating the sample.  Get accounts works.

Then I created another desktop console app, and it works.  Now I'm really confused.

I will it again on my wife's laptop this evening.  It has never had Nethereum on it.

**Comment by juanfranblanco** [comment]
Yes those are both old samples. Originally it was not possible to reference directly any of the projects in desktop apps, hence the sample using a DLL. Better ones are the web or the wallet.

**Comment by juanfranblanco** [comment]
Seen your pull request thanks

**Comment by DarthChucks** [comment]
I just ran some more tests.  The error was mine, and Nethereum seems to be working as expected.  I foolishly ran my simple test with an async method which returns void.  Async methods which return void have some strange behaviors.  I changed it to return Task, and everything works fine.  I do apologize.
