### ISSUE TITLE
Ganache does not support windows 32bit is there an alternative to Ganache

### ISSUE THREAD

**Issue by besiwims** [Nethereum/Nethereum#653]
Good day

I am running a 32bit windows OS and there is no need for me to upgrade just because I have to install Ganache. Neither is there a need for me to purchase more resources just because I want to test locally.

Help me with an alternative to Ganache. I see many others too have the same problem?

Thank you.

**Comment by juanfranblanco** [comment]
@besiwims Nethereum tests run using the preconfigured https://github.com/Nethereum/TestChains. Note you will need to download Geth 32 bit version.

**Comment by besiwims** [comment]
Thanks a lot. Geth for windows 32bit did install.
