### ISSUE TITLE
The Account.Address class is returning some uppercase 

### ISSUE THREAD

**Issue by NicolasDorier** [Nethereum/Nethereum#654]
Version: 3.8.0

This test fails
```csharp
Assert.Equal("0x12890d2cce102216644c59dae5baed380d84830c", new Account("0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7", 1337).Address);
```

This has a non obvious consequence since some methods are case sensitive.

Like https://github.com/Nethereum/Nethereum/blob/18d2c31baf3f42483aae9b1c898cd50ea5de23f0/src/Nethereum.Accounts/Managed/ManagedAccountTransactionManager.cs#L58

I would suggest that:

1. The case of `Account.Address` should be lowercase
2. `AccountTransactionManager.SendTransactionAsync` should compare string ignoring the case.

**Comment by juanfranblanco** [comment]
Thanks @NicolasDorier, the reason for the random character case is due to this EIP: https://eips.ethereum.org/EIPS/eip-55, but totally right the comparison fails on the ManagedAccounts TransactionManager. 
Corrected now to use the Nethereum.Utils.Address comparison.

From the conversation before, yes an Address Type would have helped, but the thought was to keep it simple for users, although  yes other types were introduced like HexBigInteger and HexString.

**Comment by NicolasDorier** [comment]
@juanfranblanco actually reopening the issue. Shouldn't `ManagedAccount` convert to the upper case in this case?

You can close the issue if you think it should not.

**Comment by juanfranblanco** [comment]
@NicolasDorier Great point and I am truly unsure about this one, this may cause a big breaking change (for users). For simplicity (and performance sake) the generation will only happen only when generating and address, so user input should always be treated as valid.  Yes a type would have helped..

Now I have not forced this on Abi decoding as the eip was introduced later and I did not want to create a big breaking change, hence the usage of Address extensions for validations and comparisons (the EIP is just for visual purposes).

Now, the rule as it is not set across is for any address generated (from private key or abi) by the Nethereum to output the checksum.

**Comment by juanfranblanco** [comment]
Abi decoding included here now too: https://github.com/Nethereum/Nethereum/commit/df0f48d0ae70db44e7d2b283c5fc378917cfea37
