### ISSUE TITLE
Not passing the cancellation token properly to Task.Delay

### ISSUE THREAD

**Issue by NicolasDorier** [Nethereum/Nethereum#655]
https://github.com/Nethereum/Nethereum/blob/b5b4fc667882a88fb529c232271cc54aa3993936/src/Nethereum.RPC/TransactionReceipts/TransactionReceiptPollingService.cs#L64

You should pass the cancellation token to the delay, so the caller does not wait needlessly on the end of the delay.

**Comment by juanfranblanco** [comment]
Great point, added now
