### ISSUE TITLE
Can I build this with Visual Studio?

### ISSUE THREAD

**Issue by MrYukonC** [Nethereum/Nethereum#66]
I assume this solution is buildable with Visual Studio?  Do you happen to know the latest compatible version?  It currently won't load any of the .xproj projects in Visual Studio 2015 Community.  Thanks.

**Comment by juanfranblanco** [comment]
I am using Visual Studio 2015 Update 2. You need to have installed the latest release for .Net core (it has been migrated already to 1.0)

**Comment by MrYukonC** [comment]
Hi Juan,

Thanks for clarifying. I am able to start the build now after updating
NuGet packages.

I assume Nethereum.Portable is the preferred project to build?

Is the Nethereum.Maker source not in the trunk?  I had some issues with
that, but got past it by manually pulling from Nethereum.Maker.

Now, I'm getting the following error when building Nethereum.Portable:

1>C:\Projects\Nethereum\src\Nethereum.Web3\Core\Transaction.cs(6,22,6,29):
error CS0234: The type or namespace name 'Signing' does not exist in the
namespace 'Nethereum.Core' (are you missing an assembly reference?)

originating from this using directive in Transaction.cs:

using Nethereum.Core.Signing.Crypto;

Any ideas what I might be doing wrong?

Thanks for your help.

**Comment by juanfranblanco** [comment]
Actually portable is not the one to use, this is autogenerated with BuilProjectFile project as it pulls all the files from diferentes sources. Web3 project will provide the same functionality and now is also Portable. (Before it was not possible due to dependencies)

**Comment by MrYukonC** [comment]
Okay, I will give that a try. Thanks for responding.

**Comment by MrYukonC** [comment]
I take it DNX has to be installed in order for the .xproj projects to load?

Because right now they do not load with a fresh install of Visual Studio
2015 Community.

**Comment by juanfranblanco** [comment]
You need to follow this instructions here to install core, dnx is now being replaced with core https://www.microsoft.com/net/core#windows

**Comment by MrYukonC** [comment]
Looks like that did it.  Thanks for the help.

Also, what a mess this .NET transition has become -- wow.

Anyway, thanks again.

**Comment by juanfranblanco** [comment]
Glad is working! You tell me about the mess... I wasted days transitioning projects, to be re transitioned.. errors appearing from nowhere...  but hopefully is over soon.

**Comment by Affinity121** [comment]
The solution is not buildable in old version of Visual Studio, and I do not have newest version of Visual Studio and can't install it. Could you please share somewhere DLL assembly?
