### ISSUE TITLE
what is the connection between wallet password and genrated addreses

### ISSUE THREAD

**Issue by FIVIL** [Nethereum/Nethereum#663]
Hi, I was wondering what is the connection between wallet password and generated addresses in this library, to be more specific is there any way to generate the same ETH accounts from the seed phrase with a different password or no password at all.
I have used Nethereum to generate a bunch of ETH addresses and had someone transfer some ETH to those addresses. However, right now I can't access them. I do possess the seed phrase that I used but I don't remember the password that I used. so now I was wondering is there any way to access those ETHs with just the seed phrases. I Have seen this is possible in other wallets such as metamask!!!

**Comment by juanfranblanco** [comment]
@FIVIL Just to confirm you mean the HDWallet mnemonic (words) and password, correct?
The password in this scenario is an extra form of security to generate the key seed for your HD Wallet in combination with your 12 words. This password is not used to encrypt the mnemonic  like in metamask.

**Comment by FIVIL** [comment]
yes, I have the HDWallet mnemonic. 
This means I can't retrieve the funds without knowing the password right??

**Comment by juanfranblanco** [comment]
if you have used the password in combination with the mnemonic to generate the seed no, as it acts like a salt. If you are using the password like in Metamask, then yes. Now.. depending on the lenght of your password etc, you should be able to recover it if you know all the words already.

**Comment by juanfranblanco** [comment]
this is an example https://github.com/Nethereum/Nethereum.Playground/issues/37 with a blank password

**Comment by FIVIL** [comment]
tnx
