### ISSUE TITLE
Nethereum .NET 5 integration

### ISSUE THREAD

**Issue by Hawkeye4040** [Nethereum/Nethereum#664]
I've seen for certain that Nethereum is up to date with .Net Core 3.1 I would also really like to see .NET 5 integration soon as I would like to use it for that. Also a heads up .NET 6 isn't too far away either. They're moving fast these days.

**Comment by juanfranblanco** [comment]
@Hawkeye4040 Net5 is supported, you should not have any problems, but there are issues in the HD wallet with Blazor crypto as some of the crypto libraries were removed until .net 6 which will be LTS. I may do a specific .net 5 relase in the interim to 1559 and other upgrades.

**Comment by juanfranblanco** [comment]
@Hawkeye4040 btw .net 5 target is already here https://github.com/Nethereum/Nethereum/blob/master/buildConf/Frameworks.props just not in nuget

**Comment by Hawkeye4040** [comment]
Ah that makes sense about the waiting on upgrades part. I'm glad to hear that I wasn't sure and it looked like it was only up to .net core 3.1 for my purposes for now I'd just need to be able to use in in a .NET 5 project.

**Comment by juanfranblanco** [comment]
@Hawkeye4040 It works the same, i am using it here https://github.com/Nethereum/NethereumBlazor/blob/master/NethereumExplorer.ClientWasm/NethereumExplorer.ClientWasm.csproj#L4 as one the example. 1559 it will be a bigger change, hence the mention
