### ISSUE TITLE
Question: multiple subscriptions of the same type

### ISSUE THREAD

**Issue by siskender** [Nethereum/Nethereum#665]
Let's say you have the following code:
```csharp
            var client = new StreamingWebSocketClient("wss://localhost:8786/ws");

            var filter1 = Event<Event1>.GetEventABI().CreateFilterInput();
            var subscription1 = new EthLogsObservableSubscription(_client);
            subscription1.GetSubscriptionDataResponsesAsObservable().Subscribe(log =>
            {
                try
                {
                    // decode the log into a typed event log
                    var @event = Event<Event1>.DecodeEvent(log);
                    if (@event != null)
                    {
                    }
                }
                catch
                {
                    // ignored
                }
            });

            var filter2 = Event<Event2>.GetEventABI().CreateFilterInput();
            var subscription2 = new EthLogsObservableSubscription(_client);
            subscription2.GetSubscriptionDataResponsesAsObservable().Subscribe(log =>
            {
                try
                {
                    // decode the log into a typed event log
                    var @event = Event<Event2>.DecodeEvent(log);
                    if (@event != null)
                    {
                    }
                }
                catch
                {
                    // ignored
                }
            });

            await client.StartAsync().ConfigureAwait(false);

            await subscription1.SubscribeAsync(filter1).ConfigureAwait(false);
            await subscription2.SubscribeAsync(filter2).ConfigureAwait(false);
```

It seems like there is only one EthLogsObservableSubscription allowed. Because if in this example no logs are retrieved by the subscriptions. If one of the subscriptions is removed then it works.

What I want to achieve is to listen to some (not all) events on the chain (no contract given). Would really like some advice to achieve this.

**Comment by juanfranblanco** [comment]
This should not be an issue, I have tested it just now using the same subscription parameters and I am getting the same responses.

![image](https://user-images.githubusercontent.com/562371/111305566-076c2b80-864f-11eb-8ad2-edb635a1f2a4.png)

**Comment by siskender** [comment]
Yes it seems related to #662.

I get an timeout exception after 20000 milliseconds. {"Rpc timeout after 20000 milliseconds"}.

**Comment by juanfranblanco** [comment]
Have you tried with infura?

**Comment by siskender** [comment]
No I'm using binance smart chain and using Ankr for the wss endpoints. But it seems that the Ankr wss endpoint is only accepting 1 connected client. Strange...

**Comment by juanfranblanco** [comment]
Ah, you should ask them.

**Comment by siskender** [comment]
Yes changing it to one of the relayers of Binance itself resolved the issue... thanks for looking into it :-)
