### ISSUE TITLE
Pick one support mechanism

### ISSUE THREAD

**Issue by fulldecent** [Nethereum/Nethereum#667]
Currently [the project README](https://github.com/Nethereum/Nethereum/blob/master/README.md#nethereum) directs support requests to Discord.

But the [documentation/examples playground](http://playground.nethereum.com/) directs support to Gitter.

The [official docs website](http://docs.nethereum.com/en/latest/) references Gitter.

In order to create the most connected community, please consider to choose only one preferred support mechanism and reference it consistently from everywhere.

**Comment by juanfranblanco** [comment]
@fulldecent  Yes, discord is the preferred method, as it was stated in gitter. Those need to be updated, website is going to be redone soon ™

**Comment by fulldecent** [comment]
Fixed here https://github.com/fulldecent/nethereum.com

Also addresses other issues.

If you like, you can fork that here and maybe use it with GitHub Pages. That's a quick cycle.

Then I can delete my copy so yours isn't a "fork" any more since it deserves to be the original here.

**Comment by juanfranblanco** [comment]
Ah thanks!! that is super handy, as i have the website in hugo and I was going to redo it, but as it is so simple, moving to github pages and making small edits for now will be much easier.

**Comment by fulldecent** [comment]
Cool, you're welcome.

I tried to use "Transfer repo" to send it to the Nethereum organization. But GitHub requires admin permissions on the target organization to do that so it fails.

Alternatively, I could transfer that repo to juanfranblanco and you could transfer it to Nethereum. This will require maybe five clicks total for you, including turning on GitHub Pages.

Shall I do the transfer to juanfranblanco?

**Comment by juanfranblanco** [comment]
@fulldecent  sure!!! :)

**Comment by fulldecent** [comment]
@juanfranblanco sent, please check your email to approve

**Comment by juanfranblanco** [comment]
Is moving now!! :) Thanks again

**Comment by fulldecent** [comment]
Cool, you're welcome
