### ISSUE TITLE
StreamingWebSocketClient and disconnections

### ISSUE THREAD

**Issue by soltrac** [Nethereum/Nethereum#669]
Hello,

I've seen that using NEthereum with StreamingWebSocketClient connecting to the websocket, when some time passes, I stop receiving newblocks.

I have to disconnect and reconnect again to keep receiving. Is there any way to know when I've been disconnected? Or any way to "keep-alive" the connection?

Also, onError of the subscription is not always fired, so I cannot use that.

**Comment by masherak** [comment]
@juanfranblanco I am sure this example is not throwing event Client_Error in case of disconnection, there is internal exception fired with message "Client connection error", but I can handle it just in debug mode, there is no propagation to upper layer. I kept "ConnectionTimeout" and "ForceCompleteReadTotalMilliseconds" on default values on the StreamingWebSocketClient. Should I change them somehow ? Can you help me please?
