### ISSUE TITLE
Support Newtonsoft.Json 13.0.1

### ISSUE THREAD

**Issue by orderinboxdev** [Nethereum/Nethereum#681]
Thank you all for the great work with this library.

We cannot install Nethereum into a project that is using the latest version of Newtonsoft.Json (13 as of now) through indirect dependencies.

NU1608: Detected package version outside of dependency constraint: Nethereum.Signer 3.8.0 requires Newtonsoft.Json (>= 10.0.3 && < 13.0.0) but version Newtonsoft.Json 13.0.1 was resolved.
NU1608: Detected package version outside of dependency constraint: Nethereum.Hex 3.8.0 requires Newtonsoft.Json (>= 10.0.3 && < 13.0.0) but version Newtonsoft.Json 13.0.1 was resolved.
NU1608: Detected package version outside of dependency constraint: Nethereum.Model 3.8.0 requires Newtonsoft.Json (>= 10.0.3 && < 13.0.0) but version Newtonsoft.Json 13.0.1 was resolved.
NU1608: Detected package version outside of dependency constraint: Nethereum.RLP 3.8.0 requires Newtonsoft.Json (>= 10.0.3 && < 13.0.0) but version Newtonsoft.Json 13.0.1 was resolved.
NU1608: Detected package version outside of dependency constraint: Nethereum.Util 3.8.0 requires Newtonsoft.Json (>= 10.0.3 && < 13.0.0) but version Newtonsoft.Json 13.0.1 was resolved.

Would it be possible to support Newtonsoft < 14?

**Comment by juanfranblanco** [comment]
Yes, in the next release is added.

**Comment by twilightrus** [comment]
when is the next release?

**Comment by juanfranblanco** [comment]
When i finish EIP-1559

**Comment by gviddy** [comment]
Does anybody have a work around for this in the meantime ?

**Comment by MajMcCloud** [comment]
Maybe this "can" help:

`Install-Package Nethereum -IgnoreDependencies`

**Comment by juanfranblanco** [comment]
4.0.1 is out now with EIP1559 and this :)
