### ISSUE TITLE
how to call function with array parameter

### ISSUE THREAD

**Issue by cainiaokun** [Nethereum/Nethereum#682]
this is contract
{
    "inputs":[
        {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
        },
        {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
        }
    ],
    "name":"getAmountsOut",
    "outputs":[
        {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
        }
    ],
    "stateMutability":"view",
    "type":"function"
}

i'm trying call this function with error

this is my code

var getAmountsOutFunction = route_contract.GetFunction("getAmountsOut");

var amounts_in = Web3.Convert.ToWei(Util.amounts_in, decimals);

List<string> in_out = new List<string>();

in_out.Add(address1);

in_out.Add(address2);

var amounts_out = getAmountsOutFunction.CallAsync<BigInteger[]>(amounts_in, in_out).GetAwaiter().GetResult();

help me fix this

**Comment by juanfranblanco** [comment]
Can you move questions to the discord? https://discord.gg/t9Gv45GZ Thanks

**Comment by cainiaokun** [comment]
okay
