### ISSUE TITLE
Using csharp code generator with function requiring "from"

### ISSUE THREAD

**Issue by maiorfi** [Nethereum/Nethereum#683]
It seems that "from" address parameter can be used only with "function class" generated code, while it could be useful to use the leaner mode represented by methods exposed by service (i.e. the ones that do not return transaction receipts).

Is there anything I am missing?

Thanks!

**Comment by juanfranblanco** [comment]
@maiorfi can you post some example as I don't know what you mean.

**Comment by juanfranblanco** [comment]
Ah I got you now, yeah maybe in the next release as things will change with 1559

**Comment by juanfranblanco** [comment]
@maiorfi Also note that if From is not set it will use the Account address, used to initialised Web3. 
Now, most important those need to match anyway as the txn will be signed with that.

**Comment by juanfranblanco** [comment]
Also note that with eip1559 we will have more parametes, and if we end up having transaction types, this will not fit in here as it will end up being a small mess.

**Comment by maiorfi** [comment]
Ok, thanks.
