### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by netlocks** [Nethereum/Nethereum#684]
How to send tokens in batches in Nethereum to reduce the gas price？

**Comment by juanfranblanco** [comment]
@netlocks You cannot send tokens in batches, if you are doing an airdrop the best way is to use a merkle drop (check in zeppelin or uniswap). But if you have any more questions please drop by in Discord.

**Comment by netlocks** [comment]
What is merkle drop？

**Comment by juanfranblanco** [comment]
An example https://github.com/trustlines-protocol/merkle-drop
