### ISSUE TITLE
Nethereum.Generators Missing Type Mapping for uint24

### ISSUE THREAD

**Issue by Texnomic** [Nethereum/Nethereum#685]
Nethereum.Generators doesn't generate C# Type Mapping for uint24.

## Expected Behavior

Mapping Solidity uint24 to C# uint32 or new custom type.

## Current Behavior

The Codegen completely ignores the type. Example method signature: 
`public Task<string> CreatePoolRequestAsync(string tokenA, string tokenB,  fee)`

## Possible Solution

Mapping Solidity uint24 to C# uint32 or new custom type.

## Steps to Reproduce

1. Downloading [Uniswap v3 Factory ABI](https://etherscan.io/address/0x1F98431c8aD98523631AE4a59f267346ea31F984#readContract)
1. Running `Nethereum.Generator.Console generate from-abi -abi .\UniswapV3Factory.abi -o .\Uniswap3.Factory -ns Uniswap3.Factory -cn Uniswap3FactoryContract`

**Comment by juanfranblanco** [comment]
Many thanks, I know about this, it will be fixed in the next release of Nethereum. You can use this for now https://github.com/Nethereum/Nethereum.Uniswap-V2-and-V3

**Comment by juanfranblanco** [comment]
This should be in vscode shortly

**Comment by ItayPodhajcer** [comment]
Hi,
Any estimation on when an updated version of `Nethereum.Autogen.ContractApi` with a fix will be released?
This issue was closed, but the latest version is still `3.6.2` that was released on `1/29/2020` (according to [nuget.org](https://www.nuget.org/packages/Nethereum.Autogen.ContractApi/3.6.2))

**Comment by juanfranblanco** [comment]
You can use the vscode solidity one, for the time being. The generators will be released at the same time as 4.0.

**Comment by juanfranblanco** [comment]
The generators, will require changes to support eip1559 part of 4.0 which are not ready yet.

**Comment by ItayPodhajcer** [comment]
Thanks for the quick response!!

**Comment by ItayPodhajcer** [comment]
Hi @juanfranblanco 
Any updates on this?
As v4.0.x has already been released, but `Nethereum.Autogen.ContractApi` still has a 3.x.x version

**Comment by juanfranblanco** [comment]
All the updated Nethereum packages are there for 4.0.5. Although not this one yet, you can get it from CI
