### ISSUE TITLE
Where are ABICode and ABIValue classes?

### ISSUE THREAD

**Issue by stefanotempesta** [Nethereum/Nethereum#687]
How can this code compile?

http://docs.nethereum.com/en/latest/nethereum-abi-encoding/

There is no ABICode and ABIValue class that I can find.

Thanks

**Comment by stefanotempesta** [comment]
Closing this issue. When installing the Nethereum nuget package, these classes are not available. Need to explicitly add the Netherem.Web3 package. Weird, but that is...

**Comment by juanfranblanco** [comment]
The Nethereum package is not the official one, is just a fork containing most stuff in a single place. It might not have been updated for a while.

**Comment by stefanotempesta** [comment]
Thanks Juan, I figured. Is there an official NuGet package that contains the whole bundle?

**Comment by juanfranblanco** [comment]
Use Netheruem.Web3 that references most of them. @stefanotempesta

**Comment by juanfranblanco** [comment]
There is also Nethereum.Portable BUT the extension packages reference to the single ones.

**Comment by juanfranblanco** [comment]
Also.. for your current use case you just need the Nethereum.ABI

**Comment by stefanotempesta** [comment]
Thanks Juan, will do.
