### ISSUE TITLE
Error using for loop to execute transfer.

### ISSUE THREAD

**Issue by netlocks** [Nethereum/Nethereum#688]
for (int i = 0; i < 10; i++)
                {
 var transferHandler = web3.Eth.GetContractTransactionHandler<TransferFunction>();
                var transfer = new TransferFunction()
                {
                    To = model.Address,
                    TokenAmount = Web3.Convert.ToWei(amount * 0.98m)
                };
var transactionReceipt2 = await transferHandler.SendRequestAndWaitForReceiptAsync(heyue, transfer);
                var hashs = transactionReceipt2.TransactionHash;
}

**Comment by juanfranblanco** [comment]
What error do you get?

**Comment by juanfranblanco** [comment]
Closing this for now as it seems as question, please come to discord if you have any problems
