### ISSUE TITLE
Incorrect cliquesigner post EIP1559 on goerli

### ISSUE THREAD

**Issue by mtbitcoin** [Nethereum/Nethereum#689]
With reference to https://github.com/Nethereum/Nethereum/issues/610 , post EIP1559 the RecoverCliqueSigner returns an incorrect value. 

For instance https://goerli.etherscan.io/block/5062828 returns 0xf39769205697210862af0a0844ff41538f10314c as a the signer (miner) but the correct signer (miner) should be 0x8b24eb4e6aae906058242d83e51fb077370c4720 

This appears to effect both Geth and Parity RPC decodings for the signer

**Comment by juanfranblanco** [comment]
Hi @mtbitcoin!!, you are right, tests are failing there at the moment. I just wanted to check in some of the current progress.

**Comment by juanfranblanco** [comment]
Fixed on https://github.com/Nethereum/Nethereum/commit/c05d10c5348647e2612acfc77fbf5dd5c2e3e67d and extra validation on https://github.com/Nethereum/Nethereum/commit/ba8014433f3e42d15fda161ccbd46f5227bae189

**Comment by Enigmatic331** [comment]
Thanks so much @juanfranblanco! Any chance for a nuget release soonish? :D

**Comment by juanfranblanco** [comment]
Yeah, most probably this weekend.

**Comment by mtbitcoin** [comment]
Just tested this locally, the Geth response appears to be correct but it doesn't match when querying again OE/Parity

Geth 5062828 = 0x8b24eb4e6aae906058242d83e51fb077370c4720
OE 5062828 = 0x85e38c0818bbb1114b58b93ecc4baaaf57f9405d

**Comment by mtbitcoin** [comment]
sorry, ignore the above. Looks good, had to remove the previous

blockHeaderparity.MixHash = blockHeaderparity.MixHash.Skip(1).ToArray
blockHeaderparity.Nonce = blockHeaderparity.Nonce.Skip(1).ToArray
