### ISSUE TITLE
StreamingWebSocketClient doesn't support url with verification

### ISSUE THREAD

**Issue by SatanBtc** [Nethereum/Nethereum#692]
I tried connect websocket with this url 

"wss://friendly-mahavira:emit-impure-prozac-babied-trial-edge@ws-nd-331-084-789.p2pify.com

by StreamingWebSocketClient

then returned 401，it seems that doesn't support this format url ？？

Could anyone help me？？

 thanks~...

**Comment by juanfranblanco** [comment]
Added in the latest commit support for Basic
you need to 

client.SetBasicAuthenticationHeader<StreamingWebSocketClient>("user name", "password");

**Comment by SatanBtc** [comment]
okay，thanks~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nethereum/Nethereum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上6:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nethereum/Nethereum] StreamingWebSocketClient doesn't support url with verification (#692)





 
Added in the latest commit support for Basic
 you need to
 
client.SetBasicAuthenticationHeader("user name", "password");
