### ISSUE TITLE
CSharp code generation doesn't avoid user of the 'operator' keyword as a variable name

### ISSUE THREAD

**Issue by TheWisestOne** [Nethereum/Nethereum#693]
WHen generating c sharp code based on a contract with a function that has an argument like "string operator", the generated CSharp code uses exactly "string operator" in the service file's function definition. This fails to compile, as operator is a keyword in C#.

## Expected Behavior
The operator keyword should be escaped in some way, e.g. `string _operator_` to avoid compilation issues

## Current Behavior
generated csharp code does not compile

## Possible Solution
when generating c sharp code, ensure that none of the generated variable names are keywords in c sharp. Since the set of keywords in C# differs from solidity, it is not unlikely that users will create variables with names that happen to be keywords in C#

## Steps to Reproduce
Try to do codegen on any solidity contract that uses "operator" as a variable name. For example": 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol
(see the `setApprovalForAll` function)

## Context (Environment)
using CLI/console codegen from a solidity contract

**Comment by juanfranblanco** [comment]
This is fixed now but not released as a nuget, use the vscode solidity extension to generate code.
