### ISSUE TITLE
Apparent namespace conflict between Common.Logging.Core Nethereum dependency and Unity.Collections.Common

### ISSUE THREAD

**Issue by cjcurrie** [Nethereum/Nethereum#695]
References to Unity.Collections's static class Common appear to be overwritten by references to the Nethereum dependency Common.Logging.Core.

## Expected Behavior

Nethereum should compile in project without namespace conflicts.

## Current Behavior

Importing Nethereum's net37 or net461 libraries created error
`Library\PackageCache\com.unity.collections@0.14.0-preview.16\Unity.Collections\xxHash3.cs(544,27): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)`
This is probably due to Unity.Collections.Common.umul128 being hidden by Common.Logging.Core. Unity.Collections is used by Unity's burst compiler, I believe, which is used in multithreading.

See Unity.Collections ln 790 [on github/needle-mirror](https://github.com/needle-mirror/com.unity.collections/blob/5e405965991e725a424939d709162e09fcebb62d/Unity.Collections/xxHash3.cs#L790)

## Possible Solution

Consider using an [extern alias](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias) to rename Common.Logging.Core. 

## Steps to Reproduce

1. Create a Unity project and import Nethereum's net35 or net461 (likely any other version too)
2. Use unity Package Manager to import the Burst and Jobs libraries (standard, provided by Unity Software)
3. If necessary, import with `using Unity.Jobs;`, `using UnityEngine.Jobs;`, and `using Unity.Burst;` statements.
4. Console should now log the error `Library\PackageCache\com.unity.collections@0.14.0-preview.16\Unity.Collections\xxHash3.cs(544,27): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)`

## Context (Environment)

I'm attempting to create a mobile game that uses ERC721 tokens to represent Unity game objects.

I can't get nethereum to work in my project due to namespace conflict.

## Detailed Description

Find a way to rename Common.Logging or else remove the `using Common.Logging.Core;` statement in favor of inline references to the namespace.

**Comment by juanfranblanco** [comment]
Hey @cjcurrie 

Thanks I have seen your comments in discord, I need to figure out this, as Unity should not have an issue compiling as this is a referenced assembly.

**Comment by juanfranblanco** [comment]
Also that class is private, this should not happen. 

```csharp
 private static class Common
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static ulong umul128(ulong x, ulong y, out ulong high)
            {
                // Split the inputs into high/low sections.
                ulong xLo = (uint)x;
                var xHi = x >> 32;
                ulong yLo = (uint)y;
                var yHi = y >> 32;

                // We have to use 4 multiples to compute the full range of the result.
                var hi = xHi * yHi;
                var m1 = xHi * yLo;
                var m2 = yHi * xLo;
                var lo = xLo * yLo;

                ulong m1Lo = (uint)m1;
                var loHi = lo >> 32;
                var m1Hi = m1 >> 32;

                high = hi + m1Hi + ((loHi + m1Lo + m2) >> 32);
                return x * y;
            }
        }

```

**Comment by juanfranblanco** [comment]
@cjcurrie  This looks an issue with Unity compiler for sure, are you using IL2CPP?

**Comment by ns2808** [comment]
Hi, I'm having the exact same issue. Basically in the editor I'm not able to enter play mode.

'Common' is, well, too common of a name. It should be switched to something else.

**Comment by soundling** [comment]
Same issue here, impossible to use the last Unity Netcode package with Nethereum because it relies on Burst.

**Comment by cjcurrie** [comment]
Through trial and error, I was able to overcome this namespace conflict by downgrading the Entities unity package to version 0.14.0

**Comment by cjcurrie** [comment]
@[juanfranblanco](https://github.com/juanfranblanco) So sorry I didn't see your comment. I'm using Unity 2021 which I believe uses Roslyn and LLVM for Burst. Used to be an option to choose your compiler but I don't see that any more.

**Comment by supiket** [comment]
Any idea on how to workaround this issue?

**Comment by cjcurrie** [comment]
Upgrading to Unity 2021.3.3f1 (The new LTS) from my previous version of 2021.2.2f1 has made my previous solution of using Burst 14.0 no longer working. I now receive the same error as before, 
>The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)

**Comment by robojiannis** [comment]
i'm encountering the same issue with the collections unity package; I'm also using unity 2021

**Comment by lukasreuter** [comment]
> Hey @cjcurrie
> 
> Thanks I have seen your comments in discord, I need to figure out this, as Unity should not have an issue compiling as this is a referenced assembly.

The Common.Logging.Core is not an explicitly referenced assembly though, it is set to be auto referenced, meaning every assembly in the project is bloated with this generically named namespace.
The Common class being private from the collections package is not the problem here.

**Comment by juanfranblanco** [comment]
I am considering moving to another common logging framework, but keeping this for backwards compatibility in older versions.

**Comment by Oberhaim** [comment]
HI there, 
Any fix to this issue ? 
Having the same problem...

**Comment by juanfranblanco** [comment]
@Oberhaim on master latest I have changed the logging, although is not released yet

**Comment by JamesW940516** [comment]
Hello?
Could anybody kindly fix this error of my project?

![image](https://github.com/Nethereum/Nethereum/assets/133299884/ae91596a-e017-44b5-b08a-e7b39e10f2f4)

**Comment by c665** [comment]
it's been two years and this issue is still happening
![image](https://github.com/Nethereum/Nethereum/assets/57171464/ee22e3c2-24af-48d2-9839-3ad3374fdfbf)
Unity 2022.3.13f1

**Comment by juanfranblanco** [comment]
This is not a dependency anymore and it was removed specifically for Unity. What version and framework are you using?
