### ISSUE TITLE
EthECKey.RecoverFromSignature is slow

### ISSUE THREAD

**Issue by mightywill** [Nethereum/Nethereum#697]
Hello
Following this issue https://github.com/Nethereum/Nethereum/issues/644
I've found that you have improved signing algorithm and now it can give om my machine near 4500 signatures per second which is pretty good I think
But at the same time a key recovering shows only near 600 keys per sec - and is there any way to improve this too?

**Comment by juanfranblanco** [comment]
Key recovering is not yet optimised, as it uses BouncyCastle, as it needs a big refactoring of the structure.

**Comment by juanfranblanco** [comment]
@mightywill  check the latest
