### ISSUE TITLE
NullReferenceException 

### ISSUE THREAD

**Issue by p231970** [Nethereum/Nethereum#698]
https://github.com/Nethereum/Nethereum/blob/f0f7cbd225fadfce681faff004a57e480428e62b/src/Nethereum.RPC/Eth/DTOs/Transaction.cs#L92
Possibly due to absent Type property new in EIP1559 (this is not the reason, I checked on wrong branch)

it throws "Unable to convert the result to type Nethereum.RPC.Eth.DTOs.Transaction" with inner NullReferenceException when getting pending transactions

**Comment by p231970** [comment]
4.0.2

**Comment by p231970** [comment]
actually you can try this code while transaction still be pending:
        Dim resp = Await web3.Client.SendRequestAsync(Of JToken)("eth_getTransactionByHash", Nothing, "0x6b519f5bb39df71185367ef082450a3ad934fce8c2547ebeb84ffa566f9e9081").ConfigureAwait(False)
        Dim t = resp.ToObject(Of Transaction)()
or change to another hash of any pending transaction

**Comment by juanfranblanco** [comment]
Try 4.0.3 it is fixed there, it was an issue with the patch for Geth 10..6

**Comment by p231970** [comment]
4.0.3 is working. Thanks
