### ISSUE TITLE
getBalance Hex value is correct, decimal value is wrong

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#7]
Using Nethereum to call getBalance I get a result of 0x8ac7230489e80000 which the same request in CURL gives me the same result.

However when accessing the value (BigInteger i assume) like 'Result.Value' it shows -8446744073709551616, it should be 10000000000000000000

**Comment by juanfranblanco** [comment]
What OS are you using? It must be an issue with endianism

**Comment by slothbag** [comment]
Windows 10 64bit

**Comment by juanfranblanco** [comment]
This is an issue with compacting (as per RPC requirements) and Endianism 

` [Fact] `
`        public virtual void ShouldDecode10000000000000000000()`
`        {`
`            var encode = new HexBigInteger(BigInteger.Parse("10000000000000000000"));`
`            var x = new HexBigInteger("0x008ac7230489e80000");`
`            Assert.Equal(encode.Value.ToString(), x.Value.ToString());`
        `}`

As you can see if we add and extra byte of '00' the value is correct, Geth is in BigEndian and they ignore the first bytes which are 00, when reversing to little endian, this is unrecognized

**Comment by juanfranblanco** [comment]
Checked in a fix, which forces the unsigned bytes on the constructor by adding the byte. Keeping it open as negative values are not supported.

**Comment by slothbag** [comment]
Thanks for looking into it. :+1:

**Comment by juanfranblanco** [comment]
Closing. Negative values are not necessary / supported (until further notice / changes in the clients ie geth). No info on how to handle, reverse sign plus 0xFF padding
