### ISSUE TITLE
Nethereum is dropping leading zeros from hex encoded addresses

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#70]
I have a solidity function that returns an address type, when I call the function from Nethereum, it returns a string containing the hex encoded address.  However if the address has leading zeros i.e. 0x012345 then it returns 0x12345.

This shorter address is then incompatible with subsequent calls, I have to check the length and inject zeros to make it conform to the 40 bytes the RPC expects.

**Comment by juanfranblanco** [comment]
Note to self. This is an issue with big endian, little endian and integer decoding, after decoding,  extra bytes need to be added, before hex conversion normally for string type decoding

**Comment by juanfranblanco** [comment]
This should be fixed with the latests, let me know how it goes, I might put later on the output as checksum too, as I have implemented somewhere else.

**Comment by supersbbb** [comment]
I am wondering if this bug has been fixed because I am facing the same issue too. Thanks.

**Comment by juanfranblanco** [comment]
It is fixed but RC6 is not released yet, I will release it today.

**Comment by supersbbb** [comment]
Oh good, thank you. I am waiting on this version.

**Comment by juanfranblanco** [comment]
submitted now :)

**Comment by juanfranblanco** [comment]
Closing as I have been testing this for a while now...
