### ISSUE TITLE
invalid sender: eth_sendRawTransaction

### ISSUE THREAD

**Issue by StrajnarFilip** [Nethereum/Nethereum#703]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

When I specify an account inside a Web3 object (account = private key string), transactions fail due to "invalid sender" error. I followed precise steps from playground, and docs on the website. I tried with both:
- EtherTransferTransactionInputBuilder.CreateTransactionInput + transactionManager.SignTransactionAsync
- and
- Eth.GetEtherTransferService().TransferEtherAndWaitForReceiptAsync

Both give the same error. When I do not pass in Account object (aka I work with the account, unlocked by the geth client), and as I pass only from and to address, transactions work fine, and I've done a lot of them without failure, leading me to believe it's not the fault of my client.

I've also tried it with 3 different private keys, all of them the error is the same (invalid sender: eth_sendRawTransaction)

## Expected Behavior

I'd expect the transactions to be properly signed and sent when I use valid accounts.

## Current Behavior

Throws error, transaction obviously fails

## Steps to Reproduce

Copy paste from http://playground.nethereum.com/csharp/id/1053, plugging in correct private key, correct chain ID and localhost URI

## Context (Environment)

I'm developing within a private blockchain. I'm trying to accomplish a working blockchain.

**Comment by borseno** [comment]
Same bug

**Comment by juanfranblanco** [comment]
Have you included the ChainId?

**Comment by StrajnarFilip** [comment]
> Have you included the ChainId?

Indeed I have.

**Comment by juanfranblanco** [comment]
You should not have an issue with this if you are inputting the right chainId, this is normally an issue with this.
Now the sample needs to be updated to the latest version of Nethereum due to EIP1559.

A super simple example using Nethereum testchain is the following:

```csharp
using System;
using System.Text;
using Nethereum.Hex.HexConvertors.Extensions;
using System.Threading.Tasks;
using Nethereum.Web3;
using Nethereum.Web3.Accounts;
using Nethereum.Hex.HexConvertors.Extensions;
using Nethereum.RPC.TransactionManagers;
using Nethereum.Signer;

public class Program
{
    private static async Task Main(string[] args)
    {
        //First let's create an account with our private key for the account address 
        var privateKey = "0x7580e7fb49df1c861f0050fae31c2224c6aba908e116b8da44ee8cd927b990b0";
        var account = new Account(privateKey, 444444444500);
        Console.WriteLine("Our account: " + account.Address);
        //Now let's create an instance of Web3 using our account pointing to our nethereum testchain
        var web3 = new Web3(account, "http://localhost:8545");

        var toAddress = "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe";

        var transactionManager = web3.TransactionManager;
        var fromAddress = transactionManager?.Account?.Address;
        //Start setup:
        //Sending transaction
        var transactionInput = EtherTransferTransactionInputBuilder.CreateTransactionInput(fromAddress, toAddress, 1.11m, 2);
        //Raw transaction signed
        var rawTransaction = await transactionManager.SignTransactionAsync(transactionInput);
        var txnHash = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync(rawTransaction);
        Console.WriteLine(txnHash);
        var txnReceipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txnHash);
    }
}


```

**Comment by borseno** [comment]
> Have you included the ChainId?

For me, the issue was that I used testnet bsc URL instead of mainnet, when calling mainnet contracts

**Comment by juanfranblanco** [comment]
Closing this issue, if there is any further info Ill reopen.

**Comment by juanfranblanco** [comment]
@mitnick2012 any more info?

**Comment by mitnick2012** [comment]
@juanfranblanco  I tried your code too but I get the same issue

**Comment by juanfranblanco** [comment]
Your chainId is the same as the one as used for the nethereum testchain, is that the same one as in your localhost?

**Comment by mitnick2012** [comment]
@juanfranblanco  how to verify that ?

**Comment by juanfranblanco** [comment]
you will have it on your genesis, or just simply run web3.Eth.ChainId.SendRequestAsync

**Comment by mitnick2012** [comment]
it's working now didn't now that I need to change chainId , but I get an other issue  **Insufficient funds for gas * price + value**

**Comment by mitnick2012** [comment]
yes I know but how to add ether to a test address ?

**Comment by juanfranblanco** [comment]
can we continue this in discord as this is not an issue

**Comment by mitnick2012** [comment]
ok sure

**Comment by GeneratorEVil** [comment]
> 

How u send BEP-20 transaction. When i try to send

**Comment by darkerego** [comment]
> > 
> 
> Hello! How u send BEP-20 tokens? When i try to send by this code :
> 
> var transferHandler = web3.Eth.GetContractTransactionHandler(); var transfer = new TransferFunction() { To = data.AddressTo, Value = valueForTransfer, MaxFeePerGas = gasData.Standard.Price, MaxPriorityFeePerGas = gasData.Standard.Price, Nonce = await account.NonceService.GetNextNonceAsync() }; await transferHandler.SendRequestAndWaitForReceiptAsync(tokenContractAddress, transfer);
> 
> I get invalid sender error

Yes I was getting this. Try only these parameters:

tx = {
                'nonce': nonce,
                'to': _destination,
                'value': self.web3.toWei(qty, 'ether'),
                'gas': 21000,  # 21000
                'gasPrice': self.web3.toWei('5', 'gwei'),
                'chainId': hex(self.web3.eth.chain_id)
            }
