### ISSUE TITLE
Is it possible to connect BSC network with this package?

### ISSUE THREAD

**Issue by atropos0902** [Nethereum/Nethereum#708]
I am wondering if it's possible to connect to BSC network (both Mainnet and Testnet) with this package?
If so can you give me the examples or references to check out?
Thanks!

**Comment by juanfranblanco** [comment]
Yes, BSC is a copy of Ethereum, so it is compatible.

**Comment by moodmosaic** [comment]
Typing this without a compiler but you should get the point:

```csharp
// https://chainlist.org/
// https://docs.binance.org/smart-chain/developer/rpc.html
var chainId = 56;
var jsonRpc = "https://bsc-dataseed.binance.org/";

var account = new Account("<your_private_key>", chainId);
var web3 = new Web3.Web3(account, jsonRpc);

// ...
```

**Comment by atropos0902** [comment]
> Typing this without a compiler but you should get the point:
> 
> ```cs
> using Nethereum.Web3.Accounts;
> 
> // https://chainlist.org/
> // https://docs.binance.org/smart-chain/developer/rpc.html
> var chainId = 56;
> var jsonRpc = "https://bsc-dataseed.binance.org/";
> 
> var account = new Account("<your_private_key>", chainId);
> var web3 = new Web3.Web3(account, jsonRpc);
> 
> // ...
> ```

@moodmosaic Thank you so much! Let me try.

**Comment by juanfranblanco** [comment]
This might help you too https://docs.binance.org/smart-chain/developer/rpc.html
