### ISSUE TITLE
EntryPointNotFoundException When Creating Account

### ISSUE THREAD

**Issue by jettblu** [Nethereum/Nethereum#711]
## Expected Behavior
Wallet.GetAccount() should return an account attached to a HD wallet.

## Current Behavior
An exception is returned that states,_"System.EntryPointNotFoundException: Entry point was not found. at NBitcoin.IBitcoinSerializable.ReadWrite(BitcoinStream stream) at NBitcoin.BitcoinSerializableExtensions.ToBytes(IBitcoinSerializable serializable, Nullable`1 version)..."_

## Steps to Reproduce
 mnemo = new Mnemonic(words, Wordlist.English);
 var seed = mnemo.DeriveSeed();
 var ethWallet = new Nethereum.HdWallet.Wallet(seed);
 var acc = new Account(ethWallet.GetPrivateKey(0));
 var ethAccount = ethWallet.GetAccount(indexAddy);

## Context (Environment)
I am trying to create HD wallets for multiple currencies including ETH. 

## Detailed Description
The documentation should indicate which version of NBItcoin Nethereum is compatible with and/ or the method (instead of the system) should return an exception if unable to find an entry point.

*note, I have never submitted an 'issue' before, so please forgive anything that sounds harsh or provides limited info. Great work on Nethereum!

**Comment by juanfranblanco** [comment]
Hi @jettblu, the current version used  is "5.0.54". I have added an extra unit test for your use case

**Comment by jettblu** [comment]
Awesome, thank you! I will 2x check the patch in the morning.

**Comment by juanfranblanco** [comment]
@jettblu It is not a patch, this is just demonstrating your code working, so you should not have any issues. Also note that if you use a constructor with the words will be exactly the same.

**Comment by jettblu** [comment]
@juanfranblanco I appreciate your time and responses. You indicated the 'get account' function should work regardless of the NBitcoin version, however, I am encountering the same 'Not implemented' error as before. I tried multiple versions of Nbitcoin, but kept Nethereum the same. The packages are managed by Nuget. I assume this is an issue on my end, but I am not certain.

**Comment by Kremed** [comment]
Hello everyone, I am facing the same problem now with Xamarin Maui

**Version package numbers used :**
NBitcoin 5.0.83
Nethereum.HdWallet  4.1.0

**Code :**
```
string Words = new Mnemonic(Wordlist.English, WordCount.Twelve).ToString();
string Password = TxtPassword.Text;
var wallet = new Wallet(Words,Password);
var Account = wallet.GetAccount(0);
```
Error happens here => wallet.GetAccount(0);

it do not catch the error Exception, the application is exited without giving any information about the error ??

I have tried the same lines of code on the Windows Form application and it works without any problems, 
also I am sorry if there are any deficiencies in the explanation, this is the first experience to report a problem

**Comment by Kremed** [comment]
I got a wallet address and a secret key using this code :

```
 string Words = new Mnemonic(Wordlist.English, WordCount.Twelve).ToString();
            string Password = "";
            var wallet = new Nethereum.HdWallet.Wallet(Words, Password);
            for (var i = 0; i < 20; i++)
            {
                var account = wallet.GetAccount(i);
                Console.WriteLine("Account index : " + i + " - Address : " + account.Address + " - Private key : " +
                                  account.PrivateKey);
            }
```

The only change was not to pass the salt password!! 
I did not understand the connection or the reason, but now I am able to continue the work, I hope someone can benefit from this. 

**Great job you are doing Team Nethereum**
