### ISSUE TITLE
Private node. Invalid sender eth_sendRawTransaction

### ISSUE THREAD

**Issue by GianMatelab** [Nethereum/Nethereum#712]
## Expected Behavior
When using SendRequestAndWaitForReceiptAsync or any other method to generate a transaction, the transaction should be created on the target private node

## Current Behavior
Any transaction attempt fails with Invalid Sender. On the private node, a warning is generated "Served eth_sendRawTransation err="invalid sender""

## Steps to Reproduce
The following code is being used. On the very last line, we receive the error.
```csharp 
var sourceaccount = Account.LoadFromKeyStore( File.ReadAllText( "account1.json" ), "test1", 15 );
var target = Account.LoadFromKeyStore( File.ReadAllText( "account2.json" ), "test2", 15 );

var targetnode = new Web3( sourceaccount, "http://<external IP>:8085" );

var balance = targetnode.Eth.GetBalance.SendRequestAsync( sourceaccount.Address ).Result;
Console.WriteLine( "BALANCE >> " + balance.Value );

balance = targetnode.Eth.GetBalance.SendRequestAsync( target.Address ).Result;
Console.WriteLine( "BALANCE (TARGET) >> " + balance.Value );
			
var wei = Web3.Convert.ToWei(1);

var transactionReceipt = targetnode.TransactionManager.TransactionReceiptService.SendRequestAndWaitForReceiptAsync(
								  new TransactionInput() {
									From = sourceaccount.Address,
									To = target.Address,
									Value = new HexBigInteger(wei),
								}, null).Result;
```
## Context (Environment)
Just testing a very basic example for two wallets and a transaction between them.

## Detailed Description
The geth node is setup with a ChainId value of 15, confirmed by the admin.nodeInfo command. The account balance commands return the correct balance for both accounts and the source account has more than enough funds. 
The account json data has been downloaded directly from the server keystore.
We have tried multiple approaches based on the different samples we've found but all them ultimately fail with  an Invalid Sender error. Creating the very same transaction on geth console, on the server, is successful and the transfer is made after mining is completed.

**Comment by juanfranblanco** [comment]
To keep you sane, this is a quick test, using the the ethereum test chain here: 
https://github.com/Nethereum/TestChains (using Windows which has the latest)

what version of Eth are you using, is 1559 enabled?

```csharp
using System;
using System.Threading.Tasks;
using Nethereum.Web3;
using Nethereum.Web3.Accounts;
using Nethereum.Hex.HexTypes;
using Nethereum.RPC.Eth.DTOs;


public class Program
{
    private static async Task Main(string[] args)
    {
        //First let's create an account with our private key for the account address 
        var privateKey = "0x7580e7fb49df1c861f0050fae31c2224c6aba908e116b8da44ee8cd927b990b0";
        var account = new Account(privateKey, 444444444500);
        Console.WriteLine("Our account: " + account.Address);
        //Now let's create an instance of Web3 using our account pointing to our nethereum testchain
        var web3 = new Web3(account, "http://localhost:8545");

        var balance = web3.Eth.GetBalance.SendRequestAsync(account.Address).Result;
        Console.WriteLine("BALANCE >> " + balance.Value);

        balance = web3.Eth.GetBalance.SendRequestAsync(account.Address).Result;
        Console.WriteLine("BALANCE (TARGET) >> " + balance.Value);

        var wei = Web3.Convert.ToWei(1);

        var transactionReceipt = await web3.Eth.TransactionManager.TransactionReceiptService.SendRequestAndWaitForReceiptAsync(
                                          new TransactionInput()
                                           {
                                              From = account.Address,
                                              To = account.Address,
                                              Value = new HexBigInteger(wei),
                                          }, null);
        var x = 0;
    }
}
```
[TestProjectTransfer.zip](https://github.com/Nethereum/Nethereum/files/7201726/TestProjectTransfer.zip)

**Comment by GianMatelab** [comment]
Using the pre-configured test chain it does work. Guess I'll have to check the remote node configuration.
Thank you for your time on this.

**Comment by juanfranblanco** [comment]
If you don't have enabled 1559, set web3.Eth.TransactionManager LegacyMode to true. That might help solve the problem

**Comment by GianMatelab** [comment]
Ah yes! The flag was UseLegacyAsDefault but now it is working also on the remote geth. How can I check if 1559 is enabled?

**Comment by juanfranblanco** [comment]
Mainly depends on your chain, Ethereum mainnet has 1559 enabled and the testnets, but others are yet (or are not going to be implemented). I am thinking of creating a generic configuration for each chainId.

**Comment by will0225** [comment]
Hello, I am getting same error now with rinkeby testnetwork
            var privateKey = "..............................................";
            var account = new Account(privateKey, 42);
            var web3 = new Web3(account, "https://rinkeby.infura.io/v3/e9752da5067149f9bf96c54f2bfe4e90");
            var erc721PresetMinter = new NFTMarketDeployment() {};
             var deploymentReceipt = await NFTMarketService.DeployContractAndWaitForReceiptAsync(web3, erc721PresetMinter);
            var erc721PresetMinterService = new NFTMarketService(web3, deploymentReceipt.ContractAddress);
            Console.WriteLine("Market Smart contract deployed at address:" + deploymentReceipt.ContractAddress);

This is my code
Please help me

**Comment by juanfranblanco** [comment]
@will0225 Rinkeby chainId is 4 not 42

**Comment by will0225** [comment]
thanks, one more question.
after minting token in Nethereum, How can I get token Id just minted?

**Comment by will0225** [comment]
This is code

            var erc721PresetMinterService = new NFTService(web3, ".....");
            var marketService = new NFTMarketService(web3, "....");    

            var mintingResult = await erc721PresetMinterService.CreateTokenRequestAndWaitForReceiptAsync("some url");

            Console.WriteLine("minting success", mintingResult.Logs);

**Comment by will0225** [comment]
I changed  42 with 4, but I am getting same error
![image](https://user-images.githubusercontent.com/51754234/146885157-7f3f441c-04cb-4ba4-87da-d721707e5d75.png)

**Comment by juanfranblanco** [comment]
@will0225 you are using Metamask, so this is a completely different error, have you checked the MM template ?

**Comment by will0225** [comment]
I did never checked MM template yet

**Comment by juanfranblanco** [comment]
So how are you connecting with MM?

**Comment by will0225** [comment]
I am using Nethereum UI template

**Comment by juanfranblanco** [comment]
AH.. it is the same https://github.com/Nethereum/Nethereum.Metamask.Blazor

**Comment by will0225** [comment]
![image](https://user-images.githubusercontent.com/51754234/146885942-b5758ce5-1af3-475b-a54a-3b83e793722d.png)

**Comment by will0225** [comment]
Please help  me with what was wrong.

**Comment by will0225** [comment]
also How can I get tokenId as soon as minting token?

**Comment by juanfranblanco** [comment]
Yes you account there, is not used for anything (private key and chainId) as you are connecting using MM.
Your issue is with the NFTs, as you see from your error is says that you are "minting to the zero address"

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L281

Have you supplied the address?

**Comment by will0225** [comment]
Yes, I already did

**Comment by will0225** [comment]
When I have been creating C# console project and minting NFT, it is working well now without issue.
But when I use MM template, it get this error.

**Comment by juanfranblanco** [comment]
Token id https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L289 is in an event.

**Comment by will0225** [comment]
![image](https://user-images.githubusercontent.com/51754234/146886958-256a89c0-5bbe-43d9-af04-f092db62bc94.png)
when create Console project, it worked well as you see image.

**Comment by juanfranblanco** [comment]
The best thing is to check your smart contract

**Comment by will0225** [comment]
Smart contract is sample code, it is correct

https://dev.to/dabit3/building-scalable-full-stack-apps-on-ethereum-with-polygon-2cfb

**Comment by will0225** [comment]
Only I converted sol file to c#

**Comment by juanfranblanco** [comment]
Ah I see what is happening here, when doing the estimation, the msg.sender is not set with MM just use the overload of CreateTokenRequest... with the TokenFunction and set the From to your selected MM account address.

**Comment by will0225** [comment]
ok, let me try
How can I return tokenId  when minting NFT?

**Comment by juanfranblanco** [comment]
From the event, check the http://playground.nethereum.com for examples (getting started with events)
