### ISSUE TITLE
Negative BigDecimal ToString issue

### ISSUE THREAD

**Issue by mikhail-khalizev** [Nethereum/Nethereum#713]
BigDecimal will incorrectly convert to a string when negative.

Code:
```
Console.WriteLine((Nethereum.Util.BigDecimal)(-0.0123));
```
Produces `0.0-123` instead of `-0.0123`.

**Comment by juanfranblanco** [comment]
Thanks @mikhail-khalizev this is fixed in the latest check extra tests added https://github.com/Nethereum/Nethereum/commit/1e5622770471f45bfd405ac08899baee15cf1cbd
