### ISSUE TITLE
unity build  error on webgl ,pls help

### ISSUE THREAD

**Issue by levine2008** [Nethereum/Nethereum#714]
hi 
    it is ok on unity editor,but I switch to webgl platform and build project ,it reports error,pls help ,thks 

ArgumentException: The Assembly WindowsBase is referenced by System.Reactive ('Assets/Plugins/System.Reactive.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <a9d6276083484759be43f20e6e92863e>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <a9d6276083484759be43f20e6e92863e>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by juanfranblanco** [comment]
@levine2008 all the dlls included have a bigger set than the webgl.

**Comment by levine2008** [comment]
hi， junfranblanco, I  Didn't understand how to solve it.  ^_____^

**Comment by juanfranblanco** [comment]
Apologies that sounded more crypted that I wanted, Webgl has a smaller support of features, the releases and samples include all dlls as the net461 enabled all the vanilla support of Nethereum, but yes it will break some areas, as not supported.

Just include these dlls, same subset as net351 and you should be ok:

![image](https://user-images.githubusercontent.com/562371/135402295-dd60ebe5-b9be-492c-8ffe-ba4b173b69e3.png)

Note to self (do a package of the above)

**Comment by bitmammoth** [comment]
I tried this but it did not work for me on webgl. It gives me this 

error: 
CS0234: The type or namespace name 'Web3' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

**Comment by shantanhunt** [comment]
Hi @juanfranblanco I am facing the same issue. Pls help!

**Comment by shantanhunt** [comment]
I am on Unity 2020.3.17

**Comment by ljhx2** [comment]
Maybe this problem is due to IL2CPP

In my case,
I solved it by downloading 
System.Reactive.dll from https://www.nuget.org/ and replacing 
Plugin\System.Reactive.dll with lib\netstandard2.0\System.Reactive.dll

**Comment by ryokomy** [comment]
I faced the same issue and @juanfranblanco 's comment (https://github.com/Nethereum/Nethereum/issues/714#issuecomment-930876783) was so helpful.

In my case, Common.Logging.Core was also needed in addition to the files shown on his comment.

**Comment by ryokomy** [comment]
Please use [net461dllsAOTCustom.zip](https://github.com/Nethereum/Nethereum/files/7690933/net461dllsAOTCustom.zip) if you want. It contains all files I needed.

**Comment by ramazanulucay** [comment]
@ryokomy I use your zip. Another error has occurred.

Assets\GetLatestBlockVanillaNethereum.cs(40,24): error CS0012: The type 'IClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'Nethereum.JsonRpc.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=8768a594786aba4e'.

Assets\GetLatestBlockVanillaNethereum.cs(40,24): error CS0012: The type 'IAccount' is defined in an assembly that is not referenced. You must add a reference to assembly 'Nethereum.RPC, Version=4.0.0.0, Culture=neutral, PublicKeyToken=8768a594786aba4e'.

Assets\GetLatestBlockVanillaNethereum.cs(42,38): error CS0012: The type 'IEthApiContractService' is defined in an assembly that is not referenced. You must add a reference to assembly 'Nethereum.Contracts, Version=4.0.0.0, Culture=neutral, PublicKeyToken=8768a594786aba4e'.

**Comment by AnhPham** [comment]
> Please use [net461dllsAOTCustom.zip](https://github.com/Nethereum/Nethereum/files/7690933/net461dllsAOTCustom.zip) if you want. It contains all files I needed.

This worked for me! Thanks!

**Comment by juanfranblanco** [comment]
Check the the https://github.com/Nethereum/Nethereum.Unity.Webgl if you have any issues and as an example of integration with MM, also the subset of dlls is included here: https://github.com/Nethereum/Nethereum.Unity.Webgl/tree/main/Assets/Plugins

**Comment by AnhPham** [comment]
> Check the the https://github.com/Nethereum/Nethereum.Unity.Webgl if you have any issues and as an example of integration with MM, also the subset of dlls is included here: https://github.com/Nethereum/Nethereum.Unity.Webgl/tree/main/Assets/Plugins

This may the best for me. Thank you so much! Check it now!

**Comment by billysha** [comment]
@juanfranblanco The Assembly WindowsBase is referenced by System.Reactive ('Assets/Plugins/System.Reactive.dll'). But the dll is not allowed to be included or could not be found.
how can I solve it?

**Comment by quitozang** [comment]
why can‘t I find the Nethereum.Unity.dll from nuget?
![image](https://user-images.githubusercontent.com/12569046/203679239-a09e5477-5963-4591-8635-ec8ed7ce4f0d.png)

**Comment by juanfranblanco** [comment]
@quitozang Unity packages are released here (https://github.com/Nethereum/Nethereum/releases)
