### ISSUE TITLE
Nethereum, EdjCase.JsonRpc and Mono 4.4.x

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#72]
I have discovered a strange issue with the three pieces of software mentioned in the title.

You can see a related issue here: https://github.com/edjCase/JsonRpc/issues/28

If I create a new project with Nethereum and EdjCase.JsonRpc, and call a eth_call like such:
```
var web3 = new Web3(ethereum_address);
var myContract = web3.Eth.GetContract(abi, contractAddress);
var myFunction = myContract.GetFunction("getAddress");
string address = myFunction.CallAsync<string>("test").Result;
```

Then it works on Mono just fine.  But within the scope of my larger project EdjCase.JsonRpc throws a strange error about `Field 'System.Net.HttpWebRequest.ResendContentFactory' not found.`

I can't quite pinpoint at which point in this chain of software is causing the error.  Any help would be greatly appreciated.

**Comment by juanfranblanco** [comment]
Well all points out at mono, they have a custom system.net.http (top of my head) maybe you are using different versions?

**Comment by slothbag** [comment]
I found the culprit..  is the Mono.Security.dll.

If its in the same folder as the exe then it must override or hook itself in somehow and causes the error. If you remove the dll everything works.

Strange.
