### ISSUE TITLE
How to use the  EthereumMessageSigner() function sign "signPersonalMessage" message  in Dapps

### ISSUE THREAD

**Issue by liuzhenLz** [Nethereum/Nethereum#726]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

## Steps to Reproduce

1.
1.
1.
1.

**Comment by juanfranblanco** [comment]
No more information given, also addressed in discord
