### ISSUE TITLE
EstimateGas function does not implement all arguments

### ISSUE THREAD

**Issue by brendan87** [Nethereum/Nethereum#73]
According to the JSON RPC docs [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas), eth_estimateGas should be able to take the same arguments as eth_call (a message call object and an optional block parameter). It doesn't appear that Nethereum supports calling estimateGas with a block parameter at the moment. It would be great to see it in there :)

**Comment by juanfranblanco** [comment]
As I recall I have to take it out as it was not needed, actually it was failing due to too many parameters

**Comment by juanfranblanco** [comment]
See changes https://github.com/Nethereum/Nethereum/commit/41d389ae87358f30df8e32d841b55ab1c7c3fa0a
11
