### ISSUE TITLE
Eip712TypedDataSigner doesn't support Arrays and SignTypedData() returns wrong signature

### ISSUE THREAD

**Issue by gcbsumid** [Nethereum/Nethereum#730]
Currently, Eip712TypedDataSigner.SignTypedData() returns the wrong signature compared to ethers. Eip712TypedDataSigner also doesn't support encoding arrays in the TypedData. 

## Expected Behavior
EIP712TypedDataSigner.SignedTypedData() returns the correct signature to ethers._signTypeData() for typedData with and without arrays.

### EIP712TypedDataSigner.SignedTypedData() issue
Regarding the `Eip712TypedDataSigner.SignTypedData()`, it's returning the wrong signature when compared to ethers:
`
await ethers.provider.getSigner(_signer)._signTypedData(domain, Types, value);
`

### Eip712TypedDataSigner.EncodeTypedData() doesn't support arrays
As seen in Eip712TypedDataSigner:119-137:
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer.EIP712/Eip712TypedDataSigner.cs
`
    private static bool IsReferenceType(string typeName)
    {
        switch (typeName)
        {
            // TODO: specify more precise conditions
            case var bytes when new Regex("bytes\\d+").IsMatch(bytes):
            case var @uint when new Regex("uint\\d+").IsMatch(@uint):
            case var @int when new Regex("int\\d+").IsMatch(@int):
            case "bytes":
            case "string":
            case "bool":
            case "address":
                return false;
            **case var array when array.Contains("["):
                throw new NotImplementedException("Array types are not supported");**
            default:
                return true;
        }
    }
`
This is important because we can't sign typed data with parameters. So for things like "mintBatch()" where we pass in multiple tokenIds, signing fails. Because of this, EIP712TypedDataSigner.SignedTypedData() will return the wrong signature.

## Possible Solution
`
var hashedData = Sha3Keccack.Current.CalculateHash(Eip712TypedDataSigner.Current.EncodeTypedData(typedData));

string signature = EthECDSASignature.CreateStringSignature(eCKey.SignAndCalculateV(hashedData));
`
returns the correct signature for typedData without arrays.

For the arrays, it needs to be implemented.

## Steps to Reproduce
Ethers: 
`
    async function sign(_to, _tokenIds, _amounts, _nonce, _signer, _contract) {
	const chainId = Number(await web3.eth.getChainId());
    console.log(chainId);
    console.log(_contract);
    const domain = {
        name: "MintData",
        version: "1",
        chainId: chainId,
        verifyingContract: _contract
    };

    const value = {
        to: _to,
        tokenIds: _tokenIds,
        amounts: _amounts,
        nonce: _nonce,
        signer: _signer
    };

    return await ethers.provider.getSigner(_signer)._signTypedData(domain, Types, value);
}
`

C# 
`  var typedData = new TypedData
  {
      Domain = new Domain
      {
          Name = "MintData",
          Version = "1",
          ChainId = chainId,
          VerifyingContract = verifyingContract
      },
      Types = new Dictionary<string, MemberDescription[]>
      {
          ["EIP712Domain"] = new[]
          {
              new MemberDescription {Name = "name", Type = "string"},
              new MemberDescription {Name = "version", Type = "string"},
              new MemberDescription {Name = "chainId", Type = "uint256"},
              new MemberDescription {Name = "verifyingContract", Type = "address"},
          },
          ["MintData"] = new[]
          {
              new MemberDescription {Name = "to", Type = "address"},
              new MemberDescription {Name = "tokenIds", Type = "uint256[]"},
              new MemberDescription {Name = "amounts", Type = "uint256[]"},
              new MemberDescription {Name = "nonce", Type = "uint256"},
              new MemberDescription {Name = "signer", Type = "address"},
          }
      },
      PrimaryType = "MintData",
      Message = new[]
      {
          new MemberValue {TypeName = "address", Value = data.to},
          new MemberValue {TypeName = "uint256[]", Value = data.tokenIds.ToArray()},
          new MemberValue {TypeName = "uint256[]", Value = data.amounts.ToArray()},
          new MemberValue {TypeName = "uint256", Value = data.nonce},
          new MemberValue {TypeName = "address", Value = account.Address}
      }
  };
  
  var incorrectSignature = eip712Signer.SignTypedData(typedData, eCKey);`

## Context (Environment)

I'm trying to mint multiple tokens and have a stored permissioned wallet sign the transaction. Arrays being unsupported won't let me do this. 

## Detailed Description
Please implement encoding arrays into the TypedData.

Regarding the wrong signature, currently, I'm just going to use: 

`
  var hashedData = Sha3Keccack.Current.CalculateHash(Eip712TypedDataSigner.Current.EncodeTypedData(typedData));
  string signature = EthECDSASignature.CreateStringSignature(eCKey.SignAndCalculateV(hashedData));
`

**Comment by juanfranblanco** [comment]
On the latest commit i have added support for V4 arrays and complex types using a combination of a generic definition and complex messages, hopefully this can help you. Let me know how it goes.

https://github.com/Nethereum/Nethereum/blob/ad7b4cd23adc6a478849aded47bb88833e0a2a1b/tests/Nethereum.Signer.UnitTests/Eip712TypedDataSignerSimpleScenarioTest.cs

```csharp
using System.Collections.Generic;
using Nethereum.Signer.EIP712;
using Nethereum.Util;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Xunit;

namespace Nethereum.Signer.UnitTests
{
    public class Eip712TypedDataSignerSimpleScenarioTest
    {
        private readonly Eip712TypedDataSigner _signer = new Eip712TypedDataSigner();

        //Message types for easier input
        public class Mail
        {
            [Parameter("tuple", "from", 1, "Person")]
            public Person From { get; set; }

            [Parameter("tuple[]", "to", 2, "Person[]")]
            public List<Person> To { get; set; }

            [Parameter("string", "contents", 2)]
            public string Contents { get; set; }
        }

        public class Person
        {
            [Parameter("string", "name", 1)]
            public string Name { get; set; }

            [Parameter("address[]", "wallets", 2)]
            public List<string> Wallets { get; set; }
        }

        //The generic Typed schema defintion for this message
        public TypedData GetMailTypedDefintion()
        {
            return new TypedData
            {
                Domain = new Domain
                {
                    Name = "Ether Mail",
                    Version = "1",
                    ChainId = 1,
                    VerifyingContract = "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
                },
                Types = new Dictionary<string, MemberDescription[]>
                {
                    ["EIP712Domain"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "version", Type = "string"},
                        new MemberDescription {Name = "chainId", Type = "uint256"},
                        new MemberDescription {Name = "verifyingContract", Type = "address"},
                    },
                    ["Group"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "members", Type = "Person[]"},

                    },
                    ["Mail"] = new[]
                    {
                        new MemberDescription {Name = "from", Type = "Person"},
                        new MemberDescription {Name = "to", Type = "Person[]"},
                        new MemberDescription {Name = "contents", Type = "string"},
                    },
                    ["Person"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "wallets", Type = "address[]"},
                    },
                },
                PrimaryType = "Mail",
            };
        }

        [Fact]
        private void ComplexMessageTypedDataEncodingShouldBeCorrectForV4IncludingArraysAndTypes()
        {
            var typedData = GetMailTypedDefintion();

            var mail = new Mail
            {
                From = new Person { Name = "Cow", Wallets = new List<string> { "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826", "0xDeaDbeefdEAdbeefdEadbEEFdeadbeEFdEaDbeeF" } },
                To = new List<Person>(),
                Contents = "Hello, Bob!"
            };
            mail.To.Add(new Person { Name = "Bob", Wallets = new List<string> { "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB", "0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57", "0xB0B0b0b0b0b0B000000000000000000000000000" } });
      
            var key = new EthECKey("94e001d6adf3a3275d5dd45971c2a5f6637d3e9c51f9693f2e678f649e164fa5");
            var signature = _signer.SignTypedDataV4(mail, typedData, key);
            Assert.Equal("0x943393c998ab7e067d2875385e2218c9b3140f563694267ac9f6276a9fcc53e15c1526abe460cd6e2f570a35418f132d9733363400c44791ff7b88f0e9c91d091b", signature);
            var addressRecovered = _signer.RecoverFromSignatureV4(mail, typedData, signature);
            var address = key.GetPublicAddress();
            Assert.True(address.IsTheSameAddress(addressRecovered));

        }

    }
}

```

**Comment by juanfranblanco** [comment]
Another iteration, this makes it more simpler to define the types:

```csharp
 public class Eip712TypedDataSignerSimpleScenarioTest
    {
        private readonly Eip712TypedDataSigner _signer = new Eip712TypedDataSigner();

        //Message types for easier input
        [Struct("Mail")]
        public class Mail
        {
            [Parameter("tuple", "from", 1, "Person")]
            public Person From { get; set; }

            [Parameter("tuple[]", "to", 2, "Person[]")]
            public List<Person> To { get; set; }

            [Parameter("string", "contents", 3)]
            public string Contents { get; set; }
        }

        [Struct("Person")]
        public class Person
        {
            [Parameter("string", "name", 1)]
            public string Name { get; set; }

            [Parameter("address[]", "wallets", 2)]
            public List<string> Wallets { get; set; }
        }

        [Struct("Group")]
        public class Group
        {
            [Parameter("string", "name", 1)]
            public string Name { get; set; }

            [Parameter("tuple[]", "members", 2, "Person[]")]
            public List<Person> Members { get; set; }
        }

        //The generic EIP712 Typed schema defintion for this message
        public TypedData<Domain> GetMailTypedDefinition()
        {
            return new TypedData<Domain>
            {
                Domain = new Domain
                {
                    Name = "Ether Mail",
                    Version = "1",
                    ChainId = 1,
                    VerifyingContract = "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
                },
                Types = MemberDescriptionFactory.GetTypesMemberDescription(typeof(Domain), typeof(Group), typeof(Mail), typeof(Person)),
                PrimaryType = nameof(Mail),
            };
        }

        [Fact]
        private void ComplexMessageTypedDataEncodingShouldBeCorrectForV4IncludingArraysAndTypes()
        {
            var typedData = GetMailTypedDefinition();

            var mail = new Mail
            {
                From = new Person 
                { 
                  Name = "Cow", 
                  Wallets = new List<string> { "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826", "0xDeaDbeefdEAdbeefdEadbEEFdeadbeEFdEaDbeeF" } 
                },
                To = new List<Person>
                {
                    new Person 
                    { 
                        Name = "Bob", 
                        Wallets = new List<string> { "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB", "0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57", "0xB0B0b0b0b0b0B000000000000000000000000000" } 
                    }
                },
                Contents = "Hello, Bob!"
            };

            typedData.Domain.ChainId = 1;
            
            var key = new EthECKey("94e001d6adf3a3275d5dd45971c2a5f6637d3e9c51f9693f2e678f649e164fa5");

            var signature = _signer.SignTypedDataV4(mail, typedData, key);
            
            Assert.Equal("0x943393c998ab7e067d2875385e2218c9b3140f563694267ac9f6276a9fcc53e15c1526abe460cd6e2f570a35418f132d9733363400c44791ff7b88f0e9c91d091b", signature);
            
            var addressRecovered = _signer.RecoverFromSignatureV4(mail, typedData, signature);
            var address = key.GetPublicAddress();
            
            Assert.True(address.IsTheSameAddress(addressRecovered));

        }

    }
```

**Comment by avifeld9** [comment]
Can you please give please  an example of how do I verify the array of    "new MemberDescription {Name = "wallets", Type = "address[]"}".  in the solidity code?
