### ISSUE TITLE
HttpClient shouldn't be rotated for .net 5 (and newer?)

### ISSUE THREAD

**Issue by imerr** [Nethereum/Nethereum#732]
We've been running into some weird exceptions related to socket opening when making a lot of requests
> System.Net.Http.HttpRequestException: Cannot assign requested address (*rpc endpoint here*)

Looking at the process fd usage, there's thousands of connections open to the rpc endpoint, even though the max connections are set to a reasonable number
I believe the default RpcClient does not handle .net 5 correctly, it seems to fall back to the http client recreation code, which should not be needed on modern versions from what I understand?
To test this I've created a custom rpc client, that just uses only one httpclient and that seems to behave as expected & only use up to the max connections specified - I'm not 100% sure this would work for all cases though so I figured I'd just create an issue and ask for input

Relevant code:

https://github.com/Nethereum/Nethereum/blob/641d6dc3c604d94fa867c14cfa5d9b6ce75c2a4d/src/Nethereum.JsonRpc.RpcClient/RpcClient.cs#L49-L54

**Comment by juanfranblanco** [comment]
Yes! well spotted, thank you.

**Comment by juanfranblanco** [comment]
Fixed now, and added NET5_0 Or greater, thank you!!

**Comment by imerr** [comment]
Nice, thanks for the quick response & fix
