### ISSUE TITLE
Too many calls to `net_version` for simple usage

### ISSUE THREAD

**Issue by isaiah** [Nethereum/Nethereum#733]
Made a few calls to filter logs on Infura Ropsten testnet, it quickly consumed my quota on Infura, most of the calls were to the `net_version` endpoint, is this intended? Is it possible to cache the calls?
![2021-11-11-100433_3090x883_scrot](https://user-images.githubusercontent.com/18042/141271129-32394e67-2ca8-4427-bce0-d79c1fa65397.png)

**Comment by juanfranblanco** [comment]
@isaiah Nethereum should not be calling net_version, what are you using?

**Comment by isaiah** [comment]
@juanfranblanco Thanks for the quick reply.
Pretty sure I'm only using Nethereum, great work btw. I was following the event log filtering tutorial: http://docs.nethereum.com/en/latest/nethereum-events-gettingstarted/#contract-filters-and-event-logs

**Comment by juanfranblanco** [comment]
What version / package of Nethereum are you using?

**Comment by isaiah** [comment]
4.1.1

**Comment by juanfranblanco** [comment]
It is not used anywhere internally:
![image](https://user-images.githubusercontent.com/562371/141283813-5d64e08e-d3c2-446e-a71e-9b09f72dc5cd.png)

**Comment by juanfranblanco** [comment]
Can you try to change your infuraId?

**Comment by isaiah** [comment]
@juanfranblanco Thanks for checking, I'm not able to reproduce the problem with the same code, Infura dashboard also doesn't seem to be updated in realtime, will keep you updated in case I find something.
