### ISSUE TITLE
TransferEtherAndWaitForReceiptAsync never back

### ISSUE THREAD

**Issue by liuqiba** [Nethereum/Nethereum#735]
code：

private async Task<bool> Trans(string fAddress,string privateKey, string toAddress, decimal amount)
        {
            bool suc = false;
            var account = new Account(privateKey,mData.ChainId);
            Logger.Debug("Our account: " + account.Address + " toAddress "+ toAddress + " amount " + amount);
            //Now let's create an instance of Web3 using our account pointing to our nethereum testchain
            var web3 = new Web3(account, mData.Url);

          

            // Lets transfer 1.11 Ether
            var transaction = await web3.Eth.GetEtherTransferService()
                .TransferEtherAndWaitForReceiptAsync(toAddress, amount);

            Logger.Debug($"转账成功 TransactionHash {transaction.TransactionHash} GasUsed {transaction.GasUsed}  BlockHash {transaction.BlockHash}  Status {transaction.Status}");
            suc = true;
            return suc;
        }

 await Trans(user.fromAddress, privateKey, address1, amount);

await Trans(user.fromAddress, privateKey, address2, amount);

--------------------------------------------------------------------

I tried, first "Trans" sucessed ,but second never come back,await forever
only once like this

**Comment by juanfranblanco** [comment]
Create an instance of Web3 before hand and pass it as a parameter, this way the nonce counter will be incremented correctly.

**Comment by liuqiba** [comment]
> Create an instance of Web3 before hand and pass it as a parameter, this way the nonce counter will be incremented correctly.

I do`t know your means,can you give me a sample? Thank you!

**Comment by juanfranblanco** [comment]
```csharp
private async Task Trans(Web3 web3, string fAddress,string privateKey, string toAddress, decimal amount)
{
bool suc = false;


        // Lets transfer 1.11 Ether
        var transaction = await web3.Eth.GetEtherTransferService()
            .TransferEtherAndWaitForReceiptAsync(toAddress, amount);

        Logger.Debug($"转账成功 TransactionHash {transaction.TransactionHash} GasUsed {transaction.GasUsed}  BlockHash {transaction.BlockHash}  Status {transaction.Status}");
        suc = true;
        return suc;
    }

// I am assuming your issue is that you are using the same private key
private async Task Test(){
var account = new Account(privateKey,mData.ChainId);
Logger.Debug("Our account: " + account.Address + " toAddress "+ toAddress + " amount " + amount);
//Now let's create an instance of Web3 using our account pointing to our nethereum testchain
var web3 = new Web3(account, mData.Url);
await Trans(web3, user.fromAddress, privateKey, address1, amount);

await Trans(web3, user.fromAddress, privateKey, address2, amount);
}
```
