### ISSUE TITLE
not able create contract

### ISSUE THREAD

**Issue by punnooseJosephPachikkara** [Nethereum/Nethereum#737]
string     dir = Directory.GetCurrentDirectory();
 string fileInvoiceNFT = dir + @"\wwwroot\Artifacts\InvoiceNFT.json";
              using (StreamReader r = new StreamReader(fileInvoiceNFT))
            {
                jsonInvoiceNFT = r.ReadToEnd().Replace("\n", "");
                
            }
 string contractAddressInvoiceNFT = "0x4fc968742e35A65be013729a109e4Af26A1c79aC";//From Truffle
              string url = "HTTP://localhost:7545";//From Ganache
            Web3 web3 = new Web3(url);

            var contractInvoiceNFT = web3.Eth.GetContract(jsonInvoiceNFT, contractAddressInvoiceNFT);

I am getting error "Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.List`1[System.Collections.Generic.IDictionary`2[System.String,System.Object]]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'contractName', line 1, position 18."
    "

Please do help me fix it

**Comment by juanfranblanco** [comment]
@punnooseJosephPachikkara your abi json is not well formatted. Please post general support questions in discord, thank you.

**Comment by punnooseJosephPachikkara** [comment]
@juanfranblanco   Can you please send the code to retrieve a abi json file which i have place inside my project folder.
