### ISSUE TITLE
Web3.FunctionBase - return multiple parameter values

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#74]
Found your comment -    "Only one output parameter supported to be decoded this way, use a FunctionOutputAttribute or define each outputparameter");

how will this be called to get both parameters- 

**mapping(bytes32 => DocumentInfo[]) public transfers;**

---------Ignore the issue below -----original ticket below------------------

While looking up values for a function return with struct parameter - ex. 

mapping(bytes32 => DocumentInfo[]) public transfers;

Returns only single parameter (first entry - 

>         protected async Task<TReturn> CallAsync<TReturn>(string encodedFunctionCall)
>         {
>             var result =  await ethCall.SendRequestAsync(new CallInput(encodedFunctionCall, ContractAddress), DefaultBlock);
> 
>             return FunctionCallDecoder.DecodeSimpleTypeOutput<TReturn>(**GetFirstParameterOrNull**(FunctionABI.OutputParameters), result);
> 
>         }

Ex. This return does not work

var doesexist = await exists.CallAsync<DocumentInfo>("2232853457cc9eb0fefd69e4c32c943", i);

only this works

var doesexist = await exists.CallAsync<string>("2232853457cc9eb0fefd69e4c32c943", i);

**Comment by juanfranblanco** [comment]
You will need a FunctionOutput see https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3.Tests/DaoTest.cs#L110-L153

and see 
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3.Tests/DaoTest.cs#L53-L54

**Comment by juanfranblanco** [comment]
Also check your abi generated.. you may be going a bit too far using an struct array as a mapping

**Comment by ushakrishnan** [comment]
Thank you for the reference to DaoTest.  I did implement as indicated, however when using CallDeserializingToObjectAsync, I get back null, null (two item array).  If I keep the sol the same but only change the return to string and use CallAsync, I get the first paramter.  I will debug again to see what the issue is.  

I used ethereum wallet and ran the code, and I did get back the array elements correctly. 

Will debug again.

Many thanks for the pointer, I will check again

**Comment by juanfranblanco** [comment]
Ok if you look at your abi you have as an input two parameters one, the key bytes32 the other the index number of your array, the output should be your document struct attributes

**Comment by juanfranblanco** [comment]
Like I said, start simple, then make it more complex..

**Comment by juanfranblanco** [comment]
Here is a video which it might help (as it was inspired by your issue :) ) https://youtu.be/o8UC96K0rg8

**Comment by ushakrishnan** [comment]
You are awesome!  Thank you :-)
