### ISSUE TITLE
SwapExactETHForTokensRequestAsync error: transaction type not supported

### ISSUE THREAD

**Issue by andreafi** [Nethereum/Nethereum#741]
I am trying to swap 0.02 WBNB with BUSD.
SwapExactETHForTokensRequestAsync request always gives me an error on "eth_sendRawTransaction" request: transaction type not supported

I can't find any solution.
Is it a bug or am I wrong something I don't understand?

Thanks a lot.

                Web3 = new Web3(Account, "https://bsc-dataseed.binance.org", log);
                List<string> path = new() { "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c", "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56" };

                BigInteger deadline = DateTimeOffset.Now.AddMinutes(15).ToUnixTimeSeconds();
                BigInteger amountIn = BigInteger.Parse("20000000000000000");
                var swapDTO = new SwapExactETHForTokensFunction()
                {
                    AmountToSend = amountIn,
                    AmountOutMin = amountOutMin,
                    Path = path,
                    To = to,
                    Deadline = deadline
                };

                var swapReceipt = router.SwapExactETHForTokensRequestAsync(swapDTO).Result;

**Comment by juanfranblanco** [comment]
Please set the GasPrice or web3.Eth.TransactionManager.UseLegacyAsDefault as BSC does not support 1559

**Comment by andreafi** [comment]
Thanks Juanfranblanco.
It worked!!
