### ISSUE TITLE
return object[] only return array last 解析结构数组写错了，只返回数组最后一个

### ISSUE THREAD

**Issue by yyd1234** [Nethereum/Nethereum#744]
public object DecodeAttributes(byte[] output, object result, params PropertyInfo[] properties)
        {
            if (output == null || output.Length == 0) return result;
            var parameterObjects = GetParameterOutputsFromAttributes(properties);
            var orderedParameters = parameterObjects.OrderBy(x => x.Parameter.Order).ToArray();
            var parameterResults = DecodeOutput(output, orderedParameters);

            foreach (var parameterResult in parameterResults)
            {
                var parameter = (ParameterOutputProperty)parameterResult;
                var propertyInfo = parameter.PropertyInfo;
                var decodedResult = parameter.Result;

                if (parameter.Parameter.ABIType is TupleType tupleType)
                {

                    decodedResult = Activator.CreateInstance(propertyInfo.PropertyType);
                    AssingValuesFromPropertyList(decodedResult, parameter);
                }
#if DOTNET35
                propertyInfo.SetValue(result, decodedResult, null);
#else
                propertyInfo.SetValue(result, decodedResult);
#endif
            }

            return result;
        }

**Comment by juanfranblanco** [comment]
Hi,

I don't see the issue can you explain what do you mean with a sample?

Thanks

**Comment by yyd1234** [comment]
I want return array  similar
 contract：   function getUserUpgradeData(address _user) external view returns (UserUpgradeData[] memory list);
    struct UserUpgradeData {
        address id; 
        uint32 level; 
        uint blocks;
        string name; 
        string symbol;
    }
use  public TReturn DecodeDTOTypeOutput<TReturn>(TReturn functionOuput, string output)  to decrypt，，，return only one UserUpgradeData，，，we need return UserUpgradeData[] ，need you help

**Comment by juanfranblanco** [comment]
You will need to use a List<UserUpgradeData> on your return type.
Also an example on how to deal with structs is here:
http://playground.nethereum.com/csharp/id/1012
The simplest thing is to code generate it. https://docs.nethereum.com/en/latest/nethereum-codegen-vscodesolidity/

You can do some thing like this..

```csharp
public static async Task Main()
        {
         
            var privateKey = "0xx";
            var account = new Nethereum.Web3.Accounts.Account(privateKey);
            var web3 = new Web3(account, url);
 var contractHandler = web3.Eth.GetContractHandler(contractAddress);

            var getUserUpgradeDataFunction = new GetUserUpgradeDataFunction(); 
            getUserUpgradeDataFunction.User = user;
            var getUserUpgradeDataOutputDTO = await contractHandler.QueryDeserializingToObjectAsync<GetUserUpgradeDataFunction, GetUserUpgradeDataOutputDTO>(getUserUpgradeDataFunction);
            
}

 public partial class GetUserUpgradeDataFunction : GetUserUpgradeDataFunctionBase { }

    [Function("getUserUpgradeData", typeof(GetUserUpgradeDataOutputDTO))]
    public class GetUserUpgradeDataFunctionBase : FunctionMessage
    {
        [Parameter("address", "_user", 1)]
        public virtual string User { get; set; }
    }

    public partial class GetUserUpgradeDataOutputDTO : GetUserUpgradeDataOutputDTOBase { }

    [FunctionOutput]
    public class GetUserUpgradeDataOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple[]", "list", 1)]
        public virtual List<UserUpgradeData> List { get; set; }
    }

    public partial class UserUpgradeData : UserUpgradeDataBase { }

    public class UserUpgradeDataBase 
    {
        [Parameter("address", "id", 1)]
        public virtual string Id { get; set; }
        [Parameter("uint32", "level", 2)]
        public virtual uint Level { get; set; }
        [Parameter("uint256", "blocks", 3)]
        public virtual BigInteger Blocks { get; set; }
        [Parameter("string", "name", 4)]
        public virtual string Name { get; set; }
        [Parameter("string", "symbol", 5)]
        public virtual string Symbol { get; set; }
    }

```

**Comment by wangdng** [comment]
hi, I encountered the same problem, the library I used is net351, when I use var queryRequest = new QueryUnityRequest<GetUserUpgradeDataFunction, GetUserUpgradeDataOutputDTO>(EthereumGlobaleDefine.NethereumUrl, PlayerData.AccpuntAddress);
                    yield return queryRequest.Query(new GetUserUpgradeDataFunction() {User = (string)args[0] }, contract.Address);
var dtoResult = queryRequest.Result;

Unity will report an error
NullReferenceException: Object reference not set to an instance of an object
Nethereum.ABI.TupleTypeDecoder.InitDefaultDecodingComponents () (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.TupleTypeDecoder.Decode (System.Byte[] encoded, System.Type type) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.ABIType.Decode (System.Byte[] encoded, System.Type type) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.Decoders.ArrayTypeDecoder.DecodeDynamicElementType (System.Byte[] encoded, System.Type type, System.Int32 size) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.Decoders.ArrayTypeDecoder.Decode (System.Byte[] encoded, System.Type type, System.Int32 size) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.Decoders.DynamicArrayTypeDecoder.Decode (System.Byte[] encoded, System.Type type) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.ABIType.Decode (System.Byte[] encoded, System.Type type) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeOutput (System.Byte[] outputBytes, Nethereum.ABI.FunctionEncoding.ParameterOutput[] outputParameters) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeOutput (System.String output, Nethereum.ABI.FunctionEncoding.ParameterOutput[] outputParameters) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.FunctionEncoding.ParameterDecoder.DecodeAttributes[T] (System.String output, T result, System.Reflection.PropertyInfo[] properties) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.ABI.FunctionEncoding.FunctionCallDecoder.DecodeFunctionOutput[T] (T functionOutputResult, System.String output) (at <3e856d7963de4a9dba1f7ce87ad74714>:0)
Nethereum.Contracts.Extensions.FunctionOuputDTOExtensions.DecodeOutput[TFunctionOutputDTO] (TFunctionOutputDTO functionOuputDTO, System.String output) (at <cbec0717210e4d248e706ed59c2bbee6>:0)
Nethereum.JsonRpc.UnityClient.QueryUnityRequest`2+<Query>d__7[TFunctionMessage,TResponse].MoveNext () (at <749d140fca6b4ac4bd8a07d1fb7b39e0>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ec0ed1565bd04bb69ddd0785746b977d>:0)

Is it only possible to use web3? But does web3 support IL2CPP?

**Comment by wangdng** [comment]
I am using Unity to develop our project, but I want to support IL2CPP, so I used the net351 library instead of net472. The above problem is the problem I am encountering now. The data structure used is also GetUserUpgradeDataFunction and GetUserUpgradeDataOutputDTO, but Unity Will report this error
Hope you can help, thank you very much

**Comment by juanfranblanco** [comment]
472 supports IL2CPP now all dlls are not supported, you have to reduce the set to the same of 351.

Now you cannot use the async methods you need to use it as follows:
https://github.com/Nethereum/Unity3dSimpleSampleNet461/blob/master/Assets/TokenDeployAndSendCoroutinesUnityWebRequest.cs#L140-L141
Instead of using the contract handler

**Comment by wangdng** [comment]
Thank you very much for your reply. Now that means I can only use web3 to parse this GetUserUpgradeDataOutputDTO, and can't use Unity's Ctrip method anymore?

**Comment by wangdng** [comment]
Thank you very much for the reply. Now that means I can only use web3 to parse this GetUserUpgradeDataOutputDTO, and can't use Unity's coroutine method anymore?

**Comment by wangdng** [comment]
Thank you very much for the reply. Now that means I can only use web3 to parse this GetUserUpgradeDataOutputDTO, and can't use Unity's coroutine method anymore?
Unitywebrequests can't be used anymore, right?

**Comment by juanfranblanco** [comment]
No, no the opposite, I did not spot you were using a query already. Let me validate it.

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/143599826-09d51a24-01ed-4afa-b909-2b1a43dc350b.png)
```csharp

public partial class TestDeployment : TestDeploymentBase
    {
        public TestDeployment() : base(BYTECODE) { }
        public TestDeployment(string byteCode) : base(byteCode) { }
    }

    public class TestDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = "608060405234801561001057600080fd5b5061055c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063e4ca832814610030575b600080fd5b61004361003e36600461029e565b610059565b604051610050919061032a565b60405180910390f35b60408051600a808252610160820190925260609160009190816020015b6040805160a081018252600080825260208083018290529282015260608082018190526080820152825260001990920191018161007657905050905060005b600a8110156101915760008282815181106100d2576100d26103f9565b60209081029190910181015133815263ffffffff84169181019190915290506100fc826064610425565b604082015261010a82610198565b60405160200161011a9190610444565b60408051601f19818403018152919052606082015261013882610198565b6040516020016101489190610470565b604051602081830303815290604052816080018190525080838381518110610172576101726103f9565b60200260200101819052505080806101899061049e565b9150506100b5565b5092915050565b6060816101bc5750506040805180820190915260018152600360fc1b602082015290565b8160005b81156101e657806101d08161049e565b91506101df9050600a836104cf565b91506101c0565b60008167ffffffffffffffff811115610201576102016103e3565b6040519080825280601f01601f19166020018201604052801561022b576020820181803683370190505b5090505b8415610296576102406001836104e3565b915061024d600a866104fa565b61025890603061050e565b60f81b81838151811061026d5761026d6103f9565b60200101906001600160f81b031916908160001a90535061028f600a866104cf565b945061022f565b949350505050565b6000602082840312156102b057600080fd5b81356001600160a01b03811681146102c757600080fd5b9392505050565b60005b838110156102e95781810151838201526020016102d1565b838111156102f8576000848401525b50505050565b600081518084526103168160208601602086016102ce565b601f01601f19169290920160200192915050565b60006020808301818452808551808352604092508286019150828160051b87010184880160005b838110156103d557888303603f19018552815180516001600160a01b031684528781015163ffffffff1688850152868101518785015260608082015160a082870181905291906103a3838801826102fe565b92505050608080830151925085820381870152506103c181836102fe565b968901969450505090860190600101610351565b509098975050505050505050565b634e487b7160e01b600052604160045260246000fd5b634e487b7160e01b600052603260045260246000fd5b634e487b7160e01b600052601160045260246000fd5b600081600019048311821515161561043f5761043f61040f565b500290565b633ab9b2b960e11b8152600082516104638160048501602087016102ce565b9190910160040192915050565b651cde5b589bdb60d21b8152600082516104918160068501602087016102ce565b9190910160060192915050565b60006000198214156104b2576104b261040f565b5060010190565b634e487b7160e01b600052601260045260246000fd5b6000826104de576104de6104b9565b500490565b6000828210156104f5576104f561040f565b500390565b600082610509576105096104b9565b500690565b600082198211156105215761052161040f565b50019056fea2646970667358221220b58feec7463b9b01f3533a4cc15465e381aa46db7291598c2ee67aa5cd1e45fe64736f6c634300080a0033";
        public TestDeploymentBase() : base(BYTECODE) { }
        public TestDeploymentBase(string byteCode) : base(byteCode) { }

    }

    public partial class GetUserUpgradeDataFunction : GetUserUpgradeDataFunctionBase { }

    [Function("getUserUpgradeData", typeof(GetUserUpgradeDataOutputDTO))]
    public class GetUserUpgradeDataFunctionBase : FunctionMessage
    {
        [Parameter("address", "_user", 1)]
        public virtual string User { get; set; }
    }

    public partial class GetUserUpgradeDataOutputDTO : GetUserUpgradeDataOutputDTOBase { }

    [FunctionOutput]
    public class GetUserUpgradeDataOutputDTOBase : IFunctionOutputDTO
    {
        [Parameter("tuple[]", "list", 1)]
        public virtual List<UserUpgradeData> List { get; set; }
    }

    public partial class UserUpgradeData : UserUpgradeDataBase { }

    public class UserUpgradeDataBase
    {
        [Parameter("address", "id", 1)]
        public virtual string Id { get; set; }
        [Parameter("uint32", "level", 2)]
        public virtual uint Level { get; set; }
        [Parameter("uint256", "blocks", 3)]
        public virtual BigInteger Blocks { get; set; }
        [Parameter("string", "name", 4)]
        public virtual string Name { get; set; }
        [Parameter("string", "symbol", 5)]
        public virtual string Symbol { get; set; }
    }

   void Start () {

        StartCoroutine(DeployAndGetArrayStruct());
    }

    public IEnumerator DeployAndGetArrayStruct()
    {
        var url = "http://localhost:8545";
        var privateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
        var account = "0x12890d2cce102216644c59daE5baed380d84830c";
        //initialising the transaction request sender
        var transactionRequest = new TransactionSignedUnityRequest(url, privateKey, 444444444500);
        transactionRequest.UseLegacyAsDefault = true;


        var deployContract = new TestDeployment()
        {
            FromAddress = account
        };

        //deploy the contract and True indicates we want to estimate the gas
        yield return transactionRequest.SignAndSendDeploymentContractTransaction<TestDeployment>(deployContract);

        if (transactionRequest.Exception != null)
        {
            Debug.Log(transactionRequest.Exception.Message);
            yield break;
        }

        var transactionHash = transactionRequest.Result;

        Debug.Log("Deployment transaction hash:" + transactionHash);

        //create a poll to get the receipt when mined
        var transactionReceiptPolling = new TransactionReceiptPollingRequest(url);
        //checking every 2 seconds for the receipt
        yield return transactionReceiptPolling.PollForReceipt(transactionHash, 2);
        var deploymentReceipt = transactionReceiptPolling.Result;

        Debug.Log("Deployment contract address:" + deploymentReceipt.ContractAddress);

        //Query request using our acccount and the contracts address (no parameters needed and default values)
        var queryRequest = new QueryUnityRequest<GetUserUpgradeDataFunction, GetUserUpgradeDataOutputDTO>(url, account);
        yield return queryRequest.Query(new GetUserUpgradeDataFunction() { User = account }, deploymentReceipt.ContractAddress);

        var dtoResult = queryRequest.Result;
        Debug.Log(dtoResult.List[0].Name);
        Debug.Log(dtoResult.List[0].Id);

    }


```

```solidity

pragma solidity ^0.8.3;

contract HelloWorld2 {
     struct UserUpgradeData {
        address id;
        uint32 level;
        uint blocks;
        string name;
        string symbol;
    }
    
   function getUserUpgradeData(address _user) external view returns (UserUpgradeData[] memory list){
     UserUpgradeData[] memory usersData = new UserUpgradeData[](10);
      for (uint i = 0; i < 10; i++) {
          UserUpgradeData memory userData = usersData[i];
          userData.id = _user;
          userData.level = uint32(i);
          userData.blocks = i * 100;
          userData.name =  string(abi.encodePacked("user", toString(i)));
          userData.symbol = string(abi.encodePacked("symbol", toString(i)));
          usersData[i] = userData;
      }
      return usersData;
   }

    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }
}

```
