### ISSUE TITLE
Contract events stop working

### ISSUE THREAD

**Issue by paradise** [Nethereum/Nethereum#75]
I test my application on test-net. I have a contract with one event. from .net I subscribe to this event:

`contract.CreateFilterAsync()` 

and store HexValue of event into database.

Then I call
`web3.Eth.Filters.GetFilterChangesForEthNewFilter.SendRequestAsync(<stored filter>)`

and it works good for some time, but over some time it stops receiving events at all. So I need to recreate event HexValue.

It is written that events are permanent, but why I lose my events? Maybe test-net have some problems?

**Comment by juanfranblanco** [comment]
That will be an issue with the client itself, if you are polling periodically you can store the blockNumbers and create a specific filter for the block number range you are interested.

**Comment by paradise** [comment]
I use geth, so it is an issue of geth client ? Where I can see how to get blockNumbers and create a specific filter for the block number range?

**Comment by juanfranblanco** [comment]
You can use https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3/Contracts/Event.cs#L72-L79

plus this 
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Web3/Contracts/Event.cs#L149-L153

**Comment by paradise** [comment]
I installed latest version from Nuget, but I don't have these methods available.

**Comment by juanfranblanco** [comment]
Ah! I am making a release today, give it a couple of hours.

**Comment by paradise** [comment]
If i'll specify fromBlock = 10 and toBlock = 20, are events from 10 and 20 blocks also inclujded ?

**Comment by juanfranblanco** [comment]
I cannot remember :)

**Comment by juanfranblanco** [comment]
I have not released yet as I was releasing the vscode extension, ill see if I have time today

**Comment by paradise** [comment]
Also, `Event.DecodeAllEvents<T>` throws error if `logs` parameter is null.

**Comment by juanfranblanco** [comment]
Yes you need something to decode

**Comment by juanfranblanco** [comment]
On the block number range that is a geth / client stuff. Just run a unit test

**Comment by juanfranblanco** [comment]
Submitted rc6

**Comment by paradise** [comment]
Issue is that sometimes when I call `Event.GetFilterChanges<T>()` ethGetFilterChanges returns NULL, and then `Event.DecodeAllEvents<T>(logs)` (internal call) throws an exception, because it try to enumerate NULL.

**Comment by juanfranblanco** [comment]
ahhh got you.. I thought you were doing a direct call

**Comment by juanfranblanco** [comment]
Thanks pushed the changes for that. Planning to release 1.0 soon, if you can wait for the nuget package.
