### ISSUE TITLE
eth_sign expects a hex encoded string as the data message

### ISSUE THREAD

**Issue by jyap808** [Nethereum/Nethereum#753]
Running the test case will fail.

Against a Hardhat node:
```
Errors encountered in param 1: Invalid value "Hello world" supplied to : DATA
```

Against a Geth node:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes"}}
```

**Comment by juanfranblanco** [comment]
eth_sign expects a hex string check the Eth rpc api, https://eth.wiki/json-rpc/API. so if you want to sign a simple string this needs to be converted to hex, this will be normally done using UTF8 encoder GetBytes().ToHex()

**Comment by juanfranblanco** [comment]
To be clear, people may want to sign other other types of byte arrays in hex, not just simple strings.
