### ISSUE TITLE
Can not get event with array parameter

### ISSUE THREAD

**Issue by elemongame** [Nethereum/Nethereum#759]
I have an event like that in my contract:
![image](https://user-images.githubusercontent.com/89892935/146354543-6b0970d0-8c01-4fb5-8c31-05817030f7b6.png)

And in my C# code, this is the way I get the event logs:
My event model:
![image](https://user-images.githubusercontent.com/89892935/146354962-53596d51-364f-4948-9505-f3c4493e8c8d.png)

My code to get event:
![image](https://user-images.githubusercontent.com/89892935/146355292-700d85b0-7b0c-48c8-a953-0c0849d6d09c.png)

However, I can not get the event logs.
Other event logs in my contract can be retrieved properly.

**Comment by juanfranblanco** [comment]
You need a List not and IList. If you use the code generator it will set all the right mappings for you.

**Comment by elemongame** [comment]
Tried with List, however, it is still not working

**Comment by juanfranblanco** [comment]
Submit a transaction and try decoding it from the receipt, if the log is raised it will be found.

**Comment by juanfranblanco** [comment]
Extra info on supported type for array, mainly an implementation of IList<T> https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/Decoders/ArrayTypeDecoder.cs#L53

**Comment by elemongame** [comment]
No exception thrown.
Here is full of my code.
Solidity event code:
![image](https://user-images.githubusercontent.com/89892935/146358177-5c1cdb4e-6e36-4a89-ac4e-6ab8d1713d71.png)

Event model:
![image](https://user-images.githubusercontent.com/89892935/146358264-d9c08164-3bd2-4af2-80b3-a11963649fa5.png)

Code to get the event:
![image](https://user-images.githubusercontent.com/89892935/146358346-b6500bd7-a1cf-4de3-979a-76b0e3a53cfd.png)

**Comment by elemongame** [comment]
Sorry, my bad.
Wrong at abi file path
