### ISSUE TITLE
Support .net core for IPCClient

### ISSUE THREAD

**Issue by forik** [Nethereum/Nethereum#76]
Could you please add support of .net core to ipc client. As for now it supports only full framework >= net451?

Thanks

**Comment by juanfranblanco** [comment]
The reason for this is that there is not an implementation of pipes in .net core to support multiple OS see https://github.com/Nethereum/Nethereum/issues/55

**Comment by djsowa** [comment]
I used mono implementation of UnixEndPoint and I implemented IPC client for Unix Domain Sockets to be used within Nethereum.
Here is my implementation
