### ISSUE TITLE
Nethereum.ABI.Util.IsNumber does not recognise the System.Numerics.BigInteger type as a number

### ISSUE THREAD

**Issue by AlLansley** [Nethereum/Nethereum#762]
## Expected Behavior

Calling `IsNumber` on a BigInteger should return true, with the knock-on effect that the `ConvertValuesToDefaultABIValues` method is able to deal with data of the BigInteger type.

## Current Behavior

Calling `IsNumber` on a BigInteger returns false, with the knock-on effect that the `ConvertValuesToDefaultABIValues` method is unable to successfully process BigInteger data. Should a single BigInteger value be passed into the aforementioned method then an empty list is returned.

## Possible Solution

You can call `ToByteArray()` when providing a BigInteger to `GetSha3ABIEncodedPacked`, but then if you're trying to construct a new BigInteger from the returned byte array you have to do it like this (2nd line is the key):

```
var sha3EncodedPacked = AbiEncode.GetSha3ABIEncodedPacked(someBigInteger.ToByteArray());
var foo = new BigInteger(sha3EncodedPacked.Concat(new byte[] { 0 }).ToArray() as byte[]); // This works but I cannot guarantee is correct
var thisFails = new BigInteger(sha3EncodedPacked); // Nope!
```

If you don't do that second line and try a straight conversion into BigInteger from the byteArray in the first line it fails.

## Steps to Reproduce

```
var someBigInt = new BigInteger(123);
var msg = someBigInt.IsNumber() ? "BigInteger is a number!" : "BigInteger is NOT a number!";
Debug.Log(msg); // NOT a number
var listOfAbiValues = ConvertValuesToDefaultABIValues(someBigInt);
Assert.AreEqual(1, listOfAbiValues.Count); // Will be zero, i.e. an empty list
```

## Context (Environment)

Windows 10, latest Nethereum as of Dec 22nd 2021.
Attempting to call `ABIEncode.GetSha3ABIEncodedPacked` on a BigInteger value - which can be used as an equivalent for Solidity's `uint256` data type.

**Comment by AlLansley** [comment]
Actually, it looks like the `Concat(new byte[] { 0 }).ToArray()` reconstruction does work as the following is successful:

```
var abiEncode = new ABIEncode();
BigInteger someBigInt = new BigInteger(123);
var bigIntBytes = abiEncode.GetABIEncodedPacked(someBigInt.ToByteArray());
var reconstructedBigInt = new BigInteger(bigIntBytes.Concat(new byte[] { 0 }).ToArray());
Assert.AreEqual(someBigInt, reconstructedBigInt); // Yup - true!
```

**Comment by juanfranblanco** [comment]
Yes  BigInteger, simple encoding of default values was not added as it was assumed smaller values for abi encoding, you can use for the time being something like new AbiValue("int256", yourBigInteger) for encoding which is used for all types. Ill add that now.

**Comment by juanfranblanco** [comment]
Note you will have the same issue with addresses, hence the prefer option is to use the AbiValue route, hopefully it makes sense.

**Comment by juanfranblanco** [comment]
Check this sample http://playground.nethereum.com/csharp/id/1016

**Comment by AlLansley** [comment]
> Yes BigInteger, simple encoding of default values was not added as it was assumed smaller values for abi encoding, you can use for the time being something like new AbiValue("int256", yourBigInteger) for encoding which is used for all types. Ill add that now.

Thanks for your feedback, makes sense now and the `new AbiValue` way will definitely also work.

From your above response ("_I'll add that now_"), did you mean add BigInteger recognition? I had a look at the recent commit history and didn't see it (not rushing anyone, just making sure I'm on the same page in that your plan is to add it - either that or I've misunderstood you! =D)
