### ISSUE TITLE
Nethereum.ABI.FunctionEncoding.AbiEncodingException occurs when transfering token

### ISSUE THREAD

**Issue by vlbhtcno1** [Nethereum/Nethereum#763]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

## Expected Behavior
Can transfering

## Current Behavior

Nethereum.ABI.FunctionEncoding.AbiEncodingException occurs
## Steps to Reproduce

1. My Implementation

            string contractAddress = "0xe9e7cea3dedca5984780bafc599bd69add087d56";
            var transferHandler = _web3.Eth.GetContractTransactionHandler<TransferFunction>();
            var transfer = new TransferFunction()
            {
                FromAddress = _owner.Address,
                To = recipient,              
                AmountToSend = amount,               
            };
            transfer.Gas = Web3.Convert.ToWei(5, UnitConversion.EthUnit.Gwei);
            var signed = await transferHandler.SignTransactionAsync(contractAddress, transfer);
            var transaction = await transferHandler.SendRequestAndWaitForReceiptAsync(signed);
            var receiptHash = transaction.TransactionHash;
1.
1.
1.

## Context (Environment)

I can't transfer the token

I'm using .NET 5 

I wanna send the token to another address but get an error when doing it.
## Detailed Description

Nethereum.ABI.FunctionEncoding.AbiEncodingException: 'An error occurred encoding abi value. Order: '1', Type: 'address', Value: 'null'.  Ensure the value is valid for the abi type.'

**Comment by juanfranblanco** [comment]
This is not a "bug" you are entering AmountToSend as the Value to send, AmountToSend is the Ether (wei) amount. 
This introduction to smart contracts will help http://playground.nethereum.com/csharp/id/1007

**Comment by vlbhtcno1** [comment]
> This is not a "bug" you are entering AmountToSend as the Value to send, AmountToSend is the Ether (wei) amount. This introduction to smart contracts will help http://playground.nethereum.com/csharp/id/1007
> 
> Also specific to your error, is your recepient (TO) address null?

- recipient is the address I passed to the method. 
- I can't find property TokenAmount in the current Nethereum version (4.1.1). So, I use AmountToSend instead

**Comment by juanfranblanco** [comment]
Just use this property, also please check the above introduction it goes into detail on all the steps.
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.StandardTokenEIP20/ContractDefinition/StandardTokenDefinition.cs#L160

**Comment by vlbhtcno1** [comment]
> Just use this property, also please check the above introduction it goes into detail on all the steps. https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.StandardTokenEIP20/ContractDefinition/StandardTokenDefinition.cs#L160

What version do you use at http://playground.nethereum.com/csharp/id/1007 ?

BTW, I updated my code but got the same error message.

            var recipient = "0xc84b0a4654a4450ba8f13bd79b8729ee61f22ebc";
            string contractAddress = "0xe9e7cea3dedca5984780bafc599bd69add087d56";

            var transferHandler = _web3.Eth.GetContractTransactionHandler<TransferFunction>();

            var transfer = new TransferFunction()
            {
                FromAddress = _owner.Address,
                To = recipient,
                Value = Web3.Convert.ToWei(2, UnitConversion.EthUnit.Ether),
            };

            transfer.Gas = Web3.Convert.ToWei(5, UnitConversion.EthUnit.Gwei);
            
            var signed = await transferHandler.SignTransactionAsync(contractAddress, transfer);
            var transaction = await transferHandler.SendRequestAndWaitForReceiptAsync(signed);

            var receiptHash = transaction.TransactionHash;

**Comment by juanfranblanco** [comment]
if you are connecting to anything else but Ethereum you need to set your web3.Eth.TransactionManager.UseLegacy option to true

**Comment by juanfranblanco** [comment]
Also the Gas is the amount of Gas you are going to use and that is estimated for you, that is not the GasPrice

**Comment by vlbhtcno1** [comment]
> 

I can transfer. Thank you

**Comment by vlbhtcno1** [comment]
> Also the Gas is the amount of Gas you are going to use and that is estimated for you, that is not the GasPrice

Sir, I have a question. How to check transaction is failed or success

**Comment by juanfranblanco** [comment]
@gabrielsaru28  you have asked this in discord, this is for issues only not questions.

**Comment by gabrielsaru28** [comment]
sorry !
