### ISSUE TITLE
How to  set  msg.value variable in Nethereum

### ISSUE THREAD

**Issue by payplati23** [Nethereum/Nethereum#764]
Hello, I am newbie to Nethereum.
I did write this code on ether library.
transaction = await contract.createMarketItem(nftaddress, tokenId, price, { value: listingPrice })
so I passed msg.value like that.
But I tried to pass msg.value on Nethereum.
I have no idea now.
Please help
What should I do?

**Comment by juanfranblanco** [comment]
@payplati23 in a FunctionMessage like TransferFunction for Erc20. Just set the AmountToSend
Check the http://playground.nethereum.com get started with smart contracts.
