### ISSUE TITLE
Unable to build full solution (net35 and netstandard2.0 deps)

### ISSUE THREAD

**Issue by mrwillis** [Nethereum/Nethereum#768]
Bit of a C# noob. Trying to get the project to build but seems like I am missing assemblies for net35 and netstandard2.0 across the board. Any guide on getting the full solution to build (windows 10, Visual studio 2022)?

![image](https://user-images.githubusercontent.com/2652683/147799410-ff1f76d0-9551-40a0-ab60-6c89e0e7f633.png)

**Comment by juanfranblanco** [comment]
Hi @mrwillis you should not have any issues, have you installed .net 35?

**Comment by juanfranblanco** [comment]
For everyone's reference as Nethereum targets so many old versions of the .Net, you will need to install where possible .net35, .net451, .net461, .net472, .net5, .net6, netcore2.1, netcore3.0, netstandard1.1, netstandard2.0.
