### ISSUE TITLE
Cant transfer ERC271

### ISSUE THREAD

**Issue by sashap88** [Nethereum/Nethereum#769]
Managed toi transfer ERC20
 var tokenServiceERC20 = new Nethereum.StandardTokenEIP20.StandardTokenService(web3, contractAddress);
                    var ownerBalanceTask = tokenServiceERC20.BalanceOfQueryAsync(coinOwnerAddress);

                    var tokenserviceERC721 = new Nethereum.StandardNonFungibleTokenERC721.ERC721Service(web3, contractAddress);
                    var ownerBalanceTaskerc721 = tokenserviceERC721.BalanceOfQueryAsync(coinOwnerAddress);
                    var ownerBalanceERC721 = ownerBalanceTaskerc721.Result;

var transfer = new TransferFunction()
                     {
                         To = toAddress,
                         AmountToSend = 0,
                         Nonce = new BigInteger(txCount),
                         FromAddress = coinOwnerAddress,
                         Value= ownerBalance
                 };

  var signedMessage = await web3.Eth.GetContractHandler(contractAddress)
                       .SignTransactionAsync(transfer);

                     var r = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + signedMessage).ConfigureAwait(false);

While bakance is recognized good if i sen ERC721 contract address(1 NFT), cant transfer, because there is tx exception(truing to transfer this token as erc 20 but no 271)
Chain:137 matic, Legacy=true

**Comment by juanfranblanco** [comment]
@sashap88  you cannot transfer this way you need to use TransferFrom with the TokenId. 

 public partial class TransferFromFunction : TransferFromFunctionBase { }

    [Function("transferFrom")]
    public class TransferFromFunctionBase : FunctionMessage
    {
        [Parameter("address", "from", 1)]
        public virtual string From { get; set; }
        [Parameter("address", "to", 2)]
        public virtual string To { get; set; }
        [Parameter("uint256", "tokenId", 3)]
        public virtual BigInteger TokenId { get; set; }
    }

**Comment by sashap88** [comment]
Managed to do it some time ago with the discord info that i read.
But other issue taking place. (Polygon). I receiv tx hash. it is appers at explorer for a minute and then it doesnt confirm and disappear

                    var account = new Account(privateKey, 137);
                    var web3 = new Web3(account, url);
                    web3.TransactionManager.UseLegacyAsDefault = true;


                    var txCount = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(coinOwnerAddress);

                    var t = new TransferFromFunctionBase()

                    {
                        From = coinOwnerAddress,
                        To = toAddress,
                        Nonce = new BigInteger(txCount),
                        TokenId = 55635,
                    };
                    /*
                    t.Gas = new HexBigInteger(130000);

                    t.GasPrice = new HexBigInteger(30000);
                    */
                    var signedMessage = await web3.Eth.GetContractHandler(erc721TokenContractAddress).SignTransactionAsync(t);

                    var r = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + signedMessage).ConfigureAwait(false);

                    Console.WriteLine("Transaction hash: " + r);

**Comment by sashap88** [comment]
Gas issue. Now see that simple transfer doenst work cuz executes meta tx.
https://polygonscan.com/tx/0x5d06dcc9ec012ecedb344375faac6111a1b2e6d0f5c253b41998cdb6bea37c6f

how to handle it?

**Comment by sashap88** [comment]
Again sorry!handle it everything is ok for now. Last issue how to get TokenID. Mnaged to get it from 
 var transferEventHandler = web3.Eth.GetEvent<TransferEventDTO>();
                       // Just examine a few blocks by specifying start and end blocks
                       var filter = transferEventHandler.CreateFilterInput(address,
                                    fromBlock: new BlockParameter(22595661),
                           toBlock: new BlockParameter(23298264)
                                   );
                       var logs = await transferEventHandler.GetAllChangesAsync(filter);

but then i need to look a lor of blocked and it is not the best sollution
