### ISSUE TITLE
Code generator doesn't account for C# keywords used as Solidity parameter names

### ISSUE THREAD

**Issue by NeoXtreem** [Nethereum/Nethereum#772]
## Expected Behavior
The generated parameter names should not conflict with C# keywords.

## Current Behavior
The generated parameter names conflict with C# keywords.

## Possible Solution
Make the generated parameter name unique by adding an underscore or something.

## Steps to Reproduce
The following simple contract causes this issue:
```
contract Foo {
    function Bar(uint256 operator) public { }
}
```

**Comment by juanfranblanco** [comment]
Which code generator are you using?

**Comment by NeoXtreem** [comment]
> Which code generator are you using?

Nethereum.Autogen.ContractApi Version 3.6.2

**Comment by juanfranblanco** [comment]
Ah that is not released the update, you will need to use the embedded vscode solidity for now unti release.

**Comment by juanfranblanco** [comment]
It will be hopefully released this week, anyway.

**Comment by NeoXtreem** [comment]
I'm not sure if you understood the issue I'm having. I'm able to use Nethereum.Autogen.ContractApi as it's available on NuGet. But the problem I'm having is that the generated parameter names conflict with C# keywords.

For example, The following simple contract causes this issue:

```
contract Foo {
    function Bar(uint256 operator) public { }
}
```

**Comment by juanfranblanco** [comment]
Yes this class is used to prevent this https://github.com/Nethereum/Nethereum/blob/master/generators/Nethereum.Generators/Core/CommonGenerators.cs

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NeoXtreem** [comment]
Ah, sorry - I thought you meant Nethereum.Autogen.ContractApi is not released. I didn't realise you were referring to a fix for this issue. Anyway, just updated to latest, and it resolves the issue. Thanks!
