### ISSUE TITLE
Multiple accounts for a web3 instance

### ISSUE THREAD

**Issue by truongbnu** [Nethereum/Nethereum#773]
Does NEthereum support multiple accounts from multiple private keys for a web3 instance.
```
var account = new Account(privateKey);
var web3 = new Web3(account, rpcUrl);
```
I see the only way to make a web3 instance with one private key

**Comment by juanfranblanco** [comment]
No it doesn't, everything is linked to an account. Creating a Web3 instance is not expensive anyway.
