### ISSUE TITLE
Why watcher.GetMessageHashes returns count = 0

### ISSUE THREAD

**Issue by kevinlai219** [Nethereum/Nethereum#780]
Hello?
I tried to the Nethereum Tutorial at https://github.com/Nethereum/OptimismTemplate
And when I run test code for Optimism(here: https://github.com/Nethereum/OptimismTemplate/blob/main/OptimismTemplate/OptimismTemplate.Testing/ERC20_L1_to_L2_Deposit_and_Withdraw.cs), 

var messageHashes = watcher.GetMessageHashes(receiptDeposit);

watcher.GetMessageHashes(receiptDeposit) returns count = 0
So I can't go ahead anymore.

I used l1 & l2 as following 
var web3l1 = new Web3(new Account("my private key", 42), "https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161");
var web3l2 = new Web3(new Account("my private key", 69), "https://kovan.optimism.io");

![image](https://user-images.githubusercontent.com/93578592/153107247-69eaef57-5c77-454e-b21a-501ae8ebe306.png)

Anybody can solve this issue?

**Comment by juanfranblanco** [comment]
The optimism smart contracts need to be updated, so that might be your issue. The template does not have the latest smart contracts, and the ovm does not require a different compiler anymore.

**Comment by juanfranblanco** [comment]
Please raise the issue in the Optimism project for tracking thanks.
