### ISSUE TITLE
Can't not send message from Layer 1 to Layer2

### ISSUE THREAD

**Issue by kevinlai219** [Nethereum/Nethereum#782]
ERC20_L1_to_L2_Deposit_and_Withdraw.cs

When I tried to test ERC20_L1_to_L2_Deposit_and_Withdraw.cs, I found that L2DepositedRC20Deployment didn't work right way.
Actually, L2DepositedERC20.sol contracts is inherited ERC20.sol and when the initialSupply is initialize 0 in L2DepositedERC20.
However, after running the deployment code, and get the deployed smart contracts address, the import token with that address.
It is not 0, but random number I think.
![image](https://user-images.githubusercontent.com/93578592/153123904-2905a5e8-ca23-47a8-9cea-ea60cc05dcd9.png)

Is there any problem?
In this test, I used 

L1 as https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
L2 as https://kovan.optimism.io

Another weird thing is receipt .DecodeAllEvents can't catch any event so that count = 0.

So I think these factors occur this exception.
![image](https://user-images.githubusercontent.com/93578592/153124568-8d1d63b4-7175-40bd-904c-490ac6d15065.png)

**Comment by juanfranblanco** [comment]
Hi this is not a problem with this Repo, this is a problem with the Optimism template, the optimism smart contracts need to be updated there, and sample updated, so that will be your issue.
