### ISSUE TITLE
Newtonsoft Json 2 Versions

### ISSUE THREAD

**Issue by DavidCow** [Nethereum/Nethereum#784]
Hi there,

i'm getting this error which i'm not able to resolve. 
![err](https://user-images.githubusercontent.com/15343431/153418654-0560afbd-0243-45f9-966f-7c3388a9377b.png)

i already developed stuff with the new Newtonsoft version 2.0.0. But nethereum needs some version below. 

Any hints?
Thanks!

**Comment by juanfranblanco** [comment]
@DavidCow dont include the Nethereum included one as it is not required, it is the same same that unity provides.
