### ISSUE TITLE
ContractABI Deserialization is not working

### ISSUE THREAD

**Issue by foued1979** [Nethereum/Nethereum#785]
When serializing a contract Abi, built with ABI.Model.ContractABI class, to build a Contracts.Contract, Nethereum throws a deserialization error, stating that the deserialization cannot deserialize the Abi string into a List<Dictionary<string, object[]>>, whether we use System.Text.Json or NewtonSoft.Json.

## Expected Behavior
The deserialization should be able to identify fields of ContractABI and cast functions or events to its respective functionABI or EventABI.

## Current Behavior
Deserialization is looking for list of dictionaries

**Comment by foued1979** [comment]
The contract Abi serialized using NewtonSoft:

`{"Functions":[{"Serpent":false,"Constant":true,"Name":"getReserves","InputParameters":[],"OutputParameters":[{"Name":"_reserve0","Type":"uint112","ABIType":{"CanonicalName":"uint112","Name":"uint112","FixedSize":32},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"_reserve1","Type":"uint112","ABIType":{"CanonicalName":"uint112","Name":"uint112","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"_blockTimestampLast","Type":"uint32","ABIType":{"CanonicalName":"uint32","Name":"uint32","FixedSize":32},"Order":3,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"0902f1ac"},{"Serpent":false,"Constant":true,"Name":"initialize","InputParameters":[{"Name":"_token0","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"_token1","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"OutputParameters":null,"Sha3Signature":"4cd88b76"},{"Serpent":false,"Constant":false,"Name":"mint","InputParameters":[{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"OutputParameters":[{"Name":"liquidity","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"d85d3d27"},{"Serpent":false,"Constant":false,"Name":"burn","InputParameters":[{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"OutputParameters":[{"Name":"amount0","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount1","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"dafa1d2d"},{"Serpent":false,"Constant":false,"Name":"swap","InputParameters":[{"Name":"amount0Out","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount1Out","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":3,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"data","Type":"bytes","ABIType":{"FixedSize":-1,"Name":"bytes","CanonicalName":"bytes"},"Order":4,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"OutputParameters":null,"Sha3Signature":"da2e3aa3"},{"Serpent":false,"Constant":true,"Name":"skim","InputParameters":[{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"OutputParameters":null,"Sha3Signature":"4a7dd3f0"},{"Serpent":false,"Constant":true,"Name":"sync","InputParameters":[],"OutputParameters":null,"Sha3Signature":"fff6cae9"}],"Constructor":null,"Events":[{"Name":"Mint","IsAnonymous":false,"InputParameters":[{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount0","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount1","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":3,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"2693e100245ac125419beb53c7febc035b80ce3158d58d6720c91ff205b4ea61","NumberOfIndexes":0},{"Name":"Burn","IsAnonymous":false,"InputParameters":[{"Name":"sender","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount0","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount1","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":3,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":4,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"b7dac41111e267f3553ad1aaa616b3833590f7b4acc74a1627a2a8575f6f94d8","NumberOfIndexes":0},{"Name":"Swap","IsAnonymous":false,"InputParameters":[{"Name":"sender","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount0In","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount1In","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":3,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount0Out","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":4,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"amount1Out","Type":"uint","ABIType":{"CanonicalName":"uint256","Name":"uint","FixedSize":32},"Order":5,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"to","Type":"string","ABIType":{"FixedSize":-1,"Name":"string","CanonicalName":"string"},"Order":6,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"4c9b5df2a05a6da34de1ec2bf6bd14c5d554a88b5cb67759b238ac883c1617ed","NumberOfIndexes":0},{"Name":"Sync","IsAnonymous":false,"InputParameters":[{"Name":"reserve0","Type":"uint112","ABIType":{"CanonicalName":"uint112","Name":"uint112","FixedSize":32},"Order":1,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null},{"Name":"reserve1","Type":"uint112","ABIType":{"CanonicalName":"uint112","Name":"uint112","FixedSize":32},"Order":2,"InternalType":null,"DecodedType":null,"Indexed":false,"SerpentSignature":null}],"Sha3Signature":"1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1","NumberOfIndexes":0}],"Errors":null}`

**Comment by juanfranblanco** [comment]
This is the .net serialized abi. Can you post your code?
