### ISSUE TITLE
Passing an array doesn't work

### ISSUE THREAD

**Issue by bellaj** [Nethereum/Nethereum#786]
I have a solidity function that accepts a string array  as follows :

`function sampleFct(address userAddress, string[] values)`

However when this function is called using 
```
string[] stringArray = new string[1]{"test"};
var transactionHash = sampleFct.SendTransactionAsync(senderAddress, userAddress ,stringArray  ).GetAwaiter().GetResult();
```
the hash is returned but the transaction fails **when the array is passed as an argument**
although the transaction is successful from other source like Remix or web3J

NB: other functions are called correctly thus the gas settings are correct

The used ABI : `'inputs': [ { 'name': 'userAddress', 'type': 'address' }, { 'name': 'values', 'type': 'string[]' } ]`

**Comment by juanfranblanco** [comment]
Try passing as a parameter a List string

**Comment by bellaj** [comment]
@juanfranblanco 
The same goes for lists

```
List<string> testList = new List<string>(){"test1","test2"};
var transactionHash = sampleFct.SendTransactionAsync(senderAddress, userAddress ,testList  ).GetAwaiter().GetResult();
```

**Comment by bellaj** [comment]
The encoded inputs are different from those generated by Remix

Error (generated by Nethereum)

```
0x7aa6c3cf0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000d6b9410d412f862b1c6e5d8660c1fb5fe2bbea8200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000036f726700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001

00000000000000000000000000000000000000000000000000000000000000047465737400000000000000000000000000000000000000000000000000000000 => array
```

Correct
```
0x7aa6c3cf0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000d6b9410d412f862b1c6e5d8660c1fb5fe2bbea8200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000036f726700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001

000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000047465737400000000000000000000000000000000000000000000000000000000 => array
```

**Comment by juanfranblanco** [comment]
Can you give me the correct abi? to validate those?
Or just use something like this, so overloads don't get confused
```csharp
using System;
using System.Numerics;
using System.Threading.Tasks;
using Nethereum.Web3;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.Contracts;
using System.Collections.Generic;
using Nethereum.Hex.HexConvertors.Extensions;


public class Program
{
    // The balance function message definition    
    [Function("sampleFct")]
    public class SampleFunction : FunctionMessage
    {
        [Parameter("address", "userAddress", 1)] public string UserAddress { get; set; }
        [Parameter("string[]", "values", 1)] public List<string> Values { get; set; }

    }

	

    //async Task Main to enable async methods

    private static async Task Main(string[] args)
    {
      var sampleFunction = new SampleFunction();
			sampleFunction.UserAddress = "d6b9410d412f862b1c6e5d8660c1fb5fe2bbea82";
			sampleFunction.Values = new List<string>(){"test1","test2"};
			Console.WriteLine(sampleFunction.GetCallData().ToHex());
    }
}
```

**Comment by juanfranblanco** [comment]
The results are the same: 

cd379b3a000000000000000000000000d6b9410d412f862b1c6e5d8660c1fb5fe2bbea8200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000005746573743100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000057465737432000000000000000000000000000000000000000000000000000000

![image](https://user-images.githubusercontent.com/562371/154259239-4614a9c9-87b8-4617-a18c-81aea24914f1.png)

**Comment by bellaj** [comment]
I've updated Nethereum from 3.2.0 to 4.1 and I am fixing some exceptions then I will try your proposition.
Meanwhile, is there any updated documentation about how to use  `SendTransactionAsync` in order to execute smart contract functions?
