### ISSUE TITLE
.Net Standard 2.1 Crash 

### ISSUE THREAD

**Issue by liuzhenLz** [Nethereum/Nethereum#789]
var hdWallet = new Nethereum.HdWallet.Wallet(mnemonics, "", path: "m/44'/60'/0'/0");
.Net Standard 2.1 Crashed

**Comment by juanfranblanco** [comment]
What version of Nbitcoin are you using?

**Comment by liuzhenLz** [comment]
<img width="1374" alt="截屏2022-03-17 下午5 52 49" src="https://user-images.githubusercontent.com/19431635/158783588-b1aec382-ba78-4888-b30f-eb13150ef15f.png">

**Comment by liuzhenLz** [comment]
Nbitcoin version is V7.0.6，and I Can not using the V5.05x.

**Comment by liuzhenLz** [comment]
<img width="445" alt="截屏2022-03-17 下午6 08 39" src="https://user-images.githubusercontent.com/19431635/158786460-38f6cf40-999b-4671-abd9-11a5a0821b90.png">
NBitcoin.BitcoinSerializableExtensions:ToBytes Error~

**Comment by liuzhenLz** [comment]
I can't control it to be the old version. When I download it, it becomes the latest version

**Comment by liuzhenLz** [comment]
What can I do to keep the version as V5.0.54?

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/158790474-81393642-56f9-4917-bdd3-04a5e5e672ca.png)

**Comment by liuzhenLz** [comment]
Still can't keep in the old version

**Comment by liuzhenLz** [comment]
It's better to support the later version. It's a little unfriendly and too old. When I use other wallet libraries, the versions conflict with each other

**Comment by juanfranblanco** [comment]
[TestHdWallet.zip](https://github.com/Nethereum/Nethereum/files/8284177/TestHdWallet.zip)

**Comment by juanfranblanco** [comment]
Working here.. moving to another version needs to be fully tested etc, so it takes time.

**Comment by liuzhenLz** [comment]
Thank you.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/issues/791
