### ISSUE TITLE
eth_getFilterChanges missing property

### ISSUE THREAD

**Issue by paradise** [Nethereum/Nethereum#79]
According to https://github.com/ethereum/wiki/wiki/JSON-RPC, `eth_getFilterChanges` method should return array of objects - logs, and log entry should have `removed` property, which is missing in Nethereum.RPC.Eth.Filters.FilterLog

> For filters created with eth_newFilter logs are objects with following params:
removed: TAG - true when the log was removed, due to a chain reorganization. false if its a valid log.

**Comment by juanfranblanco** [comment]
Thanks for reporting the addition.
