### ISSUE TITLE
SendRequestAndWaitForReceiptAsync keeps awaiting for receipt if client is out of gas

### ISSUE THREAD

**Issue by appartiff** [Nethereum/Nethereum#794]
eth_getTransactionReceipt  method call  got called around 68000 times in matter of  awaiting an up to an hour for
GetContractTransactionHandler.SendRequestAndWaitForReceiptAsync
to complete.
this happens when out of gas, then the whole thing hangs up and it takes unspecified amount of time to throw the out of gas error

![Screenshot 2022-03-28 173625](https://user-images.githubusercontent.com/16729165/160451140-e5e87aee-4fc2-41ff-9163-f1433ba0d9e3.png)

**Comment by juanfranblanco** [comment]
When calling SendRequestAndWaitForReceiptAsync this is making a poll request every 100 milliseconds. When working with mainnet the best option if you don't expect to be mined within the next block is to use SendRequest.

**Comment by appartiff** [comment]
Thanks for explaination!
