### ISSUE TITLE
JS ABI to C# class generator

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#8]
I am just playing around with loading in my own contract into Nethereum, was just thinking it would be nice to be able to convert a JS ABI into a C# class object so I could call contract methods using c# intellisense and type checking etc.

Just a thought.. :)

**Comment by juanfranblanco** [comment]
Yes is in the plan... check the readme, right at the bottom

**Comment by juanfranblanco** [comment]
Note priorities on the plan can change :)

**Comment by slothbag** [comment]
Sorry, didn't see it on the plan.  Keep up the good work :)
