### ISSUE TITLE
RpcResponseException: the method eth_newFilter does not exist/is not available: eth_newFilter

### ISSUE THREAD

**Issue by tungvl99ql** [Nethereum/Nethereum#804]
I use filter to get transaction history of cont address and get error "method eth_newFilter does not exist"
Also is there a way to get a list of contract transaction history txnHash by address?
![image](https://user-images.githubusercontent.com/24567757/162032145-4da9afa3-8ef5-4ddf-bacb-751891fc25bd.png)

![image](https://user-images.githubusercontent.com/24567757/162032205-2c0be7b5-1731-4138-9106-d433d96e34a0.png)

**Comment by juanfranblanco** [comment]
Some public nodes don't support that use get logs instead. Other question, you need to crawl the chain.
