### ISSUE TITLE
Key creation as on keythereum

### ISSUE THREAD

**Issue by soycabanillas** [Nethereum/Nethereum#83]
One scenario that would be useful could be the creation of private keys from Nethereum, as on https://github.com/ethereumjs/keythereum.
As I'm not proficient with cryptography, I don't dare to implement it by myself, but I could do it with a bit of a guide or I could help any other way (testing maybe).

**Comment by juanfranblanco** [comment]
Very good point, it would very helpful. I will put it on the TODO list.

**Comment by juanfranblanco** [comment]
The new keystore library can be found here https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.KeyStore

**Comment by juanfranblanco** [comment]
Simplest entry point is here https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.KeyStore/KeyStoreService.cs the library does not handle the file saving / reading as can be used on many environments

**Comment by juanfranblanco** [comment]
This is a quick sample 
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.KeyStore.Console.Sample/Program.cs
