### ISSUE TITLE
Websocket subscription for new block headers stuck at block numbers of multiples of 200

### ISSUE THREAD

**Issue by luismcv** [Nethereum/Nethereum#834]
This issue has me quite puzzled. The following simple piece of code gets stuck exactly at block numbers multiple of 200 when running against BSC nodes:

```
using Nethereum.JsonRpc.WebSocketStreamingClient;
using Nethereum.RPC.Reactive.Eth.Subscriptions;
using System.Reactive.Linq;

public class Program
{
    public static async Task Main(string[] args)
    {
        using (var client = new StreamingWebSocketClient("wss://bsc-ws-node.nariox.org:443"))
        {
            var subscription = new EthNewBlockHeadersObservableSubscription(client);
            subscription.GetSubscriptionDataResponsesAsObservable().Subscribe(block => { Console.WriteLine($"{DateTime.Now} > {block.Number.Value} "); });
            await client.StartAsync();
            await subscription.SubscribeAsync();
            Console.ReadKey();
        }
    }
}
```
```
15/05/2022 12:02:55 > 17821798 
15/05/2022 12:02:57 > 17821799 
15/05/2022 12:03:00 > 17821800 
```
and it stays there. I don't get any timeouts or any kind of errors.

The similar Javascript web3 code doesn't show this problem:
```
let Web3 = require('web3')

const web3 = new Web3(new Web3.providers.WebsocketProvider('wss://bsc-ws-node.nariox.org:443'))

web3.eth.subscribe('newBlockHeaders', function (error, result) {    
    if (!error) {
        console.log(new Date().toLocaleString() + " > " + result.number);
    }
});
```
```
15/05/2022, 12:02:55 > 17821798
15/05/2022, 12:02:58 > 17821799
15/05/2022, 12:03:01 > 17821800
15/05/2022, 12:03:04 > 17821801
15/05/2022, 12:03:06 > 17821802
15/05/2022, 12:03:10 > 17821803
```

With nariox and my own local BSC node it happens always. Not every 10 minutes (time for the BSC to mine 200 blocks) since starting the client, but exactly at every block multiple of 200.

Funnily, with moralis' node it only gets stuck sometimes. And one time I received a duplicated notification, which was simultaneously received by the Javascript client:

```
15/05/2022 11:42:57 > 17821399
15/05/2022 11:43:01 > 17821400
15/05/2022 11:43:01 > 17821400
15/05/2022 11:43:04 > 17821401
```
not sure if that it also happened at a 200 boundary was a coincidence or not.

The only thing I've found where number 200 has any relevance is that [the BSC re-elects validators every 200 blocks](https://www.bsc.news/post/bnb-chain-introduce-bep131-candidate-validators), but I can't see how this could have anything to do with streaming connections.

My local node shows this when it happens:

```
lvl=dbug msg="RPC connection read error"              err="websocket: close 1000 (normal)"
```
so from the node's side it looks like just a normal client disconnection.

**Comment by juanfranblanco** [comment]
Q: Are you keeping the connection alive? but pinging it?

**Comment by luismcv** [comment]
In my actual use case I do other requests when I receive a new block notification, shouldn't that be enough to keep the connection alive?

Anyway, a timeout would not explain this happening always at exactly at a block multiple of 200. I can launch the test program above at block ....598 and get stuck at ...600 all the same.

**Comment by juanfranblanco** [comment]
It seems that a disconnection is getting forced then at that specific block number.

**Comment by luismcv** [comment]
Yes, but why? It doesn't happen when using JS/web3. Nethereum must be doing something differently.

**Comment by luismcv** [comment]
> Now I have not had that issue with a local node (Ethereum) or Infura.

Yes, so far I've only observed this with BSC nodes.

> Web3.js might be reconnecting and Nethereum is not. Although that means reconstructing the all your subscriptions.

I've been doing some more digging. None seems to be closing or reconnecting. While both are getting updates I see this with netstat:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 100.64.0.5:35360        99.83.175.144:443       ESTABLISHED 9895/node           
tcp        0      0 100.64.0.5:35358        99.83.175.144:443       ESTABLISHED 8538/NethereumTests 
```

When Nethereum gets stuck, the connection remains open, it seems that the node keeps sending notifications, but Nethereum is ignoring them, leaving the data accumulate in the receiving queue:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 100.64.0.5:35360        99.83.175.144:443       ESTABLISHED 9895/node           
tcp    70347      0 100.64.0.5:35358        99.83.175.144:443       ESTABLISHED 8538/NethereumTests 
```

**Comment by juanfranblanco** [comment]
Ok i have found the issue, when this is happening there are a empty response(s), this has been changed to continue regardless.

**Comment by luismcv** [comment]
Great! Thanks! I've opened an issue on their side, see if we can solve the mystery completely.

**Comment by juanfranblanco** [comment]
Well I had change it to allow continuous retrying even if there are empty responses, it makes sense.

**Comment by luismcv** [comment]
I know you worked around it, and it makes Nethereum more robust anyway. I also had worked around it by having a timer that reopened the connection after 10 seconds without receiving a new block. But I couldn't leave this mystery unsolved :)

**Comment by juanfranblanco** [comment]
You actually described it what happens, the validation re-election may lead to a blank response, as the block number may need to be validated by another node, so the one that had the connection has returned blank. I will need to look at the code, but it is a theory :)

**Comment by luismcv** [comment]
Hi again. I was thinking...in your previous version, instead of just returning when the message length was 0, wouldn't it have been better to throw an exception and/or close the socket instead of leaving it there hanged forever?

**Comment by juanfranblanco** [comment]
Yes, i think this was due to a pull request. For sure that was not the intention.

**Comment by juanfranblanco** [comment]
Edit: Or my doing after a pull ..

**Comment by juanfranblanco** [comment]
Not, all my fault: https://github.com/Nethereum/Nethereum/blob/9c17ef4971960234101c8572c806be473cee0ef3/src/Nethereum.JsonRpc.WebSocketClient/StreamingWebSocketClient.cs#L249

**Comment by juanfranblanco** [comment]
Yes, the full rewrite did not handle that scenario, it should have continue retrying as it is implemented now or throw an exception. I prefer the current implementation, as it allows for blank messages to be ignored, as demonstrated that is a real scenario.

**Comment by luismcv** [comment]
I forgive you. Just don't do it again...

Jokes apart, I only mentioned it just in case there were other "silenced" issues anywhere else.

**Comment by juanfranblanco** [comment]
Nah, that was the only failed logic as it was assumed the thread was finished due to a blank message, and that would have been due to a disconnection of the client, which will have been handled on the main thread.
