### ISSUE TITLE
How can I use populateTransaction  like in ethers.js

### ISSUE THREAD

**Issue by liuqiba** [Nethereum/Nethereum#836]
Can you help me!

**Comment by juanfranblanco** [comment]
Check the http://playground.nethereum.com you have samples there.

**Comment by liuqiba** [comment]
PLZ,tell me，which one is the “populateTransaction” eg？
I`m a Newbie,thanks!

**Comment by juanfranblanco** [comment]
Jump to discord and ask for help there, there is not populate transaction which will do something similar. You have web3.Eth.TransanctionManager.SendTransaction. If you look at the playground you have an example there too.

**Comment by juanfranblanco** [comment]
http://playground.nethereum.com/csharp/id/1053 this will be a good example for what you need
