### ISSUE TITLE
Order of dimensions in Solidity's array definitions

### ISSUE THREAD

**Issue by luismcv** [Nethereum/Nethereum#837]
It seems that in Nethereum the order of the dimensions in array definitions in the "Parameter" attributes in IFunctionOutputDTOs (and probably FunctionMessages too) doesn't follow Solidity's notation. Is this by design or has this peculiarity of its notation been overlooked? 

I was getting "Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32." when calling a contract that `returns (address[3][] memory)`. After inverting the order in the Parameter attribute in the DTO to `[Parameter("address[][3]", "", 1)]` it all worked fine.

**Comment by juanfranblanco** [comment]
This is the latest as I explained.

**Comment by luismcv** [comment]
No, it wasn't me. Anyway, I should have tried with the latest version before opening an issue. Thanks!

**Comment by juanfranblanco** [comment]
@luismcv ahh !!! I guess you are working with the same contract then. It was literally last week / or before hence and same question. Obviously you did not know that :D. Yeah, just drop into discord and ask.

**Comment by juanfranblanco** [comment]
Just for info, the original thought was that in this very specific issue the user will do the swapping themselves as this will be understood better when reading the contract definition, (ie a list mapping to that string type) but yeah it has proven not to be the case, so the swapping is being done in the background automatically.
