### ISSUE TITLE
Error compiling solidity through web3, but success through json rpc

### ISSUE THREAD

**Issue by soycabanillas** [Nethereum/Nethereum#84]
The next code compiles the solidity code just fine:

            var web3 = new Web3(_options.Url);
            var buildRequest = web3.Eth.Compile.CompileSolidity.BuildRequest(solcCode);
            var rpcClient = new Nethereum.JsonRpc.Client.RpcClient(new Uri(_options.Url));
            var rpcResponse = await rpcClient.SendRequestAsync(buildRequest);

but the next one throws an exception

            var web3 = new Web3(_options.Url);
            var transactionHash = await web3.Eth.Compile.CompileSolidity.SendRequestAsync(solcCode);

The exception:

	EdjCase.JsonRpc.Client.RpcClientParseException was unhandled by user code
	  HResult=-2146233088
	  Message=Unable to convert the result to type 'System.String'
	  Source=EdjCase.JsonRpc.Client
	  StackTrace:
		   at EdjCase.JsonRpc.Client.RpcResponseExtensions.GetResult[T](RpcResponse response, Boolean returnDefaultIfNull)
		   at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.<SendRequestAsync>d__7.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
		   at Marketpay.Gateway.Ethereum.Impl.EthereumImpl.<CreateSolidityContract>d__17.MoveNext() in C:\Users\Alejandro\Documents\MarketPay\Repos\product\src\Marketpay.Gateway.Ethereum.Impl\EthereumImpl.cs:line 156
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
		   at Marketpay.Gateway.Ethereum.Tests.TransfersTest.<CreateSolidityContractAndCall>d__3.MoveNext() in C:\Users\Alejandro\Documents\MarketPay\Repos\product\test\Marketpay.Gateway.Ethereum.Tests\TransfersTest.cs:line 76
	  InnerException: 
		   HResult=-2147024809
		   Message=Can not convert Object to String.
		   Source=Newtonsoft.Json
		   StackTrace:
				at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
				at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
				at Newtonsoft.Json.Linq.JToken.ToObject[T]()
				at EdjCase.JsonRpc.Client.RpcResponseExtensions.GetResult[T](RpcResponse response, Boolean returnDefaultIfNull)
		   InnerException: 

Am I doing something wrong?

Aside from the exception, I don't know why to build a request `(CompileSolidity.BuildRequest)` one needs a web3 object. Maybe just a design decision? Nothing against it.

            var web3 = new Web3(_options.Url);
            var buildRequest = web3.Eth.Compile.CompileSolidity.BuildRequest(solcCode);
            var rpcClient = new Nethereum.JsonRpc.Client.RpcClient(new Uri(_options.Url));
            var rpcResponse = await rpcClient.SendRequestAsync(buildRequest);

**Comment by juanfranblanco** [comment]
To avoid confusions:
---------------------------------
Web3 sits on top of the RPC library, to simplify usage.

There is a specific RPC command for EthCompileSolidity, if you want to go down to that level.

So you could do:

var rpcClient = new Nethereum.JsonRpc.Client.RpcClient(new Uri(_options.Url));
var compileSolidity = new EthCompileSolidity(rpcClient);
compileSolidity.SendRequestAsync.....

web3 provides a general wrapper, to simplify the interaction with contracts, this is a similar pattern to web3js, which with autocomplete in .Net makes things much easier ;).
---------------------------------

Now to the bug, what is the response you get from the succeful response,  are you able to compile using solc from the command line? Is solc in your path?

**Comment by soycabanillas** [comment]
Thanks for the clarification.

About the bug:
1 - what is the response you get from the succeful response: 
The code that works:

        var web3 = new Web3(_options.Url);
        var buildRequest = web3.Eth.Compile.CompileSolidity.BuildRequest(solcCode);
        var rpcClient = new Nethereum.JsonRpc.Client.RpcClient(new Uri(_options.Url));
        var rpcResponse = await rpcClient.SendRequestAsync(buildRequest);

returns this:

	-		rpcResponse	{EdjCase.JsonRpc.Core.RpcResponse}	EdjCase.JsonRpc.Core.RpcResponse
			Error	null	EdjCase.JsonRpc.Core.RpcError
			HasError	false	bool
			Id	"1"	object {string}
			JsonRpcVersion	"2.0"	string
	-		Result	{{
	  "test": {
		"code": "0x6060604052604051602080605883395060806040525160008190555060318060276000396000f3606060405260e060020a60003504631df4f1448114601c575b6002565b34600257600054600435026060908152602090f3",
		"info": {
		  "source": "pragma solidity ^0.4.1;\r\n\r\ncontract test {\r\n    int _multiplier;\r\n\r\n    function test(int multiplier) {\r\n        _multiplier = multiplier;\r\n    }\r\n\r\n    function multiply(int val) returns (int d) {\r\n        return val * _multiplier;\r\n    }\r\n}",
		  "language": "Solidity",
		  "languageVersion": "0.4.2",
		  "compilerVersion": "0.4.2",
		  "compilerOptions": "--bin --abi --userdoc --devdoc --add-std --optimize -o C:\\Users\\ALEJAN~1\\AppData\\Local\\Temp\\solc800977928",
		  "abiDefinition": [
			{
			  "constant": false,
			  "inputs": [
				{
				  "name": "val",
				  "type": "int256"
				}
			  ],
			  "name": "multiply",
			  "outputs": [
				{
				  "name": "d",
				  "type": "int256"
				}
			  ],
			  "payable": false,
			  "type": "function"
			},
			{
			  "inputs": [
				{
				  "name": "multiplier",
				  "type": "int256"
				}
			  ],
			  "type": "constructor"
			}
		  ],
		  "userDoc": {
			"methods": {}
		  },
		  "developerDoc": {
			"methods": {}
		  }
		}
	  }
	}}	Newtonsoft.Json.Linq.JToken {Newtonsoft.Json.Linq.JObject}
	...
	...

2 - are you able to compile using solc from the command line? Yes, solc works ok.
3 - Is solc in your path? I think that the code that works ok should throw an error if not. Anyway, solc is in my path.

I've tested the code you included on the clarification:

	var rpcClient = new Nethereum.JsonRpc.Client.RpcClient(new Uri(_options.Url));
	var compileSolidity = new EthCompileSolidity(rpcClient);
	var compileResult = await compileSolidity.SendRequestAsync(solcCode);

, but it throws the same error.

**Comment by juanfranblanco** [comment]
That is great thanks, Ill have a look, they use both the same class, hence the issue. It is mainly a type conversion problem. What client are you using geth / parity?

**Comment by soycabanillas** [comment]
Thank you for this great library.
I'm using geth right now. Tried parity but discarded, don't remember why.

**Comment by juanfranblanco** [comment]
Ok the issue seems to be the deserialisation as a JToken instead of as string. Ill release an update / test later on

**Comment by bitcoinbrisbane** [comment]
Version 1.3.1 of that dependency breaks it.  Roll back to 1.1.2 **Install-Package EdjCase.JsonRpc.Client -Version 1.1.2**

**Comment by NAWAZUDDIN552** [comment]
var web3 = new Web3.Web3(account); 
I got this error the type web3 does not exist in the type web3
Iam newbie in Neuthereum. Thanks 
@juanfranblanco

**Comment by juanfranblanco** [comment]
@NAWAZUDDIN552  you will need new Nethereum.Web3.Web3(account) or use as:
using Nethereum.Web3;
....
var web3 = new Web3(account);
You might get the issue due to the namespace.
