### ISSUE TITLE
FilterInputBuilder Can Never Add Topic

### ISSUE THREAD

**Issue by chambs15** [Nethereum/Nethereum#840]
As far as I can tell the FilterInputBuilder.AddTopic will always throw. This is becauseGetTopic [on line ](https://github.com/Nethereum/Nethereum/blob/f0f7cbd225fadfce681faff004a57e480428e62b/src/Nethereum.Contracts/Builders/FilterInput/FilterInputBuilder_T.cs#L47) is called while the topics EventDtoProperty is always going to be null [on line ](https://github.com/Nethereum/Nethereum/blob/f0f7cbd225fadfce681faff004a57e480428e62b/src/Nethereum.Contracts/Builders/FilterInput/TopicFilterContainer.cs#L39). Unless I am missing how the topics get initialized?

**Comment by juanfranblanco** [comment]
You need to call Build

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum.Templates/blob/master/templates/DefaultSmartContract/ContractLibrary.Testing/Erc20TokenTests.cs#L84

**Comment by chambs15** [comment]
```
var mintEventHandler = _web3.Eth.GetEvent<MintEventDTO>(vehicleAddr);  
var filterInputBuilder = mintEventHandler.GetFilterBuilder().AddTopic(x => x.Result, tokenId).Build(vehicleAddr);
```
throws
```
System.NullReferenceException: Object reference not set to an instance of an object.
         at Nethereum.Contracts.TopicFilterContainer`1.<>c__DisplayClass21_0.<GetTopic>b__0(TopicFilter t)
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Nethereum.Contracts.TopicFilterContainer`1.GetTopic(PropertyInfo pInfo)
         at Nethereum.Contracts.FilterInputBuilder`1.AddTopic[TPropertyType](Expression`1 propertySelector, TPropertyType desiredValue)
```
when MintEventDTO is
```
    public partial class MintEventDTO : MintEventDTOBase { }

    [Event("Mint")]
    public class MintEventDTOBase : IEventDTO
    {
        [Parameter("uint256", "result", 1, false )]
        public virtual BigInteger Result { get; set; }
        [Parameter("address", "minter", 2, false )]
        public virtual string Minter { get; set; }
    }
```
when TokenId is BigInteger(1) and vehicleAddr is "0x19C51e32A35F3001fF2dF3d336b9545B6baCC194"

**Comment by juanfranblanco** [comment]
[Event("Mint")]
        public class MintEventDTOBase : IEventDTO
        {
            [Parameter("uint256", "result", 1, true)]
            public virtual BigInteger Result { get; set; }
            [Parameter("address", "minter", 2, true)]
            public virtual string Minter { get; set; }
        }

Your topics are not Indexed, so they cannot be found
