### ISSUE TITLE
Call contract function with array Report an error

### ISSUE THREAD

**Issue by liuqiba** [Nethereum/Nethereum#847]
error:
{ "time": "2022-06-09 13:02:41.9492", "lv": "ERROR", "msg": "Exception: Nethereum.ABI.FunctionEncoding.AbiEncodingException: An error occurred encoding abi value. Order: '2', Type: 'bytes32', Value: 'null'.  Ensure the value is valid for the abi type.
 ---> System.ArgumentException: Expected Numeric Type or String to be Encoded as Bytes32
   at Nethereum.ABI.Encoders.Bytes32TypeEncoder.Encode(Object value)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeAbiTypes(ABIType[] abiTypes, Object[] values)

code ：

`            var transferHandler = web3.Eth.GetContractTransactionHandler<MultiSwapFunctionBase>();
            var transfer = new MultiSwapFunctionBase()
            {
                //AmountToSend = 0,
                //Nonce = wallet.noce,
                //Gas= 1500000,
               // GasPrice = 5,

                FromAddress = wallet.account.Address,

//                 symbols = symbols.ToArray(),
//                 amountIns = amountIns.ToArray(),
//                 amountOutMins = amountOutMins.ToArray(),
//                 pathSlices = pathSlices.ToArray(),
//                 paths = paths.ToArray(),

                symbols = symbols,
                amountIns = amountIns,
                amountOutMins = amountOutMins,
                pathSlices = pathSlices,
                paths = paths,
            };
            ///******************
            var contractHandler = web3.Eth.GetContractHandler(contract.Address);
            var signTx = await contractHandler.SignTransactionAsync<MultiSwapFunctionBase>(transfer);
            var back = await contractHandler.SignTransactionAsync(transfer);

            ///******************

            //var transactionReceipt = await transferHandler.SendRequestAndWaitForReceiptAsync(contract.Address, transfer);
            web3.Eth.TransactionManager.UseLegacyAsDefault = true;
            var signedTransaction1 = await transferHandler.SignTransactionAsync(contract.Address, transfer);`

       class MultiSwapFunctionBase : TransferFunction
        {
            [Parameter("uint8[]", "symbols", 1)]
            public virtual List< byte> symbols { get; set; }
            [Parameter("uint[]", "amountIns", 2)]
            public virtual List<uint> amountIns { get; set; }
            [Parameter("uint[]", "amountOutMins", 3)]
            public virtual List<uint> amountOutMins { get; set; }
            [Parameter("uint8[]", "pathSlices", 4)]
            public virtual List<byte> pathSlices { get; set; }
            [Parameter("address[]", "paths", 5)]
            public virtual List<string> paths { get; set; }
            // 
            //             [Parameter("tuple[]", "symbols", 1)]
            //             public virtual byte[] symbols { get; set; }
            //             [Parameter("tuple[]", "amountIns", 2)]
            //             public virtual uint[] amountIns { get; set; }
            //             [Parameter("tuple[]", "amountOutMins", 3)]
            //             public virtual uint[] amountOutMins { get; set; }
            //             [Parameter("tuple[]", "pathSlices", 4)]
            //             public virtual byte[] pathSlices { get; set; }
            //             [Parameter("tuple[]", "paths", 5)]
            //             public virtual string[] paths { get; set; }
        }

abi：

`    {
      "inputs": [
        {
          "internalType": "uint8[]",
          "name": "symbols",
          "type": "uint8[]"
        },
        {
          "internalType": "uint256[]",
          "name": "amountIns",
          "type": "uint256[]"
        },
        {
          "internalType": "uint256[]",
          "name": "amountOutMins",
          "type": "uint256[]"
        },
        {
          "internalType": "uint8[]",
          "name": "pathSlices",
          "type": "uint8[]"
        },
        {
          "internalType": "address[]",
          "name": "paths",
          "type": "address[]"
        }
      ],
      "name": "multiSwap",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },`

version : 4.5

I saw lost all other issues but can not resolve this.
Plz help me

**Comment by liuqiba** [comment]
> 
Finally I found out that I used the wrong base class "TransferFunction"
The correct one should be "FunctionMessage"

**Comment by juanfranblanco** [comment]
@liuqiba Use the code generator, it helps to avoid mistakes

**Comment by liuqiba** [comment]
> @liuqiba Use the code generator, it helps to avoid mistakes

Thank you very much！
I didn't know  code generator was there before

**Comment by liuqiba** [comment]
> @liuqiba Use the code generator, it helps to avoid mistakes

http://playground.nethereum.com/  code generator not work 

after writting datas and click Generate code ,the box is colse ,and nothing happened

I tried  4 times.
