### ISSUE TITLE
Build Issues (Visual Studio Solution)

### ISSUE THREAD

**Issue by WINMAN174** [Nethereum/Nethereum#85]
Nethereum.JsonRpc.Client.IClient.cs, Nethereum.RPC.Eth.Services.EthUncleService.cs and Nethereum.RPC.Sample.Program.cs will not compile. I'm not sure how you guys are making that work.

I can get it to work by moving some code around but not a good solution. 

Thanks.

**Comment by juanfranblanco** [comment]
I have had a look and I don't see any issues, what is the code that you need to move around? What project?

**Comment by WINMAN174** [comment]
Found the problem. 3 links were missing. Adding them, as shown highlighted, will fix the problem. Happens all the time. 

 



 

 

Here is the other minor problem…

 



 

 

Oh, I asked about watching events on Gitter. Could not figure out how to do that. 

 

Thanks. Great work BTW. Very much appreciated.

**Comment by juanfranblanco** [comment]
The screenshots, did not appear on the mail response. But I am guessing (emphasis on the guess part, but might help) you are using the Portable project. The portable is not the "working" environment, it is auto generated by running BuildProjectFile, which adds links to all new files added to the project.

**Comment by WINMAN174** [comment]
Ok let’s try this again. 

 

Yes I see what you are doing now. Never seen anyone do that before but then again I have not had a chance to work with portables. 

 

Anyways thanks. I’ll take a look at it.

**Comment by juanfranblanco** [comment]
Yes, the portable was created as a way to transition to dnx, core, netstandard. Which is still not complete.

**Comment by juanfranblanco** [comment]
Also your email is visible in the github / mail trail. you might want to look at that.

**Comment by WINMAN174** [comment]
No seeing it. Where is that option?

**Comment by juanfranblanco** [comment]
I have deleted it from all the responses, you are responding including the mail history, which is then send to github.

**Comment by WINMAN174** [comment]
Outlook. Nice. Gonna turn that one off.

**Comment by WINMAN174** [comment]
Thought I was on Craig's list.
