### ISSUE TITLE
Nethereum.Portable - Does not have latest version 4.6.1

### ISSUE THREAD

**Issue by homeyong** [Nethereum/Nethereum#856]
Hi Developer, 

I would like to use some new function that available in version 4.6.1, how the Nethereum.Portable is not up-to-date.
Can you help?

Thank you!

**Comment by juanfranblanco** [comment]
Have you tried using https://www.nuget.org/packages/Nethereum.Fx?

**Comment by Enigmatic331** [comment]
Hi Kenny, meet Juan. Hi Juan, meet Kenny. 😁

**Comment by juanfranblanco** [comment]
Nethereum.Fx it is a bundle of most projects, similar to portable 
![Screenshot 2022-07-11 165359](https://user-images.githubusercontent.com/562371/178306260-d190b177-a4a0-405a-97ee-e6d681a94501.png)

![image](https://user-images.githubusercontent.com/562371/178306405-ecd5e7a2-8ad4-4bd5-947d-bb5cf4621bc0.png)

**Comment by Enigmatic331** [comment]
Aaaah cool, Contracts.Standards should be there - Mainly looking to try out ERC1271 and see how it works out... :) Thanks so much Juan.... 🙇

**Comment by juanfranblanco** [comment]
@Enigmatic331 @homeyong  Yes that is an easy one, just validates the return value to match 
```
public const string MAGICVALUE = "0x1626ba7e";
```

**Comment by homeyong** [comment]
Hi @juanfranblanco , thank you for getting me back. (Nethereum.Fx)
The information is helpful, now I'm trying it out to call the function IsValidSignatureAndValidateReturnQueryAsync.
