### ISSUE TITLE
how eth_sendRawTransaction

### ISSUE THREAD

**Issue by 632201630** [Nethereum/Nethereum#860]
help,I used the following code to get this error
— ```
Nethereum.JsonRpc.Client.RpcResponseException: transaction could not be decoded: could not decode RLP components: extra data at end: eth_sendRawTransaction

（I authorize fromAddress to adminAddress , initiate transfer through adminAddress , and transfer to toAddress）

var adminKey = con.GetSection(“Admin:Key”).Value;
var adminAddress = con.GetSection(“Admin:Address”).Value;
var account = new ManagedAccount(adminAddress,adminKey );
var url = "https://mainnet.infura.io/v3/xxxx"
var web3 = new Web3(account, url );
Contract contract = web3.Eth.GetContract(usdtAbi,usdtAddress);
TransactionInput txinput = new TransactionInput();
txinput.From = fromAddress;
txinput.To = toAddress;
txinput.Value = new HexBigInteger(1000000);
txinput.Nonce = 26;
EthereumMessageSigner signer1 = new EthereumMessageSigner();
var signature1 = signer1.EncodeUTF8AndSign(txinput.ToJson(), new EthECKey(adminKey));
var rrr = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync(signature1);

**Comment by juanfranblanco** [comment]
See this example http://playground.nethereum.com/csharp/id/1059, you need to use the transaction manager, also you cannot use the ManagedAccount, and if you want to interact with smart contracts this example will help you get started http://playground.nethereum.com/csharp/id/1007

**Comment by 632201630** [comment]
> 看这个例子http://playground.nethereum.com/csharp/id/1059，你需要使用事务管理器，也不能使用 ManagedAccount，如果你想与智能合约交互，这个例子将帮助你开始http://playground.nethereum.com/csharp/id/1007

I tried to create object TransferFunction, but it has no property ‘To’ in it

**Comment by 632201630** [comment]
> See this example http://playground.nethereum.com/csharp/id/1059, you need to use the transaction manager, also you cannot use the ManagedAccount, and if you want to interact with smart contracts this example will help you get started http://playground.nethereum.com/csharp/id/1007

I currently have three addresses,
adminAddress : I have the key to it
sendAddress : The approve operation is complete
receiveAddress

1.I don't know if txinput  is right. and whether 'txinput.Data' should be empty
           TransactionInput txinput = new TransactionInput();
            txinput.From = sendAddress;
            txinput.To = receiveAddress;
            txinput.Value = new HexBigInteger(1000000);
            txinput.Nonce = txCount;
            txinput.Data = "";
2.If 'web3.Eth.TransactionManager.SendTransactionAndWaitForReceiptAsync' is used, I find that no signature parameter is passed and I don't think the transaction will be completed.
The transaction returns an error of  
‘System.Exception: Invalid account used
   at Nethereum.Web3.Accounts.Managed.ManagedAccountTransactionManager.SendTransactionAsync(TransactionInput transactionInput)
   at Nethereum.RPC.TransactionReceipts.TransactionReceiptPollingService.SendRequestAndWaitForReceiptAsync(Func`1 transactionFunction, CancellationTokenSource tokenSource)’

         var signer1 = new EthereumMessageSigner();
         var signature1 = signer1.EncodeUTF8AndSign(txinput.ToJson(), new EthECKey(adminKey));
         var txnReceipt = await web3.Eth.TransactionManager.SendTransactionAndWaitForReceiptAsync(txinput, null);

**Comment by juanfranblanco** [comment]
This is how you create your web3 instance
![image](https://user-images.githubusercontent.com/562371/183060156-1ff220e5-816e-4bf9-b33e-7e8b2cd1957e.png)

and this how you send it 
![image](https://user-images.githubusercontent.com/562371/183060343-f2f1e1d8-d097-4023-befb-2be63d259450.png)

or if you want to sign it and send it later you can do this:
![image](https://user-images.githubusercontent.com/562371/183060725-78a28f0c-14cd-4941-9bca-7a7b81a47080.png)

also note that we have the TransferFunction defined already as 
![image](https://user-images.githubusercontent.com/562371/183060887-0c111ff5-486c-445b-ba68-d710a6f0f2cb.png)

although as this an standard it is already defined in :
```csharp	var x = new Nethereum.Contracts.Standards.ERC20.ContractDefinition.TransferFunction();
		x.To
```

All this can be followed here http://playground.nethereum.com/csharp/id/1007

**Comment by Cod4h** [comment]
Instructions are obsolete everywhere. I have been already 1 week trying to send a token and I still can't.

**Comment by juanfranblanco** [comment]
Hi @Cod4h the instructions are working for all the versions of Nethereum. This example explains the whole process of interacting with smart contracts http://playground.nethereum.com/csharp/id/1007
But if you just want to make a simple token transfer..you can just do this:

```csharp
 /**Finished Deploying erc20 example**/

		/**Transfer**/
			var toAddress = "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe";
		var txn = await web3.Eth.ERC20.GetContractService(contractAddress).TransferRequestAsync(toAddress,100);
		Console.WriteLine(txn);
		/**Transfer finished*/													
		
```

Full example including deployment of mock up ERC20 contract, just copy and paste it and run it in the playground

```csharp
using System;
using System.Numerics;
using System.Threading.Tasks;
using Nethereum.Web3;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.Contracts;
using Nethereum.Web3.Accounts;

public class Program
{
	//This example uses the preset Nethereum ERC20 contract interface
	private static async Task Main(string[] args)
	{

		/**connection**/
		var url = "http://testchain.nethereum.com:8545";
        var privateKey = "0x7580e7fb49df1c861f0050fae31c2224c6aba908e116b8da44ee8cd927b990b0";
        var chainId = 444444444500; //Nethereum test chain, chainId
        var account = new Account(privateKey, chainId);
        var web3 = new Web3(account, url);
		
		/**Deploying erc20 example**/
		var deploymentMessage = new StandardTokenDeployment
		{
			TotalSupply = 100000
		};

		// Then we create a deployment handler using our contract deployment definition and simply deploy the contract using the deployment message. We are auto estimating the gas, getting the latest gas price and nonce so nothing else is set anything on the deployment message.
		// Finally, we wait for the deployment transaction to be mined, and retrieve the contract address of the new contract from the receipt.

		var deploymentHandler = web3.Eth.GetContractDeploymentHandler<StandardTokenDeployment>();

		var transactionReceipt = await deploymentHandler.SendRequestAndWaitForReceiptAsync(deploymentMessage);

		var contractAddress = transactionReceipt.ContractAddress;

	    /**Finished Deploying erc20 example**/

		/**Transfer**/
			var toAddress = "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe";
		var txn = await web3.Eth.ERC20.GetContractService(contractAddress).TransferRequestAsync(toAddress,100);
		Console.WriteLine(txn);
		/**TRansfer finished*/													
		
	}


		public class StandardTokenDeployment : ContractDeploymentMessage
	{
		public static string BYTECODE =
			"0x60606040526040516020806106f5833981016040528080519060200190919050505b80600160005060003373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060005081905550806000600050819055505b506106868061006f6000396000f360606040523615610074576000357c010000000000000000000000000000000000000000000000000000000090048063095ea7b31461008157806318160ddd146100b657806323b872dd146100d957806370a0823114610117578063a9059cbb14610143578063dd62ed3e1461017857610074565b61007f5b610002565b565b005b6100a060048080359060200190919080359060200190919050506101ad565b6040518082815260200191505060405180910390f35b6100c36004805050610674565b6040518082815260200191505060405180910390f35b6101016004808035906020019091908035906020019091908035906020019091905050610281565b6040518082815260200191505060405180910390f35b61012d600480803590602001909190505061048d565b6040518082815260200191505060405180910390f35b61016260048080359060200190919080359060200190919050506104cb565b6040518082815260200191505060405180910390f35b610197600480803590602001909190803590602001909190505061060b565b6040518082815260200191505060405180910390f35b600081600260005060003373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060005060008573ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600050819055508273ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925846040518082815260200191505060405180910390a36001905061027b565b92915050565b600081600160005060008673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600050541015801561031b575081600260005060008673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060005060003373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000505410155b80156103275750600082115b1561047c5781600160005060008573ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828282505401925050819055508273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a381600160005060008673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282825054039250508190555081600260005060008673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060005060003373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828282505403925050819055506001905061048656610485565b60009050610486565b5b9392505050565b6000600160005060008373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000505490506104c6565b919050565b600081600160005060003373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600050541015801561050c5750600082115b156105fb5781600160005060003373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282825054039250508190555081600160005060008573ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828282505401925050819055508273ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a36001905061060556610604565b60009050610605565b5b92915050565b6000600260005060008473ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060005060008373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060005054905061066e565b92915050565b60006000600050549050610683565b9056";

		public StandardTokenDeployment() : base(BYTECODE)
		{
		}

		[Parameter("uint256", "totalSupply")]
		public BigInteger TotalSupply { get; set; }
	}
}
```
