### ISSUE TITLE
Unity(2021.3.5f1c1)+unitynet35dlls(4.7.0) import error

### ISSUE THREAD

**Issue by xiexx-game** [Nethereum/Nethereum#868]
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (D:/sample/Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/Newtonsoft.Json.dll)

**Comment by juanfranblanco** [comment]
This is an issue with Unity, you need to untick the assembly verification, or remove the duplicated Newtonsoft.json
