### ISSUE TITLE
How to decode raw transaction hex string?

### ISSUE THREAD

**Issue by miaojiuchen** [Nethereum/Nethereum#869]
I need to decode eth 1559 raw transaction string to get some information like `from`, `to` , `gas` etc.
It's easy to impl this in golang, but I didn't find solution to do this in Nethereum

See golang demo:
https://go.dev/play/p/Vv9b2MkJc5W

Could you please help? :) @juanfranblanco

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer/TransactionFactory.cs#L45

If you have any more questions come to discord
