### ISSUE TITLE
Deploy contract with msg.value

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#87]
Hello:
How can I deploy a contract whose constructor / default reads msg.value to perform operations? 
Tried the variations in the function **await web3.Eth.DeployContract.SendRequestAsync**, but unable to find how the parms[] should be set (is it using parms?)
Thank you

**Comment by juanfranblanco** [comment]
Yes, there is an overload missing for the value.

**Comment by ushakrishnan** [comment]
Can you provide how that could be implemented?  Where should that be changed?

**Comment by juanfranblanco** [comment]
The new commit includes the overloads for Deployment, Function has already the value option

**Comment by ushakrishnan** [comment]
Wow! Super quick!  Many thanks Juan.

**Comment by juanfranblanco** [comment]
I need to add some unit tests, before closing the issue (currently installing visual studio 2017 so it will be later).

**Comment by ushakrishnan** [comment]
Ok, I will download source code and compile for testing.  I guess it will on nuget after you close, is that so?  BTW, I watched your video and posted my appreciation of your work as my comment.  You are awesome! chaingenie.com uses nethereum :-)

**Comment by juanfranblanco** [comment]
Many thanks for your kind comments. Yes that is the plan for release, and I will check out chaingenie.com!

**Comment by ushakrishnan** [comment]
Hi Juan,  Looks like the msg.value does transfer in to smart contract, although no error is thrown.   I am running the same smart contract through ethereum wallet and able to see the balances change.

**Comment by juanfranblanco** [comment]
Great thanks, I'll make some unit tests and release this weekend

**Comment by ushakrishnan** [comment]
I meant to say DOES NOT.  Sorry for not being clear!!

**Comment by ushakrishnan** [comment]
Juan, Something not working out.  Sorry for being unclear earlier! It does NOT work / move msg.value into the smart contract
While the code works with no issues, the msg.value is not passed into the smart contract.  The exact smart contract in ethereum wallet works and I am able see changing balances. 
I am testing with safe-remote-purchase example - https://solidity.readthedocs.io/en/develop/solidity-by-example.html#safe-remote-purchase , which operates on basis of msg.value sent to the contract

**Comment by juanfranblanco** [comment]
@ushakrishnan  you might have ran out of gas, check my test is all working.  https://github.com/Nethereum/Nethereum/blob/0536dafeb81f3135c12f758abb4550489309bbc2/src/Nethereum.Web3.Tests/ContractDeploymentAndCall.cs#L157-L187

**Comment by ushakrishnan** [comment]
Thanks @juanfranblanco, will check now.
