### ISSUE TITLE
Nethereum.Autogen.ContractApi v4.2.0 needs Microsoft.NETCore.App v2.1 to run

### ISSUE THREAD

**Issue by kamran65536** [Nethereum/Nethereum#870]
I've studies the code and new commits, it seems Nethereum.Autogen.ContractApi v4.2.0 should support .net 5
but the packaged published on nuget.org still needs Microsoft.NETCore.App v2.1 to run
this makes CI/CD process very painful.

**Comment by heypran** [comment]
I agree with you. I had a similar situation, and to make it work I had to deal with different versions and some other issues. The setup is still not perfect.

**Comment by juanfranblanco** [comment]
Yeah although it is 3.1 not 2.1
