### ISSUE TITLE
BlockchainProcessor.ExecuteAsync throws InvalidOperationException in case of token cancellation

### ISSUE THREAD

**Issue by FatTigerWang** [Nethereum/Nethereum#872]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our discord channel first. [Discord](https://discord.gg/u3Ej2BReNn )

BlockchainProcessor.ExecuteAsync throws InvalidOperationException in case of token cancellation

## Expected Behavior
BlockchainProcessor.ExecuteAsync works

## Current Behavior
BlockchainProcessor.ExecuteAsync throws InvalidOperationException in case of token cancellation

## Possible Solution
By default, the LogOrchestrator.ProcessAsync() method is used for BlockchainProcessor.ExecuteAsync().

In a specific token cancellation case, LogOrchestrator.ProcessAsync will return OrchestrationProgress.Exception is null and OrchestrationProgress.BlockNumberProcessTo is also null, which will cause BlockchainProcessor.ExecuteAsync  throw `System.InvalidOperationException: Nullable object must have a value`

[BlockchainProcessor.ExecuteAsync](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.BlockchainProcessing/BlockchainProcessor.cs#L40)
[LogOrchestrator.ProcessAsync](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.BlockchainProcessing/LogProcessing/LogOrchestrator.cs#L43)

## Steps to Reproduce
```csharp
[Fact]
public async Task Should_Throw_OperationCanceledException_When_Cancellation()
{
    CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
    cancellationTokenSource.Cancel();

    var progress = await _logOrchestrator.ProcessAsync(0, 0, cancellationTokenSource.Token);

    Assert.NotNull(progress);
    Assert.Null(progress.BlockNumberProcessTo);
    Assert.NotNull(progress.Exception);
    Assert.IsType<OperationCanceledException>(progress.Exception);
}
```

## Possible Implementation
Use `cancellationToken.ThrowIfCancellationRequested()` instead of `cancellationToken.IsCancellationRequested`

**Comment by FatTigerWang** [comment]
By the way, using CancellationToken.IsCancellationRequested instead of CancellationToken.ThrowIfCancellationRequested() might be an anti-pattern.

[Stephen Cleary-Cancellation, Part 4: Polling](https://blog.stephencleary.com/2022/03/cancellation-4-polling.html)

**Comment by juanfranblanco** [comment]
Well it is an anti-pattern on this persons opinion, i need to go deeper into the issue as the cancellation is triggered by the user here.

**Comment by juanfranblanco** [comment]
So wouldn't it better to change the code here https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.BlockchainProcessing/BlockchainProcessor.cs#L40 to validate if it has been cancelled before checking the error?

**Comment by FatTigerWang** [comment]
Checking there does prevent the exception from happening, but the root cause of the exception is: BlockchainProcessor.ExecuteAsync expects LogOrchestrator.ProcessAsync to either not return an exception and have the correct BlockNumberProcessTo, or return an exception.  But LogOrchesrator.ProcessAsync neither exception nor set BlockNumberProcessTo correctly, which is obviously unexpected.  If you continue to use LogOrchesrator.ProcessAsync elsewhere, it is very likely that the processing of no exception and BlockNumberProcessTo is empty will also be missed.  So I suggest changing LogOrchesrator.ProcessAsync to return the correct expectation.

**Comment by juanfranblanco** [comment]
I think the best is to add another check here to validate it has been cancelled in which will update the progress but not throw, what has happened is that the code has been executed and cancelled, whilst on the while loop, so adding a check for cancellation after return will fix that scenario.

**Comment by juanfranblanco** [comment]
Now on the other hand, it does not feel right that we are working with this "global" god like state value, which is the cancellation and that the progress could return that, as you said. But that is the nature of cancellation which is rather smelly.

**Comment by FatTigerWang** [comment]
I tried adding token cancellation check here https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.BlockchainProcessing/BlockchainProcessor.cs#L40:
````csharp
if (!progress.HasErrored)
{
    if (cancellationToken.IsCancellationRequested) return;
    fromBlockNumber = progress.BlockNumberProcessTo.Value + 1;
    await UpdateLastBlockProcessedAsync(progress.BlockNumberProcessTo).ConfigureAwait(false);
}
else
{
    await UpdateLastBlockProcessedAsync(progress.BlockNumberProcessTo).ConfigureAwait(false);
    throw progress.Exception;
}

````
But the `Should_Complete_Current_Block_When_Canceled_During_Fetch_Of_Last_Confirmed_Block_Number` unit test is buggy, apparently it wants to save the last processed block number also when the token is cancelled.

**Comment by FatTigerWang** [comment]
any news？

**Comment by juanfranblanco** [comment]
I added this other check, which prevents the update as it will have already happened, on the response. https://github.com/Nethereum/Nethereum/commit/f64e10585f9f27ae565b339817e937a14f0fa571

**Comment by juanfranblanco** [comment]
Ok as per latest, the only thing required was to validate if cancellation and just do the Upsert, we cannot rely on the underlying implementation to do the update. https://github.com/Nethereum/Nethereum/commit/a71ea3c1a3355b0d0bda48e93c43637ed0dc259d
