### ISSUE TITLE
GetTransactionByBlockNumberAndIndex wrong value returned

### ISSUE THREAD

**Issue by ppowierza** [Nethereum/Nethereum#874]
While using method GetTransactionByBlockNumberAndIndex  like this:

```
    var hexInt = new HexBigInteger("0xEB0FF4");  // 15405044
    var txNumber = await web3.Eth.Blocks.GetBlockTransactionCountByNumber.SendRequestAsync(hexInt);
```
I get the response txNumber  = "0xbd" // 189, This value is wrong.

When on etherScan we can see that it should be 291. When I call the same endpoint from postrman, I have the same values as in etherScan.

My package version is 4.8.0 and I have .net 6.0 app

![image](https://user-images.githubusercontent.com/49204367/186524262-3741078b-4197-4189-9324-f190fa86947b.png)

**Comment by juanfranblanco** [comment]
@ppowierza you are passing a HexBigInteger instead of a BlockParameter which is created with a HexBigInteger, as a BlockParameter can also be "latest" etc. So the overload that is being used is the Object one which is mainly the requestId and defaulting to the BlockParameter "latest".

```csharp
var hexInt = new HexBigInteger(15405044);  
    	var txNumber = await web3.Eth.Blocks.GetBlockTransactionCountByNumber.SendRequestAsync(new BlockParameter(hexInt));	

```
