### ISSUE TITLE
How to decode ERC20 event (Transfer or Approval) out from transaction log using Nethereum

### ISSUE THREAD

**Issue by Kane-Tang** [Nethereum/Nethereum#877]
I tried to get ERC20 event like transfer or approval from transaction logs and it works when I tried on ERC721 while it fails for ERC20. Actually, for every transaction log I've already tested, the decoded object would all go null.  Is there anything wrong with the Nethereum usage or due to some else reasons, the following is my demo code, could you please help with it? Thanks, @juanfranblanco 

![image](https://user-images.githubusercontent.com/29678032/191202704-2b6d9e0f-f098-49c0-89fe-5c38eb60fc67.png)
![image](https://user-images.githubusercontent.com/29678032/191202781-64c664be-23c6-4c92-8300-bd87ba130178.png)

**Comment by juanfranblanco** [comment]
ERc20 event is not indexed the last parameter

**Comment by Kane-Tang** [comment]
> ERc20 event is not indexed the last parameter

you mean there are only two params for ERC20 event? According to https://ethereum.org/en/developers/docs/standards/tokens/erc-20/, it seems cover this, thanks.

**Comment by Kane-Tang** [comment]
I tried to use txReceipt.DecodeAllEvents<TransferEventDTOBase>() instead while sometimes it works, sometimes it returns no events when it can be found on Etherscan according to the transaction hash. Could you please give me the sample to get event from transaction receipt if my grammer is wrong. Thanks, @juanfranblanco

**Comment by Kane-Tang** [comment]
Could you please take a look at this question if convenient, thankks, @juanfranblanco

**Comment by juanfranblanco** [comment]
@Kane-Tang 
The 721 transfer has an extra index
![image](https://user-images.githubusercontent.com/562371/192260678-ae5ef171-e737-4279-a4c5-9e2ce3f8f23b.png)
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Contracts/Standards/ERC721/ContractDefinition/ERC721Definition.cs#L397
--
as opposed to erc20
![image](https://user-images.githubusercontent.com/562371/192261097-e753d2bc-8964-418a-88f5-2cdc258b5957.png)
which value is not
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Contracts/Standards/ERC20/ContractDefinition/ERC20Definition.cs#L142

So the look the same but they are not,
What you can do is to check the number of Topics for the matching log and switch accordingly
