### ISSUE TITLE
SingAndSendTransactionAsync - null reference exception

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#88]
Hi @juanfranblanco 

When I make a call as below for transaction to send msgvalue

var result1 = await myfn.SingAndSendTransactionAsync(pass,addressFrom, new HexBigInteger(100000), new HexBigInteger(10));

I get the following error.  

An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
Nethereum.Web3.FunctionBase.SingAndSendTransactionAsync(String password, String encodedFunctionCall, String from, HexBigInteger gas, HexBigInteger value) in FunctionBase.cs, line 189

Minor - you may want to fix the typo (Sing and Sign), works since it is consistently carried through.

**Comment by juanfranblanco** [comment]
Yes, that method was using HexBigInteger as the params values. Check the latest. And many thanks for the typo too.

**Comment by ushakrishnan** [comment]
I get the same error with the updates here - null reference in FunctionBase.cs

The same function works with sendtransaction, just not signandsend

Does not work -
var result1 = await myfn.SignAndSendTransactionAsync(pass, addressFrom, estgas, new HexBigInteger( msgValue), parmCList);

works (but msgvalue ...!)
            var result1 = await myfn.SendTransactionAsync(addressFrom, estgas, new HexBigInteger(msgValue), parmCList);

**Comment by juanfranblanco** [comment]
@ushakrishnan extra tests, change overloads and fix. Should be fine if you don't have any other problem.

**Comment by ushakrishnan** [comment]
Thanks @juanfranblanco , I will download changes now and test.  Do you really work 24x7?  Consensys was lucky to steal you :-) Thanks again.

**Comment by ushakrishnan** [comment]
Worked like a charm!  Perfect!!!!  Thank you :-)
