### ISSUE TITLE
Blazor server mode. The current thread is not associated with the Dispatcher. 

### ISSUE THREAD

**Issue by AlexK555** [Nethereum/Nethereum#882]
After updating my .net6 Blazor server application from Nethereum.Metamask.Blazor 4.6.0 to 4.8.0 I get following error:
System.InvalidOperationException: 'The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.'

``
var account = await _ethereumHostProvider.GetProviderSelectedAccountAsync();
``

## Expected Behavior
GetProviderSelectedAccountAsync should work inside OnAfterRenderAsync method in Blazor server mode.

## Current Behavior
GetProviderSelectedAccountAsync is not executed it the main UI thread because all async calls are performed with configureAwait(false) and fails.

## Possible Solution
Modify existing example project to show how to work with new version. 

## Steps to Reproduce
Run latest version of ExampleProject.Server.csproj from examples with Nethereum.Metamask.Blazor 4.8.0 or higher.
(https://github.com/Nethereum/Nethereum.Templates.Metamask.Blazor)

## Possible Implementation
Currently it works if I remove ConfigureAwait(false) from those lines of code inside the library:            

``
await ChangeSelectedAccountAsync(result).ConfigureAwait(false);
``
``
await SelectedAccountChanged.Invoke(selectedAccount).ConfigureAwait(false);
``
``
await NotifyAuthenticationStateAsEthereumConnected(ethereumAddress).ConfigureAwait(false);
``

**Comment by juanfranblanco** [comment]
@AlexK555 this is on the latest release now. Let me know if you have any other issues.
