### ISSUE TITLE
Feature Reuqest: Arweave support

### ISSUE THREAD

**Issue by taurenshaman** [Nethereum/Nethereum#885]
Web3 is inseparable from storage. 
And Arweave is the permanent one.
So is there any plan to supoort Arweave?
Very poor: there is no search result about C# (′д｀ )…彡…彡
![image](https://user-images.githubusercontent.com/1308706/196830683-62833531-2386-417c-97ce-68aabd339dbf.png)

**Comment by juanfranblanco** [comment]
Hi, no plans for this, but if you can come to discord an explain what is this..
