### ISSUE TITLE
Unity: MissingMethodException when using HdWallet

### ISSUE THREAD

**Issue by Cherden** [Nethereum/Nethereum#889]
I have a unity project that builds .NET4.X AOT with IL2CPP. I used the DLLs of 
net472UnityCommonAOT.zip from release [4.10.0](https://github.com/Nethereum/Nethereum/releases/tag/4.10.0). When calling `new NethWallet.Wallet(mnemoString, password).GetAccount(0);` the program fails with
```
MissingMethodException: void System.Security.Cryptography.Rfc2898DeriveBytes..ctor(byte[],byte[],int,System.Security.Cryptography.HashAlgorithmName)
Nethereum.HdWallet.Wallet.InitialiseSeed (System.String words, System.String seedPassword) (at <a780d13620584f328d0054f83e171813>:0)
Nethereum.HdWallet.Wallet..ctor (System.String words, System.String seedPassword, System.String path, NBitcoin.IRandom random) (at <a780d13620584f328d0054f83e171813>:0)
```
Am I missing a DLL that is not included in the release?

**Comment by juanfranblanco** [comment]
Check if you have System.Security.Cryptography included. that is a .Net framework dll

**Comment by Cherden** [comment]
I do not have it in my project. Is it possible to add it to the release?

**Comment by juanfranblanco** [comment]
Hmmm maybe is getting stripped? Do you have a linked file?

**Comment by Cherden** [comment]
I have a link.xml if that's what you meant. Content:
```
<linker>
	<assembly fullname="System" preserve="all">
		<type fullname="System.ComponentModel.TypeConverter" preserve="all"/>
		<type fullname="System.ComponentModel.ArrayConverter" preserve="all"/>
		<type fullname="System.ComponentModel.BaseNumberConverter" preserve="all"/>
		<type fullname="System.ComponentModel.BooleanConverter" preserve="all"/>
		<type fullname="System.ComponentModel.ByteConverter" preserve="all"/>
		<type fullname="System.ComponentModel.CharConverter" preserve="all"/>
		<type fullname="System.ComponentModel.CollectionConverter" preserve="all"/>
		<type fullname="System.ComponentModel.ComponentConverter" preserve="all"/>
		<type fullname="System.ComponentModel.CultureInfoConverter" preserve="all"/>
		<type fullname="System.ComponentModel.DateTimeConverter" preserve="all"/>
		<type fullname="System.ComponentModel.DecimalConverter" preserve="all"/>
		<type fullname="System.ComponentModel.DoubleConverter" preserve="all"/>
		<type fullname="System.ComponentModel.EnumConverter" preserve="all"/>
		<type fullname="System.ComponentModel.ExpandableObjectConverter" preserve="all"/>
		<type fullname="System.ComponentModel.Int16Converter" preserve="all"/>
		<type fullname="System.ComponentModel.Int32Converter" preserve="all"/>
		<type fullname="System.ComponentModel.Int64Converter" preserve="all"/>
		<type fullname="System.ComponentModel.NullableConverter" preserve="all"/>
		<type fullname="System.ComponentModel.SByteConverter" preserve="all"/>
		<type fullname="System.ComponentModel.SingleConverter" preserve="all"/>
		<type fullname="System.ComponentModel.StringConverter" preserve="all"/>
		<type fullname="System.ComponentModel.TimeSpanConverter" preserve="all"/>
		<type fullname="System.ComponentModel.UInt16Converter" preserve="all"/>
		<type fullname="System.ComponentModel.UInt32Converter" preserve="all"/>
		<type fullname="System.ComponentModel.UInt64Converter" preserve="all"/>
	</assembly>
	<assembly fullname="Nethereum.ABI" preserve="all"/>
	<assembly fullname="Nethereum.Hex" preserve="all"/>
	<assembly fullname="Nethereum.RPC" preserve="all"/>
	<assembly fullname="Nethereum.RLP" preserve="all"/>
	<assembly fullname="Nethereum.Contracts" preserve="all"/>
	<assembly fullname="Nethereum.Util" preserve="all"/>
	<assembly fullname="Nethereum.Signer" preserve="all"/>
	<assembly fullname="Nethereum.JsonRpc.Client" preserve="all"/>
	<assembly fullname="Nethereum.Unity" preserve="all"/>
</linker>
```

**Comment by juanfranblanco** [comment]
Well it seems that it is being stripped, try adding it or remove the whole file.

**Comment by Cherden** [comment]
I tried adding it, removing the file but nothing seems to work. To calrify, the error happens during runtime, even when running it in the editor. 
Minimal example if you want to verify yourself in a fresh project with the dlls in net472UnityCommonAOT.zip from release [4.10.0](https://github.com/Nethereum/Nethereum/releases/tag/4.10.0):
```
var mnemoString = new Mnemonic(Wordlist.English, WordCount.Twelve).ToString();
var account = new NethWallet.Wallet(mnemoString, password).GetAccount(0);
Debug.Log(account.PrivateKey);
```

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/198343118-90eab864-d2c8-4e64-a606-da1aad536219.png)
![image](https://user-images.githubusercontent.com/562371/198343214-6fb594db-adb5-46f2-8c65-8d40abaf9365.png)
![image](https://user-images.githubusercontent.com/562371/198343340-6920bd8e-8898-4b9e-b137-7fe4bd3771f0.png)

**Comment by Cherden** [comment]
Looking at the docs I think I found the problem. In Unity 2021.1.28f1, which I use, the .NET version is apparently lower than what Nethereum was compiled against. Looking at the docs, the constructor Nethereum tries to call got added with version 4.7.2, resulting in my project not being able to find it. It's hard to find out which .NET version that Unity version is using, but if assemblies for 4.6 could be built as well, it will most likely work.
[4.7.1 docs](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes?view=netframework-4.7.1#constructors)
[4.7.2 docs](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes?view=netframework-4.7.2#constructors)

**Comment by juanfranblanco** [comment]
Sure, I will make a build for those too. I was hoping we won't need them now.

**Comment by Cherden** [comment]
Hi, where can I find them? Release [4.11.0](https://github.com/Nethereum/Nethereum/releases/tag/4.11.0) still only has net4.7.2 dlls, resulting in the same error.

**Comment by juanfranblanco** [comment]
Included now https://github.com/Nethereum/Nethereum/releases/tag/4.11.0

**Comment by Cherden** [comment]
Works, thanks @juanfranblanco
