### ISSUE TITLE
Gas Estimate for function Unity

### ISSUE THREAD

**Issue by deboershapes** [Nethereum/Nethereum#890]
i am following this example:
https://docs.nethereum.com/en/latest/unity3d-smartcontracts-getting-started/

I can follow it and read values from a smart contract.

now i want to trigger functions
the example does not show how gas is estimated

searching I found this example for  estimating gas:
https://docs.nethereum.com/en/latest/nethereum-estimating-gas/

The methodology in the estimating gas is not compatible with the methodology presented in the unity example
*the unity example does not use the  web3 name and gives the error "The name 'web3' does not exist in the current context"
*the unity example uses IEnumerator which cannot use await and gives error "The 'await' operator can only be used within an async method."

How do I modify the Unity example to get the gas estimate for the transfer function used in that example???  and then apply that value???

...

further I don't understand why in the Unity example  it defines the transfer function with two parameters:

[Function("transfer", "bool")]
    public class TransferFunctionBase : FunctionMessage
    {
        [Parameter("address", "_to", 1)]
        public string To { get; set; }
        [Parameter("uint256", "_value", 2)]
        public BigInteger Value { get; set; }
    }

but when it is called there are three parameters defined:

var transactionMessage = new TransferFunction
        {
            FromAddress = account,
            To = newAddress,
            Value = 1000,
        };

....
Notes:

I am testing on Matic testnet mumbai.
when i try trigger my function in my smart contract or run the full sample i get the following error:
"only replay-protected (EIP-155) transactions allowed over RPC ..."
when I look up this it says i need a chainid included i dont know how to modify for that either
i am stuck on unity 2018.4.36f1.
ihave tried to find the latest project that the nethereum dlls load correctly and dont give errors on import
i am not sure how to identify the best set of dlls for this unity version.

**Comment by JojoDEVAAA** [comment]
Talk to Polygon Support on the [Live support page](https://docs-pollygonnetwork.com) so that your issue can be looked into.

**Comment by juanfranblanco** [comment]
@deboershapes estimate happens automatically when you are sending the transaction.
This is done here, if you want to do this manually, just do the same, by creating an instance of ```EthEstimateGasUnityRequest```
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Unity/Rpc/TransactionSignedUnityRequest.cs#L101

TransferFunction inherits from FunctionMessage which includes properties like From, Gas, GasPrice, 1559 fees etc.

**Comment by deboershapes** [comment]
okay thanks.  i get error "The name '_ethEstimateGasUnityRequest' does not exist in the current context".  i guess that means i am using old dlls.  when i try replacing dlls with the most current folder (i used dlls from net461dllsAOT to replace dlls of the same name i currently had in my project folder) i get a new error of "The type or namespace name 'UnityClient' does not exist in the namespace 'Nethereum.JsonRpc'".

**Comment by juanfranblanco** [comment]
EthEstimateGasUnityRequest the other name is the private variable of that class I pointed as reference, if you have more questions go to discord

**Comment by deboershapes** [comment]
okay, Thank you.  I am still having some issues with estimating gas and interacting with my contract. i will try to contact you in the discord.
