### ISSUE TITLE
Function decoder fails, System.OverflowException

### ISSUE THREAD

**Issue by aliveli186** [Nethereum/Nethereum#891]
https://bscscan.com/tx/0xd12766dd4c896939f10530d3a6ae6649b3d85ec5dabfe83a1921a1df97e78417

The above transaction's input fails to decode with error:
`System.OverflowException: 'Value was either too large or too small for an Int32.'`

`var function = new SwapExactTokensForTokensFunction().DecodeInput("0x38ed1739040000000000000000ae6f6f5dcaf609330000000000000001719f97aecc773bce0108fa5bea20e2b5bb4a92fba64570bb114880a59a0bb800000000000000000000000000024ef3ee5c00017cd0280ec5ca2c016daabfefa17f74ef174c38ce09c4000000000000000000071a6c9dc71974392a0000b11e437d87bd6c8bcee94d6bdaf4f0648fbbe28f09c40000000000000000000122a8a401a282cfc20101086f49825910c9dc3067253989869bbb93624fea07d000000000000000000000b514ea6b08641ec30055d398326f99059ff775485246999027b3197955");
`

Function:
```
[Function("swapExactTokensForTokens", "uint256[]")]
public class SwapExactTokensForTokensFunction : FunctionMessage
{
    [Parameter("uint256", "amountIn")]
    public virtual BigInteger AmountIn { get; set; }
    [Parameter("uint256", "amountOutMin", 2)]
    public virtual BigInteger AmountOutMin { get; set; }
    [Parameter("address[]", "path", 3)]
    public virtual List<string> Path { get; set; }
    [Parameter("address", "to", 4)]
    public virtual string To { get; set; }
    [Parameter("uint256", "deadline", 5)]
    public virtual BigInteger Deadline { get; set; }
}
```

**Comment by juanfranblanco** [comment]
@aliveli186 thanks I need to check this, as I am replicating it and the signature matches.

**Comment by aliveli186** [comment]
@juanfranblanco any progress?

**Comment by juanfranblanco** [comment]
The data is not encoded for that signature, so whilst the signature matches the rest of the data doesn't.
