### ISSUE TITLE
怎么实现批量转账

### ISSUE THREAD

**Issue by MarshalT** [Nethereum/Nethereum#892]
怎么实现批量转账

**Comment by juanfranblanco** [comment]
What do refer as a batch transfer? Do you want to sign multiple transactions separately and then send them all at once? If that is correct you can do something like https://github.com/Nethereum/Nethereum/blob/master/tests/Nethereum.Accounts.IntegrationTests/BatchTests.cs#L27-L33
But you will need EthSendRawTransaction instead, although you may not get much of a performance improvement.
