### ISSUE TITLE
Scan 100,000 wallets and get notified after receiving coins

### ISSUE THREAD

**Issue by mahanamiri** [Nethereum/Nethereum#894]
Hello,
I have a question.
I have 100,000 wallet addresses and I want to be notified immediately if a token is deposited into it, like a webhook / event listener or something like that.
Is there a way that is basic and we can do it? Like wallet applications, in the past I used to regularly query and compare transactions, but this is not good at all.

Example: 
`https://api.trongrid.io/v1/accounts/{address}/transactions/trc20?only_confirmed=true&contract_address=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t&only_to=true&limit=200`

for each address

**Comment by juanfranblanco** [comment]
if you have 100,000 wallet addresses the best thing will be to listen to all the erc20 (all contracts) transfers using the logProcessor and then filter for receiver if matches your wallet addresses. This won't be an event you need to do it yourself.

**Comment by juanfranblanco** [comment]
some thing like this -> http://playground.nethereum.com/csharp/id/1034

**Comment by mahanamiri** [comment]
Thank you, I think the same, but I thought there was a better way, like a webhook.
A few questions arose for me based on the example sent.
If possible, please explain this part to me more:
```
   toBlockNumber: new BigInteger(3146690),
            cancellationToken: cancellationToken,
            startAtBlockNumberIfNotProcessed: new BigInteger(3146684));
```
Also, is it possible to be limited to a specific contract?

And what should we do if we lose the process due to disconnection or any other error...

Block number confuses me more...

**Comment by juanfranblanco** [comment]
http://playground.nethereum.com/csharp/id/1036 one contract one event..

The log processor if configured will save your progress, so it will start again at the same block.


toBlockNumber <-- if not set it will continue forever to the latest
startAtBlockNumberIfNotProcessed <-- your starting block

**Comment by mahanamiri** [comment]
Thank you, it was a great help.

**Comment by mahanamiri** [comment]
And as a last question, Does anyone know if connection to TRON will work with Nethereum?
If the answer is yes, where can I find the connection URL?

**Comment by juanfranblanco** [comment]
Hi if you need any more help, please jump to discord issues are only for bugs

**Comment by juanfranblanco** [comment]
No, Tron has different rpcs even if it is a clone. But ask them if it is compatible with Ethereum / EVM it might have changed.
