### ISSUE TITLE
invalid sender: eth_sendRawTransaction using Ledger when ChainID > 109

### ISSUE THREAD

**Issue by MarcusJ42** [Nethereum/Nethereum#896]
## Expected Behavior
Transaction succeeds and application exits with code 0

## Current Behavior
'invalid sender: eth_sendRawTransaction' exception is thrown.

Further testing:

109 is the largest ChainID I can get to work. I actually encounter a different error using 110 - I get a 'System.IndexOutOfRangeException: 'Index was outside the bounds of the array.' on the SendTransactionAsync(txnInput) line rather than the invalid sender: eth_sendRawTransaction exception I've been seeing with large ChainID's.

## Possible Solution
I encountered something similar in ethers.js recently - specifically with ChainID's > 111. 

There was an open issue for it with a proposed solution that can be found here. The issue seems eerily similar here - with the breaking point being a ChainID of 110 in the case of Nethereum.

https://github.com/ethers-io/ethers.js/pull/2911

## Steps to Reproduce
```
        var rpcClient = new RpcClient(new Uri("http:/some-ip:some-port/ext/bc/some-blockchain-id/rpc"));
        var web3 = new Web3(rpcClient);
       

        var ledgerManager = await LedgerFactory.GetWindowsConnectedLedgerManagerAsync().ConfigureAwait(false);
        var signer = new ExternalAccount(new LedgerExternalSigner(ledgerManager, 0), 1515);
        await signer.InitialiseAsync().ConfigureAwait(false);
        signer.InitialiseDefaultTransactionManager(rpcClient);

        var txnInput = new TransactionInput();
        txnInput.From = "0x0....some-address";
        txnInput.To = "0x0....some-address";
        txnInput.Gas = new HexBigInteger(50000);
        txnInput.GasPrice = new HexBigInteger(50000000000);
        txnInput.Value = new HexBigInteger(Web3.Convert.ToWei(500));

       await signer.TransactionManager.SendTransactionAsync(txnInput).ConfigureAwait(false); <---exception thrown
```

## Context (Environment)
I've encountered this specifically with a local development instance of Avalanche's SubnetEVM. It works fine if the ChainID is less than 110.

**Comment by juanfranblanco** [comment]
Thanks @MarcusJ42 Ill have a look

**Comment by juanfranblanco** [comment]
@MarcusJ42 check the latest commit.
