### ISSUE TITLE
[BUG] Nethereum.UI.Blazor not 100% compatible with Milkomeda Network

### ISSUE THREAD

**Issue by Mercurial** [Nethereum/Nethereum#897]
It seems like `Nethereum.UI.Blazor` that provides blazor component and functionality to connect / interact with evm chains via Metamask is not 100% compatible with the `Milkomeda` network. Although it uses Hyper Ledger Besu for the nodes.

More information about Milkomeda: https://dcspark.github.io/milkomeda-documentation/cardano/for-developers/configuring-metamask-for-devs

Example non working code running inside a blazor web assembly app:

```csharp
if (_ethereumHostProvider is null) return;
var connectResult = await _ethereumHostProvider.CheckProviderAvailabilityAsync();
await _ethereumHostProvider.EnableProviderAsync();

var web3 = await _ethereumHostProvider.GetWeb3Async();

web3.TransactionManager.UseLegacyAsDefault = true;
web3.TransactionManager.EstimateOrSetDefaultGasIfNotSet = false;
web3.TransactionManager.CalculateOrSetDefaultGasPriceFeesIfNotSet = false;

var accountAddress = web3.TransactionManager.Account != null ? web3.TransactionManager.Account.Address :
                await _ethereumHostProvider.GetProviderSelectedAccountAsync();

Console.WriteLine("Connected Account: {0}", accountAddress);

var balance = await web3.Eth.GetBalance.SendRequestAsync(accountAddress);
Console.WriteLine($"Balance in Wei: {balance.Value}");

var etherAmount = Web3.Convert.FromWei(balance.Value);
Console.WriteLine($"Balance in Ether: {etherAmount}");
var currentNonce = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(accountAddress,
BlockParameter.CreatePending());
Console.WriteLine("Nonce {0}", currentNonce);

var abi = await HttpClient.GetStringAsync("abi.json");

var nonce = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(accountAddress);
var gasPrice = await web3.Eth.GasPrice.SendRequestAsync();
var time = DateTimeOffset.Now.ToUnixTimeSeconds();

Console.WriteLine("Nonce: {0}", nonce);
Console.WriteLine("Gas Price: {0}", gasPrice);
Console.WriteLine("Timestamp: {0}", time);

var contract = web3.Eth.GetContract(abi, "0xCA77372a728C09610BCf68a47C71c419888b380D");
var retrieveFunction = contract.GetFunction("retrieve");
var storeFunction = contract.GetFunction("store");
var gas = await storeFunction.EstimateGasAsync(time);
var data = storeFunction.GetData(time);

Console.WriteLine("Estimate Gas: {0}", gas);

var tx = new LegacyTransaction(
"0xCA77372a728C09610BCf68a47C71c419888b380D",
Nethereum.Util.UnitConversion.Convert.ToWei(0),
nonce,
gasPrice,
gas,
data);

Console.WriteLine("Test Store: {0}", data);
Console.WriteLine("Unsigned Raw Tx: {0}", $"0x{tx.GetRLPEncoded().ToHex()}");

var txReceipt = await web3.Eth.TransactionManager.SendTransactionAndWaitForReceiptAsync(new TransactionInput(
    data,
    "0xCA77372a728C09610BCf68a47C71c419888b380D",
    accountAddress,
    gas, gasPrice,
    new HexBigInteger(Nethereum.Util.UnitConversion.Convert.ToWei(0))));

Console.WriteLine("TxHash: {0}", txReceipt.TransactionHash);
Console.WriteLine("Fee: {0}", Nethereum.Util.UnitConversion.Convert.FromWei(txReceipt.GasUsed.Value *
txReceipt.EffectiveGasPrice.Value));
Console.WriteLine("Retrieve: {0}", await retrieveFunction.CallAsync<int>());
```
The moment the code reaches this line:

```csharp
var gas = await storeFunction.EstimateGasAsync(time);
```

It gives this error

<img width="1902" alt="image" src="https://user-images.githubusercontent.com/585569/201486231-15b77b41-1ccf-4a65-8ac4-c83893ccaf1e.png">

then when I comment that part of the code and just provide a static gas limit amount it errors at this line:

```csharp
Console.WriteLine("Retrieve: {0}", await retrieveFunction.CallAsync<int>());
```
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/585569/201486340-fdc6e606-459d-4e40-8640-c949d042684a.png">

Currently my work around is to provide a readonly provider and call those functions in the context of the read only provider.

```csharp
var readOnlyWeb3 = new Web3("https://rpc-devnet-cardano-evm.c1.milkomeda.com/");
```

So far I've been able to make it work with this work around.

Also without a work around it works 100% in a `Console` application.

Thanks for reading!

**Comment by Mercurial** [comment]
more details about this issue: https://github.com/dcSpark/milkomeda-c1-evm-passive/issues/16

**Comment by juanfranblanco** [comment]
@Mercurial Thanks, it seems that you have found the issue

**Comment by Mercurial** [comment]
> @Mercurial Thanks, it seems that you have found the issue

hey thanks for the reply, I added a PR to fix the issue on Nethereum side: https://github.com/Nethereum/Nethereum/pull/898

🙏🏻

**Comment by juanfranblanco** [comment]
@Mercurial  as per the PR comment, I have added the default serialisation settings that exclude nulls, this is aligned with all the nethereum rpc calls, so it fits better https://github.com/Nethereum/Nethereum/commit/585eafed4538a89a5ec41db401e098e9e5547de1
