### ISSUE TITLE
custom contract method balanceOf(account) failing

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#9]
I have a standard token contract which has a balanceOf method which takes an address as an argument and returns a uint256.

When I call it using `balanceOfFunction.CallAsync<uint>(account);` it throws exception with some unrelated error message.  When checking the JSON comms with wireshark I can see geth responded with `"error":{"code":-32602,"message":"Invalid address length, expected 40 got 4 bytes"}}`

**Comment by juanfranblanco** [comment]
Check this https://github.com/Nethereum/Netherum.Maker/tree/master/Nethereum.ERC20.Sample. It uses the Standard Token, and my "tests" work..

**Comment by slothbag** [comment]
Thanks.  The only difference I can see was I was using uint and your example is using ulong, however that did did resolve the issue.  

I wonder if this is another geth 1.3 vs 1.4 bug?  i'll do a side by side comparison of the JSON data from Web3.js to Nethereum.. see if there is a clue there.

**Comment by slothbag** [comment]
So the JSON data hex is pretty much the same between Nethereum and Web3.js, apart from Nethereum including the nulls but thats ok.

I did spot one difference, it web3.js when doing successive calls it retains the same HTTP connection for all of them.  When doing multiple calls from Nethereum it breaks them up into multiple requests with some EOF errors at the end of each.

e.g.
```
{"id":1,"jsonrpc":"2.0","method":"eth_getBalance","params":["223aea5cf8c5a21859171edb2d01d2ceab033678","latest"]}
HTTP/1.1 200 OK
Content-Length: 55
Content-Type: application/json

{"jsonrpc":"2.0","id":1,"result":"0x8ac7230489e80000"}
HTTP/1.1 200 OK
Content-Length: 58
Content-Type: application/json

{"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}
```

**Comment by slothbag** [comment]
Nope, I just tried making the balanceOf a single call on its own and it still gives invalid address length error message

**Comment by slothbag** [comment]
Found the problem.. it IS all the null values.  {"from":null, "gas":null, "gasPrice":null,"value":null} when I try in CURL I get the error. When I remove the null properties the call succeeds.

Not sure how the tests are passing??

**Comment by juanfranblanco** [comment]
It might be due to different versions as you said, including a formatter to exclude nulls will fix that.

**Comment by slothbag** [comment]
Do you have an example on "including a formatter" I can refer to?

**Comment by slothbag** [comment]
I seem to have gotten around the null property issue See #11

Now i'm getting Arithmetic overflow error :(
