### ISSUE TITLE
Issue with JSON parameter input for await ethGetBalance.SendRequestAsync ?

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#90]
Issue with JSON parameter input for await ethGetBalance.SendRequestAsync ?

In the code below passing data works passing jq does not work.  For all other calls (web3 calls), both passing jq type parameter and formdata both work.  

I tried to debug code, but right at await the call @sendasync fails only for ethBalance call.

since passing formdata works for ethGetBalance, it probably is something else?

```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
var data = new FormData();
data.append("accountId", "0x5D8f066440aE6E123718091d29FF9fE0F821E196");
var jq = "{'accountId':'0x5D8f066440aE6E123718091d29FF9fE0F821E196'}";
var xhr = new XMLHttpRequest();
//xhr.withCredentials = true;
xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});
xhr.open("POST", "http://localhost:53310/api/v1/basicfns/GetAccountBalance");
xhr.setRequestHeader("cache-control", "no-cache");
  xhr.send(data); ///////////fails when jq is sent
</script>
```

**Comment by juanfranblanco** [comment]
Thanks Ill have a look.

**Comment by juanfranblanco** [comment]
Tested using the rpc EthGetBalance on both parity and geth and I had no problems. Using both an account number and an account number + blockNumber.

**Comment by ushakrishnan** [comment]
Did you pass in parameters as formdata for json?   Formdata as input works.  Only JSON does not.

For some reason, formdata works but JSON gives CORS issue.  On my end, all controllers have same setup on my end, so could not understand why only EthGetBalance will give CORS error at SendAsync while web3 calls do not.  I will check my code again, if you had no issues passing JSON successfully and had no issues.  Thank you for checking.

**Comment by juanfranblanco** [comment]
Have you configured geth for cors? --rpccorsdomain "*"

**Comment by ushakrishnan** [comment]
Yes, and web3 functions work. I think I may have made a mistake, debugging now.  I will close this issue and will reopen it, if the issue persists after I fix my bug (I do have a bug that I just found!!).  Thank you
