### ISSUE TITLE
我发送我的Token 但是失败了

### ISSUE THREAD

**Issue by MarshalT** [Nethereum/Nethereum#904]
https://ftmscan.com/tx/0x8ca0fabe6b8aac665e8339c55f9a2daa4e9c8409c7988e6e4a6f5aefbd5e2c9e
![image](https://user-images.githubusercontent.com/33778588/203570904-562a05ee-3c68-43ac-af15-df687dd64634.png)

**Comment by juanfranblanco** [comment]
Not enough information, and not a Nethereum issue, please ask in Discord
