### ISSUE TITLE
Polygon Mainnet giving invalid sender: eth_sendRawTransaction (Works for ethereum)

### ISSUE THREAD

**Issue by aliusman** [Nethereum/Nethereum#905]
Polygon Mainnet giving **_Invalid Sender_** Error where it works for Ethereum

## Expected Behavior
Send normal transactions just like Ethereum

## Current Behavior
Getting an error "**invalid sender: eth_sendRawTransaction**"

## Possible Solution
Not sure

## Steps to Reproduce
Running the following code 
```
var web3 = new Web3(account, UseMainNet ? Chain.Chain_api_Polygon_main : Chain.Chain_api_Polygon_testnet);
web3.TransactionManager.UseLegacyAsDefault = true; // I tried with and without this
var transaction = await web3.Eth
 .GetEtherTransferService()
 .TransferEtherAndWaitForReceiptAsync(_address, _amount);
return transaction.TransactionHash.ToString();
```
I also tried the following 
```
var transactionManager = web3.TransactionManager;
var a = await web3.Eth.ChainId.SendRequestAsync();
Console.WriteLine(a); // ChainId 137 which is correct for the Mainnet
var transactionInput = EtherTransferTransactionInputBuilder.CreateTransactionInput(_from, _address, _amount);
var rawTransaction = await transactionManager.SignTransactionAsync(transactionInput);
var txnHash = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync(rawTransaction);
Console.WriteLine(txnHash);
var txnReceipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txnHash);
return txnReceipt.TransactionHash.ToString();
```

## Context (Environment)
- The same exact code works fine for Ethereum, 
- Also the following works fine to get the correct balance of MATIC on an address
```
await web3.Eth
  .GetBalance
  .SendRequestAsync(_address)
```

## Detailed Description
I looked through the old issues logged here but none of them actually solve the problem

## Possible Implementation
I am not sure

**Comment by juanfranblanco** [comment]
Are you putting the chainId when creating your Account? new Account(pkey, chainId)

**Comment by aliusman** [comment]
> Are you putting the chainId when creating your Account? new Account(pkey, chainId), although this should put automatically if not set.
Hey @juanfranblanco , yes I am, Also when I run this before sending the transaction, it gives me the ID 137 which is the correct ChainId for Polygon Mainnet
```
var chainId = await web3.Eth.ChainId.SendRequestAsync();
Console.WriteLine(chainId);
```

**Comment by juanfranblanco** [comment]
hmm weird as invalid_sender is normally due to an invalid chainId, when not set or when using legacy / non legacy.

**Comment by aliusman** [comment]
@juanfranblanco  I might be doing that wrong, the way I am loading the account is the following 

`account = new Nethereum.Web3.Accounts.Account(PvtKey, Nethereum.Signer.Chain.MainNet);`

Is this the correct way?

**Comment by juanfranblanco** [comment]
Ahh yes you are doing it wrong, the Nethereum.Signer.Chain.MainNet is 1 as it refers to the Ethereum mainnet

**Comment by aliusman** [comment]
Ah so simple yet I made it complicated, thank you so much, yeah that is set to 1, for some reason they await web3.Eth.ChainId.SendRequestAsync(); call returns 137 so I thought maybe it is converting it somehow, I added 137 and it works. Thanks for that @juanfranblanco I will close the issue as it's not an issue

**Comment by aliusman** [comment]
appreciate your help

**Comment by juanfranblanco** [comment]
Yes, if you don't put your chainId it will get it from the node, and set it. But if already set, it will use that, as this prevents you from putting the wrong url and sending a txn. (Also saves a call)
