### ISSUE TITLE
Error: Could not load signature of NBitcoin.Protocol.Message:GetArrayPool due to: Could not load file or assembly

### ISSUE THREAD

**Issue by JavinYang** [Nethereum/Nethereum#907]
Importing netStandardUnityCommonAOT into unity generates multiple errors. How can I solve these problems?

Error: Could not load signature of NBitcoin.Protocol.Message:GetArrayPool due to: Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>

Error: Could not load signature of System.Text.ValueStringBuilder:.ctor due to: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>

Unloading broken assembly Assets/Plugins/NBitcoin.dll, this assembly can cause crashes in the runtime

Unloading broken assembly Assets/Plugins/Microsoft.Extensions.Logging.Abstractions.dll, this assembly can cause crashes in the runtime

MissingMethodException: void System.Security.Cryptography.Rfc2898DeriveBytes..ctor(byte[],byte[],int,System.Security.Cryptography.HashAlgorithmName)
Demo.Start () (at Assets/Demo.cs:14)

**Comment by juanfranblanco** [comment]
Check the UnityTemplate this uses NBitcoin, but i recommend for NBitcoin to use the Net472 version if netstandard does not work for you.

Please use discord for questions
