### ISSUE TITLE
I don't understand why using EstimateGasAsync requires using an account with a balance.

### ISSUE THREAD

**Issue by JavinYang** [Nethereum/Nethereum#908]
The following code works normally
```
       var account = new Account("Account key for remaining balance", 12345);
        string contractAddress = "0x52CC36a004E05a397089edc90A97ccC0D05C55f1";

        Web3 web3 = new Web3(account, "http://127.0.0.1:8545");
        web3.TransactionManager.UseLegacyAsDefault = true;

        var transferHandler = web3.Eth.GetContractTransactionHandler<TransferFunction>();
        var transfer = new TransferFunction()
        {
            To = "0xEa79Ee3aE79900836CE3Ee075766c9038f064C4c",
            TokenAmount = 100
        };

        var estimate = await transferHandler.EstimateGasAsync(contractAddress, transfer);
        Console.WriteLine(estimate.Value);
```
But when I create a new address with no balance, it will fail: **invalid opcode: INVALID: eth_estimateGas**
```
     var account = new Account("new Account key", 12345);
```
I don't know why Estimate Gas needs an account. Isn't this gas constant?
Does it return different quantities based on different accounts?
Does it cost gas fee to call this function?

**Comment by juanfranblanco** [comment]
It fails when making the estimation as it the evm requires you to have some balance.
It does not cost anything to estimate gas. 
You can estimate with another account which has some ether.

Also Can you please use discord for questions, thanks.
