### ISSUE TITLE
How to obtain a finalized block?

### ISSUE THREAD

**Issue by JavinYang** [Nethereum/Nethereum#909]
<img width="1027" alt="截屏2022-12-01 19 35 06" src="https://user-images.githubusercontent.com/16144271/205042878-dc8ec0bd-caf6-47d2-9477-3f4deab79a11.png">

Is there a way to obtain the finalized block?

**Comment by juanfranblanco** [comment]
It is part of the BlockParameter as per the others https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/Eth/DTOs/BlockParameter.cs#L15
