### ISSUE TITLE
All WebSocket JsonRpc calls have id=1, performance issue?

### ISSUE THREAD

**Issue by aliveli186** [Nethereum/Nethereum#910]
All WebSocket JsonRpc calls have id=1 as can be seen on the image below.
Not that it is a bug but it means each request must wait for it's response to arrive before sending the next request, which may not be desired if fast execution is wanted.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/8914034/205320438-3905c37b-5abe-4857-a7a0-f6ac18455f3f.png">

**Comment by juanfranblanco** [comment]
WebSocket requests are synchronous, WebSocketStreaming is not so a new guid is created if not passed as a parameter a value https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.Client/Streaming/RpcStreamingRequestResponseHandler.cs#L23, but nevertheless a value can be set per each request if wanted 
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/Eth/EthGetBalance.cs#L49
