### ISSUE TITLE
keystore output - does it require address?

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum#92]
https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition 

indicates the non-requirement of address.  NEthereum keystore outputs with address.

Comments?

**Comment by juanfranblanco** [comment]
Yes, geth outputs the address so I am making it compatible.

**Comment by juanfranblanco** [comment]
Those clients will need it to simply list the addresses in the keystore without the need to decrypt the private key and retrieve it from there.

**Comment by ushakrishnan** [comment]
Thanks Juan, helpful
