### ISSUE TITLE
Attempt counter is being incremented before the log and waiting strategy

### ISSUE THREAD

**Issue by JoseAfonsoThreeSigma** [Nethereum/Nethereum#920]
The counter should only be incremented after the log and the apply of the waiting strategy. This starts the waiting strategy array in the index 1 instead of the index 0.

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/Eth/Blocks/LastConfirmedBlockNumberService.cs#L53:L68

**Comment by juanfranblanco** [comment]
Thanks @JoseAfonsoThreeSigma !

**Comment by juanfranblanco** [comment]
@JoseAfonsoThreeSigma doing another change whilst there, logging before waiting with readable +1 and attempt count for waiting increased after the wait.

**Comment by JoseAfonsoThreeSigma** [comment]
Awesome! That helps with the readability, thanks @juanfranblanco 😄
