### ISSUE TITLE
Anisaworld

### ISSUE THREAD

**Issue by Oda206** [Nethereum/Nethereum#921]

**Comment by juanfranblanco** [comment]
Hi, you did not provide any information, so it is closed now.

**Comment by Oda206** [comment]
I cannot login to my account for some reason and I didn't change my password I need help

**Comment by juanfranblanco** [comment]
What account, I think you are on the wrong GitHub

**Comment by Oda206** [comment]
And How is that ? Unless you hacked my account

**Comment by Oda206** [comment]
If find out you did

**Comment by Oda206** [comment]
What the hell are you talking about you're in my account think I'm f****** stupid you got to be f****** with me

**Comment by Oda206** [comment]
You think you can just take and take my money and get away with it

**Comment by Oda206** [comment]
You piece of s***

**Comment by Oda206** [comment]
Mr Juan Fucked Braco I gotchu.

**Comment by Oda206** [comment]
Say something

**Comment by Oda206** [comment]
It shows that you changed the name to from my profile name to yours

**Comment by Oda206** [comment]
So you f****** did hack my account

**Comment by Oda206** [comment]
And it's not closed you just changed everything on it you f****** hacker

**Comment by juanfranblanco** [comment]
What? Sorry I think you are confused.

**Comment by juanfranblanco** [comment]
Is this a problem with Nethereum? If not you are in the wrong GitHub repository. If it is, explain what is your Nethereum coding issue / bug. That type of language is not necessary.

**Comment by juanfranblanco** [comment]
Invalid submissions are closed.

**Comment by Oda206** [comment]
You hear me I'm calling the f****** police I have all your information

**Comment by juanfranblanco** [comment]
If you would explain your issue with Nethereum I would help you kindly, as you seem rather stressed, or you are trolling I don't kno. But if you continue this way you will be reported and blocked.

**Comment by juanfranblanco** [comment]
Locked and blocked as is spamming all the repos.

**Comment by juanfranblanco** [comment]
Reported to GitHub, as they might help him / her.
