### ISSUE TITLE
What are you talking about this is my account

### ISSUE THREAD

**Issue by Oda206** [Nethereum/Nethereum#923]
What account, I think you are on the wrong GitHub 

_Originally posted by @juanfranblanco in https://github.com/Nethereum/Nethereum/issues/921#issuecomment-1425147216_

**Comment by Oda206** [comment]
The hell are you talking about you're in my account kind of game trying to pull

**Comment by juanfranblanco** [comment]
That why are you posting this in Nethereum, you might be mistaking it for something else.

**Comment by juanfranblanco** [comment]
Closing this as it is not related to Nethereum.

**Comment by Oda206** [comment]
Do you changed it genius

**Comment by Oda206** [comment]
Because you changed it how could I be in your account that doesn't even
sound right

**Comment by Oda206** [comment]
I'm calling the police

**Comment by juanfranblanco** [comment]
Locked and blocked as is spamming all the repos.
