### ISSUE TITLE
Batch request only returns 1 batch item out of expected N

### ISSUE THREAD

**Issue by northwestnodes-eric** [Nethereum/Nethereum#926]
## Expected Behavior
Expect all batch items to be filled with a response. Any response will do at this point.

## Current Behavior
No matter the RPC endpoint, no matter the RPC server (self-hosted, third-party, etc.) we only see 1 out of (in this case) 32 items being filled.

## Possible Solution
N/A

## Steps to Reproduce
```
// building request
RpcRequestResponseBatch batchRequest = new RpcRequestResponseBatch();
foreach (ulong blockNumber in blockNumbers)
{
    var batchItem = new RpcRequestResponseBatchItem<EthGetBlockWithTransactionsByNumber, BlockWithTransactions>((EthGetBlockWithTransactionsByNumber)web3.Eth.Blocks.GetBlockWithTransactionsByNumber, web3.Eth.Blocks.GetBlockWithTransactionsByNumber.BuildRequest(new BlockParameter(blockNumber)));
    batchRequest.BatchItems.Add(batchItem);
}

// sending request
var batchResponse = await web3.Client.SendBatchRequestAsync(batchRequest); // returns 1 batch item with a BLockWithTransactions Response/RawResponse in it and 31 null
```

Here is a JSON serialized `List<ulong> blockNumbers` as an example:
```
[
  16004308,
  16004309,
  16004310,
  16004311,
  16004312,
  16004313,
  16004314,
  16004315,
  16004316,
  16004317,
  16004318,
  16004319,
  16004320,
  16004321,
  16004322,
  16004323,
  16004324,
  16004325,
  16004326,
  16004327,
  16004328,
  16004329,
  16004330,
  16004331,
  16004332,
  16004333,
  16004334,
  16004335,
  16004304,
  16004305,
  16004306,
  16004307
]
```

## Context (Environment)
Commercial project seriously hampered by this limitation. When following the example code for RPC batch requests, we only see 1 out of N batch items filled. The rest is null. The null items do not indicate an error (HasError = false).

## Detailed Description
N/A

## Possible Implementation
N/A

**Comment by northwestnodes-eric** [comment]
Serialized batch response as a sanity check. The request messages are filled with the block numbers, yet no responses.
[rawResponse (2).txt](https://github.com/Nethereum/Nethereum/files/10767397/rawResponse.2.txt)

**Comment by juanfranblanco** [comment]
you need a different id per request

**Comment by juanfranblanco** [comment]
```web3.Eth.Blocks.GetBlockWithTransactionsHashesByNumber.BuildRequest(new BlockParameter(new HexBigInteger(i)), i)```
as per integration test
