### ISSUE TITLE
SignTypedDataV4 produces incorrect results

### ISSUE THREAD

**Issue by pingu2k4** [Nethereum/Nethereum#928]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our discord channel first. [Discord](https://discord.gg/u3Ej2BReNn )

I have been scratching my head over this all day, but it appears that there is an issue with some types of data with TypedDataV4. I have tried structuring everything as structs, as shown in the docs and also by providing JSON. I was getting identical results within Nethereum, however they were different to what the expected signature was.

After a lot of chasing answers, and reading through past issues several times, I decided to replicate the experiment performed by the poster in #841. Using the same methodology, I ran a [JS Fiddle](https://codesandbox.io/s/typed-data-sample-forked-ni8mh4?file=/src/index.js) with my typed data example. The hash I get back from that is `4f08a7bb9d951d28787f2103ccb0e018bce02fbf08819953942ea013ccf208d5`.

## Expected Behavior
I would expect getting the hash the equivalent way with Nethereum to return the same result - `4f08a7bb9d951d28787f2103ccb0e018bce02fbf08819953942ea013ccf208d5`.

## Current Behavior
Running the following C#, the result is different:

```csharp
var data = "{ types: { EIP712Domain: [ { name: \"name\", type: \"string\" }, { name: \"version\", type: \"string\" }, { name: \"chainId\", type: \"uint256\" }, { name: \"verifyingContract\", type: \"address\" } ], Mail: [ { name: \"to\", type: \"Person[]\" }, { name: \"contents\", type: \"string\" } ], Person: [ { name: \"name\", type: \"string\" }, { name: \"wallets\", type: \"address[]\" } ] }, domain: { name: \"Ether Mail\", version: \"1\", chainId: 1, verifyingContract: \"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\" }, primaryType: \"Mail\", message: { to: [ { name: \"Bob\", wallets: [ \"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\", \"0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57\", \"0xB0B0b0b0b0b0B000000000000000000000000000\" ] } ], contents: \"Hello, Bob!\" } }";

var typedDataRaw = TypedDataRawJsonConversion.DeserialiseJsonToRawTypedData(data);

var signer = new Eip712TypedDataSigner();
var encodedData = signer.EncodeTypedDataRaw(typedDataRaw);
var hashBytes = new Sha3Keccack().CalculateHash(encodedData);
var hashHex = hashBytes.ToHex().RemoveHexPrefix();
Console.WriteLine(hashHex);
```
The result from this, is `a7f60314a32adc242676f7264d7246d13f70989540ce0584605f811c69556bf7`. Because of this, our signatures are always incorrect.

## Possible Solution
I have no idea sorry. However performing the same steps with the JSON from issue #841 gets the correct result, so its a different, yet similar issue to what was posted there.

## Steps to Reproduce
Run the JS Fiddle posted in top section, and compare that to result of running the C# code in Current Behaviour section.

## Context (Environment)
Currently blocked by this in my project, can't find an alternative way to proceed.

**Comment by pingu2k4** [comment]
I've put more effort into showing that there is an issue - it was late last night sorry.

Take this code sandbox, originally written by the auther of #841. https://codesandbox.io/s/typed-data-sample-cqp7kw?file=/src/index.js
841 is fixed, and the C# code for that generates the exact same result since having been fixed. They both produce `a7f60314a32adc242676f7264d7246d13f70989540ce0584605f811c69556bf7` as the result.

I have taken the same code, and replaced the object with my data. This can be found here: https://codesandbox.io/s/typed-data-sample-forked-ni8mh4?file=/src/index.js

Now, I have also produced some minimal C# containing the JSON for these 2 objects and matching code as the JS. (here: https://dotnetfiddle.net/dBFzJF). The first one matches the the first JS example, the one provided in issue #841. The second however, whilst the JSON object exactly matches the object in the second JS example, they provide different results. The JS outputs `4f08a7bb9d951d28787f2103ccb0e018bce02fbf08819953942ea013ccf208d5`, and C# produces `a7f60314a32adc242676f7264d7246d13f70989540ce0584605f811c69556bf7`.

**Comment by juanfranblanco** [comment]
Using TypedData

```csharp

using System;
using System.Text;
using System.Collections.Generic;
using Nethereum.Signer.EIP712;
using Nethereum.Util;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.ABI.EIP712;
using Nethereum.Signer;
using System.Numerics;
using Nethereum.Hex.HexConvertors.Extensions;

///EIP-712: Ethereum typed structured data hashing and signing
///This example demonstrates how to create a compatible Typed data schema definition 
/// For more information about the standard check: https://eips.ethereum.org/EIPS/eip-712
public class TypedDataSigningUsingEIP712_V4
{
	static void Main(string[] args)
	{
		var signer = new Eip712TypedDataSigner();

		var typedData = GetOrderTypedDefinition();

		//The data we are going to sign (Primary type) mail
		var order = new Order
		{
			Trader = "0x7235d8d035c5ecd470f5a47bdfacf844ef1358c8",
			Side = 0,
			MatchingPolicy = "0x0000000000b92d5d043faf7cecf7e2ee6aaed232",
			Collection = "0x34d85c9cdeb23fa97cb08333b511ac86e1c4e258",
			TokenId = 0,
			Amount = 1,
			PaymentToken = "0x0000000000a39bb272e79075ade125fd351887ac",
			Price = 1000000000000000000,
			ListingTime = 1677201457,
			ExpirationTime = 1708737456,
			Fees = new List<Fee>(),
			Salt = BigInteger.Parse("176833519079950976564067085591514560244"),
			ExtraParams = "0x01".HexToByteArray(),
			Nonce = 0
		};

		//This type data is specific to the chainId 1
		typedData.SetMessage(order);
		typedData.Domain.ChainId = 1;
		var encoded = signer.EncodeTypedData(typedData);
		var hash = Nethereum.Util.Sha3Keccack.Current.CalculateHash(encoded);
		Console.WriteLine(hash.ToHex());

	}


	public static TypedData<Domain> GetOrderTypedDefinition()
	{
		return new TypedData<Domain>
		{
			Domain = new Domain
			{
				Name = "Blur Exchange",
				Version = "1.0",
				ChainId = 1,
				VerifyingContract = "0x000000000000ad05ccc4f10045630fb830b95127"
			},
			Types = MemberDescriptionFactory.GetTypesMemberDescription(typeof(Order), typeof(Fee),typeof(Domain)),
			PrimaryType = nameof(Order),
		};
	}


	[Struct("Order")]
	public class Order
	{
		[Parameter("address", "trader", 1)]
		public string Trader { get; set; }

		[Parameter("uint8", "side", 2)]
		public BigInteger Side { get; set; }

		[Parameter("address", "matchingPolicy", 3)]
		public string MatchingPolicy { get; set; }

	    [Parameter("address", "collection", 4)]
		public string Collection { get; set; }

		[Parameter("uint256", "tokenId", 5)]
		public BigInteger TokenId { get; set; }

		[Parameter("uint256", "amount", 6)]
		public BigInteger Amount { get; set; }

	    [Parameter("address", "paymentToken", 7)]
		public string PaymentToken { get; set; }

		[Parameter("uint256", "price", 8)]
		public BigInteger Price { get; set; }

		[Parameter("uint256", "listingTime", 9)]
		public BigInteger ListingTime { get; set; }

		[Parameter("uint256", "expirationTime", 10)]
		public BigInteger ExpirationTime { get; set; }

		[Parameter("tuple[]", "fees", 11, "Fee[]")]
		public List<Fee> Fees { get; set; }

		[Parameter("uint256", "salt", 12)]
		public BigInteger Salt { get; set; }

		[Parameter("bytes", "extraParams", 13)]
		public byte[] ExtraParams { get; set; }

		[Parameter("uint256", "nonce", 14)]
		public BigInteger Nonce { get; set; }
	}

	[Struct("Fee")]
	public class Fee
	{
		[Parameter("uint16", "rate", 1)]
		public BigInteger Rate { get; set; }

		[Parameter("address", "recipient", 2)]
		public string Recipient { get; set; }
	}

}


```

**Comment by pingu2k4** [comment]
Thanks for looking at it, and thanks for the alternative above! Due to the docs, that was how I tried it the first time around, and only tried JSON after that... (Json was more convenient to me as that's how I received the data).

**Comment by juanfranblanco** [comment]
Yes, deserialization was not picking the BigIntegers as it is a different approach.
