### ISSUE TITLE
NuGet Packages with wrong version numbers and wrong references

### ISSUE THREAD

**Issue by migoldfinger** [Nethereum/Nethereum#930]
I just want to  update (2023-03-20 10:51:00 UTC) my project with the new version for nethereum nuget packages.

Problem 1)
While the guthub repository releases states that the last version is 4.13.0 at Least
Nethereum.HdWallet, Nethereum.Json.Rpc.WebSocketClient, Nethereum.RPC.Reactive points to version 4.14.0

Problem 2)
Upgrade to Nethereum.HdWallet 4.14.0 is impossible since the referencess Nethereum.Merkle.Patricia with version (>= 4.14.0) simply does not exist. Sames goes for Nethereum.RPC.Reactive

**Comment by juanfranblanco** [comment]
@migoldfinger I am currently releasing, hence you have issues.

**Comment by migoldfinger** [comment]
Works fine now. Thanks
