### ISSUE TITLE
Overflow exception being thrown on TimePreferenceFeeSuggestionStrategy when last blocks fees had a value of 0 (only likely on local-dev chains)

### ISSUE THREAD

**Issue by JoseAfonsoThreeSigma** [Nethereum/Nethereum#932]
I'm having a problem calculating fees on new dev blockchains (using Anvil) where I have an array of `baseFeePerGas` with values of zero. Down the line, this results in suggested baseFee values so low, that the conversion from Double to Decimal in the line 238 results in an overflow exception.

One possible solution is to only deal with BigDecimals and avoid the casts between Double <-> Decimal in line 238. Lemme know if I can provide more details to help here. Cheers

https://github.com/Nethereum/Nethereum/blob/7746b6511a061db6ff057555488382f03d0d04fb/src/Nethereum.RPC/Fee1559Suggestions/TimePreferenceSuggestionStrategy.cs#L238

![image](https://user-images.githubusercontent.com/104689221/228312749-1b049928-e244-455b-9712-d21905a4da37.png)
![image](https://user-images.githubusercontent.com/104689221/228314913-155bf405-e5e9-4304-895c-d4b1efd06cb0.png)

**Comment by juanfranblanco** [comment]
Solved already
