### ISSUE TITLE
how to batch query token balance

### ISSUE THREAD

**Issue by rocheldebbrarmke** [Nethereum/Nethereum#934]
who can help me . i try use  https://github.com/Nethereum/Nethereum/blob/master/tests/Nethereum.Accounts.IntegrationTests/BatchTests.cs

but i not know how to write query token balance

**Comment by juanfranblanco** [comment]
Try this https://playground.nethereum.com/csharp/id/1066 it is a specific method to query all balances using all uniswap tokens
