### ISSUE TITLE
Possible regression in BigDecimal conversion from double

### ISSUE THREAD

**Issue by akovac35** [Nethereum/Nethereum#936]
I would like to report a possible regression with the following update

https://github.com/Nethereum/Nethereum/commit/fbaaef1e07ab398fc79711d5e72e5f4d71af8e6b#diff-5297525dd08f19132997301d55b76017dd82aff903298ee1a7fd38f23403c4fbR230

This update causes

`12111121212.121212d` to be converted to 
`12111121212.1212 big decimal`

This was not happening before the update. Not sure if this consequence was intended.

**Comment by juanfranblanco** [comment]
Yes it was done on purpose as it is more exact, we were getting errors in bigger values as the nature of double makes it inaccurate. 

See this SO for explanation https://stackoverflow.com/questions/7453900/c-sharp-double-to-decimal-precision-loss.

 I am thinking of using the last answer, but the best thing is to use decimals all the way and then convert it. I have to refactor some areas in Nethereum myself to ensure decimal is used always across.

**Comment by akovac35** [comment]
If the refactoring you mentioned is related to passing Ethereum values around, a good way to do it would be using BigInteger and Wei units, or BigDecimal and Ethereum units.

The conversion which you indicated is not precise either - I think the in-between step of converting to decimal should be avoided:

`12111121212.121212d` to be converted to
`12111121212.121212005615234375 decimal`

What are the design goals of the following method: `public static implicit operator BigDecimal(double value)`

To capture the original value as closely as possible?

**Comment by juanfranblanco** [comment]
No, I just use doubles on fee history rpc, nothing mayor. Like you said BigInteger and BigDecimal.. 
The original design goals was to have this as the closest conversion, but as doubles starts to be approximate and there were issues in some scenarios in which you will end in an overflow due to the conversion not being valid, so the intermediate conversion to Decimals removed any approximation and provided the safest solution.

Regarding not being precise is what you actually see in the debugger, the real number is what you see in the decimal.

**Comment by akovac35** [comment]
Regarding debugger comment - I raised this issue because my conversion tests failed, so this does not seem to be only debugger related.

I don't think conversion from double to BigDecimal should cause changes to mantissa precision (at least for the case I indicated), regardless if the double value is itself imprecise in a given context. And intermediate conversion to decimal causes the loss in mantissa precision.

May you please list the values which were causing problems for previous implementation of conversion between double and BigDecimal? I would just like to have an example to use for testing in case there exists another solution.

**Comment by juanfranblanco** [comment]
These were the big issues across others

  [Fact]
        public void ShouldPowDouble()
        {
            var value = BigDecimal.Pow((double)10,(double)27);
            Assert.Equal("1000000000000000000000000000", value.ToString());
        }

        [Fact]
        public void ShouldNotHangFromDouble()
        {
            var converted = (BigDecimal)double.Epsilon; // hangs
        }
