### ISSUE TITLE
BytesTypeEncoder incorrectly encodes an empty byte array (adds extra 32 zero bytes).

### ISSUE THREAD

**Issue by timaiv** [Nethereum/Nethereum#938]
BytesTypeEncoder incorrectly encodes an empty byte array (adds extra 32 zero bytes).

This leads to a long list of problems, ex : contract signatures (using keccak256) are also broken.

## Steps to Reproduce
```
contract TestEncode {
    function test(bool someBool, bytes memory someBytes) public view returns(bool) {
        return true;
    }
}
```

Generated using `Nethereum.Autogen.ContractApi`
```cs

    [Function("test", "bool")]
    public class TestFunctionBase : FunctionMessage
    {
        [Parameter("bool", "someBool", 1)]
        public virtual bool SomeBool { get; set; }
        [Parameter("bytes", "someBytes", 2)]
        public virtual byte[] SomeBytes { get; set; }
    }
```
```cs
var func = new TestFunction()
{
       SomeBool = true,
       SomeBytes = new byte[]{  }
 };

var encoded = "0x" + Convert.ToHexString(func.GetCallData()).ToLower();
```

## Expected Behavior
0x365a9d2f000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000

## Current Behavior
0x365a9d2f0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
## Possible Solution
Use same mechanism as in DynamicArrayTypeEncoder.

## Context (Environment)
```
<PackageReference Include="Nethereum.Web3" Version="4.13.0" />
<PackageReference Include="Nethereum.Autogen.ContractApi" Version="4.11.0" />
```

**Comment by juanfranblanco** [comment]
Oh thank you!! Forgot to say

**Comment by timaiv** [comment]
> Oh thank you!! Forgot to say

ETA?
Its crucial bug for us (signature verification problem). 2 months have passed.

**Comment by juanfranblanco** [comment]
I will do a release this week. Fix is in main.

**Comment by MorandiGonzalez** [comment]
> I will do a release this week. Fix is in main.

Hi Juan,

Any updates about release?
Thanks in advanse.
