### ISSUE TITLE
Multi Query batch using RPC 

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#946]
Integrate multiquery batch similar to the extension created here  https://gist.github.com/dlebee/75a052dd4e2cd630352e23b30a0a0387 by @dlebee

**Comment by andybn** [comment]
It is an essential feature ...

**Comment by juanfranblanco** [comment]
@andybn use multiquery with smart contracts until then, my plan is to make it very similar, so porting will be easy. The truth is that the smart contract approach is less expensive.

**Comment by juanfranblanco** [comment]
This is in the latest with added support to other batches as default in rpc

**Comment by dlebee** [comment]
> This is in the latest with added support to other batches as default in rpc

Hey, great news.

I would love to see a commit or PR or doc to see the change, I did look for it but maybe you have better pointers.

**Comment by juanfranblanco** [comment]
Check the release https://github.com/Nethereum/Nethereum/releases/tag/4.16.0
