### ISSUE TITLE
ENS service reverse resolve returns null address instead of null for expired ENS

### ISSUE THREAD

**Issue by ssa3512** [Nethereum/Nethereum#948]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our discord channel first. [Discord](https://discord.gg/u3Ej2BReNn )

## Expected Behavior
When reverse resolving an ENS address that is not registered or is expired, the call to `ReverseResolveAsync` returns null

## Current Behavior
When reverse resolving an ENS address, if the ENS has expired the resolved returns the null address instead of null

## Possible Solution

Check result for constant "0x0000000000000000000000000000000000000000" before returning and return null if match

## Steps to Reproduce

```cs
var web3 = new Web3($"https://eth-mainnet.g.alchemy.com/v2/{alchemyApiKey}");
var reverse = await web3.Eth.GetEnsService().ReverseResolveAsync("0x6cC4eAD03B6FDa979fA33b40546BA5D09C35396A");
```
## Context (Environment)

Displaying a reverse resolved ENS is a user friendly thing to do when working with addresses. There should not be a requirement on the consumer of the library to check the result for the null address as this is not a valid reverse resolution.

## Possible Implementation

Update [ReverseResolveAsync](https://github.com/Nethereum/Nethereum/blob/709130eeddecde78daabaf19c21ba13d5549ab07/src/Nethereum.Contracts/Standards/ENS/ENSService.cs#LL154C9-L160C10) to read
```cs
public async Task<string> ReverseResolveAsync(string address)
{
    var addressReverse = address.RemoveHexPrefix().ToLower() + REVERSE_NAME_SUFFIX;
    var fullNameNode = _ensUtil.GetNameHash(addressReverse).HexToByteArray();
    var resolverService = await GetResolverAsync(fullNameNode).ConfigureAwait(false);
    var resolved = await resolverService.NameQueryAsync(fullNameNode).ConfigureAwait(false);
    if (resolved == ENS_ZERO_ADDRESS)
    {
        return null;
    }
    return resolved;
}
```

**Comment by juanfranblanco** [comment]
Hi @ssa3512, 

This is common behavior in addresses as the 0 address is the default, in a similar way to BigIntegers defaulting to 0. There might be scenarios that the resolved address is the 0 address too.

**Comment by ssa3512** [comment]
> What I am trying to say that this should be handled at the user level

When doing an ENS reverse resolution from a service would the expectation not be to get back either a valid ENS or nothing?

The zero address is *not* an ENS address so you are effectively asking every consumer of this service to check for an invalid scenario. The point of a bigger ENS service wrapper seems to be to abstract away the contract calls behind ENS and return the expected values from the series of calls. The forward lookup contracts return a zero address if not registered but Nethereum returns null, and the majority of the time the reverse lookup service returns null. This is just an edge case in the way the contracts return if an address previously had a reverse address registered and no longer does.

I can write an extension method that wraps this functionality but I highly recommend reconsidering handling this at the library level as it is logic that every consumer of the library would need if they want to avoid invalid results.

**Comment by juanfranblanco** [comment]
Well the way that you will handle that is to check if that the resolve address matches the 0 address, returning a null will mean a breaking change for anyone that handles the return value as the 0 address and does not expect a null.

**Comment by juanfranblanco** [comment]
@ssa3512  Are you calling ReverseResolveAsync or ResolveAsync?

**Comment by ssa3512** [comment]
@juanfranblanco I am using `ReverseResolveAsync`: here's a minimal repro:

```cs
string rpcUrl = "[put your rpc url here]";

var web3 = new Web3(rpcUrl);
var ens = web3.Eth.GetEnsService();

var ecKey = EthECKey.GenerateKey();
var privateKey = ecKey.GetPrivateKeyAsBytes().ToHex();
var account = new Account(privateKey);

// fresh address, will never have reverse resolve
var revResolve1 = await ens.ReverseResolveAsync(account.Address); 

// vvd.eth
var revResolve2 = await ens.ReverseResolveAsync("0x0F0eAE91990140C560D4156DB4f00c854Dc8F09E"); 

// 0x6cC4eAD03B6FDa979fA33b40546BA5D09C35396A returns null address
var revResolve3 = await ens.ReverseResolveAsync("0x6cC4eAD03B6FDa979fA33b40546BA5D09C35396A");

Console.WriteLine(revResolve1 ?? "null value returned");
Console.WriteLine(revResolve2 ?? "null value returned");
Console.WriteLine(revResolve3 ?? "null value returned");
```

Output for this is:

```
null value returned
vvd.eth
0x0000000000000000000000000000000000000000
```
