### ISSUE TITLE
I did not found

### ISSUE THREAD

**Issue by tanderbold** [Nethereum/Nethereum#95]
Hi, i can't find this stuff:
1. backup wallet
2. import existing accounts (private keys) 
3. dump priv key from address
4. rename account (i can do this in ui)
5. get confirmations (how can i understand the transaction is succesful)

**Comment by juanfranblanco** [comment]
1. Backup wallet, you will need to this manually. Different Os, users, nodes will store a wallet in different places.
2. You can use Nethereum.KeyStore
3. You cannot dump a private key from an address (if you don't know it on the first place)
4. Rename an account? This is a parity specific functionality where a keystore file has a name  associated with it. This may be added on the newer releases, when different nodes might have separate / specific libraries.
5. http://ethereum.stackexchange.com/questions/319/what-number-of-confirmations-is-considered-secure-in-ethereum/793#793

**Comment by juanfranblanco** [comment]
I think this are very specific questions to some of your needs, maybe easier to go to gitter and chat

**Comment by tanderbold** [comment]
Thank you for your answer. I already created all needed stuff manually.

**Comment by juanfranblanco** [comment]
I am glad you got sorted already 👍
