### ISSUE TITLE
Feature: Allow to decode EventABI as a dynamic object

### ISSUE THREAD

**Issue by JuanuMusic** [Nethereum/Nethereum#958]
I'm facing this problem where I need to decode an event ABI, but with a dynamic object because I dont know the type at compile time.

I havent been able to find a way to do this with Nethereum today.
is it a good candidate for a feature? I can help build it.

**Comment by juanfranblanco** [comment]
i case you missed it

![image](https://github.com/Nethereum/Nethereum/assets/562371/4242b9fb-af2e-4542-82cc-96852e1077b1)

**Comment by JuanuMusic** [comment]
Hmm... thanks.. Now I need to figure out how to convert a ContractABI into an abi STRING.

Basiclaly, al my contract an events definitions are dynamic and known only at runtime, so I need to build everything on the fly.
Any pointer?

**Comment by juanfranblanco** [comment]
If everything is dynamic you will need the ABI string. As you are working fully not typed. So you will need to know what contract is that from and it's ABI.

**Comment by JuanuMusic** [comment]
I see!
Then how about we turn this ticket into a new feature?
Override the `ToString` method of the ABI objects (`ContractABI`,`EventABI`, `FunctionABI`, etc...) so that it returns the actual ABI string?

In my case it would be really helpful since I have the objec ts instances with the definitions.

**Comment by juanfranblanco** [comment]
If you have already instances with the definitions, you can use those to decode and check the events.

**Comment by juanfranblanco** [comment]
You have all this EventAbi extensions https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Contracts/Extensions/EventExtensions.cs

You can do somethign like this

var eventAbi = Event<TransferEventDTO>.GetEventABI();
		
		if(eventAbi.IsLogForEvent(log)){
			var transferEventDTO = eventAbi.DecodeEvent<TransferEventDTO>(log);
			Console.WriteLine(transferEventDTO.From);
			Console.WriteLine(transferEventDTO.To);
			Console.WriteLine(transferEventDTO.Value);
		}

**Comment by JuanuMusic** [comment]
But then again I need to know the EventDTO in advance (which I dont).
Maybe we need to add the `DecodeEventToJObject(log)` function?

**Comment by JuanuMusic** [comment]
Actually, I think I have just figured out how to solve it.

This is what Im doing now.
This lets me rogramatcally use the data.

```
          if (abi.IsLogForEvent(filterLog))
          {
              var p = abi.DecodeEventDefaultTopics(filterLog);
              if (p != null)
              {
                  Console.WriteLine($"Event {abi.Name} triggered");
              }
          }
```

**Comment by juanfranblanco** [comment]
![image](https://github.com/Nethereum/Nethereum/assets/562371/eee7f94a-6c75-423a-b1ac-b9edb4af5db8)

Added these too in the latest
