### ISSUE TITLE
Nethereum cannot read output arrays

### ISSUE THREAD

**Issue by foued1979** [Nethereum/Nethereum#959]
New Solidity functionalities enable smart contracts to return arrays as output parameters. However, Nethereum is currently reading only simple outputs; i.e. string, uint256, etc.

## Expected Behavior
If we look at the smart contract 0xba12222222228d8ba445958a75a0704d566bf2c8 on EtherScan, we can see that the function "getPoolTokens" **returns** 3 parameters:
`address[] tokens`
`uint256[] balances`
`uint256 lastChangeBlock`

Hence, when querying this function (e.g. with the poolId "0xa6f548df93de924d73be7d25dc02554c6bd66db500020000000000000000000e") we would expect to get an array of 2 token addresses, an array of 2 BigIntegers and a BigInt.

----
![image](https://github.com/Nethereum/Nethereum/assets/28772895/38f0e041-3b2e-4700-822c-ef795b14f74a)
----

## Current Behavior
(1) if we indicate in the FunctionOutputDTO that we expect an array type (e.g. address[]), the function call throws a System.AggregateException "Cannot dynamically create an instance of type System.String[]" because the array type is not supported for output parameters
(2) if we indicate that we expect a string instead of an array (either for an array of string or an array of BigInt), the code returns only zeros (i.e. "0/0/").

=> How do I know that my function is correct? I properly receive the `uint256 lastChangeBlock`

## Steps to Reproduce
The Balancer example has been provided above

**Comment by foued1979** [comment]
Error is coming from the ArrayTypeDecoder.DecodeStaticElement (for static elements), line 117, where `var decodedListOutput = (IList) Activator.CreateInstance(type)` is used; system cannot create an array without size being specified. Then, if using `Activator.CreateInstance(type, size)` we are facing the issue where the size is fixed and we cannot add elements in `DecodeAndAddElement`.

The code should be changed into
`var elementType = GetIListElementType(type);

			if (elementType == null)
                throw new Exception("Only types that implement IList<T> are supported to decoded Array Types");

			var decodedListOutput = (IList) Activator.CreateInstance(typeof(List<>).MakeGenericType(elementType));

			if (decodedListOutput == null)
				throw new Exception("Only types that implement IList<T> are supported to decoded Array Types");

			var currentIndex = 0;

            while (currentIndex < size)
            {
                var encodedElement = encoded.Skip(currentIndex * ElementType.FixedSize).Take(ElementType.FixedSize).ToArray();
                DecodeAndAddElement(elementType, decodedListOutput, encodedElement);
                currentIndex++;
            }

            return ToArray(decodedListOutput, elementType, size);`

Where
`private object ToArray(IList list, Type elementType, int size)
{
     var array = Array.CreateInstance(elementType, size);
            
     for (int i = 0; i < size; i++) array.SetValue(list[i], i);

     return array;
}`

**Comment by juanfranblanco** [comment]
How are you declaring the DTO / Struct in Nethereum?

**Comment by foued1979** [comment]
The output parameters were declared as arrays in the function DTO (address[] and uint256[]).

**Comment by juanfranblanco** [comment]
> The output parameters were declared as arrays in the function DTO (address[] and uint256[]).

No I mean can you copy and paste your csharp code

**Comment by foued1979** [comment]
The function DTOs are created dynamically (so nothing easily readable) at runtime based on the specifications of the function definitions. The function definition looks like:

<Function>
      <Reference>1</Reference>
      <Name>getPoolTokens</Name>
      <FunctionType>GetPoolTokens</FunctionType>
      <Constant>true</Constant>
      <InputParameters>
        <Parameter Alias="PoolId" Name="poolId" Type="bytes32" Order="1"></Parameter>
      </InputParameters>
      <OutputParameters>
        <Parameter Alias="Tokens" Name="tokens" Type="address[]" Order="1"></Parameter>
        <Parameter Alias="Balances" Name="balances" Type="uint256[]" Order="2"></Parameter>
        <Parameter Alias="LastChangeBlock" Name="lastChangeBlock" Type="uint256" Order="3"></Parameter>
      </OutputParameters>
    </Function>

The parameters are used to declare the properties of the function output DTO, with the corresponding ParameterAttribute (where type of parameter attribute is equal to the Type of the spec). The property of the C# class will be converted such as (for example): uint256 -> BigInteger, address -> string

**Comment by juanfranblanco** [comment]
Why don't just use the code generator

**Comment by juanfranblanco** [comment]
I am just getting my head around this.. so somebody has created an xml from an abi to later on generate this as contract definitions?. What project is this?

**Comment by juanfranblanco** [comment]
![demo-etherscan-codegen-balancer](https://github.com/Nethereum/Nethereum/assets/562371/f24570ad-abd5-4a93-89ee-064c90872d69)

**Comment by juanfranblanco** [comment]
Invalid issue, closing

**Comment by juanfranblanco** [comment]
@foued1979 Can you let me know if this some tool or third party service, and which one it is if so?

**Comment by foued1979** [comment]
> Why don't just use the code generator, that is why is there, instead of using your own custom.. just use the abi to generate your code instead of xml, you might be doing something wrong with your custom generator.
> 
> So make sure what you do generate is right ...

My code is 100% correct; it is not a third party, it is all developed by me for high frequency trading. I use my own ABI conventions to have my own contract ABIs, more flexible and able to read / write all type of contracts (whether EVM or not).
I was expecting the Nethereum code to be more flexible (i.e. not being too strongly typed when declaring parameters) => the modification I brought to the Nethereum code is (I believe) more flexible and is now working (enables to create fully custom ABIs).

**Comment by juanfranblanco** [comment]
You might have missed something 

![image](https://github.com/Nethereum/Nethereum/assets/562371/4ffca240-4e65-443e-9992-b8be77b6fd6e)

**Comment by juanfranblanco** [comment]
You don't need to be strongly typed either https://playground.nethereum.com/csharp/id/1070

**Comment by juanfranblanco** [comment]
But really cool regardless !! I hope is helping you

**Comment by juanfranblanco** [comment]
I got you know, so you are creating FunctionABIs etc from Xml instead the json ABI, or human readable  http://playground.nethereum.com/csharp/id/1068 
![image](https://github.com/Nethereum/Nethereum/assets/562371/28d18525-f804-4bea-b48f-c68432d27ea5)
There are extensions to deserialise to default to dynamic, json etc.. just have a look, all arrays are supported.

**Comment by juanfranblanco** [comment]
> In fact, I have created my own mapping with my own function names so that different contracts with same functionalities are interpreted in the same way by my code <=> for example, a swap, regardless of the signature or contract format, is understood as a swap by my code. Same as for any smart contract functionality (getBalance, allowance, getReserves, etc.).
> 
Ah excellent that was mainly the idea of the typed objects, that they can be reused across a Swap is a swap across many standards and GetBalance etc, now i see your point of using the custom xml as it is easier to onboard, ie does this system have x and y functionality.

I have TODO to use generators that will speed up the encoding / decoing, so that might help you in the future even if typed. 

> I have exchange / blockchain managers acting in parallel and managing pairs / tokens across different blockchains and exchanges, simultaneously, to detect DEX vs DEX arbitrage opportunities (within less than 1s for 2000 paths, approximately - and my ABI typology helps avoiding data collision when using RPC requests) => as you can imagine, I needed to have the lightest code as possible to have the code being straight to the point (and also flexible enough to onboard any future format - including digital assets).

Awesome, that is great. I would never have thought that will be still arbing opportunities.

**Comment by juanfranblanco** [comment]
Well if it helps on the dynamic

```csharp
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Threading.Tasks;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.ABI.FunctionEncoding;
using Nethereum.ABI.Model;
using Nethereum.Contracts;
using Nethereum.Web3.Accounts;
using Nethereum.Web3;
using Nethereum.Hex.HexConvertors.Extensions;
using Nethereum.Hex.HexTypes;
using System.Linq;


public class DynamicRebalancer
{

	public static async Task Main()
	{
		
		var web3 = new Web3("https://mainnet.infura.io/v3/ddd5ed15e8d443e295b696c0d07c8b02");

		var contract = web3.Eth.GetContract(@"
		[{'inputs':[{'internalType':'bytes32','name':'poolId','type':'bytes32'}],'name':'getPoolTokens','outputs':[{'internalType':'contract IERC20[]','name':'tokens','type':'address[]'},{'internalType':'uint256[]','name':'balances','type':'uint256[]'},{'internalType':'uint256','name':'lastChangeBlock','type':'uint256'}],'stateMutability':'view','type':'function'}]", "0xba12222222228d8ba445958a75a0704d566bf2c8");
	
		var getPoolTokensFunction = contract.GetFunction("getPoolTokens");
		var output = await getPoolTokensFunction.CallDecodingToDefaultAsync("0xa6f548df93de924d73be7d25dc02554c6bd66db500020000000000000000000e".HexToByteArray());
		var jobject = output.ConvertToJObject();

		Console.WriteLine(jobject.ToString());
	}	
}

```

**Comment by foued1979** [comment]
Thanks - I will have a look.  I assume that a conversion occurs when parameters are created using GetContract; conversion doesn't occur when I dynamically create the parameters and attach "my" ABI to the Nethereum contract.ABI class. The initial error i was getting (in the decoder) was "cannot dynamically create instance of System.String[]"; which is due to the fact that size of array must be specified with the Activator.CreateInstance (or the Array.CreateInstance). But then, when using the size of the parameter to create the array, I was confronted to the fixed size and therefore the impossibility to use Add => I changed the code to create instance of List and then convert the list to Array.

This is how I create the contractABI; abi that I attach to the new Contract(new RPC.EthApiService(web3.Client), typeof(AbiModel.ContractABI), contractId).ContractBuilder.ContractABI:


var abiContract = new ContractABI();
var abiFunctions = new List<FunctionABI>();

foreach (var function in listOfFunctions)
{
    var functionAbi = new FunctionABI(function.Name, function.Constant);
    var newAliases = new SortedDictionary<string, string>();
    var inputParameters = new List<EthAbi.Parameter>();
    var outputParameters = new List<EthAbi.Parameter>();

    if (function.InputParameters != null)
        foreach (var parameter in function.InputParameters)
        {
			var inputParam = new EthAbi.Parameter(parameter.Type, parameter.Name, parameter.Order);

			if (parameter.Type == "tuple")
            {
				var component = StructuresDef.Structures.First(c => c.Name == parameter.ComponentName);
				var tupleParameters = new List<EthAbi.Parameter>();

				foreach (var componentParameter in component.Parameters)
				{
					tupleParameters.Add(new EthAbi.Parameter(componentParameter.Type, componentParameter.Name, componentParameter.Order));
				}

                (inputParam.ABIType as TupleType)!.SetComponents(tupleParameters.ToArray()); 
			}

			inputParameters.Add(inputParam);
		}  


    if (function.OutputParameters != null)
        foreach (var parameter in function.OutputParameters)
        {
            outputParameters.Add(new EthAbi.Parameter(parameter.Type, parameter.Name, parameter.Order));
            if (!functionOutputAliases.ContainsKey(parameter.Name)) newAliases.Add(parameter.Name, parameter.Alias);
        }

    functionAbi.InputParameters = inputParameters.ToArray();
    functionAbi.OutputParameters = outputParameters.ToArray();

    abiFunctions.Add(functionAbi);
	
    if (function.FunctionType == "Other") functionNameMapping.Add(function.Name, function.Name);
    else functionNameMapping.Add(function.FunctionType, function.Name);

    functionOutputAliases.Add(function.Name, newAliases);


Events = listOfEvents.ToArray();
abiContract.Functions = abiFunctions.ToArray();
