### ISSUE TITLE
Question: Tests not all running

### ISSUE THREAD

**Issue by cicorias** [Nethereum/Nethereum#96]
I wanted to get a sanity check as I'm taking both last commit and commit at tag 1.0.4 and running the tests from within VS2015 or via xunit test runner and getting about 44 failures and 189 passing.

Are there steps you have that get a 100% pass or just not up2date on fixing all the tests after refactoring, etc.

Just wanted to know before I spend too much more time on getting 100% pass before making changes.

Thanks.

**Comment by juanfranblanco** [comment]
Some of them are specific to some client specific integration tests. Those just need to be refactored to be generic.

**Comment by juanfranblanco** [comment]
The generic geth client used is this https://github.com/Nethereum/Nethereum/tree/master/testchain with a configured chain using the batch file

**Comment by juanfranblanco** [comment]
The plan is to have a "fast" geth, mainly a geth instance that mines blocks every second. Which could be embedded in the same way as the TestRpc one https://github.com/Nethereum/Nethereum.TestRPCRunner

**Comment by juanfranblanco** [comment]
I have included now a "fast geth" on the testchain folder.  Also removed a couple of obsolete tests, and a couple of environment changes to make all test pass.  Use the batch file for RPC.

**Comment by cicorias** [comment]
Thanks for the fast response. I'll take a look in the morning as I'm in Australia for a few weeks.

This is great stuff btw. 

We are looking at adding some support for Quorom which is a fork of geth.

**Comment by juanfranblanco** [comment]
That is on my TODO list too. I was starting this week but was unsure if to refactor out Management tools from Geth and Parity first to specific projects. Ping me in Gitter to chat more about it if you want.

**Comment by juanfranblanco** [comment]
A side not on the issue, if using "fast geth" some of the tests will need to re-run as the nonces don't have time to catch up with the tests.
