### ISSUE TITLE
Transferring a Token from Wallet to Another Wallet

### ISSUE THREAD

**Issue by emin-karadag** [Nethereum/Nethereum#960]
Hello,
I want to send any token in my Metamask wallet to another wallet. Examples on the Internet are always given for the Ethereum network.
For example; Can and how can I send tokens on the BSC network or Avalanche network using the Nethereum library?
Thanks.

**Comment by juanfranblanco** [comment]
@emin-karadag you just change the url of your connection to point to the right public node for any compatible evm chain

**Comment by emin-karadag** [comment]
@juanfranblanco I understand. For example I need to use BSC url for BSC network. In this way, I can transfer BNB. However, I cannot transfer any X tokens in the BSC network.
This is exactly my problem.
I can also get a code sample if possible.
Thank you.
