### ISSUE TITLE
Nethereum conflicts with Netcode for GameObjects Package.

### ISSUE THREAD

**Issue by JamesW940516** [Nethereum/Nethereum#962]
## Expected Behavior
Both Nethereum and Netcode for GameObjects in one project without errors.

## Current Behavior
There are errors when I import Nethereum dlls and Netcode for GameObjects in one project.

## Steps to Reproduce
#1
Unity Version : 2022.3.4f1 (LTS)
Nethereum version : https://github.com/Nethereum/Nethereum/releases/download/4.14.0/net472UnityCommonAOT.zip

When I import the Nethereum package into an empty project, there is no error.
But when I build the project, following errors come out.
![image](https://github.com/Nethereum/Nethereum/assets/133299884/aa443de2-2685-4d1d-b17e-2e8fa71fe546)

#2
Unity Version : 2022.3.4f1 (LTS)
Nethereum version : https://github.com/Nethereum/Nethereum/releases/download/4.6.1/netStandardMinimalUnityAOT.zip

When I import the Nethereum package into an empty project, there is no error.
But when I build the project, following errors come out.
![image](https://github.com/Nethereum/Nethereum/assets/133299884/d9af53be-f338-4cea-94ff-95dc2e5f138e)

#3
Unity Version : 2022.1.5f1
Nethereum version : https://github.com/Nethereum/Nethereum/releases/download/4.6.1/netStandardMinimalUnityAOT.zip

When I import the Nethereum package into an empty project, there is no error.
When I build the project, there is no error again.
That was good to me. I thought I could change my unity editor version to 2022.1.5f1.
But when I import Netcode for GameObjects 1.5.1 into the project, errors come out, which are the same as above.

## Context (Environment)

I am making a MMO Web3 Game using Unity Netcode for GameObjects and Nethereum.
I just need to import both Netcode for GameObjects and Nethereum into one project, so that I can make a MMO Web3 game.

**Comment by juanfranblanco** [comment]
The first error indicates you need to add the Newtonsoft JSON library using the package manager. It seems that unity does not include it by default now.

**Comment by JamesW940516** [comment]
Thank you very much.

I imported com.unity.nuget.newtonsoft-json into project.
I resolved the issue #1 and got both packages into one project.
And could build IL2CPP LINUX Dedicated Game Server.

You saved my project.
Thank you again.
