### ISSUE TITLE
wallet_switchEthereumChain for MetaMask is not implemented

### ISSUE THREAD

**Issue by sunday-games** [Nethereum/Nethereum#968]
Thank you very much for your work! Please implement ApiMethods.wallet_switchEthereumChain for MetaMask same way as for example already implemented ApiMethods.wallet_addEthereumChain

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/HostWallet/WalletSwitchEthereumChain.cs

Although the pattern is to use this better (if it does not exist) https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/HostWallet/WalletAddEthereumChain.cs

**Comment by juanfranblanco** [comment]
![image](https://github.com/Nethereum/Nethereum/assets/562371/33a10b8b-be80-4c4b-aac3-693d670ad770)

**Comment by sunday-games** [comment]
> https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/HostWallet/WalletSwitchEthereumChain.cs
> 
> Although the pattern is to use this better (if it does not exist) https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.RPC/HostWallet/WalletAddEthereumChain.cs

This code is not in our version. I see that WalletSwitchEthereumChain was added much later than WalletAddEthereumChain. Apparently we just have an outdated version of the library. Thanks a lot!

**Comment by juanfranblanco** [comment]
Yes although as per MM documentation Add is a better option as it does both.
