### ISSUE TITLE
using IPC

### ISSUE THREAD

**Issue by tanderbold** [Nethereum/Nethereum#97]
Hi
I try to use ipc api by creating a web3
public static Web3 web3 = new Web3(new Nethereum.JsonRpc.IpcClient.IpcClient("geth.ipc"));

after I try to get accounts
var accs = Utils.web3.Personal.ListAccounts.SendRequestAsync().Result;

sometimes it throw exceptions (in half of cases)
EdjCase.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send ipc requests(s) ---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: {. Path '', line 2, position 0.
   в Newtonsoft.Json.JsonTextReader.Read()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в Nethereum.JsonRpc.IpcClient.IpcClient.<SendAsync>d__18`2.MoveNext()

what is wrong in my code?

**Comment by juanfranblanco** [comment]
Thanks for reporting this, I'll have a look at it. I assume the list of accounts is the same, and is the output from geth that varies, based on your comment.

**Comment by tanderbold** [comment]
can i avoid that with specify Newtonsoft.Json.JsonSerializerSettings ?

**Comment by juanfranblanco** [comment]
Looking at your error this might not be the issue, as the additional content is at line2. It seems that it has not received the whole response.

**Comment by tanderbold** [comment]
I use rpc client instead of ipc, and solved my troubles. It had not json exceptions. I mean problem in ipc client...

**Comment by juanfranblanco** [comment]
Thanks! Ill keep looking at the IPC issue

**Comment by juanfranblanco** [comment]
Closing and moving all the IPC to https://github.com/Nethereum/Nethereum/issues/55
