### ISSUE TITLE
Geth Unlock Account in latest version

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#99]
Reported:

var unlockAccountResult = await web3.Personal.UnlockAccount.SendRequestAsync(
address, password, new HexBigInteger(120));
and I get Exception : invalid argument 2: json: cannot unmarshal string into Go value of type uint64 ..so it can't convert password? I use geth 1.5.7
but when I used 1.5.6 and use the same function there're no problems!

**Comment by tanderbold** [comment]
I have this problem on 1.0.6 version Nethereum.RPC & Nethereum.Web3 with geth 1.5.8

**Comment by juanfranblanco** [comment]
You need to use a integer instead of HexBigInteger, it has changed.

**Comment by juanfranblanco** [comment]
It accepts HexBigInteger to support parity and previous versions.

**Comment by tanderbold** [comment]
Thanks, It works

**Comment by khuyenthuvn** [comment]
Thank you very much. It's worked
