### ISSUE TITLE
Serializing `bytes32`, then encoding from JSON does not work

### ISSUE THREAD

**Issue by MiniaczQ** [Nethereum/Nethereum#992]
Basic types, like bytes32 fail serialization to deserialization.

## Expected Behavior

The type should be correctly encoded after serialization.

## Current Behavior

When bytes32 type is serialized then encoded from json, exception is thrown.

## Possible Solution

---

## Steps to Reproduce

```cs
[Struct("Empty")]
class Empty
{
}

[Fact]
public void SerializeDeserialize()
{
var typedData = new TypedData<DomainWithSalt>
{
	Domain = new DomainWithSalt
	{
		Name = "a",
		Version = "b",
		ChainId = BigInteger.Parse("1"),
		VerifyingContract = EthECKey.GenerateKey().GetPublicAddress(),
		Salt = Convert.FromHexString("0567ba82f82338342c115e01e2461857ecefd0db574456d345ffb092d0273f67")
	},
	Types = MemberDescriptionFactory.GetTypesMemberDescription(typeof(DomainWithSalt), typeof(Empty)),
	PrimaryType = nameof(Empty)
};
typedData.SetMessage(new Empty());


var json = typedData.ToJson();
var typedDataRecovered = TypedDataRawJsonConversion.DeserialiseJsonToRawTypedData<DomainWithSalt>(json);
typedData.Should().BeEquivalentTo(typedDataRecovered);
}
```

yields
```An error occurred encoding abi value. Order: '1', Type: 'bytes32', Value: 'BWe6gvgjODQsEV4B4kYYV+zv0NtXRFbTRf+wktAnP2c='.  Ensure the value is valid for the abi type.```

## Context (Environment)

Sending TypedData over JSON API.

## Other
The `ToJson` seems to be the only 'working' serialization for `TypedData` I tried System.Text and Newtonsoft and they both seem to not work correctly.

**Comment by juanfranblanco** [comment]
Is that Salt a ByteArray?

**Comment by MiniaczQ** [comment]
I used `byte[]`, since that's what's in the provided [DomainWithSalt](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.ABI/EIP712/Domain.cs#L67)

**Comment by MiniaczQ** [comment]
From further experiments I found the reason is:
When I first create the object, I set it to a `byte[]` directly, but when it gets converted to JSON it becomes a string and then the deserializer is unable to turn the b64 representation back to `byte[]`

**Comment by juanfranblanco** [comment]
Yes it should be a hex string other formats are not valid

**Comment by MiniaczQ** [comment]
I tried 3 serializers, System.Text.Json has many problems, Newtonsoft is configured to only output the schema, so the only working  serializer I could find was the `ToJson` implemented in [TypedDataRawJsonConversion](https://github.com/Nethereum/Nethereum/blob/2ed8e5d0551d47b4ee6f86da8f5d2310b2735cd3/src/Nethereum.ABI/EIP712/TypedDataRawJsonConversion.cs#L19C74-L19C74)

**Comment by juanfranblanco** [comment]
You can only serialise this with Nethereum. How do you set that hash value? What is that Convert method?

**Comment by MiniaczQ** [comment]
What hash value? I don't do any hashing besides signing

This is the convert class, it just turns hex strings to bytes:
https://learn.microsoft.com/en-us/dotnet/api/system.convert.fromhexstring?view=net-5.0

**Comment by juanfranblanco** [comment]
Apologies typo, I meant salt, how do you get that encoded value ? That is incorrect. What does the JSON output look like?

**Comment by juanfranblanco** [comment]
Use the name extension HexToByteArray(), but most important what does the JSON look like when deserialising that input is not hex.

**Comment by juanfranblanco** [comment]
That is invalid it requires a hex value.

**Comment by MiniaczQ** [comment]
Yes and I have no control over that. The `ToJson` method converts `bytes[]` to base-64 instead of hex

**Comment by juanfranblanco** [comment]
Got you now, this is json.net doing its thing in the background. Ill fix that.

**Comment by juanfranblanco** [comment]
@MiniaczQ the fix should be out in the next release. Thanks for the issue and the explanation!
