### ISSUE TITLE
StreamingWebSocketClient.SendRequestAsync handled but not processed

### ISSUE THREAD

**Issue by CorrM** [Nethereum/Nethereum#997]
`StreamingWebSocketClient.SendRequestAsync` handled but not processed because of how `HexBigInteger` are serialized `HexRPCTypeJsonConverter<HexBigInteger, BigInteger>)`

the converter are write `HexValue` property which is something like that "0x10ff120d37d2d65ccd488244744efa695f160da2ee1a",
while in `StreamingWebSocketClient.HandleRequest` the request are queued in `_requests` like that `request.Id.ToString()` which returns "6359096680633240967060028056052355086296209982418458" its same as the hex value above BUT in `StreamingWebSocketClient.HandleResponse` response `RpcStreamingResponseMessage` are received from the websocket with id that sent by `SendRequestAsync` with id in hex format so `if (_requests.TryRemove(response.Id.ToString(), out handler))` will always `false`

## Expected Behavior
Response processed normally.

## Current Behavior
Response never processed.

## Possible Solution
- Write `HexValue` instead of `ToString()`  in `HexRPCTypeJsonConverter.WriteJson`.

## Steps to Reproduce
1. Instantiate `StreamingWebSocketClient`
2. Call `StartAsync`
3. Call `SubscribeAsync`

## Possible Workaround
```csharp
public sealed class RpcRequestMessageJsonConverter : JsonConverter<RpcRequestMessage>
{
    public override void WriteJson(JsonWriter writer, RpcRequestMessage value, JsonSerializer serializer)
    {
        writer.WriteStartObject();
        writer.WritePropertyName("id");
        writer.WriteValue(value.Id.ToString()); // Here the trick
        writer.WritePropertyName("jsonrpc");
        writer.WriteValue(value.JsonRpcVersion);
        writer.WritePropertyName("method");
        writer.WriteValue(value.Method);
        writer.WritePropertyName("params");
        writer.WriteStartArray();

        foreach (object parameter in (IEnumerable)value.RawParameters)
        {
            serializer.Serialize(writer, parameter);
        }

        writer.WriteEndArray();
        writer.WriteEndObject();
    }

    public override RpcRequestMessage ReadJson(JsonReader reader, Type objectType, RpcRequestMessage existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        return serializer.Deserialize<RpcRequestMessage>(reader);
    }
}
```
and in your `StreamingWebSocketClient`
```csharp
using var client = new StreamingWebSocketClient($"wss://mainnet.infura.io/ws/v3/{INFURA_API_KEY}");
client.JsonSerializerSettings.Converters.Add(new RpcRequestMessageJsonConverter());
```

**Comment by juanfranblanco** [comment]
There are two types of requests subscription and "normal" requests. Normal requests are identified as GUIDs and are not in hex format.

**Comment by juanfranblanco** [comment]
Example:
![image](https://github.com/Nethereum/Nethereum/assets/562371/28574e1e-2e41-4979-9f3a-12b116568a4b)
![image](https://github.com/Nethereum/Nethereum/assets/562371/ae85234a-a78a-476a-8c5c-700d11c78ca0)

**Comment by CorrM** [comment]
Here is the code that trigger the problem
```csharp
public partial class SwapEventDTO : SwapEventDTOBase { }

    [Event("Swap")]
    public class SwapEventDTOBase : IEventDTO
    {
        [Parameter("address", "sender", 1, true )]
        public virtual string Sender { get; set; }
        [Parameter("uint256", "amount0In", 2, false )]
        public virtual BigInteger Amount0In { get; set; }
        [Parameter("uint256", "amount1In", 3, false )]
        public virtual BigInteger Amount1In { get; set; }
        [Parameter("uint256", "amount0Out", 4, false )]
        public virtual BigInteger Amount0Out { get; set; }
        [Parameter("uint256", "amount1Out", 5, false )]
        public virtual BigInteger Amount1Out { get; set; }
        [Parameter("address", "to", 6, true )]
        public virtual string To { get; set; }
    }

private static async Task TestAsync()
    {
        var web3 = new Web3($"https://mainnet.infura.io/v3/{API_KEY}");

        Event<Pair.SwapEventDTO> swapEventHandler = web3.Eth.GetEvent<Pair.SwapEventDTO>("0x0d4a11d5EEaaC28EC3F61d100daF4d40471f1852");
        HexBigInteger filter = await swapEventHandler.CreateFilterAsync();

        using (var client = new StreamingWebSocketClient($"wss://mainnet.infura.io/ws/v3/{API_KEY}"))
        {
            var subscription = new EthLogsObservableSubscription(client);
            subscription.GetSubscriptionDataResponsesAsObservable().Subscribe(log =>
            {
            });
            
            subscription.GetSubscribeResponseAsObservable().Subscribe(id => Console.WriteLine($"Subscribed with id: {id}"));

            await client.StartAsync();
            await subscription.SubscribeAsync(filter);
            
            await Task.Delay(10000);

            await subscription.UnsubscribeAsync();
        }
    }
```

The problem:
![image](https://github.com/Nethereum/Nethereum/assets/5868825/170aa0a7-f023-4139-8719-7cf9ea975091)
![image](https://github.com/Nethereum/Nethereum/assets/5868825/e8d52633-3737-4aa4-8b72-2cf31bc530aa)

**Comment by juanfranblanco** [comment]
The issue is that you are passing as a parameter the "filterId" This method does not work like this.

It should be done this way:

![image](https://github.com/Nethereum/Nethereum/assets/562371/8baf19c5-4e8f-45b7-b993-2c1d983ba4c4)

As you can see here, you are actually passing as a parameter the request.Id , this identifies the rpc requests not the subscriptions.

![image](https://github.com/Nethereum/Nethereum/assets/562371/330d8bf4-fbc4-4e0d-8f7c-1344c3004b05)
